[[Adding_a_Satellite_6_Provider]]
= Adding a Satellite 6 Provider
To start provisioning bare metal machines, you need at least one Red Hat Satelllite 6 provider added to {product-title}.


. Navigate to menu:Configuration[Management].
. Select menu:Configuration[Add a new Provider].
. Enter a *Name* for the provider.
. Enter a *URL* for the provider. This is the root URL for the Satellite 6 server and can be either an IP address or a hostname. For example, _http://satellite6.example.com_.
. Select *Verify Peer Certificate* to use encrypted communication with the provider. This requires the *SSL certificates* from your Red Hat Satellite 6 provider.
. Enter a *Username* for a user on the provider. Ideally, this would be a user in Satellite 6 with administrative access.
. Enter a *Password*, and then enter it again in *Confirm Password*.
. Click *Validate* to test your connection with the Red Hat Satellite 6 server.
. Click *Add* to confirm your settings and save the provider.

{product-title} saves the Satellite 6 provider in its database and triggers a refresh of resources detected in the provider.






