[[amazon-provider-permissions]]

= Permissions for Amazon EC2 Providers

ifdef::cfme[]
Red Hat recommends using Amazon EC2's _Power User_ Identity and Access Management (IAM) policy when adding Amazon EC2 as a cloud provider in {product-title_short}.
This policy allows those in the _Power User_ group full access to AWS services except for user administration, meaning a {product-title_short} API user can access all of the API functionality, but cannot access or change user
permissions.
 
[NOTE]
====
When adding an Amazon EC2 provider in {product-title_short} with the intention to use the SmartState analysis feature, Red Hat recommends assigning _Admin_ group privileges.  For situations in which assigning the _Admin_ group is unacceptable, manually create an Amazon EC2 policy role using specific permissions. See xref:amazon-ec2-manual-role-creation[] for more information.
====
endif::cfme[]

Use Amazon EC2's _Power User_ Identity and Access Management (IAM) policy when adding Amazon EC2 as a cloud provider in {product-title_short}.
This policy allows those in the _Power User_ group full access to AWS services except for user administration, meaning a {product-title_short} API user can access all of the API functionality, but cannot access or change user
permissions.
 
[NOTE]
====
When adding an Amazon EC2 provider in {product-title_short} with the intention to use the SmartState analysis feature, assign _Admin_ group privileges.  For situations in which assigning the _Admin_ group is unacceptable, manually create an Amazon EC2 policy role using specific permissions. See xref:amazon-ec2-manual-role-creation[] for more information.
====

Further limiting API access limitations can limit Automate capabilities, as Automate
scripts directly access the AWS SDK to create brand new
application functionality.

The AWS services primarily accessed by the {product-title_short} API include:

* Elastic Compute Cloud (EC2)
* CloudFormation
* CloudWatch
* Elastic Load Balancing
* Simple Notification Service (SNS)
* Simple Queue Service (SQS)

[[amazon-ec2-manual-role-creation]]
== Manually Creating an Amazon EC2 Role

include::Amazon_EC2_Manual_Role_Creation.adoc[]







