= Authenticating to Microsoft SCVMM

You must enable WinRM to listen for HTTP traffic on Microsoft SCVMM servers in order for CloudForms Management Engine to establish a connection.
You must also set the appropriate execution policy on the SCVMM server to allow PowerShell scripts from the appliance to run remotely. 

[IMPORTANT]
======
Support for Microsoft SCVMM is in Technology Preview.
======
See link:https://access.redhat.com/support/offerings/techpreview/[Technology Preview Features Support Scope]. 

. Log in to the Microsoft SCVMM server and enable WinRM for configuration.
+
----
winrm quick config
----			
+
. Set the following options:  
+
----
winrm set winrm/config/client/auth @{Basic="true"}
winrm set winrm/config/service/auth @{Basic="true"}
winrm set winrm/config/service @{AllowUnencrypted="true"}
----			
+
. For Windows 2012 R2 with PowerShell 4.0, use the following syntax to set these options:  
+
----
winrm set winrm/config/client/auth '@{Basic="true"}'
winrm set winrm/config/service/auth '@{Basic="true"}'
winrm set winrm/config/service '@{AllowUnencrypted="true"}'
----			
+
. Enable remote script execution on the SCVMM server using the +Set-ExecutionPolicy+ cmdlet.
+
----
Set-ExecutionPolicy RemoteSigned
----
+
For more information on SCVMM remote script execution policies, see link:http://technet.microsoft.com/en-us/library/ee176961.aspx[Using the Set-ExecutionPolicy Cmdlet]. 

If PowerShell returns an error, search for `log_dos_error_results` in the `evm.log` and `scvmm.log` files for information. 

