[[configuration_management_providers]]
= Configuration Management Providers

In {product-title_short}, a configuration management provider is a systems management product that you can add to a {product-title_short} appliance to manage the lifecycle of your resources. Configuration management providers are useful for uniformly applying changes and updates across providers, and for recording and reporting status and change activity. They can also help eliminate the confusion and error brought about by the existence of different providers. 

This chapter describes the different types of configuration management providers available to {product-title_short}, and how to manage them. Configuration management providers must be added individually to {product-title_short}.


[[red-hat-satellite-6]]
== Red Hat Satellite 6

Satellite 6 is a subscription and system management tool that provides a way to provision hosts (both virtual and bare metal) and configure them using a set of Puppet modules. {product-title} provides functionality to integrate with a Red Hat Satellite 6 server and take advantage of its features. This includes:

* Monitoring the inventory of your Red Hat Satellite 6 server, including independent hosts and hosts provisioned using hostgroups.
* Reprovisioning existing bare metal system hosts to new host groups.
* Applying {product-title} policy tags to hosts.

[IMPORTANT]
====
{product-title} only reprovisions existing systems in a Red Hat Satellite 6 environment. Provisioning systems from Red Hat Satellite 6's bare metal discovery service is planned for a future release.
====

:leveloffset: 3 
include::Defining_the_Workflow.adoc[]

:leveloffset: 3
include::Defining_the_Hostgroup_Hierarchy.adoc[]

:leveloffset: 3
include::Adding_a_Satellite_6_Provider.adoc[]

:leveloffset: 3
include::Triggering_a_Refresh_of_a_Satellite_6_Provider.adoc[]

:leveloffset: 3
include::Displaying_Red_Hat_Satellite_6_Contents.adoc[]

:leveloffset: 3
include::Reprovisioning_a_Bare_Metal_Host.adoc[]

:leveloffset: 3
include::Tagging_a_Bare_Metal_Host.adoc[]




