= Containers Providers

A containers provider is a service that manages container resources, and can be added to the {product-title} appliance.

{product-title} can connect to OpenShift Container Platform containers providers and manage them similarly to infrastructure and cloud providers. This allows you to gain control over different aspects of your environment and answer questions, such as:

* How many containers exist in my environment?
* Does a specific node have enough resources?
* How many distinct images are used?
* Which image registries are used?

When {product-title} connects to a container's environment, it collects information on different areas of the environment:

* Entities such as pods, nodes, or services.
* Basic relationships between the entities, for example: Which services are serving which pods?
* Advanced insight into relationships, for example: Which two different containers are using the same image?
* Additional information, such as events, projects, routes, and metrics.

You can manage policies for containers entities by adding tags. All containers entities except volumes can be tagged.


:leveloffset: 2
[[Obtaining_OpenShift_Container_Platform_Management_Token]]
= Obtaining an OpenShift Container Platform Management Token

When deploying OpenShift Enterprise using `openshift-ansible-3.0.20` (or later versions), the OpenShift Container Platform link:https://docs.openshift.com/container-platform/latest/admin_guide/service_accounts.html[service account] and link:https://docs.openshift.com/container-platform/latest/admin_guide/manage_authorization_policy.html[roles] required by {product-title} are installed by default.

[NOTE]
====
See the link:https://docs.openshift.com/container-platform/latest/architecture/additional_concepts/authorization.html#roles[OpenShift Container Platform documentation] for a list of the default roles.
====

To obtain the token to use for the provider definition, follow the instructions below for your OpenShift Container Platform version.


[[obtaining-a-management-token-in-openshift-container-platform]]
== Obtaining a Management Token in OpenShift Container Platform 3.3 and Later

include::../common/provider-ocp-mgt-token.adoc[]


[[obtaining-a-management-token-in-openshift-enterprise-3.2]]
== Obtaining a Management Token in OpenShift Enterprise 3.2

include::../common/provider-ose-mgt-token-3_2.adoc[]


[[obtaining-a-management-token-in-openshift-enterprise-3.1]]
== Obtaining a Management Token in OpenShift Enterprise 3.1

include::../common/provider-ose-mgt-token-3_1.adoc[]


:leveloffset: 2
= Enabling OpenShift Cluster Metrics

Use the OpenShift Cluster Metrics plug-in to collect node, pod, and container metrics into one location. This helps track usage and find common issues.

* Configure {product-title} to allow for all three https://access.redhat.com/documentation/en/red-hat-cloudforms/4.1/deployment-planning-guide/#assigning_the_capacity_and_utilization_server_roles[*Capacity & Utilization* server roles].

* Enable cluster metrics using the https://access.redhat.com/documentation/en-us/openshift_container_platform/3.5/html-single/installation_and_configuration/#install-config-cluster-metrics[OpenShift Enterprise documentation].

:leveloffset: 2
include::Adding_an_OpenShift_Provider.adoc[]


:leveloffset: 2
include::Tagging_Containers_Providers.adoc[]


:leveloffset: 2
include::Removing_Containers_Providers.adoc[]


:leveloffset: 2
include::Editing_a_Containers_Provider.adoc[]


:leveloffset: 2
include::Viewing_a_Containers_Providers_Timeline.adoc[]


:leveloffset: 2
include::Managing_Containers.adoc[]




