= Containers Providers

A containers provider is a service that manages container resources, and can be added to the {product-title} appliance.

The menu:Compute[Containers] area has options to add and manage containers providers. This includes the *Providers* page, which displays all discovered or added containers providers.

{product-title} supports adding OpenShift Enterprise as a containers provider.


:leveloffset: 2
[[Obtaining_OpenShift_Enterprise_Management_Token]]
= Obtaining an OpenShift Enterprise Management Token

When deploying OpenShift Enterprise using `openshift-ansible-3.0.20` (or later versions), the service account and roles required by {product-title} are installed by default.

To obtain the token to use for the provider definition, follow the instructions below for your OpenShift Enterprise version.

== Obtaining a Management Token in OpenShift Enterprise 3.2

include::../common/provider-ose-mgt-token-3_2.adoc[]

This command provides the token needed to add an OpenShift Enterprise provider.


== Obtaining a Management Token in OpenShift Enterprise 3.1

include::../common/provider-ose-mgt-token-3_1.adoc[]

This command provides the token needed to add an OpenShift Enterprise provider.

:leveloffset: 2
= Configuring OpenShift Metrics

To collect the node, pod, and container metrics, you must run the OpenShift Metrics services inside your cluster. For more information, see the https://access.redhat.com/documentation/en/openshift-enterprise/version-3.1/installation-and-configuration/#enabling-cluster-metrics[Enabling Cluster Metrics] in _OpenShift Enterprise Installation and Configuration_.

[NOTE]
======
include::../common/cap-util-note-metrics-collection.adoc[]
======

:leveloffset: 2
include::Adding_an_OpenShift_Provider.adoc[]


:leveloffset: 2
include::Tagging_Containers_Providers.adoc[]


:leveloffset: 2
include::Removing_Containers_Providers.adoc[]


:leveloffset: 2
include::Editing_a_Containers_Provider.adoc[]


:leveloffset: 2
include::Viewing_a_Containers_Providers_Timeline.adoc[]


:leveloffset: 2
include::Managing_Containers.adoc[]



