[[amazon-provider-aws-events]]
= Enabling Amazon EC2 Events

After adding an Amazon EC2 provider and configuring an SNS topic in xref:amazon-provider-aws-config-notifications[], create a CloudTrail, then configure CloudWatch rules on your EC2 provider to automatically get events in {product-title_short} for monitoring the provider.

[NOTE]
====
The following procedures are accurate at time of publishing. See the https://docs.aws.amazon.com/awscloudtrail/latest/userguide/[Amazon AWS documentation] for further details on these steps.
====

== Creating a CloudTrail

In the CloudTrail area of the AWS Management Console, create a trail and an S3 bucket:

. Create a *Trail* with a custom name.
. (Optional) If you want to apply the trail to all of your {product-title_short} regions, select *Yes* for *Apply trail to all regions*.
. For *Management Events*, select *Read/Write events: All*.
. Create a new S3 bucket.


== Creating CloudWatch Rules Based on Event Patterns

In the CloudWatch area of the AWS Management Console, create three rules: one rule each for EC2, volumes, and snapshots.

[IMPORTANT]
====
When an SNS topic is deleted and recreated (manually or by {product-title_short}), CloudWatch rules must be recreated as well, even though the SNS target topic for CloudWatch rules appears to be assigned to these rules.
The CloudWatch rule does not send events to this recreated topic until it is recreated too.
====

To create a CloudWatch rule for EC2:

. Navigate to menu:Events[Rules] and click *Create rule*.
. Select the *Event Pattern* radio button to specify the event source.
. Edit the *Event Pattern Preview* box, and paste and save the following code to create a rule based on a custom event pattern:
+
----
{
  "source": [
    "aws.ec2"
  ],
  "detail-type": [
    "AWS API Call via CloudTrail"
  ],
  "detail": {
    "eventSource": [
      "ec2.amazonaws.com"
    ]
  }
}
----
+
. Click *Add target* and specify the following attributes:
* *Type*: `SNS Topic`
* *Topic*: `AWSConfig_topic`
* *Input*: `Matched event`
. Click *Configure Details* to save these details.
. Configure a name and description for the rule if desired. Ensure the *Enabled* checkbox is selected for *State*.
. Click *Create Rule* to save the CloudWatch rule.

Repeat the same procedure to create a CloudWatch rule for volumes, pasting the code snippet below to the *Event Pattern Preview* box:

. Navigate to menu:Events[Rules] and click *Create rule*.
. Select the *Event Pattern* radio button to specify the event source.
. Edit the *Event Pattern Preview* box, and paste and save the following code to create a rule based on a custom event pattern:
+
----
{
  "source": [
    "aws.ec2"
  ],
  "detail-type": [
    "EBS Volume Notification"
  ]
}
----
+
. Click *Add target* and specify the following attributes:
* *Type*: `SNS Topic`
* *Topic*: `AWSConfig_topic`
* *Input*: `Matched event`
. Click *Configure Details* to save these details.
. Configure a name and description for the rule if desired. Ensure the *Enabled* checkbox is selected for *State*.
. Click *Create Rule* to save the CloudWatch rule.


Repeat the same procedure to create a CloudWatch rule for snapshots, pasting the code snippet below to the *Event Pattern Preview* box:

. Navigate to menu:Events[Rules] and click *Create rule*.
. Select the *Event Pattern* radio button to specify the event source.
. Edit the *Event Pattern Preview* box, and paste and save the following code to create a rule based on a custom event pattern:
+
----
{
  "source": [
    "aws.ec2"
  ],
  "detail-type": [
    "EBS Snapshot Notification"
  ]
}
----
+
. Click *Add target* and specify the following attributes:
* *Type*: `SNS Topic`
* *Topic*: `AWSConfig_topic`
* *Input*: `Matched event`
. Click *Configure Details* to save these details.
. Configure a name and description for the rule if desired. Ensure the *Enabled* checkbox is selected for *State*.
. Click *Create Rule* to save the CloudWatch rule.

EC2 can now automatically refresh events in {product-title_short}.

