[[enabling_public_amis_from_amazon_ecs2]]
= Enabling Public AMIs from Amazon EC2

By default, public AMIs from an Amazon EC2 provider are not viewable in {product-title}. To make these images viewable, you must edit the main configuration file for the appliance.

[NOTE]
====
Syncing all public images may require additional memory resources. Also, bear in mind that syncing happens in each configured Amazon EC2 provider, which will require a similar amount of total memory resources.
====

. Navigate to menu:Settings[Settings > Configuration > Zone > Advanced].
. Select the configuration file to edit from the *File* list. If not already automatically selected, select *EVM Server Main Configuration*.
. Set the *get_public_images* parameter:
.. Set the parameter to *get_public_images: true* to make public images viewable.
.. Set the parameter to *get_public_images: false* to make public images not viewable.
. Optionally, configure an array of filters in *public_images_filters* to restrict which images are synced.
See http://docs.aws.amazon.com/sdkforruby/api/Aws/EC2/Client.html#describe_images-instance_method for more details.

