[[manageiq-automate-role]]

=== Modifying the Automate Workspace Using the `manageiq-automate` Role. 

The `manageiq-automate` role allows users of {product-title} Automate to modify and add to the automate workspace via an Ansible playbook. 

[NOTE]
====
When using this role in a playbook on a {product-title} appliance, add an empty roles directory at the root of the playbook. In the roles directory, include a requirements.yml file with the following contents:

-----
---
- src: syncrou.manageiq-automate
-----
====

==== Role Variables

The `manageiq_automate` role employees the following variables when implemented in a playbook run on a {product-title_short} appliance. Variables are defined in `defaults/main.yml` and `vars/main.yml`.

|Name|Default|Description|
|----|--------|-----------|
|`auto_commit`|`True`|If set to False it will not auto commit back to ManageIQ each call to a set_ method in the manageiq_automate module.|
|`manageiq_validate_certs`|`True`|If set to False in the manageiq_connection dictionary or passed in via extra_vars or assigned in the playbook vars then the lookup will allow self signed certificates to be used when using SSL REST API connection urls.|




Use the `manageiq-automate`role by following the steps below:

==== Install the `manageiq-automate` role. 

. ssh into the {product-title_short} appliance as `root`. 
+
------
ssh root@<hostname>.com
------
+
. Install the role using the `ansible galaxy` command.
+
-----
ansible-galaxy install syncrou.manageiq-automate 
-----

==== Example Playbook

The example below uses variable substitution, setting tasks to retrieve the list of method parameters which are used to modify object attributes. A final task uses the `set_retry` module to update the retry interval. 
-----
- name: Siphon Method Parameters into an object
  hosts: localhost
  connection: local
  vars:
  - auto_commit: True
  - object: root
  - interval: 600
  # Only needed if this playbook is NOT run on a ManageIQ Appliance
  - manageiq_connection:
        url: 'http://localhost:3000'
        username: 'admin'
        password: 'password'
        automate_workspace: 'automate_workspaces/1234'
        manageiq_validate_certs: false

  gather_facts: False
  roles:
  - syncrou.manageiq-automate

  tasks:
    - name: "Get the list of Method Parameters"
      manageiq_automate:
        workspace: "{{ workspace }}"
        get_method_parameters: yes
      register: method_params

    - name: "Set attributes"
      manageiq_automate:
        workspace: "{{ workspace }}"
        set_attributes:
          object: "{{ object }}"
          attributes: "{{ method_params.value }}"

    - name: Set Retry
      manageiq_automate:
        workspace: "{{ workspace }}"
        set_retry:
          interval: "{{ interval }}"
-----