[[network_providers]]
= Network Managers

In {product-title}, a network manager is an inventory of networking entities on existing cloud and infrastructure providers managed by your {product-title_short} appliance.

This provider type exposes software-defined networking (SDN) providers including _OpenStack Network (Neutron)_, _Azure Network_, and _Amazon EC2 Network_, which enables software-defined networking inventory collection. The OpenStack Network provider collects inventory of floating IPs from OpenStack so that IPs can be allocated without querying OpenStack database every time. Also, it refreshes all Neutron data from both OpenStack and OpenStack Infrastructure, and extracts the Neutron logic to a shared place. Note that management via the network providers configuration is currently disabled.

This chapter describes the different types of network managers available to {product-title_short}, and how to manage them. Network managers are discovered automatically by {product-title_short} from other connected providers. 

:leveloffset: 2
include::Adding_Viewing_Network_Providers.adoc[]


:leveloffset: 2
include::Refreshing_Network_Providers.adoc[]


:leveloffset: 2
include::Tagging_Network_Providers.adoc[]


:leveloffset: 2
include::Removing_Network_Providers.adoc[]


:leveloffset: 2
include::Viewing_Network_Providers_Timeline.adoc[]


You can also assign policy profiles to network providers, or remove them. The method for doing so is similar to that of any normal policy profile. 
ifdef::cfme[See https://access.redhat.com/documentation/en/red-hat-cloudforms/4.7/policies-and-profiles-guide/#assigning_policy_profiles_to_a_network_provider[Assigning Policy Profiles to a Network Provider] and https://access.redhat.com/documentation/en/red-hat-cloudforms/4.7/policies-and-profiles-guide/#removing_policy_profiles_from_a_network_provider[Removing Policy Profiles from a Network Provider] in the _Policies and Profiles Guide_.]

:leveloffset: 2
include::Network_Topology.adoc[]










