[[RH-Cloud-Integration]]
= Integration with Red Hat Cloud

Using {product-title_short} as a cloud manager for Red Hat Cloud, you can:

* Manage on-premises private cloud combined with software-as-a-services.
* Collect and send data to the Insights Platform to be consumed by applications.

Connect to the software-as-a-service offerings at cloud.redhat.com and synchronize {product-title_short} for selected providers to cloud services.

== Connecting to cloud.redhat.com Services

You can register the appliance with insights, and connect to cloud.redhat.com to manage your Red Hat insfrastructure in the cloud.

. Navigate to menu:Red Hat Cloud[Services].
. Click *Take me there*.


== Synchronizing Providers

To synchronize all of your {product-title_short} data to Red Hat Cloud Services:

. Navigate to menu:Red Hat Cloud[Providers].
. Click *Synchronize this Platform to Cloud*.

To synchronize selected providers to Red Hat Cloud Services:

. Navigate to menu:Red Hat Cloud[Providers]. 
. Select the providers you want to synchronize, then click *Connect to Red Hat Cloud Services*. This will push data for selected providers to Red Hat Cloud services. 

Note that you can filter the list of providers by name and type. 
