[[storage_managers]]
= Storage Managers

//NEED IMPROVED DEFINITION.
In {product-title}, a storage manager is a service providing storage resources that you can manage from a {product-title} appliance. This chapter describes the different types of storage managers used by {product-title}, and how to manage them.

Two types of storage managers are currently available to {product-title}: OpenStack Cinder and OpenStack Swift, which manage physical and software-defined storage. These storage managers are discovered automatically by {product-title} after adding an OpenStack cloud provider.


:leveloffset: 2
= OpenStack Cinder Managers

Cinder is an OpenStack service that provides and manages persistent block storage resources that OpenStack Compute instances can consume.

To use OpenStack Cinder as a storage manager, you must first add an OpenStack cloud provider to your {product-title} appliance and enable events. The Cinder service will be automatically discovered by CloudForms and added to the *Storage Managers* list in {product-title}. See xref:adding_openstack_cloud_providers[] for instructions on adding a cloud provider and enabling events.



:leveloffset: 3
include::Viewing_a_Cinder_Manager_Timeline.adoc[]

:leveloffset: 3
include::Creating_Cloud_Volumes_on_Cinder.adoc[]

:leveloffset: 3
include::Creating_a_Cinder_Backup.adoc[]

:leveloffset: 3
include::Restoring_from_a_Cinder_Backup.adoc[]

:leveloffset: 3
include::Creating_a_Cinder_Volume_Snapshot.adoc[]

:leveloffset: 3
include::Attaching_Cinder_Volumes.adoc[]

:leveloffset: 3
include::Detaching_Cinder_Volumes.adoc[]

:leveloffset: 3
include::Editing_Cinder_Volumes.adoc[]

:leveloffset: 3
include::Deleting_Cinder_Volumes.adoc[]



:leveloffset: 2
= OpenStack Swift Managers

Swift is an OpenStack service that provides cloud object storage.

To use OpenStack Swift as a storage manager, you must first add an OpenStack cloud provider to your {product-title} appliance and enable events. The Swift service will be automatically discovered by CloudForms and added to the *Storage Managers* list in {product-title}. See xref:adding_openstack_cloud_providers[] for instructions on adding a cloud provider and enabling events.

:leveloffset: 3
include::Viewing_Swift_Object_Stores.adoc[]





