[[storage_managers]]
= Storage Managers

In {product-title}, a storage manager is a service providing storage resources that you can manage from a {product-title} appliance. This chapter describes the different types of storage managers used by {product-title}, and how they are added to {product-title}.

There are three types of storage managers currently available to {product-title}: 

* Amazon Elastic Block Store
* OpenStack Block Storage (`openstack-cinder`) 
* OpenStack Object Storage (`openstack-swift`)

:leveloffset: 2
= Amazon Elastic Block Store Managers

The Amazon Elastic Block Store service provides and manages persistent block storage resources that Amazon EC2 instances can consume.

To use the Amazon Elastic Block Store service as a storage manager, you must first add an Amazon EC2 cloud provider to your {product-title} appliance. The Amazon Elastic Block Store service is automatically discovered by {product-title}, and added to the *Storage Managers* list. See xref:adding-amazon-ec2-providers[] for instructions on adding an Amazon EC2 cloud provider.

ifdef::cfme[]
[NOTE]
====
For information on managing the inventory available to Amazon Elastic Block Store managers, see https://access.redhat.com/documentation/en-us/red_hat_cloudforms/4.7/html-single/managing_infrastructure_and_inventory/#volumes[Volumes] in the _Managing Infrastructure and Inventory_ guide.
====
endif::cfme[]


:leveloffset: 2
= OpenStack Block Storage Managers

The OpenStack Block Storage service (`openstack-cinder`) provides and manages persistent block storage resources that OpenStack infrastructure instances can consume.

To use OpenStack Block Storage as a storage manager, you must first add an OpenStack cloud provider to your {product-title} appliance and enable events. The Block Storage service will be automatically discovered by {product-title} and added to the *Storage Managers* list in {product-title}. See xref:adding_openstack_cloud_providers[] for instructions on adding a cloud provider and enabling events.

ifdef::cfme[]
[NOTE]
====
For information on managing the inventory available to OpenStack Block Storage managers, see https://access.redhat.com/documentation/en-us/red_hat_cloudforms/4.7/html-single/managing_infrastructure_and_inventory/#volumes[Volumes] in the _Managing Infrastructure and Inventory_ guide.
====
endif::cfme[]

:leveloffset: 3
= OpenStack Block Storage Manager Targeted Refresh

{product-title} supports targeted refresh
of OpenStack Block Storage (Cinder) volumes. This functionality automatically pulls down 
new inventory data for an object when {product-title_short} receives an event from the
OpenStack provider. For example, if {product-title_short} receives a `volume.update.end`
event from Cinder, instead of refreshing the entire inventory, it performs a targeted refresh of the
volume referenced in the event.

:leveloffset: 2
= OpenStack Object Storage Managers

The OpenStack Object Storage (`openstack-swift`) service provides cloud object storage.

To use the OpenStack Object Storage service as a storage manager, you must first add an OpenStack cloud provider to your {product-title} appliance and enable events. The Object Storage service will be automatically discovered by {product-title} and added to the *Storage Managers* list in {product-title}. See xref:adding_openstack_cloud_providers[] for instructions on adding a cloud provider and enabling events.

:leveloffset: 3
include::Viewing_Swift_Object_Stores.adoc[]










