[[storage_providers]]
= Storage Providers

In {product-title}, a storage provider is a virtual infrastructure environment that you can add to a {product-title} appliance to manage and interact with the resources in that environment. This chapter describes the different types of storage providers that you can add to {product-title}, and how to manage them. [REWORD]

There are two types of storage providers available to {product-title}: OpenStack Cinder and OpenStack Swift. Storage providers are discovered automatically by {product-title} after adding an OpenStack cloud provider (check fact - link to that section).

The web interface uses virtual thumbnails to represent providers. Each thumbnail contains four quadrants by default, which display basic information about each provider.


:leveloffset: 2
= OpenStack Cinder Providers

Cinder is block storage service
Openstack docs - persistent block storage resources that OpenStack Compute instances can consume.
Block storage needed for storing virtual machines and their data
Cinder is the openstack component which 
(BKGD - reword) Cinder is the OpenStack component that provides access to, and manages, block storage. To OpenStack hosts, the storage appears as a block device that uses iSCSI, Fibre Channel, NFS or a range of other proprietary protocols for back-end connectivity.St

To use Openstack Cinder as a storage provider, add OpenStack as a cloud provider -- the Cinder component will be automatically discovered by CloudForms and added to the Storage Providers list. See xref:adding_openstack_cloud_providers[] for instructions.


:leveloffset: 3
include::Viewing_a_Cinder_Provider_Timeline.adoc[]

:leveloffset: 3
include::Creating_Cloud_Volumes_on_Cinder.adoc[]

:leveloffset: 3
include::Attaching_Cinder_Volumes.adoc[]

:leveloffset: 3
include::Detaching_Cinder_Volumes.adoc[]

:leveloffset: 3
include::Deleting_Cinder_Volumes.adoc[]



:leveloffset: 2
= OpenStack Swift Providers






