After deploying the appliance, log in with the root password `smartvm`. If you deployed the appliance as a virtual machine, you can log in through `virsh`:

[literal,subs="+quotes"]
-----------
[root@kvm-host ~]# **virsh console my-cfme**
Connected to domain my-cfme
**...**
Welcome to the CFME Virtual Appliance.

You can browse to http://localhost.localdomain/

Red Hat Enterprise Linux Server 7.2 (Maipo)
Kernel 3.10.0-327.36.1.el7.x86_64 on an x86_64
localhost login: root
Password: 
Last login: Thu Oct 13 23:03:53 on tty2
Welcome to the Appliance Console

For a menu, please type: appliance_console
[root@localhost ~]# 
-----------

[[configuring_general_appliance_settings]]
=== Configuring General Appliance Settings

include::common/configuration-advanced.adoc[]

[[configuring_a_database]]
=== Configuring a Database for {product-title}

{product-title} supports the use of an internal or external database. The following instructions are suitable for configuring an _internal_ database. For instructions on how to configure an external database instead, see https://access.redhat.com/documentation/en/red-hat-cloudforms/4.1/single/installing-red-hat-cloudforms-on-red-hat-enterprise-linux-openstack-platform#configuring_an_external_database[Configuring an External Database].

include::common/configuration-db.adoc[]

=== Configuring General {product-title} Settings

After configuring the general settings for the appliance and creating a database for it, you can now launch {product-title}. To do this, use the *Start EVM Server Processes* option from the appliance console (xref:configuring_general_appliance_settings[]). Once you launch {product-title}, note the *Hostname* and *IP Address* displayed on the appliance console screen. 

Open the {product-title} web-based user interface by accessing either *Hostname* and *IP Address* on a web browser. At the login screen, use the following credentials:

* Username: *admin*
* Password: *smartvm*

[NOTE]
============
You can also change the password of the *admin* account from the login screen. To do so, click the *Update Password* link.
============

You can access and configure most {product-title} settings through the *Configuration* menu. You can access this menu through *Administrator | EVM* > *Configuration*. 

include::common/configuration-gui.adoc[]

ifdef::cfme[]
[[registering-appliances]]
=== Registering Your Appliance

include::common/configuration-register-appliance.adoc[]

[[Updating_Appliances]]
==== Updating Your Appliance

include::common/configuration-update-appliance.adoc[]
endif::cfme[]

=== Configuring {product-title_short} Metrics for SmartState Analysis

You can also configure {product-title_short} to perform a _SmartState Analysis_. This type of analysis collects details such as accounts, drivers, network information, hardware, and security patches on assets managed by the OpenStack provider. Enabling SmartState Analysis involves two steps:

. xref:cf-caputils[], and 
. xref:cf-smartproxy[]

These steps are required to allow {product-title_short} to collect metrics from OpenStack and use them to perform a SmartState analysis. You can choose different servers to perform either function; the following sections assume that you will.


[[cf-caputils]]
==== Configuring {product-title_short} Capacity and Utilization

include::common/cap-util-note-metrics-collection.adoc[]

// https://access.redhat.com/documentation/en/red-hat-cloudforms/4.1/managing-providers/#configuring_openshift_metrics

To enable these server roles:

include::common/cap-util-assign-server-roles.adoc[]

For more information, see https://access.redhat.com/documentation/en/red-hat-cloudforms/4.1/deployment-planning-guide/#capacity_and_utilization_collection[Capacity and Utilization Collection] from the _Deployment Planning Guide_.

[[cf-smartproxy]]
==== Enabling SmartState Analysis

include::common/smartstate.adoc[]
