After deploying the appliance, log in with the root password `smartvm`. If you deployed the appliance as a virtual machine, you can log in through `virsh`:

[literal,subs="+quotes"]
-----------
[root@kvm-host ~]# **virsh console my-cfme**
Connected to domain my-cfme
**...***
Welcome to the CFME Virtual Appliance.

You can browse to http://localhost.localdomain/

Red Hat Enterprise Linux Server 7.2 (Maipo)
Kernel 3.10.0-327.36.1.el7.x86_64 on an x86_64
localhost login: root
Password: 
Last login: Thu Oct 13 23:03:53 on tty2
Welcome to the Appliance Console

For a menu, please type: appliance_console
[root@localhost ~]# 
-----------

[[configuring_general_appliance_settings]]
=== Configuring General Appliance Settings

include::common/configuration-advanced.adoc[]

[[configuring_a_database]]
=== Configuring a Database for {product-title}

{product-title} supports the use of an internal or external database. The following instructions are suitable for configuring an _internal_ database. For instructions on how to configure an external database instead, see https://access.redhat.com/documentation/en/red-hat-cloudforms/4.1/single/installing-red-hat-cloudforms-on-red-hat-enterprise-linux-openstack-platform#configuring_an_external_database[Configuring an External Database].

include::common/configuration-db.adoc[]

=== Configuring General {product-title} Settings

After configuring the general settings for the appliance and creating a database for it, you can now launch {product-title}. To do this, use the *Start EVM Server Processes* option from the appliance console (xref:configuring_general_appliance_settings[]). Once you launch {product-title}, note the *Hostname* and *IP Address* displayed on the appliance console screen. 

Open the {product-title} web-based user interface by accessing either *Hostname* and *IP Address* on a web browser. At the login screen, use the following credentials:

* Username: *admin*
* Password: *smartvm*

[NOTE]
============
You can also change the password of the *admin* account from the login screen. To do so, click the *Update Password* link.
============

You can access and configure most {product-title} settings through the *Configuration* menu. You can access this menu through *Administrator | EVM* > *Configuration*. 

include::common/configuration-gui.adoc[]


