
{product-title} can be installed on a number of virtualization platforms, such as https://access.redhat.com/documentation/en/red-hat-cloudforms/4.0/installing-cloudforms-on-vmware-vsphere/installing-cloudforms-on-vmware-vsphere[VMware vSphere], and https://access.redhat.com/documentation/en/red-hat-cloudforms/4.0/installing-cloudforms-on-red-hat-enterprise-virtualization/installing-cloudforms-on-red-hat-enterprise-virtualization[Red Hat Enterprise Virtualization]. This chapter describes how to install and configure {product-title} on _Red Hat OpenStack Platform_.

[[obtaining-the-appliance]]
=== Obtaining and Installing the {product-title} Appliance

First, download the appliance from the Red Hat Customer Portal:

include::common/cfme-obtaining-the-appliance.adoc[]

Afterwards, upload or install the appliance image as a virtual machine or instance on a supported virtualization environment or cloud provider. See the  https://access.redhat.com/documentation/en/red-hat-cloudforms/?category=installation%2520and%2520upgrade&version=4.2[Installation and Upgrade] section for information on different supported _{product-title}_ deployment methods.

Whichever deployment method you choose, ensure that _{product-title}_ is configured with connectivity to the OpenStack management network. 

[TIP]
=================
See https://access.redhat.com/documentation/en/red-hat-cloudforms/4.2/single/installing-red-hat-cloudforms-on-red-hat-enterprise-linux-openstack-platform/#uploading-the-appliance-on-openstack[Uploading the Appliance on OpenStack] for instructions on deploying _{product-title}_ as an instance on the overcloud.
=================

////////////////////
_{product-title}_ can be installed and configured in a few quick steps. After downloading the _{product-title}_ appliance from the Red Hat Customer Portal (xref:obtaining-the-appliance[]), the installation process takes you through the steps of uploading it to a supported virtualization environment or cloud provider.

NOTE: After installing the _{product-title}_ appliance, you must configure the database for {product-title}. See xref:configuring_a_database[].

[[obtaining-the-appliance]]
=== Obtaining and Deploying the {product-title} Appliance

include::common/cfme-obtaining-the-appliance.adoc[]

=== Deploying the Appliance as a Virtual Machine

Upon obtaining the {product-title} appliance, deploy it in a network where it can communicate with the OpenStack management network. 

You can deploy the appliance on bare metal or as a virtual machine.

To deploy the appliance as a virtual machine, perform the following steps:


include::common/cfme-install-appliance-as-vm.adoc[]
////////////////////
