[id='Infrastructure_migration_solution_overview']
= Infrastructure Migration Solution overview

The Red Hat Infrastructure Migration Solution (IMS) enables you to migrate virtual machines from VMware 5.5 (and later) to the following target environments:

* Red Hat Virtualization 4.2
+
Red Hat Virtualization (RHV) is a virtualization platform built on Red Hat Enterprise Linux. You can manage your virtual infrastructure, including hosts, virtual machines, networks, storage, and users, from a centralized graphical user interface or with a REST API. (For more information, see the link:https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.2/[Red Hat Virtualization documentation].)

* Red Hat OpenStack Platform 13
+
Red Hat OpenStack Platform enables you to create a scaleable, fault-tolerant, private or public cloud based on Red Hat Enterprise Linux. (For more information, see the link:https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/13/[Red Hat OpenStack Platform documentation].)
Note

The migration process is performed with CloudForms 4.7, a user interface for managing the infrastructure. (For more information, see the link:https://access.redhat.com/documentation/en-us/red_hat_cloudforms/4.7/[Red Hat CloudForms documentation].)

The infrastructure migration has the following key steps:

.Migration phases

The Infrastructure Migration Solution has 4 key phases:

. xref:Planning_the_migration[Planning the migration]
+
* xref:Planning_questions[Questions designed to assess the resources and time required for your migration]
* xref:Best_practices_for_migration[Recommendations to minimize the impact on your users]

. xref:Preparing_the_migration_environment[Preparing the environment for migration]
+
* xref:Preparing_the_vmware_source_environment[Preparing the source network and checking the virtual machines for anything that could hinder the migration process]
* xref:Preparing_the_target_environment[Configuring the target storage and networks, installing software, and adding the providers to CloudForms]

. xref:Migrating_the_infrastructure[Migration]
+
* xref:Creating_an_Infrastructure_Mapping[Mapping the source and target infrastructures]
* xref:Creating_and_running_a_migration_plan[Creating and running a migration plan]. For a detailed description of the migration process, see xref:Vmware_to_rhv_workflow[] or xref:Vmware_to_osp_workflow[].

include::modules/con_Vmware_to_rhv_workflow.adoc[leveloffset=+1]
include::modules/con_Vmware_to_osp_workflow.adoc[leveloffset=+1]
