[id="Preparing_the_conversion_hosts"]
= Conversion hosts

Before you create the conversion hosts, you must decide xref:Number_of_conversion_hosts[how many conversion hosts] to create and whether to use xref:datapath_transformation_options_vddk_ssh[VDDK or SSH] transformation.

[[Number_of_conversion_hosts]]
.Number of conversion hosts

Because all the virtual machines in a migration plan are migrated at the same time, the number of conversion hosts you require depends on the number of virtual machines you are migrating. Multiple conversion hosts are recommended for load-balancing purposes, even for smaller migrations.

The number of virtual machines that you can migrate simultaneously depends on your infrastructure capabilities. Each migration requires a certain amount of network bandwidth, I/O throughput, and processing power for the conversion process. You should thoroughly test your environment before the migration to determine how many migrations it can support without negative effects.

Each conversion host is limited to `10` concurrent migrations, unless you  xref:Configuring_the_maximum_number_of_concurrent_migrations[change the default value].

[IMPORTANT]
====
The maximum number of concurrent virtual machine migrations per conversion host is `20` for both VDDK and SSH transformation. The SSH limitation, however, applies only to RHV 4.2.5, not to later versions of RHV.
====

[[datapath_transformation_options_vddk_ssh]]
.Transformation options: VDDK or SSH

Choose the transformation option, VDDK or SSH, that is appropriate for your migration size and setup:

VDDK::
* Recommended because it is approximately twice as fast as SSH
* Compiled with `nbdkit` to provide direct connectivity to the virtual machine disks
* Requires VDDK package download
* Conversion host configuration requires a location

SSH::
* Slower than VDDK
* Better suited for large-scale migrations than VDDK
* Does not require additional downloads, packages, tools, or compilation
* Source and target environments must share SSH keys
* SSH access must be enabled on the source hypervisors

include::modules/proc_Creating_conversion_hosts.adoc[leveloffset=+1]
include::modules/proc_Configuring_conversion_hosts_for_vddk_transformation.adoc[leveloffset=+1]
include::modules/proc_Configuring_conversion_hosts_for_ssh_transformation.adoc[leveloffset=+1]
include::modules/proc_Enabling_conversion_hosts_in_cloudforms.adoc[leveloffset=+1]
include::modules/proc_Configuring_the_maximum_number_of_concurrent_migrations.adoc[leveloffset=+1]
