[id='Infrastructure_migration_solution_overview']
= Infrastructure Migration Solution overview

The Red Hat Infrastructure Migration Solution (IMS) enables you to migrate virtual machines from VMware{nbsp}5.5 (and later) to the following target environments:

* link:https://access.redhat.com/documentation/en-us/red_hat_virtualization[Red Hat Virtualization] 4.3
+
Red Hat Virtualization (RHV) is a virtualization platform built on Red Hat Enterprise Linux (RHEL{nbsp}7). Red Hat Virtualization enables you to manage your virtual infrastructure, including hosts, virtual machines, networks, storage, and users, from a centralized graphical user interface or with a REST API.

* link:https://access.redhat.com/documentation/en-us/red_hat_openstack_platform[Red Hat OpenStack Platform] 13/14
+
OpenStack Platform enables you to build a private or public cloud on top of RHEL. OpenStack Platform is scaleable and fault-tolerant.
+
[NOTE]
====
PLACEHOLDER: CNV migration and link to CNV doc.
====

The migration process is performed with link:https://access.redhat.com/documentation/en-us/red-hat-cloudforms[Red Hat CloudForms], a user interface for managing the infrastructure.

The infrastructure migration has the following key steps:

. xref:Planning_the_migration[Planning the migration]
+
* Assessing your source and target environments to ensure that you have sufficient resources
* Formulating strategies to minimize the impact on users

. xref:Preparing_the_environment_for_migration[Preparing the environment for migration]
+
* Preparing the source environment
* Preparing the target environment
* Configuring the conversion hosts (Red Hat Virtualization hosts or OpenStack Platform instances, running `virt-v2v` and `virt-v2v-wrapper`)

. xref:Migrating_the_infrastructure[Migrating the infrastructure]
+
* Mapping the source resources to the target infrastructure
* Creating and running a migration plan (see xref:Vmware_to_rhv_migration_workflow[] or xref:Vmware_to_osp_migration_workflow[] for migration process details)

include::modules/con_Vmware_to_rhv_migration_workflow.adoc[leveloffset=+1]
include::modules/con_Vmware_to_osp_migration_workflow.adoc[leveloffset=+1]
