[id='Infrastructure_migration_solution_overview']
= Infrastructure Migration Solution overview

Red Hat's Infrastructure Migration Solution (IMS) enables you to migrate your virtual machines from VMware to Red Hat Virtualization or to Red Hat OpenStack Platform.

link:https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.2/[Red Hat Virtualization] (RHV) is an enterprise-grade virtualization platform built on Red Hat Enterprise Linux. With Red Hat Virtualization, you can manage your entire virtual infrastructure, including hosts, virtual machines, networks, storage, and users, from a centralized graphical user interface or with a REST API.

link:https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/13/[Red Hat OpenStack Platform] provides the foundation to build a private or public Infrastructure-as-a-Service (IaaS) cloud on top of Red Hat Enterprise Linux. It offers a massively scalable, fault-tolerant platform for the development of cloud-enabled workloads.

link:https://access.redhat.com/documentation/en-us/red-hat-cloudforms[Red Hat CloudForms] provides the user interface required to manage challenging enterprise environments.

Currently, IMS supports only cold migration. Virtual machines are powered off gracefully as part of the migration process.

.Migration phases

The Infrastructure Migration Solution has 4 key phases:

xref:Planning_the_migration[Planning the migration]::
During the planning phase, you assess your source and target environments to ensure that you have sufficient resources for migration. You may choose to schedule the migration in phases or to create migration groups in order to minimize the impact on your users.

xref:Preparing_the_migration_environment[Preparing the migration environment]::
During this phase, you configure your source and target environments and install the required software.

xref:Migrating_the_infrastructure[Migrating the infrastructure]::
During the migration phase, you map the resources of your source environment to your target environment. After creating an infrastructure mapping, you create and run a migration plan.

Verifying the migration::
The completed migration plan displays successfully migrated virtual machines. If errors appear, see xref:Troubleshooting[].

include::modules/con_Vmware_to_rhv_workflow.adoc[leveloffset=+1]
include::modules/con_Vmware_to_osp_workflow.adoc[leveloffset=+1]
