// Module included in the following assemblies:
//
// assembly_Preparing_the_1_1_environment_for_migration.adoc
// RHV only
[id="Configuring_secure_remote_login_to_the_vmware_hypervisors"]
= (SSH only) Configuring secure remote login to the VMware hypervisors

You can configure secure remote login to the VMware hypervisors with `ssh-agent` and `ssh-add`.

[IMPORTANT]
====
You must configure and verify secure remote login for each VMware hypervisor.
====

Perform the following procedure on the Manager machine:

. Create an `ssh-agent` session for the vdsm user:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# sudo -u vdsm ssh-agent

SSH_AUTH_SOCK=/tmp/ssh-_socket_number_/agent._pid_; export SSH_AUTH_SOCK; <1>
SSH_AGENT_PID=139150; export SSH_AGENT_PID;
echo Agent pid 139150;
----
<1> Copy the `SSH_AUTH_SOCK` value from the output of the `ssh-agent` command. You will use it for `ssh-add` and connecting over SSH to the VMware hypervisors.

. Run `ssh-add` to authorize the vdsm user's private key for the `ssh-agent` session:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# sudo -u vdsm SSH_AUTH_SOCK=_SSH_AUTH_SOCK_value_ ssh-add
----

. Connect to each VMware hypervisor as `vdsm`, using the `ssh-agent` session and `ssh`, to verify the secure remote login:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# sudo -u vdsm \
    SSH_AUTH_SOCK=_SSH_AUTH_SOCK_value_ ssh root@_esx1.example.com_
----
+
[IMPORTANT]
====
If the connection fails, all migrations from this VMware hypervisor using SSH transformation will fail.
====
