// Module included in the following assemblies:
// proc_Migrating_the_infrastructure.adoc
[id="Changing_the_maximum_number_of_concurrent_migrations"]
= (Optional) Changing the maximum number of concurrent migrations

You can change the maximum number of concurrent migrations for conversion hosts or providers to control the impact of the migration process on your infrastructure.

[CAUTION]
====
For VDDK, an ESXi memory limitation allows a maximum of `10` concurrent migrations per conversion host, unless you increase the ESXi memory.
====

The provider setting has priority over the conversion host setting. For example, if the maximum number of concurrent migrations is `20` for a provider and `3` for five conversion hosts, the maximum number of concurrent migrations is `20`, not `15` (`5` conversion hosts `x` `3` concurrent migrations).

An increase in the maximum number of concurrent migrations affects all migration plans immediately. Virtual machines that are queued to migrate will migrate in greater numbers.

A decrease maximum number of concurrent migrations affects only future migration plans. Migration plans that are in progress will use the limit that was set when the plan was created.

[NOTE]
====
OpenStack Platform only: If you change the maximum number of concurrent migrations, you must ensure that your conversion hosts have sufficient RAM.
====

Changing the maximum number of concurrent migrations for all conversion hosts::

In CloudForms, click menu:Compute[Migration > Migration Settings] and select the new limit.

[NOTE]
====
The following commands are performed on the command line of the CloudForms machine.
====

Changing the maximum number of concurrent migrations for a single conversion host::
+
[options="nowrap" subs="+quotes,verbatim"]
----
# vmdb
# rails console
irb(main):001:0> $evm = MiqAeMethodService::MiqAeService.new(MiqAeEngine::MiqAeWorkspaceRuntime.new)
irb(main):002:0> $evm.vmdb(:host).find_by(:name => "_host1.example.com_").custom_set("Max Transformation Runners", _20_)
----

Changing the maximum number of concurrent migrations for a provider::
+
[options="nowrap" subs="+quotes,verbatim"]
----
# vmdb
# rails console
irb(main):001:0> $evm = MiqAeMethodService::MiqAeService.new(MiqAeEngine::MiqAeWorkspaceRuntime.new)
irb(main):002:0> $evm.vmdb(:ext_management_system).find_by(:name => "_RHV_").custom_set("Max Transformation Runners", _30_)
----

Getting the maximum number of concurrent migrations for a provider::
+
[options="nowrap" subs="+quotes,verbatim"]
----
# vmdb
# rails console
irb(main):001:0> $evm = MiqAeMethodService::MiqAeService.new(MiqAeEngine::MiqAeWorkspaceRuntime.new)
irb(main):002:0> $evm.vmdb(:ext_management_system).find_by(:name => "_OpenStack_").custom_get("Max Transformation Runners")
----
