[id="Configuring_secure_remote_login_to_the_vmware_hypervisors_for_ssh_transformation"]
.Configuring secure remote login to the VMware hypervisors for SSH transformation

Perform the following procedure on the Manager machine:

. Enter the following command:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# sudo -u vdsm ssh-agent
----
+
The command returns this output:
+
[options="nowrap" subs="+quotes,verbatim"]
----
SSH_AUTH_SOCK=_socket_domain_; export SSH_AUTH_SOCK; <1>
SSH_AGENT_PID=139150; export SSH_AGENT_PID;
echo Agent pid 139150;
----
<1> The `socket_domain` format is +/tmp/ssh-_socket_number_/agent._pid_+.

. Enter the following commands, copying the _socket_domain_ from the output, to validate the SSH configuration for each VMware hypervisor:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# sudo -u vdsm SSH_AUTH_SOCK=_socket_domain_ ssh-add
# sudo -u vdsm \
    SSH_AUTH_SOCK=_socket_domain_ ssh root@_esx1.example.com_
----
+
[IMPORTANT]
====
These commands must be run for each VMware hypervisor.

If the last command fails, all migrations from this VMware hypervisor using SSH transformation will fail. Check the following procedures:

* xref:Configuring_the_vmware_hypervisors_for_ssh_transformation[]
* xref:Copying_the_vmware_keys_for_SSH_for_rhv[]
====
+
If the SSH connection is successful, you can authenticate the conversion hosts in CloudForms. See xref:Authenticating_the_red_hat_virtualization_conversion_hosts[].

[id="Authenticating_the_red_hat_virtualization_conversion_hosts"]
.Authenticating the Red Hat Virtualization conversion hosts in CloudForms

Perform the following procedure for each Red Hat Virtualization conversion host:

. Click menu:Compute[Infrastructure > Hosts] and select a Red Hat Virtualization conversion host.
. Click the *Configuration* drop-down button and select *Edit Selected items*.
. In the *Default* tab of the Endpoints section, enter the *Username* and the *Password* for `root`.
. Click *Validate* and wait for validation to complete.
. Click *Save*.

You can create an infrastructure mapping. See xref:Creating_an_infrastructure_mapping[].

Optionally, you can verify the conversion hosts in a browser. See xref:Verifying_conversion_hosts[].
