// Module included in the following assemblies:
// IMS_1.1/modules/proc_Configuring_conversion_hosts_for_transformation.adoc
[id="Configuring_the_{context}_conversion_hosts"]
ifdef::rhv[]
= Configuring the Red Hat Virtualization conversion hosts

Configuring the Red Hat Virtualization conversion hosts for VDDK or SSH transformation involves the following steps.

.VDDK

. Downloading the VMware Virtual Disk Development Kit (xref:rhv_vddk_download[])
. Configuring the conversion hosts (xref:Configuring_the_rhv_conversion_hosts_procedure[]):
.. Installing the `ovirt-ansible-v2v-conversion-host` package
.. Creating the `extra_vars.yml` and `secure_vars.yml` files
.. Running the `conversion_host_enable` playbook
.. Verifying the configuration with the `conversion_host_check` playbook
. Authenticating the conversion hosts in CloudForms (xref:Authenticating_the_red_hat_virtualization_conversion_hosts[])

.SSH

. Configuring the conversion hosts (xref:Configuring_the_rhv_conversion_hosts_procedure[]):
.. Installing the `ovirt-ansible-v2v-conversion-host` package
.. Creating the `extra_vars.yml` and `secure_vars.yml` files
.. Running the `conversion_host_enable` playbook
.. Verifying the configuration with the `conversion_host_check` playbook
. Copying the VMware SSH keys to the conversion hosts (xref:Copying_the_vmware_keys_for_SSH_for_rhv[])
. Configuring secure remote login to the VMware hypervisors (xref:Configuring_secure_remote_login_to_the_vmware_hypervisors[])
. Authenticating the conversion hosts in CloudForms (xref:Authenticating_the_red_hat_virtualization_conversion_hosts[])
endif::rhv[]
ifdef::osp[]
= Configuring the OpenStack Platform conversion hosts

Configuring the OpenStack Platform conversion hosts for VDDK or SSH transformation involves the following steps.

.VDDK

. Downloading the VMware Virtual Disk Development Kit (xref:osp_vddk_download[])
. Configuring the conversion hosts (xref:Configuring_the_osp_conversion_hosts_procedure[]):
.. Creating the `extra_vars.yml` and `secure_vars.yml` files
.. Running the `conversion_host_enable` playbook
.. Verifying the configuration with the `conversion_host_check` playbook

.SSH

. Configuring the conversion hosts (xref:Configuring_the_osp_conversion_hosts_procedure[]):
.. Creating the `extra_vars.yml` and `secure_vars.yml` files
.. Configuring the conversion host with the `conversion_host_enable` playbook
.. Verifying the configuration with the `conversion_host_check` playbook
. Copying the VMware SSH keys to the conversion hosts (xref:Copying_the_vmware_keys_for_SSH_for_osp[])
endif::osp[]

ifdef::rhv[]
[IMPORTANT]
====
If you upgrade the target environment, you should upgrade the conversion hosts so that you have the latest software and critical updates:

. Log in to the Manager machine using SSH.
. Run the following command:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# yum update
----
====
endif::rhv[]
ifdef::osp[]
[IMPORTANT]
====
If you upgrade the target environment, you should upgrade the conversion hosts so that you have the latest software and critical updates:

. Download the latest conversion host appliance.
. Redeploy the conversion hosts. See xref:Deploying_osp_conversion_hosts[Deploying the OpenStack Platform conversion hosts].
====
endif::osp[]

== Downloading VDDK
ifdef::rhv[]
[id="rhv_vddk_download"]
endif::rhv[]
ifdef::osp[]
[id="osp_vddk_download"]
endif::osp[]

Download and save the VMware Virtual Disk Development Kit:

. Navigate to link:https://www.vmware.com/support/pubs/[].
. Click *VMware SDK & API Product Documentation* to expand.
. Click *VMware Virtual Disk Development Kit (VDDK)*.
. Click *Latest Releases* and select the latest VDDK release.
. Click *Download SDKs* to download the VDDK archive file.
. Save the VDDK archive file in an HTML-accessible location and record its URL.

You are ready to configure the conversion hosts.

== Configuring the conversion hosts

ifdef::rhv[]
[id="Configuring_the_rhv_conversion_hosts_procedure"]
Perform the following procedure on the Manager machine:

. Install the `ovirt-ansible-v2v-conversion-host` package:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# yum install ovirt-ansible-v2v-conversion-host
----

. Create an `extra_vars.yml` file and update its parameters:
+
[options="nowrap" subs="+quotes,verbatim"]
----
---
v2v_host_type: rhevm

# Transport methods to configure on the conversion host. Valid values: `vddk`, `ssh`
v2v_transport_methods:
  - _vddk_

# Maximum number of concurrent conversions per host. Default is `10`.
v2v_max_concurrent_conversions: _10_

# File name of VDDK package
v2v_vddk_package_name: "VMware-vix-disklib-_version_.x86_64.tar.gz"

# URL of VDDK package
v2v_vddk_package_url: "http://_path_to_vddk_package_/{{ v2v_vddk_package_name }}"

# Name of the CloudForms provider to which the conversion host belongs
manageiq_provider_name: RHV

# Base URL of CloudForms machine
manageiq_url: "https://_CloudForms_FQDN_"

# Whether to validate certificate of CloudForms server. Default is `true`.
manageiq_validate_certs: _false_

# To obtain the CloudForms zone ID, run this API call on the CloudForms machine:
# curl -sk -u admin 'https://_CloudForms_FQDN_/api/zones/?filter\[\]=name=RHV&expand=resources&attributes=zone
manageiq_zone_id: "42000000000001"'

# List of infrastructure providers
# Each provider is a dictionary with 3 attributes: `name`, `hostname`, and `connection_configurations`
manageiq_providers:
  - name: "_RHV_"
    hostname: _Manager_FQDN_or_IP_address_
    connection_configurations: <1>
      - endpoint:
          role: "default"
          certificate_authority: | <2>
            -----BEGIN CERTIFICATE-----
            _MIIDoDCCAoigAwIBAgIBATANBgkqhkiG9w0BAQsFADA9MRswGQYDVQ...._
            -----END CERTIFICATE-----
----
<1> `connection_configurations` has a single endpoint, whose role is `default`.
<2> The CA certificate is stored as `/etc/pki/ovirt-engine/apache-ca.pem` on the Manager machine.
endif::rhv[]
ifdef::osp[]
[id="Configuring_the_osp_conversion_hosts_procedure"]
Perform the following procedure on each conversion host:

. Go to `/usr/share/ovirt-ansible-v2v-conversion-host/playbooks`.
. Create an `extra_vars.yml` file and update its parameters:
+
[options="nowrap" subs="+quotes,verbatim"]
----
---
v2v_host_type: openstack

# Transport methods to configure on the conversion host. Valid values: `vddk`, `ssh`
v2v_transport_methods:
  - _vddk_

# Maximum number of concurrent conversions per host. Default is `10`.
v2v_max_concurrent_conversions: _10_

# File name of VDDK package
v2v_vddk_package_name: "VMware-vix-disklib-_version_.x86_64.tar.gz"

# URL of VDDK package
v2v_vddk_package_url: "http://_path/to/downloaded_vddk_package_/{{ v2v_vddk_package_name }}"

manageiq_provider_name: OpenStack

# Base URL of CloudForms machine
manageiq_url: "https://_CloudForms_FQDN_"

# Whether to validate certificate of CloudForms server. Default is `true`.
manageiq_validate_certs: _false_
manageiq_zone_id: "42000000000001"

# List of cloud providers
# Each provider is a dictionary with 3 attributes: `name`, `hostname`, and `connection_configurations`
manageiq_providers:
  - name: "_OpenStack_"
    hostname: _controller_node_FQDN_or_IP_address_
    connection_configurations: <1>
      - endpoint:
          role: "default"
          security_protocol: "ssl" <2>
          certificate_authority: | <3>
            -----BEGIN TRUSTED CERTIFICATE-----
            _MIIDNzCCAh8CAQEwDQYJKoZIhvcNAQELBQAwYjELMAkGA1UEBhMCVV...._
            -----END TRUSTED CERTIFICATE-----
            -----BEGIN TRUSTED CERTIFICATE-----
            _MIIDlzCCAn+gAwIBAgIJAOP7AaT7dsLYMA0GCSqGSIb3DQEBCwUAMG...._
            -----END TRUSTED CERTIFICATE-----
----
<1> `connection_configurations` has a single endpoint, whose role is `default`.
<2> You can specify the connection security: `non-ssl`, `ssl-without-validation`, or `ssl`. If you choose `ssl`, add the CA chain (`certificate_authority`)
<3> The CA chain (`certificate_authority`) is a concatenation of two CA files:
+
* `/etc/pki/ca-trust/source/anchors/undercloud-cacert.pem` on the undercloud server
* `/etc/pki/ca-trust/anchors/overcloud-cacert.pem` on one of the overcloud controllers
+
If you deploy your own CA chain, use the chain that signs the OpenStack Platform API certificates (see link:https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/14/html-single/director_installation_and_usage/index#appe-SSLTLS_Certificate_Configuration[SSL/TLS Certificate Configuration] in _Red Hat OpenStack Platform Director Installation and Usage_).
endif::osp[]

. Create an encrypted `secure_vars.yml` file:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# ansible-vault create secure_vars.yml
----

. Add the following variables to `secure_vars.yml` and save the file:
+
[options="nowrap" subs="+quotes,verbatim"]
----
---
# CloudForms `admin` user, for connecting to CloudForms
manageiq_username: "_username_"

# CloudForms `admin` password:
manageiq_password: "_password_"

# SSH private key to connect to VMware hypervisors. Required for both VDDK and SSH. <1>
v2v_ssh_private_key: |
  -----BEGIN RSA PRIVATE KEY-----
  _b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAlwAAAAdzc2gtcn...._
  -----END RSA PRIVATE KEY-----
----
<1> This is the private key of the SSH key pair that you created in xref:Configuring_the_vmware_hypervisors_for_ssh_transformation[].
ifdef::rhv[]
+
[IMPORTANT]
====
If the RHV conversion host has an existing SSH private key, the `v2v_ssh_private_key` value does not overwrite it. You must delete the old key manually in `/var/lib/vdsm/.ssh/id_rsa` before running the `conversion_host_enable` playbook.
====
endif::rhv[]

. Run the `conversion_host_enable` playbook:
+
ifdef::rhv[]
[options="nowrap" subs="+quotes,verbatim"]
----
# ansible-playbook -i _conversion_host_FQDN_or_IP_, -b \
    -e "ansible_ssh_private_key_file=/etc/pki/ovirt-engine/keys/engine_id_rsa" \
    -e @extra_vars.yml -e @secure_vars.yml --ask-vault-pass \
    /usr/share/ovirt-ansible-v2v-conversion-host/playbooks/conversion_host_enable.yml
----
endif::rhv[]
ifdef::osp[]
[options="nowrap" subs="+quotes,verbatim"]
----
# ansible-playbook -i _conversion_host_FQDN_or_IP_, -c local -b \
    -e @extra_vars.yml -e @secure_vars.yml --ask-vault-pass \
    /usr/share/ovirt-ansible-v2v-conversion-host/playbooks/conversion_host_enable.yml
----
endif::osp[]
+
[WARNING]
====
Running the `conversion_host_enable` playbook more than once on the same host creates multiple entries in the CloudForms database for that host.

If you need to run the `conversion_host_enable` playbook again, you should remove the existing database entry by running the `conversion_host_disable` playbook on the host:

[options="nowrap" subs="+quotes,verbatim"]
----
# ansible-playbook /usr/share/ovirt-ansible-v2v-conversion-host/playbooks/conversion_host_disable.yml
----
====

. Run the `conversion_host_check` playbook to verify the conversion host configuration:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# ansible-playbook --ask-vault-pass -i _conversion_host_FQDN_or_IP_, conversion_host_check.yml
----
ifdef::rhv[]
+
* If you are using VDDK, you can authenticate the conversion hosts in CloudForms. See xref:Authenticating_the_red_hat_virtualization_conversion_hosts[].
* If you are using SSH, you are ready to copy the VMware keys to the conversion hosts. See xref:Copying_the_vmware_keys_for_SSH_for_rhv[].
endif::rhv[]
ifdef::osp[]
+
* If you are using VDDK, you can create an infrastructure mapping. See xref:Creating_an_infrastructure_mapping[].
* If you are using SSH, you are ready to copy the VMware keys to the conversion hosts. See xref:Copying_the_vmware_keys_for_SSH_for_osp[].
endif::osp[]
