// Module included in the following assemblies:
//
// ims_common/assembly_Migrating_the_virtual_machines.adoc
// For 1.1
[id="Changing_the_maximum_number_of_concurrent_migrations"]
= (Optional) Changing the maximum number of concurrent migrations

You can change the maximum number of concurrent migrations for conversion hosts or providers to control the impact of the migration process on your infrastructure.

The provider setting has priority over the conversion host setting. For example, if the maximum number of concurrent migrations is `20` for a provider and `3` for five conversion hosts, the maximum number of concurrent migrations is `20`, not `15` (`5` conversion hosts `x 3` concurrent migrations per host).

An increase in the maximum number of concurrent migrations affects all migration plans immediately. Virtual machines that are queued to migrate will migrate in greater numbers.

A decrease maximum number of concurrent migrations affects only future migration plans. Migration plans that are in progress will use the limit that was set when the plan was created.

[CAUTION]
====
The default value of *Maximum concurrent migrations per conversion host* is `10`.

If you increase this value, you must make the following changes:

* Red Hat OpenStack Platform: Ensure that your conversion hosts have sufficient RAM.

* VDDK transformation: Increase the VMware hypervisors' memory. Otherwise, an ESXi memory limitation will cause the migration to fail.
====

Changing the maximum number of concurrent migrations for all conversion hosts::
Click menu:Compute[Migration > Migration Settings] and select a new *Maximum concurrent migrations per conversion host*.

Changing the maximum number of concurrent migrations for a single conversion host::
. Log in to the CloudForms machine using SSH.
. Enter the following command:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# vmdb
# rails console
irb(main):001:0> $evm = MiqAeMethodService::MiqAeService.new(MiqAeEngine::MiqAeWorkspaceRuntime.new)
irb(main):002:0> $evm.vmdb(:host).find_by(:name => "_host1.example.com_").custom_set("Max Transformation Runners", _20_)
----

Changing the maximum number of concurrent migrations for a provider::
[NOTE]
====
The default maximum number of concurrent migrations for a provider is `20`.
====
. Log in to the CloudForms machine using SSH.
. Enter the following command:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# vmdb
# rails console
irb(main):001:0> $evm = MiqAeMethodService::MiqAeService.new(MiqAeEngine::MiqAeWorkspaceRuntime.new)
irb(main):002:0> $evm.vmdb(:ext_management_system).find_by(:name => "_RHV_").custom_set("Max Transformation Runners", _30_)
----

Getting the maximum number of concurrent migrations for a provider::
. Log in to the CloudForms machine using SSH.
. Enter the following command:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# vmdb
# rails console
irb(main):001:0> $evm = MiqAeMethodService::MiqAeService.new(MiqAeEngine::MiqAeWorkspaceRuntime.new)
irb(main):002:0> $evm.vmdb(:ext_management_system).find_by(:name => "_OpenStack_").custom_get("Max Transformation Runners")
----
