= Infrastructure Migration Solution Guide
:imagesdir: images
:vernum: 1.0
:toc: left
:toclevels: 3
:numbered!:
:compat-mode:
:experimental:

// Attributes
include::common/attributes/cfme.adoc[]

:cfme:

:numbered:

[[Introduction]]
== Introduction

{product-title} is Red Hat's solution for moving your virtual machines from VMware to Red Hat Virtualization.

Red Hat Virtualization (RHV) is an enterprise-grade virtualization platform built on Red Hat Enterprise Linux. With Red Hat Virtualization, you can manage your entire virtual infrastructure, including hosts, virtual machines, networks, storage, and users, from a centralized graphical user interface or with a REST API.

The infrastructure migration is performed with Red Hat CloudForms. CloudForms is a user interface, providing the control and automation required to manage challenging enterprise environments.

The infrastructure migration process has 4 key phases:

* Installation:
** Installing and configuring Red Hat Virtualization, Red Hat Virtualization Host(s) or Red Hat Enterprise Linux host(s), and Red Hat CloudForms
** Creating and configuring the RHV conversion host(s) and configuring the maximum number of concurrent migrations.

* Discovery and Assessment:
** Discovering and assessing your environment
** Migration example
** Best practices

* Planning:
** Creating an infrastructure mapping
** Creating and running a migration plan

* Migration:
** Migration workflow
** Troubleshooting

include::doc/assembly_Installation.adoc[leveloffset=+1]
include::doc/assembly_Discovery_and_Assessment.adoc[leveloffset=+1]
include::doc/assembly_Planning.adoc[leveloffset=+1]
include::doc/assembly_Migration.adoc[leveloffset=+1]
