[[Installation]]
== Installation

=== Installing the NetApp SDK

The procedure describes the steps to install the NetApp SDK.

[arabic]
. From the +NetApp+ site, download the +SDK+ to +/var/www/miq/vmdb/lib+. The file name is in the format +netapp-manageability-sdk-abc.0Pxyz.zip+. You need to be a NetApp customer to obtain this file.
. Unzip the file by logging into an +SSH+ session on the appliance, and type:
+
-----------------------------------------------------------------
unzip -d /var/www/miq/vmdb/lib/netapp-manageability-sdk-4.0P1.zip  
-----------------------------------------------------------------
+
. Enter:
+
----------------------------------------------------------------------------------------------------------------------------------
echo "export LD_LIBRARY_PATH=\$LD_LIBRARY_PATH:/var/www/miq/vmdb/lib/netapp-manageability-sdk-4.0P1/lib/linux-64" /etc/default/evm  
----------------------------------------------------------------------------------------------------------------------------------
+
. Restart the CFME service by entering the command:
+
---------------------------
service evmserverd restart  
---------------------------
+


=== Enabling Storage Features in CFME

This procedure describes the steps to enable storage features in the CloudForms Management Engine (CFME).

[arabic]
. Log in to the dashboard.
. Navigate to +Configure+ → +Configuration+.
. Click on the +Settings+ accordion, then click +Zones+.
. Click the +Zone+ where the CloudForms Management Engine server is located.
. In the +Servers+ area, click on the CloudForms Management Engine server.
. Click +Advanced+ tab.
. From +File+, select +EVM Server Main Configuration+.
. In the +EVM Server Main Configuration+ editor, make the following changes while maintaining the exact spacing.
+
---------------------------------
product:
 maindb: ExtManagementSystem
 storage: true                   
---------------------------------
+
. Click +Save+.
. Refresh the browser screen to see a label for storage.


=== Enabling the Storage Inventory Server Roles

This procedure describes the steps to enable storage inventory server roles.

[arabic]
. Log in to the dashboard.
. Navigate to +Configure+ → +Configuration+.
. Click on the +Settings+ accordion, then click +Zones+.
. Click the zone where the CloudForms Management Engine server is located.
. From the +Server+ page, go to +Server Control+.
. From the list of +Server Roles+, select +Storage Inventory+. To collect +Capacity and Utilization+ data, select the appropriate +Storage Capacity+ and +Utilization Roles+ as well. 
. Click +Save+.


=== Adding a Storage Manager

This procedure describes the steps to add a storage manager.

. Navigate to +Storage+ → +Storage Manager+. 
. Click +Configuration+.
. Click +Add a New Storage Manager+.
. Type in a descriptive name for the Storage Manager.
. Type in the Host Name, IP Address, and Port of the agent. 
. Select the +Type+. 
. If using more than one zone, select which zone you want this agent assigned.
. Type in a +User ID+ and +Password+ for the agent.
. Click +Validate+ to confirm that the user and password connects.
. Click +Save+.

