// Module included in the following assemblies:
// assembly_Migrating_the_infrastructure.adoc
[id="Changing_the_maximum_number_of_concurrent_migrations"]
= (Optional) Changing the maximum number of concurrent migrations

You can change the maximum number of concurrent migrations for conversion hosts or providers to control the impact of the migration process on your infrastructure.

[WARNING]
====
For VDDK, the number of maximum concurrent migrations per conversion host must not be greater than `20`. Otherwise, network overload will cause the migration to fail.
====

The provider setting has priority over the conversion host setting. For example, if the maximum number of concurrent migrations is `20` for a provider and `3` for five conversion hosts, the maximum number of concurrent migrations is `20`, not `15` (`5` conversion hosts `x` `3` concurrent migrations).

An increase in the maximum number of concurrent migrations affects all migration plans immediately. Virtual machines that are queued to migrate will migrate in greater numbers.

A decrease maximum number of concurrent migrations affects only future migration plans. Migration plans that are in progress will use the limit that was set when the plan was created.

.Changing the maximum number of concurrent migrations for all conversion hosts or providers

. In CloudForms, click menu:Compute[Migration > Migration Settings].
. In the *Migration Throttling* tab, select a value for *Maximum concurrent migrations per provider* and click *Apply*.
+
[NOTE]
====
Currently, the *Maximum concurrent migrations per conversion host* interface control does not work. See xref:Known_issues[].
// For VDDK, do not set the maximum number of concurrent migrations per conversion host higher than `20`.
//
// The value of *Maximum concurrent migrations per conversion host* is constrained so that it cannot be greater than *Maximum concurrent migrations per provider*.
====

.Changing the maximum number of concurrent migrations for a specific conversion host

. Log in to the CloudForms machine using SSH.
. Enter the following command:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# curl -sk -u _username:password_ https://_CloudForms_FQDN_/api/conversion_hosts/_conversion_host_id_ -X POST -d '{"action": "edit", "resource": {"max_concurrent_tasks": _2_}}'
----
+
You can obtain the `_conversion_host_id_` using the API call in xref:Verifying_conversion_hosts[].
