// Module included in the following assemblies:
//
// ims_common/assembly_Migrating_the_virtual_machines.adoc
// For 1.2
[id="Changing_the_maximum_number_of_concurrent_migrations_{context}"]
= Changing the maximum number of concurrent migrations

You can change the maximum number of concurrent migrations for conversion hosts or providers to control the impact of the migration process on your infrastructure.

The provider setting has priority over the conversion host setting. For example, if the maximum number of concurrent migrations is `20` for a provider and `3` for five conversion hosts, the maximum number of concurrent migrations is `20`, not `15` (`5` conversion hosts `x 3` concurrent migrations per host).

An increase in the maximum number of concurrent migrations affects all migration plans immediately. Virtual machines that are queued to migrate will migrate in greater numbers.

A decrease maximum number of concurrent migrations affects only future migration plans. Migration plans that are in progress will use the limit that was set when the plan was created.

Changing the maximum number of concurrent migrations for all conversion hosts or providers::
[CAUTION]
====
ifdef::osp[]
Red Hat OpenStack Platform conversion hosts require an additional 1 GB RAM for each additional concurrent migration above `10`.
endif::osp[]

If you are using VDDK transformation, the number of concurrent migrations must not exceed `20`. Otherwise, network overload will cause the migration to fail.
====
. Click menu:Compute[Migration > Migration Settings].
. In the *Migration Throttling* tab, select a value for *Maximum concurrent migrations per conversion host* or *Maximum concurrent migrations per provider* and click *Apply*.
+
The value of *Maximum concurrent migrations per conversion host* is constrained so that it cannot be greater than *Maximum concurrent migrations per provider*.
+
[NOTE]
====
In the current release, the *Maximum concurrent migrations per conversion host* interface control does not work.
====

// Commenting out because of https://bugzilla.redhat.com/show_bug.cgi?id=1716283
// Setting limit via API is not working.
//
// Changing the maximum number of concurrent migrations for a specific conversion host::
// . Log in to the CloudForms machine using SSH.
// . Enter the following command:
// +
// [options="nowrap" subs="+quotes,verbatim"]
// ----
// # curl -sk -u _username:password_  https://_CloudForms_FQDN_/api/conversion_hosts/_conversion_host_id_ -X POST -d '{"action": "edit", "resource": {"max_concurrent_tasks": _2_}}' <1> <2> <3> <4>
// ----
//
// <1> `username:password` is the username and password for CloudForms.
// <2> `CloudForms_FQDN` is the FQDN of the CloudForms machine.
// <3> To obtain a `conversion_host_id`:
// +
// . Enter the following API call in the address bar of a browser:
// +
// [options="nowrap" subs="+quotes,verbatim"]
// ----
// https://_CloudForms_FQDN_/api/conversion_hosts
// ----
// +
// A login window is displayed.
//
// . Enter your *Username* and *Password* and click *Sign in*. The conversion hosts and their IDs are displayed in JSON format.
// <4> `max_concurrent_tasks` is the maximum number of concurrent migrations. The default is `10`.
