// Module included in the following assemblies:
// assembly_Preparing_the_environment_for_migration.adoc
[id="Configuring_the_conversion_hosts"]
= Configuring the conversion hosts

You can select, authenticate, and configure your conversion hosts for VDDK or SSH transformation:

* VDDK:

. xref:Downloading_vddk[]
. xref:Configuring_conversion_hosts_in_cloudforms[]

* SSH:

. xref:Configuring_conversion_hosts_in_cloudforms[]
. xref:Ssh_only_copying_the_vmware_keys_to_the_conversion_hosts[]

After configuring the conversion hosts, you can xref:Verifying_conversion_hosts[verify the conversion hosts] using an API call in a browser. This command returns the conversion host names and number. It does not check configuration.

[IMPORTANT]
====
If you upgrade your target environment, update the conversion hosts to ensure that you have the latest software and critical updates:

* Red Hat Virtualization
+
Run `yum update` on the conversion hosts.

* OpenStack Platform
+
Download the latest conversion host appliance and re-deploy the conversion hosts as described in xref:Deploying_osp_conversion_hosts[].
====

[id="Downloading_vddk"]
== Downloading VDDK

Download and save the VMware Virtual Disk Development Kit:

. Navigate to link:https://www.vmware.com/support/pubs/[].
. Click *VMware SDK & API Product Documentation* to expand.
. Click *VMware Virtual Disk Development Kit (VDDK)*.
. Click *Latest Releases* and select the latest VDDK release.
. Click *Download SDKs* to download the VDDK archive file.
. Save the VDDK archive file and record its path.

You can configure the conversion hosts in CloudForms.

[id="Configuring_conversion_hosts_in_cloudforms"]
== Configuring the conversion hosts in CloudForms

. In CloudForms, click menu:Compute[Migration > Migration Settings].
. In the *Conversion Hosts* tab, click *Configure Conversion Host*.
. Perform the following procedures in the *Configure Conversion Host* wizard:

[cols="1,3", options="header"]
|===
|Screen |Procedure
|*Location*
.<a|. Select a *Provider Type*.
. Select a *Provider*.

. Select a Red Hat Virtualization *Cluster* / OpenStack Platform *Project*.

. Click *Next*.
|*Hosts*
.<a|. Select one or more hosts from the dropdown list.
. Click *Next*.
|*Authentication*
.<a|. Click *Browse* to browse to the SSH key or paste it in the *Conversion host SSH key* field.

* Red Hat Virtualization Manager deploys a private SSH key on the conversion hosts in order to send commands and run playbooks. The default key file is `/etc/pki/ovirt-engine/keys/engine_id_rsa` on the Manager machine.
* OpenStack Platform user uses a private SSH key to connect to the conversion hosts.

. Select *SSH* or *VDDK* as a *Transformation method*.

* *SSH*: Click *Browse* to browse to the SSH key or paste it in the *VMware hypervisors SSH key* field. The VMware keys are copied to the conversion hosts in a separate step and are not deployed automatically, in order to prevent man-in-the-middle attacks.
+
[IMPORTANT]
====
*Red Hat Virtualization*: If a RHV host has an existing SSH private key, you must delete the old key manually in `/var/lib/vdsm/.ssh/id_rsa` before configuring the conversion host. Conversion host configuration does not overwrite existing keys.
====

* *VDDK*: Enter the path of the VDDK package in the *VDDK library path* field and click *Validate*. Wait for validation to complete.

. Click *Configure*.
|*Results*
.<a|Wait for the conversion host configuration to finish and click *Close*.

The configured conversion hosts and status information, including error messages, appear in the *Configured Conversion Hosts* list.

Click *Remove* to unconfigure a conversion host or *Retry* to retry a conversion host configuration.

You can verify the names and number of conversion hosts using an API call in a browser. See xref:Verifying_conversion_hosts[].
|===

* If you are using VDDK transformation, you can start the infrastructure migration. See xref:Migrating_the_infrastructure[].
* If you are using SSH transformation, copy the VMware SSH keys to the conversion hosts.

[id="Ssh_only_copying_the_vmware_keys_to_the_conversion_hosts"]
== Copying the VMware SSH keys to the conversion hosts

Copy the VMware SSH keys to the conversion hosts for your environment:

* xref:Copying_the_vmware_keys_for_SSH_for_rhv[Red Hat Virtualization]
* xref:Copying_the_vmware_keys_for_SSH_for_osp[OpenStack Platform]

:context: rhv
:rhv:
include::../ims_common/proc_Copying_the_vmware_keys_to_the_conversion_hosts.adoc[leveloffset=+2]
:rhv!:
:context: osp
:osp:
include::../ims_common/proc_Copying_the_vmware_keys_to_the_conversion_hosts.adoc[leveloffset=+2]
:osp!:

include::../ims_common/proc_Verifying_conversion_hosts.adoc[leveloffset=+1]
