// Module included in the following assemblies:
// assembly_Troubleshooting.adoc
[id="Migration_logs"]
= Migration logs

You can check the conversion host logs, playbook logs (if you are running premigration or postmigration playbooks), and the CloudForms log to identify the cause of a migration error.

When disk migration starts, two logs are created in the conversion host:

* `virt-v2v`: Debug output from `virt-v2v` itself. This log tracks the core of the virtual machine migration process, including `libguestfs` traces and disk migration details.
* `virt-v2v-wrapper`: Log of the daemonizing wrapper for `virt-v2v`. This log traces the orchestration of the virtual machine conversion on the conversion host, including disk migration percentages and `virt-v2v` error reporting.

[IMPORTANT]
====
If you need to open a link:https://access.redhat.com/support/cases/#/case/new[Red Hat Support call], both the `virt-v2v` log and `virt-v2v-wrapper` log are required for analysis and troubleshooting.
====

.Downloading conversion host and playbook logs in CloudForms

. Click menu:Compute[*Migration* > Migration Plans].
. Click a completed migration plan to view its details.
. Click *Download Log* of a virtual machine and select a log from the dropdown list:

* *Premigration log:* This option only appears if a premigration playbook is used.
* *Migration log:* This is the `virt-v2v` log.
* *Virt-v2v-wrapper log:*
* *Postmigration log:* This option only appears if a postmigration playbook is used.

[id="CloudForms_log"]
.Accessing the CloudForms migration log

. Log into the CloudForms machine using SSH.
. You can view the migration log, `/var/www/miq/vmdb/log/automation.log`.
