= QuickStart Guide for CloudForms with Red Hat OpenStack Platform
OpenStack Documentation Team <rhos-docs@redhat.com>
:imagesdir: images
:vernum: 10
:toc: left
:compat-mode:
:experimental:

:cfme:
:openstack:

// Custom attributes
include::common/attributes/cfme.adoc[]

include::topics/common/introduction.adoc[]

== Key {product-title} Features for OpenStack Cloud Providers

{product-title} provides several interface features specific to OpenStack cloud providers:

* The {product-title_short} *Topology* widget (xref:using-the-topology-widget[]) provides an interactive visualization of the OpenStack cloud. 
* {product-title_short} provides a user interface for managing OpenStack storage resources (xref:storage_managers[]).
* _Custom buttons_, which allows you to provide automation for specific actions to OpenStack tenants (xref:custom-button-tenants[]).

When adding an OpenStack cloud provider, you can also:

* Enable _tenant mapping_. This creates a one-to-one association between tenants in {product-title_short} and OpenStack.
* Connect to OpenStack through the Keystone V3 API. This API enables multiple OpenStack identity domains. Domains are high-level containers for projects, users, and groups. Users of different domains can be represented in different authentication back ends.

For information about tenant mapping and the Keystone V3 API, see xref:add-openstack-oc[].

[[installing-cloudforms]]
== Installing and Configuring {product-title}
include::topics/installing.adoc[]

=== Configuring {product-title}

include::topics/configuration-quick.adoc[]

== Adding an OpenStack Infrastructure Provider

// see topics/Adding_OpenStack_Providers.adoc for singlesourcable

include::common/openstack/adding-an-openstack-infrastructure-provider.adoc[]

[[openstack-events-uc]]
=== Configuring the Undercloud to Store Events

include::common/openstack/configure-undercloud-to-store-events.adoc[]

[[add-openstack-oc]]
== Adding an OpenStack Cloud Provider

include::common/openstack/adding-an-openstack-cloud-provider.adoc[]

[[openstack-events-oc]]
=== Configuring the Overcloud to Store Events

include::common/openstack/configure-overcloud-to-store-events.adoc[]

[[perform-smartstate-analysis]]
== Performing a SmartState Analysis

Red Hat CloudForms can analyze a cloud Instance or infrastructure host to collect metadata such as user accounts, applications, software patches, and other internal information. This key CloudForms feature is called SmartState Analysis. SmartState analysis can be initiated manually or automatically using Control Policies.

include::common/smartstate-analysis-instances.adoc[]

[[using-the-topology-widget]]
== Using the Topology Widget

The *Topology* widget is an interactive topology graph, showing the status and relationships between the different resources and entities of the OpenStack providers that {product-title} has access to.

* The topology graph includes instances, nodes, and other cloud resources within the overall OpenStack cloud provider environment.
include::common/topology_widget.adoc[]

To view an OpenStack provider through the *Topology* widget:

. Navigate to menu:Compute[Cloud > Providers].
. Click the desired OpenStack cloud provider for viewing the provider summary.
. On the provider summary page, click *Topology* in the *Overview* box on the right-hand side of the page.

[[policies]]
== Managing Policies

include::topics/managing-policies.adoc[]

[[instances]]
== Managing Instances

Cloud instance provisioning goes through three phases:

. Request: This includes ownership information, tags, virtual hardware requirements, the operating system, and any customization required. See https://access.redhat.com/documentation/en-us/red_hat_cloudforms/4.6-beta/html-single/provisioning_virtual_machines_and_hosts/#provisioning-requests[Provisioning Requests] from the https://access.redhat.com/documentation/en-us/red_hat_cloudforms/4.6-beta/html-single/provisioning_virtual_machines_and_hosts/[Provisioning Virtual Machines and Hosts] guide for more details.
. Approval: Provisioning requests are then approved or denied. This phase can happen automatically or manually. See https://access.redhat.com/documentation/en-us/red_hat_cloudforms/4.6-beta/html-single/provisioning_virtual_machines_and_hosts/#provisioning-request-approval-methods[Provisioning Request Approval Methods] from the https://access.redhat.com/documentation/en-us/red_hat_cloudforms/4.6-beta/html-single/provisioning_virtual_machines_and_hosts/[Provisioning Virtual Machines and Hosts] guide for more details.
. Provision: Approved provisioning requests are executed. See https://access.redhat.com/documentation/en-us/red_hat_cloudforms/4.6-beta/html-single/provisioning_virtual_machines_and_hosts/#working-with-provisioning-requests[Working with Provisioning Requests] from the https://access.redhat.com/documentation/en-us/red_hat_cloudforms/4.6-beta/html-single/provisioning_virtual_machines_and_hosts/[Provisioning Virtual Machines and Hosts] guide for more details.

[[provisioning-an-openstack-instance-from-an-image]]
=== Provisioning an OpenStack Instance from an Image

include::common/provisioning-requests-openstack.adoc[]

[[storage_managers]]
== Managing Storage

include::common/openstack/storage-manager-available.adoc[]

For more information, see https://access.redhat.com/documentation/en-us/red_hat_cloudforms/4.6-beta/html-single/managing_providers/#storage_managers[Storage Managers] from the https://access.redhat.com/documentation/en-us/red_hat_cloudforms/4.6-beta/html-single/managing_providers/[Managing Providers] guide.

=== Managing Block Storage

The OpenStack Block Storage service (`openstack-cinder`) provides and manages persistent block storage resources that OpenStack infrastructure instances can consume. {product-title_short} provides an interface for managing these resources (volumes, volume backups, and volume snapshots).

To create a volume:

include::common/openstack/cinder-volume-create.adoc[]

To attach a volume to an instance (for example, one created through xref:provisioning-an-openstack-instance-from-an-image[]):

include::common/openstack/cinder-instance-attach.adoc[]

To view a timeline of storage manager events:

include::common/openstack/cinder-view-timeline.adoc[]

To back up a volume:

include::common/openstack/cinder-backup-create.adoc[]

To take a volume snapshot:

include::common/openstack/cinder-snapshot-create.adoc[]

For more information about available options for block storage resources in {product-title_short}, see https://access.redhat.com/documentation/en-us/red_hat_cloudforms/4.6-beta/html-single/managing_providers/#openstack_block_storage_managers[OpenStack Block Storage Managers] (from the https://access.redhat.com/documentation/en-us/red_hat_cloudforms/4.6-beta/html-single/managing_providers/[Managing Providers] guide).

=== Managing Object Storage

The OpenStack Object Storage (`openstack-swift`) service provides cloud object storage. The object store summary page shows details including the object store's size, parent cloud, storage manager, cloud tenant, and the number of cloud objects on the object store.

To view the summary page of an object store:

include::common/openstack/swift-view-stores.adoc[]

[[catalogs-services]]
== Catalogs and Services

include::topics/catalogs-services.adoc[]

[[_sect_reports]]
== Reports

include::topics/reports.adoc[]

[[_sect_chargeback]]
== Chargeback

include::topics/chargeback.adoc[]

/// [appendix]
[[provisioning-dialogs-customizing]]
== Customizing Provisioning Dialogs

include::common/provisioning-dialogs-customization.adoc[]

[[custom-button-tenants]]
== Creating Custom Buttons for Cloud Tenants

{product-title_short} also allows you to create _custom buttons_ for cloud tenants. This is useful for providing shortcuts to functionalities and features frequently used by specific tenants.

[NOTE]
==========
This capability is made possible through the _Automate_ model. See https://access.redhat.com/documentation/en-us/red_hat_cloudforms/4.6-beta/html-single/scripting_actions_in_cloudforms/#understanding-the-automate-model[Understanding the Automate Model] from the https://access.redhat.com/documentation/en-us/red_hat_cloudforms/4.6-beta/html-single/scripting_actions_in_cloudforms/[Scripting Actions in CloudForms] guide for more details.
==========

The following subsections summarize the two main steps for creating a custom button for cloud tenants.

[[create-custom-button-group]]
=== Creating a Custom Button Group

A _button group_ is a label for a collection of buttons under an _object type_. To create a button group:

include::common/automate-custom-button-group.adoc[]

The button group will show in the *Cloud Tenant* object type. When it does, create a custom button for any tenant within the OpenStack Cloud (see xref:create-a-custom-button[]).

[[create-a-custom-button]]
=== Creating a Custom Button

include::common/automate-custom-button.adoc[]

The button will show in the object type you added the button to. See https://access.redhat.com/documentation/en-us/red_hat_cloudforms/4.6-beta/html-single/scripting_actions_in_cloudforms/#invoking-automate[Invoking Automate] from the https://access.redhat.com/documentation/en-us/red_hat_cloudforms/4.6-beta/html-single/scripting_actions_in_cloudforms/[Scripting Actions in CloudForms] guide for more in-depth coverage.


[appendix]
[[provision-keypairs]]
== Managing Keypairs

include::common/provisioning-requests-keypairs.adoc[]


///////////////////////////////////////////////////
include::topics/Adding_OpenStack_Providers.adoc[]
include::topics/Adding_an_OpenStack_Infrastructure_Provider.adoc[]
include::topics/CFME_Lifecycle.adoc[]
include::topics/Provisioning_Requests.adoc[]
include::topics/Controlling_the_Power_State_of_an_Instance.adoc[]
include::topics/Viewing_Capacity_and_Utilization_Charts_for_an_Instance.adoc[]
include::topics/Further_reading.adoc[]


[[tenant-mapping]]
== Tenant Mapping

include::common/openstack/tenant-mapping.adoc[]

In previous releases, {product-title_short} and OpenStack tenants were disparate and unrelated entities. Tenant mapping creates a one-to-one association between tenants from both products.

=== Managing Tenants

You can manage tenants through two different sections of the {product-title_short} interface:

* To view OpenStack tenants, navigate to menu:Compute[Clouds > Tenants]
* To view the {product-title_short} tenants, navigate to menu:Compute[Administrator | EVM > Configuration]. Under the *Access Control* accordion, click *Tenants*. 

The {product-title_short} view provides a heirarchy, with the top _root_ level being the base {product-title_short} tenant. Every cloud provider is a child tenant of the base {product-title_short} tenant. Each OpenStack tenant is nested under its corresponding cloud provider. 



