[id='ref_Troubleshooting']
= Troubleshooting

[[Remigrating_Virtual_Machines]]
[discrete]
== Remigrating Virtual Machines

You can remigrate previously migrated virtual machines:

. Delete the target virtual machines corresponding to the source virtual machines that you are re-migrating. Otherwise, the remigration will fail because a target machine with the same name already exists.
. Delete the disks belonging to these virtual machines, which were created in the target datastore during the earlier migration, to free up space.
. Create a xref:CSV_file[CSV file] with the names and, optionally, providers, of the source virtual machines.
+
[NOTE]
====
The virtual machines cannot be discovered automatically by the migration plan because they are marked in the CloudForms VMDB as `migrated`.
====

. Create and run a new migration plan, using the CSV file to import the virtual machines.

[[Retrying_a_Migration_Plan]]
[discrete]
== Retrying a Migration Plan

If one or more virtual machines in a migration plan fails to migrate, the plan's migration status is `Failed`. You can retry a migration plan to migrate the virtual machines that failed to migrate:

. Click the migration plan to go to the details page to identify the virtual machines that failed to migrate.
. Delete the target virtual machines corresponding to the source virtual machines that failed to migrate. Otherwise, the retry will fail because a target machine with the same name already exists.
. Go to menu:Compute[Migration], select `Failed Migrations`, select the failed migration plan, and click `Retry`.

[discrete]
== Log Files

If a migration plan does not complete successfully, you can check the logs for errors:

* CloudForms migration log: `/var/www/miq/vmdb/log/automation.log`
* Conversion host logs: `/tmp`
* Virtual machine migration log: Click the migration plan to go to the details page and click `Download Log`.

[discrete]
== Common Issues and Mistakes

Incorrect infrastructure mapping::
If you create an infrastructure mapping and subsequently add or remove providers or provider objects, the infrastructure mapping will not work because the object IDs of the providers and their objects have changed. You must delete the infrastructure mapping and re-create it.

RHV host credentials not set in CloudForms::
If the RHV host credentials are not set, CloudForms cannot communicate with the hosts. To authenticate the RHV hosts with CloudForms, see link:https://access.redhat.com/documentation/en-us/red_hat_cloudforms/4.6/html-single/managing_providers/#authenticating_rhv_hosts[Authenticating Red Hat Virtualization Hosts] in _CloudForms: Managing Providers_.

Incorrect attributes in the virtual machine CSV import file::
Create a new migration plan, import the correct CSV file, and run the migration plan.
