[id='ref_Troubleshooting']
= Troubleshooting

[discrete]
== Re-migrating Virtual Machines

If a migration fails for any reason (for example, network communication between the source and target providers is disrupted during the migration process), you can re-migrate the virtual machines:

. Delete any target virtual machines that were created during the failed migration. Otherwise, the re-migration will fail because a target machine with the same name already exists.
. Delete disks that were created in the target datastore during the failed migration to free up space.
. Create a xref:CSV_file[CSV file] with the names and, optionally, providers, of the source virtual machines.
+
[NOTE]
====
The virtual machines cannot be discovered by the migration plan because they are marked in the CloudForms VMDB as `migrated`.
====

. Create and run a migration plan, using the CSV file to import the virtual machines.

[discrete]
== Log Files

If a migration plan does not complete successfully, check the logs for errors:

* CloudForms migration log: `/var/www/miq/vmdb/log/automation.log`
* Conversion host logs: `/tmp`

[discrete]
== Common Issues and Mistakes

Incorrect infrastructure mapping::
If you create an infrastructure mapping and subsequently add or remove providers or provider objects, the infrastructure mapping will not work because the object IDs of the providers and their objects have changed. You must delete the infrastructure mapping and re-create it.

RHV host credentials not set in CloudForms::
If the RHV host credentials are not set, CloudForms is unable to communicate with the hosts. To authenticate the RHV hosts with CloudForms, see link:https://access.redhat.com/documentation/en-us/red_hat_cloudforms/4.6/html-single/managing_providers/#authenticating_rhv_hosts[Authenticating Red Hat Virtualization Hosts] in _CloudForms: Managing Providers_.

Incorrect attributes in the virtual machine CSV import file::
Create a new migration plan, import the correct CSV file, and run the migration plan.
