[id="Uploading_the_virtio_and_guest_tool_image_files_to_the_storage_domain"]
= Uploading the VirtIO and Guest Tool Image Files to the Storage Domain

The `virtio-win` ISO and Virtual Floppy Drive (VFD) images contain the VirtIO drivers for Windows virtual machines. The `rhv-tools-setup` ISO contains the Red Hat Virtualization Guest Tools for Windows virtual machines. These image files provide software that can be installed on virtual machines to improve performance and usability.

Copy and upload the VirtIO and Guest Tool image files to the Manager's data storage domain:

. Using SCP, copy the following files from the Manager to your local machine:

* `/usr/share/virtio-win/virtio-win.iso`
* `/usr/share/virtio-win/virtio-win_x86.vfd`
* `/usr/share/virtio-win/virtio-win_amd64.vfd`
* `/usr/share/rhv-guest-tools-iso/rhv-tools-setup.iso`

. In the Administration Portal, click menu:Storage[Disks].
. Select *Start* from the *Upload* menu.
. Click *Choose File* and select an image to upload.
. Click *OK*.
+
A progress bar indicates the status of the upload. You can pause, cancel, or resume uploads from the *Upload* menu.

After uploading the image files to the Manager, you can install CloudForms.
