[[Creating_a_Migration_Plan]]
= Creating and Running a Migration Plan

Create and run a migration plan:

. Go to menu:Compute[Migration] and click *Create Migration Plan*.
. Select the infrastructure mapping from the drop-down list.
. Enter the name of your migration plan and click *Next*.
. Select *Choose from a list of VMs discovered in the selected infrastructure mapping* and click *Next*.
. Select the virtual machines to migrate and click *Next*.
. Select *Start Migration Immediately* and click *Create*.
. Click *Close*. The migration plan may take some time to complete. The "Migrations in Progress" message, the migration status, and the elapsed time are displayed.
+
You can view the status of the individual virtual machines in menu:Compute[Infrastructure > Hosts].
. Optional. You can view the progress of the migration in the CloudForms log:
+
----
# ssh _CloudForms_host_
# tail -f /var/www/miq/vmdb/log/automation.log
----
+
You can also view the progress of each virtual machine in the conversion host log *(%AP: When I checked the conversion host, there was no /import directory in the vdsm directory)*:
+
----
# ssh _conversion_host_
# tail -f /var/log/vdsm/import/*
----
+
When the migration is complete, a "Completed Migrations" message appears, with the number of successfully migrated virtual machines.

