[[Creating_a_Migration_Plan]]
= Creating and Running a Migration Plan

[discrete]
== Prerequisites

* If you are migrating a large number of virtual machines or you are re-migrating virtual machines after a failed migration, create a CSV file [[CSV_file]]containing a list of virtual machines to import.
+
The CSV file specifies the virtual machine names (mandatory) and providers (optional, for differentiating virtual machines with identical names), in the following format:
+
[options="nowrap" subs="+quotes,verbatim"]
----
Name, Provider
_vm01_, _vSphere3_
_vm02_, _vSphere3_
_vm03_, _vSphere3_
...
----

* Check the target datastore to ensure that there are no virtual machines with the same name as a virtual machine that is being migrated. A name conflict will cause the migration to fail.

If you are migrating a small number of virtual machines, you can use the migration plan to discover the virtual machines. The migration plan displays a list, from which you manually select the virtual machines to migrate.

[discrete]
== Procedure

. Go to menu:Compute[Migration] and click *Create Migration Plan*.

. Select the infrastructure mapping from the drop-down list.

. Enter the name of your migration plan.

. Discover the virtual machines:

* If you are using the migration plan to discover the virtual machines automatically:

.. Select *Choose from a list of VMs discovered in the selected infrastructure mapping*.
.. Click *Next*.

* If you are importing a CSV file:

.. (Optional) To validate your infrastructure mapping, select *Choose from a list of VMs discovered in the selected infrastructure mapping* and click *Next*. If your virtual machines appear in the list, the infrastructure mapping is correct. Click *Back*.
.. Select *Import a CSV file with a list of VMs to be migrated* and click *Next*.
.. Click *Import*, browse to the CSV file, and click *Open*.

. Select the virtual machines to migrate and click *Next*.

. Select *Start Migration Immediately* and click *Create*.

. Click *Close*. The migration plan may take some time to complete. *In Progress Plans*, the amount of data being transferred, the number of virtual machines being migrated, and the elapsed time are displayed.
+
When the migration is complete, the migration plan is displayed under *Completed Migrations*, with the number of successfully migrated virtual machines. A *Retry* option enables you to re-migrate any virtual machines in this plan that failed to migrate.

[NOTE]
====
During migration, the clock displaying the migration plan progress (in menu:Compute[Migration]) may be a few seconds ahead of the clock that appears in the migration plan details (menu:Compute[Migration>__Migration Plan__]). This is because the migration plan clock displays the total time to run the migration plan, while the migration plan details clock displays the total time to migrate the virtual machines.
====

[discrete]
== Advanced Migration: Automating Pre- and Post-Migration Tasks with Ansible

Certain tasks may need to be performed before or after a virtual machine is migrated, for example, removing web server virtual machines from a load-balancing pool before migration and adding them back to the pool after migration.

When you create a migration plan, there is an option to specify an Ansible service catalog item to be run before or after each virtual machine within the plan is migrated.

[NOTE]
====
You must create the Ansible service catalog items before you create a migration plan. See link:https://access.redhat.com/documentation/en-us/red_hat_cloudforms/4.6/html-single/provisioning_virtual_machines_and_hosts/#create-playbook-service-catalog-item[Creating an Ansible Playbook Service Catalog Item] for details.
====
