[[Creating_a_Migration_Plan]]
= Creating and Running a Migration Plan

If you are migrating a large number of virtual machines or you are re-migrating virtual machines after a failed migration, you must create a CSV file of virtual machines to import.

The CSV file specifies the virtual machine names (mandatory) and providers (optional, for differentiating virtual machines with identical names), in the following format:

[options="nowrap" subs="+quotes,verbatim"]
----
Name, Provider
_vm01_, _vSphere3_
_vm02_, _vSphere3_
_vm03_, _vSphere3_
...
----

If you are migrating a small number of virtual machines, follow the procedure below. The migration plan discovers the virtual machines, which you select manually.

[discrete]
== Procedure

. Go to menu:Compute[Migration] and click *Create Migration Plan*.

. Select the infrastructure mapping from the drop-down list.

. Enter the name of your migration plan.

. Discover the virtual machines to migrate:

* If you are migrating a small number of virtual machines:

.. Click *Next*.
.. Select *Choose from a list of VMs discovered in the selected infrastructure mapping* and click *Next*.

* If you are migrating a large number of virtual machines:[[CSV_import]]

.. (Optional) To validate your infrastructure mapping, select *Choose from a list of VMs discovered in the selected infrastructure mapping* and click *Next*. If your virtual machines appear in the list, the infrastructure mapping is correct. Click *Back*.
.. Select *Import a CSV file with a list of VMs to be migrated* and click *Next*.
.. Click *Import*, browse to the CSV file, and click *Open*.

. Select the virtual machines to migrate and click *Next*.

. *(%AP: TBD: Ansible pre and post playbooks with link to https://access.redhat.com/documentation/en-us/red_hat_cloudforms/4.6/html-single/creating_a_service_in_cloudforms_for_virtual_machine_provisioning/)*

. Select *Start Migration Immediately* and click *Create*.

. Click *Close*. The migration plan may take some time to complete. *In Progress Plans*, the status of the datastores and VMs, and the elapsed time are displayed.
+
When the migration is complete, *Completed Migrations* is displayed, with the number of successfully migrated virtual machines.
