[id="proc_Installing_cloudforms_automatically"]
= Installing CloudForms

CloudForms is installed with Ansible. The Ansible roles are located in +/usr/share/doc/ovirt-ansible-roles-_version_/examples+.

[discrete]
== Procedure

. Create a working directory on the Red Hat Virtualization Manager machine, for example, `/my_ansible`.

. In your working directory, create a `passwords.yml` file containing the Manager password:
+
[options="nowrap" subs="+quotes,verbatim"]
----
engine_password: _password_
----

. Encrypt `passwords.yml` with Ansible vault:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# ansible-vault encrypt passwords.yml
----
+
You will be asked for a vault password.

. Copy `manageiq.yml` to your current directory:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# cp /usr/share/doc/ovirt-ansible-roles-_version_/examples/manageiq.yml .
----

. Replace +_ovirt.example.com_+, +_miq_vm_name_+, and +_miq_vm_cluster_+ with the correct values in `manageiq.yml`:
+
[options="nowrap" subs="+quotes,verbatim"]
----
  vars:
    engine_fqdn: _ovirt.example.com_
    engine_user: admin@internal
    engine_cafile: /etc/pki/ovirt-engine/ca.pem

    miq_qcow_url: https://access.cdn.redhat.com//content/origin/files/sha256/eb/eb8af0fba78baac85eabd5b9ff30ba3191e6e00014528d55c36b673f5e6c762d/cfme-rhevm-5.9.2.4-1.x86_64.qcow2?_auth_=1531378089_ef400f29642f72d85f7784654124a611
    miq_vm_name: _manageiq_g2_
    miq_vm_cluster: _mycluster_
----

. Log into the link:https://access.redhat.com[Red Hat Customer Portal] so that the `manageiq` playbook can download the CloudForms image.

. Run the `manageiq` playbook, providing the vault password when prompted:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# ansible-playbook --ask-vault-pass manageiq.yml
----

After installing CloudForms, you will configure the RHV conversion hosts.

[discrete]
== Additional resources

* For more information, see link:https://github.com/oVirt/ovirt-ansible-manageiq/blob/master/README.md[Deploy ManageIQ in oVirt].
