[[Configuring-cloudforms]]
= Configuring the CloudForms Database

After installing CloudForms and running it for the first time, configure the internal database in which CloudForms stores information about the environment:

. Connect using SSH to the CloudForms machine and start the appliance console to display the console settings menu:
+
----
# appliance_console
----

. Press *Enter* to manually configure settings.
. Select *Configure Database* from the menu and press *Enter*.
. Select *Create key* and press *Enter*.
. Select *Create Internal Database* for the database location and press *Enter*.
. Choose a disk for the database and press *Enter*. This can be either a disk you attached previously, or a partition on the current disk.
+
[IMPORTANT]
====
Red Hat recommends using a separate disk for the database.
====
+
If there is an unpartitioned disk attached to the virtual machine, the dialog will show options similar to the following:

* `/dev/vdb: 20480`
* Don't partition the disk

. Select */dev/vdb* for the database location and press *Enter*.
+
This option creates a logical volume using this device and mounts the volume to the appliance in a location appropriate for storing the database. The default location is `/var/opt/rh/rh-postgresql95/lib/pgsql`, which can be found in the environment variable `$APPLIANCE_PG_MOUNT_POINT`.

. Enter `Y` to select *Should this appliance run as a standalone database server?*
. Create and confirm a password for the database.

CloudForms configures its internal database.
