[id="proc_Creating_rhv_conversion_hosts"]
= Creating RHV Conversion Hosts

All the virtual machines that are specified in a migration plan are migrated at the same time. Therefore, the number of RHV conversion hosts that you create depends on the number of virtual machines you intend to migrate.

Each conversion host is limited to 10 concurrent migrations, unless you change the default value (see xref:Configuring_the_maximum_number_of_concurrent_migrations[] below). Multiple conversion hosts are recommended, even for smaller migrations, for load-balancing purposes.

[NOTE]
====
The number of virtual machines that you can migrate at the same time depends on your infrastructure capabilities. Each migration requires a certain amount of network bandwidth, I/O throughput, and processing power for the conversion process. You should test your environment to understand how many migrations can occur simultaneously without negative effects.
====

Create one or more RHV conversion hosts:

. Log in to the link:https://www.vmware.com/support/developer/vddk/[VMware VDDK Documentation] site and download the latest VDDK package (for example, `VMware-vix-disklib-6.5.3-8315684.x86_64.tar.gz`) to your local machine.

. Using SCP, copy the VDDK package to `/var/www/html` on the Manager machine.

. Go to the conversion hosts directory on the Manager machine:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# cd /usr/share/ovirt-ansible-v2v-conversion-host-_version_/playbooks/
----

. Create a `conversion_hosts_inventory.yml` inventory file with the following variables:
+
[options="nowrap" subs="+quotes,verbatim"]
----
all:
  hosts:
    _host1.example.com_:
    _host2.example.com_:
  vars:
    ansible_ssh_private_key_file: /etc/pki/ovirt-engine/keys/engine_id_rsa
    v2v_vddk_package_name=VMware-vix-disklib-_version_.x86_64.tar.gz
    v2v_vddk_package_url=http://_Manager_FQDN_/VMware-vix-disklib-_version_.x86_64.tar.gz
----

. Enable the conversion hosts:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# ansible-playbook -i conversion_hosts_inventory.yml conversion_host_enable.yml
----

. Verify that the conversion hosts are enabled:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# ansible-playbook -i conversion_hosts_inventory.yml conversion_host_check.yml
----

After creating the RHV conversion hosts, you must configure them in CloudForms.

[NOTE]
====
If you upgrade your RHV environment, you must run the `conversion_host_enable` playbook again, with the option `-e v2v_vddk_override=true`, to update the IMS packages.
====

[discrete]
== Additional resources

* For more information, see link:https://github.com/oVirt/ovirt-ansible-v2v-conversion-host[V2V - Conversion Host - Ansible].
