[[Creating_a_Migration_Plan]]
= Creating and Running a Migration Plan

If you are migrating a large number of virtual machines or you are re-migrating virtual machines after a failed migration, you must create a CSV file of virtual machines to import.

The CSV file specifies the virtual machine names (mandatory) and providers (optional, for differentiating virtual machines with identical names), in the following format:

[options="nowrap" subs="+quotes,verbatim"]
----
Name, Provider
_vm01_, _vSphere3_
_vm02_, _vSphere3_
_vm03_, _vSphere3_
...
----

If you are migrating a small number of virtual machines, follow the procedure below. The migration plan discovers the virtual machines, which you select manually.

[discrete]
== Procedure

. Go to menu:Compute[Migration] and click *Create Migration Plan*.

. Select the infrastructure mapping from the drop-down list.

. Enter the name of your migration plan.

. Discover the virtual machines to migrate:

* If you are migrating a small number of virtual machines:

.. Click *Next*.
.. Select *Choose from a list of VMs discovered in the selected infrastructure mapping* and click *Next*.

* If you are migrating a large number of virtual machines:[[CSV_import]]

.. (Optional) To validate your infrastructure mapping, select *Choose from a list of VMs discovered in the selected infrastructure mapping* and click *Next*. If your virtual machines appear in the list, the infrastructure mapping is correct. Click *Back*.
.. Select *Import a CSV file with a list of VMs to be migrated* and click *Next*.
.. Click *Import*, browse to the CSV file, and click *Open*.

. Select the virtual machines to migrate and click *Next*.

. Select *Start Migration Immediately* and click *Create*.

. Click *Close*. The migration plan may take some time to complete. *In Progress Plans*, the status of the datastores and VMs, and the elapsed time are displayed.
+
When the migration is complete, *Completed Migrations* is displayed, with the number of successfully migrated virtual machines.

[NOTE]
====
During migration, the clock displaying the migration plan progress (in menu:Compute[Migration]) may be a few seconds ahead of the clock that appears in the migration plan details (menu:Compute[Migration>__Migration Plan__]). This is because the migration plan clock displays the total time to run the migration plan, while the migration plan details clock displays the total time to migrate the virtual machines.
====

[discrete]
== Advanced Migration: Automating Pre- and Post-Migration Tasks with Ansible

Certain tasks may need to be performed before or after a virtual machine is migrated, for example, removing web server virtual machines from a load-balancing pool before migration and adding them back to the pool after migration.

When you create a migration plan, there is an option to specify an Ansible service catalog item to be run before or after each virtual machine within the plan is migrated.

[NOTE]
====
You must create the Ansible service catalog items before you create a migration plan.
====

See link:[TBD] for details.
