[[Installing_Red_Hat_Virtualization_Manager]]
=== Installing Red Hat Virtualization Manager

The procedure for installing Red Hat Virtualization Manager has 5 key stages:

* Ensure that your system meets the prerequisites
* Enable the Manager repositories
* Install the Manager packages
* Configure the Manager
* Connect to the Administration Portal

[NOTE]
====
These procedures describe how to set up a basic Red Hat Virtualization environment with a local Manager database and Data Warehouse. For more options, see the link:https://access.redhat.com/documentation/en/red-hat-virtualization/[Red Hat Virtualization Documentation].
====

[discrete]
==== Prerequisites

Your system must meet the following minimum requirements to install the Red Hat Virtualization Manager:

* Hardware:
** CPU - Minimum: dual core. Recommended: quad core or multiple dual core CPUs.
** System RAM - Minimum: 4 GB. Recommended: 16 GB.
** Hard disk (locally accessible and writable) - Minimum: 25 GB. Recommended: 50 GB.
** Network Interface Card (NIC) - Minimum and recommended: Bandwidth of at least 1 Gbps.

* Browser: Latest version of Internet Explorer, Firefox, or Chrome.
* Operating system: Red Hat Enterprise Linux 7, updated to the latest minor release.
+
Do not install any additional packages after the base installation, as they may cause dependency issues when attempting to install the packages required by the Manager.
+
Do not enable additional repositories. The required repositories are specified in the next section, xref:Enabling_the_Manager_Repositories[Enabling the Manager Repositories].

[[Enabling_the_Manager_Repositories]]
[discrete]
==== Enabling the Manager Repositories

To install the Red Hat Virtualization packages, you must register the system with Red Hat Subscription Manager, attach the `Red Hat Enterprise Linux Server` and `Red Hat Virtualization` subscriptions, and enable the Manager repositories:

. Register your system with the Content Delivery Network, entering your Customer Portal user name and password when prompted: 
+
[options="nowrap" subs="+quotes,verbatim"]
----
# subscription-manager register
----

. Find the `Red Hat Enterprise Linux Server` and `Red Hat Virtualization` subscription pools and note down the pool IDs: 
+
[options="nowrap" subs="+quotes,verbatim"]
----
# subscription-manager list --available
----

. Use the pool IDs to attach the subscriptions to the system: 
+
[options="nowrap" subs="+quotes,verbatim"]
----
# subscription-manager attach --pool=_pool_id_
----
+
[NOTE]
====
To find out which subscriptions are currently attached, run:
[options="nowrap" subs="+quotes,verbatim"]
----
# subscription-manager list --consumed
----
To list all enabled repositories, run:
[options="nowrap" subs="+quotes,verbatim"]
----
# yum repolist
----
====

. Disable all existing repositories: 
+
[options="nowrap" subs="+quotes,verbatim"]
----
# subscription-manager repos --disable=*
----

. Enable the required repositories:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# subscription-manager repos --enable=rhel-7-server-rpms
# subscription-manager repos --enable=rhel-7-server-supplementary-rpms
# subscription-manager repos --enable=rhel-7-server-rhv-4.2-manager-rpms
# subscription-manager repos --enable=rhel-7-server-rhv-4-manager-tools-rpms
# subscription-manager repos --enable=rhel-7-server-ansible-2-rpms
# subscription-manager repos --enable=jb-eap-7-for-rhel-7-server-rpms
----

[discrete]
==== Installing the Manager Packages

. Update all packages on the machine where you are installing the Red Hat Virtualization Manager: 
+
[options="nowrap" subs="+quotes,verbatim"]
----
# yum update
----
+
[NOTE]
====
Reboot the machine if any kernel-related packages have been updated. *(%AP: Why don't we just tell them to reboot instead of making it optional? There are almost always kernel-related packages that are updated.)*
====
+
. Install the `rhvm` package and dependencies:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# yum install rhvm
----

[discrete]
==== Configuring the Manager

The `engine-setup` command asks you a series of configuration questions, applies that configuration, and starts the `ovirt-engine` service. `engine-setup` also creates and configures the Engine and Data Warehouse databases.

. Run the `engine-setup` command to begin configuration: 
+
[options="nowrap" subs="+quotes,verbatim"]
----
# engine-setup
----

. Press `Enter` to configure the Manager on your local host: 
+
[options="nowrap" subs="+quotes,verbatim"]
----
Configure Engine on this host (Yes, No) [Yes]:
----

. Press `Enter` to configure the Image I/O Proxy (`ovirt-imageio-proxy`), which enables the Manager to upload images to storage domains: 
+
[options="nowrap" subs="+quotes,verbatim"]
----
Configure Image I/O Proxy on this host? (Yes, No) [Yes]:
----

. Press `Enter` to configure a websocket proxy server, which enables users to connect to virtual machines via the noVNC or HTML 5 consoles: 
+
[options="nowrap" subs="+quotes,verbatim"]
----
Configure WebSocket Proxy on this machine? (Yes, No) [Yes]:
----

. Press `Enter` to configure the Data Warehouse on the Manager machine:
+
[options="nowrap" subs="+quotes,verbatim"]
----
Please note: Data Warehouse is required for the engine. If you choose to not configure it on this host, you have to configure it on a remote host, and then configure the engine on this host so that it can access the database of the remote Data Warehouse host. 
Configure Data Warehouse on this host (Yes, No) [Yes]:
----

. Press `Enter` to enable access to a virtual machines's serial console from the command line:
+
[options="nowrap" subs="+quotes,verbatim"]
----
Configure VM Console Proxy on this host (Yes, No) [Yes]:
----

. Press `Enter` to install Open Virtual Network (OVN) as an external network provider:
+
[options="nowrap" subs="+quotes,verbatim"]
----
Configure ovirt-provider-ovn (Yes, No) [Yes]:
----
+
The default cluster uses OVN as its default network provider. Hosts added to the default cluster are automatically configured to communicate with OVN.

. Press `Enter` to accept the automatically detected host name or enter an alternative host name and press `Enter`:
+
[options="nowrap" subs="+quotes,verbatim"]
----
Host fully qualified DNS name of this server [_autodetected host name_]: 
----
+
If you are using virtual hosts, the automatically detected host name may be incorrect.

. Press `Enter` to configure Firewalld as the default firewall:
+
[options="nowrap" subs="+quotes,verbatim"]
----
Setup can automatically configure the firewall on this system.
Note: automatic configuration of the firewall may overwrite current settings.
NOTICE: iptables is deprecated and will be removed in future releases
Do you want Setup to configure the firewall? (Yes, No) [Yes]:
----

. Press `Enter` to create a local Data Warehouse database:
+
[options="nowrap" subs="+quotes,verbatim"]
----
Where is the DWH database located? (Local, Remote) [Local]:
----

. Press `Enter` to automatically configure the Data Warehouse database:
+
----
Setup can configure the local postgresql server automatically for the DWH to run. This may conflict with existing applications.
Would you like Setup to automatically configure postgresql and create DWH database, or prefer to perform that manually? (Automatic, Manual) [Automatic]:
----

. Press `Enter` to create a local Engine database: 
+
[options="nowrap" subs="+quotes,verbatim"]
----
Where is the Engine database located? (Local, Remote) [Local]:
----

. Press `Enter` to create and configure the Engine database automatically:
+
[options="nowrap" subs="+quotes,verbatim"]
----
Setup can configure the local postgresql server automatically for the engine to run. This may conflict with existing applications.
Would you like Setup to automatically configure postgresql and create Engine database, or prefer to perform that manually? (Automatic, Manual) [Automatic]:
----

. Set a password for the automatically created administrative user of the Red Hat Virtualization Manager and press `Enter`:
+
[options="nowrap" subs="+quotes,verbatim"]
----
Engine admin password:
Confirm engine admin password:
----

. Press `Enter` to select both Virt and Gluster modes: 
+
[options="nowrap" subs="+quotes,verbatim"]
----
Application mode (Both, Virt, Gluster) [Both]:
----

. If you installed the OVN provider, press `Enter` to accept the default OVN provider user and specify the OVN provider password:
+
[options="nowrap" subs="+quotes,verbatim"]
----
Use default credentials (admin@internal) for ovirt-provider-ovn (Yes, No) [Yes]:
oVirt OVN provider user[admin@internal]: 
oVirt OVN provider password: 
----

. Press `Enter` to set the default value for the `wipe_after_delete` flag, which wipes the blocks of a virtual disk when the disk is deleted, to `No`: 
+
[options="nowrap" subs="+quotes,verbatim"]
----
Default SAN wipe after delete (Yes, No) [No]:
----

. The Manager uses certificates to communicate securely with its hosts. Press `Enter` to accept the auto-detected domain name for the certificate:
+
[options="nowrap" subs="+quotes,verbatim"]
----
Organization name for certificate [_autodetected domain-based name_]:
----

. Press `Enter` to make the welcome page of the Manager the default page presented by the Apache web server:
+
[options="nowrap" subs="+quotes,verbatim"]
----
Setup can configure the default page of the web server to present the application home page. This may conflict with existing applications.
Do you wish to set the application as the default web page of the server? (Yes, No) [Yes]:
----

. Press `Enter` to secure external SSL (HTTPS) communication between the Manager and the hosts using the self-signed certificate created earlier in the configuration:
+
[options="nowrap" subs="+quotes,verbatim"]
----
Setup can configure apache to use SSL using a certificate issued from the internal CA.
Do you wish Setup to configure that, or prefer to perform that manually? (Automatic, Manual) [Automatic]:
----

. Press `Enter` to configure the Data Warehouse sampling scale:

+
[options="nowrap" subs="+quotes,verbatim"]
----
Please choose Data Warehouse sampling scale:
(1) Basic
(2) Full
(1, 2)[1]:
----
`Basic` reduces the values of `DWH_TABLES_KEEP_HOURLY` to `720` and `DWH_TABLES_KEEP_DAILY` to `0`, easing the load on the Manager machine. This is recommended when the Manager and Data Warehouse are installed on the same machine.

. Review the installation settings and press `Enter` to accept the values and proceed with the installation: 
+
[options="nowrap" subs="+quotes,verbatim"]
----
Please confirm installation settings (OK, Cancel) [OK]:
----
+
When your environment has been configured, `engine-setup` displays details about how to access your environment. `engine-setup` saves your answers to a file that can be used to reconfigure the Manager using the same values and outputs the location of the log file for the Red Hat Virtualization Manager configuration process.

. If you intend to connect your Red Hat Virtualization environment with a directory server, synchronize the system clock with a remote NTP server, to avoid unexpected account expiry issues:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# timedatectl set-ntp yes
----
You must have an NTP service, such as chrony, installed and running.

. Install the certificate authority according to the instructions provided by your browser. You can obtain the certificate authority's certificate by going to `http://_your-manager-fqdn_/ovirt-engine/services/pki-resource?resource=ca-certificate&amp;format=X509-PEM-CA`, replacing _your-manager-fqdn_ with the fully qualified domain name (FQDN) that you provided during the installation.

Proceed to the next section to connect to the Administration Portal as the *admin@internal* user.

