[id="Configuring_rhv_conversion_hosts_in_CloudForms"]
= Configuring RHV Conversion Hosts in CloudForms

You must configure the RHV conversion hosts in CloudForms:

. Go to menu:Compute[Infrastructure > Hosts] and select a Red Hat Virtualization Host.
. Click the `Policy` drop-down button and select `Edit Tags`.
. Select `V2V - Transformation Host` from the tag drop-down list and `t` as the assigned value.
. Select `V2V - Transformation Method` from the tag drop-down list and either `VDDK` or `SSH` as the assigned value.
+
[NOTE]
====
VDDK is approximately twice as fast as SSH.
====

. Click `Save`.
. Select the same host, click the `Configuration` drop-down button, and select `Edit this item`.
. In the `Default` tab of the Endpoints section, enter the `Username` *root* and the password.
. Click `Validate`. If a success message is displayed, click `Save`.

If you are using `VDDK` transformation, go to xref:Discovery_and_Assessment[]. If you are using `SSH` transformation, go to xref:Configuring_rhv_conversion_hosts_for_ssh_transformation[].
