[id="proc_Installing_cloudforms_automatically"]
= Installing CloudForms Automatically

*(%AP: This section needs to be reviewed. Moran Goldboim says the user needs to sign into the Customer Portal. When does this step occur?)*

CloudForms is installed automatically using the oVirt Ansible role, `oVirt.manageiq`. The conversion host is created with the `conversion_host_enable` playbook.

Ansible roles are located in +/usr/share/doc/ovirt-ansible-roles-_version_/examples+.

[discrete]
== Procedure

. Create a working directory on the Red Hat Virtualization Manager machine, for example, `/my_ansible`.

. In your working directory, create a `passwords.yml` file containing the engine password:
+
[options="nowrap" subs="+quotes,verbatim"]
----
engine_password: _password_
----

. Encrypt `passwords.yml` with Ansible vault:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# ansible-vault encrypt passwords.yml
----
+
You will be asked for a vault password.

. Copy `manageiq.yml`, `conversion_host_enable.yml`, and `conversion_host_check.yml` to your current directory:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# cp /usr/share/doc/ovirt-ansible-roles-_version_/examples/{manageiq.yml,conversion_host_enable.yml,conversion_host_check.yml} .

----

. Replace +_ovirt.example.com_+ in `manageiq.yml` with the FQDN of the Manager machine:
+
[options="nowrap" subs="+quotes,verbatim"]
----
  vars:
    engine_fqdn: _ovirt.example.com_
    engine_user: admin@internal
    engine_cafile: /etc/pki/ovirt-engine/ca.pem
----

. Run the `manageiq` playbook, providing the vault password when prompted:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# ansible-playbook --ask-vault-pass manageiq.yml
----

. Add your host names or IP addresses to `/etc/ansible/hosts`.

. Download the latest VMware VDDK package from link:https://www.vmware.com/support/developer/vddk/[https://www.vmware.com/support/developer/vddk/]. *(%AP: do we need to specify a version or is 'latest' OK?)*

. Use SCP to copy the VMware VDDK package to the Manager machine.

. Run the `conversion_host_enable` playbook:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# ansible-playbook -i _conversion_host_ or _ansible_host_file_, conversion_host_enable.yml -e 'v2v_vddk_package_name=_vddk_package_name_.tar.gz' -e 'v2v_vddk_package_url=http://_hostname_to_package_location_/vddk/VMware-vix-disklib-stable.tar.gz'
----
*(%AP: What is the vddk package url supposed to be? Package path on Manager? Or conversion host? Is there a comma after `-i _conversion_host_ or _ansible_host_file_`? What is the 'conversion_host' file? For 'ansible_host_file', can we use /etc/ansible/hosts?)*

. Run the `conversion_host_check` playbook to verify that the conversion host is enabled:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# ansible-playbook conversion_host_check.yml
----

[discrete]
== Additional resources

* For more details, see link:https://github.com/oVirt/ovirt-ansible-manageiq/blob/master/README.md[Deploy ManageIQ in oVirt].
