[id="proc_Configuring_rhv_conversion_hosts"]
= Configuring Red Hat Virtualization Conversion Hosts

Create one or more Red Hat Virtualization conversion hosts.

[discrete]
== Prerequisites

. Log into the link:https://www.vmware.com/support/developer/vddk/[VMware VDDK Documentation] site and download the latest VDDK package (for example, `VMware-vix-disklib-6.5.3-8315684.x86_64.tar.gz`).

. Using SCP, copy the VDDK package to `/var/www/html` on the Manager machine.

. Generate an SSH key for the Manager machine and copy it to each RHV conversion host.

[discrete]
== Procedure

. Copy the conversion host playbooks to your current directory:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# cp /usr/share/doc/ovirt-ansible-v2v-conversion-host-_version_/examples/{conversion_host_enable.yml,conversion_host_check.yml} .
----

. Create a `conversion_hosts` inventory file:
+
[options="nowrap" subs="+quotes,verbatim"]
----
all:
  vars:
    v2v_repo_rpms_name: "v2v-nbdkit-rpms"
    v2v_repo_srpms_name: "v2v-nbdkit-src-rpms"
    v2v_vddk_package_name: "_VMware-vix-disklib-6.5.2-6195444.x86_64.tar.gz_"
  hosts:
    _conversion_host1.com_:
    _conversion_host2.com_:
----

. Enable the conversion hosts:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# ansible-playbook -i conversion_hosts conversion_host_enable.yml
----

. Verify that the conversion hosts are enabled:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# ansible-playbook conversion_host_check.yml
----

After configuring the conversion hosts, you can configure CloudForms.

[discrete]
== Additional resources

* For more information, see link:https://github.com/oVirt/ovirt-ansible-v2v-conversion-host[V2V - Conversion Host - Ansible]
