[[Adding_a_host_to_the_Manager]]
= Adding a Host to the Red Hat Virtualization Manager

[NOTE]
====
Adding a host to your Red Hat Virtualization environment can take some time, as the following steps are completed by the platform: virtualization checks, installation of packages, and creation of a bridge.
====

Add a host to the Manager:

. In the Administration Portal, click menu:Compute[Hosts].
. Click btn:[New].
. Use the drop-down list to select the *Data Center* and *Host Cluster* for the new host.
. Enter the *Name* and the *Address* of the new host. The standard SSH port, port 22, is auto-filled in the *SSH Port* field.
. Enter the `root` password.
. Click btn:[OK]. The power management reminder is displayed.
. Click btn:[OK].
+
The new host appears in the list of hosts with the status, `Installing`, and you can view the progress of the installation in the details pane. After a brief delay the host status changes to *Up*.

[IMPORTANT]
====
Keep the environment up-to-date. See link:https://access.redhat.com/articles/2974891[] for more information. Since bug fixes for known issues are frequently released, Red Hat recommends using scheduled tasks to update the hosts and the Manager.
====

