[[Storage]]
=== Adding Storage

You must attach at least one storage domain to each data center. Setting up storage is a prerequisite for a new data center because a data center cannot be initialized unless storage domains are attached and activated. A storage domain can be made of either block devices (iSCSI or Fibre Channel) or a file system.

[IMPORTANT]
====
Red Hat Virtualization currently does not support storage with a block size of 4K. You must configure block storage in legacy (512b block) mode. 
====

This document describes how to add NFS storage. For other storage types, click the link for documentation:

* xref:Adding_NFS_Storage[NFS]
* xref:iSCSI[iSCSI]
* xref:fc[Fibre Channel]
* xref:FCoE[Fibre Channel over Ethernet]
* xref:Gluster[Red Hat Gluster Storage]
* xref:Ceph[Red Hat Ceph File System]
* xref:POSIX[POSIX-Compliant FS]
* xref:local[Local Storage]

For more information about storage, see:

* link:https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.2/html/administration_guide/chap-storage[Storage] in the _Administration Guide_.

* link:https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Storage_Administration_Guide/index.html[_Red Hat Enterprise Linux Storage Administration Guide_].

include::proc_Adding_NFS_Storage.adoc[]

==== Adding Other Storage

This section describes other forms of storage that are supported by Red Hat Virtualization.

[[iSCSI]]
[discrete]
==== iSCSI

Production workloads require an enterprise-grade iSCSI server. When enterprise iSCSI is deployed over 10 GbE, segregated with VLANs, and with CHAP authentication, it is both fast and secure. iSCSI can also use multipathing to improve high availability.

Red Hat Virtualization supports 1500 logical volumes per block-based storage domain. No more than 300 LUNs are permitted.

See:

* link:https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.2/html-single/administration_guide/#Adding_iSCSI_Storage1[Adding iSCSI Storage] in the _Administration Guide_.

* link:https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Storage_Administration_Guide/ch24.html[Online Storage Management] in the _Red Hat Enterprise Linux Storage Administration Guide_ for general information.

include::ref_Storage_to_CF_link.adoc[]

[[fc]]
[discrete]
==== Fibre Channel

Fibre Channel is both fast and secure, and should be taken advantage of if it is already used in the target data center. It also has the advantage of low CPU overhead, compared to iSCSI and NFS. Fibre Channel can also use multipathing to improve high availability.

Red Hat Virtualization supports 1500 logical volumes per block-based storage domain. No more than 300 LUNs are permitted.

See:

* link:https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.2/html-single/administration_guide/#Adding_FCP_Storage[Adding FCP Storage] in the _Administration Guide_.

* link:https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Storage_Administration_Guide/ch24.html[Online Storage Management] in the _Red Hat Enterprise Linux Storage Administration Guide_ for general information.

include::ref_Storage_to_CF_link.adoc[]

[[FCoE]]
[discrete]
==== Fibre Channel over Ethernet

To use Fibre Channel over Ethernet (FCoE) in Red Hat Virtualization, you must enable the *fcoe* key on the Manager, and install the _vdsm-hook-fcoe_ package on the hosts. 

Red Hat Virtualization supports 1500 logical volumes per block-based storage domain. No more than 300 LUNs are permitted.

See:

* link:https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.2/html-single/administration_guide/#How_to_Set_Up_RHVM_to_Use_FCoE[How to Set Up Red Hat Virtualization Manager to Use FCoE] in the _Administration Guide_.

* link:https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Storage_Administration_Guide/ch24.html[Online Storage Management] in the _Red Hat Enterprise Linux Storage Administration Guide_ for general information.

include::ref_Storage_to_CF_link.adoc[]

[[Gluster]]
[discrete]
==== Red Hat Gluster Storage

Red Hat Gluster Storage (RHGS) is a POSIX-compliant, open-source file system. Three or more servers are configured as a Red Hat Gluster Storage cluster, instead of network-attached storage (NAS) appliances or a storage area network (SAN) array.

Red Hat Gluster Storage should be utilized over 10 GbE and segregated with VLANs.

Check the compatibility matrix in link:https://access.redhat.com/articles/2356261[] before using RHGS with Red Hat Virtualization.

See: 

* link:https://access.redhat.com/documentation/en-us/red_hat_gluster_storage/3.2/html/configuring_red_hat_virtualization_with_red_hat_gluster_storage/[_Configuring Red Hat Virtualization with Red Hat Gluster Storage_]

* link:https://access.redhat.com/documentation/en-us/red-hat-gluster-storage/[Red Hat Gluster Storage] for general information.

include::ref_Storage_to_CF_link.adoc[]

[[Ceph]]
[discrete]
==== Red Hat Ceph File System

Red Hat Ceph File System (CephFS) is a file system compatible with POSIX standards that uses a Ceph Storage Cluster to store its data. No special configuration is required on the Red Hat Virtualization side when adding CephFS as a storage domain. It is added the same way as any other POSIX-compliant FS storage. 

* link:https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.2/html-single/administration_guide/#sect-Preparing_and_Adding_POSIX_Compliant_File_System_Storage[Adding POSIX Compliant File System Storage] in the _Administration Guide_.

include::ref_Storage_to_CF_link.adoc[]

[[POSIX]]
[discrete]
==== POSIX-Compliant FS

Other POSIX-compliant file systems can be used as storage domains in Red Hat Virtualization, as long as they are clustered file systems, such as Red Hat Global File System 2 (GFS2), and support sparse files and direct I/O. The Common Internet File System (CIFS), for example, does not support direct I/O, making it incompatible with Red Hat Virtualization. 

See:

* link:https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Global_File_System_2/index.html[_Red Hat Enterprise Linux Global File System 2_]

* link:https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.2/html-single/administration_guide/#sect-Preparing_and_Adding_POSIX_Compliant_File_System_Storage[Adding POSIX Compliant File System Storage] in the _Administration Guide_.

include::ref_Storage_to_CF_link.adoc[]

[[local]]
[discrete]
==== Local Storage

Local storage is set up on an individual host, using the host's own resources. When you set up a host to use local storage, it is automatically added to a new data center and cluster that no other hosts can be added to. Virtual machines created in a single-host cluster cannot be migrated, fenced, or scheduled.

For Red Hat Virtualization Hosts, local storage should always be defined on a file system that is separate from / (root). Red Hat recommends using a separate logical volume or disk. 

See: link:https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.2/html-single/administration_guide/#sect-Preparing_and_Adding_Local_Storage[Preparing and Adding Local Storage] in the _Administration Guide_.

include::ref_Storage_to_CF_link.adoc[]

