= Method Hierarchy

The Automate Model inline methods have a hierarchy.
The sublevels in the hierarchy have access to the methods for itself and the levels above it.
For example, Red Hat Hosts have access to the Red Hat Host methods, Host Methods, and Base Methods. 

The following nested list displays the hierarchy.
Certain methods in this list have links to additional methods detailed in this book.
Methods without links do not have any additional methods. 

* Top Level: Base - <<_base_methods,Base Methods>>			
+
* Authentication (authentication) 
+
* Private Keys (auth_private_key) 
+
* Key Pair for Clouds (auth_key_pair_cloud) 
+
* Amazon (auth_key_pair_amazon) 
* OpenStack (auth_key_pair_openstack) 



* Availability Zones (availability_zone) - <<_availability_zones_availability_zone,Availability Zones availability zone>>					
+
* Amazon (availability_zone_amazon) 
* OpenStack (availability_zone_openstack) 

* Classification (classification) - <<_classifications_classification,Classifications classification>>					
* Cloud Networks (cloud_network) - <<_cloud_networks_cloud_network,Cloud Networks cloud network>>					
* Cloud Resource Quotas (cloud_resource_quota) - <<_cloud_resource_quotas_cloud_resource_quota,Cloud Resource Quotas cloud resource quota>>					
+
* OpenStack (openstack_resource_quota) 

* Cloud Subnets (cloud_subnet) - <<_cloud_subnets_cloud_subnet,Cloud Subnets cloud subnet>>					
* Cloud Tenants (cloud_tenant) - <<_cloud_tenants_cloud_tenant,Cloud Tenants cloud tenant>>					
* Customization Templates (customization_template) - <<_customization_template,Customization template>>					
+
* Cloud Init (customization_template_cloud_init) 
* Kickstart (customization_template_kickstart) 
* Sysprep (customization_template_sysprep) 

* Cluster (ems_cluster) - <<_sect_clusters_ems_cluster,sect-Clusters ems cluster>>					
* Event (ems_event) - <<_management_system_events_ems_event,Management System Events ems event>>					
* Folder (ems_folder) - <<_management_system_folders_ems_folder,Management System Folders ems folder>>					
* Providers (ext_management_system) - <<_sect_providers_ext_management_system,sect-Providers ext management system>>					
+
* Cloud (ems_cloud) 
+
* Amazon (ems_amazon) 
* OpenStack (ems_openstack) 

* Infrastructue (ems_infra) 
+
* Microsoft System Center VMM (ems_microsoft) 
* Red Hat Enterprise Virtualization (ems_redhat) 
* VMware vCenter (ems_vmware) 


* Filesystems (filesystem) 
* Firewall Rules (filewall_rule) - <<_firewall_rules_firewall_rule,Firewall Rules firewall rule>>					
* Flavors - <<_flavors_flavor,Flavors flavor>>					
+
* Amazon (flavor_amazon) 
* OpenStack (flavor_openstack) 

* Floating IPs (floating_ip) - <<_floating_ips_floating_ip,Floating IPs floating ip>>					
+
* Amazon (floating_ip_amazon) 
* OpenStack (floating_ip_openstack) 

* Guest Applications (guest_application) - <<_guest_applications_guest_application,Guest Applications guest application>>					
* Guest Devices (guest_device) - <<_guest_device_guest_device,Guest Device guest device>>					
* Hardware (hardware) - <<_hardware_hardware,Hardware hardware>>					
* Hosts (host) - <<_sect_hosts_host,sect-Hosts host>>					
+
* Red Hat Enterprise Virtualization (host_redhat) 
* VMware (host_vmware) 
+
* VMware ESX (host_vmware_esx) - <<_hosts_vmware_esx_host_vmware_esx,Hosts Vmware ESX host vmware esx>>									


* ISO Images (iso_image) 
* Jobs (job) 
* LANs (lan) - <<_lan_lan,LAN lan>>					
* Groups (miq_group) - <<_sect_groups_miq_group,sect-Groups miq group>>					
* Policies (miq_policy) 
* Proxies (miq_proxy) - <<_proxies_miq_proxy,Proxies miq proxy>>					
* Requests (miq_request) - <<_sect_request_miq_request,sect-Request miq request>>					
+
* Automation (automation_request) - <<_automation_request,Automation request>>							
* Host Provisioning (miq_host_provision_request) - <<_miq_host_provision_request,Miq host provision request>>							
* VM Provisioning (miq_provision_request) - <<_miq_provision_request,Miq provision request>>							
+
* VM Templates (miq_provision_request_template) 

* Service Reconfiguration (service_reconfigure_request) 
* Service Template Provisioning (service_template_provision_request) 
* VM Migration (vm_migrate_request) 
* VM Reconfiguration (vm_reconfigure_request) 

* Request Task (miq_request_task) - <<_sect_request_task_miq_request_task,sect-Request Task miq request task>>					
+
* Automation (automation_task) - <<_automation_task,Automation task>>							
* Host Provisioning (miq_host_provision) - <<_miq_host_provision,Miq host provision>>							
* VM Provisioning (miq_provision) - <<_sect_vm_provision_task_miq_provision,sect-VM Provision Task miq provision>>							
+
* Cloud (miq_provision_cloud) - <<_vm_provisioning_for_clouds_task_miq_provision_cloud,VM Provisioning for Clouds Task miq provision cloud>>									
+
* Amazon (miq_provision_amazon) 
* OpenStack (miq_provision_openstack) 

* Red Hat Enterprise Virtualization (miq_provision_redhat) 
+
* Via ISO (miq_provision_redhat_via_iso) 
* Via PXE (miq_provision_redhat_via_pxe) 

* VMware (miq_provision_vmware) 
+
* Via NetApp RCU (miq_provision_vmware_via_net_app_rcu) 
* Via PXE (miq_provision_vmware_via_pxe) 


* Service Reconfiguration (service_reconfigure_task) - <<_service_reconfiguration_task_service_reconfigure_task,Service Reconfiguration Task service reconfigure task>>							
* Service Template Provisioning (service_template_provision_task) - <<_service_template_provision_task,Service template provision task>>							
* VM Migratation (vm_migrate_task) - <<_vm_migrate_task,Vm migrate task>>							
* VM Reconfiguration (vm_reconfigure_task) 

* Servers (miq_server) - <<_sect_servers_miq_server,sect-Servers miq server>>					
* Networks (network) - <<_network_network,Network network>>					
* Operating Systems (operating_system) 
* PXE Images (pxe_image) - <<_pxe_image,Pxe image>>					
+
* iPXE (pxe_image_ipxe) 
* PXELINUX (pxe_image_pxelinux) 

* PXE Servers (pxe_server) - <<_pxe_server,Pxe server>>					
* Resource Pools (resource_pool) 
* Security Groups (security_group) - <<_security_groups_security_group,Security Groups security group>>					
+
* Amazon (security_group_amazon) 
* OpenStack (security_group_openstack) 

* Services (service) - <<_service2,Service2>>					
* Service Resources (service_resource) - <<_service_resource_service_resource,Service Resource service resource>>					
* Service Templates (service_template) - <<_service_template,Service Template>>					
* Snapshots (snapshot) - <<_snapshot_snapshot,Snapshot snapshot>>					
* Storages (storage) - <<_sect_datastores_storage,sect-Datastores storage>>					
* Switches (switch) - <<_switch_switch,Switch switch>>					
* Users (user) - <<_sect_user_user,sect-User user>>					
* VMs or Templates (vm_or_template) - <<_sect_virtual_machines_and_templates_vm_or_template,sect-Virtual Machines and Templates vm or template>>					
+
* Templates (miq_template) 
+
* Cloud (template_cloud) 
+
* Amazon (template_amazon) 
* OpenStack (template_openstack) 

* Infrastructure (template_infra) 
+
* Microsoft (template_microsoft) 
* Red Hat Enterprise Virtualization (template_redhat) 
* VMware (template_vmware) 


* VMs (vm) - <<_sect_vms_vm,sect-VMs vm>>							
+
* Clouds (vm_cloud) - <<_vms_for_clouds_vm_cloud,VMs for Clouds vm cloud>>									
+
* Amazon (vm_amazon) 
* OpenStack (vm_openstack) 

* Infrastructure (vm_infra) 
+
* Microsoft (vm_microsoft) 
* Red Hat Enterprise Virtualization (vm_redhat) 
* Vmware (vm_vmware) 



* Windows Images (windows_images) - <<_windows_image,Windows image>>					
