[[_chap_methods_available_for_use_with_cloudforms_management_engine]]
== Methods Available for Use with {product-title}

Methods can be used from within {product-title} to create custom actions and workflows for the objects managed for your {product-title} Infrastructure.
This document describes the methods available for use in {product-title}.
This document is organized by the object hierarchy in the Automate Model. 

[NOTE]
====
Users of {product-title} can construct custom automation methods in Ruby to extend the product.
{product-title} ships with a core set of Ruby gems used by the {product-title} Rails Application.
The Ruby gems in this set are subject to change, and have changed since the previous version. If you are calling gems using Automate that are no longer in the {product-title} appliance, you can install them by using the `gem install` command. 

While gems can be imported into automation methods using `require`, it is recommended that the authors of the automation methods clearly document the use of gems either in the core set or a custom set.
It is the responsibility of the author of such custom automation to own the life cycle of any gem being referenced in those methods. 

ifdef::cfme[]
The link:https://access.redhat.com/documentation/en/red-hat-cloudforms/4.7/release-notes/release-notes[Red Hat CloudForms 4.7 Release Notes], list Ruby gems that have been added, updated, or removed in the latest version of CloudForms Management Engine.

For lists of Ruby gems included in different CloudForms Management Engine releases, see the following article:

* https://access.redhat.com/articles/1534753
endif::cfme[]
====

include::About_evm.root.adoc[]

include::Method_Hierarchy.adoc[]

include::Base_Methods.adoc[]

include::Availability_Zones_availability_zone.adoc[]

include::Classifications_classification.adoc[]

include::Cloud_Networks_cloud_network.adoc[]

include::Cloud_Resource_Quotas_cloud_resource_quota.adoc[]

include::Cloud_Subnets_cloud_subnet.adoc[]

include::Cloud_Tenants_cloud_tenant.adoc[]

include::Customization_template.adoc[]

[[_sect_clusters_ems_cluster]]
=== Clusters (ems_cluster)

[cols="1,1", frame="all", options="header"]
|====
| 
							
								Method
							
						
| 
							
								Use
							
						

| 
							
								all_resource_pools
							
						
| 
							
								Return all of the objects Resource Pools
							
						

| 
							
								all_vms
							
						
| 
							
								Return all of the objects Virtual Machines
							
						

| 
							
								default_resource_pool
							
						
| 
							
								Return the objects default Resource Pool
							
						

| 
							
								ems_events
							
						
| 
							
								Returns an array of EmsEvent records associated with the object
							
						

| 
							
								ext_management_system
							
						
| 
							
								Return objects Management System
							
						

| 
							
								hosts
							
						
| 
							
								Return objects Hosts
							
						

| 
							
								parent_folder
							
						
| 
							
								Return objects Parent Folder
							
						

| 
							
								register_host(host)
							
						
| 
							
								Register Host to this Cluster
							
						

| 
							
								resource_pools
							
						
| 
							
								Return objects Resource Pools
							
						

| 
							
								storages
							
						
| 
							
								Return objects datastores
							
						

| 
							
								vms
							
						
| 
							
								Return objects Virtual Machines
							
						
|====


[source,ruby]
----


  #########################
  #
  # Method: dumpCluster
  # Inputs: $evm.root['ems_cluster']
  # Description: Dump Cluster information
  #
  ##########################
  def dumpCluster(cluster)
    $evm.log("info","#{@log_prefix} - Cluster:<#{cluster.name}> Begin Attributes")
    cluster.attributes.sort.each { |k, v| $evm.log("info", "#{@log_prefix} - Cluster:<#{cluster.name}> Attributes - #{k}: #{v.inspect}")}
    $evm.log("info","#{@log_prefix} - Cluster:<#{cluster.name}> End Attributes")
    $evm.log("info","")

    $evm.log("info","#{@log_prefix} - Cluster:<#{cluster.name}> Begin Associations")
    cluster.associations.sort.each { |assc| $evm.log("info", "#{@log_prefix} - Cluster:<#{cluster.name}> Associations - #{assc}")}
    $evm.log("info","#{@log_prefix} - Cluster:<#{cluster.name}> End Associations")
    $evm.log("info","")

    $evm.log("info","#{@log_prefix} - Cluster:<#{cluster.name}> Begin Virtual Columns")
    cluster.virtual_column_names.sort.each { |vcn| $evm.log("info", "#{@log_prefix} - Cluster:<#{cluster.name}> Virtual Columns - #{vcn}: #{cluster.send(vcn)}")}
    $evm.log("info","#{@log_prefix} - Cluster:<#{cluster.name}> End Virtual Columns")
    $evm.log("info","")
  end
----

include::Management_System_Events_ems_event.adoc[]

include::Management_System_Folders_ems_folder.adoc[]

[[_sect_providers_ext_management_system]]
=== Providers (ext_management_system)

[cols="1,1", frame="all", options="header"]
|====
| 
							
								Method
							
						
| 
							
								Use
							
						

| 
							
								authentication_password_encrypted
							
						
| 
							
								Returns credentials password encrypted
							
						

| 
							
								authentication_password
							
						
| 
							
								Returns credentials password unencrypted
							
						

| 
							
								authentication_userid
							
						
| 
							
								Returns credentials user id
							
						

| 
							
								ems_clusters
							
						
| 
							
								Returns objects clusters
							
						

| 
							
								ems_events
							
						
| 
							
								Returns an array of EmsEvent records associated with the object
							
						

| 
							
								ems_folders
							
						
| 
							
								Returns objects folders
							
						

| 
							
								hosts
							
						
| 
							
								Returns objects hosts
							
						

| 
							
								refresh
							
						
| 
							
								Refreshes relationships and power states for objects related to the object
							
						

| 
							
								resource_pools
							
						
| 
							
								Returns objects resource pools
							
						

| 
							
								storages
							
						
| 
							
								Returns objects storages
							
						

| 
							
								vms
							
						
| 
							
								Returns objects vms
							
						

| 
							
								to_s
							
						
| 
							
								Converts object to string
							
						
|====



[source,ruby]
----


  #########################
  #
  # Method: dumpEMS
  # Inputs: $evm.root['ext_management_system']
  # Description: Dump EMS information
  #
  ##########################
  def dumpEMS(ems)
    $evm.log("info","#{@log_prefix} - EMS:<#{ems.name}> Begin Attributes")
    ems.attributes.sort.each { |k, v| $evm.log("info", "#{@log_prefix} - EMS:<#{ems.name}> Attributes - #{k}: #{v.inspect}")}
    $evm.log("info","#{@log_prefix} - EMS:<#{ems.name}> End Attributes")
    $evm.log("info","")

    $evm.log("info","#{@log_prefix} - EMS:<#{ems.name}> Begin Associations")
    ems.associations.sort.each { |assc| $evm.log("info", "#{@log_prefix} - EMS:<#{ems.name}> Associations - #{assc}")}
    $evm.log("info","#{@log_prefix} - EMS:<#{ems.name}> End Associations")
    $evm.log("info","")

    $evm.log("info","#{@log_prefix} - EMS:<#{ems.name}> Begin EMS Folders")
    ems.ems_folders.each { |ef| ef.attributes.sort.each { |k,v| $evm.log("info", "#{@log_prefix} - EMS:<#{ems.name}> EMS Folder:<#{ef.name}> #{k}: #{v.inspect}")}}
    $evm.log("info","#{@log_prefix} - EMS:<#{ems.name}> End EMS Folders")
    $evm.log("info","")

    $evm.log("info","#{@log_prefix} - EMS:<#{ems.name}> Begin Virtual Columns")
    ems.virtual_column_names.sort.each { |vcn| $evm.log("info", "#{@log_prefix} - EMS:<#{ems.name}> Virtual Columns - #{vcn}: #{ems.send(vcn)}")}
    $evm.log("info","#{@log_prefix} - EMS:<#{ems.name}> End Virtual Columns")
    $evm.log("info","")
  end
----

include::Cloud_Providers_ems_cloud.adoc[]

include::Firewall_Rules_firewall_rule.adoc[]

include::Flavors_flavor.adoc[]

include::Floating_IPs_floating_ip.adoc[]

include::Guest_Applications_guest_application.adoc[]

include::Guest_Device_guest_device.adoc[]

include::Hardware_hardware.adoc[]

[[_sect_hosts_host]]
=== Hosts (host)


[cols="1,1", frame="all", options="header"]
|====
| 
							
								Method
							
						
| 
							
								Use
							
						

| 
							
								authentication_password
							
						
| 
							
								Returns credential password
							
						

| 
							
								authentication_userid
							
						
| 
							
								Returns credential user
							
						

| 
							
								datacenter
							
						
| 
							
								Returns datacenter
							
						

| 
							
								directories
							
						
| 
							
								Returns list of directories for the object
							
						

| 
							
								domain
							
						
| 
							
								Returns the domain portion of the hostname
							
						

| 
							
								ems_cluster
							
						
| 
							
								Returns cluster
							
						

| 
							
								ems_events
							
						
| 
							
								Returns an array of EmsEvent records associated with the object
							
						

| 
							
								ems_folder
							
						
| 
							
								Returns hosts folder on Management System
							
						

| 
							
								event_log_threshold?(options)
							
						
| 
							
								Searches event log records to determine if an event has occurred x number of times within a defined time frame. Returns true if the number of matching records found are greater or equal to the specified freq_threshold, otherwise it returns false
							
							
							
								Options values:
							
							
								:message_filter_type - Must be one of "STARTS WITH", "ENDS WITH", "INCLUDES", "REGULAR EXPRESSION"
							
							
								:message_filter_value - <string value to search for>
							
							
								:time_threshold - Options time interval to search. Example: 2.days (Search the past 2 days of event logs) Default 10.days
							
							
								:freq_threshold - Number of occurrences to check for. Default = 2
							
							
								:source, :event_id, :level, :name - Options filter values
							
						

| 
							
								ext_management_system
							
						
| 
							
								Returns Management System
							
						

| 
							
								files
							
						
| 
							
								Returns list of files for the object
							
						

| 
							
								guest_applications
							
						
| 
							
								Returns Guest Applications
							
						

| 
							
								hardware
							
						
| 
							
								Returns hardware
							
						

| 
							
								lans
							
						
| 
							
								Returns LANs
							
						

| 
							
								operating_system
							
						
| 
							
								Returns Operating System
							
						

| 
							
								storages
							
						
| 
							
								Returns datastores
							
						

| 
							
								switches
							
						
| 
							
								Returns network switches
							
						

| 
							
								vms
							
						
| 
							
								Returns VMs.
							
						

| 
							
								credentials(type = :remote)
							
						
| 
							
								Returns credentials for a Host for the specified type as an array for username/pwd. (Default type is :remote if no type is specified.)
							
							
								Supports 4 different types of credentials:
							
							
								:default = Default
							
							
								:remote = Remote Login (think SSH for ESX)
							
							
								:ws = Web Services
							
							
								:ipmi = IPMI
							
							
							
								Example 1:
							
							
								cred = host.credentials
							
							
								cred => ["user", "pwd"]
							
							
							
								Example 2:
							
							
								user_str, pwd_str = host.credentials(:ipmi)
							
							
								user_str => "user"
							
							
								pwd_str => "pwd"
							
						

| 
							
								ems_custom_keys
							
						
| 
							
								Returns Management Systems custom keys
							
						

| 
							
								ems_custom_get(key)
							
						
| 
							
								Gets Value for specified Management Systems custom key
							
						

| 
							
								ems_custom_set(attribute, value)
							
						
| 
							
								Sets value for specified custom key of the Management System
							
						

| 
							
								custom_keys
							
						
| 
							
								Lists {product-title} Server custom keys
							
						

| 
							
								custom_get(key)
							
						
| 
							
								Gets value for specified {product-title} Server custom key
							
						

| 
							
								custom_set(key, value)
							
						
| 
							
								Sets value for specified {product-title} Server custom key
							
						

| 
							
								ssh_exec(script)
							
						
| 
							
								Runs the specified script on the host
							
						

| 
							
								get_realtime_metric(metric, range, function)
							
						
| 
							
								Returns specified realtime metric
							
						

| 
							
								current_memory_usage
							
						
| 
							
								Returns current memory usage
							
						

| 
							
								current_cpu_usage
							
						
| 
							
								Returns current cpu usage
							
						

| 
							
								current_memory_headroom
							
						
| 
							
								Returns current memory headroom
							
						

| 
							
								to_s
							
						
| 
							
								Converts object to string
							
						

| 
							
								scan
							
						
| 
							
								Performs SmartState Analysis on the object
							
						
|====



The following table lists the metric types available for the `get_realtime_metric(metric, range, function)` method for hosts. 

[cols="1,1", frame="all", options="header"]
|====
| 
							
								Metric
							
						
| 
							
								Description
							
						

| 
							
								v_derived_storage_used
							
						
| 
							
								Capacity - Used space in bytes
							
						

| 
							
								v_pct_cpu_ready_delta_summation
							
						
| 
							
								CPU - Percentage ready
							
						

| 
							
								v_pct_cpu_wait_delta_summation
							
						
| 
							
								CPU - Percentage wait
							
						

| 
							
								v_pct_cpu_used_delta_summation
							
						
| 
							
								CPU - Percentage used
							
						

| 
							
								v_derived_host_count
							
						
| 
							
								State - Number of hosts (Hourly Count / Daily Average)
							
						

| 
							
								v_derived_cpu_reserved_pct
							
						
| 
							
								CPU - Percentage available
							
						

| 
							
								v_derived_memory_reserved_pct
							
						
| 
							
								Memory - Percentage available
							
						
|====

The following Ruby snippet demonstrates using the `get_realtime_metric(metric, range, function)` method using the `v_pct_cpu_ready_delta_summation` metric. 

[source,ruby]
----

host = $evm.root['host']
cpu_rdy = host.get_realtime_metric(:v_pct_cpu_ready_delta_summation, [15.minutes.ago.utc,5.minutes.ago.utc], :avg)
----


[source,ruby]
----


#########################
  #
  # Method: dumpHost
  # Inputs: $evm.root['host']
  # Description: Dump Host information
  #
  ##########################
  def dumpHost(host)
    host = $evm.object['host'] || $evm.root['host']
    $evm.log("info","#{@log_prefix} - Host:<#{host.name}> Begin Attributes")
    host.attributes.sort.each { |k, v| $evm.log("info", "#{@log_prefix} - Host:<#{host.name}> Attributes - #{k}: #{v.inspect}")}
    $evm.log("info","#{@log_prefix} - Host:<#{host.name}> End Attributes")
    $evm.log("info","")

    $evm.log("info","#{@log_prefix} - Host:<#{host.name}> Begin Associations")
    host.associations.sort.each { |assc| $evm.log("info", "#{@log_prefix} - Host:<#{host.name}> Associations - #{assc}")}
    $evm.log("info","#{@log_prefix} - Host:<#{host.name}> End Associations")
    $evm.log("info","")

    $evm.log("info","#{@log_prefix} - Host:<#{host.name}> Begin Hardware")
    host.hardware.attributes.each { |k,v| $evm.log("info", "#{@log_prefix} - Host:<#{host.name}> Hardware - #{k}: #{v.inspect}")}
    $evm.log("info","#{@log_prefix} - Host:<#{host.name}> End Hardware")
    $evm.log("info","")

    $evm.log("info","#{@log_prefix} - Host:<#{host.name}> Begin Lans")
    host.lans.each { |lan| lan.attributes.sort.each { |k,v| $evm.log("info", "#{@log_prefix} - Host:<#{host.name}> Lan:<#{lan.name}> - #{k}: #{v.inspect}")}}
    $evm.log("info","#{@log_prefix} - Host:<#{host.name}> End Lans")
    $evm.log("info","")

    $evm.log("info","#{@log_prefix} - Host:<#{host.name}> Begin Switches")
    host.switches.each { |switch| switch.attributes.sort.each { |k,v| $evm.log("info", "#{@log_prefix} - Host:<#{host.name}> Swtiche:<#{switch.name}> - #{k}: #{v.inspect}")}}
    $evm.log("info","#{@log_prefix} - Host:<#{host.name}> End Switches")
    $evm.log("info","")

    $evm.log("info","#{@log_prefix} - Host:<#{host.name}> Begin Operating System")
    host.operating_system.attributes.sort.each { |k, v| $evm.log("info", "#{@log_prefix} - Host:<#{host.name}> Operating System - #{k}: #{v.inspect}")}
    $evm.log("info","#{@log_prefix} - Host:<#{host.name}> End Operating System")
    $evm.log("info","")

    $evm.log("info","#{@log_prefix} - Host:<#{host.name}> Begin Guest Applications")
    host.guest_applications.each { |guest_app| guest_app.attributes.sort.each { |k, v| $evm.log("info", "#{@log_prefix} - Host:<#{host.name}> Guest Application:<#{guest_app.name}> - #{k}: #{v.inspect}")}}
    $evm.log("info","#{@log_prefix} - Host:<#{host.name}> End Guest Applications")
    $evm.log("info","")

    $evm.log("info","#{@log_prefix} - Host:<#{host.name}> Begin Virtual Columns")
    host.virtual_column_names.sort.each { |vcn| $evm.log("info", "#{@log_prefix} - Host:<#{host.name}> Virtual Columns - #{vcn}: #{host.send(vcn).inspect}")}
    $evm.log("info","#{@log_prefix} - Host:<#{host.name}> End Virtual Columns")
    $evm.log("info", "")
  end
----

include::Hosts_Vmware_ESX_host_vmware_esx.adoc[]

include::LAN_lan.adoc[]

[[_sect_groups_miq_group]]
=== Groups (miq_group)



[cols="1,1", frame="all", options="header"]
|====
| 
							
								Method
							
						
| 
							
								Use
							
						

| 
							
								users
							
						
| 
							
								Returns users in the current miq_group
							
						

| 
							
								vms
							
						
| 
							
								Returns Virtual Machines that this group owns
							
						

| 
							
								custom_keys
							
						
| 
							
								Returns all custom keys for the group
							
						

| 
							
								custom_get(key)
							
						
| 
							
								Returns the value of the specified custom key for the group
							
						

| 
							
								custom_set(key, value)
							
						
| 
							
								Sets the value for the specified key
							
						
|====



[source,ruby]
----


  #########################
  #
  # Method: dumpGroup
  # Inputs: $evm.root['user'].miq_group
  # Description: Dump User's Group information
  #
  ##########################
  def dumpGroup
    user = $evm.root['user']
    unless user.nil?
      miq_group = user.miq_group
      unless miq_group.nil?
        $evm.log("info","#{@method} - Group:<#{miq_group.description}> Begin Attributes [miq_group.attributes]")
        miq_group.attributes.sort.each { |k, v| $evm.log("info", "#{@method} - Group:<#{miq_group.description}> Attributes - #{k}: #{v.inspect}")} unless $evm.root['user'].miq_group.nil?
        $evm.log("info","#{@method} - Group:<#{miq_group.description}> End Attributes [miq_group.attributes]")
        $evm.log("info", "")

        $evm.log("info","#{@method} - Group:<#{miq_group.description}> Begin Associations [miq_group.associations]")
        miq_group.associations.sort.each { |assc| $evm.log("info", "#{@method} - Group:<#{miq_group.description}> Associations - #{assc}")}
        $evm.log("info","#{@method} - Group:<#{miq_group.description}> End Associations [miq_group.associations]")
        $evm.log("info","")

        $evm.log("info","#{@method} - Group:<#{miq_group.description}> Begin Virtual Columns [miq_group.virtual_column_names]")
        miq_group.virtual_column_names.sort.each { |vcn| $evm.log("info", "#{@method} - Group:<#{miq_group.description}> Virtual Columns - #{vcn}: #{miq_group.send(vcn).inspect}")}
        $evm.log("info","#{@method} - Group:<#{miq_group.description}> End Virtual Columns [miq_group.virtual_column_names]")
        $evm.log("info","")
      end
    end
  end
----

[[_sect_request_miq_request]]
=== Request (miq_request)

Request objects are submitted to {product-title} Server for processing.
After the request phase, the request becomes a task object.
The table below shows the relationship between a request object and a task object. 

[cols="1,1", frame="all", options="header"]
|====
| 
							
								Request Object
							
						
| 
							
								Task Object
							
						

| 
							
								automation_request
							
						
| 
							
								automation_task
							
						

| 
							
								miq_host_provision_request
							
						
| 
							
								miq_host_provision
							
						

| 
							
								miq_provision_request
							
						
| 
							
								miq_provision
							
						

| 
							
								vm_reconfigure_request
							
						
| 
							
								vm_reconfigure_task
							
						

| 
							
								service_template_provision_request
							
						
| 
							
								service_template_provision_task
							
						

| 
							
								vm_migrate_request
							
						
| 
							
								vm_migrate_task
							
						
|====

If you set something on the request object, it will be inherited by the task instance that does the work.
This may be useful if you are provisioning multiple virtual machines at a time and need to modify the same setting for all.
Otherwise, the item can be modified on the individual task. 

[cols="1,1", frame="all", options="header"]
|====
| 
							
								Method
							
						
| 
							
								Use
							
						

| 
							
								add_tag(category, tag_name)
							
						
| 
							
								Add a tag to a provision instance by specifying the category and tag name
							
							
								Example: miq_provision.add_tag(:location, "CHI")
							
						

| 
							
								approve(approver,reason for approval)
							
						
| 
							
								Approves the miq_request.
							
							
								Example: $evm.root["miq_request"].approve("admin", "Auto-Approved")
							
						

| 
							
								approvers
							
						
| 
							
								Returns request approvers.
							
						

| 
							
								authorized?
							
						
| 
							
								Returns true if authorized, false if not.
							
						

| 
							
								clear_tag(category=nil, tag_name=nil)
							
						
| 
							
								Without any parameters, the clear_tag method will clear all tags from the provision request. Providing a category will clear all tags selected in that category. Clear a specific category/tag by providing it.
							
							
								Example: miq_provision.clear_tag(:location, "CHI")
							
						

| 
							
								deny
							
						
| 
							
								Denies the miq_request
							
							
								Example:
							
							
								# Deny the request
							
							
								$evm.log('info',"Request denied because of Quota")
							
							
								$evm.root["miq_request"].deny("admin", "Quota Exceeded")
							
						

| 
							
								get_classification(category)
							
						
| 
							
								Works the same as get_tag(category) but the returned data is a hash with :name and :description
							
							
								Example:
							
							
								request.get_classification(:department)
							
							
								Returns: [{:name=>"accounting", :description=>"Accounting"}, {:name=>"engineering", :description=>"Engineering"}]
							
						

| 
							
								get_classifications
							
						
| 
							
								Works the same as get_tag but the returned tag data is a hash with :name and :description
							
							
								Example:
							
							
								request.get_classifications
							
							
								Returns: {:cc=>{:name=>"001", :description=>"Cost Center 001"}, :department=>[{:name=>"accounting", :description=>"Accounting"}, {:name=>"engineering", :description=>"Engineering"}]}
							
						

| 
							
								get_option(key)
							
						
| 
							
								Returns a value from the options hash based on the name of the key name passed in. Internally many of the values are stored as an array of items. (For example, a target host would be stored as the index to the host object in the db and the display name.) Calling this method will return the first item if it is an array. For non-array values the item is returned unmodified.
							
							
								Example: miq_provision_request.get_option(:number_of_cpus)
							
						

| 
							
								get_tag(category)
							
						
| 
							
								Returns the tags selected for the specified tag category.
							
							
								Example: request.get_tag(:department)
							
							
								Returns: ["accounting", "engineering"]
							
						

| 
							
								get_tags
							
						
| 
							
								Get all selected tags stored in a hash by category. If more than one tag is selected in a category, the hash will contain an array of tag names. Otherwise it will contain the tag name as a string.
							
							
								Example: request.get_tags
							
							
								Returns: {:cc=>"001", :department=>["accounting", "engineering"]}
							
						

| 
							
								miq_request
							
						
| 
							
								(Legacy support) Internal Note: The miq_request instance use to be a separate instance from the specific request instance (like miq_provision_request). When the classes were refactored into 1 this method was added to allow existing code and automate methods to continue to run unchanged.)
							
						

| 
							
								miq_request_tasks
							
						
| 
							
								Returns the requests tasks
							
						

| 
							
								options
							
						
| 
							
								Returns a hash containing all the options set for the current provision object
							
						

| 
							
								pending
							
						
| 
							
								Puts the object in a pending state for approval
							
							
								Example:
							
							
								# Raise automation event: request_pending
							
							
								$evm.root["miq_request"].pending
							
						

| 
							
								reason
							
						
| 
							
								Returns reason for approval or denial of request
							
						

| 
							
								requester
							
						
| 
							
								Returns the requester
							
						

| 
							
								resource
							
						
| 
							
								Returns the resource for the request
							
						

| 
							
								set_message(value)
							
						
| 
							
								Sets the message for the request
							
						

| 
							
								set_option(key, value)
							
						
| 
							
								Sets the specified key/value pair for the object
							
						
|====

include::Automation_request.adoc[]

include::Miq_host_provision_request.adoc[]

include::Miq_provision_request.adoc[]

[[_sect_request_task_miq_request_task]]
=== Request Task (miq_request_task)



[cols="1,1", frame="all", options="header"]
|====
| 
							
								Method
							
						
| 
							
								Use
							
						

| 
							
								add_tag(category, tag_name)
							
						
| 
							
								Add a tag to a provision instance by specifying the category and tag name.
							
							
								Example: miq_provision.add_tag(:location, "CHI")
							
						

| 
							
								clear_tag(category=nil, tag_name=nil)
							
						
| 
							
								Without any parameters, the clear_tag method will clear all tags from the provision request. Providing a category will clear all tags selected in that category. Clear a specific category/tag by providing it.
							
							
								Example: miq_provision.clear_tag(:location, "CHI")
							
						

| 
							
								destination
							
						
| 
							
								Returns the destination object. (The resultant object from running the task. In the case of provisioning, this would be the newly created VM.)
							
						

| 
							
								execute
							
						
| 
							
								Executes or processes the request.
							
						

| 
							
								finished(msg)
							
						
| 
							
								Sets the task to finished with the supplied message.
							
						

| 
							
								get_classification(category)
							
						
| 
							
								Works the same as get_tag(category) but the returned data is a hash with :name and :description.
							
							
								Example:
							
							
								request.get_classification(:department)
							
							
								Returns: [{:name=>"accounting", :description=>"Accounting"}, {:name=>"engineering", :description=>"Engineering"}]
							
						

| 
							
								get_classifications
							
						
| 
							
								Works the same as get_tag but the returned tag data is a hash with :name and :description.
							
							
								Example:
							
							
								request.get_classifications
							
							
								Returns: {:cc=>{:name=>"001", :description=>"Cost Center 001"}, :department=>[{:name=>"accounting", :description=>"Accounting"}, {:name=>"engineering", :description=>"Engineering"}]}
							
						

| 
							
								get_option_last(key)
							
						
| 
							
								This method is the same as get_option, except that it returns the last array value.
							
						

| 
							
								get_option(key)
							
						
| 
							
								Returns a value from the options hash based on the name of the key name passed in. Internally many of the values are stored as an array of items. (For example, a target host would be stored as the index to the host object in the db and the display name.) Calling this method will return the first item if it is an array. For non-array values the item is returned unmodified.
							
							
								Example: miq_provision_request.get_option(:number_of_cpus)
							
						

| 
							
								get_tag(category)
							
						
| 
							
								Returns the tags selected for the specified tag category.
							
							
								Example: request.get_tag(:department)
							
							
								Returns: ["accounting", "engineering"]
							
						

| 
							
								get_tags
							
						
| 
							
								Get all selected tags stored in a hash by category. If more than one tag is selected in a category, the hash will contain an array of tag names. Otherwise it will contain the tag name as a string.
							
							
								Example: request.get_tag
							
							
								Returns: {:cc=>"001", :department=>["accounting", "engineering"]}
							
						

| 
							
								message=(msg)
							
						
| 
							
								Sets the message for the request task.
							
						

| 
							
								miq_request
							
						
| 
							
								Returns the miq_request for the task.
							
						

| 
							
								miq_request_task
							
						
| 
							
								Returns the parent miq_request task.
							
						

| 
							
								miq_request.user_message=(msg)
							
						
| 
							
								Allows automate method to override the default request status message.
								As a result, you can set custom messages for the progression of the state machine and its success or failure.
								This message will appear as the last message for the service request.
							
						

| 
							
								miq_request_tasks
							
						
| 
							
								Returns the children miq_request tasks.
							
						

| 
							
								options
							
						
| 
							
								Returns a hash containing all the options set for the current object.
							
						

| 
							
								set_option(key, value)
							
						
| 
							
								Updates a key/value pair in the options hash for the provision object. Often the value is required to be an array.
							
						

| 
							
								source
							
						
| 
							
								Returns the source object. (The source, or input, object that the task runs against. In the case of provisioning, this would be the VM or template selected to be provisioned.)
							
						
|====

include::Automation_task.adoc[]

include::Miq_host_provision.adoc[]

[[_sect_vm_provision_task_miq_provision]]
==== VM Provision Task (miq_provision)

[cols="1,1", frame="all", options="header"]
|====
| 
								
									Method
								
							
| 
								
									Use
								
							

| 
								
									check_quota(quota_type, options={})
								
							
| 
								
									Returns the quota information for the specified type
								
							

| 
								
									eligible_clusters
								
							
| 
								
									Returns an array of available Cluster objects filtered by previously selected resources
								
							

| 
								
									eligible_customization_templates
								
							
| 
								
									Returns an array of available Customization Templates
								
							

| 
								
									eligible_folders
								
							
| 
								
									Returns an array of available Folder objects filtered by previously selected resources
								
							

| 
								
									eligible_hosts
								
							
| 
								
									Returns an array of available Host objects filtered by previously selected resources
								
							

| 
								
									eligible_iso_images
								
							
| 
								
									Returns an array of available ISO Image objects filtered by previously selected resources
								
							

| 
								
									eligible_pxe_images
								
							
| 
								
									Returns an array of available PXE Image objects filtered by previously selected resources
								
							

| 
								
									eligible_pxe_servers
								
							
| 
								
									Returns an array of available PXE Servers filtered by previously selected resources
								
							

| 
								
									eligible_resource_pools
								
							
| 
								
									Returns an array of available Resource Pool objects filtered by previously selected resources
								
							

| 
								
									eligible_resources(rsc_type)
								
							
| 
								
									Returns the eligible resources for the resource type specified
								
							

| 
								
									eligible_storages
								
							
| 
								
									Returns an array of available Storage (Datastore) objects filtered by previously selected resources
								
							

| 
								
									eligible_windows_images
								
							
| 
								
									Returns an array of available Windows Image objects filtered by previously selected resources
								
							

| 
								
									get_domain_details
								
							
| 
								
									Returns domain information
								
							

| 
								
									get_domain_name
								
							
| 
								
									Returns domain name
								
							

| 
								
									get_folder_paths
								
							
| 
								
									Returns a hash where the key is an index and the value is the fully-qualified path name of the folder. (Sample: {7 => Dev/Dept1/QA, 8 => Test/Dept2/QA}) This format is useful when a fully-qualified path is required to match the folder name. For example, if you had multiple QA folders under different departments in the sample above. To find the proper QA folder you need to evaluate the entire folder path.
								
							

| 
								
									get_network_details
								
							
| 
								
									Returns network information
								
							

| 
								
									get_network_scope
								
							
| 
								
									Returns network scope
								
							

| 
								
									miq_provision_request
								
							
| 
								
									Returns the provision request object
								
							

| 
								
									set_cluster(rsc)
								
							
| 
								
									Set the cluster to use based on object returned from eligible_clusters
								
							

| 
								
									set_customization_spec(name=nil, override=false)
								
							
| 
								
									Sets the name of the custom spec to use as defined by its name in Virtual Center (Note: This is not supported when being passed by VMware.)
								
							

| 
								
									set_customization_template(rsc)
								
							
| 
								
									Set the customization_template to use based on object returned from eligible_customization_templates
								
							

| 
								
									set_dvs(portgroup, switch = portgroup)
								
							
| 
								
									Set the name of the Distributed Virtual Switch (portgroup). An options <switch> name can also be passed
								
								
									Example: miq_provision.set_dvs('default')
								
							

| 
								
									set_folder(folder_path)
								
							
| 
								
									Set the folder to use based on object returned from eligible_folders. In addition, set_folder accepts the following folder types:
								
								
									Folder Paths - separated by forward slashes. (Must include Data-center name.) Example: Prod/Discovered virtual machine where Prod is the Data-center name and Discovered virtual machine is the folder name.
								
								
									Object returned from the get_folder_paths method
								
							

| 
								
									set_host(rsc)
								
							
| 
								
									Set the host to use based on object returned from eligible_hosts
								
							

| 
								
									set_network_adapter(idx, nic_hash, value=nil)
								
							
| 
								
									Modifies the network card attached to the VM container
								
								
									Available settings:
								
								
									:is_dvs true / false (Default: false)
								
								
									:network (Network Name)
								
								
									:mac_address
								
								
									:devicetype (Default: VirtualPCNet32) Defined by VMware: http://www.vmware.com/support/developer/vc-sdk/visdk400pubs/ReferenceGuide/vim.vm.device.VirtualEthernetCard.html
								
								
									:connectable => {:allowguestcontrol => true / false} (Default: true)
								
								
									:connectable => {:startconnected => true / false} (Default: true)
								
								
									:connectable => {:connected => true / false} (Default: true)
								
								
								
									Example: prov.set_network_adapter(1, {:network => dvs_net1, :is_dvs => true} )
								
							

| 
								
									set_network_address_mode(mode)
								
							
| 
								
									Available modes are dhcp and static
								
							

| 
								
									set_nic_settings(idx, nic_hash, value=nil)
								
							
| 
								
									Modifies the network interface settings at the operating system level
								
								
									Available settings:
								
								
									:addr_mode "dhcp" / "static" (Default: Statis)
								
								
									:ip_addr
								
								
									:subnet_mask
								
								
									:gateway
								
								
									:dns_domain
								
								
									:dns_servers (Windows Only) Comma separated values
								
								
									:sysprep_netbios_mode (Windows Only) Defined by VMware: http://www.vmware.com/support/developer/vc-sdk/visdk400pubs/ReferenceGuide/vim.vm.customization.IPSettings.NetBIOSMode.html
								
								
									:wins_servers Passed as a string specifying the Primary and Secondary WINS servers separated by a comma. "<PrimaryWINS>, <SecondaryWINS>"
								
								
									Example: prov.set_nic_settings(1, {:ip_addr=>10.226.133.55, :subnet_mask=>'255.255.255.192', :gateway=>'10.226.133.5', :addr_mode=>["static", "Static"] } )
								
							

| 
								
									set_iso_image(rsc)
								
							
| 
								
									Set the iso_image to use based on object returned from eligible_iso_images
								
							

| 
								
									set_pxe_image(rsc)
								
							
| 
								
									Set the pxe_image to use based on object returned from eligible_pxe_images
								
							

| 
								
									set_pxe_server(rsc)
								
							
| 
								
									Set the pxe_server to use based on object returned from eligible_pxe_servers
								
							

| 
								
									set_resource_pool(rsc)
								
							
| 
								
									Set the resource_pool to use based on object returned from eligible_resource_pools
								
							

| 
								
									set_storage(rsc)
								
							
| 
								
									Set the Datastore (storage object) to use based on object returned from eligible_storages
								
							

| 
								
									set_vlan(vlan)
								
							
| 
								
									Sets the name of the VLan to use
								
								
									Example: miq_provision.set_vlan('default')
								
							

| 
								
									set_vm_notes(note)
								
							
| 
								
									Sets text for the VM notes (aka annotation) field
								
							

| 
								
									set_vm_notes(notes)
								
							
| 
								
									Sets text for the VM notes (aka annotation) field
								
							

| 
								
									set_windows_image(rsc)
								
							
| 
								
									Set the windows_image to use based on object returned from eligible_windows_images
								
							

| 
								
									source_type
								
							
| 
								
									Returns the provision source type. (values are 'vm' or 'template')
								
							

| 
								
									status
								
							
| 
								
									Returns provision status
								
							

| 
								
									target_type
								
							
| 
								
									Returns the provision target type. (values are 'vm' or 'template')
								
							

| 
								
									vdi_farm
								
							
| 
								
									Returns VDI Farm information
								
							

| 
								
									vm
								
							
| 
								
									The newly created vm
								
							

| 
								
									vm_template
								
							
| 
								
									Returns the template selected to be provisioned
								
							
|====


[source,ruby]
----


begin
  miq_provision = $evm.root["miq_provision"] || $evm.root['miq_provision']
  prov = $evm.root["miq_provision"]
  user = prov.miq_request.requester
  raise "User not specified" if user.nil?



  ###################################
  # Process Change Request Number and set VM Annotation
  ###################################
  intake = prov.get_option(:vm_description)
  intake = "Change Request#: #{intake}"
  prov.set_option(:vm_description,intake)


  ###################################
  # Set the customization spec based on the environment tag chosen in the dialog
  ###################################
  tags = prov.get_tags
  $evm.log("info","Tags: #{tags.inspect}")
  env = tags[:environment]
  $evm.log("info", "Mapping custom spec based on Category Environment <#{env}> chosen in the dialog")
  if env.eql? "dev"
    customization_spec = "Dev-Specification"
    miq_provision.set_customization_spec(customization_spec)
  end
  if env.eql? "stg"
    customization_spec = "Stg-Specification"
    miq_provision.set_customization_spec(customization_spec)
  end


  ###################################
  # Set the VM Notes as follows:
  ###################################
  vm_notes = "#{intake}"
  vm_notes +=  "\nOwner: #{miq_provision.get_option(:owner_first_name)} #{miq_provision.get_option(:owner_last_name)}"
  vm_notes += "\nEmail: #{miq_provision.get_option(:owner_email)}"
  vm_notes += "\nSource Template: #{miq_provision.vm_template.name}"
  miq_provision.set_vm_notes(vm_notes)


  ###################################
  # Drop the VM in the targeted folder
  # In VC a folder must exist that matches the LDAP Group
  # VM will be placed in the Folder
  ###################################
  if prov.get_option(:placement_folder_name).nil?
    ###################################
    # If you want to use a Default folder, set folder = below to the default
    ###################################
    #    folder = "22F DC/LAB FARM/GSE/Intel/Infrastructure/ManageIQ/SelfServiceVMs"
    folder = "DC1/Infrastructure/ManageIQ/SelfService"
    $evm.log("info", "Placing VM in VC folder: <#{folder}")
    $evm.log("info", "Set_folder called with [#{folder.inspect}]")

    miq_provision.set_folder(folder)
  end


  ####################################################
  # Set the IP Address based on the :mac_address entered in the dialog
  #
  ####################################################
  ipaddr = prov.get_option(:mac_address)

  if ! ipaddr.nil?
    # Set provisioning options to override options
    prov.set_option(:sysprep_spec_override, [true, 1])
    prov.set_option(:addr_mode, ["static", "Static"])
    prov.set_option(:ip_addr, ipaddr)
    # Reset :mac_address to nil
    prov.set_option(:mac_address, nil)
  end

  $evm.log("info", "Provision Options: #{prov.options.inspect}")

  exit MIQ_OK

rescue => err
  $evm.log("info", "Set_folder err [#{err}]\n#{err.backtrace.join("\n")}")
end
----

include::Adding_Disks_to_OpenStack_Instance_Provisioning.adoc[]

include::Booting_OpenStack_Instances_from_Volume.adoc[]

include::VM_Provisioning_for_Clouds_Task_miq_provision_cloud.adoc[]

include::Service_template_provision_task.adoc[]

include::Service_Reconfiguration_Task_service_reconfigure_task.adoc[]

include::Vm_migrate_task.adoc[]

include::Proxies_miq_proxy.adoc[]

[[_sect_servers_miq_server]]
=== Servers (miq_server)



These methods are available to the {product-title} Server. 

[cols="1,1", frame="all", options="header"]
|====
| 
							
								Method
							
						
| 
							
								Use
							
						

| 
							
								zone
							
						
| 
							
								Returns {product-title} Servers Zone
							
						

| 
							
								region_number
							
						
| 
							
								Returns {product-title} Servers Region Number
							
						

| 
							
								region_name
							
						
| 
							
								Returns {product-title} Servers Region Name
							
						
|====



[source,ruby]
----


  #########################
  #
  # Method: dumpServer
  # Inputs: $evm.root['miq_server']
  # Description: Dump MIQ Server information
  #
  ##########################
  def dumpServer
    $evm.log("info","#{@method} - Server:<#{$evm.root['miq_server'].name}> Begin Attributes")
    $evm.root['miq_server'].attributes.sort.each { |k, v| $evm.log("info", "#{@method} - Server:<#{$evm.root['miq_server'].name}> Attributes - #{k}: #{v.inspect}")}
    $evm.log("info","#{@method} - Server:<#{$evm.root['miq_server'].name}> End Attributes")
    $evm.log("info", "")
  end
----

include::Network_network.adoc[]

include::Pxe_image.adoc[]

include::Pxe_server.adoc[]

include::Security_Groups_security_group.adoc[]

include::Service2.adoc[]

include::Service_Resource_service_resource.adoc[]

include::Service_Template.adoc[]

include::Snapshot_snapshot.adoc[]

[[_sect_datastores_storage]]
=== Datastores (storage)


[cols="1,1", frame="all", options="header"]
|====
| 
							
								Method
							
						
| 
							
								Use
							
						

| 
							
								ext_management_systems,
							
						
| 
							
								Returns objects Management System
							
						

| 
							
								hosts
							
						
| 
							
								Returns objects Hosts
							
						

| 
							
								vms
							
						
| 
							
								Returns objects Virtual Machines
							
						

| 
							
								unregistered_vms
							
						
| 
							
								Returns objects unregistered Virtual Machines
							
						

| 
							
								to_s
							
						
| 
							
								Converts object to string
							
						

| 
							
								scan
							
						
| 
							
								Performs SmartState Analysis on the object
							
						
|====



[source,ruby]
----


 #########################
  #
  # Method: dumpStorage
  # Inputs: $evm.root['storage']
  # Description: Dump Storage information
  #
  ##########################
  def dumpStorage(storage)
    $evm.log("info","#{@log_prefix} - Storage:<#{storage.name}> Begin Attributes")
    storage.attributes.sort.each { |k, v| $evm.log("info", "#{@log_prefix} - Storage:<#{storage.name}> Attributes - #{k}: #{v.inspect}")}
    $evm.log("info","#{@log_prefix} - Storage:<#{storage.name}> End Attributes")
    $evm.log("info","")

    $evm.log("info","#{@log_prefix} - Storage:<#{storage.name}> Begin Associations")
    storage.associations.sort.each { |assc| $evm.log("info", "#{@log_prefix} - Storage:<#{storage.name}> Associations - #{assc}")}
    $evm.log("info","#{@log_prefix} - Storage:<#{storage.name}> End Associations")
    $evm.log("info","")

    $evm.log("info","#{@log_prefix} - Storage:<#{storage.name}> Begin Virtual Columns")
    storage.virtual_column_names.sort.each { |vcn| $evm.log("info", "#{@log_prefix} - Storage:<#{storage.name}> Virtual Columns - #{vcn}: #{storage.send(vcn)}")}
    $evm.log("info","#{@log_prefix} - Storage:<#{storage.name}> End Virtual Columns")
    $evm.log("info","")
  end
----

include::Switch_switch.adoc[]

[[_sect_user_user]]
=== User (user)



These methods can be used on the currently logged on user. 

[cols="1,1", frame="all", options="header"]
|====
| 
							
								Method
							
						
| 
							
								Use
							
						

| 
							
								current_group
							
						
| 
							
								Returns user's assigned internal group
							
						

| 
							
								custom_get(key)
							
						
| 
							
								Returns the custom key value specified by "key"
							
						

| 
							
								custom_keys
							
						
| 
							
								Returns an array of custom keys
							
						

| 
							
								custom_set(key,value)
							
						
| 
							
								Sets custom value for "key" to "value"
							
						

| 
							
								email
							
						
| 
							
								Returns user's email address
							
						

| 
							
								get_ladap_attribute(name)
							
						
| 
							
								Returns the value of the specified LDAP attribute
							
						

| 
							
								get_ldap_atttribute_names
							
						
| 
							
								Returns user's LDAP attribute names
							
						

| 
							
								ldap_group
							
						
| 
							
								Returns user's assigned LDAP group
							
						

| 
							
								miq_requests
							
						
| 
							
								Returns user's requests
							
						

| 
							
								name
							
						
| 
							
								Returns user's name
							
						

| 
							
								userid
							
						
| 
							
								Returns user's userid
							
						

| 
							
								vms
							
						
| 
							
								Returns Virtual Machines that this user owns
							
						
|====



[source,ruby]
----


  #########################
  #
  # Method: dumpUser
  # Inputs: $evm.root['user']
  # Description: Dump User information
  #
  ##########################
  def dumpUser
    user = $evm.root['user']
    unless user.nil?
      $evm.log("info","#{@method} - User:<#{user.name}> Begin Attributes [user.attributes]")
      user.attributes.sort.each { |k, v| $evm.log("info", "#{@method} - User:<#{user.name}> Attributes - #{k}: #{v.inspect}")}
      $evm.log("info","#{@method} - User:<#{user.name}> End Attributes [user.attributes]")
      $evm.log("info", "")

      $evm.log("info","#{@method} - User:<#{user.name}> Begin Associations [user.associations]")
      user.associations.sort.each { |assc| $evm.log("info", "#{@method} - User:<#{user.name}> Associations - #{assc}")}
      $evm.log("info","#{@method} - User:<#{user.name}> End Associations [user.associations]")
      $evm.log("info","")

      $evm.log("info","#{@method} - User:<#{user.name}> Begin Virtual Columns [user.virtual_column_names]")
      user.virtual_column_names.sort.each { |vcn| $evm.log("info", "#{@method} - User:<#{user.name}> Virtual Columns - #{vcn}: #{user.send(vcn).inspect}")}
      $evm.log("info","#{@method} - User:<#{user.name}> End Virtual Columns [user.virtual_column_names]")
      $evm.log("info","")
    end
  end
----

[[_sect_virtual_machines_and_templates_vm_or_template]]
=== Virtual Machines and Templates (vm_or_template)

The following methods can be used on a virtual machine or template object. 

[cols="1,1", frame="all", options="header"]
|====
| 
							
								Method
							
						
| 
							
								Use
							
						
|
							add_disk footnote:[Supported for Red Hat Virtualization and VMWare virtual machines]
							
|

							Add storage to an existing VM. 
							
							This method accepts as parameters: disk_name, disk_size_mb, and options to pass values for :thinProvisioned, :dependent, and :persistent. 
							
							Example: `vm.add_disk("[#{vm.storage_name}]", size_in_mb, thin_provisioned: true)`

| 
							
								changed_vm_value?
							
						
| 
							
								Checks the 2 most recent drift state captures , and answers whether the specified value changed between them
							
						

| 
							
								collect_running_processes
							
						
| 
							
								Collects the running processes of the object
							
						

| 
							
								create_snapshot(name, desc = nil)
							
						
| 
							
								Create a snapshot of the object. The *name* parameter is not used for Red Hat Virtualization virtual machines when creating a snapshot. 
							
						

| 
							
								custom_get(key)
							
						
| 
							
								Get the value of specified {product-title} Server key from the object
							
						

| 
							
								custom_keys
							
						
| 
							
								List all {product-title} Server custom keys for the object
							
						

| 
							
								custom_set(key, value)
							
						
| 
							
								Set a custom {product-title} Server key value
							
						

| 
							
								datacenter
							
						
| 
							
								Returns objects Datacenter
							
						

| 
							
								direct_service
							
						
| 
							
								Show the direct service relationship of the virtual machine
							
						

| 
							
								directories
							
						
| 
							
								Returns number of directories on the object
							
						

| 
							
								ems_blue_folder (this will be reworked to be more VMware-specific)
							
						
| 
							
								Returns objects blue folder from VMware. These are the folders showing in VM and Templates view in VMware
							
						

| 
							
								ems_cluster
							
						
| 
							
								Returns objects cluster
							
						

| 
							
								ems_custom_get(key)
							
						
| 
							
								Gets specified key of custom Management System Attribute
							
						

| 
							
								ems_custom_keys
							
						
| 
							
								List the custom keys defined by the Management System for the object
							
						

| 
							
								ems_custom_set(attribute, value)
							
						
| 
							
								Sets specified key and value of custom Management System Attribute
							
						

| 
							
								ems_folder
							
						
| 
							
								Returns objects folder on Management System
							
						

| 
							
								ems_ref_string
							
						
| 
							
								Returns unique identifier the Management System uses to identify this resource. For example, in VMware a VM would return a value like: "vm-26622"
							
						

| 
							
								event_log_threshold? (options)
							
						
| 
							
								Searches event log records to determine if an event has occurred x number of times within a defined time frame. Returns true if the number of matching records found are greater or equal to the specified freq_threshold, otherwise it returns false
							
							
								Options values:
							
							
								:message_filter_type - Must be one of "STARTS WITH", "ENDS WITH", "INCLUDES", "REGULAR EXPRESSION"
							
							
								:message_filter_value - <string value to search for>
							
							
								:time_threshold - Options time interval to search. Example: 2.days (Search the past 2 days of event logs) Default 10.days
							
							
								:freq_threshold - Number of occurrences to check for. Default = 2
							
							
								:source, :event_id, :level, :name - Options filter values
							
						

| 
							
								event_threshold?(options)
							
						
| 
							
								Checks if an event (or multiple events) have occurred X number of times in N seconds. The values below are used if no data is passed
							
							
								event_threshold?(options = {:time_threshold => 30.minutes, :event_types => ["MigrateVM_Task_Complete"], :freq_threshold => 2})
							
						

| 
							
								ext_management_system
							
						
| 
							
								Returns objects Management System
							
						

| 
							
								files
							
						
| 
							
								Returns number of files on the object
							
						

| 
							
								get_realtime_metric(metric, range, function)
							
						
| 
							
								Returns specified realtime metric
							
						

| 
							
								group=(group)
							
						
| 
							
								Sets objects group
							
						

| 
							
								guest_applications
							
						
| 
							
								Returns objects Guest Application list
							
						

| 
							
								hardware
							
						
| 
							
								Returns objects Hardware
							
						

| 
							
								host
							
						
| 
							
								Returns objects Host
							
						

| 
							
								migrate(host, pool = nil, priority = "defaultPriority", state = nil)
							
						
| 
							
								Migrates the object to another host. The only required parameter is host
							
						

| 
							
								miq_provision
							
						
| 
							
								If VM was created using {product-title} Server provisioning, this is the miq_provision task instance that created the VM
							
						

| 
							
								operating_system
							
						
| 
							
								Returns objects Operating System
							
						

| 
							
								owner
							
						
| 
							
								Return objects owner
							
						

| 
							
								owner=(owner)
							
						
| 
							
								Sets objects owner
							
						

| 
							
								performances_maintains_value_for_duration?
							
						
| 
							
								Based on options given, checks to see if a performance threshold is maintained for a time period
							
							
								Example: vm.performances_maintains_value_for_duration?(:column => "cpu_usage_rate_average", :operator => "=", :value => 3.51, :duration => 20.minutes)
							
						

| 
							
								reboot_guest
							
						
| 
							
								Reboots the guest operating system
							
						

| 
							
								reconfigured_hardware_value?
							
						
| 
							
								Checks if hardware value has been reconfigured
							
						

| 
							
								refresh
							
						
| 
							
								Refresh power states and relationships of the object
							
						

| 
							
								registered?
							
						
| 
							
								Is the object registered?
							
						

| 
							
								remove_all_snapshots
							
						
| 
							
								Remove all of the objects snapshots
							
						

| 
							
								remove_from_disk
							
						
| 
							
								Removes the object from disk
							
						

| 
							
								remove_from_vmdb
							
						
| 
							
								Removes the object from the VMDB
							
						

| 
							
								remove_snapshot(snapshot_id)
							
						
| 
							
								Remove a specific snapshot based on the snapshot_id
							
						

| 
							
								resource_pool
							
						
| 
							
								Returns objects Resource Pool
							
						

| 
							
								retire_now
							
						
| 
							
								Retire the object immediately
							
						

| 
							
								retirement_warn=(seconds)
							
						
| 
							
								Send a retirement warning
							
						

| 
							
								retires_on=(date)
							
						
| 
							
								Retire the object on date specified
							
						

| 
							
								revert_to_snapshot(snapshot_id)
							
						
| 
							
								Revert to a snapshot based on the snapshot_id
							
						

| 
							
								scan(scan_categories = nil)
							
						
| 
							
								Perform SmartState Analysis on the object. Scan_categories is optional
							
						

| 
							
								service
							
						
| 
							
								Show the top-level service for a virtual machine in a service hierarchy. For the immediate parent service relationship of a virtual machine, use direct_service
							
						

| 
							
								shutdown_guest
							
						
| 
							
								Shuts down the guest operating system of the object
							
						

| 
							
								snapshots
							
						
| 
							
								Returns list of snapshots for the object
							
						

| 
							
								standby_guest
							
						
| 
							
								Puts the operating system on standby
							
						

| 
							
								start
							
						
| 
							
								Starts the object
							
							
								See Samples/PowerOn_DHOB
							
						

| 
							
								stop
							
						
| 
							
								Stops the object
							
						

| 
							
								storage
							
						
| 
							
								Returns objects Datastore
							
						

| 
							
								suspend
							
						
| 
							
								Suspends the object
							
						

| 
							
								to_s
							
						
| 
							
								Converts object to string
							
						

| 
							
								unlink_storage
							
						
| 
							
								Removes the reference to the VM's Datastore
							
						

| 
							
								unregister
							
						
| 
							
								Unregisters the object from the Management System
							
						
|====



[source,ruby]
----


  #########################
  #
  # Method: dumpVM
  # Inputs: $evm.root['vm']
  # Description: Dump VM information
  #
  ##########################
  def dumpVM(vm)
    $evm.log("info","#{@log_prefix} - VM:<#{vm.name}> Begin Attributes [vm.attributes]")
    vm.attributes.sort.each { |k, v| $evm.log("info", "#{@log_prefix} - VM:<#{vm.name}> Attributes - #{k}: #{v.inspect}")}
    $evm.log("info","#{@log_prefix} - VM:<#{vm.name}> End Attributes [vm.attributes]")
    $evm.log("info","")

    $evm.log("info","#{@log_prefix} - VM:<#{vm.name}> Begin Associations [vm.associations]")
    vm.associations.sort.each { |assc| $evm.log("info", "#{@log_prefix} - VM:<#{vm.name}> Associations - #{assc}")}
    $evm.log("info","#{@log_prefix} - VM:<#{vm.name}> End Associations [vm.associations]")
    $evm.log("info","")

    $evm.log("info","#{@log_prefix} - VM:<#{vm.name}> Begin Hardware Attributes [vm.hardware]")
    vm.hardware.attributes.each { |k,v| $evm.log("info", "#{@log_prefix} - VM:<#{vm.name}> Hardware - #{k}: #{v.inspect}")}
    $evm.log("info","#{@log_prefix} - VM:<#{vm.name}> End Hardware Attributes [vm.hardware]")
    $evm.log("info","")

    $evm.log("info","#{@log_prefix} - VM:<#{vm.name}> Begin Hardware Associations [vm.hardware.associations]")
    vm.hardware.associations.sort.each { |assc| $evm.log("info", "#{@log_prefix} - VM:<#{vm.name}> hardware Associations - #{assc}")}
    $evm.log("info","#{@log_prefix} - VM:<#{vm.name}> End hardware Associations [vm.hardware.associations]")
    $evm.log("info","")

    $evm.log("info","#{@log_prefix} - VM:<#{vm.name}> Begin Neworks [vm.hardware.nics]")
    vm.hardware.nics.each { |nic| nic.attributes.sort.each { |k,v| $evm.log("info", "#{@log_prefix} - VM:<#{vm.name}> VLAN:<#{nic.device_name}> - #{k}: #{v.inspect}")}}
    $evm.log("info","#{@log_prefix} - VM:<#{vm.name}> End Networks [vm.hardware.nics]")
    $evm.log("info","")

    unless vm.ext_management_system.nil?
      $evm.log("info","#{@log_prefix} - VM:<#{vm.name}> Begin EMS [vm.ext_management_system]")
      vm.ext_management_system.attributes.sort.each { |ems_k, ems_v| $evm.log("info", "#{@log_prefix} - VM:<#{vm.name}> EMS:<#{vm.ext_management_system.name}> #{ems_k} - #{ems_v.inspect}")}
      $evm.log("info","#{@log_prefix} - VM:<#{vm.name}> End EMS [vm.ext_management_system]")
      $evm.log("info","")
    end

    unless vm.owner.nil?
      $evm.log("info","#{@log_prefix} - VM:<#{vm.name}> Begin Owner [vm.owner]")
      vm.owner.attributes.each { |k,v| $evm.log("info", "#{@log_prefix} - VM:<#{vm.name}> Owner - #{k}: #{v.inspect}")}
      $evm.log("info","#{@log_prefix} - VM:<#{vm.name}> End Owner [vm.owner]")
      $evm.log("info","")
    end

    unless vm.operating_system.nil?
      $evm.log("info","#{@log_prefix} - VM:<#{vm.name}> Begin Operating System [vm.operating_system]")
      vm.operating_system.attributes.sort.each { |k, v| $evm.log("info", "#{@log_prefix} - VM:<#{vm.name}> Operating System - #{k}: #{v.inspect}")}
      $evm.log("info","#{@log_prefix} - VM:<#{vm.name}> End Operating System [vm.operating_system]")
      $evm.log("info","")
    end

    unless vm.guest_applications.nil?
      $evm.log("info","#{@log_prefix} - VM:<#{vm.name}> Begin Guest Applications")
      vm.guest_applications.each { |guest_app| guest_app.attributes.sort.each { |k, v| $evm.log("info", "#{@log_prefix} - VM:<#{vm.name}> Guest Application:<#{guest_app.name}> - #{k}: #{v.inspect}")}} unless vm.guest_applications.nil?
      $evm.log("info","#{@log_prefix} - VM:<#{vm.name}> End Guest Applications")
      $evm.log("info","")
    end

    unless vm.snapshots.nil?
      $evm.log("info","#{@log_prefix} - VM:<#{vm.name}> Begin Snapshots")
      vm.snapshots.each { |ss| ss.attributes.sort.each { |k, v| $evm.log("info", "#{@log_prefix} - VM:<#{vm.name}> Snapshot:<#{ss.name}> - #{k}: #{v.inspect}")}} unless vm.snapshots.nil?
      $evm.log("info","#{@log_prefix} - VM:<#{vm.name}> End Snapshots")
      $evm.log("info","")
    end

    unless vm.storage.nil?
      $evm.log("info","#{@log_prefix} - VM:<#{vm.name}> Begin VM Storage [vm.storage]")
      vm.storage.attributes.sort.each { |stor_k, stor_v| $evm.log("info", "#{@log_prefix} - VM:<#{vm.name}> Storage:<#{vm.storage.name}> #{stor_k} - #{stor_v.inspect}")}
      $evm.log("info","#{@log_prefix} - VM:<#{vm.name}> End VM Storage [vm.storage]")
      $evm.log("info","")
    end

    $evm.log("info","#{@log_prefix} - VM:<#{vm.name}> Begin Virtual Columns -----")
    vm.virtual_column_names.sort.each { |vcn| $evm.log("info", "#{@log_prefix} - VM:<#{vm.name}> Virtual Columns - #{vcn}: #{vm.send(vcn).inspect}")}
    $evm.log("info","#{@log_prefix} - VM:<#{vm.name}> End Virtual Columns -----")
    $evm.log("info","")
  end
----

[source,ruby]
----


  ####################
  #
  # Method: createSnapshot
  #
  ####################

  def createSnapshot(vm, snap_name, snap_desc=snap_name)
    $evm.log("info","#{@method} - VM:<#{vm.name}> Creating Snapshot:<#{snap_name}> Description:<#{snap_desc}>")
    vm.create_snapshot(snap_name, snap_desc)
  end
----

[source,ruby]
----

  ####################
  # Red Hat Virtualization Virtual Machines
  # Method: createSnapshot
  #
  ####################

	def createSnapshot(vm, snap_desc=snap_name)
		$evm.log("info","#{@method} - VM:<#{vm.name}> Creating Snapshot:<#{snap_name}> Description:<#{snap_desc}>")
		vm.create_snapshot(snap_desc)
	end
----

[[_sect_vms_vm]]
==== VMs (vm)

[cols="1,1", frame="all", options="header"]
|====
| 
								
									Method
								
							
| 
								
									Use
								
							

| 
								
									add_to_service(service)
								
							
| 
								
									Adds the VM to a service object
								
							

| 
								
									remove_from_service
								
							
| 
								
									Removes the VM from its parent service
								
							
|====

The following table lists the metric types available for the `get_realtime_metric(metric, range, function)` method for virtual machines. 

[cols="1,1", frame="all", options="header"]
|====
| 
								
									Metric
								
							
| 
								
									Description
								
							

| 
								
									v_derived_storage_used
								
							
| 
								
									Capacity - Used space in bytes
								
							

| 
								
									v_pct_cpu_ready_delta_summation
								
							
| 
								
									CPU - Percentage ready
								
							

| 
								
									v_pct_cpu_wait_delta_summation
								
							
| 
								
									CPU - Percentage wait
								
							

| 
								
									v_pct_cpu_used_delta_summation
								
							
| 
								
									CPU - Percentage used
								
							

| 
								
									v_derived_vm_count
								
							
| 
								
									State - Peak average virtual machines (Hourly Count / Daily Average)
								
							

| 
								
									v_derived_cpu_reserved_pct
								
							
| 
								
									CPU - Percentage available
								
							

| 
								
									v_derived_memory_reserved_pct
								
							
| 
								
									Memory - Percentage available
								
							
|====

The following Ruby snippet demonstrates using the `get_realtime_metric(metric, range, function)` method using the `v_pct_cpu_ready_delta_summation` metric. 

[source,ruby]
----

host = $evm.root['vm']
cpu_rdy = vm.get_realtime_metric(:v_pct_cpu_ready_delta_summation, [15.minutes.ago.utc,5.minutes.ago.utc], :avg)
----

include::VMs_for_Clouds_vm_cloud.adoc[]

include::Windows_image.adoc[]

[[_sect_creating_categories_and_tags]]
=== Creating Categories and Tags

These methods are invoked using $evm.execute.
See after the table for usage examples. 

[cols="1,1", frame="all", options="header"]
|====
| 
							
								Method(parameter)
							
						
| 
							
								Use
							
						

| 
							
								category_exists?
							
						
| 
							
								Checks to see if a tag category exists. Usually used with unless or if to then create a category that does not exist.
							
							
								Example: $evm.execute('category_exists?', "department")
							
						

| 
							
								category_create
							
						
| 
							Creates a new category, and if only one tag value from this category can be assigned to a configuration item, sets that tag value using the `single_value` option.
							    
								Example: $evm.execute('category_create', :name => "department", :single_value => false, :description => "Department")
							    
							    *NOTE:* 
							    
							    The `category_create` method currently does not work as expected. The user interface shows the value provided for `:description` in the *Display Name* field and the value provided for `:example_text` is displayed in the *Description* field.
                                
|
								tag_exists?
							
						
| 
							
								Checks to see if a tag exists in a category.
							
							
								Example: $evm.execute('tag_exists?', "department", "finance")
							
						

| 
							
								tag_create
							
						
| 
							
								Creates a new tag in the specified category.
							
							
								Example: $evm.execute('tag_create', "department", :name => "finance", :description => "Finance")
							
						
|====



include::Category_and_Tags_Methods_Example1.adoc[]

include::Quota2.adoc[]












