[[_miq_provision_request]]
==== VM Provision Request (miq_provision_request)

[cols="1,1", frame="all", options="header"]
|===
| 
						
							Method
						
					
| 
						
							Use
						
					

| 
						
							check_quota(quota_type, options={})
						
					
| 
						
							Returns the quota information for the specified type
						
					

| 
						
							ci_type
						
					
| 
						
							Returns the cloud infrastructure type: vm
						
					

| 
						
							eligible_clusters
						
					
| 
						
							Returns an array of available Cluster objects filtered by previously selected resources
						
					

| 
						
							eligible_customization_templates
						
					
| 
						
							Returns an array of available Customization Templates filtered by previously selected resources
						
					

| 
						
							eligible_folders
						
					
| 
						
							Returns an array of available Folder objects filtered by previously selected resources
						
					

| 
						
							eligible_hosts
						
					
| 
						
							Returns an array of available Host objects filtered by previously selected resources
						
					

| 
						
							eligible_iso_images
						
					
| 
						
							Returns an array of available ISO image objects filtered by previously selected resources
						
					

| 
						
							eligible_pxe_images
						
					
| 
						
							Returns an array of available PXE Image objects filtered by previously selected resources
						
					

| 
						
							eligible_pxe_servers
						
					
| 
						
							Returns an array of available PXE Server objects filtered by previously selected resources
						
					

| 
						
							eligible_resource_pools
						
					
| 
						
							Returns an array of available Resource Pool objects filtered by previously selected resources
						
					

| 
						
							eligible_resources(rsc_type)
						
					
| 
						
							Returns eligible resources given the type specified
						
					

| 
						
							eligible_storages
						
					
| 
						
							Returns an array of available Storage (Datastore) objects filtered by previously selected resources
						
					

| 
						
							eligible_windows_images
						
					
| 
						
							Returns an array of available Windows Image objects filtered by previously selected resources
						
					

| 
						
							get_folder_paths
						
					
| 
						
							Returns a hash where the key is an index and the value is the fully-qualified path name of the folder. (Sample: {7 => Dev/Dept1/QA, 8 => Test/Dept2/QA}) This format is useful when a fully-qualified path is required to match the folder name. For example, if you had multiple QA folders under different departments in the sample above. To find the proper QA folder you need to evaluate the entire folder path.
						
					

| 
						
							get_retirement_days
						
					
| 
						
							Returns the number of dates until retirement
						
					

| 
						
							miq_provision
						
					
| 
						
							Returns the task.
						
					

| 
						
							miq_request
						
					
| 
						
							Returns the miq_provision_requests miq_request object
						
					

| 
						
							set_cluster(rsc)
						
					
| 
						
							Set the cluster to use based on object returned from eligible_clusters
						
					

| 
						
							set_customization_template(rsc)
						
					
| 
						
							Set the customization_template to use based on object returned from eligible_customization_templates
						
					

| 
						
							set_folder(folder_path)
						
					
| 
						
							Set the folder to use based on object returned from eligible_folders. In addition, set_folder accepts the following folder types:
						
						
							Folder Paths - separated by forward slashes. (Must include Data-center name.) Example: Prod/Discovered virtual machine where Prod is the Data-center name and Discovered virtual machine is the folder name.
						
						
							Object returned from the get_folder_paths method
						
					

| 
						
							set_host(rsc)
						
					
| 
						
							Set the host to use based on object returned from eligible_hosts
						
					

| 
						
							set_network_adapter(idx, nic_hash, value=nil)
						
					
| 
						
							Modifies the network card attached to the VM container
						
						
							Available settings:
						
						
							:is_dvs true / false (Default: false)
						
						
							:network (Network Name)
						
						
							:mac_address
						
						
							:devicetype (Default: VirtualPCNet32) Defined by VMware: http://www.vmware.com/support/developer/vc-sdk/visdk400pubs/ReferenceGuide/vim.vm.device.VirtualEthernetCard.html
						
						
							:connectable => {:allowguestcontrol => true / false} (Default: true)
						
						
							:connectable => {:startconnected => true / false} (Default: true)
						
						
							:connectable => {:connected => true / false} (Default: true)
						
						
						
							Example: prov.set_network_adapter(1, {:network => dvs_net1, :is_dvs => true} )
						
					

| 
						
							set_network_address_mode(mode)
						
					
| 
						
							Sets IP address type. Available modes are dhcp and static
						
					

| 
						
							set_nic_settings(idx, nic_hash, value=nil)
						
					
| 
						
							Modifies the network interface settings at the operating system level
						
						
							Available settings:
						
						
							:addr_mode "dhcp" / "static" (Default: static)
						
						
							:ip_addr
						
						
							:subnet_mask
						
						
							:gateway
						
						
							:dns_domain
						
						
							:dns_servers (Windows Only) Comma separated values
						
						
							:sysprep_netbios_mode (Windows Only) Defined by VMware: http://www.vmware.com/support/developer/vc-sdk/visdk400pubs/ReferenceGuide/vim.vm.customization.IPSettings.NetBIOSMode.html
						
						
							:wins_servers Passed as a string specifying the Primary and Secondary WINS servers separated by a comma. "<PrimaryWINS>, <SecondaryWINS>"
						
						
							Example: prov.set_nic_settings(1, {:ip_addr=>10.226.133.55, :subnet_mask=>'255.255.255.192', :gateway=>'10.226.133.5', :addr_mode=>["static", "Static"] } )
						
					

| 
						
							set_iso_image(rsc)
						
					
| 
						
							Set the iso_image to use based on object returned from eligible_iso_images
						
					

| 
						
							set_pxe_image(rsc)
						
					
| 
						
							Set the pxe_image to use based on object returned from eligible_pxe_images
						
					

| 
						
							set_pxe_server(rsc)
						
					
| 
						
							Set the pxe_server to use based on object returned from eligible_pxe_servers
						
					

| 
						
							set_resource_pool(rsc)
						
					
| 
						
							Set the resource_pool to use based on object returned from eligible_resource_pools
						
					

| 
						
							set_resource(rsc)
						
					
| 
						
							Sets the resource for the request. (Helper method, should not be called directly)
						
					

| 
						
							set_retirement_days
						
					
| 
						
							Set the number of days until retirement.
						
					

| 
						
							set_storage(rsc)
						
					
| 
						
							Set the Datastore (storage object) to use based on object returned from eligible_storages
						
					

| 
						
							set_vm_notes(note)
						
					
| 
						
							Sets text for the VM notes (aka annotation) field
						
					

| 
						
							set_windows_image(rsc)
						
					
| 
						
							Set the windows_image to use based on object returned from eligible_windows_images
						
					

| 
						
							source_type
						
					
| 
						
							Returns the provision source type. (values are 'vm' or 'template')
						
					

| 
						
							src_vm_id
						
					
| 
						
							Returns ID of the template being cloned
						
					

| 
						
							target_type
						
					
| 
						
							Returns the provision target type. (values are 'vm' or 'template')
						
					

| 
						
							vm_template
						
					
| 
						
							Returns the requests template
						
					
|===
