[[_quota2]]
=== Quota



[cols="1,1", frame="all", options="header"]
|===
| 
						
							Method(parameter)
						
					
| 
						
							Use
						
					

| 
						
							vms_by_owner, vms_by_group, vms_by_owner_and_group
						
						
					
| 
						
							Collect stats about existing VMs by owner or in the same LDAP group as the owner in the current request.
						
						
							Sample return object:
						
						
							{:class_name=>"Vm", :count=>5, :ids=>[22, 120, 121, 122, 117], :cpu=>6, :memory=>5120, :allocated_storage=>29032972288, :used_storage=>29032972288}
						
					

| 
						
							retired_vms_by_owner, retired_vms_by_group, retired_vms_by_owner_and_group
						
						
					
| 
						
							Collect stats about retired VMs, that have not been deleted from the host, by owner or in the same LDAP group as the owner in the current request.
						
						
							Sample return object:
						
						
							{:class_name=>"Vm", :count=>5, :ids=>[22, 120, 121, 122, 117], :cpu=>6, :memory=>5120, :allocated_storage=>29032972288, :used_storage=>29032972288}
						
					

| 
						
							provisions_by_owner, provisions_by_group
						
						
					
| 
						
							Collect stats based on provisions running on the same day as the current request (based on scheduled date or immediate) by owner or in the same LDAP group as the owner. (Results do not include Provision Requests that have not been approved.)
						
						
							Sample return object:
						
						
							{:class_name=>"MiqProvisionRequest", :count=>6, :ids=>[115, 116, 104, 102, 105, 112], :cpu=>6, :memory=>1536, , :storage=>62914560}
						
					

| 
						
							requests_by_owner, requests_by_group
						
						
					
| 
						
							Collect stats based on provision requests made the same day as the request by the same owner or LDAP group as the owner in the current request, regardless of when the provision request is scheduled to run. (Results do not include Provision Requests that have been denied.)
						
						
							Sample return object:
						
						
							{:class_name=>"MiqProvisionRequest", :count=>6, :ids=>[115, 116, 104, 102, 105, 112], :cpu=>6, :memory=>1536, , :storage=>62914560}
						
					

| 
						
							active_provisions_by_owner, active_provisions_by_group, active_provisions
						
					
| 
						
							Collect stats based on currently active provision requests by the same owner or LDAP group as the owner in the current request.
						
						
						
							Sample return object:
						
						
							{:class_name=>"MiqProvisionRequest", :count=>6, :ids=>[115, 116, 104, 102, 105, 112], :cpu=>6, :memory=>1536, , :storage=>62914560}
						
					
|===

