[[_service2]]
=== Service (service)

[cols="1,1", frame="all", options="header"]
|===
| 
						
							Method
						
					
| 
						
							Use
						
					

| 
						
							custom_keys
						
					
| 
						
							Returns custom keys
						
					

| 
						
							custom_get(key)
						
					
| 
						
							Gets value for specified custom key
						
					

| 
						
							custom_set(attribute, value)
						
					
| 
						
							Sets value for specified custom key
						
					

| 
						
							display=(display)
						
					
| 
						
							Set display option
						
					

| 
						
							group=(group)
						
					
| 
						
							Sets group that owns the service
						
					

| 
						
							name=(new_name)
						
					
| 
						
							Sets name of service
						
					

| 
						
							owner=(owner)
						
					
| 
						
							Sets owner of the service
						
					

| 
						
							request_retire
						
					
| 
						
							Retire Service immediately
						
					

| 
						
							retirement_warn=(seconds)
						
					
| 
						
							Sets when to send retirement warning
						
					

| 
						
							retires_on=(date)
						
					
| 
						
							Sets retirement date
						
					

| 
						
							shutdown_guest
						
					
| 
						
							Shuts downs guest operating system of the Service
						
					

| 
						
							start
						
					
| 
						
							Start the Service
						
					

| 
						
							stop
						
					
| 
						
							Stop the Service
						
					

| 
						
							suspend
						
					
| 
						
							Suspend the Service
						
					

| 
						
							vms
						
					
| 
						
							Show all virtual machines associated with this service
						
					

| 
						
							direct_vms
						
					
| 
						
							Show virtual machines directly associated with this service
						
					

| 
						
							indirect_vms
						
					
| 
						
							Show virtual machines associated with lower level services in the hierarchy
						
					

| 
						
							root_service
						
					
| 
						
							Show the top level service in the hierarchy for the target service
						
					

| 
						
							all_service_children
						
					
| 
						
							Show all lower level services to the target service in the hierarchy
						
					

| 
						
							direct_service_children
						
					
| 
						
							Show direct services associated with the target service
						
					

| 
						
							indirect_service_children
						
					
| 
						
							Show services associated with lower level services of the target service
						
					

| 
						
							parent_service
						
					
| 
						
							Show the parent service for the target service
						
					

| 
						
							description=(new_description)
						
					
| 
						
							Sets the service description
						
					

| 
						
							remove_from_vmdb
						
					
| 
						
							Delete the service from the database
						
					

| 
						
							dialog_options
						
					
| 
						
							Returns all dialog options
						
					

| 
						
							get_dialog_option(key)
						
					
| 
						
							Returns a specific dialog option specified by key
						
					

| 
						
							set_dialog_option(key, value)
						
					
| 
						
							Sets value of a dialog option specified by key
						
					
|===
