[[configuring-authentication]]
== Configuring External Authentication to {product-title_short}

After installing {product-title_short}, you can configure external authentication using the `httpd` pod.

Configuring the `httpd` pod for external authentication is done by updating the `httpd-auth-configs` configuration map to include all necessary configuration files and certificates. 

Upon startup, the `httpd` pod overlays its files with the ones specified in the `auth-configuration.conf` file in the configuration map. This is done by the `initialize-httpd-auth` service that runs before `httpd`.

You can configure this manually using the steps in xref:defining-configmap[], or automatically using the steps in xref:automatic-defining-configmap[].

[[configmap-settings]]
=== Configuration Map Settings

The configuration map includes the following:

* `auth-type` - The authentication type.
+
This parameter drives which configuration files `httpd` will load upon start-up. Supported values are:
+
.`auth-type` values
[width="100%",cols="30%,70%",options="header",]
|====
| Value    | External-Authentication Configuration 
| `internal` | Application Based Authentication (_default_) - Database, LDAP/LDAPS, Amazon. This is the default.
| `external` | IPA, IPA 2-factor authentication, IPA/AD Trust, LDAP (OpenLDAP, RHDS, Active Directory, etc.)
| `active-directory` | Active Directory domain realm join
| `saml` | SAML based authentication (Keycloak, ADFS, etc.)
|====
+
* `auth-kerberos-realms` - The Kerberos realms to join.
+
When configuring external authentication against IPA, Active Directory or LDAP, this parameter defines the kerberos realm `httpd`  is configured against, i.e. `example.com`. When specifying multiple Kerberos realms, they must be separated by spaces. The default is `undefined`.
+
* `auth-configuration.conf` - The external authentication configuration file  which declares the list of files to overlay upon start-up if `auth-type` is other than `internal`.
+
Syntax for the file is as follows:
+
----
# for comments
file = basename1 target_path1 permission1
file = basename2 target_path2 permission2
----
+
For the files to overlay on the `httpd` pod, one `file` directive is needed per file.
+
* `basename` - The name of the source file in the configuration map.
* `target_path` - The path of the file on the pod to overwrite, i.e. `/etc/sssd/sssd.conf`
* `permission` (optional) - By default, files are copied using the pod's default umask, owner and group, so files are created as mode 644 owner root, group root.
+
`permission` can be specified as follows, reflecting the mode and ownership to set the copied files to:
+
** mode
** mode:owner
** mode:owner:group
+
For example:
** 755
** 640:root
** 644:root:apache

Binary files can be specified in the configuration map in their base64 encoded format with a basename having a `.base64` extension. Such files are then converted back to binary as they are copied to their target path.

When an /etc/sssd/sssd.conf file is included in the configuration map, the `httpd`  pod automatically enables the sssd service upon startup.

[NOTE]
====
See xref:appe-saml-authentication-example[] for an example SAML configuration file.
====

[[defining-configmap]]
=== Defining the Configuration Map Manually

The authentication configuration map can be defined and customized in the `httpd` pod as follows:

----
$ oc edit configmaps httpd-auth-configs
----
Or simply replaced if generated and edited externally as follows:

----
$ oc replace configmaps httpd-auth-configs --filename external-auth-configmap.yaml
----

Then redeploy the `httpd` pod for the new authentication configuration to take effect.


[[automatic-defining-configmap]]
=== Configuring External Authentication Automatically with httpd_configmap_generator

You can automatically generate authentication configuration maps for the `httpd` pod with the `httpd_configmap_generator` pod, available as a Ruby gem.

This gem provides a command-line interface to automate the generation of `auth-config` maps, which can be used with the `httpd auth` pod for enabling external authentication.

To automatically generate and `auth-config` map:

. Install the `httpd_configmap_generator` tool:
+
----
# gem install httpd_configmap_generator
----
+
. Run the `httpd_configmap_generator` tool:
+
----
$ httpd_configmap_generator --help
httpd_configmap_generator 0.1.1 - External Authentication Configuration script

Usage: httpd_configmap_generator auth_type | update | export [--help | options]

supported auth_type: active-directory, ipa, ldap, saml

httpd_configmap_generator options are:
-V, --version    Version of the httpd_configmap_generator command
-h, --help       Show this message
----

[NOTE]
====
To show the usage for each authentication type or sub-command, run:
----
$ httpd_configmap_generator <command_or_authentication_type> --help
----
====


==== Supported Authentication Types

.Supported Authentication Types
[width="100%",cols="20%,40%,40%",options="header",]
|====
|auth-type|Identity Provider/Environment|for usage
| active-directory | Active Directory domain realm join               | [README-active-directory](README-active-directory.md) 
| ipa              | IPA, IPA 2-factor authentication, IPA/AD Trust   | [README-ipa](README-ipa.md)                           
| ldap             | LDAP directories                                 | [README-ldap](README-ldap.md)                         
| saml             | Keycloak, etc.                                   | [README-saml](README-saml.md)  
|====

==== Updating an auth configuration map

With the `update` subcommand, you can add file(s) to the configuration
map. The `--add-file` option can be specified multiple times, one per file to add
to a configuration map.

Supported file specification for the `--add-file` option are:

----
--add-file=file-path
--add-file=source-file-path,target-file-path
--add-file=source-file-path,target-file-path,file-permission
--add-file=file-url,target-file-path,file-permission
----

When entering file specifications, `file-url` is an HTTP URL and `file-permission` can be specified as: `mode:owner:group`.


Examples:

.Adding files by specifying paths:

The file ownership and permissions will be based on the files specified.

----
$ httpd_configmap_generator update \
--input=/tmp/original-auth-configmap.yaml                    \
--add-file=/etc/openldap/cacerts/primary-directory-cert.pem  \
--add-file=/etc/openldap/cacerts/seconday-directory-cert.pem \
--output=/tmp/updated-auth-configmap.yaml
----

.Adding target files from different source directories:

----
$ httpd_configmap_generator update \
--input=/tmp/original-auth-configmap.yaml                                        \
--add-file=/tmp/uploaded-cert1,/etc/openldap/cacerts/primary-directory-cert.pem  \
--add-file=/tmp/uploaded-cert2,/etc/openldap/cacerts/seconday-directory-cert.pem \
--output=/tmp/updated-auth-configmap.yaml
----

The file ownership and permissions will be based on the source files specified,
in this case the ownership and permissions of the `/tmp/uploaded-cert1`
and `/tmp/uploaded-cert2` files will be used.

.Adding a target file with user-specified ownership and mode:

----
$ httpd_configmap_generator update \
--input=/tmp/original-auth-configmap.yaml                          \
--add-file=/tmp/secondary-keytab,/etc/http2.keytab,600:apache:root \
--output=/tmp/updated-auth-configmap.yaml
----

.Adding files by URL:

----
$ httpd_configmap_generator update \
--input=/tmp/original-auth-configmap.yaml \
--add-file=http://aab-keycloak:8080/auth/realms/testrealm/protocol/saml/description,/etc/httpd/saml2/idp-metadata.xml,644:root:root \
--output=/tmp/updated-auth-configmap.yaml
----

When downloading a file by URL, a target file path and file ownership/mode must be specified.


==== Exporting a file from an auth configuration map

With the `export` subcommand, you can export a file from the configuration
map. For example, to extract the sssd.conf file out of the auth configuration map:

----
$ httpd_configmap_generator export \
--input=/tmp/external-ipa.yaml \
--file=/etc/sssd/sssd.conf     \
--output=/tmp/sssd.conf
----

==== Building the Httpd Configmap Generator in a Container

Container for configuring external authentication for the `httpd` auth pod.
It is based on the auth `httpd` container and generates the `httpd` auth-config map
needed to enable external authentication.

To install, run:

----
$ git clone https://github.com/ManageIQ/httpd_configmap_generator.git
----

___

===== Running with Docker

. Build the container image:
+
----
$ cd httpd_configmap_generator
$ docker build . -t manageiq/httpd_configmap_generator:latest
----
+
. Run the `httpd_configmap_generator` container:
+
----
$ docker run --privileged manageiq/httpd_configmap_generator:latest &
----
+
. Get the httpd_configmap_generator container id:
+
----
$ CONFIGMAP_GENERATOR_ID="`docker ps -l -q`"
----
+
. Generate a configmap for external authentication against IPA:
+
While the httpd_configmap_generator tool can be run in the container by first getting into a bash shell:
+
----
$ docker exec -it $CONFIGMAP_GENERATOR_ID /bin/bash -i
----
+
The tool can also be executed directly as follows:
+
For example, to generate a configuration map for IPA:
+
----
$ docker exec $CONFIGMAP_GENERATOR_ID httpd_configmap_generator ipa \
--host=appliance.example.com        \
--ipa-server=ipaserver.example.com  \
--ipa-domain=example.com            \
--ipa-realm=EXAMPLE.COM             \
--ipa-principal=admin               \
--ipa-password=smartvm1             \
-o /tmp/external-ipa.yaml
----
+
`--host` above must be the DNS of the application exposing the httpd auth pod, i.e. ${APPLICATION_DOMAIN}
. Copy the new auth configmap back locally:
+
----
$ docker cp $CONFIGMAP_GENERATOR_ID:/tmp/external-ipa.yaml ./external-ipa.yaml
----
+
. The new configmap can then be applied to the auth httpd pod and then redeployed to take effect:
+
----
$ oc replace configmaps httpd-auth-configs --filename ./external-ipa.yaml
----

====== Stopping the `httpd-configmap-generator` container

When completed with `httpd-configmap-generator`, the container can simply be stopped and/or removed:

----
$ docker stop $CONFIGMAP_GENERATOR_ID
----

----
$ docker rmi --force manageiq/httpd_configmap_generator:latest
----


===== Running with OpenShift

.Pre-deployment tasks

The httpd-configmap-generator service account must be added to the httpd-scc-sysadmin SCC before the Httpd Configmap Generator can run.

. As the admin user, create the httpd-scc-sysadmin SCC:
+
----
$ oc create -f templates/httpd-scc-sysadmin.yaml
----
+
. Include the httpd-configmap-generator service account with the new SCC:
+
----
$ oc adm policy add-scc-to-user httpd-scc-sysadmin system:serviceaccount:<your-namespace>:httpd-configmap-generator
----
+
. Verify that the httpd-configmap-generator service account is now included in the httpd-scc-sysadmin SCC:
+
----
$ oc describe scc httpd-scc-sysadmin | grep Users
Users:        system:serviceaccount:<your-namespace>:httpd-configmap-generator
----


.Deploying the Httpd Configmap Generator Application

. As a regular user, run:
+
----
$ oc create -f templates/httpd-configmap-generator-template.yaml

$ oc get templates
NAME                        DESCRIPTION                                 PARAMETERS     OBJECTS
httpd-configmap-generator   Httpd Configmap Generator                   6 (all set)    3
----
+
. Deploy the Httpd Configmap Generator:
+
----
$ oc new-app --template=httpd-configmap-generator
----
+
. Check the readiness of the Httpd Configmap Generator:
+
----
$ oc get pods
NAME                                READY     STATUS    RESTARTS   AGE
httpd-configmap-generator-1-txc34   1/1       Running   0          1h
----

.Getting the pod name

For working with the `httpd-configmap-generator` script in the `httpd-configmap-generator` pod, it is necessary to
get the pod name reference below:

----
$ CONFIGMAP_GENERATOR_POD=`oc get pods | grep "httpd-configmap-generator" | cut -f1 -d" "`
----


.Generating a configmap for external authentication against IPA

The following example shows how to generate a configmap for external authentication against IPA.

. To generate a configmap for external authentication against IPA, run
+
----
$ oc rsh $CONFIGMAP_GENERATOR_POD httpd_configmap_generator ipa \
--host=appliance.example.com        \
--ipa-server=ipaserver.example.com  \
--ipa-domain=example.com            \
--ipa-realm=EXAMPLE.COM             \
--ipa-principal=admin               \
--ipa-password=smartvm1             \
-o /tmp/external-ipa.yaml
----
+
[NOTE]
====
`--host` above must be the DNS of the application exposing the httpd auth pod, i.e. ${APPLICATION_DOMAIN}.
====
+
. Copy the new auth configmap back locally:
+
----
$ oc cp $CONFIGMAP_GENERATOR_POD:/tmp/external-ipa.yaml ./external-ipa.yaml
----
+
. The new configmap can then be applied to the auth httpd pod and then redeployed to take effect:
+
----
$ oc replace configmaps httpd-auth-configs --filename ./external-ipa.yaml
----
+
. To generate a new auth configuration map, redeploy the `httpd-configmap-generator` pod first to get a clean environment before running the `httpd-configmap-generator` tool.

.Cleaning up

When done generating an auth-configmap, the `httpd-configmap-generator` pod can simply be scaled down:

----
$ oc scale dc httpd-configmap-generator --replicas=0
----

or deleted if no longer needed:

----
$ oc delete all  -l app=httpd-configmap-generator
$ oc delete pods -l app=httpd-configmap-generator
----



