[[installing-cloudforms]]
== Installing {product-title}

{product-title} can be installed and ready to configure in a few quick steps. After downloading {product-title} as a virtual machine image template from the Red Hat Customer Portal, the following process takes you through the steps of uploading the {product-title} appliance to Microsoft Azure.

[IMPORTANT]
====
After uploading the {product-title} appliance, you must configure the database for {product-title}; see xref:configuring_a_database[Configuring a Database for {product-title}].
====

ifdef::miq[]
[[obtaining-the-appliance]]
=== Obtaining the {product-title} Virtual Appliance

. In a browser, navigate to link:manageiq.org/download[].
. Select *Microsoft Azure* from the *--Choose your platform--* list.
. Select *Stable (fine-2)* from the *--Choose a release--* list.
. Follow the instructions to download the appliance.
endif::miq[]

ifdef::cfme[]
[[obtaining-the-appliance]]
=== Obtaining the {product-title} Virtual Appliance

. Go to link:https://access.redhat.com[access.redhat.com] and log in to the Red Hat Customer Portal using your customer account details.
. Click *Downloads* in the menu bar.
. Click *A-Z* to sort the product downloads alphabetically.
. Click menu:Red Hat CloudForms[Download Latest] to access the product download page.
. From the list of installers and images, select the {product-title} appliance specified for Microsoft Azure download link.
endif::cfme[]

[[uploading-the-appliance-to-microsoft-azure]]
=== Uploading the {product-title} Virtual Appliance to Microsoft Azure

You can upload the appliance to an Azure environment using the following two methods. Red Hat recommends using the PowerShell (AzureRm module) method.

* Using Azure PowerShell script
* Using Azure Command-Line Interface (Azure CLI)

To upload the {product-title} appliance file to Microsoft Azure, ensure the following requirements are met:

* Approximately 2 GB of space for each VHD image; 44+ GB of space, 16 GB RAM, and 4 VCPUs for the {product-title} appliance.
* link:https://azure.microsoft.com/en-us/free/[Microsoft Azure Account]. 
* Administrator access to the Azure portal.
* xref:converting-aligning-cfme-appliance-image[Converting and Aligning the {product-title} Virtual Appliance Image]
* Depending on your infrastructure, allow time for the upload.


[IMPORTANT]
====
Azure requires that the uploaded Virtual Hard Disk (VHD) files are in a fixed format. The {product-title_short} virtual appliance image .vhd file is dynamic by default. Currently, the Azure Powershell script and Azure CLI does not automatically convert the dynamic .vhd file to fixed during upload. To upload using either method, the {product-title_short} virtual appliance image .vhd file must be first converted from dynamic to fixed, and properly aligned to the nearest 1 MB boundary. Once converted and properly aligned, you can then upload the appliance virtual image .vhd file using either the Azure PowerShell or Azure CLI method.
====


[[converting-aligning-cfme-appliance-image]]
==== Converting and Aligning the {product-title_short} Virtual Appliance Image

Complete the following procedure to ensure the {product-title} dynamic .vhd file is aligned correctly, and is in a fixed-size VHD format. 

[NOTE]
====
All .vhd files provisioned for Microsoft Azure must be aligned to the nearest 1 MB boundary and be in a fixed-size VHD format. If you attempt to upload a dynamic .vhd file or one that is not properly aligned, virtual appliance provisioning will not work.
====

. Convert the dynamic .vhd file you downloaded in xref:obtaining-the-appliance[] to RAW format.
+
----
$ qemu-img convert -f vpc -O raw <image-name.vhd> <image-name.raw>

Example:

$ qemu-img convert -f vpc -O raw cfme-azure-5.7.2.1-1.x86_64.vhd cfme-azure-5.7.2.1-1.x86_64.raw
----
+
. Copy and paste the script below into a new bash shell script file, for example, `aligned-size.sh`. Change _rawdisk="image-name"_ to the image name for your file. This script will calculate the rounded file size to the nearest 1 MB boundary.
+
----
#!/bin/bash
rawdisk="cfme-azure-5.7.2.1-1.x86_64.raw"
MB=$((1024 * 1024))
size=$(qemu-img info -f raw --output json "$rawdisk" | gawk 'match($0, /"virtual-size": ([0-9]+),/, val) {print val[1]}')
rounded_size=$((($size/$MB + 1) * $MB))
echo "rounded size = $rounded_size"
export rounded_size
----
+
. Run the shell script. The file name `aligned-size.sh` is used in this example.
+
----
$ sh aligned-size.sh

rounded size = 34361835520
----
+
. Resize the virtual appliance image using the rounded size.
+
----
$ qemu-img resize -f raw <image-name.raw> <rounded_size>

Example:

$ qemu-img resize -f raw cfme-azure-5.7.2.1-1.x86_64.raw 34361835520

Image resized.
----
+
. Convert the appliance image to a fixed-size .vhd file.
+
----
$ qemu-img convert -f raw -o subformat=fixed -O vpc <image-name.raw> <image-name.vhd>

Example:

qemu-img convert -f raw -o subformat=fixed -O vpc cfme-azure-5.7.2.1-1.x86_64.raw cfme-azure-5.7.2.1-1.x86_64.vhd
----
+
. Get the virtual size for the .vhd file.
+
----
$ qemu-img info --output=json -f vpc <path-to-image>

Example:

$ qemu-img info --output=json -f vpc cfme-azure-5.7.2.1-1.x86_64.vhd

{
  "virtual-size": 34361835520,
  "filename": "cfme-azure-5.7.2.1-1.x86_64.vhd",
  "cluster-size": 2097152,
  "format": "vpc",
  "actual-size": 2133401600,
  "dirty-flag": false
}
----
. Divide the virtual-size value by 1024, twice. If the result is a whole number, the .vhd file is aligned properly. The example below shows that the file is properly aligned.
+
----
34361835520 / 1024 / 1024 = 32770
----
+



[IMPORTANT]
====
qemu-img version 1.5.3 is used in this procedure. Check the qemu-img version using the command: `yum info qemu-img`. If the version is 2.2.1 or later, add the option _force_size_ in the conversion command, for example, _subformat=fixed,force_size_. 
====

The {product-title} Azure virtual appliance image is ready for uploading and provisioning in Microsoft Azure.



[[uploading-the-appliance-using-azure-powershell-script]]
==== Uploading the {product-title_short} Virtual Appliance Using Azure Powershell Script

Complete the following steps to upload the {product-title} virtual appliance image you converted to a fixed-size VHD format and properly aligned per requirement using the procedure in xref:converting-aligning-cfme-appliance-image[].

[NOTE]
====
Make sure Azure Resource Manager cmdlets are available. See *To install the cmdlets* section in https://msdn.microsoft.com/en-us/library/mt125356.aspx[Azure Resource Manager Cmdlets].
====

. Log in to *Azure Resource Manager* using the cmdlet:
+
------
## Customize for Your Environment
$SubscriptionName = "my subscription"

Login-AzureRmAccount
Select-AzureRmSubscription -SubscriptionName $SubscriptionName
------
+  
When prompted, enter your user name and password for the Azure Portal.

. Upload the .vhd file to a storage account. As shown in the example script below, you will first create a *Resource Group* through the Portal UI or Powershell. Additionally, create the storage container defined in "BlobDestinationContainer" in advance.
+
------
Example Script:

## Customize for Your Environment
$SubscriptionName = "my subscription"

$ResourceGroupName = "test"
$StorageAccountName = "test"

$BlobNameSource = "cfme-test.vhd"
$BlobSourceContainer = "templates"
$LocalImagePath = "C:\tmp\$BlobNameSource"

##

# Upload VHD to a "templates" directory. You can pass a few arguments, such as `NumberOfUploaderThreads 8`. The default number of uploader threads is `8`. See https://msdn.microsoft.com/en-us/library/mt603554.aspx

Add-AzureRmVhd -ResourceGroupName $ResourceGroupName -Destination https://$StorageAccountName.blob.core.windows.net/$BlobSourceContainer/$BlobNameSource -LocalFilePath $LocalImagePath -NumberOfUploaderThreads 8
------
+
. Create a virtual machine. Then, define your VM and VHD name, your system/deployment name and size. Next, you will set the appropriate Storage, Network and Configuration options for your environment.
+
------
Example Script:

## Customize for Your Environment

$BlobNameDest = "cfme-test.vhd"
$BlobDestinationContainer = "vhds"
$VMName = "cfme-test"
$DeploySize= "Standard_A3"
$vmUserName = "user1"

$InterfaceName = "test-nic"
$VNetName = "test-vnet"
$PublicIPName = "test-public-ip"

$SSHKey = <your ssh public key>

##

$StorageAccount = Get-AzureRmStorageAccount -ResourceGroup $ResourceGroupName -Name $StorageAccountName

$SourceImageUri = "https://$StorageAccountName.blob.core.windows.net/templates/$BlobNameSource"
$Location = $StorageAccount.Location
$OSDiskName = $VMName

# Network
$Subnet1Name = "default"
$VNetAddressPrefix = "10.1.0.0/16"
$VNetSubnetAddressPrefix = "10.1.0.0/24"
$PIp = New-AzureRmPublicIpAddress -Name $PublicIPName -ResourceGroupName $ResourceGroupName -Location $Location -AllocationMethod Dynamic -Force
$SubnetConfig = New-AzureRmVirtualNetworkSubnetConfig -Name $Subnet1Name -AddressPrefix $VNetSubnetAddressPrefix
$VNet = New-AzureRmVirtualNetwork -Name $VNetName -ResourceGroupName $ResourceGroupName -Location $Location -AddressPrefix $VNetAddressPrefix -Subnet $SubnetConfig -Force
$Interface = New-AzureRmNetworkInterface -Name $InterfaceName -ResourceGroupName $ResourceGroupName -Location $Location -SubnetId $VNet.Subnets[0].Id -PublicIpAddressId $PIp.Id -Force

# Specify the VM Name and Size
$VirtualMachine = New-AzureRmVMConfig -VMName $VMName -VMSize $DeploySize

# Add User
$cred = Get-Credential -UserName $VMUserName -Message "Setting user credential - use blank password"
$VirtualMachine = Set-AzureRmVMOperatingSystem -VM $VirtualMachine -Linux -ComputerName $VMName -Credential $cred

# Add NIC
$VirtualMachine = Add-AzureRmVMNetworkInterface -VM $VirtualMachine -Id $Interface.Id

# Add Disk
$OSDiskUri = $StorageAccount.PrimaryEndpoints.Blob.ToString() + $BlobDestinationContainer + "/" + $BlobNameDest

$VirtualMachine = Set-AzureRmVMOSDisk -VM $VirtualMachine -Name $OSDiskName -VhdUri $OSDiskUri -CreateOption fromImage -SourceImageUri $SourceImageUri -Linux

# Set SSH key
Add-AzureRmVMSshPublicKey -VM $VirtualMachine -Path “/home/$VMUserName/.ssh/authorized_keys” -KeyData $SSHKey

# Create the VM
New-AzureRmVM -ResourceGroupName $ResourceGroupName -Location $Location -VM $VirtualMachine
------
+


[NOTE]
====
These are the procedural steps as of the time of writing. For more information, see the following Azure documentation. 

* https://azure.microsoft.com/en-us/documentation/articles/powershell-azure-resource-manager

The steps covered in the following article are for a Windows machine, however, most of the items are common between Windows and Linux.

* https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-windows-create-powershell
====


[[uploading-the-appliance-using-azure-cli]]
==== Uploading and Provisioning the {product-title_short} Virtual Appliance Using Azure Command-Line Interface

Although it is recommended to use the PowerShell method, you can upload the appliance to an Azure environment using the Azure Command-Line Interface (Azure CLI).


.Install Azure CLI 2.0:

Complete the steps below to install Azure CLI 2.0 using curl. See link:https://docs.microsoft.com/en-us/cli/azure/install-azure-cli[] for other installation methods.

. Make sure Python is updated and install the prerequisite packages.
+
----
$ sudo yum update
$ sudo yum install -y gcc libffi-devel python-devel openssl-devel
----
+
. Install Azure CLI 2.0.
+
----
$ curl -L https://aka.ms/InstallAzureCli | bash
----
+




.Uploading and Provisioning the {product-title_short} Virtual Appliance Using Azure CLI:

Complete the following steps to upload and provision the {product-title} virtual appliance you converted to a fixed-size VHD format and properly aligned per requirement using the procedure in xref:converting-aligning-cfme-appliance-image[].


. Upload the image to the storage container. It may take several minutes. Note: Enter `az storage container list` to get the list of storage containers.
+
----
$ az storage blob upload --account-name <storage-account-name> --container-name <container-name> --type page --file <path-to-vhd> --name <image-name>.vhd

Example:

$ az storage blob upload --account-name azrhelclistact --container-name azrhelclistcont --type page --file cfme-azure-5.7.2.1-1.x86_64.vhd --name cfme-azure-5.7.2.1-1.x86_64.vhd 
Percent complete: %100.0
----
+
. Get the URL for the uploaded .vhd file. You will need to use this URL in the following step.
+
----
$ az storage blob url -c <container-name> -n <image-name>.vhd

Example:

$ az storage blob url -c azrhelclistcont -n cfme-azure-5.7.2.1-1.x86_64.vhd "https://azrhelclistact.blob.core.windows.net/azrhelclistcont/cfme-azure-5.7.2.1-1.x86_64.vhd"
----
+
. Create the virtual machine. Note that the following command uses `--generate-ssh-keys`. In this example, the private/public key pair `/home/clouduser/.ssh/id_rsa` and `/home/clouduser/.ssh/id_rsa.pub` are created.
+
----
$ az vm create --resource-group <resource-group> --location <azure-region> --use-unmanaged-disk --name <vm-name> --storage-account <storage-account-name> --os-type linux --admin-username <administrator-name> --generate-ssh-keys --image <URL>

az vm create --resource-group azrhelclirsgrp --location southcentralus --use-unmanaged-disk --name cfme-appliance-1 --storage-account azrhelclistact --os-type linux --admin-username clouduser --generate-ssh-keys --image https://azrhelclistact.blob.core.windows.net/azrhelclistcont/cfme-azure-5.7.2.1-1.x86_64.vhd

{
  "fqdns": "",
  "id": "/subscriptions//resourceGroups/azrhelclirsgrp/providers/Microsoft.Compute/virtualMachines/cfme-appliance-1",
  "location": "southcentralus",
  "macAddress": "",
  "powerState": "VM running",
  "privateIpAddress": "10.0.0.4",
  "publicIpAddress": "12.84.121.147",
  "resourceGroup": "azrhelclirsgrp"
}
----
+
Make a note of the public IP address. You will need this to log in to the virtual machine in the next step.
. Start an SSH session and log in to the appliance.
+
----
$ ssh -i <path-to-ssh-key> <admin-username@public-IP-address>

Example:

$ ssh  -i /home/clouduser/.ssh/id_rsa clouduser@12.84.121.147
The authenticity of host '12.84.121.147' can't be established.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '12.84.121.147' (ECDSA) to the list of known hosts.

Welcome to the Appliance Console

For a menu, please type: appliance_console
----
+
. Enter `sudo appliance_console` at the prompt. The summary screen appears.

You have successfully provisioned a {product-title} virtual appliance in Microsoft Azure. 


[NOTE]
====
The exported storage connection string does not persist after a system reboot. If any of the commands in the above steps fail, export the storage connection string again using the following commands:

. Get the storage account connection string.
+
----
$ az storage account show-connection-string -n <storage-account-name> -g <resource-group>

Example:

$ az storage account show-connection-string -n azrhelclistact -g azrhelclirsgrp
{
  "connectionString": "DefaultEndpointsProtocol=https;EndpointSuffix=core.windows.net;AccountName=azrhelclistact;AccountKey=NreGk...=="
}
----
+
. Export the connection string. Copy the connection string and paste it into the following command. This connects your system to the storage account. 
+
----
$ export AZURE_STORAGE_CONNECTION_STRING="<storage-connection-string>"

Example:

$ export AZURE_STORAGE_CONNECTION_STRING="DefaultEndpointsProtocol=https;EndpointSuffix=core.windows.net;AccountName=azrhelclistact;AccountKey=NreGk...=="
----
+
====




