[id="Discovery"]
= Discovery and Assessment

Discovery and assessment comprise the high-level planning of your migration. At this stage, you will formulate a specific migration goal, for example, "I want to migrate 2000 virtual machines, with 200 TB of data, in less than 6 months." To achieve this goal, you need to discover your current environment

The following questions will guide you through the discovery process:

* What am I migrating?
+
Identify the hosts and virtual machines to be migrated. If your deployment is large and complex, you may want to divide your resources into migration groups.

* What is the maximum number of resources that I can migrate?
+
There is no maximum size for migration. However, you may not want to migrate all your virtual machines at the same time, in order to minimize the impact on your users.

* What resources will my target environment require?
+
Your target environment must be large enough to hold the migrated virtual machines, in addition to the original VMware virtual machines. The VMware virtual machines are not affected by the migration process. Their power state after the migration will be the same as before the migration.

* What am I missing?
+
Identify resource gaps, such as bandwidth, storage, licenses, or a suitable maintenance window.

* How long will the migration take?
+
There are no hard and fast rules to determine how long the actual migration will take. This is determined on a case-by-case basis. It may be possible to do a phased migration of your applications, if they are distributed in a high-availability architecture, without downtime at the application layer.

* What impact will the migration have on my users?
+
Assess the effect the migration may have on a production environment. Check whether users will lose access to critical applications.

[discrete]
== Migration Example

This migration example is provided to help you estimate how long your migration may take.

The following infrastructure took 1 hour and 30 minutes to migrate:

* Infrastructure:

** 10 virtual machines (100 GB RAM).
** Virtual machine disks 2/3 full (total of 1 TB of data).

* Hardware:

** Strong host (40 cores, 500 GB RAM).
** Fast SSD XtremIO storage.
** Fiber Channel 8 interface for host-to-storage connection.
** 10GbE network interface cards for all other connections.

[discrete]
== Best Practices

* Create migration groups, so that you are not migrating all of your virtual machines at the same time. The following questions provide guidelines:

** How are the virtual machines grouped now?
** Which virtual machines should be migrated together?
** What workloads should be migrated together?
** What applications must remain available?

* Consider which parts of the workload to migrate first:

** Databases
** Applications
** Web servers
** Load balancers

* Keep linked applications together, so that they migrate at the same time.

* Rebooting or deleting snapshots should be done before the migration, to reduce the risk of failure.

* Schedule your migration carefully, to minimize the impact on your users.

* Stagger the migration schedules.

* Move critical applications during maintenance windows.

* Plan for redundancy.

* Ensure that you have sufficient space for the migration. The migration process does not delete the original virtual machines.

* Minimize the impact on your environment, by creating multiple migration plans to control and throttle the migration process.

* Prepare your users for downtime.
