[id="Discovery_and_Assessment"]
= Discovery and Assessment

The discovery and assessment phase is the foundation of the planning phase of your migration. At the end of this phase, you will formulate a specific migration goal, for example, "I want to migrate 2000 virtual machines, with 200 TB of data, in less than 6 months." To achieve this goal, you will discover and assess your current environment.

The following questions will guide you through the process:

What am I migrating?::
Identify the hosts and virtual machines to be migrated. If your deployment is large and complex, you may want to divide your resources into migration groups.

What is the maximum number of resources that I can migrate?::
There is no maximum size for migration. However, you may not want to migrate all your virtual machines at the same time, in order to minimize the impact on your users.

What resources will my target environment require?::
Your target environment must be large enough to hold the migrated virtual machines, in addition to the source virtual machines. The source virtual machines are not affected by the migration process and their power state will be the same after the migration as it was before.

What am I missing?::
Identify resource gaps, such as bandwidth, storage, licenses, or a suitable maintenance window.

How long will the migration take?::
There are no hard and fast rules to determine how long the actual migration will take. This is determined on a case-by-case basis. The migration example described below can help you to estimate the time required. It may be possible to do a phased migration of your applications, if they are distributed in a high-availability architecture, without downtime at the application layer.

What impact will the migration have on my users?::
Assess the effect the migration may have on a production environment. Check whether users will lose access to critical applications.

include::modules/ref_Migration_example.adoc[leveloffset=+1]
include::modules/ref_Best_practices.adoc[leveloffset=+1]
