*This draft is a work in progress and internal only.*

* link:https://docs.google.com/document/d/13MKOhFta3fVU_QKPBOGBXTj9fHJGWk8g3h0Ph2WtrEs/edit?ts=5b17ef07#heading=h.6jbfzvwb9yos[Content Plan]
* Google docs version for link:https://docs.google.com/document/d/1Wfv7HvKGCdiQ8gw63G47F1uRwbu5etGGWqG5Pp_edfY/edit?usp=sharing[comments]
* GA date: August 14, 2018
* Contacts: link:mailto:sbream@redhat.com[Steve Bream] (CS), link:mailto:apinnick@redhat.com[Avital Pinnick] (TW)


[[Introduction]]
= Introduction

{product-title} is Red Hat's solution for moving your virtual machines from VMware to Red Hat Virtualization. By moving from VMware to Red Hat Virtualization, you can reduce licensing costs and dependence on proprietary virtualization, while investing in transformative technologies such as multi-cloud management, automation, and containers.

Red Hat Virtualization (RHV) is an enterprise-grade virtualization platform built on Red Hat Enterprise Linux. With Red Hat Virtualization, you can manage your entire virtual infrastructure, including hosts, virtual machines, networks, storage, and users, from a centralized graphical user interface or with a REST API.

The infrastructure migration is performed with Red Hat CloudForms. CloudForms is a user interface, providing the control and automation required to manage challenging enterprise environments.

The infrastructure migration has 4 key stages:

* Prerequisites: Installing Red Hat Virtualization, Red Hat Virtualization Host, and Red Hat CloudForms. Creating and configuring RHV conversion hosts.
* Discovery: Discovering your environment to plan your migration.
* Planning: Planning for Migration.
* Migration: Creating an infrastructure mapping, creating and running a migration plan.
* Troubleshooting: Re-migrating virtual machines, log files, common issues or mistakes.
