[id="Discovery"]
= Discovery

Discovery is the high-level planning of your migration. At this stage, you will formulate a migration goal, for example, "I want to migrate 2000 virtual machines, with 200 TB of data, in less than 6 months."

In order to achieve this goal, you will need to discover your current environment and ask the following questions:

* What am I migrating?
+
You will need to identify the hosts and virtual machines for migration. If your deployment is large and complex, you will probably divide your resources into migration groups.

* Scaling
+
TBD: What are the minimum and maximum size migrations? At least a note about max size

* What resources will my target environment require?
+
Your target environment must be large enough to hold the migrated virtual machines, in addition to the VMware virtual machines (the VMware virtual machines will not be affected by the migration process, in case you need to roll back the migration for any reason).

* Identifying resource gaps (What am I missing? Ex: bandwidth, storage, licenses, maintenance window) - a reminder

* How long will the migration take?
+
There are no hard and fast rules to determine how long the actual migration will take. This is determined on a case-by-case basis. It may be possible to do a phased migration of your applications, if they are distributed in a high availability architecture, without downtime at the application layer.

* What impact will the migration have on my users?
+
Will the migration disrupt the production environment? Will users lack access to critical applications?
