[id='ref_Troubleshooting']
= Troubleshooting

[discrete]
== Re-migrating Virtual Machines

If a migration fails for any reason (for example, network communication between the source and target providers is disrupted during the migration process), you can re-migrate the virtual machines:

. Delete the target virtual machines that were created during the failed migration. Not doing so will cause the migration to fail because a target machine with the same name already exists.
. Create a xref:CSV_import[CSV file] with the names and, optionally, providers, of the source virtual machines.
+
[NOTE]
====
The virtual machines cannot be discovered by the migration plan because they are marked in the CloudForms VMDB as `migrated`.
====

. Create and run a migration plan, using the CSV file to import the virtual machines.

[discrete]
== Log Files

If a migration plan does not complete successfully, check the logs for errors:

* CloudForms migration log: `/var/www/miq/vmdb/log/automation.log`
* Conversion host logs: `/tmp`

[discrete]
== Common Issues and Mistakes

* Incorrect infrastructure mapping.
+
If you create an infrastructure mapping and subsequently add or remove providers or provider objects, the infrastructure mapping will not work. This is because the object IDs of the providers and their objects have changed. Solution: Delete the infrastructure mapping and re-create it.

* RHV host credentials are not set in CloudForms.
+
If the RHV host credentials are not set, CloudForms is unable to communicate with the hosts. Solution: Authenticate the RHV hosts with CloudForms. See xref:Authenticating_RHV_Manager_and_Hosts[].

* RHV conversion host tags not set correctly.
+
If the conversion host tags are not set, the migration will fail. Solution: Set the appropriate tags for the RHV conversion hosts and run the `conversion_host_check` playbook to verify that the RHV hosts are configured correctly. See xref:Configuring_rhv_conversion_hosts[Creating RHV Conversion Hosts].

* Incorrect attributes in the virtual machine CSV import file.
+
Solution: Create a new migration plan, import the correct CSV file, and run the migration plan.
