[[_sect_reports]]
= Reports

Click the [label]#Reports# accordion under menu:Cloud Intelligence[Reports] to see a list of reports available.
These reports have been constructed to help you view the most commonly requested and significant data.
From here, you can also create reports if you have appropriate access.
CloudForms Management Engine provides a large group of default reports organized into categories.
Each category has its own set of subfolders. 

* Use [label]#Configuration Management# to see hardware, application, network, service, user account, operating system, and snapshot information for all of your items. 
* Use [label]#Migration Readiness# to see information specifically related to items required to migrate a virtual machine. 
* Use [label]#Operations# to look at free space on registered and unregistered virtual machines, to see power states for virtual machines, and see which offline virtual machines have snapshots or have never been analyzed.
  You are also provided with reports specifically related to the operation of CloudForms Management Engine, such as user ids and snapshots taken by CloudForms Management Engine. 
* Use [label]#VM Sprawl# to check on usage information and disk waste. 
* Use [label]#Relationships# to see virtual machine, folder, and cluster relationships. 
* Use [label]#Events# to view operations and configuration management events. 
* Use [label]#Performance by Asset Type# to see a report on the performance of your virtual infrastructure.
  You must be capturing capacity and utilization data to get this information. 
* Use [label]#Running Processes# to view the information on processes running on a virtual machine.
  You must have domain credentials entered for the zone to collect the info for these reports, and the virtual machine must have been analyzed at least once. 
* [label]#Trending# shows projections of datastore capacity and host CPU and memory use. 
* [label]#Provisioning# shows provisioning activity based on the approver, datastore, requester, and virtual machine. 

For a complete list of Reportable Fields in CloudForms Management Engine, see xref:_appe_reportable_fields_in_cloudforms_management_engine[]

:leveloffset: 2
include::running_reports.adoc[]


:leveloffset: 2
include::viewing_reports.adoc[]


:leveloffset: 2
include::topics/Adding_a_Report.adoc[]


:leveloffset: 2
include::topics/Copying_a_report.adoc[]


:leveloffset: 2
include::topics/Editing_a_Report.adoc[]


:leveloffset: 2
include::topics/Deleting_a_Report.adoc[]


:leveloffset: 2
include::topics/To_import_a_report.adoc[]


:leveloffset: 2
include::topics/To_export_a_report.adoc[]


:leveloffset: 2
include::report_menus.adoc[]


