
[[_sect_report_menus]]
= Report Menus

By default, all account roles have the same reports available.
If you have the super administrator or administrator role, you can customize the accordions, the folders within them, and the locations of your reports. 

NOTE: When you create your own report, the report is not automatically available.
You must add it to a report menu. 

The report menu is a hierarchical structure that consists of the following components: 

* The [label]#Top Level# under which the accordions are shown.
  ([label]#Top Level# is only displayed when you are in the report menu editor.)  					
* Accordions that are general categories for the reports.
  The defaults supplied are [label]#Configuration Management#, [label]#Migration Readiness, Operations#, [label]#VM Sprawl#, [label]#Relationships#, and [label]#Events#.
* Folders that are used to further organize reports within an accordion.
  For example, under the [label]#Configuration Management#, you would see folders for virtual machines, hosts, and other virtual infrastructure components. 
* Reports that are stored directly in the folders. 

:leveloffset: 3
include::topics/To_manage_Report_Menu_Accordions.adoc[]


:leveloffset: 3
include::topics/To_manage_Report_Menu_Folders.adoc[]


:leveloffset: 3
include::topics/To_organize_reports_in_Report_Menus.adoc[]


