[[installing-cloudforms-aws]]
== Installing {product-title}

Installing {product-title} consists of the following steps:

. Downloading the appliance for your environment as a virtual machine image template.
. Setting up a virtual machine based on the appliance.
. Configuring the {product-title_short} appliance.

After you have completed all the procedures in this guide, you will have a working environment on which additional customizations and configurations can be performed.

ifdef::miq[]
[[obtaining-the-appliance]]
=== Obtaining the appliance

. In a browser, navigate to link:manageiq.org/download[].
. Select *Amazon* from the *--Choose your platform--* list.
. Select *Stable* from the *--Choose a release-git add-* list.
. Follow the instructions to download the appliance.
endif::miq[]

ifdef::cfme[]
[[obtaining-the-appliance]]
=== Obtaining the Appliance

. Go to link:https://access.redhat.com[access.redhat.com] and log in to the Red Hat Customer Portal using your customer account details.
. Click *Downloads* in the menu bar.
. Click *A-Z* to sort the product downloads alphabetically.
. Click *Red Hat CloudForms* to access the product download page.
. From the list of installers and images, click the *Download Now* link for *CFME EC2 Virtual Appliance*.
endif::cfme[]

[[uploading-the-appliance-on-amazon-ec2]]
=== Uploading the Appliance to an Amazon S3 Bucket

Uploading the {product-title} appliance file onto Amazon EC2 has the following requirements:

* 44 GB of space on the chosen datastore.
* 12 GB RAM.
* 4 vCPUs.
* Depending on your infrastructure, allow time for the upload.
* Prerequisites on Amazon EC2: 
** An Amazon S3 bucket to store disk images.
** A VM import service role (IAM role) named `vmimport`. 
** See xref:prerequisite-steps-on-amazon-ec2[].

.Uploading the appliance image:

. Upload to the Amazon S3 Bucket the {product-title} appliance VHD image obtained in xref:obtaining-the-appliance[] from your local file system using your choice of tool.


[[prerequisite-steps-on-amazon-ec2]]
==== Prerequisite Steps on Amazon EC2

[IMPORTANT]
====
These are the prerequisites and procedural steps as of the time of writing. For more information on creating an Amazon S3 Bucket and VM Import Service Role, see the link:https://docs.aws.amazon.com/vm-import/latest/userguide/vmimport-image-import.html[Amazon EC2 documentation].
====

Complete the following prerequisite steps on AWS:

. Install the AWS client on the computer you want to interact with the AWS API from.
+
----
$ pip install awscli
----
+
. Configure and download your AWS secret/access key by following the steps in the link:https://docs.aws.amazon.com/general/latest/gr/managing-aws-access-keys.html[Managing Access Keys for Your AWS Account] documentation.
. Configure the AWS client with your access/secret key.
+
----
Example:

$ aws configure
AWS Access Key ID [******]: ACCESS_KEY
AWS Secret Access Key [******]: SECRET_KEY
Default region name [None]:
Default output format [None]:
----
+
. Create the `trust-policy.json` file for the *vmimport* role.
+
----
Example:

{
   "Version": "2012-10-17",
   "Statement": [
      {
         "Effect": "Allow",
         "Principal": { "Service": "vmie.amazonaws.com" },
         "Action": "sts:AssumeRole",
         "Condition": {
            "StringEquals":{
               "sts:Externalid": "vmimport"
            }
         }
      }
   ]
}
----
+
. Create the *vmimport* role using the `trust-policy.json` file that we just created.
+
----
$ aws iam create-role --role-name vmimport --assume-role-policy-document file://trust-policy.json
----
+
[NOTE]
====
This user must have permissions to create and modify IAM roles.
====
. Create the `role-policy.json` file. Be sure to use the exact image name that you uploaded to the S3 Bucket.
+
----
Example:

{
   "Version": "2012-10-17",
   "Statement": [
      {
         "Effect": "Allow",
         "Action": [
            "s3:ListBucket",
            "s3:GetBucketLocation",
            "s3:FullAccess"
         ],
         "Resource": [
            "arn:aws:s3:::NAME_OF_IMAGE_IN_S3_BUCKET"
         ]
      },
      {
         "Effect": "Allow",
         "Action": [
            "s3:GetObject"
         ],
         "Resource": [
            "arn:aws:s3:::NAME_OF_IMAGE_IN_S3_BUCKET/*"
         ]
      },
      {
         "Effect": "Allow",
         "Action":[
            "ec2:ModifySnapshotAttribute",
            "ec2:CopySnapshot",
            "ec2:RegisterImage",
            "ec2:Describe*",
            "ec2:FullAccess"
         ],
         "Resource": "*"
      }
   ]
}
----
+
. Apply the *vmimport* role to the {product-title_short} appliance image you uploaded to the S3 Bucket.
+
----
$ aws iam put-role-policy --role-name vmimport --policy-name vmimport --policy-document file://role-policy.json
----
+








[[importing-the-appliance-on-amazon-ec2]]
=== Importing the Appliance to Amazon Elastic Compute Cloud (Amazon EC2)

To import the appliance:

. Create a containers.json file: 
+  
----
[
  {
  "Description": "NAME OF INSTANCE",
  "Format": "vhd",
  "UserBucket": {
        "S3Bucket": "BUCKET WITH UPLOADED .VHD IMAGE",
        "S3Key": "NAME OF .VHD IMAGE"
      }
  }
]
----
+
. Use AWS-CLI tools to import the image. Run the following command:
+
----
$ aws ec2 import-image --disk-containers file://containers.json --region BUCKET_REGION
----
+
. Check the progress of your imported image by running the following command:
+
----
 $ aws ec2 describe-import-image-tasks --region BUCKET_REGION --import-task-ids import-ami-AMI_ID_GOT_FROM_RESPONSE
----
+


