[[Adding_a_Satellite_6_Provider_to_CloudForms]]
== Adding a Satellite 6 Provider to CloudForms
To start provisioning bare metal machines, you need at least one Red Hat Satelllite 6 provider added to Red Hat CloudForms Management Engine. The following procedure show how to do this.

=== Adding a Red Hat Satellite 6 Provider
[arabic]
. Log in to your Red Hat CloudForms Management Engine UI as the administration user.
. Navigate to Infrastructure → Configuration Management. The providers list appears and should be empty.
. Select Configuration → Add a new Provider. A empty form for your new Satellite 6 provider appears.
. Enter a Name for the provider. This is just a plain text name to help identify your provider in the Red Hat CloudForms Management Engine UI. For example, Satellite 6.
. Enter a URL for the provider. This is the root URL for the Satellite 6 server and can be either an IP address or a hostname. For example, http://satellite6.example.com.
. Select Verify Peer Certificate to use encrypted communication with the provider. This requires the SSL certificates from your Red Hat Satellite 6 provider.
. Enter a Username for a user on the provider. Ideally, this would be a user in Satellite 6 with administrative access.
. Enter a Password and enter it again to Verify Password. Click the Validate button to test your connection with the Red Hat Satellite 6 server.
. Click Add to confirm your settings and save the provider.

Red Hat CloudForms Management Engine saves the Satellite 6 provider in its database and triggers a refresh of resources detected in the provider.


