[[Reprovisioning_a_Bare_Metal_Host_in_Red_Hat_CloudForms]]
== Reprovisioning a Bare Metal Host in Red Hat CloudForms

The current inventory of your Red Hat Satellite 6 server is now visable in Red Hat CloudForms Management Engine. The next procedure is an example of reprovisioning an existing bare metal system into a new hostgroup. For this example, your Red Hat Satellite 6 environment requires the following:

- An existing bare metal system stored as a host object in your Red Hat Satellite 6 server. This system can either:
** A standalone system previously provisioned without a host group.
** A system previously provisioned using a host group.
- A target host group. This host group contains the system configuration to apply to the host when reprovisioning it. This includes:
** A new operating system installation, including a new partition table.
** A new networking configuration that the Red Hat Satellite 6 server defines and manages.
** Registration to any Red Hat subscriptions and repositories assigned to the hostgroup.
** Application of any Puppet modules assigned to the hostgroup.

=== Reprovisioning a Bare Metal Host in Red Hat CloudForms

[arabic]
. If you have not navigated elsewhere, the +Infrastructure+ → +Configuration Management+ screen displays your Red Hat Satellite 6 server.
. Select +Configured Systems+ from the accordion menu on the left. This displays our system list.
. Select one or more +hosts+ to reprovision. Use the checkboxes to select these systems.
. Select +Lifecycle+ → +Provision+ Configured Systems. This displays the form for provisioning details.
. Under the +Request+ tab, enter the following details:
[loweralpha]
.. +E-Mail address+
.. +First Name+
.. +Last Name+
.. This form also contains optional fields for users to enter a plain text +Note+ to inform Red Hat CloudForms administrators of any special details and a field their manager's Name in case administrators require approval from a user's manager.
. Select the +Purpose+ tab and select any Red Hat CloudForms policy tags that apply to the system.
. Select the +Catalog+ tab. This screen displays the list of chosen machines to reprovision and their current details. Select a +target host group+ from the +Configuration Profile list+. Red Hat CloudForms communicates to Red Hat Satellite to apply the configuration from this host group to the selected host and reprovision the system.
. Select the +Customise+ tab. This screen displays some customizable fields for the selected system. You can change the +Root Password+ or change the +Hostname+ and +IP Address+. Note that these fields are optional as the host group in Red Hat Satellite 6 contains this information. The fields here will override the settings from the hostgroup.
+
[Important]
.Important
-------
Provisioning bare metal systems still requires access to the network that Red Hat Satellite 6 manages. This is because Red Hat Satellite controls PXE booting, kickstarts, and Puppet configuration for bare metal systems. Ensure the IP address you enter in Red Hat CloudForms Management Engine can access a DHCP service that Red Hat Satellite 6 provides either through the main server or through a Red Hat Satellite 6 Capsule server.
-------
+
. Select the +Customise+ tab. This screen allows you to either launch the provisioning process Immediately on Approval or using a schedule. Click +Schedule+ to show the date and time fields you use to schedule the provisioning.
. When you have completed all sections of the provisioning form, click +Submit+.

This submits the provisioning request. Depending on the request settings on your Red Hat CloudForms appliance, this provisioning request might require approval from an administrator. If not, the provisioning request launches depending on your choce for the Schedule.

[Note]
.Note
-------
Previously provisioned hosts might require manual selection of PXE boot from the boot menu or else they might boot to hard disk and not reprovision.
-------
