= Migration Analytics Guide
:imagesdir: images
:vernum: 1.0
:toc: left
:toclevels: 3
:compat-mode:
:experimental:

:context: migration_analytics
:numbered:

toc::[]

Migration Analytics enables you to examine your VMware virtual machines and collect data about their operating systems and workloads, using the link:https://access.redhat.com/documentation/en-us/red_hat_cloudforms[Red Hat CloudForms] user interface.

Migration Analytics supports VMware version 6.0 (and later).

You then use the Migration Analytics service at link:https://cloud.redhat.com/beta[https://cloud.redhat.com/beta] to analyze the data and create a report. This report provides an estimate of the initial savings in migrating to Red Hat, a detailed analysis of the VMware virtual machines, and recommendations to help you plan your migration.

[NOTE]
====
Migration Analytics is available as a technology preview for Red Hat CloudForms 5.0. For more information on the support scope for features marked as technology previews, see link:https://access.redhat.com/support/offerings/techpreview/[Technology Preview Features Support Scope].
====

[id='Understanding-migration-analytics']
== Understanding Migration Analytics

Migration Analytics involves the following tasks:

. xref:Deploying-migration-analytics[Deploying Migration Analytics] in Red Hat CloudForms
. xref:Scanning-vms-for-migration-analytics[Scanning the VMware virtual machines]
. xref:Collecting-inventory-data[Collecting the inventory data] for Migration Analytics
. xref:Creating-migration-analytics-reports[Creating a report] with the Migration Analytics service
+
See xref:Migration-analytics-report[] for more information about the contents of the report.

The xref:Migration-analytics-workflow[Migration Analytics workflow] describes the process and architecture in greater detail.

include::modules/Migration-analytics-workflow.adoc[leveloffset=+2]
include::modules/Migration-analytics-report.adoc[leveloffset=+2]

[id='Deploying-migration-analytics']
== Deploying Migration Analytics

You can deploy Migration Analytics by installing CloudForms on VMware vSphere and enabling the Migration Analytics menu.

include::modules/Installing-cloudforms.adoc[leveloffset=+2]
include::modules/Configuring-cloudforms.adoc[leveloffset=+2]
include::modules/Creating-analysis-profile-for-migration-analytics.adoc[leveloffset=+2]

[id='Using-migration-analytics']
== Using Migration Analytics

In the CloudForms user interface, you scan the VMware virtual machines and collect the inventory data.

In a browser, you navigate to the Migration Analytics service at link:https://cloud.redhat.com/beta[https://cloud.redhat.com/beta] and create a report. The Migration Analytics service uploads the inventory data, analyzes it, and generates a report.

include::modules/Scanning-vms-for-migration-analytics.adoc[leveloffset=+2]
include::modules/Collecting-inventory-data.adoc[leveloffset=+2]
include::modules/Creating-migration-analytics-reports.adoc[leveloffset=+2]
