---
title: ManageIQ
title_short: ManageIQ
title_short_l: manageiq
title_abbr_uc: MIQ
appliance_rpm_dir: /opt/manageiq/manageiq-appliance
operator_api_version: v1alpha1
operator_custom_resource_definition_name_plural: manageiqs
operator_custom_resource_definition_name_singular: manageiq
operator_custom_resource_kind: ManageIQ
operator_directory: https://github.com/ManageIQ/manageiq-pods/tree/master/manageiq-operator
operator_namespace: manageiq.org
workflow_service_account: manageiq-default
import_opentofu: runuser --login manageiq --command 'podman --root=/var/lib/manageiq/containers/storage image load --input /tmp/<OpenTofu_image>'
opentofu_image_name: <OpenTofu_image>
container_image: docker.io/manageiq/opentofu-runner:latest
vendor: ManageIQ
