// Module included in the following assemblies:
// IMS_1.3/master.adoc
[id='Updating_vmware_host_ip_api_{context}']
= Updating a VMware host's IP address for migration

By default, CloudForms uses the management network for migration, which may not provide the best performance.

You can update a VMware host's IP address with the CloudForms API to use a faster network for migration.

.Procedure

. Obtain the VMware host ID:
+
----
$ curl -s -k -u <user>:<password> \ <1>
'https://<CloudForms_FQDN>/api/hosts/?filter[]=name=<VMware_host_FQDN>' <2>
----
<1> Specify your CloudForms user name and password.
<2> Specify the CloudForms FQDN and the VMware host's FQDN.
+
The VMware host ID appears at the end of the `resources` URL, after `/api/hosts/`:
+
[source,json]
----
{
  "name": "hosts",
  ...
  "resources": [{"href":"https://<CloudForms_FQDN>/api/hosts/<VMware_host_ID>"}]
  ...
}
----

. Update the VMware host's IP address with the `TransformationIPAddress` custom attribute:
+
----
# curl -s -k -u <user>:<password> \ <1>
'https://<CloudForms_FQDN>/api/hosts/<VMware_host_ID>/custom_attributes/' \ <2>
-X POST -d '{"action": "add", "resources": [{"name": "TransformationIPAddress","<VMware_IP_address>"}]} <3>
----
<1> Specify your CloudForms user name and password.
<2> Specify the CloudForms FQDN and the VMware host ID.
<3> Specify the IP address of the VMware host.

. Verify the VMware host's updated IP address:
+
----
$ curl -s -k -u <user>:<password> \ <1>
'https://<CloudForms_FQDN>/api/hosts/<VMware_host_ID>?expand=custom_attributes' <2>
----
<1> Specify your CloudForms user name and password.
<2> Specify the CloudForms FQDN and the VMware host ID.
+
The IP address is displayed as the `value` of the `TransformationIPAddress` custom attribute:
+
[source,json]
----
{
  "href": "<CloudForms_FQDN>/api/hosts/",
  "id": "<VMware_host_ID>",
  ...
  "custom_attributes": [
    {
      "href": "https://<CloudForms_FQDN>/api/hosts/<VMware_host_ID/custom_attributes/2",
      "id": "2",
      "section": "metadata",
      "name": "TransformationIPAddress",
      "value": "<VMware_IP_address>",
      "resource_type": "Host",
      "resource_id": "<VMware_host_ID>"
      ...
    }
  ...
  ]
}
----
