// Module included in the following assemblies:
//
// modules/assembly_Migrating_the_virtual_machines.adoc
// For 1.1
[id="Changing_the_maximum_number_of_concurrent_migrations_{context}"]
= Changing the maximum number of concurrent migrations

You can change the maximum number of concurrent migrations for conversion hosts or providers to control the impact of the migration process on your infrastructure.

The provider setting has priority over the conversion host setting. For example, if the maximum number of concurrent migrations is `20` for a provider and `3` for five conversion hosts, the maximum number of concurrent migrations is `20`, not `15` (`5` conversion hosts `x 3` concurrent migrations per host).

An increase in the maximum number of concurrent migrations affects all migration plans immediately. Virtual machines that are queued to migrate will migrate in greater numbers.

A decrease maximum number of concurrent migrations affects only future migration plans. Migration plans that are in progress will use the limit that was set when the plan was created.

[CAUTION]
====
ifdef::osp[]
Red Hat OpenStack Platform conversion hosts require an additional 1 GB RAM for each additional concurrent migration above `10`.
endif::osp[]

If you are using VDDK transformation, the number of concurrent migrations must not exceed `20`. Otherwise, network overload will cause the migration to fail.
====

Changing the maximum number of concurrent migrations for all conversion hosts::
. In CloudForms, click menu:Compute[Migration > Migration Settings].
. Select a new *Maximum concurrent migrations per conversion host*. The default is `10`.
+
[NOTE]
====
In the current release, the *Maximum concurrent migrations per conversion host* interface control does not work.
====

// Commenting out because of https://bugzilla.redhat.com/show_bug.cgi?id=1716283
// Setting limit via API is not working.
//
// Changing the maximum number of concurrent migrations for a single conversion host::
// . Log in to the CloudForms machine using SSH.
// . Enter the following command:
// +
// [options="nowrap" subs="+quotes,verbatim"]
// ----
// # vmdb
// # rails console
// irb(main):001:0> $evm = MiqAeMethodService::MiqAeService.new(MiqAeEngine::MiqAeWorkspaceRuntime.new)
// irb(main):002:0> $evm.vmdb(:host).find_by(:name => "_host1.example.com_").custom_set("Max Transformation Runners", _20_) <1> <2>
// ----
// <1> `host1.example.co` is the name of your conversion host.
// <2> `Max Transformation Runners` is the maximum number of concurrent migrations. The default value is `10` for a conversion host.

Changing the maximum number of concurrent migrations for a provider::
. Log in to the CloudForms machine using SSH.
. Enter the following command:
+
ifdef::rhv[]
[options="nowrap" subs="+quotes,verbatim"]
----
# vmdb
# rails console
irb(main):001:0> $evm = MiqAeMethodService::MiqAeService.new(MiqAeEngine::MiqAeWorkspaceRuntime.new)
irb(main):002:0> $evm.vmdb(:ext_management_system).find_by(:name => "RHV").custom_set("Max Transformation Runners", _30_) <1>
----
endif::rhv[]
ifdef::osp[]
[options="nowrap" subs="+quotes,verbatim"]
----
# vmdb
# rails console
irb(main):001:0> $evm = MiqAeMethodService::MiqAeService.new(MiqAeEngine::MiqAeWorkspaceRuntime.new)
irb(main):002:0> $evm.vmdb(:ext_management_system).find_by(:name => "OpenStack").custom_set("Max Transformation Runners", _30_) <1>
----
endif::osp[]
<1> `Max Transformation Runners` is the maximum number of concurrent migrations. The default value is `20` for a provider.

Getting the maximum number of concurrent migrations for a provider::
. Log in to the CloudForms machine using SSH.
. Enter the following command:
+
ifdef::rhv[]
----
# vmdb
# rails console
irb(main):001:0> $evm = MiqAeMethodService::MiqAeService.new(MiqAeEngine::MiqAeWorkspaceRuntime.new)
irb(main):002:0> $evm.vmdb(:ext_management_system).find_by(:name => "RHV").custom_get("Max Transformation Runners")
----
endif::rhv[]
ifdef::osp[]
----
# vmdb
# rails console
irb(main):001:0> $evm = MiqAeMethodService::MiqAeService.new(MiqAeEngine::MiqAeWorkspaceRuntime.new)
irb(main):002:0> $evm.vmdb(:ext_management_system).find_by(:name => "OpenStack").custom_get("Max Transformation Runners")
----
endif::osp[]
[options="nowrap" subs="+quotes,verbatim"]
