// Module included in the following assemblies:
//
// IMS_1.1/assembly_Preparing_the_1_1_target_environment.adoc
// RHV only
[id="Configuring_secure_remote_login_to_the_vmware_hypervisors"]
= Configuring secure remote login to the VMware hypervisors

You can configure secure remote login to the VMware hypervisors by using `ssh-agent` and `ssh-add`.

[CAUTION]
====
Secure remote login must be verified for *each* VMware hypervisor. If secure remote login fails, all migrations from that hypervisor will fail.
====

.Procedure

. On the Manager machine, create an `ssh-agent` session for the `vdsm` user:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# sudo -u vdsm ssh-agent
----
+
`ssh-agent` creates the `SSH_AUTH_SOCK` and `SSH_AGENT_PID` environment variables:
+
[options="nowrap" subs="+quotes,verbatim"]
----
SSH_AUTH_SOCK=/tmp/ssh-_socket_number_/agent._pid_; export SSH_AUTH_SOCK;
SSH_AGENT_PID=139150; export SSH_AGENT_PID;
echo Agent pid 139150;
----

. Copy the `SSH_AUTH_SOCK` variable from the output.

. Run `ssh-add` to authorize the `vdsm` user's private key for the `ssh-agent` session:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# sudo -u vdsm SSH_AUTH_SOCK=_SSH_AUTH_SOCK_ ssh-add
----

. Connect to a VMware hypervisor to verify the secure remote login:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# sudo -u vdsm \
    SSH_AUTH_SOCK=_SSH_AUTH_SOCK_ ssh root@_esx1.example.com_
----
