// Module included in the following assemblies:
//
// IMS_1.1/master.adoc
// IMS_1.2/master.adoc
[id="Copying_vmware_ssh_keys_to_conversion_hosts_{context}"]
= Copying the VMware SSH keys to the conversion hosts

Copy the SSH public keys of the VMware hypervisors to the conversion hosts.

You can collect the VMware keys either when you configure the VMware hypervisors for SSH transformation or by using `ssh-keyscan`.

== Copying keys collected during VMware hypervisor configuration

ifdef::rhv_1-1_ssh,rhv_1-2_ssh[]
. Copy the VMware keys to `/var/lib/vdsm/.ssh/known_hosts` on each conversion host.
. Verify the SSH connection by connecting to each VMware hypervisor as `vdsm`:
+
----
$ sudo -u vdsm ssh root@_esx1.example.com_ <1>
----
<1> Specify the host name of your VMware hypervisor.
+
If the SSH connection fails, check that the VMware hypervisor has SSH access enabled and that you copied the correct keys. Otherwise, all migrations from that hypervisor using SSH transformation will fail.
endif::[]
ifdef::osp_1-1_ssh,osp_1-2_ssh[]
. Copy the VMware keys to `/root/.ssh/known_hosts` on each conversion host.
. On each conversion host, verify the SSH connection by connecting to each VMware hypervisor as `cloud-user`:
+
[options="nowrap" subs="+quotes,verbatim"]
----
$ sudo -u cloud-user ssh root@_esx1.example.com_ <1>
----
<1> Specify the host name of the VMware hypervisor.
+
If the SSH connection fails, check that the VMware hypervisor has SSH access enabled and that you copied the correct keys. Otherwise, all migrations from that hypervisor using SSH transformation will fail.
endif::[]

== Copying keys collected with `ssh-keyscan`

You must run `ssh-keyscan` for *each VMware hypervisor*. Otherwise your conversion hosts will not have all the VMware hypervisor keys and the migration will fail.

ifdef::rhv_1-1_ssh,rhv_1-2_ssh[]
. Run `ssh-keyscan` for each VMware hypervisor and copy its public key to `known_hosts`, as in the following example:
+
[options="nowrap" subs="+quotes,verbatim"]
----
$ ssh-keyscan _esx1_IP_ > /var/lib/vdsm/.ssh/known_hosts <1>
$ ssh-keyscan _esx2_IP_ >> /var/lib/vdsm/.ssh/known_hosts
$ ssh-keyscan _esx3_IP_ >> /var/lib/vdsm/.ssh/known_hosts
----
<1> Specify the IP address, not the host name, of the VMware hypervisor.

. Change the ownership of the `known_hosts` file to `vdsm` user and `kvm` group:
+
----
$ chown 36:36 /var/lib/vdsm/.ssh/known_hosts
----

. Verify the SSH connection by connecting to each VMware hypervisor as `vdsm`:
+
----
$ sudo -u vdsm ssh root@_esx1.example.com_ <1>
----
<1> Specify the host name of the VMware hypervisor.
+
If the SSH connection fails, check that the VMware hypervisor has SSH access enabled and that you copied the correct keys. Otherwise, all migrations from that hypervisor using SSH transformation will fail.
endif::[]
ifdef::osp_1-1_ssh,osp_1-2_ssh[]
. Run `ssh-keyscan` for each VMware hypervisor and copy its public key to `known_hosts`, as in the following example:
+
[options="nowrap" subs="+quotes,verbatim"]
----
$ ssh-keyscan _esx1_IP_ > /root/.ssh/known_hosts <1>
$ ssh-keyscan _esx2_IP_ >> /root/.ssh/known_hosts
$ ssh-keyscan _esx3_IP_ >> /root/.ssh/known_hosts
----
<1> Specify the IP address, not the host name, of the VMware hypervisor.

. On each conversion host, verify the SSH connection by connecting to each VMware hypervisor as `cloud-user`:
+
[options="nowrap" subs="+quotes,verbatim"]
----
$ sudo -u cloud-user ssh root@_esx1.example.com_ <1>
----
<1> Specify the host name of the VMware hypervisor.
+
If the SSH connection fails, check that the VMware hypervisor has SSH access enabled and that you copied the correct keys. Otherwise, all migrations from that hypervisor using SSH transformation will fail.
endif::[]
