// Module included in the following assemblies:
//
// IMS_1.1/master.adoc
// IMS_1.2/master.adoc
[id="Creating_a_rhel_premigration_playbook_{context}"]
= Creating a `RHEL premigration` playbook for RHEL/Linux virtual machines

If you are migrating virtual machines running RHEL or other Linux operating systems, you must create and run a `RHEL premigration` playbook to call the Ansible `ims.rhel_premigration` role.

The `ims.rhel_premigration` role ensures that the virtual machine IP addresses are accessible after migration.

.Prerequisites

* The `rhel-<version>-server-rpms` repository must be enabled for the source virtual machines. If you have disabled it, you can re-enable it in the RHEL premigration playbook.

.Procedure

. link:https://galaxy.ansible.com/fdupont_redhat/ims_rhel_pre_migration[Install the `ims.rhel_premigration` role] with Ansible Galaxy.
. Create a `RHEL premigration` playbook according to the following example:
+
[source,yml]
----
---
- hosts: to_be_migrated
  vars:
    rhsm_config: <1>
      server_hostname: "server.example.com"
      server_username: "admin"
      server_password: "secret" <2>
      org_id: "my_organization"
    rhsm_repositories:
      - "rhel-<version>-server-rpms"
  roles:
    - role: ims.rhel_pre_migration
----
<1> Specify the configuration parameters for your environment.
<2> Passwords and other sensitive information should be encrypted with Ansible vault.

You will add this playbook when you create your migration plan.
