// Module included in the following assemblies:
//
// IMS_1.1/assembly_Preparing_the_1_1_target_environment.adoc
// IMS_1.2/assembly_Preparing_the_1_2_target_environment.adoc
[id="Creating_osp_conversion_hosts"]
= Creating the Red Hat OpenStack Platform conversion hosts

You can create the Red Hat OpenStack Platform conversion hosts with the conversion appliance. The number of conversion hosts you deploy depends on your migration size and infrastructure capabilities.

[NOTE]
====
For optimal performance, deploy conversion hosts on compute nodes with link:https://docs.openstack.org/devstack/latest/guides/devstack-with-nested-kvm.html[nested virtualization enabled]. Nested virtualization is a technology preview.
====

.Procedure

. Navigate to link:https://access.redhat.com/downloads/[Red Hat Product Downloads].
. In the *A-Z* tab, click *Red Hat OpenStack Platform*.
. Click *Download Latest*.
. Select `14.0` from the *Version* list.

ifdef::osp_1-1[]
. In the *Product Software* tab, locate the `RHOSP V2V Image for Red Hat OpenStack Director 14.0.1 (x86_64)`, click *Download Now*, and save the image.
endif::[]

ifdef::osp_1-2[]
. In the *Product Software* tab, locate the `RHOSP V2V Image for Red Hat OpenStack Director 14.0.3 (x86_64)` (or later), click *Download Now*, and save the image.
endif::[]

. Upload the image to Red Hat OpenStack Platform.
. link:https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/14/html-single/instances_and_images_guide/index#section-launch-instance[Launch the image] as a conversion host instance, with the following resources:
+
** 4 vCPUs
** 10 GB RAM, if you use the default maximum number of concurrent migrations per conversion host, which is `10`. If you increase the number of concurrent migrations, you must add 1 GB RAM for each additional concurrent migration. If you reduce the number, you can reduce the RAM but the conversion host cannot have less than 8 GB RAM.
** `/tmp` (10 GB, or 1 GB for each concurrent migration)
** `/var/tmp` (10 GB, or 1 GB for each concurrent migration)
** `/var/logs` (5 GB)

. link:https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/14/html-single/instances_and_images_guide/index#section-resize-instance[Resize the instance] to accommodate its file system.
+
The instance is created from an image, but the disk space defined in the image will not be sufficient. You can either extend the partition (and subsequently, extend the physical volume in the volume group) to the required size, or you can create a new partition and add it as a physical volume to the volume group.
+
[NOTE]
====
You must resize `lv_root` to use all available disk space because the image will not use it by default.
====
