// Module included in the following assemblies:
//
// IMS_1.1/master.adoc
// IMS_1.2/master.adoc
[id="Configuring_the_vmware_hypervisors_for_ssh_transformation_{context}"]
= Configuring the VMware hypervisors for SSH transformation

For SSH transformation, you must enable SSH access and copy a public SSH key to each VMware hypervisor. The corresponding private key will be used to configure the conversion hosts.

[IMPORTANT]
====
A single SSH key pair is recommended because this key pair is used only for virtual machine conversion and it simplifies conversion host management.

If you wish to use a dedicated SSH key pair for each conversion host, you can copy the public key of each conversion host to all the VMware hypervisors.
====

.Procedure

. Enable SSH access on each VMware hypervisor, according to the VMware documentation:

.. In a browser, navigate to link:https://docs.vmware.com/en/VMware-vSphere/index.html[VMware vSphere Documentation].
.. Enter `Enable ESXi Shell and SSH Access with the Direct Console User Interface` in the *Search* field and select your VMware version.
.. Click the `HTML` icon to view the procedure.
+
You can collect the SSH public keys of the VMware hypervisors at this stage, to copy to the conversion hosts.

. Generate an SSH key pair without a passphrase:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# ssh-keygen -N ''
----

. Copy the public SSH key to `/etc/ssh/keys-root/authorized_keys` on *each* VMware hypervisor.
+
You will use the private SSH key to configure the conversion hosts.
