// Module included in the following assemblies:
//
// IMS_1.1/master.adoc
// IMS_1.2/master.adoc
// IMS_1.3/master.adoc
[id="Creating_osp_conversion_hosts_{context}"]
= Creating a Red Hat OpenStack Platform conversion host

ifdef::osp_1-1_vddk,osp_1-2_vddk[]
You can create a Red Hat OpenStack Platform conversion host with the conversion appliance. The number of conversion hosts you deploy depends on your migration size and infrastructure capabilities.

[NOTE]
====
For optimal performance, deploy the conversion hosts on compute nodes with link:https://docs.openstack.org/devstack/latest/guides/devstack-with-nested-kvm.html[nested virtualization enabled]. Nested virtualization is a technology preview.
====
endif::[]
ifdef::osp_1-3_vddk[]
You can create a Red Hat OpenStack Platform conversion host with the Universal Conversion Host Image (UCI). The number of conversion hosts you deploy depends on your migration size and infrastructure capabilities.

.Prerequisites

* Deploy the conversion hosts on compute nodes with link:https://docs.openstack.org/devstack/latest/guides/devstack-with-nested-kvm.html[nested virtualization enabled]. Nested virtualization is a technology preview.
endif::[]

.Procedure

. Log in to Red Hat OpenStack Platform.

ifdef::osp_1-1_vddk,osp_1-2_vddk[]
. link:https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/16.0/html-single/instances_and_images_guide/index#section-upload-image[Upload the V2V image] to the OpenStack Image Service.

. link:https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/16.0/html-single/instances_and_images_guide/index#section-launch-instance[Launch the conversion host instance], specifying the following options:

* *Instance Boot Source*: V2V image
* link:https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/16.0/html-single/instances_and_images_guide/index#section-flavors[Resources]:
+
** 4 vCPUs
** 10 GB RAM, if you use the default maximum number of concurrent migrations per conversion host, which is `10`. If you increase the number of concurrent migrations, you must add 1 GB RAM for each additional concurrent migration. If you reduce the number, you can reduce the RAM but the conversion host cannot have less than 8 GB RAM.
** `/tmp` (10 GB, or 1 GB for each concurrent migration)
** `/var/tmp` (10 GB, or 1 GB for each concurrent migration)
** `/var/logs` (5 GB)
endif::[]
ifdef::osp_1-3_vddk[]
. link:https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/16.0/html-single/instances_and_images_guide/index#section-upload-image[Upload the UCI] to the OpenStack Image Service.

. link:https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/16.0/html-single/instances_and_images_guide/index#section-launch-instance[Launch the conversion host instance], specifying the following options:

* *Instance Boot Source*: UCI
* link:https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/16.0/html-single/instances_and_images_guide/index#section-flavors[Resources]:
+
** 4 vCPUs
** 10 GB RAM, if you use the default maximum number of concurrent migrations per conversion host, which is `10`. If you increase the number of concurrent migrations, you must add 1 GB RAM for each additional concurrent migration. If you reduce the number, you can reduce the RAM but the conversion host cannot have less than 8 GB RAM.
** `/tmp` (10 GB, or 1 GB for each concurrent migration)
** `/var/tmp` (10 GB, or 1 GB for each concurrent migration)
** `/var/logs` (5 GB)
endif::[]

. link:https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/16.0/html-single/instances_and_images_guide/index#section-resize-instance[Resize the conversion host instance] to accommodate its file system.
+
The conversion host instance is created from an image, but the disk space defined in the image is not sufficient. You can either extend the partition (and subsequently, extend the physical volume in the volume group) to the required size or you can create a new partition and add it as a physical volume to the volume group.
+
[NOTE]
====
You must resize `lv_root` to use all available disk space because the image will not use it by default.
====

ifdef::osp_1-1_vddk[]
. Add each RHOSP conversion host's private SSH key to CloudForms:

.. Log in to the CloudForms user interface.
.. Click *Compute* -> *Clouds* -> *Providers*.
.. Select the Red Hat OpenStack Platform provider tile, click *Configuration*, and select *Edit Selected Cloud Provider.*
.. Click the *RSA key pair* tab in the *Endpoints* section.
.. Enter the *Username* `cloud-user` and the *Private Key* of the conversion host instance. If you deploy multiple conversion hosts, they must use the same key pair.
.. Click *Save*.
endif::[]
