// Module included in the following assemblies:
//
// IMS_1.1/master.adoc
// IMS_1.2/master.adoc
[id="Creating_a_rhel_premigration_playbook_{context}"]
= Creating a `RHEL premigration` playbook for RHEL/Linux virtual machines

If you are migrating a virtual machine running RHEL or other Linux operating system, you must create and run a `RHEL premigration` playbook to call the Ansible `ims.rhel_premigration` role.

The `ims.rhel_premigration` role ensures that the virtual machine IP addresses are accessible after migration.

.Prerequisites

* The `rhel-<version>-server-rpms` repository must be enabled for the VMware virtual machines. If you have disabled it, you can re-enable it in the RHEL premigration playbook.

.Procedure

. link:https://galaxy.ansible.com/fdupont_redhat/ims_rhel_pre_migration[Install the `ims.rhel_premigration` role] with Ansible Galaxy.
. Create a `RHEL premigration` playbook according to the following example:
+
[source,yaml]
----
---
- hosts: <hosts> <1>
  vars:
    rhsm_repositories:
      - "rhel-<version>-server-rpms" <2>
  roles:
    - role: ims.rhel_pre_migration
----
<1> Specify the VMware hosts on which you are running this playbook.
<2> Specify the RHEL version.

You will add this playbook when you create your migration plan.
