// Module included in the following assemblies:
//
// assembly_Configuring_the_environment_for_ssh_transformation.adoc
[id="Configuring_the_vmware_hypervisors_for_ssh_transformation_{context}"]
= Configuring the VMware hypervisors for SSH transformation

For SSH transformation, you must configure the VMware hypervisors for passwordless access by sharing a conversion host's public SSH key with the hypervisors.

[IMPORTANT]
====
A single SSH key pair is recommended because the key pair is used only for virtual machine conversion and it simplifies conversion host management.

If you wish to use a dedicated SSH key pair for each conversion host, you can copy the public key of each conversion host to all the VMware hypervisors.
====

.Procedure

. Enable SSH access on each VMware hypervisor. For instructions, navigate to link:https://docs.vmware.com/en/VMware-vSphere/index.html[VMware vSphere Documentation] and enter `Enable ESXi Shell and SSH Access with the Direct Console User Interface]` in the *Search* field.
+
You can collect the SSH public keys of the VMware hypervisors at this stage, to copy to the conversion hosts.

. Generate an SSH key pair without a passphrase:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# ssh-keygen -N ''
----

. Copy the public SSH key to `/etc/ssh/keys-root/authorized_keys` on *each* VMware hypervisor.
+
You will use the private SSH key to configure the conversion hosts.
