// Module included in the following assemblies:
//
// IMS_1.1/master.adoc
// IMS_1.2/master.adoc
[id="Changing_the_maximum_number_of_concurrent_migrations_{context}"]
= Changing the maximum number of concurrent migrations

You can change the maximum number of concurrent migrations for conversion hosts or providers to control the impact of the migration process on your infrastructure.

The provider setting has priority over the conversion host setting. For example, if the maximum number of concurrent migrations is `20` for a provider and `3` for five conversion hosts, the maximum number of concurrent migrations is `20`, not `15` (`5` conversion hosts `x 3` concurrent migrations per host).

An increase in the maximum number of concurrent migrations affects all migration plans immediately. Virtual machines that are queued to migrate will migrate in greater numbers.

A decrease maximum number of concurrent migrations affects only future migration plans. Migration plans that are in progress will use the limit that was set when the plan was created.

[CAUTION]
====
ifdef::osp_1-1_vddk,osp_1-2_vddk[]
Red Hat OpenStack Platform conversion hosts require an additional 1 GB RAM for each additional concurrent migration above `10`.
endif::osp_1-1_vddk,osp_1-2_vddk[]

For VDDK transformation, the number of concurrent migrations must not exceed `20`. Otherwise, network overload will cause the migration to fail.
====

.Changing the maximum number of concurrent migrations for all conversion hosts

. Log in to the CloudForms user interface.
. Click menu:Compute[Migration > Migration Settings].

ifdef::rhv_1-1_vddk,osp_1-1_vddk[]
. Select a new *Maximum concurrent migrations per conversion host*. The default is `10`.

endif::rhv_1-1_vddk,osp_1-1_vddk[]
ifdef::rhv_1-2_vddk,osp_1-2_vddk[]
. In the *Migration Throttling* tab, select a value for *Maximum concurrent migrations per conversion host* or *Maximum concurrent migrations per provider* and click *Apply*.
+
The value of *Maximum concurrent migrations per conversion host* is constrained so that it cannot be greater than *Maximum concurrent migrations per provider*.

endif::rhv_1-2_vddk,osp_1-2_vddk[]

// 1.1
// Commenting out because of https://bugzilla.redhat.com/show_bug.cgi?id=1716283
// Setting limit via API is not working.
//
// Changing the maximum number of concurrent migrations for a single conversion host::
// . Log in to the CloudForms machine using SSH.
// . Enter the following command:
// +
// [options="nowrap" subs="+quotes,verbatim"]
// ----
// # vmdb
// # rails console
// irb(main):001:0> $evm = MiqAeMethodService::MiqAeService.new(MiqAeEngine::MiqAeWorkspaceRuntime.new)
// irb(main):002:0> $evm.vmdb(:host).find_by(:name => "_host1.example.com_").custom_set("Max Transformation Runners", _20_) <1> <2>
// ----
// <1> `host1.example.co` is the name of your conversion host.
// <2> `Max Transformation Runners` is the maximum number of concurrent migrations. The default value is `10` for a conversion host.

ifdef::rhv_1-2_vddk,osp_1-2_vddk[]
.Changing the maximum number of concurrent migrations for a specific conversion host

. Log in to the conversion host using SSH.
. Obtain the `conversion_host_id`:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# curl -sk -u _username:password_ 'https://_CloudForms_FQDN_/api/conversion_hosts/'
----

. Enter the following command:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# curl -sk -u _username_:_password_ 'https://_CloudForms_FQDN_/api/conversion_hosts/_conversion_host_id_' -X POST -d '{"action": "edit", "resource": {"max_concurrent_tasks": _15_}}' <1> <2> <3> <4>
----

<1> Specify the CloudForms admin username and password.
<2> Specify the FQDN of the CloudForms machine.
<3> Specify the `conversion_host_id`.
<4> Specify the maximum number of concurrent migrations. The default is `10`.

endif::rhv_1-2_vddk,osp_1-2_vddk[]
ifdef::rhv_1-1_vddk,osp_1-1_vddk[]
.Changing the maximum number of concurrent migrations for a provider

. Log in to the CloudForms machine using SSH.
endif::[]
ifdef::rhv_1-1_vddk[]
. Enter the following command:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# vmdb
# rails console
irb(main):001:0> $evm = MiqAeMethodService::MiqAeService.new(MiqAeEngine::MiqAeWorkspaceRuntime.new)
irb(main):002:0> $evm.vmdb(:ext_management_system).find_by(:name => "RHV").custom_set("Max Transformation Runners", _30_) <1>
----
<1> `Max Transformation Runners` is the maximum number of concurrent migrations. The default value is `20` for a provider.
endif::rhv_1-1_vddk[]
ifdef::osp_1-1_vddk[]
. Enter the following command:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# vmdb
# rails console
irb(main):001:0> $evm = MiqAeMethodService::MiqAeService.new(MiqAeEngine::MiqAeWorkspaceRuntime.new)
irb(main):002:0> $evm.vmdb(:ext_management_system).find_by(:name => "OpenStack").custom_set("Max Transformation Runners", _30_) <1>
----
<1> `Max Transformation Runners` is the maximum number of concurrent migrations. The default value is `20` for a provider.

endif::osp_1-1_vddk[]
ifdef::rhv_1-1_vddk,osp_1-1_vddk[]
.Obtaining the maximum number of concurrent migrations for a provider

. Log in to the CloudForms machine using SSH.
endif::[]
ifdef::rhv_1-1_vddk[]
. Enter the following command:
+
----
# vmdb
# rails console
irb(main):001:0> $evm = MiqAeMethodService::MiqAeService.new(MiqAeEngine::MiqAeWorkspaceRuntime.new)
irb(main):002:0> $evm.vmdb(:ext_management_system).find_by(:name => "RHV").custom_get("Max Transformation Runners")
----

endif::rhv_1-1_vddk[]
ifdef::osp_1-1_vddk[]
. Enter the following command:
+
----
# vmdb
# rails console
irb(main):001:0> $evm = MiqAeMethodService::MiqAeService.new(MiqAeEngine::MiqAeWorkspaceRuntime.new)
irb(main):002:0> $evm.vmdb(:ext_management_system).find_by(:name => "OpenStack").custom_get("Max Transformation Runners")
----

endif::osp_1-1_vddk[]
