// Module included in the following assemblies:
//
// IMS_1.1/master.adoc
// IMS_1.2/master.adoc
[id="Preparing_the_vmware_virtual_machines_for_{context}"]
= Preparing the VMware virtual machines

Perform the following steps on each VMware virtual machine that you are migrating:

. Install VMware Tools to capture IP addresses.
+
To download and install VMware Tools, see link:https://www.vmware.com/support/ws5/doc/new_guest_tools_ws.html[VMware Workstation 5.0: Installing VMware Tools].

. Unmount mounted ISO/CDROM disks.
. Ensure that each NIC has no more than one IPv4 and/or one IPv6 address.
. Ensure that the virtual machine names contain only upper- or lower-case letters, numbers, underscores (`_`), hyphens (`-`), or periods (`.`).
+
[NOTE]
====
International characters and spaces are not permitted.
====

ifdef::rhv_1-1_vddk,rhv_1-2_vddk,rhv_1-3_vddk[]
. Ensure that the virtual machine names do not duplicate names of virtual machines in the Red Hat Virtualization environment.
endif::rhv_1-1_vddk,rhv_1-2_vddk,rhv_1-3_vddk[]
ifdef::osp_1-1_vddk,osp_1-2_vddk,osp_1-3_vddk[]
. Ensure that the virtual machine names do not duplicate names of virtual machines in the Red Hat OpenStack Platform tenant.
endif::osp_1-1_vddk,osp_1-2_vddk,osp_1-3_vddk[]
