// Module included in the following assemblies:
//
// IMS_1.1/master.adoc
// IMS_1.2/master.adoc
[id="Environment_configuration_errors_{context}"]
= Environment configuration errors

[id="VMware_environment_errors_{context}"]
.VMware

* A VMware virtual machine cannot be migrated if it has any of the following conditions:

** Mounted ISO/CDROM disk
** Encrypted disk
** Invalid name, containing spaces or special characters
ifdef::osp_1-1_vddk,osp_1-2_vddk[]
** Powered off during migration
endif::[]

* If you are performing more than ten concurrent migrations from a single VMware hypervisor, you must increase the hypervisor's NFC service memory.

ifdef::rhv_1-1_vddk,rhv_1-2_vddk[]
[id="rhv_environment_errors_{context}"]
.Red Hat Virtualization

* Name conflict
+
VMware virtual machine has the same name as a Red Hat Virtualization virtual machine.

* MAC address conflict
+
VMware virtual machine has the same MAC address as a Red Hat Virtualization virtual machine in a MAC address pool.

* Check that the conversion host does not have an existing private SSH key in `/var/lib/vdsm/.ssh/id_rsa`. Conversion host configuration does not overwrite old SSH keys. They must be deleted manually.

* SSH transformation only:

** If you are using SSSD with single sign-on, you must reinstall `ipa-client` without OpenSSH.
** Check that you enabled SSH access on the VMware hypervisors and correctly configured your conversion hosts for SSH transformation.
endif::[]
ifdef::osp_1-1_vddk,osp_1-2_vddk[]
[id="osp_environment_errors_{context}"]
.Red Hat OpenStack Platform

* `disallowed by policy` error
+
The Red Hat OpenStack Platform `admin` user in CloudForms does not have `admin` role privileges in the target project. link:https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/14/html-single/users_and_identity_management_guide/#edit_a_project[Add the `admin` user as `member` and `admin`] to your target project.
+
[options="" subs="+quotes,verbatim"]
----
ERROR: Command exited with non-zero return code 1, output: HttpException: 403: Client Error for url: https://_FQDN_:13696/v2.0/ports, {"NeutronError": {"message": "((rule:create_port and rule:create_port:mac_address) and rule:create_port:fixed_ips) is disallowed by policy", "type": "PolicyNotAuthorized", "detail": ""}}
----
endif::[]
