// Module included in the following assemblies:
//
// assembly_Troubleshooting.adoc
[id="IP_address_errors_{context}"]
= IP address errors

* IP address of a migrated RHEL (or other Linux-based operating system) virtual machine is not accessible
+
You must create a `RHEL premigration` playbook and add it to the migration plan.

ifdef::rhv_1-1_vddk,rhv_1-2_vddk,rhv_1-3_vddk[]
* Migrated virtual machine does not have an IP address
+
You must install VMware Tools on the VMware virtual machine before migration.
endif::[]
ifdef::osp_1-1_vddk,osp_1-2_vddk,osp_1-3_vddk[]
* Migrated virtual machine does not have an IP address

** You must install VMware Tools on the VMware virtual machine before migration.

** Check the VMware virtual machine for an interface configuration file mapped to a non-existent interface (for example, `/etc/sysconfig/network-scripts/ifcfg-eth1` exists, but `eth1` interface does not). Log example:
+
[options="" subs="+quotes,verbatim"]
----
CalledProcessError: Command \'['openstack', u'--os-username=admin', u'--os-identity-api-version=3', u'--os-user-domain-name=default', u'--os-auth-url=http://osp.example.com:5000/v3', u'--os-project-name=admin', u'--os-password=\*\*******', u'--os-project-id=0123456789abcdef0123456789abcdef', \'port', \'create', \'--format', \'json', \'--network', u'01234567-89ab-cdef-0123-456789abcdef', \'--mac-address', u'00:50:56:01:23:45', \'--enable', u'port_0', \'--fixed-ip', \'*ip-address=None*'"]' returned non-zero exit status 1
_date_ _time_:ERROR: Command output:
BadRequestException: Unknown errors
----
endif::[]
