// Module included in the following assemblies:
//
// assembly_Troubleshooting.adoc
[id="Infrastructure_mapping_errors_{context}"]
= Infrastructure mapping errors

ifdef::rhv_1-1,rhv_1-2[]
* `Networks missing`, `Datastores missing`, and `Clusters missing` error messages: If you create an infrastructure mapping and then change a provider or refresh the Red Hat Virtualization hosts, the provider's object IDs change. Delete the infrastructure mapping and create a new one.
endif::[]
ifdef::osp_1-1,osp_1-2[]
* `Networks missing`, `Datastores missing`, and `Clusters missing` error messages: If you create an infrastructure mapping and then change a provider, the provider's object IDs change. Delete the infrastructure mapping and create a new one.

* Storage volume type not detected: Check that you have set at least one volume type. See link:https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/14/html-single/storage_guide/index#section-volumes-advanced-vol-type[Group Volume Settings with Volume Types] in the _Red Hat OpenStack Platform Storage Guide_ for the storage.
endif::[]
