// Module included in the following assemblies:
//
// IMS_1.1/master.adoc
// IMS_1.2/master.adoc
// IMS_1.3/master.adoc
[id="Optimizing_your_migration_{context}"]
= Optimizing performance for migration

You can minimize the impact of the migration on your environment and improve performance.

For details on performance-related configurations, see link:https://access.redhat.com/articles/4713391[Performance recommendations for migrating from VMware to Red Hat Virtualization or Red Hat OpenStack Platform with IMS].

[id='Optimizing-the-migration-environment_{context}']
== Optimizing the migration environment

You can configure the VMware and Red Hat environments to optimize your migration.

.VMware environment

You can improve performance with the following configurations:

* Extend the VMware virtual machine network to the Red Hat environment.
* Ensure that the VMware network provides high throughput.
+
VMware and Red Hat hosts often have multiple network interfaces. By default, the conversion hosts use the VMware hosts' admin interface to import virtual machines. Configure your routing for the fastest possible connection between the VMware and Red Hat environment. You can use host routes or IP table filtering to control the traffic flow.

* Ensure that the VMware network does not affect production machines, for example, by using a backup network to avoid overload.
* Divide the VMware virtual machines equally between two VMware hosts, if possible.
* Remove unnecessary data from the VMware disks.

.Red Hat environment

You can improve performance with the following configurations:

* Update your Red Hat environment to the latest z-stream release and install required patches.
* Use fast, full SSD storage.
* Ensure that the network connection between the bare metal hosts and storage is at least 10 GbE.
* Use Fibre Channel interfaces between the hosts and storage.
* Configure multipath access between the hosts and storage.

[id='Optimizing-the-conversion-hosts_{context}']
== Optimizing conversion host performance

You can improve performance with the following conversion host configurations:

ifdef::rhv_1-1_vddk,rhv_1-2_vddk[]
* Configure midrange or high-end machines, with at least 10 GB of available RAM and 4 CPUs, as conversion hosts.
+
If you increase the maximum number of concurrent migrations beyond `10` (up to `20` concurrent migrations), add 1 GB RAM for each additional migration.
+
[NOTE]
====
If you increase the maximum number of concurrent migrations, you must perform test migrations to assess the capabilities of your environment's infrastructure and to ensure that the actual migration does not fail.
====

* Enable high performance and disable power-saving in the BIOS settings of the bare metal hosts.
endif::[]
ifdef::rhv_1-3_vddk,osp_1-2_vddk,osp_1-3_vddk[]
* Deploy the conversion hosts on dedicated, midrange or high-end bare metal hosts, with at least 10 GB of available RAM and 4 CPUs.
+
If you increase the maximum number of concurrent migrations beyond `10` (up to `20` concurrent migrations), add 1 GB RAM for each additional migration.
+
[NOTE]
====
If you increase the maximum number of concurrent migrations, you must perform test migrations to assess the capabilities of your environment's infrastructure and to ensure that the actual migration does not fail.
====
endif::[]
ifdef::rhv_1-1_vddk,rhv_1-2_vddk[]
* Ensure that the conversion host is not hosting virtual machines with heavy read/write workloads during the migration.
* Ensure that virtual machines on the conversion host are idle during the migration process.
+
Their presence will not affect migration performance.
endif::[]

ifdef::osp_1-1_vddk,osp_1-2_vddk[]
* Deploy the conversion host instances with at least 10 GB of available RAM and 4 CPUs.
+
If you increase the maximum number of concurrent migrations beyond `10` (up to `20` concurrent migrations), add 1 GB RAM for each additional migration.
+
[NOTE]
====
If you increase the maximum number of concurrent migrations, you must perform test migrations to assess the capabilities of your environment's infrastructure and to ensure that the actual migration does not fail.
====
endif::[]

ifdef::osp_1-1_vddk,osp_1-2_vddk,osp_1-3_vddk[]
* Deploy the conversion hosts on dedicated bare metal hosts.
* Ensure that the virtual machines on those hosts have low storage input/output usage.
* Enable nested virtualization for the compute nodes on which the conversion hosts are deployed.
endif::[]

* Deploy multiple conversion hosts (up to 5) for load-balancing and improved performance.
+
The virtual machines in a migration plan are automatically distributed among the conversion hosts. This decreases the load on the conversion hosts and allows you to increase the concurrent migrations beyond the limits of a single conversion host.

[id='Scheduling-the-migration_{context}']
== Scheduling the migration

You can improve performance and minimize the impact on your users by scheduling the migration carefully:

ifdef::rhv_1-1_vddk,rhv_1-2_vddk,osp_1-1_vddk,osp_1-2_vddk[]
* Prepare your users for downtime.
+
Currently, IMS supports only cold migration. Virtual machines are powered off gracefully as part of the migration process.
endif::[]

* Stagger the migration schedules.
* Move critical applications during maintenance windows.
* Schedule the migration when storage input/output usage is low.
* Create multiple migration plans for finer control.

[id='Grouping-virtual-machines-for-migration_{context}']
== Grouping virtual machines for migration

You can improve performance and minimize the impact on your users by creating migration groups of virtual machines:

* Create migration groups for your virtual machines, so that you are not migrating all of them at the same time.
* Migrate virtual machines as a group, rather than individually.
+
You can deploy up to 5 conversion hosts, with each host migrating up to 20 virtual machines concurrently. *These limits should not be exceeded.*

* Consider the following questions when creating migration groups:

** How are the virtual machines grouped now?
** Which virtual machines should be migrated together?
** Which workloads or linked applications should be migrated together?
** What applications must remain available?

* Consider which parts of the workload to migrate first:

** Databases
** Applications
** Web servers
** Load balancers
