[id="IMS_1_1_overview"]
= Infrastructure Migration Solution overview

The Red Hat Infrastructure Migration Solution (IMS) 1.1 enables you to migrate virtual machines from VMware 5.5 (and later) to the following target environments:

* Red Hat Virtualization 4.2
+
Red Hat Virtualization is a virtualization platform built on Red Hat Enterprise Linux. You can manage your virtual infrastructure, including hosts, virtual machines, networks, storage, and users, from a centralized graphical user interface or with a REST API. For more information, see the link:https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.2/[Red Hat Virtualization documentation].

* Red Hat OpenStack Platform 13 or 14
+
Red Hat OpenStack Platform enables you to create a scaleable, fault-tolerant, private or public cloud based on Red Hat Enterprise Linux. For more information, see the link:https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/14/[Red Hat OpenStack Platform documentation].

The migration process is performed with CloudForms 4.7.3, a user interface for managing the infrastructure. For more information, see the link:https://access.redhat.com/documentation/en-us/red_hat_cloudforms/4.7/[Red Hat CloudForms documentation].

The migration process has the following key steps:

. Planning the migration. See xref:Planning_the_migration[].
+
* Questions to ask before migration to estimate time and resource requirements, including the following:
* Recommendations to minimize the impact on your users

. Preparing the environment for migration. See xref:Preparing_the_1_1_environment_for_migration[].
+
* Preparing the VMware environment
* Preparing the Red Hat Virtualization or Red Hat OpenStack Platform environment
* Configuring the conversion hosts.  Conversion hosts are Red Hat Virtualization hosts or Red Hat OpenStack Platform instances running `virt-v2v` and `virt-v2v-wrapper`, which perform the migration.

. Migrating the virtual machines. See xref:Migrating_the_virtual_machines[].
+
* Mapping the source and target environments
* Creating and running a migration plan
+
For a detailed description of the migration process, see the migration workflows:

** xref:Vmware_to_rhv_migration_workflow[]
** xref:Vmware_to_osp_migration_workflow[]

:context: rhv
:rhv:
include::ims_common/con_Migration_workflow.adoc[leveloffset=+1]
:rhv!:

:context: osp
:osp:
include::ims_common/con_Migration_workflow.adoc[leveloffset=+1]
:osp!:
