[id="Configuring_the_1_1_{context}_conversion_hosts"]
= Configuring the conversion hosts for VDDK or SSH transformation

Perform the following steps to configure your conversion hosts for VDDK or SSH transformation:

[cols="1,1", options="header"]
|===
^|VDDK ^|SSH
a|. Download the VDDK package. See xref:Downloading_vddk_for_{context}[].
. Configure the conversion hosts. See xref:Configuring_the_{context}_conversion_hosts_with_Ansible_playbooks[]
ifdef::rhv[]
. Authenticate the conversion hosts. xref:Authenticating_rhv_conversion_hosts_in_cloudforms[]
endif::rhv[]
. (Optional) Verify the conversion hosts in a browser. See xref:Verifying_{context}_conversion_hosts_in_browser[].

a|. Configure the conversion hosts. See xref:Configuring_the_{context}_conversion_hosts_with_Ansible_playbooks[].
. Copy the VMware SSH keys to the conversion hosts. See xref:Copying_vmware_keys_to_{context}_conversion_hosts[].
. Configure secure remote login to the VMware hypervisors. See xref:Configuring_secure_remote_login_to_the_vmware_hypervisors[].
ifdef::rhv[]
. Authenticate the conversion hosts. xref:Authenticating_rhv_conversion_hosts_in_cloudforms[]
endif::rhv[]
. (Optional) Verify the conversion hosts in a browser. See xref:Verifying_{context}_conversion_hosts_in_browser[].
|===

include::ims_common/proc_Downloading_vddk.adoc[leveloffset=+1]

You can configure the conversion hosts with Ansible playbooks.

include::modules/proc_Configuring_conversion_hosts_with_Ansible.adoc[leveloffset=+1]

If you are using VDDK, you can migrate your virtual machines. (Optionally) You can verify the conversion hosts in a browser. See xref:Verifying_{context}_conversion_hosts_in_browser[].

If you are using SSH, copy the VMware keys to the conversion hosts. See xref:Copying_vmware_keys_to_{context}_conversion_hosts[].

include::ims_common/proc_Copying_the_vmware_keys_to_the_conversion_hosts.adoc[leveloffset=+1]

ifdef::rhv[]

After you have copied all VMware keys to all conversion hosts, you can configure secure remote login to the VMware hypervisors.

include::modules/proc_Configuring_secure_remote_login_to_the_vmware_hypervisors.adoc[leveloffset=+1]

If the connection is successful, authenticate the conversion hosts in CloudForms. See xref:Authenticating_rhv_conversion_hosts_in_cloudforms[].

include::modules/proc_Authenticating_rhv_conversion_hosts.adoc[leveloffset=+1]
endif::rhv[]

You can migrate your virtual machines. (Optionally) You can verify the conversion hosts in a browser. See xref:Verifying_{context}_conversion_hosts_in_browser[].

include::ims_common/proc_Verifying_conversion_hosts_in_browser.adoc[leveloffset=+1]
