[id="Configuring_the_1_1_osp_conversion_hosts"]
= Configuring the Red Hat OpenStack Platform conversion hosts

Configuring your conversion hosts for VDDK transformation involves the following steps:

. Downloading the VMware Virtual Disk Development Kit. See xref:Downloading_vddk_for_{context}[]
. Configuring the conversion hosts with Ansible playbooks. See xref:Configuring_the_{context}_conversion_hosts_with_Ansible_playbooks[].

Configuring your conversion hosts for SSH transformation involves the following steps:

. Configuring the conversion hosts with Ansible playbooks. See xref:Configuring_the_{context}_conversion_hosts_with_Ansible_playbooks[].
. Copying the VMware SSH keys to the conversion hosts. See xref:Copying_vmware_keys_to_{context}_conversion_hosts[].

include::ims_common/proc_Downloading_vddk.adoc[leveloffset=+1]

You are ready to configure your conversion hosts. See xref:Configuring_the_{context}_conversion_hosts_with_Ansible_playbooks[].

include::modules/proc_Configuring_conversion_hosts_with_Ansible.adoc[leveloffset=+1]

If you are using VDDK, you are ready to migrate your virtual machines.

If you are using SSH, you are ready to copy the VMware keys to the conversion hosts. See xref:Copying_vmware_keys_to_{context}_conversion_hosts[].

include::ims_common/proc_Copying_the_vmware_keys_to_the_conversion_hosts.adoc[leveloffset=+1]

You are ready to migrate your virtual machines.

(Optionally) You can verify the conversion hosts in a browser. See xref:Verifying_{context}_conversion_hosts_in_browser[].

include::ims_common/proc_Verifying_conversion_hosts_in_browser.adoc[leveloffset=+1]
