= Red Hat Infrastructure Migration Solution
:imagesdir: ../images
:vernum: 1.1
:toc: left
:toclevels: 3
:numbered!:
:compat-mode:
:experimental:


:ims:
:numbered:

Red Hat Infrastructure Migration Solution (IMS) 1.1 enables you to migrate virtual machines from VMware{nbsp}5.5 (and later) to  Red Hat Virtualization or Red Hat OpenStack Platform, using Red Hat CloudForms.

Red Hat Virtualization 4.2::
Red Hat Virtualization is a virtualization platform built on Red Hat Enterprise Linux. You can manage your virtual infrastructure, including hosts, virtual machines, networks, storage, and users, from a centralized graphical user interface or with a REST API. See link:https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.2/[Red Hat Virtualization 4.2] documentation for more information.

Red Hat OpenStack Platform 13 and 14::
Red Hat OpenStack Platform enables you to create a scaleable, fault-tolerant, private or public cloud based on Red Hat Enterprise Linux. See link:https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/13[Red Hat OpenStack Platform 13] or link:https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/14[Red Hat OpenStack Platform 14] documentation for more information.

Red Hat CloudForms 4.7.3::
Red Hat CloudForms is the environment in which you perform the migration. Red Hat CloudForms is a unified set of management tools for use across virtualized, private cloud, and public cloud platforms. See link:https://access.redhat.com/documentation/en-us/red_hat_cloudforms/4.7/[Red Hat CloudForms 4.7] documentation for more information.

The following workflows describe the migration process in detail:

* xref:Vmware_to_rhv_migration_workflow[]
* xref:Vmware_to_osp_migration_workflow[]

:context: rhv
:rhv:
include::ims_common/con_Migration_workflow.adoc[leveloffset=+1]
:rhv!:

:context: osp
:osp:
include::ims_common/con_Migration_workflow.adoc[leveloffset=+1]
:osp!:


include::ims_common/assembly_Planning_the_migration.adoc[leveloffset=+1]
include::assembly_Preparing_the_1_1_environment_for_migration.adoc[leveloffset=+1]
include::ims_common/assembly_Migrating_the_virtual_machines.adoc[leveloffset=+1]
include::ims_common/assembly_Troubleshooting.adoc[leveloffset=+1]
