
[[ipa-ad-trust]]
== IPA/AD Trust Authentication

Active Directory (AD) Trust Authentication on the Appliance is supported
with External Authentication to IPA.

In this guide we will cover how to manually configure an Appliance's
external authentication to work with AD Trust Authentication using IPA.
This provides IPA Users access to the Appliance Administrative UI and the REST API
using their AD credentials.

1.  <<requirements, Requirements>>
2.  <<configure-ipa-ad-trust-server, Set up and configure an IPA server for AD Trust Authentication>>
3.  <<enable-external-auth, Enable the MiQ Appliance to use the configued IPA server>>
4.  <<configure-admin-ui, Configure the MiQ appliance to use external authentication>>
5.  <<create-group-ui, Create groups on the MiQ appliance>>
6.  <<use-ad-trust, Use AD Trust Authentication>>

[[requirements]]
== Requirements

The following is needed in order to enable AD Trust Authentication to the Appliance:

* A CentOS/RHEL 7.2 based MiQ Appliance
* Windows Server 2008 R2 or later with configured AD DC and DNS installed locally on the DC

[[configure-ipa-ad-trust-server]]
== Set up and configure an IPA server for AD Trust Authentication

* Configure an IPA Server based on FreeIPA 3.3.3 or later

Instructions for setting up and configuring cross-realm trust between an IPA domain and an AD (Active Directory) domain
can be found at http://www.freeipa.org/page/Active_Directory_trust_setup[freeipa.org Active Directory Trust Setup]

* Add necessary user attributes to the SSSD Configuration on the IPA Server

The SSSD configuration file on the IPA Server must be updated to list needed user attributes.

Add the following entry to the SSSD configuration file /etc/sssd/sssd.conf

```bash
[ifp]
user_attributes = +mail, +givenname, +sn, +displayname
```

* DNS Configuration Significance

Special care should be made when configuring DNS as improper DNS configurations can result in poor performance
and improper functionality.  For more details refer to the following documents:

* http://www.freeipa.org/page/Active_Directory_trust_setup#DNS_configuration[freeipa.org Active Directory Trust Setup/DNS configuration]
* http://www.freeipa.org/page/DNS[freeipa.org DNS]
* https://www.freeipa.org/page/Howto/DNSSEC[freeipa.org DNSSEC]

[[enable-external-auth]]
== Enable the MiQ Appliance to use the configued IPA server

Use the Appliance Console to enable external authentication to the IPA Server.

1. Log in to console as _root_
2. Run _appliance_console_
3. Summary screen should show *External Auth* as _not configured_, Press any key
4. From the Advanced Setting menu, select the menu item *Configure External Authentication (httpd)*
5. Enter the FQDN of the IPA Server, i.e. _ipaserver.test.company.com_
6. Enter the IPA Server domain, i.e. _test.company.com_
7. Enter the IPA Server realm, i.e. _TEST.COMPANY.COM_
8. Press enter to select the default IPA Server Principal, i.e. _admin_
9. Enter the Password of the IPA Server Principal
10. Review details, and Enter *y* to proceed.

[[configure-admin-ui]]
== Configure the MiQ appliance to use external authentication

Log in to the MiQ appliance as admin, then in _Settings->Configuration->Server->Authentication_

* Set mode to External (httpd)
* Check: _Get User Groups from External Authentication (httpd)_
* _Optionally_ Check: _Enable Single Signon_
* Click Save.

The above steps need to be done on each UI and WebService enabled appliance.

in _Settings->Configuration->Access Control_

* Make sure the user's groups are created on the Appliance and appropriate roles assigned to those groups.

[[create-group-ui]]
== Create groups on the MiQ appliance

The below steps need to be done on each UI and WebService enabled appliance.

Log in to the MiQ appliance as admin, then in _Settings->Configuration->Access Control->Groups->Configuration->Add a new Group_

* Check: _(Look Up LDAP Groups)_
* Enter the AD user as the _User to Look Up_ i.e. _ipauser@ipaserver.test.company.com_
* Click Retrieve.
* Choose a group from the _LDAP Groups for User_ dropdown.
* Assign the appropriate roles to the group
* Click Add.

[[use-ad-trust]]
== Use AD Trust Authentication

Once the above is done, the user simply needs to specify their AD Username and Password when:

* Logging into the Appliance Administrative UI

* Accessing the REST API

* Using the Self Service UI

* Using the Single Sign On (SSO) to access the MiQ appliance after generating a Kerberos ticket by using kinit with AD credentials.



