
[[openid-connect]]
== OpenID-Connect

External Authentication on the Appliance has been enhanced to support OpenID-Connect,
which will also be referred to as _OIDC_.

The OIDC implementation has been tested with KeyCloak 3.2.1.

In this guide we will cover how to manually configure an Appliance's
external authentication to work with OIDC. The OIDC implementation has been
tested with KeyCloak but is implemented generically using Apache's mod_auth_openidc
module and should work with other OIDC Identity Providers.

The current implementation only secures the Appliance's Web administrative UI with OIDC.

*Note:* The REST API and Self-Service UI do not currently support OIDC.

1.  <<requirements, Requirements>>
2. <<apache-configuration, Apache Configuration>>
3. <<oidc-configuration, OIDC Configuration>>
4. <<oidc-assertions, OIDC Assertions>>
5.  <<configuring-the-administrative-ui, Configuring the Administrative UI>>
6.  <<re-enabling-local-login, Re-Enabling Local Login>>
7. <<oidc-configuration-cli, Configuring OIDC using the CLI>>


[[requirements]]
== Requirements

The following is needed in order to enable OIDC Authentication to the Appliance:

* A CentOS/RHEL 7.5 based Appliance
* A OIDC Identity Provider, (e.g. KeyCloak 3.2.1 or Later)

[[apache-configuration]]
=== Apache Configuration

Copy the Apache OIDC template configuration files:

```
# TEMPLATE_DIR="/var/www/miq/system/TEMPLATE"
# cp ${TEMPLATE_DIR}/etc/httpd/conf.d/manageiq-remote-user-openidc.conf \
    /etc/httpd/conf.d/
# cp ${TEMPLATE_DIR}/etc/httpd/conf.d/manageiq-external-auth-openidc.conf \
    /etc/httpd/conf.d/
```

[[oidc-configuration]]
=== OIDC Configuration

The Apache _/etc/httpd/conf.d/manageiq-external-auth-openidc.conf_ configuration files must be updated
with installation specific values:

The defaults in the _manageiq-external-auth-oidc.conf_ file are:

[options="header"]
|======================================================================================
| Name                     | Value
| LogLevel                 | warn
| OIDCCryptoPassphrase     | sp-cookie
| OIDCOAuthRemoteUserClaim | username
|======================================================================================

Installation specific values must be specified in the _manageiq-external-auth-oidc.conf_ file for these parameters:

[options="header",cols="<1,<1,<2"]
|======================================================================================
| Name                       | Parameter                  | Value
| ServerName

and

OIDCRedirectURI              | miq_appliance              | FQDN of the appliance
| OIDCProviderMetadataURL    | oidc_provider_metadata_url | The OpenID-Connect Provider URL,
i.e. http://<keycloak_server{gt}:8080/auth/realms/miq/.well-known/openid-configuration
| OIDCClientID               | oidc_client_id             | The OpenID-Connect Client ID
| OIDCClientSecret           | oidc_client_secret         | The OpenID-Connect Client Secret
|======================================================================================


For KeyCloak, a Realm can be created for one or more Appliances with individual Clients
defined one per Appliance where the Client ID identifies the individual appliance, 
e.g. the appliance hostname.

Adding a Client in the KeyCloak ManageIQ Realm:

* Set Client ID as <miq-appliance{gt}
* Set Client protocol as *openid-connect*.

The Client definition for the appliance can then be updated with the following:
[options="header",cols="<1,<2"]
|=========================================================================================
| Setting                                         | Value
| Client Protocol                                 | openid-connect
| Access Type                                     | confidential
| Valid Redirect URIs                             | https://<miq-appliance{gt}
|                                                 | https://<miq-appliance{gt}/oidc_login/redirect_uri
| User Info Signed                                | unsigned
| Request Object Signature Algorithm              | any
|=========================================================================================

The value used for OIDCClientSecret (_oidc_client_secret_) in the _manageiq-external-auth-oidc.conf_ file is taken
from the Keycloak Client's _Credentials / Secret_ value. To generate a new client secret,
First set the _Credentials / Client Authenticator_ to _Client Id and Secret_
. Then _Regenerate Secret_ button.

Finally, restart Apache on the appliance as follows:

```
# systemctl restart httpd
```

[[oidc-assertions]]
==== OIDC Assertions

For authenticating to the appliance, the following remote user parameters are looked at by
the appliance upon a successful login and redirect from the Identity Provider.

[options="header"]
|==============================================
| HTTP Environment           | OIDC Assertion
| REMOTE_USER                | username
| REMOTE_USER_EMAIL          | email
| REMOTE_USER_FIRSTNAME      | firstname
| REMOTE_USER_LASTNAME       | lastname
| REMOTE_USER_FULLNAME       | fullname
| REMOTE_USER_GROUPS         | groups
|==============================================

For KeyCloak, the above OIDC Assertions can be created for the Appliance Client in KeyCloak as
Mappers.

The following mappers are automatically generated when the OIDC client is created:

[options="header",cols="3*^"]
|============================================================================================================
| Name         | Category       | Mapper Type
| email        | Token mapper   | User Property
| family name  | Token mapper   | User Property
| given name   | Token mapper   | User Property
| full name    | Token mapper   | User's full name
| username     | Token mapper   | User Property
|============================================================================================================

The following _Group Membership_ mapper must be manually created:

[options="header",cols="8*^"]
|============================================================================================================
| Name                 | Consent Required | Mapper Type      | Token Claim Name | Full group path | Add to ID token | Add to access token | Add to userinfo
| groups               |   OFF            | Group Membership | groups           | OFF             | ON              | OFF                 | OFF
|============================================================================================================

The following _User Session Note_ mappers must be manually created:

[options="header",cols="8*^"]
|============================================================================================================
| Name                 | Consent Required | Mapper Type       | User Session Note | Token Claim Name | Claim JSON Type | Add to ID token | Add to access token
| Client Host          |   OFF            | User Session Note | clientHost        | clientHost       | String          | ON              | ON
| Client ID            |   OFF            | User Session Note | clientId          | clientId         | String          | ON              | ON
| Client IP Address    |   OFF            | User Session Note | clientAddress     | clientAddress    | String          | ON              | ON
|============================================================================================================

[[configuring-the-administrative-ui]]
== Configuring the Administrative UI

After having configured Apache for OIDC, the next step is to update the Appliance Administrative UI
to be OIDC aware and function accordingly.

Login as admin, then in _Configure->Configuration->Authentication_

* Set mode to External (httpd)
* Check: _Provider Type: Enable Enable OpenID-Connect_ - This enables the OIDC login button on the login screen, that redirects
to the OIDC protected page for authentication, and supports the OIDC logout process.
* Optional: Check: _Enable Single Signon_ - With this option enabled, initial access to the Appliance Administrative UI will
redirect to the OIDC Identity Provider authentication screen.  Note that logouts from the Appliance will
return the user to the Appliance login screen allowing them to login as admin unless _Disable Local Login_
is checked below.
* Optional: Check: _Disable Local Login_ - Do this *only* if you need to disable _admin_ login to appliance and only
allow OIDC based authentication.  Note that if there are issues with the Identity Provider or you need
admin access to the appliance you won't be able to login until you re-enable the Local Login
as described below.
* Check: _Get User Groups from External Authentication (httpd)_
* Click Save.

The above steps need to be done on each UI enabled appliance.

In Configure->Configuration->Access Control

* Make sure the user's groups are created on the Appliance and appropriate roles assigned to those groups.

[[re-enabling-local-login]]
== Re-Enabling Local Login

If the Local Login has been disabled in the Administrative UI and there is a need to be able
to login as _admin_, the Local Login can be re-enabled using either of the following methods:

=== Administrative UI:

This option is available if the Identity Provider is available and one can login using a user
with enough administrative privileges to update it:

* Login as administrative user,
* In then in _Configure->Configuration->Authentication_ uncheck _Disable Local Login_ and save.

=== Appliance Console Interface:

* ssh to the appliance as root
* Run _appliance_console_
* Select menu entry _Update External Authentication Options_
* Select _Enable Local Login_
* then _Apply updates_

=== Appliance Console CLI:

* ssh to the appliance as root
* Run _appliance_console_cli --extauth-opts_ *local_login_disabled=false*


[[oidc-configuration-cli]]
== Configuring OIDC using the CLI

Another way to configure OpenID-Connect on the appliance is to use the appliance
console CLI instead of the above steps. The `--openidc-config` subcommand of
the  appliance console CLI allows one to configure the appliance for OpenID-Connect
Authentication by updating both Apache configurations as well as the necessary
Administrative UI settings. The `--openidc-unconfig` subcommand is also provided
for unconfiguring the appliance OpenID-Connect Authentication and reverting
the appliance to Database Authentication.

Usage of the new Appliance Console CLI subcommands are as follows:

=== Configure OpenID-Connect

To configure the appliance for OpenID-Connect Authentication:

```
# appliance_console_cli --openidc-config
                        [--openidc-client-host]
                        --openidc-url
                        --openidc-client-id
                        --openidc-client-secret
                        [--openidc-enable-sso]
```

When the `--openidc-client-host` is not specified, the configured appliance host
is used for the ServerName and OpenID-Connect Redirect URI in the
OpenID-Connect Apache configuration file. The `--openidc-client-host` is
usually the externally reachable FQDN of the appliance.

Configuring OpenID-Connect requires the following parameters:

[options="header",cols="<2,<5"]
|====================================================================
|Parameter               | Description
|--openidc-url           | This is the OpenID-Connect Provider URL
|--openidc-client-id     | The OpenID-Connect Provider Cliend ID
|--openidc-client-secret | The OpenID-Connect Provider Client Secret
|====================================================================

The `--openidc-url` varies for different providers. An example provider
URL for keycloak:

```
--openidc-url=http://keycloak-server:8080/auth/realms/miq-realm/.well-known/openid-configuration
```
With *miq-realm* being the Keycloak Realm this OpenID-Connect
appliance client is being configured for.

The `--openidc-client-id` is the Client ID specified for
the appliance in the OpenID-Connect provider, usually
just `<miq-appliance-fqdn{gt}`

By default, SSO is not enabled, so from the Appliance login page, the user clicks
on Log In to Corporate System to get redirected to the OpenID-Connect
login page. With this option enabled, the Appliance redirects the user
to the OpenID-Connect login page for logging in.

=== Unconfigure OpenID-Connect

To unconfigure the appliance from OpenID-Connect Authentication and revert to
Database authentication:

```
# appliance_console_cli --openidc-unconfig
```

This will remove the Apache external authentication OpenID-Connect configuration
files and revert the appliance's authentication settings to Database mode.
