[[installing-cloudforms]]
== Installing CloudForms

CloudForms Management Engine is able to be installed and ready to configure in a few quick steps. After downloading CloudForms Management Engine as a virtual machine image template from the Red Hat Customer Portal, the installation process takes you through the steps of uploading the appliance to a supported virtualization or cloud provider.

[IMPORTANT]
=======
After installing the CloudForms Management Engine Appliance, you must configure the database for Red Hat CloudForms. See xref:configuring_a_database[].
=======

=== Obtaining the CloudForms Management Engine Appliance

. Go to link:https://access.redhat.com[access.redhat.com] and log in to the Red Hat Customer Portal using your customer account details.
. Click *Downloads* in the menu bar.
. Click *A-Z* to sort the product downloads alphabetically.
. Click *Red Hat CloudForms* and then *Download Latest* to access the product download page.
. From the list of installers and images, select the *CFME VMware Virtual Appliance* download link.

=== Uploading the Appliance on VMware vSphere

Uploading the CloudForms Management Engine Appliance file onto VMware vSphere systems has the following requirements:

* 44 GB of space on the chosen vSphere datastore.
* Administrator access to the vSphere Client.
* Depending on your infrastructure, allow time for the upload.

[NOTE]
=======
These are the procedural steps as of the time of writing. For more information, consult the VMware documentation.
=======

Use the following procedure to upload the CloudForms Management Engine Appliance OVF template from your local file system using the vSphere Client.

. In the vSphere Client, select menu:File[Deploy OVF Template]. The Deploy OVF Template wizard appears.
. Specify the source location and click *Next*.
* Select *Deploy from File* to browse your file system for the OVF template, for example `cfme-vsphere-5.4-43.x86_64.vsphere.ova`.
* Select *Deploy from URL* to specify a URL to an OVF template located on the internet.
. View the *OVF Template Details* page and click *Next*.
. Select the deployment configuration from the drop-down menu and click *Next*. The option selected typically controls the memory settings, number of CPUs and reservations, and application-level configuration parameters. 
. Select the host or cluster on which you want to deploy the OVF template and click *Next*.
. Select the host on which you want to run the run the CloudForms Management Engine appliance, and click *Next*.
. Navigate to, and select the resource pool where you want to run the CloudForms Management Engine appliance and click *Next*.
. Select a datastore to store the deployed CloudForms Management Engine Appliance, and click Next. Ensure to select a datastore large enough to accommodate the virtual machine and all of its virtual disk files.
. Select the disk format to store the virtual machine virtual disks, and click *Next*.
* Select *Thin Provisioned* if the storage is allocated on demand as data is written to the virtual disks.
* Select *Thick Provisioned* if all storage is immediately allocated.
. For each network specified in the OVF template, select a network by right-clicking the *Destination Network* column in your infrastructure to set up the network mapping and click *Next*.
. The *IP Allocation* page does not require any configuration changes. Leave the default settings in the *IP Allocation* page and click *Next*.
. Set the user-configurable properties and click *Next*. The properties to enter depend on the selected IP allocation scheme. For example, you are prompted for IP related information for the deployed virtual machines only in the case of a fixed IP allocation scheme.
. Review your settings and click *Finish*.

The progress of the import task appears in the vSphere Client Status panel.