[[installing-cloudforms]]
== Installing {product-title}

Installing {product-title} consists of the following steps:

. Uploading the VHD image into your SCVMM Library.
. Creating a blank VHD to be used for the DB disk.
. Running a Powershell script to create a deployable template for the {product-title_short} appliance.
. Configuring the {product-title_short} appliance.

After you have completed all the procedures in this guide, you will have a working environment on which additional customizations and configurations can be performed.

ifdef::miq[]
[[obtaining-the-appliance]]
=== Obtaining the appliance

. In a browser, navigate to link:manageiq.org/download[].
. Select *SCVMM* from the *--Choose your platform--* list.
. Select *Stable* from the *--Choose a release--* list.
. Follow the instructions to download the appliance.
endif::miq[]

ifdef::cfme[]
[[obtaining-the-appliance]]
=== Obtaining the Appliance

To obtain a copy of the appliance from the Customer Portal:

. Log in to the Red Hat Customer Portal at link:https://access.redhat.com[access.redhat.com] using your customer account details.
. Click *Downloads* in the menu bar.
. Click *A-Z* to sort the product downloads alphabetically.
. Click *Red Hat CloudForms* to access the product download page.
//EDIT APPLIANCE IMAGE NAME - look at Portal
. From the list of installers and images, click the *Download Now* link for *CFME Red Hat Virtual Appliance (qcow)*.
endif::cfme[]


[[uploading-the-appliance-on-SCVMM]]
=== Uploading the Appliance to the SCVMM Library
(Preparing ?)

EDIT!
Log in to your SCVMM environment (?) to upload your {product-title} appliance.

. Log in to SCVMM.
.
.

You have successfully uploaded the {product-title} appliance.

////
??
The appliance image is placed in a queue to be uploaded. It may take some time before the Status of the image changes from Queued to Active.
////

. Create a blank VHD to be used for the DB disk and add it to your SCVMM Library.
+
For example, on a node with Hyper-V installed you can create a 20GB blank VHD with the following Powershell command:
+
----
$ New-VHD -Path 'C:\path\to\my\newvdisk.vhdx' -SizeBytes 20gb -Dynamic
----
+

. Run the following Powershell script to create a deployable template for the {product-title_short} appliance:
+
----
$networkName = "yourNetwork"
$templateName = "myNewCFMETemplate"
$templateOwner = "ownerUsername"
$memorySizeMb = 12288
$cpuCount = 4
$srcPath = "C:\path\to\vhd\in\Library"
$dbDiskSrcPath = "C:\path\to\db\vhd\in\Library"
$templateOsType = "Red Hat Enterprise Linux 7 (64 bit)"
$scvmmFqdn = "fqdn.of.scvmm.com"

$JobGroupId01 = [Guid]::NewGuid().ToString()
$LogicalNet = Get-SCLogicalNetwork -Name $networkName
New-SCVirtualNetworkAdapter -JobGroup $JobGroupID01 -MACAddressType Dynamic
    -LogicalNetwork $LogicalNet -Synthetic
New-SCVirtualSCSIAdapter -JobGroup $JobGroupID01 -AdapterID 6 -Shared $False
New-SCHardwareProfile -Name $templateName -Owner $templateOwner
    -Description 'Temp profile used to create a VM Template' -MemoryMB
$memorySize
    -CPUCount $cpuCount -JobGroup $JobGroupID01
$JobGroupId02 = [Guid]::NewGuid().ToString()
$VHD = Get-SCVirtualHardDisk | where {{ $_.Location -eq $srcPath }} | where {{
$_.HostName -eq $scvmmFqdn }}
New-SCVirtualDiskDrive -IDE -Bus 0 -LUN 0 -JobGroup $JobGroupID02
-VirtualHardDisk $VHD
$DBVHD = Get-SCVirtualHardDisk | where {{ $_.Location -eq $dbDiskSrcPath }}
New-SCVirtualDiskDrive -IDE -Bus 1 -LUN 0 -JobGroup $JobGroupID02
-VirtualHardDisk $DBVHD
$HWProfile = Get-SCHardwareProfile | where {{ $_.Name -eq $templateName }}
$OS = Get-SCOperatingSystem | where {{ $_.Name -eq $templateOsType }}
New-SCVMTemplate -Name $templateName -Owner $templateOwner -HardwareProfile
$HWProfile `
    -JobGroup $JobGroupID02 -RunAsynchronously -Generation 1 -NoCustomization
Remove-HardwareProfile -HardwareProfile $templateName
----
+
.
