pressgang_website_callback([
	{"topicId":44384,"target":"chap-Changing_the_UI_Locale","title":"Changing the UI Locale","newSince":""},
	{"topicId":27041,"target":"chap-Enabling_Public_AMIs_from_Amazon_EC2","title":"Enabling Public AMIs from Amazon EC2","newSince":""},
	{"topicId":44489,"target":"RHBA-20151100_-_Red_Hat_CloudForms_5.4.0_Bug_Fixes_and_Enhancement_Update","title":"RHBA-2015:1100 - Red Hat CloudForms 5.4.0 Bug Fixes and Enhancement Update","newSince":""},
	{"topicId":44490,"target":"chap-Technical_Notes","title":"Technical Notes","newSince":""},
	{"topicId":43059,"target":"chap-Deprecated_Technologies","title":"Deprecated Technologies","newSince":""},
	{"topicId":24179,"target":"Updating_the_Appliance_Operating_System","title":"Updating the Appliance Operating System","newSince":""},
	{"topicId":41460,"target":"chap-About_Red_Hat_CloudForms_Management_Engine","title":"Getting Help and Giving Feedback","newSince":""},
	{"topicId":41109,"target":"chap-About_Red_Hat_CloudForms_Management_Engine","title":"About Red Hat CloudForms Management Engine","newSince":""},
	{"topicId":42966,"target":"appe-Revision_History","title":"Revision History","newSince":""},
	{"topicId":42967,"target":"chap-Enhancements","title":"Enhancements","newSince":""},
	{"topicId":43065,"target":"Abstract","title":"Abstract","newSince":""},
	{"topicId":42938,"target":"Author_Group","title":"Author Group","newSince":""},
	{"topicId":43163,"target":"chap-Support_Matrix","title":"Support Matrix","newSince":""},
	{"topicId":44379,"target":"chap-Release_Information","title":"Release Information","newSince":""},
	{"topicId":21947,"target":"Updating_Appliances","title":"Updating Appliances","newSince":""},
	{"topicId":41115,"target":"chap-Migrating_to_Red_Hat_CloudForms_3.2","title":"Migrating to Red Hat CloudForms 3.2","newSince":""},
	{"topicId":21948,"target":"Registering_Appliances","title":"Registering Appliances","newSince":""},
	{"topicId":44381,"target":"Release_Notes","title":"Release Notes","newSince":""},
	{"topicId":44382,"target":"Known_Issue","title":"Known Issue","newSince":""},
	{"topicId":22015,"target":"chap-Registering_and_Updating_CloudForms_Management_Engine","title":"Registering and Updating CloudForms Management Engine","newSince":""}], 23046, "Red Hat CloudForms", "Release Notes", "3.2");