// Module included in the following assemblies:
// doc-Migration_Analytics_Guide/cfme/master.adoc
[id='Collecting-inventory-data_{context}']
= Collecting inventory data in CloudForms

You can collect inventory data for analysis with Migration Analytics in CloudForms.

.Prerequisites

* You must enable the Migration Analytics menu.
* You must perform a SmartScan analysis scan on the VMware virtual machines.

.Procedure

. Log in to the CloudForms user interface.
. Navigate to menu:Compute[Infrastructure > Providers] and select the VMware provider.
. Click menu:Configuration[Refresh Relationships and Power States] and click *OK*.
. Navigate to menu:Migration[Migration Analytics] and click *Get started*.
+
A summary page listing all providers is displayed.

. Click *vSphere* to view the provider summary.
. Click *Collect Inventory Data*.
. Select *vSphere* from the provider list.
. Select *Detailed Data* and click *Continue*.
. Click *Copy to Clipboard* and paste the command on the command line to copy the inventory data file to your local machine.
