// Module included in the following assemblies:
// doc-Migration_Analytics_Guide/cfme/master.adoc
[id='Importing-a-customized-smartstate-analysis-profile_{context}']
= Creating a customized SmartState analysis profile

You can create a customized SmartState analysis profile so that custom workloads and instances are detected, added to the inventory data file, and included in the Migration Analytics report.

.Prerequisites

* You must link:https://access.redhat.com/documentation/en-us/red_hat_cloudforms/5.0/html-single/general_configuration/index#editing-an-analysis-profile[delete the `default` VM analysis profile] in the CloudForms user interface.
+
Importing a new `default` profile does not overwrite the existing profile. The import process concatenates the `default` profiles.

.Procedure

. Log in to the CloudForms machine as root user.
. Create a `/root/custom_profile.yaml` file, using the `custom_profile.yaml` file as a template.
. Edit the `custom_profile.yaml` file for your workloads by updating the `target` parameters.
+
For example, you can modify the paths to startup scripts and configuration files for custom Oracle WebLogic instances:
+
[source,yaml]
----
---
name: default <1>
definition:
- name: default_file
  guid:
  item_type: file
  definition:
    stats:
    - target: /u01/app/oracle/domains/base/bin/startNodeManager.sh
    - target: /u01/app/oracle/domains/base/startWebLogic.sh
    - target: /home/oracle/oraInventory
    - target: /u01/app/oracle/domains/base/config/config.xml
----
<1> The imported analysis profile is called `default`. If you change the profile name, you must link:https://access.redhat.com/documentation/en-us/red_hat_cloudforms/5.0/html-single/assigning_a_custom_analysis_profile_to_a_virtual_machine/index#create-vm-control-policy[create a control policy] and add it to the vSphere provider.

. Save the `custom_profile.yaml` file.

. Go to the `vmdb` directory:
+
----
# vmdb
----

. Import the `custom_profile.yaml` file:
+
----
# bundle exec rake evm:import:scan_profiles -- --source /root/custom_profile.yaml
----

. In the CloudForms user interface, verify that the `default` profile appears under *Analysis Profiles*.
