// Module included in the following assemblies:
// doc-Migration_Analytics_Guide/cfme/master.adoc
[id='Creating-migration-analytics-reports_{context}']
= Creating a Migration Analytics report

You can create a report with the Migration Analytics service at link:https://cloud.redhat.com/beta[https://cloud.redhat.com/beta]. The Migration Analytics service uploads your inventory data file, analyzes it, and generates a report.

.Prerequisites

* Inventory data file generated by CloudForms
* Access to link:https://cloud.redhat.com/beta[https://cloud.redhat.com/beta]

.Procedure

. Launch a browser and navigate to link:https://cloud.redhat.com/beta[https://cloud.redhat.com/beta].
. In the *Migration Services* tile, click *Open*.
+
The *Reports* window is displayed.

. Click *Create* and fill in the following fields:

* Mandatory fields:
** *Inventory data file*: Inventory data file generated by CloudForms
** *Report name*: Name of your report, up to 50 characters
** *Year-over-year growth rate for new hypervisors*: Number of new hypervisors to be added each year

* Optional fields:
** *Report description*: Brief description of your report
** *Percentage of new hypervisors migrated each year*: Percentage of new hypervisors that you intend to migrate each year.

. Click *Create report*.
+
The inventory data file is uploaded and the generated report appears in the *Reports* list.

. Click the report name to view the report.
+
In the *Workload migration inventory* section of the report, you can filter the list of virtual machines or click *Export as CSV* to save the report to your local machine.
