// Module included in the following assemblies:
// doc-Migration_Analytics_Guide/cfme/MA_1.0/master.adoc
[id='Installing-cloudforms_{context}']
= Installing Red Hat CloudForms on VMware vSphere

You can install the Red Hat CloudForms appliance on VMware vSphere.

.Prerequisites

* VMware vSphere 6.0 or later
* Resources for the CloudForms appliance:

** 6 vCPUs
** 32 GB RAM
** 40 GB hard disk for the CloudForms appliance
** 20 GB hard disk for the CloudForms database

.Procedure

. In a browser, navigate to the link:https://access.redhat.com/downloads[Red Hat Customer Portal Software & Download Center] and log in using your customer account details.
+
If you do not have a customer account, navigate to link:https://access.redhat.com/products/red-hat-cloudforms-migrations/evaluation[Red Hat CloudForms for Red Hat Migrations], create a Red Hat account, and download a trial version of CloudForms.

. Click *A-Z* to sort the product downloads alphabetically.
. Click *Red Hat CloudForms* to access the product download page.
. In *Product Software*, click *Download Now* for *CFME VMware Virtual Appliance (Paravirtualization)* and save the file to your local system.

. Deploy the CloudForms appliance according to the link:https://docs.vmware.com/en/VMware-vSphere/index.html[VMware vSphere Documentation] for your vSphere version.
+
Expand *ESXi and vCenter Server* -> *vSphere Virtual Machine Administration* -> *Deploying OVF and OVA Templates* -> *Deploy an OVF or OVA Template* and follow the procedure.

. Add the 20 GB hard disk for the CloudForms database according to the VMware documentation.
+
Expand *ESXi and vCenter Server* -> *vSphere Virtual Machine Administration* -> *Configuring Virtual Machine Hardware* -> *Virtual Disk Configuration* -> *Add a New Hard Disk to a Virtual Machine* and follow the procedure.

. Verify that the CloudForms appliance and database disk are correctly configured in vSphere.
