// Module included in the following assemblies:
// doc-Migration_Analytics_Guide/cfme/master.adoc
[id='Migration-analytics-report']
= Migration Analytics report

The Migration Analytics report is generated by the Migration Analytics service at link:https://cloud.redhat.com/beta[https://cloud.redhat.com/beta] and is displayed in your browser. It comprises the following sections.

.Initial savings estimation

This section describes the estimated savings realized by migrating from VMware to Red Hat Virtualization over a three-year period, based on the data retrieved from the infrastructure. The savings estimates are broken down into VMware maintenance costs, Red Hat Virtualization costs, and Red Hat training and services.

.Workload migration summary

This section describes the complexity of the migration and provides detailed workload data. A pie chart displays the complexity of migrations:

* *Easy*: Virtual machine with no unusual configuration
* *Medium*: For example, virtual machine with more than four vNICs or a shared disk
* *Hard*: For example, a virtual machine with Raw Device Mapping
* *Unknown*: Unidentified operating system, for example, FreeBSD 12

.Workload migration inventory

This section displays a list of the virtual machines to be migrated, with detailed information about the workload, operating system, estimated migration effort, and recommended migration targets.

In this section, you can filter the list of virtual machines by fields or click *Export as CSV* to save the report to your local machine.
