// Module included in the following assemblies:
// doc-Migration_Analytics_Guide/cfme/master.adoc
[id='Migration-analytics-report']
= Migration Analytics report

The Migration Analytics report is generated by the Migration Analytics service at link:https://cloud.redhat.com/beta[https://cloud.redhat.com/beta] and is displayed in your browser. You can filter the results or download the report.

The report contains the following sections.

.Initial savings estimation

This section describes the estimated savings realized by migrating from VMware to Red Hat Virtualization over a three-year period, based on the data retrieved from the infrastructure. The savings estimates are broken down into VMware maintenance costs, Red Hat Virtualization costs, and Red Hat training and services.

.Workload migration summary

This section describes the complexity of the migration and provides detailed workload data. A pie chart displays the complexity of the migration:

* *Easy*: Virtual machine has no unusual configuration.
* *Medium*: Virtual machine has a moderately complex configuration, for example, more than four vNICs or a shared disk.
* *Hard*: Virtual machine has a challenging configuration, for example, Raw Device Mapping.
* *Unknown*: Virtual machine's operating system cannot be detected. Its migration complexity is unknown.
* *Unsupported*: Virtual machine's operating system is not supported for migration, for example, FreeBSD 12.

.Workload migration inventory

This section displays a list of the virtual machines to be migrated, with detailed information about each virtual machine's workload, operating system, estimated migration effort, and recommended migration targets.

In this section, you can filter the list of virtual machines by fields or click *Export as CSV* to save the report to your local machine.
