// Module included in the following assemblies:
// doc-Migration_Analytics_Guide/cfme/master.adoc
[id='Migration-analytics-report']
= Migration Analytics report

The Migration Analytics report is generated by the Migration Analytics service at link:https://cloud.redhat.com/beta[https://cloud.redhat.com/beta] and is displayed in your browser.

The report contains the following sections.

.Initial savings estimation

This section describes the estimated savings realized by migrating from VMware to Red Hat Virtualization over a three-year period, based on the data retrieved from the infrastructure. The savings estimates are broken down into VMware maintenance costs, Red Hat Virtualization costs, and Red Hat training and services.

.Workload migration summary

This section describes the complexity of the migration and provides detailed workload data.

A pie chart summarizes the complexity of the migration:

* *Easy*: Virtual machine has a supported operating system and configuration. It requires no changes for migration.
* *Medium*: Virtual machine configuration, for example, Windows operating system, high availability configuration, cluster membership, or shared disks, may require manual changes after migration.
* *Hard*: Virtual machine configuration, for example, raw device mapping, requires manual changes before and after migration.
* *Unknown*: Virtual machine configuration is incomplete. Its migration complexity cannot be determined.
* *Unsupported*: Virtual machine configuration, for example, an unsupported operating system, is not supported on the target platform.

.Workload migration inventory

This section displays a list of the virtual machines to be migrated, with detailed information about each virtual machine's workload, operating system, estimated migration effort, and recommended migration targets.

In this section, you can filter the list of virtual machines by fields or click *Export as CSV* to save the report.
