// Module included in the following assemblies:
// assembly_.adoc
= Supported Browsers

Browser support is divided into tiers:

* Tier 1: Browser and operating system combinations that are fully tested and fully supported. Red Hat Engineering is committed to fixing issues with browsers on this tier.

* Tier 2: Browser and operating system combinations that are partially tested, and are likely to work. Limited support is provided for this tier. Red Hat Engineering will attempt to fix issues with browsers on this tier.

* Tier 3: Browser and operating system combinations that are not tested, but may work. Minimal support is provided for this tier. Red Hat Engineering will attempt to fix only minor issues with browsers on this tier.

.Supported Browsers
[options="header"]
|====
|Support Tier |Browser
|Tier 1 a|* Google Chrome - Chrome for business
* Mozilla Firefox Extended Support Release
|Tier 2 |Microsoft Internet Explorer Edge - Version 44 and later
|Tier 3 |Safari on MacOS (Mojave) - Version 12.1.x
|====
