// Module included in the following assemblies:
// doc-Migration_Analytics_Guide/cfme/MA_1.0/master.adoc
[id='ssa-support_{context}']
= Support for SmartState analysis

Red Hat CloudForms uses SmartState analysis to analyze virtual machines and instances on the providers. SmartState analysis collects information about base operating systems, virtual hardware, installed applications, and other details. The collected data enables workload detection and increases the accuracy of the Migration Analytics recommendations.

This section describes the operating systems, file systems, and infrastructure providers supported for SmartState analysis.

.Operating systems

The following virtual machine operating systems are supported for SmartState analysis:

* Windows 2016
* Windows 2010
* Windows 10
* Windows 8.1
* Windows 7 SP1
* Red Hat Enterprise Linux 6, 7, and 8
* Fedora (all versions)
* Debian and Debian-derived (all versions)
* Ubuntu and Ubuntu-derived (all versions)
* SUSE and openSUSE-derived (all versions)

.File systems

The following file systems are supported for SmartState analysis:

* Ext3
* Ext4
* FAT32
* ISO9660 (CDFS)
* NTFS
* XFS

.Infrastructure providers

The following infrastructure providers  are supported for SmartState analysis:

* VMware vSphere 6.0 and later
