// Module included in the following assemblies:
// doc-Migration_Analytics_Guide/cfme/MA_1.0/master.adoc
[id='Supported-browsers_{context}']
= Supported Browsers

The following browsers are supported for Migration Analytics.

.Supported Browsers
[options="header"]
|====
|Support Tier |Browser
a|Tier 1:

Browser and operating system combinations that are fully tested and fully supported. Red Hat Engineering is committed to fixing issues with browsers on this tier.
a|Google Chrome Enterprise

Mozilla Firefox Extended Support Release

a|Tier 2:

Browser and operating system combinations that are partially tested, and are likely to work. Limited support is provided for this tier. Red Hat Engineering will attempt to fix issues with browsers on this tier.
|Microsoft Internet Explorer Edge - Version 44 and later

a|Tier 3:

Browser and operating system combinations that are not tested, but may work. Minimal support is provided for this tier. Red Hat Engineering will attempt to fix only minor issues with browsers on this tier.
|Safari on MacOS (Mojave) - Version 12.1.x
|====
