= Migration Analytics Guide
:imagesdir: images
:vernum: 1.0
:toc: left
:toclevels: 3
:compat-mode:
:experimental:

:context: migration_analytics
:migration_analytics:
:numbered:
:sectnums:
:partnums:

toc::[]

Migration Analytics examines your VMware virtual machines and collects data about their operating systems and workloads using link:https://access.redhat.com/documentation/en-us/red_hat_cloudforms[Red Hat CloudForms]. In the CloudForms user interface, you can run an analysis scan on the VMware virtual machines and download the collected data as an inventory data file.

You create a report with the Migration Analytics service on link:https://cloud.redhat.com[cloud.redhat.com], which uploads and analyzes the data. The report provides an estimate of the initial savings in migrating to Red Hat, a detailed analysis of the VMware virtual machines, and recommendations to help you plan your migration.

Migration Analytics supports VMware version 6.0 or later.

[NOTE]
====
Migration Analytics is available as a technology preview for Red Hat CloudForms 5.0. For more information on the support scope for features marked as technology previews, see link:https://access.redhat.com/support/offerings/techpreview/[Technology Preview Features Support Scope].
====

include::modules/Migration-analytics-workflow.adoc[leveloffset=+1]

=== Migration Analytics requirements

include::modules/Supported-browsers.adoc[leveloffset=+3]
include::modules/Supported-platforms.adoc[leveloffset=+3]
include::modules/SSA-support.adoc[leveloffset=+3]

== Installing and configuring Red Hat CloudForms for Migration Analytics

You can install the Red Hat CloudForms appliance on VMware vSphere and configure the CloudForms internal database.

You then download and install the VMware Virtual Disk Development Kit (VDDK) SDK. VDDK is required for SmartState analysis of the VMware virtual machines.

After installation is complete, you can add the VMware vCenter provider to CloudForms, assign a control policy to the provider, and disable `scan_via_host` so that you do not have to authenticate each VMware host manually in CloudForms.

.Optional: Automated VDDK installation and CloudForms configuration

You can install VDDK, assign a control policy to the VMware vCenter provider, and configure CloudForms with a link:https://access.redhat.com/articles/5001061[configuration script].

You must perform the following steps before running the script:

* xref:Installing-cloudforms_{context}[]
* xref:Configuring-cf-internal-database_{context}[]
* xref:Downloading_vddk_{context}[]
* xref:Adding-a-provider-to-cloudforms_{context}[]

After running the script, you can skip the following steps:

* xref:Installing-vddk_{context}[]
* xref:Assigning_control_policy_to_provider_{context}[]
* xref:Disabling-scan_via_host_{context}[]
* xref:Creating-a-default-smartstate-analysis-profile_{context}[]

You are ready to xref:Scanning-vms-for-migration-analytics_{context}[scan your VMware virtual machines].

include::modules/Installing-cloudforms.adoc[leveloffset=+2]
include::modules/Configuring-cf-internal-db.adoc[leveloffset=+2]
include::modules/Downloading-vddk.adoc[leveloffset=+2]
include::modules/Installing-vddk.adoc[leveloffset=+2]

=== Configuring Red Hat CloudForms for Migration Analytics

You can add VMware vCenter to Red Hat CloudForms, assign a control policy, and disable `scan_via_host`.

include::modules/Logging-in-to-cf.adoc[leveloffset=+2]
include::modules/Adding-provider-to-cloudforms.adoc[leveloffset=+2]
include::modules/Assigning_control_policy_to_provider.adoc[leveloffset=+2]
include::modules/Configuring-cloudforms.adoc[leveloffset=+2]

[id='Managing-analysis-profiles_{context}']
== Managing SmartState analysis profiles

You can create a `default` SmartState analysis profile to scan your VMware virtual machines.

You can create a custom analysis profile by modifying the xref:Custom-profile-yaml-example[`custom_profile.yaml` template].

You can export existing analysis profiles for backup, troubleshooting, or updates.

include::modules/Creating-a-default-analysis-profile.adoc[leveloffset=+2]
include::modules/Creating-a-custom-analysis-profile.adoc[leveloffset=+2]

[NOTE]
====
See xref:Custom-profile-yaml-example[] for the template.
====

include::modules/Exporting-analysis-profiles.adoc[leveloffset=+2]

== Collecting data for Migration Analytics

You can scan your VMware virtual machines and download the results as an inventory data file to your local machine.

Optionally, you can combine multiple inventory data files into a single file in order to generate a single Migration Analytics report.

include::modules/Scanning-vms-for-migration-analytics.adoc[leveloffset=+2]
include::modules/Collecting-inventory-data.adoc[leveloffset=+2]
include::modules/Combining-inventory-data-files.adoc[leveloffset=+2]

[id='Creating-and-filtering-a-migration-analytics-report']
== Creating and filtering a Migration Analytics report

You can create a Migration Analytics report, filter the results, and export the data.

include::modules/Creating-migration-analytics-report.adoc[leveloffset=+2]
include::modules/Migration-analytics-report.adoc[leveloffset=+2]
include::modules/Filtering-migration-analytics-report.adoc[leveloffset=+2]
include::modules/Exporting-migration-analytics-report.adoc[leveloffset=+2]

include::modules/Troubleshooting.adoc[leveloffset=+1]

[appendix]

include::modules/Custom_profile_yaml_example.adoc[leveloffset=+1]

:!migration_analytics:
