= Migration Analytics Guide
:imagesdir: images
:vernum: 1.0
:toc: left
:toclevels: 3
:compat-mode:
:experimental:

:context: migration_analytics
:migration_analytics:
:numbered:
:sectnums:
:partnums:

toc::[]

Migration Analytics examines your VMware virtual machines and collects data about their operating systems and workloads using link:https://access.redhat.com/documentation/en-us/red_hat_cloudforms[Red Hat CloudForms]. In the CloudForms user interface, you can run an analysis scan on the VMware virtual machines and download the collected data as an inventory data file.

You create a report with the link:https://cloud.redhat.com/beta[Migration Analytics service], which uploads and analyzes the data. The report provides an estimate of the initial savings in migrating to Red Hat, a detailed analysis of the VMware virtual machines, and recommendations to help you plan your migration.

Migration Analytics supports VMware version 6.0 or later.

[NOTE]
====
Migration Analytics is available as a technology preview for Red Hat CloudForms 5.0. For more information on the support scope for features marked as technology previews, see link:https://access.redhat.com/support/offerings/techpreview/[Technology Preview Features Support Scope].
====

include::modules/Migration-analytics-workflow.adoc[leveloffset=+1]

=== Migration Analytics requirements

include::modules/Supported-browsers.adoc[leveloffset=+3]
include::modules/Supported-platforms.adoc[leveloffset=+3]
include::modules/SSA-support.adoc[leveloffset=+3]

== Installing Red Hat CloudForms and the VMware Virtual Disk Development Kit

You can install the Red Hat CloudForms appliance on VMware vSphere. You then download and install the VMware Virtual Disk Development Kit (VDDK) SDK. VDDK is required for SmartState analysis of the VMware virtual machines.

include::modules/Installing-cloudforms.adoc[leveloffset=+2]
include::modules/Installing-vddk.adoc[leveloffset=+2]

== Configuring Red Hat CloudForms for Migration Analytics

In the CloudForms user interface, you can add VMware vCenter as an infrastructure provider and assign a control policy to apply a SmartState analysis profile. You then configure CloudForms for Migration Analytics.

include::modules/Adding-provider-to-cloudforms.adoc[leveloffset=+2]
include::modules/Assigning_control_policy_to_provider.adoc[leveloffset=+2]
include::modules/Configuring-cloudforms.adoc[leveloffset=+2]

[id='Managing-analysis-profiles_{context}']
== Managing analysis profiles

A `default` SmartState analysis profile is used to scan your VMware virtual machines.

You can create a custom analysis profile by modifying the xref:Custom-profile-yaml-example[`custom_profile.yaml` template].

You can export existing analysis profiles for backup, troubleshooting, or updates.

include::modules/Creating-a-default-analysis-profile.adoc[leveloffset=+2]
include::modules/Creating-a-custom-analysis-profile.adoc[leveloffset=+2]

[NOTE]
====
See xref:Custom-profile-yaml-example[] for the template.
====

include::modules/Exporting-analysis-profiles.adoc[leveloffset=+2]

== Collecting data for Migration Analytics

You can scan your VMware virtual machines and download the results as an inventory data file to your local machine.

Optionally, you can combine multiple inventory data files into a single file in order to generate a single Migration Analytics report.

include::modules/Scanning-vms-for-migration-analytics.adoc[leveloffset=+2]
include::modules/Collecting-inventory-data.adoc[leveloffset=+2]
include::modules/Combining-inventory-data-files.adoc[leveloffset=+2]

[id='Creating-and-filtering-a-migration-analytics-report']
== Creating and filtering a Migration Analytics report

You can create a Migration Analytics report, filter the results, and export the data.

include::modules/Creating-migration-analytics-report.adoc[leveloffset=+2]
include::modules/Migration-analytics-report.adoc[leveloffset=+2]
include::modules/Filtering-migration-analytics-report.adoc[leveloffset=+2]
include::modules/Exporting-migration-analytics-report.adoc[leveloffset=+2]

include::modules/Troubleshooting.adoc[leveloffset=+1]

[appendix]

include::modules/Custom_profile_yaml_example.adoc[leveloffset=+1]

:!migration_analytics:
