[[preparing_vm_for_openshift]]

== Preparing a Virtual Machine for OpenShift Enterprise

To host OpenShift Enterprise, virtual machines require the following:

* Red Hat Enterprise Linux 6.4 or higher

* Network access, with valid IP addresses and access to the OpenShift Enterprise sources, for example through Red Hat Subscription Manager or Red Hat Satellite

* SSH key access from all appliances running the Automation Role to the virtual machines

* Ruby 1.9.3 or higher

* Red Hat recommends creating a virtual machine template meeting these requirements to enable efficient deployment of multiple instances.
You can use your preferred source, for example PXE, ISO, or Clone, when creating the virtual machine so long as the requirements are met for OpenShift Enterprise installation.

Use the following procedure to prepare a template virtual machine:

. Install Red Hat Enterprise Linux 6.4 from ISO as a basic server on a new virtual machine using Red Hat Enterprise Virtualization.

. Register the virtual machine with Red Hat Subscription Manager and update the system using `yum update`.

. Install Ruby 1.9.3 using `yum install`.

. Copy the SSH key from your appliance to the virtual machine. Confirm you can open an SSH session from the appliance to the virtual machine.

. Prepare the virtual machine to become a template by clearing the UDEV rules for Network and unique details from the `ifcfg-eth0` file.

. Power off the virtual machine and use the Red Hat Enterprise Virtualization console to create a template from the virtual machine.

DNS is an important element of the environment, as machines must be able to connect bi-directionally to any resource in the network using the hostname.
That means that new virtual machines instantiated from the template need to register to your DNS system automatically.



NEW

== Preparing a Virtual Machine for OpenShift Enterprise

Initial blurb?

=== Requirements

To host OpenShift Enterprise, virtual machines require the following:

* Red Hat Enterprise Linux 6.4 or higher

* Network access, with valid IP addresses and access to the OpenShift Enterprise sources, for example through Red Hat Subscription Manager or Red Hat Satellite

* SSH key access from all appliances running the Automation Role to the virtual machines

* Ruby 1.9.3 or higher

* Red Hat recommends creating a virtual machine template meeting these requirements to enable efficient deployment of multiple instances.
You can use your preferred source, for example PXE, ISO, or Clone, when creating the virtual machine so long as the requirements are met for OpenShift Enterprise installation.

* DNS is an important element of the environment, as machines must be able to connect bi-directionally to any resource in the network using the hostname.
That means that new virtual machines instantiated from the template need to register to your DNS system automatically.

Use the following procedures to prepare a template virtual machine to host OpenShift Enterprise.

=== Creating a Virtual Machine in Red Hat Enterprise Virtualization

Install Red Hat Enterprise Linux 6.4 or higher from an ISO as a basic server on a new virtual machine using Red Hat Enterprise Virtualization.

From: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Virtualization/3.6-Beta/html-single/Virtual_Machine_Management_Guide/index.html#Creating_a_new_virtual_machine_from_a_blank_template

Create a new virtual machine and configure the required settings.
⁠

==== Creating a New Virtual Machine

. Click the *Virtual Machines* tab.
. Click the *New VM* button to open the New Virtual Machine window (insert screenshot?)

. Enter a *Name* for the virtual machine.
. Select a Linux variant from the *Operating System* drop-down list. OpenShift requires Red Hat Enterprise Linux 6.4 or higher.
. Click the *Show Advanced Options* button, and:
.. From the *System* tab, specify the virtual machine's *Memory Size*. (REQ FOR OPENSHIFT?)
.. From the *Boot Options* tab, choose the *First Device* that the virtual machine will boot from.

* If you have selected CD-ROM as a boot device, tick this check box and select a CD-ROM image from the drop-down menu. The images must be available in the ISO domain.

You can accept the default settings for all other fields, or change them if required. For more details on all fields in the New Virtual Machine window, see (LINK TO RHEV GUIDE) Section A.1, “Explanation of Settings in the New Virtual Machine and Edit Virtual Machine Windows”.
. Click *OK*.

The new virtual machine is created and displays in the list of virtual machines in the Red Hat Enterprise Virtualization Manager with a status of `Down`. Before you can use this virtual machine, add at least one network interface and one virtual disk, and install an operating system.


===== Adding a Network Interface to the Virtual Machine

. From the *Virtual Machines* tab, select the virtual machine you created.
. Click the *Network Interfaces* tab in the details pane.
. Click *New*. (ADD DIAGRAM?) Figure 2.2. New Network Interface window
. Enter the *Name* of the network interface.
. Use the drop-down lists to select the *Profile* and the *Type* of the network interface. The *Profile* and *Type* drop-down lists are populated in accordance with the profiles and network types available to the cluster and the network interface cards available to the virtual machine.
. Select the *Custom MAC address* check box and enter a MAC address for the network interface card as required.
. Click *OK*.

The new network interface is listed in the *Network Interfaces* tab in the details pane of the virtual machine. The *Link State* is set to *Up* by default when the network interface card is defined on the virtual machine and connected to the network.

(INSTEAD OF THIS, POINT ONE GENERAL LINK TO THE RHEV GUIDE - ADMIN or USER in 3.5 TO GIVE MORE INFO.)
For more details on the fields in the New Network Interface window, see  (LINK TO RHEV GUIDE) Section A.2, “Explanation of Settings in the New Network Interface and Edit Network Interface Windows”.


==== Adding a Virtual Disk

Configure storage for your virtual machine by adding a virtual disk. To add a disk to the virtual machine:

. From the *Virtual Machines* tab, select your virtual machine.
. Click the *Disks* tab in the details pane.
. Click *New*. (need diagram?) The New Virtual Disk Window Figure 2.3. The New Virtual Disk Window
. Use the appropriate radio buttons to switch between *Image*, *Direct LUN*, or Cinder*. (relevant???) Virtual disks added in the User Portal can only be *Image* disks. *Direct LUN* and *Cinder* disks can be added in the Administration Portal.
. Enter a *Size(GB)*, *Alias*, and *Description* for the new disk. (recommendations for size?)
. Use the drop-down lists and check boxes to configure the disk. See (LINK HERE) Section A.3, “Explanation of Settings in the New Virtual Disk and Edit Virtual Disk Windows” for more details on the fields for all disk types.
. Click *OK*.

The new disk appears in the details pane after a short time.

==== Installing the Virtual Machine Operating System
⁠
. Click the *Virtual Machines* tab and select a virtual machine with a status of `Down`.
. Click the run ( ) button.
. Alternatively, right-click the virtual machine and select *Run*.

* The virtual machine status changes to `Up`, and the operating system installation begins. Open a console to the virtual machine if one does not open automatically.
⁠
2.4.2. Opening a Console to a Virtual Machine
Use Remote Viewer to connect to a virtual machine.
⁠
Procedure 2.5. Connecting to Virtual Machines

. Install `Remote Viewer` if it is not already installed. See (ADD LINK) Section 1.4.1, “Installing Console Components”.
. Click the *Virtual Machines* tab and select a virtual machine.
. Click the console button or right-click the virtual machine and select *Console*.

* If the connection protocol is set to SPICE, a console window will automatically open for the virtual machine.
* If the connection protocol is set to VNC, a `console.vv` file will be downloaded. Click on the file and a console window will automatically open for the virtual machine.

. Follow the prompts in the Red Hat Enterprise Linux installer to install the virtual machine's operating system. For more information, on installing Red Hat Enterprise Linux 6, see https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Installation_Guide/index.html

=== Registering the virtual machine

Register the virtual machine to the Red Hat Content Delivery Network (is that right?) with the following steps:

. After the installation is complete, reboot the instance and log in as the root user.
. Update the `/etc/sysconfig/network-scripts/ifcfg-eth0` file so it only contains the following values:
+
------
TYPE=Ethernet
DEVICE=eth0
ONBOOT=yes
BOOTPROTO=dhcp
NM_CONTROLLED=no
------
+
. Reboot the machine.
. Register the machine with the Content Delivery Network:
------
# subscription-manager register
------
..  Enter your Customer Portal user name and password when prompted:
+
------
Username: admin@example.com
Password:
------
+
..  Find entitlement pools containing the channel:
+
------
# subscription-manager list --available | grep -A8 "Red Hat Enterprise Linux Server"
------
+
.. Use the pool identifiers located in the previous step to attach the Red Hat Enterprise Linux Server entitlement to the system:
+
------
# subscription-manager attach --pool=pool_id
------
+
.. Enable the required channel:
+
------
# subscription-manager repos --enable=rhel-7-server-rpms
------
+
* (change) For RHEL OpenStack Platform 7, the required channels are rhel-7-server-openstack-7.0-rpms and rhel-7-server-rh-common-rpms. For more information, see "Subscribe to the Required Channels" in the Installation Reference.

.. Update the system:
+
------
# yum -y update
------
+
. FIX NUMBERING Un-register the virtual machine so that the resulting image does not contain the same subscription details for every instance cloned based on it.
+
------
# subscription-manager repos --disable=*
# subscription-manager unregister
# yum clean all
------
+

The virtual machine is now registered to the Red Hat Content Delivery Network (is that what we call it?).


=== Configuring the virtual machine

. Install Ruby 1.9.3:
+
------
# yum install ruby
------
+
. Copy the SSH key from your appliance to the virtual machine:
+
------
# COMMAND
------
+
. Confirm you can open an SSH session from the appliance to the virtual machine:
+
------
# COMMANDS
------
+
. Prepare the virtual machine to become a template by clearing the UDEV rules for Network and unique details from the ifcfg-eth0 file.
+
------
# COMMANDS
------
+
. Power off the virtual machine:
+
------
# poweroff
------

=== Creating a virtual machine template

6.3.1. Creating a Template
Create a template from an existing virtual machine to use as a blueprint for creating additional virtual machines (OR SOMETHING ELSE?_).

[IMPORTANT]
======
Before you create a template, you must seal the source virtual machine to ensure all system-specific details are removed from the virtual machine. This is necessary to prevent the same details from appearing on multiple virtual machines created based on the same template. (add link) See Section 6.4.1, “Sealing a Linux Virtual Machine for Deployment as a Template”.
======

Procedure 6.3. Creating a Template

. Click the *Virtual Machines* tab and select the source virtual machine.
. Ensure the virtual machine is powered down and has a status of `Down`.
. Click *Make Template*.
⁠
(diagram)The New Template window - Figure 6.1. The New Template window
. Enter a *Name*, *Description*, and *Comment* for the template.
. Select the cluster with which to associate the template from the *Cluster* drop-down list. By default, this is the same as that of the source virtual machine.
. Optionally, select a CPU profile for the template from the *CPU Profile* drop-down list.
. Optionally, select the *Create as a Sub Template* version check box, select a *Root Template*, and enter a *Sub Version Name* to create the new template as a sub template of an existing template.
. In the *Disks Allocation* section, enter an alias for the disk in the *Alias* text field, and select the storage domain on which to store the disk from the *Target* list. By default, these are the same as those of the source virtual machine.
. Select the *Allow all users to access this Template* check box to make the template public.
. Select the *Copy VM permissions* check box to copy the permissions of the source virtual machine to the template.
. Click *OK*.

The virtual machine displays a status of `Image Locked` while the template is being created. The process of creating a template may take up to an hour depending on the size of the virtual machine disk and the capabilities of your storage hardware. When complete, the template is added to the *Templates* tab. You can now create new virtual machines based on the template.


[NOTE]
======
When a template is made, the virtual machine is copied so that both the existing virtual machine and its template are usable after template creation.
======

ADD FINAL PARAGRAPH.
