[[preparing_vm_for_openshift]]

== Preparing a Virtual Machine for OpenShift Enterprise

To host OpenShift Enterprise, virtual machines require the following:

* Red Hat Enterprise Linux 6.4 or higher

* Network access, with valid IP addresses and access to the OpenShift Enterprise sources, for example through Red Hat Subscription Manager or Red Hat Satellite

* SSH key access from all appliances running the Automation Role to the virtual machines

* Ruby 1.9.3 or higher
			
* Red Hat recommends creating a virtual machine template meeting these requirements to enable efficient deployment of multiple instances.
You can use your preferred source, for example PXE, ISO, or Clone, when creating the virtual machine so long as the requirements are met for OpenShift Enterprise installation.
	
Use the following procedure to prepare a template virtual machine:

. Install Red Hat Enterprise Linux 6.4 from ISO as a basic server on a new virtual machine using Red Hat Enterprise Virtualization.

. Register the virtual machine with Red Hat Subscription Manager and update the system using +yum update+.

. Install Ruby 1.9.3 using +yum install+.

. Copy the SSH key from your appliance to the virtual machine. Confirm you can open an SSH session from the appliance to the virtual machine.

. Prepare the virtual machine to become a template by clearing the UDEV rules for Network and unique details from the +ifcfg-eth0+ file.

. Power off the virtual machine and use the Red Hat Virtualization console to create a template from the virtual machine.
			
DNS is an important element of the environment, as machines must be able to connect bi-directionally to any resource in the network using the hostname.
That means that new virtual machines instantiated from the template need to register to your DNS system automatically.

