[[Configuring-cloudforms]]
=== Configuring CloudForms

After installing CloudForms and running it for the first time, you must perform some basic configuration. To configure CloudForms, you must at a minimum:

. Add a disk to the infrastructure hosting your appliance.
. Configure the database. 

Configure the CloudForms appliance using the internal appliance console.

[[accessing-appliance-console]]
[discrete]
==== Accessing the Appliance Console

. Start the appliance and open a terminal console.
ifdef::login[]
. After starting the appliance, log in with a user name of `root` and the default password of `smartvm`. This displays the Bash prompt for the `root` user.
endif::login[]
ifdef::ssh[]
. Log in to the appliance using the SSH key.
endif::ssh[]
. Enter the `appliance_console` command. The CloudForms appliance summary screen is displayed.
. Press `Enter` to manually configure settings.
. Press the number for the item you want to change, and press `Enter`. The options for your selection are displayed.
. Follow the prompts to make the changes.
. Press `Enter` to accept a setting where applicable.

[NOTE]
====
The CloudForms appliance console automatically logs out after five minutes of inactivity.
====

////
ifdef::cfme[]
[[configuring_a_database]]
////

////
Before using CloudForms, configure the database options for it; CloudForms provides the following two options for database configuration:

* Install an internal PostgreSQL database to the appliance 
* Configure the appliance to use an external PostgreSQL database
////

[[configuring-an-internal-database]]
[discrete]
==== Configuring an Internal Database

CloudForms uses a database to store information about the environment. *(%AP: I included only the internal DB. Should I include option for external DB?)*

[IMPORTANT]
====
Before installing an internal database, add a disk to the infrastructure hosting your appliance. See the documentation specific to your infrastructure for instructions for adding a disk. As a storage disk usually cannot be added while a virtual machine is running, Red Hat recommends adding the disk before starting the appliance. CloudForms only supports installing of an internal VMDB on blank disks; installation will fail if the disks are not blank.
====

. Start the appliance and open a terminal console.
ifdef::login[]
. After starting the appliance, log in with a user name of `root` and the default password of `smartvm`. This displays the Bash prompt for the `root` user.
endif::login[]
ifdef::ssh[] 
. Log in to the appliance using the SSH key.
endif::ssh[] 
. Enter the `appliance_console` command. The CloudForms appliance summary screen displays.
. Press *Enter* to manually configure settings.
. Select *5) Configure Database* from the menu.
. You are prompted to create or fetch an encryption key.
* If this is the first CloudForms appliance, choose *1) Create key*.
* If this is not the first CloudForms appliance, choose *2) Fetch key from remote machine* to fetch the key from the first appliance. For worker and multi-region setups, use this option to copy key from another appliance. 
+
[NOTE]
====
All CloudForms appliances in a multi-region deployment must use the same key.
====
+
. Choose *1) Create Internal Database* for the database location.
. Choose a disk for the database. This can be either a disk you attached previously, or a partition on the current disk. 
+
[IMPORTANT]
====
Red Hat recommends using a separate disk for the database.
====
+
If there is an unpartitioned disk attached to the virtual machine, the dialog will show options similar to the following:
+
----
1) /dev/vdb: 20480
2) Don't partition the disk 
----
+
* Enter *1* to choose `/dev/vdb` for the database location. This option creates a logical volume using this device and mounts the volume to the appliance in a location appropriate for storing the database. The default location is `/var/opt/rh/rh-postgresql95/lib/pgsql`, which can be found in the environment variable `$APPLIANCE_PG_MOUNT_POINT`.
* Enter *2* to continue without partitioning the disk. A second prompt will confirm this choice. Selecting this option results in using the root filesystem for the data directory (not advised in most cases). 
. Enter *Y* or *N* for *Should this appliance run as a standalone database server?*
* Select *Y* to configure the appliance as a database-only appliance. As a result, the appliance is configured as a basic PostgreSQL server, without a user interface. 
* Select *N* to configure the appliance with the full administrative user interface.
. When prompted, enter a unique number to create a new region.
+
[IMPORTANT]
====
Creating a new region destroys any existing data on the chosen database.
====
+
.  Create and confirm a password for the database.

CloudForms configures the internal database.

////
Commented out the external DB
[[configuring-an-external-database]]
===== Configuring an External Database

Based on your setup, you will choose to configure the appliance to use an external PostgreSQL database. For example, we can only have one database in a single region. However, a region can be segmented into multiple zones, such as database zone, user interface zone, and reporting zone, where each zone provides a specific function. The appliances in these zones must be configured to use an external database. 

The `postgresql.conf` file used with CloudForms databases requires specific settings for correct operation. For example, it must correctly reclaim table space, control session timeouts, and format the PostgreSQL server log for improved system support. Due to these requirements, Red Hat recommends that external CloudForms databases use a `postgresql.conf` file based on the standard file used by the CloudForms appliance.

Ensure you configure the settings in the `postgresql.conf` to suit your system. For example, customize the `shared_buffers` setting according to the amount of real storage available in the external system hosting the PostgreSQL instance. In addition, depending on the aggregate number of appliances expected to connect to the PostgreSQL instance, it may be
necessary to alter the `max_connections` setting.

[NOTE]
====
* CloudForms 4.x requires PostgreSQL version 9.4.
* Because the `postgresql.conf` file controls the operation of all databases managed by a single instance of PostgreSQL, do not mix CloudForms databases with other types of databases in a single PostgreSQL instance.
====

. Start the appliance and open a terminal console.
ifdef::login[]
. After starting the appliance, log in with a user name of `root` and the default password of `smartvm`. This displays the Bash prompt for the `root` user.
endif::login[]
ifdef::ssh[]
. Log in to the appliance using the SSH key.
endif::ssh[]
. Enter the `appliance_console` command. The CloudForms appliance summary screen is displayed.
. Press *Enter* to manually configure settings.
. Select *5) Configure Database* from the menu.
. You are prompted to create or fetch a security key.
* If this is the first CloudForms appliance, choose *1) Create key*.
* If this is not the first CloudForms appliance, choose *2) Fetch key from remote machine* to fetch the key from the first appliance. 
+
[NOTE]
====
All CloudForms appliances in a multi-region deployment must use the same key.
====
+
. Choose *2) Create Region in External Database* for the database location.
. Enter the database hostname or IP address when prompted.
. Enter the database name or leave blank for the default (`vmdb_production`).
. Enter the database username or leave blank for the default (`root`).
. Enter the chosen database user's password.
. Confirm the configuration if prompted.

CloudForms will then configure the external database.
endif::cfme[]

[[configuring-a-worker-appliance]]
==== Configuring a Worker Appliance

You can use multiple appliances to facilitate horizontal scaling, as well as for dividing up work by roles. Accordingly, configure an appliance to handle work for one or many roles, with workers within the appliance carrying out the duties for which they are configured. You can configure a worker appliance through the terminal. The following steps demonstrate how to join a worker appliance to an appliance that already has a region configured with a database. 

. Start the appliance and open a terminal console.
ifdef::login[]
. After starting the appliance, log in with a user name of `root` and the default password of `smartvm`. This displays the Bash prompt for the `root` user.
endif::login[]
ifdef::ssh[]
. Log in to the appliance using the SSH key.
endif::ssh[]
. Enter the `appliance_console` command. The CloudForms appliance summary screen is displayed.
. Press *Enter* to manually configure settings.
. Select *5) Configure Database* from the menu.
. You are prompted to create or fetch a security key. Since this is not the first CloudForms appliance, choose *2) Fetch key from remote machine*. For worker and multi-region setups, use this option to copy key from another appliance. 
+
[NOTE]
====
All CloudForms appliances in a multi-region deployment must use the same key.
====
+
. Choose *3) Join Region in External Database* for the database location.
. Enter the database hostname or IP address when prompted.
. Enter the port number or leave blank for the default (`5432`).
. Enter the database name or leave blank for the default (`vmdb_production`).
. Enter the database username or leave blank for the default (`root`).
. Enter the chosen database user's password.
. Confirm the configuration if prompted.
////