
[[_sect_cloud_intelligence_dashboard]]
== Cloud Intelligence Dashboard

Cloud Intelligence shows your virtual environment's events, reports, and configurable alerts.
This information supports better information technology decision making and predictions for future virtual machine management.

When you log in to the console, it brings you directly to the *Cloud Intelligence Dashboard* page by default.
The console uses widgets to organize this page, providing you with a default set of commonly used widgets.
The configuration items on these widgets are clickable, allowing you to drill down directly to a referenced item.

Customize this page to include charts and reports you specifically want to see as soon as you log in to the console.
You can add, remove, move, minimize, zoom into, and maximize widgets.
Only users with the proper access can create widgets.

include::To_add_a_widget.adoc[]

include::To_reset_to_the_default_set_of_widgets.adoc[]

include::To_remove_a_widget.adoc[]

include::To_zoom_in_to_a_chart_widget.adoc[]

include::To_open_a_chart_or_report_widget_in_its_own_window.adoc[]

include::To_minimize_or_maximize_a_widget.adoc[]

include::To_download_a_report_widget_as_a_file.adoc[]

include::Copying_a_Dashboard.adoc[]
