[[integrating_prometheus_alerts]]
== OpenShift Prometheus Alerts

[NOTE]
====
This feature is available with this release of {product-title} as a technology preview only. For more information on the support scope for features marked as technology previews, see https://access.redhat.com/support/offerings/techpreview[Technology Preview Features Support Scope].
====

Prometheus is used as an external alerting component. {product-title} integrates Prometheus alerts for use with OpenShift Container Platform. {product-title_short} collects EmsEvents from Prometheus, generates alerts based on these events, and then attaches alerts to inventory objects.

It is possible to view ongoing alerts in {product-title_short} and manage their life cycle, including the ability to:

* View active alerts per provider in the alert dashboard.
* View alert data and related objects.
* Assign and acknowledge alerts in the alerts list screen.

=== Integrating Prometheus alerts in {product-title_short}

.Complete the following prerequisite steps on the OpenShift Container Platform:

. Deploy and Configure Prometheus on OpenShift; see https://docs.openshift.com/container-platform/3.7/install_config/cluster_metrics.html#openshift-prometheus[Prometheus on OpenShift Container Platform].

. Add Prometheus to an OpenShift cluster and configure alert definitions. 
.. See intructions below to define alerts (currently has to be done on the Prometheus side):
+
----
$ oc edit configmap -n openshift-metrics prometheus
# Supported annotations:
# severity: ERROR|WARNING|INFO. defaults to ERROR.
# miqTarget: ContainerNode|ExtManagementSystem, defaults to ContainerNode.
# miqIgnore: "true|false", should ManageIQ pick up this alert, defaults to true.
  prometheus.rules: |
    groups:
    - name: example-rules
      interval: 30s # defaults to global interval
      rules:
      - alert: "Node Down"
        expr: up{job="kubernetes-nodes"} == 0
        annotations:
          miqTarget: "ContainerNode"
          severity: "ERROR"
          url: "https://www.example.com/fixing_instructions"
          message: "Node {{$labels.instance}} is down"

----
+
. Reload the Prometheus configuration. You can do this by deleting the Prometheus pod, then redeploying with the new configuration.


.Complete the following steps to set up Prometheus alerts in {product-title_short}:

. In the {product-title_short} user interface, navigate to menu:Control[Explorer]. Create one container node alert based on *All datawarehouse alerts*, and one provider alert based on *All datawarehouse alerts*.
. Add each new alert to an alert profile.
. Assign *Prometheus node Profile* and *Prometheus Provider Profile* to the enterprise.
. Add a Prometheus alerts endpoint.


