[[integrating_prometheus_alerts]]
=== Integrating Prometheus Alerts

[NOTE]
====
This feature is available with this release of {product-title} as technology preview only. For more information on the support scope for features marked as technology previews, see https://access.redhat.com/support/offerings/techpreview[Technology Preview Features Support Scope].
====

Prometheus is used as an external alerting component. {product-title} integrates Prometheus alerts for use with OpenShift Container Platform. {product-title_short} collects EmsEvents from Prometheus, generates alerts based on these events, and then attaches alerts to inventory objects.

It is possible to view ongoing alerts in {product-title_short} and manage their life cycle, including the ability to:

* View active alerts per provider in the alert dashboard.
* View alert data and related objects.
* Assign and acknowledge alerts in the alerts list screen.

.Prerequisites

* Create an Ansible role for deploying Prometheus on OpenShift.
* Add Prometheus to an OpenShift cluster and configure alert definitions.

Complete the following procedure to setup Prometheus alerts in {product-title_short}.

. In {product-title_short}, navigate to menu:Control[Explorer]. Create one container node alert based on *All datawarehouse alerts*, and one provider alert based on *All datawarehouse alerts*.
. Add each new alert to an alert profile.
. Assign *Prometheus node Profile* and *Prometheus Provider Profile* to the enterprise.
. Add a Prometheus alerts endpoint.


