[[_operational_alerts]]
=== Operational Alert Types

.Operational Alerts
[cols="1,1,1", frame="all", options="header"]
|===
| 
						
							Driving Event
						
					
| 
						
							Explanation (Thresholds, Description)
						
					
| 
						
							Proposed Action if Alert is Raised
						
					
| 
						
							EVM Server Start
						
					
| 
						
							Alert is raised when an EVM Server starts.
						
					
|

| 
						
							EVM Server Stop
						
					
| 
						
							Alert is raised when an EVM Server stops.
						
					
|

| 
						
							EVM Server Not Responding
						
						
					
| 
						
							Alert is raised when one EVM server detects that another EVM Server has not responded in (2 minutes).
						
					
| 
						
							This is a sign of a problem that should be investigated. Check logs.
						
					

| 
						
							EVM Server Exceeded Memory Limit
						
					
| 
						
							Alert is raised when an EVM server has exceeded its system memory limit and begins killing workers. Default is 80%.
						
						
						
							Threshold configured in Advanced Settings.
						
						
							server:
						
						
							:worker_monitor:
						
						
							:kill_algorithm:
						
						
							:name: :used_swap_percent_gt_value
						
						
							:value: 80
						
					
| 
						
							This may be caused by the following issues: 
							
								
									
										The server is running with too few resources.
									
								
								
									
										The server is enabled with too many roles or number of workers.
									
								
								
									
										The server picked up all the roles because another server has failed.
									
								
								
									
										A runaway process has taken up most of the memory.
									
								
							
						
					

| 
						
							EVM Server is Master
						
					
| 
						
							When one EVM Server takes over as a master server.
						
					
| 
						
							Typically, this should only occur when first starting a set of servers, perhaps following expected outages. If a server picks up as master in other situations, the old master had an issue that needs to be researched (such as server not responding in time).
						
					

| 
						
							EVM Server High System Disk Usage
						
					
| 
						
							The EVM Servers system disk is 80% full. This check is run as part of a system schedule.
						
						
						
							Threshold configured in Advanced Settings.
						
						
							server:
						
						
							events:
						
						
							:disk_usage_gt_percent: 80
						
					
| 
						
							Something is filling the disk such as temp files used by the operating system such as, yum updates and normal /tmp files, or EVM temp files in /var/lib/data/miqtemp/.
						
					

| 
						
							EVM Server High App Disk Usage
						
					
| 
						
							The EVM Servers app disk is 80% full. This check is run as part of a system schedule.
						
						
						
							Threshold configured in Advanced Settings.
						
						
							server:
						
						
							events:
						
						
							:disk_usage_gt_percent: 80
						
					
| 
						
							Possibly EVM temp files are being left around.
						
					

| 
						
							EVM Server High Log Disk Usage
						
					
| 
						
							The EVM Servers log disk is 80% full. This check is run as part of a system schedule.
						
						
						
							Threshold configured in Advanced Settings.
						
						
							server:
						
						
							events:
						
						
							:disk_usage_gt_percent: 80
						
					
| 
						
							Logs are getting too big or are not being log rotated properly every day. Check most recent logs.
						
					

| 
						
							EVM Server High DB Disk Usage
						
					
| 
						
							The EVM Servers db disk is 80% full. This check is run as part of a system schedule. Applies if using PostgreSQL as the VDMB.
						
						
						
							Threshold configured in Advanced Settings.
						
						
							server:
						
						
							events:
						
						
							:disk_usage_gt_percent: 80
						
					
| 
						
							Database or database logging is getting too large. May need FULL vacuuming of PostgreSQL database.
						
					

| 
						
							EVM Worker Started
						
					
| 
						
							Alert is raised when a worker is about to start.
						
					
|

| 
						
							EVM Worker Stopped
						
						
					
| 
						
							Alert is raised when a worker is requested to stop.
						
					
|

| 
						
							EVM Worker Killed
						
					
| 
						
							Alert is raised when a non- responsive worker does not restart on its own and is killed.
						
					
|

| 
						
							EVM Worker Not Responding
						
					
| 
						
							Alert is raised when a worker has not responded for 2 minutes (:heartbeat_timeout) or has not started within 10 minutes (:starting_timeout).
						
					
|

| 
						
							EVM Worker Exceeded Memory Limit
						
					
| 
						
							Alert is raised when a worker exceeds the memory threshold. The default is 150 MB, but some workers have their own value in the :memory_threshold section for that specific worker.
						
					
|

| 
						
							EVM Worker Exceeded Uptime Limit
						
					
| 
						
							Alert is raised when a worker has been running longer than the :restart_interval. (Most workers are set to never restart using the 0.hours setting.) The EMS Refresh SmartProxy workers are set to restart every 2 hours.
						
					
|

| 
						
							EVM Worker Exit File
						
					
| 
						
							Alert is raised when the scheduler worker exits due to a pending large ntp time change.
						
					
|
|===
