[[_to_assign_chargeback_rates]]
= Assigning Chargeback Rates

CloudForms Management Engine allows you to assign chargeback rates by choosing from [label]#Compute# and [label]#Storage#. 

.Procedure: To Assign Chargeback Rates
. Navigate to menu:Cloud Intelligence[Chargeback]. 
Click the [label]#Assignments# accordion, and click either [label]#Compute# or [label]#Storage#.
 

* Use [label]#Compute# to assign a compute chargeback rate.
  You can assign chargeback rates to [label]#The Enterprise#, [label]#Selected Clusters#, [label]#Selected Infrastructure Providers#, or [label]#Tagged VMs and Instances#. 
* Use [label]#Storage# to assign a storage chargeback rate.
. You can assign chargeback rates to [label]#The Enterprise#, [label]#Selected Datastores#, or [label]#Tagged Datastores# 			
. From the [label]#Basic Info# area, use the [label]#Assign To# list to select a type of assignee to assign the rate set to.
  The options displayed vary based on the type you selected. 
. For each item to set, select the chargeback rate to use. 
. Click btn:[Save]. 

.Result:
The rate is assigned.
The next time you generate a chargeback report, these values will be used. 

NOTE: Note that when viewing chargeback, there is a rate for a virtual machine for the number of the CPUs.
The chargeback for this parameter is calculated based on when the virtual machine is running.
If the virtual machine is not running, then it is not charged for CPU allocation. . 