[[_to_access_and_use_a_timeline]]
= Accessing and Using a Timeline

You can use timelines to view the history record for virtual machines.
 

.Note
[NOTE]
====
Amazon does not provide events, so CloudForms Management Engine does not support timelines for virtual machines hosted by Amazon. 
====	

.Procedure: To Access and Use a Timeline
. Navigate to menu:Cloud Intelligence[Timelines]. 
. From the accordion on the left, click a category of [label]#Timeline#. 
+
* Select [label]#Configuration Management# to see when items were brought under management. 
* Select [label]#Events# to view timelines related to operations and changes in configuration. 

. Drag the relevant time band, such as hour, day, or month to go to the time you want to see.
  Note that some timelines, such as [label]#Events Operations: All Events#, use minutes, hours, and days instead going back only 30 days. 
. To see more detail for a resource in the timeline, click on it.
  A balloon appears with a clickable link to the resource. 