[[_to_assign_chargeback_rates]]

=== Assigning Chargeback Rates

{product-title} allows you to assign chargeback rates by choosing from *Compute* and *Storage*.

. Navigate to menu:Cloud Intel[Chargeback].
. Click the *Assignments* accordion, and click either *Compute* or *Storage*.

==== Configuring Chargeback for Compute

Use *Compute* to assign a compute chargeback rate.
You can assign chargeback rates to *The Enterprise*, *Selected Cloud/Infrastructure Providers*, *Selected Clusters/Deployment Roles*, *Selected Containers Providers*, *Tagged VMs and Instances*, *Tagged Images*, *Labeled Images*, or *Tenants*.

. From the *Basic Info* area, use the *Assign To* list to select a type of assignee to assign the rate set to.
. For *Tagged VMs and Instances* and *Tagged Images* select a *Tag Category*.
. For each item to set, select the chargeback rate to use. The options displayed vary based on the type you select.
. Click *Save*.



==== Configuring Chargeback for Storage

Use *Storage* to assign a storage chargeback rate.
You can assign chargeback rates to *The Enterprise*, *Selected Datastores*, *Tagged Datastores*, or *Tenants*.


. From the *Basic Info* area, use the *Assign To* list to select a type of assignee to assign the rate set to.
. For *Tagged Datastores* select a *Tag Category*.
. For each item to set, select the chargeback rate to use. The options displayed vary based on the type you select.

. Click *Save*.

The rate is assigned.
The next time you generate a chargeback report, these values will be used.

[NOTE]
====
When viewing chargeback, there is a rate for a virtual machine for the number of the CPUs.
The chargeback for this parameter is calculated based on when the virtual machine is running.
If the virtual machine is not running, then it is not charged for CPU allocation.
====
