= Managing Providers
:imagesdir: images
:vernum: 0
:doctype: book
:toc: left
:toclevels: 3
:numbered!:
:experimental:

// Custom attributes
include::common/attributes/miq.adoc[]

:miq:

:numbered:

{product-title} can manage a variety of external environments, known as providers and managers. A provider or manager is any system that {product-title_short} integrates with for the purpose of collecting data and performing operations.

In {product-title_short}, a _provider_ is an external virtualization, cloud, or containers environment that manages multiple virtual machines or instances residing on multiple hosts. One example is Red Hat Virtualization, a platform that manages multiple hosts and virtual machines.

In {product-title_short}, a _manager_ is an external management environment that manages more than one type of resource. One example of a manager is OpenStack, which manages infrastucture, cloud, network, and storage resources.

This guide covers working with providers and managers in {product-title_short}, which include:

* Infrastructure providers
* Configuration management providers
* Automation management providers
* Cloud providers
* Networking management providers
* Container providers
* Storage managers

For information on working with the resources contained by a provider or manager, see _Managing Infrastructure and Inventory_.


:leveloffset: 1
include::doc-Managing_Providers/miq/topics/Infrastructure_Providers.adoc[]


:leveloffset: 1
include::doc-Managing_Providers/miq/topics/Configuration_Management_Providers.adoc[]

:leveloffset: 1
include::doc-Managing_Providers/miq/topics/Automation_Management_Providers.adoc[]


:leveloffset: 1
include::doc-Managing_Providers/miq/topics/Cloud_Providers.adoc[]


:leveloffset: 1
include::doc-Managing_Providers/miq/topics/Networking_Providers.adoc[]

:leveloffset: 1
include::doc-Managing_Providers/miq/topics/Containers_Providers.adoc[]


:leveloffset: 1
include::doc-Managing_Providers/miq/topics/Storage_Managers.adoc[]


[appendix]
[[appendix]]
:leveloffset: 1
= Appendix

include::common/app-self_signed_CA.adoc[]
