[[Installing_RHVH]]
= Installing Red Hat Virtualization Hosts

You must install at least one host to function as a conversion host during the migration. Ensure that your hosts are sufficient to cover the memory and CPU requirements of the virtual machines that you are migrating.

Red Hat Virtualization Host (RHVH) is a minimal operating system, based on Red Hat Enterprise Linux, that is designed to provide a simple method for setting up a physical machine to act as a hypervisor in a Red Hat Virtualization environment. The minimal operating system contains only the packages required for the machine to act as a hypervisor, and features a Cockpit user interface for monitoring the host and performing administrative tasks.

RHVH uses NIST 800-53 partitioning by default, to improve security.

The procedure for installing RHVH on a physical machine has 3 key stages:

* Download the RHVH ISO image from the Customer Portal.
* Write the RHVH ISO image to a bootable media device.
* Install the RHVH minimal operating system.

[discrete]
== Prerequisites

Your conversion host machines must meet the following minimum requirements to support migration:

* CPU:
** Must support Intel® 64 or AMD64 CPU extensions, with AMD-V™ or Intel VT® hardware virtualization extensions enabled.
** Must support the No eXecute flag (NX).
* BIOS: Virtualization must be enabled.
* Memory: Minimum: 2 GB. Maximum: 2 TB. The amount of RAM required depends on guest operating system requirements, guest application requirements, and guest memory activity and usage. KVM can also overcommit physical RAM for virtualized guests, allowing you to provision guests with RAM requirements greater than what is physically present, on the assumption that the guests are not all working concurrently at peak load. KVM does this by only allocating RAM for guests as required and shifting underutilized guests into swap.
* Storage: Minimum: 45 GB. Hosts require local storage to store configuration, logs, kernel dumps, and for use as swap space.
* Network Interface Card (NIC) - Minimum: At least 2 x 10 GbE or FC8/FC16 connections to the storage. In addition, the conversion host should have a 10 GbE interface to copy the image from the VMware system.

[discrete]
== Procedure

. Download the RHVH ISO image from the Customer Portal:

.. Log into the Customer Portal at link:https://access.redhat.com[].
.. Click *Downloads* in the menu bar.
.. Click *Red Hat Virtualization*, scroll up, and click *Download Latest* to access the product download page.
.. Choose the appropriate hypervisor image and click *Download Now*.

. Copy the hypervisor image to a bootable media device. A DVD is recommended, due to the large size of the image.
. Start the machine on which to install RHVH, using the prepared installation media device.
. From the boot menu, select the *Install* option, and press `Enter`.
. Select a language, and click *Continue*.
. Select a time zone from the *Date &amp; Time* screen and click *Done*.
. Select a keyboard layout from the *Keyboard* screen and click *Done*.
. Select the device on which to install RHVH from the *Installation Destination* screen. Optionally, enable encryption. Click *Done*.
+
. Select a network from the *Network &amp; Host Name* screen and click *Configure...* to configure the connection details. Enter a host name in the *Host name* field, and click *Done*.
. Click *Begin Installation*.
. Set a root password.
. Click *Reboot* to complete the installation.
+
[NOTE]
====
When RHVH restarts, `nodectl check` performs a health check on the host and displays the result when you log in on the command line. The message `node status: OK` or `node status: DEGRADED` indicates the health status. Run `nodectl check` to get more information. The service is enabled by default.
====
+
. Once the installation is complete, log into the Cockpit user interface at +https://_HostFQDNorIP_:9090+ to register the host with the Content Delivery Network.
. Click *Subscriptions*, click *Register System*, and enter your Customer Portal user name and password. The *Red Hat Virtualization Host* subscription is automatically attached to the system.
. Click *Terminal*, and enable the `Red Hat Virtualization Host 7` repository to allow later updates to the Red Hat Virtualization Host:
[options="nowrap" subs="+quotes,verbatim"]
+
----
# subscription-manager repos --enable=rhel-7-server-rhvh-4-rpms
----

After installing the Red Hat Virtualization hosts, you can add the hosts to your Red Hat Virtualization environment.
