[[Adding_NFS_Storage]]
= Adding NFS Storage

NFS versions 3 and 4 are supported by Red Hat Virtualization 4. Production workloads require an enterprise-grade NFS server. When enterprise NFS is deployed over 10 GbE, segregated with VLANs, and individual services are configured to use specific ports, it is both fast and secure.

As NFS exports are grown to accommodate more storage needs, Red Hat Virtualization recognizes the larger data store immediately. No additional configuration is necessary on the hosts or from within Red Hat Virtualization. This provides NFS a slight edge over block storage from a scale and operational perspective.

[discrete]
== Prerequisites

* *nfs-utils* installed.

* The following services installed and enabled:

** *nfs*: `systemctl start nfs` starts the NFS server and the appropriate RPC processes to service requests for shared NFS file systems.
** *nfs-lock*: `systemctl start nfs-lock` activates a mandatory service that starts the appropriate RPC processes allowing NFS clients to lock files on the server.
** *rpcbind*: `rpcbind` accepts port reservations from local RPC services. These ports are then made available (or advertised) so the corresponding remote RPC services can access them. `rpcbind` responds to requests for RPC services and sets up connections to the requested RPC service. This is not used with NFSv4.

[discrete]
== Preparing NFS Storage

NFS shares serve as data and ISO domains on a Red Hat Enterprise Linux server.

* Data Domain: Data domains hold the virtual hard disks and OVF files of all the virtual machines and templates in a data center. In addition, snapshots of the virtual machines are stored in the data domains. Data domains cannot be shared across data centers. Data domains of multiple types (iSCSI, NFS, FC, POSIX, and Gluster) can be added to the same data center, provided they are all shared, rather than local, domains.

* ISO Domain: ISO domains store ISO files (or logical CDs) used to install and boot operating systems and applications for the virtual machines. An ISO domain removes the data center’s need for physical media. An ISO domain can be shared across different data centers. ISO domains can only be NFS-based. Only one ISO domain can be added to a data center.

. Create the data directory:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# mkdir -p _/exports/data_
----

. Add the newly created directory to the `/etc/exports` file:
+
[options="nowrap" subs="+quotes,verbatim"]
----
_/exports/data_ *(rw)
----

. Export the storage domain:
+
----
# exportfs -r
----

. Reload the NFS service:
+
----
# systemctl reload nfs
----

. Create the group `kvm`:
+
----
# groupadd kvm -g 36
----

. Create the user `vdsm` in the group `kvm`:
+
----
# useradd vdsm -u 36 -g 36
----

. Set the ownership of your exported directory to 36:36, which gives vdsm:kvm ownership:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# chown -R 36:36 _/exports/data_
----

. Change the mode of the directory so that read and write access is granted to the owner, and so that read and execute access is granted to the group and other users:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# chmod 0755 _/exports/data_
----

[discrete]
== Attaching NFS Storage

Attach the NFS storage domain to the data center in your Red Hat Virtualization environment. This storage domain provides storage for virtual disks and and ISO boot media. This procedure assumes that you have already exported shares.

. In the Administration Portal, click menu:Storage[Domains].
. Click *New Domain*.
. Enter a *Name* for the storage domain.
. Accept the default values for the *Data Center*, *Domain Function*, *Storage Type*, *Format*, and *Use Host* lists.
. Enter the *Export Path* to be used for the storage domain. The export path should be in the format of _192.168.0.10:/data_ or _domain.example.com:/data_.
. Click *OK*.

The new NFS data domain has a status of `Locked` until the disk is prepared. The data domain is then automatically attached to the data center.

include::ref_Storage_link.adoc[]
