[[managing_record_attributes]]
== Managing Record Attributes

You can specify any attribute via the *URI* or *CMDB* class instance. If neither exists, the value is determined from the {product-title} *VM* or *miq_provision* objects.

The attributes can be reduced or extended as required by amending the Ruby methods.

[NOTE]
====
Some attributes are not free-text (variable) fields, that is, they must be specific values. For example, the `vendor` value must already exist in the ServiceNow Vendor table beforehand.
====

[[create-and-update-(_patch)-record]]
=== Create and Update (_patch) Record
You can use the following attributes when creating and/or updating a record.

[[attribute]]
==== Attribute

[width="40%"]
|====
|Attribute |Value
|virtual |Boolean true or false, set to true.
|name VMs |Virtual infrastructure name.
|short_description |{product-title} virtual machine GUID.
|host_name |The virtual machine's operating system hostname.
|cpu_count |The virtual machine's CPU count.
|ram |The virtual machine's memory.
|vendor |The virtual machine's hardware vendor (provider).
|sys_id footnoteref:[a, sys_id attribute is not required during `create`. Its value is returned from the `create` request and the {product-title} object custom attribute *servicenow_sys_id* is created and updated.] |ServiceNow record unique system ID.
|====

[[get-and-delete-record]]
=== Get and Delete Record

You can use the following attribute for getting or deleting a record.

[width=100%]
|====
| Attribute | Value
| sys_id    | ServiceNow record unique system ID.
|====

[[get-all-records]]
=== Get All Records

There are no attributes required to get all records. This method gets all records in the specified *ServiceNow table* and writes their attributes to `automation.log`.



