[[vm-management]]
== Vm Management

Management of Virtual Machines adds support of the following actions:

[cols="<,<",options="header",]
|=====================
| Action | Description
| start | Starts a VM
| stop | Stops a VM
| suspend | Suspends a VM
| scan | Scans a VM (Perform SmartState Analysis)
| set_owner | Sets the owner of a VM
| add_event | Adding an Event to a VM
| add_lifecycle_event | Add a Lifecycle Event to a VM
| delete | Deletes a VM in the Appliance
|=====================

* link:#targeting-vms[Targeting VMs]
* link:#querying-vms[Querying VMs]
* link:#start-vm[Starting a VM]
* link:#stop-vm[Stopping a VM]
* link:#suspend-vm[Suspending a VM]
* link:#scan-vm[Scanning a VM]
* link:#set-owner-vm[Setting Owner of a VM]
* link:#add-event-vm[Adding an Event to a VM]
* link:#add-lifecycle-event-vm[Adding a Lifecycle Event to a VM]
* link:#delete-vm[Deleting a VM]

[[targeting-vms]]
=== Targeting VMs

These actions can be triggered on individual vm resources:

[source,data]
----
/api/vms/:id
----

As simply as POSTing the following action to a VM.

[source,json]
----
{
  "action" : "start"
}
----


Requests can also be made on multiple vms by targetting the primary collection:

[source,data]
----
/api/vms
----

[source,json]
----
{
  "action" : "start",
  "resources" : [
    { "href" : "http://localhost:3000/api/vms/11" },
    { "href" : "http://localhost:3000/api/vms/12" },
    ...
  ]
}
----

[[querying-vms]]
=== Querying VMs

Virtual Machines are queried via the primary collection URL:

[source,data]
----
/api/vms
----

Filtering, sorting and paging as mentioned on the
link:../api/query.html[Querying] page.

When querying vms, expanding the resources themselves
as well as the following subcollections:

|======================
| accounts
| software
|======================

For example:

----
GET /api/vms?expand=resources,accounts,software
----

Or querying and individual vm

----
GET /api/vms/:id?expand=accounts,software
----

[[start-vm]]
=== Starting a VM

[source,json]
----
{
  "action" : "start"
}
----

[[stop-vm]]
=== Stopping a VM

[source,json]
----
{
  "action" : "stop"
}
----

[[suspend-vm]]
=== Suspending a VM

[source,json]
----
{
  "action" : "suspend"
}
----

[[scan-vm]]
=== Scanning a VM

[source,json]
----
{
  "action" : "scan"
}
----

[[set-owner-vm]]
=== Setting Owner of a VM

[source,json]
----
{
  "action" : "set_owner",
  "resource" : {
    "owner" : "admin"
  }
}
----

[[add-event-vm]]
=== Adding an Event to a VM

[source,json]
----
{
  "action" : "add_event",
  "resource" : {
    "event_type" : "...",
    "event_message" : "...",
    "event_time" : "UTC Time"
  }
}
----

NOTE: event_time above is optional. If skipped, current time will be used.

[[add-lifecycle-event-vm]]
=== Adding a Lifecycle Event to a VM

[source,json]
----
{
  "action" : "add_lifecycle_event",
  "resource" : {
    "event" : "...",
    "status" : "...",
    "message" : "...",
    "created_by" : "..."
  }
}
----

[[delete-vm]]
=== Deleting a VM

[source,json]
----
{
  "action" : "delete"
}
----

Or simply doing the following:

----
DELETE /api/vms/:id
----

Additional VM Management examples can be found on the main REST API Examples section.

