pressgang_website_callback([
	{"topicId":44419,"target":"Add_Event","title":"Add Event","newSince":""},
	{"topicId":44421,"target":"Add_a_Lifecycle_Event_to_a_Virtual_Machine","title":"Add a Lifecycle Event to a Virtual Machine","newSince":""},
	{"topicId":44422,"target":"Adding_a_Sample_Service_Catalog","title":"Adding a Sample Service Catalog","newSince":""},
	{"topicId":44423,"target":"Adding_Multiple_Service_Catalogs","title":"Adding Multiple Service Catalogs","newSince":""},
	{"topicId":44424,"target":"Assign_Service_Templates_to_Service_Catalogs","title":"Assign Service Templates to Service Catalogs","newSince":""},
	{"topicId":44425,"target":"Assign_Tags_to_a_Service","title":"Assign Tags to a Service","newSince":""},
	{"topicId":30346,"target":"REST_API_Entry_Point","title":"REST API Entry Point","newSince":""},
	{"topicId":44426,"target":"Assign_a_Tag_by_Reference_to_a_Service","title":"Assign a Tag by Reference to a Service","newSince":""},
	{"topicId":30347,"target":"Supported_Content_Types","title":"Supported Content Types","newSince":""},
	{"topicId":44427,"target":"Assign_a_Tag_by_Name_to_a_Service","title":"Assign a Tag by Name to a Service","newSince":""},
	{"topicId":30348,"target":"URL_Paths","title":"URL Paths","newSince":""},
	{"topicId":44428,"target":"Assign_Tags_to_a_Service_Template","title":"Assign Tags to a Service Template","newSince":""},
	{"topicId":30349,"target":"Methods_and_related_URLs","title":"Methods and related URLs","newSince":""},
	{"topicId":44429,"target":"Trigger_a_Single_Automation_Request","title":"Trigger a Single Automation Request","newSince":""},
	{"topicId":30350,"target":"Updating_Resources","title":"Updating Resources","newSince":""},
	{"topicId":44430,"target":"Trigger_Multiple_Automation_Requests","title":"Trigger Multiple Automation Requests","newSince":""},
	{"topicId":30351,"target":"Return_Codes","title":"Return Codes","newSince":""},
	{"topicId":41231,"target":"Authentication11","title":"Authentication","newSince":""},
	{"topicId":44431,"target":"Create_a_Provider","title":"Create a Provider","newSince":""},
	{"topicId":30352,"target":"CRUD_Examples","title":"CRUD Examples","newSince":""},
	{"topicId":41232,"target":"HTTP_Headers","title":"HTTP Headers","newSince":""},
	{"topicId":44432,"target":"Create_a_Provider_with_Compound_Credentials","title":"Create a Provider with Compound Credentials","newSince":""},
	{"topicId":30353,"target":"sect-Authentication","title":"Authentication","newSince":""},
	{"topicId":44433,"target":"Delete_a_Provider","title":"Delete a Provider","newSince":""},
	{"topicId":30354,"target":"Using_Basic_Authentication","title":"Using Basic Authentication","newSince":""},
	{"topicId":44434,"target":"Querying_a_Delete_Task","title":"Querying a Delete Task","newSince":""},
	{"topicId":30355,"target":"Using_Authentication_Tokens","title":"Using Authentication Tokens","newSince":""},
	{"topicId":44435,"target":"Deleting_Multiple_Providers","title":"Deleting Multiple Providers","newSince":""},
	{"topicId":30356,"target":"sect-JSON_Specification","title":"JSON Specification","newSince":""},
	{"topicId":44436,"target":"Delete_Multiple_Service_Catalogs","title":"Delete Multiple Service Catalogs","newSince":""},
	{"topicId":30357,"target":"Basic_types","title":"Basic types","newSince":""},
	{"topicId":44437,"target":"Delete_Services","title":"Delete Services","newSince":""},
	{"topicId":30358,"target":"Common_Attributes_and_Actions","title":"Common Attributes and Actions","newSince":""},
	{"topicId":41238,"target":"Listing_and_Querying_Collections_and_Sub-Collections","title":"Listing and Querying Collections and Sub-Collections","newSince":""},
	{"topicId":44438,"target":"Delete_Multiple_Service_Templates","title":"Delete Multiple Service Templates","newSince":""},
	{"topicId":30359,"target":"Collections4","title":"Collections","newSince":""},
	{"topicId":41239,"target":"Collection_Queries","title":"Collection Queries","newSince":""},
	{"topicId":44439,"target":"Delete_Virtual_Machines","title":"Delete Virtual Machines","newSince":""},
	{"topicId":40984,"target":"Modifying_Resource_Attributes","title":"Modifying Resource Attributes","newSince":""},
	{"topicId":30360,"target":"Actions4","title":"Action Specification","newSince":""},
	{"topicId":41240,"target":"Sub-Collection_Queries","title":"Sub-Collection Queries","newSince":""},
	{"topicId":44440,"target":"Edit_a_Service","title":"Edit a Service","newSince":""},
	{"topicId":30361,"target":"Forms1","title":"Forms","newSince":""},
	{"topicId":41241,"target":"Available_Actions","title":"Available Actions","newSince":""},
	{"topicId":44441,"target":"Edit_a_Service_Catalog","title":"Edit a Service Catalog","newSince":""},
	{"topicId":30362,"target":"sect-Query_Specification","title":"Query Specification","newSince":""},
	{"topicId":44442,"target":"Edit_Multiple_Service_Catalogs","title":"Edit Multiple Service Catalogs","newSince":""},
	{"topicId":30363,"target":"Control_Attributes","title":"Control Attributes","newSince":""},
	{"topicId":44443,"target":"Edit_Multiple_Services","title":"Edit Multiple Services","newSince":""},
	{"topicId":30364,"target":"Filtering","title":"Filtering","newSince":""},
	{"topicId":44444,"target":"Edit_a_Service_Template","title":"Edit a Service Template","newSince":""},
	{"topicId":30365,"target":"Expanding_Collections1","title":"Expanding Collections","newSince":""},
	{"topicId":44445,"target":"Edit_Multiple_Service_Templates","title":"Edit Multiple Service Templates","newSince":""},
	{"topicId":44446,"target":"Edit_a_Service_via_a_PATCH_Request","title":"Edit a Service via a PATCH Request","newSince":""},
	{"topicId":44447,"target":"Edit_a_Service_via_a_PUT_Request","title":"Edit a Service via a PUT Request","newSince":""},
	{"topicId":44448,"target":"Order_a_Service_from_a_Service_Catalog","title":"Order a Service from a Service Catalog","newSince":""},
	{"topicId":44449,"target":"Order_Multiple_Services_from_a_Service_Catalog","title":"Order Multiple Services from a Service Catalog","newSince":""},
	{"topicId":44450,"target":"Paging_Queries","title":"Paging Queries","newSince":""},
	{"topicId":44453,"target":"Queries","title":"Queries","newSince":""},
	{"topicId":44454,"target":"Refresh_a_Provider","title":"Refresh a Provider","newSince":""},
	{"topicId":44455,"target":"Retire_a_Service","title":"Retire a Service","newSince":""},
	{"topicId":44456,"target":"Retire_Multiple_Services","title":"Retire Multiple Services","newSince":""},
	{"topicId":44457,"target":"Scan_a_Virtual_Machine","title":"Scan a Virtual Machine","newSince":""},
	{"topicId":44458,"target":"Set_the_Owner_of_a_Virtual_Machine","title":"Set the Owner of a Virtual Machine","newSince":""},
	{"topicId":44459,"target":"Start_a_Virtual_Machine","title":"Start a Virtual Machine","newSince":""},
	{"topicId":44460,"target":"Stop_a_Virtual_Machine","title":"Stop a Virtual Machine","newSince":""},
	{"topicId":44461,"target":"Suspend_a_Virtual_Machine","title":"Suspend a Virtual Machine","newSince":""},
	{"topicId":44462,"target":"Unassign_Service_Templates_from_a_Service_Catalog","title":"Unassign Service Templates from a Service Catalog","newSince":""},
	{"topicId":44463,"target":"Unassign_Tags","title":"Unassign Tags","newSince":""},
	{"topicId":44464,"target":"Unassign_Tags_from_a_Service_Template","title":"Unassign Tags from a Service Template","newSince":""},
	{"topicId":44465,"target":"Update_a_Provider","title":"Update a Provider","newSince":""},
	{"topicId":44466,"target":"chap-Examples","title":"Examples","newSince":""},
	{"topicId":44467,"target":"sect-General_Queries","title":"General Queries","newSince":""},
	{"topicId":44468,"target":"sect-Events","title":"Events","newSince":""},
	{"topicId":44469,"target":"sect-Service_Catalogs","title":"Service Catalogs","newSince":""},
	{"topicId":44470,"target":"sect-Tags","title":"Tags","newSince":""},
	{"topicId":44471,"target":"sect-Automation_Requests","title":"Automation Requests","newSince":""},
	{"topicId":44472,"target":"sect-Providers","title":"Providers","newSince":""},
	{"topicId":44473,"target":"sect-Services","title":"Services","newSince":""},
	{"topicId":44474,"target":"sect-Virtual_Machines","title":"Virtual Machines","newSince":""},
	{"topicId":42938,"target":"Author_Group","title":"Author Group","newSince":""},
	{"topicId":44475,"target":"sect-Service_Templates","title":"Service Templates","newSince":""},
	{"topicId":44478,"target":"Trigger_a_Single_Provisioning_Request","title":"Trigger a Single Provisioning Request","newSince":""},
	{"topicId":44479,"target":"Trigger_Multipe_Provisioning_Requests","title":"Trigger Multipe Provisioning Requests","newSince":""},
	{"topicId":44480,"target":"sect-Provisioning_Requests","title":"Provisioning Requests","newSince":""},
	{"topicId":42944,"target":"appe-Revision_History","title":"Revision History","newSince":""},
	{"topicId":30421,"target":"Abstract","title":"Abstract","newSince":""}], 23040, "Red Hat CloudForms", "Red Hat CloudForms REST API", "3.2");