
[[manageiq-rest-api-version-history]]
== Version History

[cols="1,1,1,5",options="header"]
|=======================================================================
|API Version |Entry Points |Published |Description
|*3.0.0* |/api, /api/v3.0.0 |January 2018 |
CRUD of Custom Button Sets,
CRUD of Custom Buttons,
Support Automate Workspaces,
Support Service Dialog query parameters,
Dialog Field Refresh Enhancement,
Updating request tasks,
Support additional VM decorators,
Return the full dialog upon Service Dialog creates and edits,
Support add_providers_vms action on Services,
Deleting Tasks,
Support Event Streams,
Support set_current_group for Users,
Support Custom Attributes on Services and Instances,
Deprecated Orchestration Template classes,
Return picture href for generic object subcollections,
Return image_href and extensions with Pictures,
Support Security groups,
Creating Providers require credentials,
CRUD for Generic Object Definitions,
CRUD for Generic Objects,
VMs Subcollection for Providers,
Querying Container Projects,
Removed Arbitration Profiles, Rules and Settings,
Flavor Management,
Management of Physical Servers,
Support Guest Devices,
Support Metrics Rollups,
Querying by multiple tags,
Querying Floating IPs,
Query and Delete Network Routers,
Support set_miq_server action on VMs,
Querying Cloud Subnets,
Enabled paging by default,
Delete Cloud Volumes,
Support Configuration Script Payload subcollection,
Removed Blueprint support,
Return hrefs on create,
Enable custom actions for several collections,
Support DELETE method for Custom Attributes,
Support multi-manager Provider refreshes,
Refreshing Authentications,
Refreshing Configuration Script Sources,
Enable edits for Automation and Provision Requests,
Assigning and Unassining Policies from Policy Profiles 
|*2.4.0* |/api, /api/v2.4.0 |June 2017 | CRUD on actions,
Creating and accessing alert actions of alert resources,
CRUD on Alert Definitions,
Querying Alerts,
CRUD on Authentications,
CRUD on Conditions,
Querying Cloud Volumes,
Querying Configuration Script Payloads,
Creating and querying Authentications of Configuration Script Payloads,
CRUD on Configuration Script Sources,
Querying Load Balancers,
Copying Orchestration Templates,
CRUD on Policies,
Accessing Load Balancers of Providers,
Importing VMs in Providers,
Querying Regions,
CRUD and Copy of Service Dialogs,
Copying Service Orders,
Accessing Orchestration Stacks of Services,
Bulk assignment of Tags on Services,
Adding and Removing Resources of Services,
Adding and Removing Approvers to Service Requests,
CRUD of Service Templates,
Editing Vms,
Creating, Querying, Reverting and Deleting Snapshots of Vms,
Bulk assignment of Tags on Vms,
Creating, Querying and Deleting Snapshots of Instances
|*2.3.0* |/api, /api/v2.3.0 |December 2016 |Automate Collection,
Automate Domains Collection, Automate Domain refresh_from_source,
Collection OPTIONS and metadata,
Service Power Operations,
Picture Create action,
Delete Service Dialogs,
Bulk Queries,
CRUD on Notifications,
Blueprint Collection, CRUD, publishing, and Tagging,
Custom Attributes on Providers,
Additional Server information provided in API entry point,
CRUD on Arbitration Profiles,
CRUD on Arbitration Rules,
CRUD on Arbitration Settings,
Queries of Virtual Templates,
Cloud Networks subcollection for Providers,
Service Create action,
CRUD on Orchestration Templates
|*2.2.0* |/api, /api/v2.2.0 |June 2016 |CRUD on Groups,
CRUD on Users,
Updating a Host password,
Service Reconfigure action,
Additional Vm collection actions,
Instance collection actions,
Approve/Deny provision and automation requests,
Delete one's own authentication token,
Filtering enhancements to support virtual attributes,
Querying enhancements to support case insensitive sorting,
CRUD on Tenant quotas,
Exposing read-only subset of Settings,
Shopping Carts
|*2.1.0* |/api, /api/v2.1.0 |November 2015 |CRUD on Tenants,
CRUD on Categories and Tags,
CRUD on User Roles,
CRUD on Chargeback Rates,
Tagging Tenants, Changing user password,
Querying reports, importing and running reports,
Querying service dialogs of service template and services,
Querying pictures of services, service requests and service templates,
Custom buttons and dialogs support on services and service templates,
Ability to trigger custom actions on services,
Setting ownership on Services, Vms and Templates,
User group authorization,
Additional Primary Collections: Features, Roles, Tenants,
Service dialogs, Provision dialogs,
Reports, Chargebacks, Rates, Categories, Tags
|*2.0.0* |/api, /api/v2.0.0 |May 2015 |Parity with SOAP API,
Support for Providers CRUD & Refresh action,
VM Control Management,
VM Custom Attributes,
Improved Tagging queries,
Tag Management,
Policy and Policy Profile Management,
Improved Action Result responses,
Expanded Primary collections
|*1.1* |/api/v1.1 |October 2014 |CVE-2014-7814 Fix,
sqlfilter replaced with new filter[] parameter
|*1.0* |/api/v1.0 |August 2014 |Foundation,
Collections, Resources and Subcollections,
Querying, Filtering, Paging, and Sorting,
Tagging,
Service Catalog Management,
Service Ordering,
Provision Requests,
Automation Requests
|=======================================================================

