
[[manageiq-rest-api-version-history]]
== Version History

[cols="1,1,1,3",options="header"]
|=======================================================================
|API Version |Entrypoints |Published |Description
|*2.3.0* |/api, /api/v2.3.0 |December 2016 |Automate Collection,
Automate Domains Collection, Automate Domain refresh_from_source,
Collection OPTIONS and metadata,
Service Power Operations,
Picture Create action,
Delete Service Dialogs,
Bulk Queries,
CRUD on Notifications,
Blueprint Collection, CRUD, publishing, and Tagging,
Custom Attributes on Providers,
Additional Server information provided in API Entrypoint,
CRUD on Arbitration Profiles,
CRUD on Arbitration Rules,
CRUD on Arbitration Settings,
Queries of Virtual Templates,
Cloud Networks subcollection for Providers,
Service Create action,
CRUD on Orchestration Templates
|*2.2.0* |/api, /api/v2.2.0 |June 2016 |CRUD on Groups,
CRUD on Users,
Updating a Host password,
Service Reconfigure action,
Additional Vm collection actions,
Instance collection actions,
Approve/Deny provision and automation requests,
Delete one's own authentication token,
Filtering enhancements to support virtual attributes,
Querying enhancements to support case insensitive sorting,
CRUD on Tenant quotas,
Exposing read-only subset of Settings,
Shopping Carts
|*2.1.0* |/api, /api/v2.1.0 |November 2015 |CRUD on Tenants,
CRUD on Categories and Tags,
CRUD on User Roles,
CRUD on Chargeback Rates,
Tagging Tenants, Changing user password,
Querying reports, importing and running reports,
Querying service dialogs of service template and services,
Querying pictures of services, service requests and service templates,
Custom buttons and dialogs support on services and service templates,
Ability to trigger custom actions on services,
Setting ownership on Services, Vms and Templates,
User group authorization,
Additional Primary Collections: Features, Roles, Tenants,
Service dialogs, Provision dialogs,
Reports, Chargebacks, Rates, Categories, Tags
|*2.0.0* |/api, /api/v2.0.0 |May 2015 |Parity with SOAP API,
Support for Providers CRUD & Refresh action,
VM Control Management,
VM Custom Attributes,
Improved Tagging queries,
Tag Management,
Policy and Policy Profile Management,
Improved Action Result responses,
Expanded Primary collections
|*1.1* |/api/v1.1 |October 2014 |CVE-2014-7814 Fix,
sqlfilter replaced with new filter[] parameter
|*1.0* |/api/v1.0 |August 2014 |Foundation,
Collections, Resources and Subcollections,
Querying, Filtering, Paging, and Sorting,
Tagging,
Service Catalog Management,
Service Ordering,
Provision Requests,
Automation Requests
|=======================================================================

