// Policies
// --------

include::common/policies-intro.adoc[]

include::Note_OpenSCAP_XREF.adoc[]

[[control-policies]]
=== Control Policies

A control policy is a combination of an event, a condition, and an
action. This combination provides management capabilities in your
virtual environment.

* An event is a trigger to check a condition.
* A condition is a test triggered by an event.
* An action is an execution that occurs if a condition is met.

include::To_create_a_Control_Policy.adoc[]

include::Editing_Basic_Info_Scope_and_Notes_for_a_Policy.adoc[]

include::Copying_a_Policy.adoc[]

include::Deleting_a_Policy.adoc[]

include::Creating_a_new_Policy_Condition.adoc[]

include::Editing_Policy_Condition_Assignments.adoc[]

include::Editing_Policy_Event_Assignments.adoc[]

include::To_assign_an_Action_to_an_Event.adoc[]

[[compliance-policies]]
=== Compliance Policies

Compliance policies are specifically designed to secure your environment
by checking conditions that you create. These conditions can include the
same conditions that you would use in a control policy, and most of the
procedures are the same. However, a compliance policy automatically
assigns the mark as a compliant action when the entity type (virtual machine or host, for example) to which the policy applies
passes all of the conditions. If any of the conditions are not met, then
the virtual machine or host is marked as non-compliant. The compliance
status is shown in the summary screen for the entity type
and on the compare and drift screens.

include::To_create_a_compliance_Policy.adoc[]

include::To_create_a_Condition_to_check_file_contents_of_a_host.adoc[]

[[checking-for-compliance]]
==== Checking for Compliance

After you have created your compliance policies and assigned them to a
policy profile, you can check compliance in two ways. You can either
schedule the compliance check or perform the check directly from the
summary screen.

The compliance check runs all compliance policies that are assigned to
the host or virtual machine. If the item fails any of the checks, it is
marked as non-compliant in the item's summary screen.

[NOTE]
====
To schedule, you must have `EvmRole-administrator` access to the
{product-title} server.
====

include::To_schedule_a_Compliance_check.adoc[]

include::To_check_a_Virtual_Machine_for_Compliance_from_the_Summary_Screen.adoc[]

include::To_check_a_Host_for_Compliance_from_the_Summary_Screen.adoc[]

include::To_check_a_Replicator_for_Compliance_from_the_Summary_Screen.adoc[]

include::To_check_a_Pod_for_Compliance_from_the_Summary_Screen.adoc[]

include::To_check_a_Container_Node_for_Compliance_from_the_Summary_Screen.adoc[]

include::To_check_a_Container_Image_for_Compliance_from_the_Summary_Screen.adoc[]



