//Policy Profiles
//---------------

Policy profiles are groups of policies that you can assign wholesale to virtual machines, providers, clusters, hosts, resource pools, replicators, pods, container nodes, and container images. Policy profiles provide a framework for easily managing and assigning different levels of security, across various types of cloud resources.

include::Note_OpenSCAP_XREF.adoc[]

include::Creating_Policy_Profiles.adoc[]

include::Deleting_a_Policy_Profile.adoc[]

[[simulating-policy]]
=== Simulating Policy

Before assigning a policy profile to a virtual machine, use the
{product-title} controls policy simulation feature to
determine if a virtual machine passes a policy profile.

include::To_simulate_Policy_Profiles_on_Virtual_Machines.adoc[]

[[profile-assign]]
=== Assigning Policy Profiles

After creating your policy profiles, you are ready to evaluate and
assign them.

* Assign a policy profile to a virtual machine to apply the policy profile to a specific virtual machine, independent of its related host, provider, or repository.
* Assign a policy profile to a provider to apply the policy profile to all virtual machines, hosts, replicators, pods, container nodes or container images registered to that provider.
* Assign a policy profile to a replicator to apply the policy profile to that specific replicator.
* Assign a policy profile to a pod to apply the policy profile to that specific pod.
* Assign a policy profile to a container node to apply the policy profile to that specific node.
* Assign a policy profile to a container image to apply the policy profile to that specific image.
* Assign a policy profile to a cluster to apply the policy profile to all virtual machines or hosts assigned to that cluster.
* Assign a VM policy profile to a host to apply the policy profile to that specific host or all virtual machines registered to that host.
* Assign a VM policy profile to a resource pool to apply the policy profile to all virtual machines or hosts assigned to that resource pool.

include::Assigning_Policy_Profiles_to_an_Infrastructure_Provider.adoc[]

include::Removing_Policy_Profiles_from_an_Infrastructure_Provider.adoc[]

include::To_assign_Policy_Profiles_to_a_Cluster.adoc[]

include::To_remove_Policy_Profiles_from_a_Cluster.adoc[]

include::To_assign_Policy_Profiles_to_a_Host.adoc[]

include::To_remove_Policy_Profiles_from_a_Host.adoc[]

include::To_assign_Policy_Profiles_to_a_Virtual_Machine.adoc[]

include::To_remove_Policy_Profiles_from_a_Virtual_Machine.adoc[]

include::To_assign_Policy_Profiles_to_a_Resource_Pool.adoc[]

include::To_remove_Policy_Profiles_from_a_Resource_Pool.adoc[]

include::Assigning_Policy_Profiles_to_a_Cloud_Provider.adoc[]

include::Removing_Policy_Profiles_from_a_Cloud_Provider.adoc[]

include::Assigning_Policy_Profiles_to_a_Network_Provider.adoc[]

include::Removing_Policy_Profiles_from_a_Network_Provider.adoc[]

include::Assigning_Policy_Profiles_to_a_Container_Provider.adoc[]

include::Removing_Policy_Profiles_from_a_Container_Provider.adoc[]

include::Assigning_Policy_Profiles_to_a_Replicator.adoc[]

include::Removing_Policy_Profiles_from_a_Replicator.adoc[]

include::Assigning_Policy_Profiles_to_a_Pod.adoc[]

include::Removing_Policy_Profiles_from_a_Pod.adoc[]

include::Assigning_Policy_Profiles_to_a_Container_Node.adoc[]

include::Removing_Policy_Profiles_from_a_Container_Node.adoc[]

include::Assigning_Policy_Profiles_to_a_Container_Image.adoc[]

include::Removing_Policy_Profiles_from_a_Container_Image.adoc[]

include::Assigning_Policy_Profiles_to_an_Instance.adoc[]

include::Removing_Policy_Profiles_from_an_Instance.adoc[]

include::To_disable_a_Policy.adoc[]

include::To_view_Policy_Simulation_RSOP.adoc[]
