By default, the Telemetry service does not store events emitted by other services in a Red Hat OpenStack Platform environment. The following procedure outlines how to enable the Telemetry service on your OpenStack cloud provider to store such events. This ensures that events are exposed to {product-title} when a Red Hat OpenStack Platform environment is added as a cloud provider.

// . On the director node, edit _undercloud.conf_, and set _store_events_ to _true_.
. Log in to the undercloud host.
. Create an environment file called _ceilometer.yaml_, and add the following contents:
+
------
parameter_defaults:
  CeilometerStoreEvents: true
------
. Please see the below *NOTE*.

If your OpenStack cloud provider was not deployed through the undercloud, you can also set this manually. To do so:

. Log in to your Controller node.
. Edit _/etc/ceilometer/ceilometer.conf_, and specify the following option:
+
------
store_events = True
------

[NOTE]
====
Passing the newly created environment file to the overcloud deployment is environment specific and requires executing commands in particular order depending on use of variables. For further information please see link:https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/11/html/director_installation_and_usage/[_Director Installation and Usage_] in the Red Hat OpenStack Platform documentation.
====
