[[installing-cloudforms]]
== Installing {product-title}

Installing {product-title} on Red Hat Virtualization consists of the following steps:

. Downloading the appliance for your environment as a virtual machine image template.
. Uploading the appliance image to the Red Hat Virtualization data storage domain.
. Creating a virtual machine based on the appliance.

After you have completed all the procedures in this chapter, you will have a working environment which you can further configure and customize.

.Requirements

Uploading the {product-title_short} appliance file to Red Hat Virtualization requires:

* 44 GB of storage space on both the export domain and the local partition where `/tmp` resides, as the `OVF` archive is locally expanded into that directory.
* 12 GB RAM.
* 4 vCPUs.

[NOTE]
====
See https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.2/html/virtual_machine_management_guide/chap-installing_linux_virtual_machines#Creating_a_virtual_machine_linux_vm[Creating a Virtual Machine] in the Red Hat Virtualization _Virtual Machine Management Guide_ for information on specifying memory for a new virtual machine.  
====

[[obtaining-the-appliance]]
=== Obtaining the Appliance

ifdef::miq[]
To obtain a copy of the appliance from the ManageIQ homepage:

. In a browser, navigate to link:https://www.manageiq.org/download[].
. Select *Red Hat Virtualization* from the *--Choose your platform--* list.
. Select *Stable* from the *--Choose a release--* list.
. Follow the instructions to download the appliance.
endif::miq[]

ifdef::cfme[]
To obtain a copy of the appliance from the Customer Portal:

. Log in to the Red Hat Customer Portal at link:https://access.redhat.com[access.redhat.com] using your customer account details.
. Click *Downloads* in the menu bar.
. Click *A-Z* to sort the product downloads alphabetically.
. Click *Red Hat CloudForms* to access the product download page.
. Select *Red Hat CloudForms Beta* from the *Product Variant:* dropdown list.
. From the list of installers and images, click the *Download Now* link for the latest version of the *CFME Red Hat Virtual Appliance (qcow)*.
endif::cfme[]

After the image completes downloading, you are ready to upload the CloudForms appliance to your Red Hat Virtualization environment and create a virtual machine.

[[uploading-the-appliance-on-red-hat-virtualization]]
=== Uploading the Appliance to Red Hat Virtualization

Upload the `qcow2` appliance image to your Red Hat Virtualization data storage domain from the Red Hat Virtualization Administration Portal.

//After uploading the image, create a disk and attach it to a virtual machine.

.Prerequisites:

* You must configure the Image I/O Proxy when running `engine-setup`. See https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.2/html/installation_guide/configuring_the_red_hat_virtualization_manager[Configuring the Red Hat Virtualization Manager] in the  _Red Hat Virtualization Installation Guide_ for more information.
* Internet Explorer 10, Firefox 35, or Chrome 13 or greater is required to perform this upload procedure. Previous browser versions do not support the required HTML5 APIs.
* You must import the required certificate authority into the web browser used to access the Administration Portal.

[NOTE]
====
To import the certificate authority, browse to `https://<engine_address>/ovirt-engine/services/pki-resource?resource=ca-certificate&format=X509-PEM-CA` and select all the trust settings. Refer to the instructions to install the certificate authority in https://access.redhat.com/solutions/95103[Firefox], https://access.redhat.com/solutions/17864[Internet Explorer], or https://access.redhat.com/solutions/1168383[Google Chrome].
====

To upload the appliance:

. Log in to the Red Hat Virtualization Administration Portal.
. Click menu:Storage[Disks].
. Select menu:Upload[Start].
. Click *Choose File*, and select the appliance image to upload.
. Under *Disk Options*, enter an *Alias* for the image.
. (Optional) Edit other fields in *Disk Options* if desired.
. Click *OK*.

A progress bar in the *Status* column indicates the status of the upload. You can also pause, cancel, or resume uploads from the *Upload* menu.

The status shows *OK* when the image has completed uploading.

[NOTE]
====
See the https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.2/html/administration_guide/sect-storage_tasks#Uploading_Images_to_a_Data_Storage_Domain[Uploading Images to a Data Storage Domain] in the _Red Hat Virtualization Administration Guide_ for more information.
====

.Increasing the Upload Timeout Value

. If the upload times out and you see the message, `Reason: timeout due to transfer inactivity`, increase the timeout value:
+
----
# engine-config -s TransferImageClientInactivityTimeoutInSeconds=6000
----
+
. Restart the ovirt-engine service:
+
----
# systemctl restart ovirt-engine
----


[[creating_vm]]
=== Creating a {product-title_short} Virtual Machine

After uploading the appliance to the data domain, create a virtual machine containing the {product-title_short} image and a second disk for the database:

. In menu:Compute[Virtual Machines], click *New* to open the *New Virtual Machine* dialog.
. From the *General* tab, specify a name for the virtual machine and any other details.
. Click *Attach*.
. Select the {product-title_short} appliance you uploaded from the list of images and click *OK*.
. Click the VM to open its details screen, and click the *Disks* tab.
. Click *Edit* to the disk, and check *Bootable* if it is not marked already.
. Click *OK*.
. Add a second disk for the database:
.. Click the *General* tab and click the *Edit* button to edit the virtual machine.
.. Click *+* and *Create* to create a disk for the database (VMDB).
.. Specify a *Size* in GB for the disk that allows sufficient space for your database. Red Hat recommends allocating the virtual machine disk fully at the time of creation. Three main factors affect the size of your database over time:
+
* Virtual Machine Count: the most important factor in the calculation of virtual machine database (VMDB) size over time.
* Host Count: the number of hosts associated with the provider.
* Storage Count: the number of individual storage elements as seen from the perspective of the provider or host. It is not the total number of virtual disks for all virtual machines.
+
ifdef::cfme[]
[NOTE]
====
See https://access.redhat.com/documentation/en-us/red_hat_cloudforms/4.7/html-single/deployment_planning_guide/#database-requirements[Database Requirements] in the _Deployment Planning Guide_ for information on calculating disk size for your database.
====
endif::cfme[]
ifdef::miq[]
[NOTE]
====
See "Database Requirements" in the _Deployment Planning Guide_ for size considerations.
====
endif::miq[]
+
.. Set the *Allocation Policy* to `Preallocated` (thick provisioning) for best performance.
.. Specify any other values as desired.
. Click *OK* to create the disk and return to the *New Virtual Machine* window.
. Add a network interface to the virtual machine by selecting a vNIC profile from the *nic1* list.
. Click *OK* to save your changes to the virtual machine.
. Start the {product-title_short} appliance by clicking the *Run* button.

Your Red Hat Virtualization environment now contains a running {product-title_short} appliance.

Next, configure the database on the disk you created by following the steps in xref:configuring-an-internal-database[].


