[[Configuring-cloudforms]]
== Configuring {product-title}

Although the {product-title} appliance comes configured to be integrated immediately into your environment, you can make some changes to its configuration.

[[changing-configuration-settings]]
=== Changing Configuration Settings

The procedure describes how to make changes to the configuration settings on the {product-title} appliance.

. Log in to the appliance using the SSH key.
. Enter the `sudo appliance_console` command. The CloudForms Management Engine appliance summary screen displays.
. Press `Enter` to manually configure settings.
. Press the number for the item you want to change, and press `Enter`. The options for your selection are displayed.
. Follow the prompts to make the changes.
. Press `Enter` to accept a setting where applicable.

[NOTE]
====
The {product-title} appliance console automatically logs out after five minutes of inactivity.
====

[[advanced-configuration-settings]]
=== Advanced Configuration Settings

You can use the following options for advanced configuration of the appliance:

* Use *Set DHCP Network Configuration* to use DHCP to obtain the IP address and network configuration for your {product-title} appliance. The appliance is initially configured as a DHCP client with bridged networking.
* Use *Set Static Network Configuration* if you have a specific IP address and network settings you need to use for the {product-title} appliance.
* Use *Test Network Configuration* to check that name resolution is working correctly.
* Use *Set Hostname* to specify a hostname for the {product-title} appliance.
+
[IMPORTANT]
====
A valid fully qualified hostname for the {product-title} appliance is required for SmartState analysis to work correctly,
====
+
* Use *Set Timezone, Date, and Time* to configure the time zone, date, and time for the {product-title} appliance.
* Use *Restore Database from Backup* to restore the VMDB database from a previous backup.
* Use *Setup Database Region* to create regions for VMDB replication.
* Use *Configure Database* to configure the VMDB database. Use this option to configure the database for the appliance after installing and running it for the first time.
* Use *Extend Temporary Storage* to add temporary storage to the appliance. The appliance formats an unpartitioned disk attached to the appliance host and mounts it at `/var/www/miq_tmp`. The appliance uses this temporary storage directory to perform certain image download functions.
* Use *Configure External Authentication (httpd)* to configure authentication through an IPA server.
* Use *Generate Custom Encryption Key* to regenerate the encryption key used to encode plain text password.
* Use *Harden Appliance Using SCAP Configuration* to apply Security Content Automation Protocol (SCAP) standards to the appliance. You can view these SCAP rules in the `/var/www/miq/lib/appliance_console/config/scap_rules.yml` file.
* Use *Stop Server Processes* to stop all server processes. You may need to do this to perform maintenance.
* Use *Start Server Processes* to start the server. You may need to do this after performing maintenance.
* Use *Restart appliance* to restart the {product-title} appliance. You can either restart the appliance and clear the logs or just restart the appliance.
* Use *Shut Down Appliance* to power down the appliance and exit all processes.
* Use *Summary Information* to go back to the network summary screen for the {product-title} appliance.
* Use *Quit* to leave the {product-title} appliance console.

[[configuring_a_database]]
=== Configuring a Database for {product-title}

{product-title} uses a database to store information about the cloud environment it manages. You must configure a database for the appliance before you can use it to administer your cloud infrastructure. {product-title} provides the following two options for database configuration:

* Configuring an internal PostgreSQL database
* Configuring an external PostgreSQL database

[[configuring-an-internal-database]]
==== Configuring an Internal Database

[IMPORTANT]
====
Before installing an internal database, add a disk to the infrastructure hosting your appliance. See the storage documentation specific to your infrastructure for instructions on how to add a disk. As a storage disk usually cannot be added while a virtual machine is running, Red Hat recommends adding the disk before starting the appliance. {product-title} only supports installing of an internal VMDB on blank disks. The installation will fail if the disks are not blank.
====

. Start the appliance and open a terminal console.
. Log in to the appliance using the SSH key.
. Enter the `sudo appliance_console` command. The {product-title} appliance summary screen displays.
. Press *Enter* to manually configure settings.
. Select *8) Configure Database* from the menu.
. You are prompted to create or fetch an encryption key.
* If this is the first {product-title} appliance, choose *1) Create key*.
* If this is not the first {product-title} appliance, choose *2) Fetch key* from remote machine to fetch the key from the first {product-title} appliance. All {product-title} appliances in a multi-region deployment must use the same key.
. Choose *1) Internal* for the database location.
. Choose a disk for the database. For example:
+
----
1)  /dev/vdb: 20480

Choose disk:
----
+
Enter *1* to choose `/dev/vdb` for the database location.

. When prompted, enter a unique three digit region ID to create a new region. As your deployment grows, you can add more regions in the future to manage multiple appliances.
+
[IMPORTANT]
====
Creating a new region destroys any existing data on the chosen database.
====
+
.  Confirm the configuration when prompted.

{product-title} configures the internal database.

[[configuring-an-external-database]]
==== Configuring an External Database

Based on your setup, you will choose to configure the appliance to use an external PostgreSQL database. For example, we can only have one database in a single region. However, a region can be segmented into multiple zones where each zone provides specific functionality, such as Database, User Interface, Reporting among others. The appliances in these zones must be configured to use an external database.

Note that the `postgresql.conf` file used with {product-title} databases requires specific settings for correct operation. For example, it must correctly reclaim table space, control session timeouts, and format the PostgreSQL server log for improved system support. Due to these requirements, Red Hat recommends that external {product-title} databases use a `postgresql.conf` file based on the standard file used by the {product-title} appliance.

Ensure you configure the settings in the `postgresql.conf` to suit your system. For example, customize the `shared_buffers` setting according to the amount of real storage available in the external system hosting the PostgreSQL instance. In addition, depending on the aggregate number of appliances expected to connect to the PostgreSQL instance, it may be
necessary to alter the `max_connections` setting.

[NOTE]
====
* {product-title} 4.x requires PostgreSQL version 9.4.

* Because the `postgresql.conf` file controls the operation of all databases managed by a single instance of PostgreSQL, do not mix {product-title} databases with other types of databases in a single PostgreSQL instance.
====

. Start the appliance and open a terminal console.
. Log in to the appliance using the SSH key.
. Enter the `sudo appliance_console` command. The {product-title} appliance summary screen displays.
. Press *Enter* to manually configure settings.
. Select *8) Configure Database* from the menu.
. You are prompted to create or fetch a security key.
* If this is the first {product-title} appliance, select the option to create a key.
* If this is not the first {product-title} appliance, select the option to fetch the key from the first {product-title} appliance. All {product-title} appliances in a multi-region deployment must use the same key.
. Choose *2) External* for the database location.
. Enter the database hostname or IP address when prompted.
. Enter the database name or leave blank for the default (`vmdb_production`).
. Enter the database username or leave blank for the default (`root`).
. Enter the chosen database user's password.
. Confirm the configuration if prompted.

{product-title} will then configure the external database.

[[configuring-a-worker-appliance]]
=== Configuring a Worker Appliance

You can use multiple appliances to facilitate horizontal scaling, as well as for dividing up work by roles. Accordingly, configure an appliance to handle work for one or many roles, with workers within the appliance carrying out the duties for which they are configured. You can configure a worker appliance through the terminal. The following steps demonstrate how to join a worker appliance to an appliance that already has a region configured with a database.

. Start the appliance and open a terminal console.
. Log in to the appliance using the SSH key.
. Enter the `sudo appliance_console` command. The {product-title} appliance summary screen displays.
. Press *Enter* to manually configure settings.
. Select *8) Configure Database* from the menu.
. You are prompted to create or fetch a security key. Select the option to fetch the key from the first {product-title} appliance. All {product-title} appliances in a multi-region deployment must use the same key.
. Choose *2) External* for the database location.
. Enter the database hostname or IP address when prompted.
. Enter the database name or leave blank for the default (`vmdb_production`).
. Enter the database username or leave blank for the default (`root`).
. Enter the chosen database user's password.
. Confirm the configuration if prompted.


