[[Overview]]
== Overview

Red Hat CloudForms' integration with ServiceNow enables authentication with an existing ServiceNow database and add/amend items in the ServiceNow database during state machine processing, for example, the VM provision state machine. Note that information in this guide assumes you have credentials and access to a ServiceNow database instance.

The following new namespace and class delivers support for the management of ServiceNow Configuration Management Database (CMDB) records using ServiceNow’s RESTful web service.
-------
/RedHat/Integration/ServiceNow/CMDB
-------

You can manage records in the CMDB_CI_SERVER table, including create, update, and/or delete. The following methods are included:

==== CMDB_CI_SERVER 
[width="50%"]
|=========================================================
|Method |Action |

|create |Create record in specified ServiceNow table. |

|delete |Delete record in specified ServiceNow table. |

|get |Get record from specified ServiceNow table and list its attributes. |

|get_all |Get all records in ServiceNow and list attributes. |

|update |Get specified record, update required attributes and post updated record. |

|update_patch |Post required attributes to specified record. |

+
[Note]
=======
Configuration item (CI) and record are used interchangeably and refer to items in a ServiceNow database table.
=======
+

