[[additional-configuration-vmware]]
== Additional Configuration for Appliances on VMware vSphere

[[installing-vmware-vddk]]
=== Installing VMware VDDK on {product-title_short}

[IMPORTANT]
====
Execution of SmartState Analysis on virtual machines within a VMware environment requires the Virtual Disk Development Kit (VDDK). This version of {product-title_short} supports VDDK versions 6.0, 6.5, and 6.7.
====

To install VMware VDDK:

. Download the required VDDK version (`VMware-vix-disklib-[version].x86_64.tar.gz`) from the VMware website.
+
[NOTE]
=====
* If you do not already have a login ID to VMware, then you will need to create one. At the time of this writing, the file can be found by navigating to menu:Downloads[vSphere]. Select the version from the drop-down list, then click the *Drivers & Tools* tab. Expand *Automation Tools and SDKs*, and click *Go to Downloads* next to the *VMware vSphere Virtual Disk Development Kit* version. Alternatively, find the file by searching for it using the *Search* on the VMware site.

* See VMware documentation for information about their policy concerning backward and forward compatibility for VDDK.
=====
+
. Download and copy the `VMware-vix-disklib-[version].x86_64.tar.gz` file to the `/root` directory of the appliance.
. Start an SSH session into the appliance.
. Extract and install the `VMware-vix-disklib-[version].x86_64.tar.gz` file using the following commands:
+
----
# cd /root
# tar -xvf VMware-vix-disklib-[version].x86_64.tar.gz
# cp vmware-vix-disklib-distrib/ -rf /usr/lib/vmware-vix-disklib/
# ln -s /usr/lib/vmware-vix-disklib/lib64/libvixDiskLib.so /usr/lib/libvixDiskLib.so
# ln -s /usr/lib/vmware-vix-disklib/lib64/libvixDiskLib.so.6 /usr/lib/libvixDiskLib.so.6
----
+
. Run `ldconfig` to instruct {product-title_short} to find the newly installed VDDK library.

+
[NOTE]
====
Use the following command to verify the VDDK files are listed and accessible to the appliance:
----
# ldconfig -p | grep vix
----
====
+

. Restart the {product-title_short} appliance.

The VDDK is now installed on the {product-title_short} appliance. This enables use of the SmartState Analysis server role on the appliance.


[[appliance-tuning-vmware]]
=== Tuning Appliance Performance

By default, the {product-title_short} appliance uses the `tuned` service and its `virtual-guest` profile to optimize performance. In most cases, this profile provides the best performance for the appliance.

However on some VMware setups (for example, with a large vCenter database), the following additional tuning may further improve appliance performance:

* When using the `virtual-guest` profile in `tuned`, edit the `vm.swappiness` setting to `1` in the `tuned.conf` file from the default of `vm.swappiness = 30`.

* Use the `noop` scheduler instead. See the https://kb.vmware.com/s/article/2011861[VMware documentation] for more details on the best scheduler for your environment. See https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/performance_tuning_guide/sect-red_hat_enterprise_linux-performance_tuning_guide-storage_and_file_systems-configuration_tools#sect-Red_Hat_Enterprise_Linux-Performance_Tuning_Guide-Configuration_tools-Setting_the_default_IO_scheduler[Setting the Default I/O Scheduler] in the Red Hat Enterprise Linux _Performance Tuning Guide_ for instructions on changing the default I/O scheduler.







