[[installing-cloudforms]]
== Installing {product-title}

Installing {product-title} consists of the following steps:

. Downloading the appliance for your environment as a virtual machine image template.
. Setting up a virtual machine based on the appliance.
. Configuring the {product-title_short} appliance.

After you have completed all the procedures in this guide, you will have a working environment on which additional customizations and configurations can be performed.

[[obtaining-the-appliance]]
=== Obtaining the appliance

ifdef::miq[]
. In a browser, navigate to link:https://www.manageiq.org/download[].
. Find the table with the relevant type of release.
. Click *VMware vSphere* from the list to download the appliance image.
endif::miq[]

ifdef::cfme[]
. Go to link:https://access.redhat.com[access.redhat.com] and log in to the Red Hat Customer Portal using your customer account details.
. Click *Downloads* in the menu bar.
. Click *A-Z* to sort the product downloads alphabetically.
. Click *Red Hat CloudForms* to access the product download page.
. Select *Red Hat CloudForms Beta* from the *Product Variant:* dropdown list.
. From the list of installers and images, click the *Download Now* link for *CFME VMware Virtual Appliance*.
endif::cfme[]

[[uploading-the-appliance-on-vmware-vsphere]]
=== Uploading the Appliance on VMware vSphere

Uploading the {product-title} appliance file onto VMware vSphere systems has the following requirements:

* 44 GB of space on the chosen vSphere datastore.
* 12 GB RAM.
* 4 VCPUs.
* Administrator access to the vSphere Client.
* Depending on your infrastructure, allow time for the upload.

[NOTE]
====
These are the procedural steps as of the time of writing. For more information, consult the VMware documentation.
====

Use the following procedure to upload the {product-title} appliance OVF template from your local file system using the vSphere Client.

. In the vSphere Client, select menu:File[Deploy OVF Template]. The Deploy OVF Template wizard appears.
. Specify the source location and click *Next*.
* Select *Deploy from File* to browse your file system for the OVF template, for example `manageiq-vsphere-ivanchuk-4.ova`.
* Select *Deploy from URL* to specify a URL to an OVF template located on the internet.
. View the *OVF Template Details* page and click *Next*.
. Select the deployment configuration from the drop-down menu and click *Next*. The option selected typically controls the memory settings, number of CPUs and reservations, and application-level configuration parameters.
. Select the host or cluster on which you want to deploy the OVF template and click *Next*.
. Select the host on which you want to run the run the {product-title} appliance, and click *Next*.
. Navigate to, and select the resource pool where you want to run the {product-title} appliance and click *Next*.
. Select a datastore to store the deployed {product-title} appliance, and click Next. Ensure to select a datastore large enough to accommodate the virtual machine and all of its virtual disk files.
. Select the disk format to store the virtual machine virtual disks, and click *Next*.
* Select *Thin Provisioned* if the storage is allocated on demand as data is written to the virtual disks.
* Select *Thick Provisioned* if all storage is immediately allocated.
. For each network specified in the OVF template, select a network by right-clicking the *Destination Network* column in your infrastructure to set up the network mapping and click *Next*.
. The *IP Allocation* page does not require any configuration changes. Leave the default settings in the *IP Allocation* page and click *Next*.
. Set the user-configurable properties and click *Next*. The properties to enter depend on the selected IP allocation scheme. For example, you are prompted for IP related information for the deployed virtual machines only in the case of a fixed IP allocation scheme.
. Review your settings and click *Finish*.

The progress of the import task appears in the vSphere Client Status panel.








