pressgang_website_callback([
	{"topicId":15363,"target":"Removing_a_Datastore","title":"Removing a Datastore","newSince":""},
	{"topicId":21507,"target":"Viewing_Availability_Zone_Relationships","title":"Viewing Availability Zone Relationships","newSince":""},
	{"topicId":30212,"target":"Abstract","title":"Abstract","newSince":""},
	{"topicId":15365,"target":"Tagging_a_Datastore","title":"Tagging a Datastore","newSince":""},
	{"topicId":15367,"target":"Viewing_Capacity_and_Utilization_Charts_for_a_Datastore","title":"Viewing Capacity and Utilization Charts for a Datastore","newSince":""},
	{"topicId":15371,"target":"sect-Repositories","title":"Repositories","newSince":""},
	{"topicId":15372,"target":"Refreshing_Multiple_Repositories","title":"Refreshing Multiple Repositories","newSince":""},
	{"topicId":15374,"target":"Adding_a_Repository","title":"Adding a Repository","newSince":""},
	{"topicId":15376,"target":"Editing_a_Repository","title":"Editing a Repository","newSince":""},
	{"topicId":42002,"target":"Authenticating_Red_Hat_Enterprise_Virtualization_Hosts","title":"Authenticating Red Hat Enterprise Virtualization Hosts","newSince":""},
	{"topicId":15378,"target":"Removing_Repositories","title":"Removing Repositories","newSince":""},
	{"topicId":15380,"target":"Tagging_Repositories","title":"Tagging Repositories","newSince":""},
	{"topicId":15382,"target":"Reviewing_a_Repository","title":"Viewing a Repository","newSince":""},
	{"topicId":15396,"target":"PXE_Servers","title":"PXE Servers","newSince":""},
	{"topicId":15399,"target":"sect-Capacity_and_Utilization_Collection","title":"Capacity and Utilization Collection","newSince":""},
	{"topicId":15400,"target":"To_assign_the_Capacity_Utilization_Server_Roles","title":"Assigning the Capacity and Utilization Server Roles","newSince":""},
	{"topicId":15401,"target":"Notes_on_Capacity_and_Utilization_Collection_for_RHEVM_3.1","title":"Data Collection for Red Hat Enterprise Virtualization 3.1 and 3.2","newSince":""},
	{"topicId":15402,"target":"sect-Data_Collected","title":"Data Collected","newSince":""},
	{"topicId":15403,"target":"Capacity_and_Utilization_Charts_for_Host_Clusters_and_Virtual_Machines","title":"Capacity and Utilization Charts for Host, Clusters, and Virtual Machines","newSince":""},
	{"topicId":15404,"target":"Capacity_and_Utilization_Charts_for_Datastores","title":"Capacity and Utilization Charts for Datastores","newSince":""},
	{"topicId":15412,"target":"sect-Chart_Features","title":"Chart Features","newSince":""},
	{"topicId":15413,"target":"To_zoom_into_a_chart","title":"Zooming into a Chart","newSince":""},
	{"topicId":15414,"target":"To_drill_into_chart_data","title":"Drilling into Chart Data","newSince":""},
	{"topicId":15415,"target":"Optimization","title":"Optimization","newSince":""},
	{"topicId":15416,"target":"sect-Utilization_Trends","title":"Utilization Trends","newSince":""},
	{"topicId":15417,"target":"To_view_utilization_trend_summary","title":"Viewing Utilization Trend Summary","newSince":""},
	{"topicId":15418,"target":"To_view_detail_lines_of_a_utilization_trend","title":"Viewing Detail Lines of a Utilization Trend","newSince":""},
	{"topicId":15419,"target":"To_view_a_report_of_a_utilization_trend","title":"Viewing a Report of a Utilization Trend","newSince":""},
	{"topicId":15420,"target":"sect-Planning","title":"Planning","newSince":""},
	{"topicId":15421,"target":"To_plan_where_to_put_a_new_Virtual_Machine","title":"Planning Where to Put a New Virtual Machine","newSince":""},
	{"topicId":15422,"target":"sect-Bottlenecks","title":"Bottlenecks","newSince":""},
	{"topicId":15423,"target":"To_view_the_bottleneck_summary","title":"Viewing the Bottleneck Summary","newSince":""},
	{"topicId":15424,"target":"To_view_a_report_of_the_bottlenecks_trend","title":"Viewing a Report of the Bottlenecks Trend","newSince":""},
	{"topicId":15426,"target":"chap-Cloud_Intelligence","title":"Cloud Intelligence","newSince":""},
	{"topicId":15427,"target":"sect-Dashboard","title":"Dashboard","newSince":""},
	{"topicId":15428,"target":"To_add_a_widget","title":"Adding a Widget","newSince":""},
	{"topicId":15429,"target":"To_reset_to_the_default_set_of_widgets","title":"Resetting to the Default Set of Widgets","newSince":""},
	{"topicId":15430,"target":"To_remove_a_widget","title":"Removing a Widget","newSince":""},
	{"topicId":15431,"target":"To_zoom_in_to_a_chart_widget","title":"Zooming in to a Chart Widget","newSince":""},
	{"topicId":41544,"target":"Adding_OpenStack_Providers","title":"Adding OpenStack Providers","newSince":""},
	{"topicId":41545,"target":"Adding_Amazon_EC2_Providers","title":"Adding Amazon EC2 Providers","newSince":""},
	{"topicId":15433,"target":"To_minimize_or_maximize_a_widget","title":"Minimizing or Maximizing a Widget","newSince":""},
	{"topicId":15434,"target":"To_download_a_report_widget_as_a_file","title":"Downloading a Report Widget as a File","newSince":""},
	{"topicId":15436,"target":"To_create_a_Report_widget","title":"Creating a Report Widget","newSince":""},
	{"topicId":15437,"target":"To_create_a_Chart_widget","title":"Creating a Chart Widget","newSince":""},
	{"topicId":15438,"target":"To_create_an_RSS_Feed_widget","title":"Creating an RSS Feed Widget","newSince":""},
	{"topicId":15439,"target":"To_create_a_Menu_widget","title":"Creating a Menu Widget","newSince":""},
	{"topicId":15440,"target":"To_edit_a_widget","title":"Editing a Widget","newSince":""},
	{"topicId":15441,"target":"To_copy_a_widget","title":"Copying a Widget","newSince":""},
	{"topicId":15442,"target":"To_delete_a_widget","title":"Deleting a Widget","newSince":""},
	{"topicId":15443,"target":"To_generate_widget_content_immediately","title":"Generating Widget Content Immediately","newSince":""},
	{"topicId":15444,"target":"sect-Reports","title":"Reports","newSince":""},
	{"topicId":15445,"target":"sect-Running_Reports","title":"Running Reports","newSince":""},
	{"topicId":15446,"target":"To_generate_a_single_report","title":"Generating a Single Report","newSince":""},
	{"topicId":15447,"target":"To_schedule_a_Report","title":"Scheduling a Report","newSince":""},
	{"topicId":15449,"target":"To_run_a_scheduled_report_immediately","title":"Running a Scheduled Report Immediately","newSince":""},
	{"topicId":15450,"target":"sect-Viewing_Reports","title":"Viewing Reports","newSince":""},
	{"topicId":15453,"target":"Changing_Report_Views","title":"Changing Report Views","newSince":""},
	{"topicId":21598,"target":"chap-Clouds","title":"Clouds","newSince":""},
	{"topicId":21599,"target":"sect-Providers","title":"Providers","newSince":""},
	{"topicId":15455,"target":"Report_Download_Buttons","title":"Report Download Buttons","newSince":""},
	{"topicId":21600,"target":"sect-Flavors","title":"Flavors","newSince":""},
	{"topicId":15456,"target":"Downloading_a_Report","title":"Downloading a Report","newSince":""},
	{"topicId":21601,"target":"Reviewing_a_Flavor","title":"Viewing a Flavor","newSince":""},
	{"topicId":15458,"target":"Showing_a_Report_in_Full_Screen","title":"Showing a Report in Full Screen","newSince":""},
	{"topicId":15461,"target":"Adding_a_Report","title":"Adding a Report","newSince":""},
	{"topicId":21606,"target":"Viewing_Flavor_Relationships","title":"Viewing Flavor Relationships","newSince":""},
	{"topicId":15465,"target":"Editing_a_Report","title":"Editing a Report","newSince":""},
	{"topicId":15467,"target":"Deleting_a_Report","title":"Deleting a Report","newSince":""},
	{"topicId":22636,"target":"sect-Security_Groups","title":"Security Groups","newSince":""},
	{"topicId":22637,"target":"Viewing_Security_Groups","title":"Viewing Security Groups","newSince":""},
	{"topicId":21613,"target":"sect-Instances","title":"Instances","newSince":""},
	{"topicId":21614,"target":"sect-Filtering_Instances_and_Images","title":"Filtering Instances and Images","newSince":""},
	{"topicId":15470,"target":"To_export_a_report","title":"Exporting a Report","newSince":""},
	{"topicId":21615,"target":"Using_an_Instance_or_Image_Filter","title":"Using an Instance or Image Filter","newSince":""},
	{"topicId":15471,"target":"To_import_a_report","title":"Importing a Report","newSince":""},
	{"topicId":21616,"target":"Creating_an_Instance_or_Image_Filter","title":"Creating an Instance or Image Filter","newSince":""},
	{"topicId":15472,"target":"sect-Report_Menus","title":"Report Menus","newSince":""},
	{"topicId":21617,"target":"Loading_a_Report_Filter_or_Search_Expression","title":"Loading a Report Filter or Search Expression","newSince":""},
	{"topicId":15473,"target":"To_manage_Report_Menu_Accordions","title":"Managing Report Menu Accordions","newSince":""},
	{"topicId":15474,"target":"To_manage_Report_Menu_Folders","title":"Managing Report Menu Folders","newSince":""},
	{"topicId":21619,"target":"Changing_Views_for_Instances_and_Images","title":"Changing Views for Instances and Images","newSince":""},
	{"topicId":15475,"target":"To_organize_reports_in_Report_Menus","title":"Organizing Reports in Report Menus","newSince":""},
	{"topicId":21620,"target":"Sorting_Instances_and_Images","title":"Sorting Instances and Images","newSince":""},
	{"topicId":15476,"target":"sect-Usage","title":"Usage","newSince":""},
	{"topicId":21621,"target":"Creating_an_Instance_or_Image_Report","title":"Creating an Instance or Image Report","newSince":""},
	{"topicId":15477,"target":"To_access_Usage_data","title":"Accessing Usage Data","newSince":""},
	{"topicId":21622,"target":"Searching_for_Instances_or_Images","title":"Searching for Instances or Images","newSince":""},
	{"topicId":15478,"target":"sect-Chargeback","title":"Chargeback","newSince":""},
	{"topicId":22647,"target":"Tagging_Security_Groups","title":"Tagging Security Groups","newSince":""},
	{"topicId":21623,"target":"Analyzing_Instances_and_Images","title":"Analyzing Instances and Images","newSince":""},
	{"topicId":15479,"target":"Chargeback_Rates","title":"Chargeback Rates","newSince":""},
	{"topicId":21624,"target":"sect-Comparing_Instances_and_Images","title":"Comparing Instances and Images","newSince":""},
	{"topicId":15480,"target":"To_create_chargeback_rates","title":"Creating Chargeback Rates","newSince":""},
	{"topicId":21625,"target":"Creating_an_Instance_Comparison_Report","title":"Creating an Instance Comparison Report","newSince":""},
	{"topicId":15481,"target":"To_assign_chargeback_rates","title":"Assigning Chargeback Rates","newSince":""},
	{"topicId":21626,"target":"Refreshing_Instances_and_Images","title":"Refreshing Instances and Images","newSince":""},
	{"topicId":15482,"target":"To_create_a_chargeback_report","title":"Creating a Chargeback Report","newSince":""},
	{"topicId":21627,"target":"Extracting_Running_Processes_from_Instances_and_Images","title":"Extracting Running Processes from Instances and Images","newSince":""},
	{"topicId":21628,"target":"Setting_Ownership_for_Instances_and_Images","title":"Setting Ownership for Instances and Images","newSince":""},
	{"topicId":15484,"target":"To_access_and_use_a_Timeline","title":"Accessing and Using a Timeline","newSince":""},
	{"topicId":21629,"target":"Removing_Instances_and_Images_from_the_VMDB","title":"Removing Instances and Images from the VMDB","newSince":""},
	{"topicId":15485,"target":"To_download_a_Timelines_data","title":"Downloading a Timeline's Data","newSince":""},
	{"topicId":44158,"target":"Enabling_AWS_Config_Notifications","title":"Enabling AWS Config Notifications","newSince":""},
	{"topicId":21630,"target":"Tagging_Instances_and_Images","title":"Tagging Instances and Images","newSince":""},
	{"topicId":15486,"target":"RSS","title":"RSS","newSince":""},
	{"topicId":21631,"target":"Reviewing_an_Instance_or_Image","title":"Reviewing an Instance or Image","newSince":""},
	{"topicId":21632,"target":"Instance_and_Image_Taskbars","title":"Instance and Image Taskbars","newSince":""},
	{"topicId":21633,"target":"Performing_SmartState_Analysis_on_an_Instance_or_Image","title":"Performing SmartState Analysis on an Instance or Image","newSince":""},
	{"topicId":21636,"target":"Viewing_Running_Processes_after_Collection","title":"Viewing Running Processes after Collection","newSince":""},
	{"topicId":21637,"target":"Editing_Instance_or_Image_Properties","title":"Editing Instance or Image Properties","newSince":""},
	{"topicId":21640,"target":"Right_Sizing_an_Instance","title":"Right Sizing an Instance","newSince":""},
	{"topicId":21642,"target":"Viewing_Capacity_and_Utilization_Charts_for_an_Instance","title":"Viewing Capacity and Utilization Charts for an Instance","newSince":""},
	{"topicId":21643,"target":"Viewing_the_Instance_or_Image_Timeline","title":"Viewing the Instance or Image Timeline","newSince":""},
	{"topicId":21644,"target":"Changing_the_Summary_View_of_an_Instance_or_Image","title":"Changing the Summary View of an Instance or Image","newSince":""},
	{"topicId":21646,"target":"Instance_or_Image_Summary","title":"Instance or Image Summary","newSince":""},
	{"topicId":21647,"target":"Viewing_the_Operating_System_Properties1","title":"Viewing the Operating System Properties","newSince":""},
	{"topicId":21648,"target":"Viewing_a_User_Information_for_an_Instance_or_Image","title":"Viewing User Information for an Instance or Image","newSince":""},
	{"topicId":21649,"target":"Viewing_a_Group_Information_for_an_Instance_or_Image","title":"Viewing Group Information for an Instance or Image","newSince":""},
	{"topicId":21650,"target":"Viewing_Genealogy_of_an_Instance_or_Image","title":"Viewing Genealogy of an Instance or Image","newSince":""},
	{"topicId":21651,"target":"Detecting_Drift_on_Instances_or_Images","title":"Detecting Drift on Instances or Images","newSince":""},
	{"topicId":21652,"target":"Creating_a_Drift_Report_for_an_Instance_or_Image","title":"Creating a Drift Report for an Instance or Image","newSince":""},
	{"topicId":34453,"target":"Authenticating_VMware_vCenter_Hosts","title":"Authenticating VMware vCenter Hosts","newSince":""},
	{"topicId":21653,"target":"Viewing_Analysis_History_for_an_Instance_or_Image","title":"Viewing Analysis History for an Instance or Image","newSince":""},
	{"topicId":21654,"target":"Viewing_Event_Logs_for_an_Instance_or_Image","title":"Viewing Event Logs for an Instance or Image","newSince":""},
	{"topicId":42674,"target":"Data_Collection_for_Red_Hat_Enterprise_Virtualization_3.3_and_3.4","title":"Data Collection for Red Hat Enterprise Virtualization 3.3 and 3.4","newSince":""},
	{"topicId":25811,"target":"Data_Collection_for_Red_Hat_Enterprise_Linux_OpenStack_Platform","title":"Data Collection for Red Hat Enterprise Linux OpenStack Platform","newSince":""},
	{"topicId":21757,"target":"Controlling_the_Power_State_of_an_Instance","title":"Controlling the Power State of an Instance","newSince":""},
	{"topicId":44288,"target":"Adding_a_Red_Hat_Enterprise_Virtualization_Manager_Provider","title":"Adding a Red Hat Enterprise Virtualization Manager Provider","newSince":""},
	{"topicId":15110,"target":"sect-Virtual_Machines","title":"Virtual Machines","newSince":""},
	{"topicId":44295,"target":"Adding_a_VMware_vCenter_Provider","title":"Adding a VMware vCenter Provider","newSince":""},
	{"topicId":44296,"target":"Adding_a_Microsoft_System_Center_Virtual_Machine_Manager_Provider","title":"Adding a Microsoft System Center Virtual Machine Manager Provider","newSince":""},
	{"topicId":15112,"target":"sect-Filtering_Virtual_Machines_and_Templates","title":"Filtering Virtual Machines and Templates","newSince":""},
	{"topicId":30473,"target":"appe-Reportable_Fields_in_CloudForms_Management_Engine","title":"Reportable Fields in CloudForms Management Engine","newSince":""},
	{"topicId":15114,"target":"To_create_a_Virtual_Machine_or_Template_Filter","title":"Creating a Virtual Machine or Template Filter","newSince":""},
	{"topicId":15115,"target":"To_load_a_report_filter_or_search_expression","title":"Loading a Report Filter or Search Expression","newSince":""},
	{"topicId":15117,"target":"Changing_Views","title":"Changing Views for Virtual Machines and Templates","newSince":""},
	{"topicId":15118,"target":"Sorting_Virtual_Machines_and_Templates","title":"Sorting Virtual Machines and Templates","newSince":""},
	{"topicId":15121,"target":"Creating_a_Virtual_Machine_or_Template_Report","title":"Creating a Virtual Machine or Template Report","newSince":""},
	{"topicId":44307,"target":"Adding_an_OpenStack_Infrastructure_Provider","title":"Adding an OpenStack Infrastructure Provider","newSince":""},
	{"topicId":15123,"target":"Searching_by_Virtual_Machine_or_Template_Name","title":"Searching for Virtual Machines or Templates","newSince":""},
	{"topicId":15129,"target":"sect-Analyzing_Virtual_Machines_and_Templates","title":"Analyzing Virtual Machines and Templates","newSince":""},
	{"topicId":15130,"target":"Storage_Support_Notes_about_Analyzing_from_RHEVM_3.1","title":"SmartState Analysis on Red Hat Enterprise Virtualization Manager 3.1 and Above - Storage Support Notes","newSince":""},
	{"topicId":15131,"target":"Storage_Support_Notes_about_Analyzing_from_RHEVM_3.0","title":"SmartState Analysis on Red Hat Enterprise Virtualization Manager 3.0 - Storage Support Notes","newSince":""},
	{"topicId":15133,"target":"sect-Comparing_Virtual_Machines_and_Templates","title":"Comparing Virtual Machines and Templates","newSince":""},
	{"topicId":15135,"target":"Virtual_Machine_and_Templates_Comparison_Sections","title":"Virtual Machine and Templates Comparison Sections","newSince":""},
	{"topicId":15136,"target":"To_use_Comparison_Sections","title":"Using the Virtual Machine Comparison Sections","newSince":""},
	{"topicId":15137,"target":"To_create_a_comparison_report","title":"Creating a Virtual Machine Comparison Report","newSince":""},
	{"topicId":15138,"target":"Refreshing_Virtual_Machines_and_Templates","title":"Refreshing Virtual Machines and Templates","newSince":""},
	{"topicId":15140,"target":"Extracting_Running_Processes","title":"Extracting Running Processes from Virtual Machines and Templates","newSince":""},
	{"topicId":15143,"target":"To_set_ownership","title":"Setting Ownership for Virtual Machines and Templates","newSince":""},
	{"topicId":15144,"target":"Removing_Virtual_Machines_and_Templates_from_the_VMDB","title":"Removing Virtual Machines and Templates from the VMDB","newSince":""},
	{"topicId":15147,"target":"To_tag_Virtual_Machines_and_Templates","title":"Tagging Virtual Machines and Templates","newSince":""},
	{"topicId":15156,"target":"To_view_running_processes_after_collection","title":"Viewing Running Processes after Collection","newSince":""},
	{"topicId":15158,"target":"To_edit_Virtual_Machine_or_Template_Properties","title":"Editing Virtual Machine or Template Properties","newSince":""},
	{"topicId":15159,"target":"Setting_Ownership_of_a_Virtual_Machine_or_Template","title":"Setting Ownership of a Virtual Machine or Template","newSince":""},
	{"topicId":15164,"target":"To_right-size_a_Virtual_Machine","title":"Right Sizing a Virtual Machine","newSince":""},
	{"topicId":15168,"target":"To_view_capacity_and_utilization_charts_for_a_Virtual_Machine","title":"Viewing Capacity and Utilization Charts for a Virtual Machine","newSince":""},
	{"topicId":15170,"target":"To_view_the_timeline_for_a_Virtual_Machine_or_Template","title":"Viewing the Virtual Machine or Template Timeline","newSince":""},
	{"topicId":15174,"target":"Virtual_Machine_or_Template_Summary","title":"Virtual Machine or Template Summary","newSince":""},
	{"topicId":15178,"target":"Viewing_the_Operating_System_Properties","title":"Viewing the Operating System Properties","newSince":""},
	{"topicId":15180,"target":"Viewing_Virtual_Machine_or_Template_Snapshot_Information","title":"Viewing Virtual Machine or Template Snapshot Information","newSince":""},
	{"topicId":15183,"target":"To_view_a_users_group_memberships","title":"Viewing User Information for a Virtual Machine or Template","newSince":""},
	{"topicId":15184,"target":"To_view_a_groups_members","title":"Viewing Group Information for a Virtual Machine or Template","newSince":""},
	{"topicId":15185,"target":"Viewing_Genealogy_of_a_Virtual_Machine_or_Template","title":"Viewing Genealogy of a Virtual Machine or Template","newSince":""},
	{"topicId":15187,"target":"To_view_and_compare_genealogy","title":"Comparing Genealogy of a Virtual Machine or Template","newSince":""},
	{"topicId":15188,"target":"To_tag_Virtual_Machines_or_Templates_with_a_common_genealogy","title":"Tagging Virtual Machines or Templates with a Common Genealogy","newSince":""},
	{"topicId":15189,"target":"Viewing_Drift_on_Virtual_Machines_or_Templates","title":"Detecting Drift on Virtual Machines or Templates","newSince":""},
	{"topicId":15191,"target":"To_create_a_drift_report","title":"Creating a Drift Report for a Virtual Machine or Template","newSince":""},
	{"topicId":15193,"target":"To_view_analysis_history","title":"Viewing Analysis History for a Virtual Machine or Template","newSince":""},
	{"topicId":15195,"target":"To_view_disk_information","title":"Viewing Disk Information for a Virtual Machine or Template","newSince":""},
	{"topicId":15197,"target":"To_view_event_logs","title":"Viewing Event Logs for a Virtual Machine or Template","newSince":""},
	{"topicId":15200,"target":"chap-Infrastructure","title":"Infrastructure","newSince":""},
	{"topicId":15201,"target":"chap-Common_Infrastructure_and_Cloud_Controls","title":"Common Infrastructure and Cloud Controls","newSince":""},
	{"topicId":15202,"target":"Changing_List_Views","title":"Changing Views","newSince":""},
	{"topicId":15204,"target":"Sorting_Infrastructure_Items","title":"Sorting Infrastructure Items","newSince":""},
	{"topicId":15206,"target":"Creating_an_Infrastructure_Report","title":"Creating an Infrastructure Report","newSince":""},
	{"topicId":15208,"target":"Searching_by_Name","title":"Searching by Name","newSince":""},
	{"topicId":15210,"target":"sect-Advanced_Searching","title":"Advanced Searching","newSince":""},
	{"topicId":15211,"target":"To_search_for_infrastructure_items","title":"Searching for Infrastructure Items with Advanced Search","newSince":""},
	{"topicId":15212,"target":"To_save_a_search","title":"Saving an Advanced Search","newSince":""},
	{"topicId":15213,"target":"To_load_a_report_filter_or_search_expression1","title":"Loading a Report Filter or Search Expression","newSince":""},
	{"topicId":15215,"target":"sect-Providers1","title":"Providers","newSince":""},
	{"topicId":21361,"target":"Installing_VMware_VDDK_on_CloudForms_Management_Engine","title":"Installing VMware VDDK on CloudForms Management Engine","newSince":""},
	{"topicId":15222,"target":"To_remove_Management_Systems","title":"Removing a Provider","newSince":""},
	{"topicId":15223,"target":"Refreshing_Multiple_Management_Systems","title":"Refreshing Providers","newSince":""},
	{"topicId":15225,"target":"Tagging_Multiple_Management_Systems","title":"Tagging Multiple Providers","newSince":""},
	{"topicId":15227,"target":"Discovering_Multiple_Management_Systems","title":"Discovering Providers","newSince":""},
	{"topicId":15229,"target":"Reviewing_a_Management_System","title":"Viewing a Provider","newSince":""},
	{"topicId":15242,"target":"Viewing_the_Management_System_Timeline","title":"Viewing the Provider Timeline","newSince":""},
	{"topicId":15246,"target":"Viewing_Hosts_and_Clusters","title":"Viewing Hosts and Clusters","newSince":""},
	{"topicId":15248,"target":"Viewing_Virtual_Machines_and_Templates","title":"Viewing Virtual Machines and Templates","newSince":""},
	{"topicId":15250,"target":"sect-Clusters","title":"Clusters","newSince":""},
	{"topicId":15251,"target":"Performing_SmartState_Analysis_on_Clusters","title":"Performing SmartState Analysis on Clusters","newSince":""},
	{"topicId":15253,"target":"sect-Comparing_Clusters","title":"Comparing Clusters","newSince":""},
	{"topicId":15255,"target":"To_create_a_comparison_report1","title":"Creating a Cluster Comparison Report","newSince":""},
	{"topicId":15256,"target":"Removing_Clusters","title":"Removing Clusters","newSince":""},
	{"topicId":15258,"target":"Tagging_Clusters","title":"Tagging Clusters","newSince":""},
	{"topicId":15260,"target":"Reviewing_a_Cluster","title":"Viewing a Cluster","newSince":""},
	{"topicId":15778,"target":"Resource_Pools_Accordion","title":"Resource Pools Accordion","newSince":""},
	{"topicId":15782,"target":"To_open_a_chart_or_report_widget_in_its_own_window","title":"Opening a Chart or Report Widget in Its Own Window","newSince":""},
	{"topicId":15271,"target":"Viewing_Capacity_and_Utilization_Charts_for_a_Cluster","title":"Viewing Capacity and Utilization Charts for a Cluster","newSince":""},
	{"topicId":15783,"target":"To_modify_a_report_schedule","title":"Modifying a Report Schedule","newSince":""},
	{"topicId":15784,"target":"Copying_a_report","title":"Copying a Report","newSince":""},
	{"topicId":15273,"target":"Viewing_Cluster_Timeline","title":"Viewing Cluster Timeline","newSince":""},
	{"topicId":15282,"target":"To_create_a_drift_report1","title":"Creating a Drift Report for Clusters","newSince":""},
	{"topicId":15283,"target":"sect-Hosts","title":"Hosts","newSince":""},
	{"topicId":15284,"target":"sect-Filtering_Hosts","title":"Filtering Hosts","newSince":""},
	{"topicId":15286,"target":"To_set_a_default_Host_Filter","title":"Setting a Default Host Filter","newSince":""},
	{"topicId":15287,"target":"To_create_a_Host_Filter","title":"Creating a Host Filter","newSince":""},
	{"topicId":15288,"target":"Performing_SmartState_Analysis_on_Hosts","title":"Performing SmartState Analysis on Hosts","newSince":""},
	{"topicId":15290,"target":"sect-Comparing_Hosts","title":"Comparing Hosts","newSince":""},
	{"topicId":42938,"target":"Author_Group","title":"Author Group","newSince":""},
	{"topicId":15292,"target":"Host_Comparison_Sections","title":"Host Comparison Sections","newSince":""},
	{"topicId":15293,"target":"To_use_Host_Comparison_Sections","title":"Using the Host Comparison Sections","newSince":""},
	{"topicId":15294,"target":"To_create_a_comparison_report2","title":"Creating a Host Comparison Report","newSince":""},
	{"topicId":15295,"target":"Refreshing_Multiple_Hosts","title":"Refreshing Multiple Hosts","newSince":""},
	{"topicId":42943,"target":"appe-Revision_History","title":"Revision History","newSince":""},
	{"topicId":15297,"target":"Discovering_Multiple_Hosts","title":"Discovering Multiple Hosts","newSince":""},
	{"topicId":15298,"target":"Detecting_Drift_on_Clusters","title":"Detecting Drift on Clusters","newSince":""},
	{"topicId":15300,"target":"Adding_a_single_Host","title":"Adding a Single Host","newSince":""},
	{"topicId":15302,"target":"Editing_Hosts","title":"Editing Hosts","newSince":""},
	{"topicId":41926,"target":"Exporting_a_Widget","title":"Exporting a Widget","newSince":""},
	{"topicId":41927,"target":"Importing_a_Widget","title":"Importing a Widget","newSince":""},
	{"topicId":15304,"target":"Removing_Hosts","title":"Removing Hosts","newSince":""},
	{"topicId":15306,"target":"Tagging_Multiple_Hosts","title":"Tagging Multiple Hosts","newSince":""},
	{"topicId":41931,"target":"Authenticating_to_Microsoft_SCVMM","title":"Authenticating to Microsoft SCVMM","newSince":""},
	{"topicId":15308,"target":"Reviewing_a_Host","title":"Viewing a Host","newSince":""},
	{"topicId":15313,"target":"Refreshing_Relationships_and_Power_States_for_a_Host","title":"Refreshing Relationships and Power States for a Host","newSince":""},
	{"topicId":19416,"target":"Adding_Database_Credentials_for_Data_Collection","title":"Adding Database Credentials for Data Collection","newSince":""},
	{"topicId":15323,"target":"Viewing_Capacity_and_Utilization_Charts_for_a_Host","title":"Viewing Capacity and Utilization Charts for a Host","newSince":""},
	{"topicId":15325,"target":"Viewing_the_Host_Timeline","title":"Viewing the Host Timeline","newSince":""},
	{"topicId":15330,"target":"Host_Virtual_Summary","title":"Host Virtual Summary","newSince":""},
	{"topicId":15333,"target":"Viewing_Host_Device_Information","title":"Viewing Host Device Information","newSince":""},
	{"topicId":15335,"target":"Viewing_Host_Network_Information","title":"Viewing Host Network Information","newSince":""},
	{"topicId":41959,"target":"sect-Tenants","title":"Tenants","newSince":""},
	{"topicId":41960,"target":"Viewing_a_Tenant","title":"Viewing a Tenant","newSince":""},
	{"topicId":15337,"target":"Viewing_Storage_Adapters","title":"Viewing Storage Adapters","newSince":""},
	{"topicId":41961,"target":"Viewing_Tenant_Relationships","title":"Viewing Tenant Relationships","newSince":""},
	{"topicId":15339,"target":"Detecting_Drift_on_Hosts","title":"Detecting Drift on Hosts","newSince":""},
	{"topicId":15341,"target":"To_create_a_drift_report2","title":"Creating a Drift Report for Hosts","newSince":""},
	{"topicId":15342,"target":"sect-Resource_Pools","title":"Resource Pools","newSince":""},
	{"topicId":15343,"target":"Removing_a_Resource_Pool","title":"Removing a Resource Pool","newSince":""},
	{"topicId":15345,"target":"Tagging_a_Resource_Pool","title":"Tagging a Resource Pool","newSince":""},
	{"topicId":15348,"target":"Viewing_the_Resource_Pool_Summary","title":"Viewing the Resource Pool Summary","newSince":""},
	{"topicId":15349,"target":"sect-Datastores","title":"Datastores","newSince":""},
	{"topicId":15350,"target":"Performing_SmartState_Analysis_on_Datastores","title":"Performing SmartState Analysis on Datastores","newSince":""},
	{"topicId":21495,"target":"Removing_Cloud_Providers","title":"Removing Cloud Providers","newSince":""},
	{"topicId":21496,"target":"Refreshing_Cloud_Providers","title":"Refreshing Cloud Providers","newSince":""},
	{"topicId":21497,"target":"Tagging_Cloud_Providers","title":"Tagging Cloud Providers","newSince":""},
	{"topicId":15354,"target":"Reviewing_a_Datastore","title":"Viewing a Datastore","newSince":""},
	{"topicId":21498,"target":"Discovering_Amazon_EC2_Cloud_Providers","title":"Discovering Amazon EC2 Cloud Providers","newSince":""},
	{"topicId":21499,"target":"Editing_a_Cloud_Provider","title":"Editing a Cloud Provider","newSince":""},
	{"topicId":21500,"target":"Viewing_a_Cloud_Providers_Timeline","title":"Viewing a Cloud Provider's Timeline","newSince":""},
	{"topicId":21502,"target":"sect-Availability_Zones","title":"Availability Zones","newSince":""},
	{"topicId":21503,"target":"Reviewing_an_Availability_Zone","title":"Viewing an Availability Zone","newSince":""}], 23039, "Red Hat CloudForms", "Insight Guide", "3.2");