[[installing-cloudforms]]
== Installing CloudForms

CloudForms Management Engine is able to be installed and ready to configure in a few quick steps. After downloading CloudForms Management Engine as a virtual machine image template from the Red Hat Customer Portal, the installation process takes you through the steps of uploading the appliance to a supported virtualization or cloud provider.

[IMPORTANT]
=======
After installing the CloudForms Management Engine Appliance, you must configure the database for Red Hat CloudForms. See xref:configuring_a_database[].
=======

=== Obtaining the CloudForms Management Engine Appliance

. Go to link:https://access.redhat.com[access.redhat.com] and log in to the Red Hat Customer Portal using your customer account details.
. Click btn:[Downloads] in the menu bar.
. Click btn:[A-Z] to sort the product downloads alphabetically.
. Click menu:Red Hat CloudForms[Download Latest] to access the product download page.
. From the list of installers and images, select the +CFME Red Hat Virtual Appliance+ download link.

=== Uploading the Appliance on Red Hat Enterprise Virtualization Manager

Uploading the CloudForms Management Engine Appliance file onto Red Hat Enterprise Virtualization Management systems has the following requirements:

* 44 GB of storage space on both the export domain and the local partition where **/tmp** resides since the OVF archive is locally expanded into that directory.
* Install the **rhevm-image-uploader** package containing the engine-image-uploader script to your local machine.
+
----
# yum install rhevm-image-uploader
----
+
It is recommended to use -v (verbose logging) when using the **engine-image-uploader** script to see the progression of the upload.
* Depending on your infrastructure, allow approximately 90 minutes for the upload.
* Once the OVF is uploaded and imported as a template, add a network adapter to the template itself.

=== Using the Image Uploader Tool

The engine-image-uploader command allows you to list export storage domains and upload virtual machine images in OVF format to an export storage domain and have them automatically recognized in the Red Hat Enterprise Virtualization Manager.

[NOTE]
======
The image uploader only supports gzip-compressed OVF files created by Red Hat Enterprise Virtualization.
======

The archive contains images and master directories in the following format:

----
|-- images
|   |-- [Image Group UUID]
|        |--- [Image UUID (this is the disk image)]
|        |--- [Image UUID (this is the disk image)].meta
|-- master
|   |---vms
|       |--- [UUID]
|             |--- [UUID].ovf
----

The basic syntax for the image uploader command is:

----
engine-image-uploader [options] listengine-image-uploader [options] upload [file].[file]...[file]
----

The image uploader command supports two actions - list, and upload.

* The list action lists the export storage domains to which images can be uploaded.
* The upload action uploads images to the specified export storage domain.

You must specify one of the above actions when you use the image uploader command. Moreover, you must specify at least one local file to use the upload action.

There are several parameters to further refine the **engine-image-uploader** command. You can set defaults for any of these parameters in the **/etc/ovirt-engine/imageuploader.conf** file.

*General Options*

+-h, --help+

Displays information on how to use the image uploader command.

+--conf-file=[PATH]+

Sets +[PATH]+ as the configuration file the command will use. The default is **/etc/ovirt-engine/imageuploader.conf**.

+--log-file=[PATH]+

Sets +[PATH]+ as the specific file name the command will use to write log output. The default is **/var/log/ovirt-engine/ovirt-image-uploader/ovirt-image-uploader-[date].log**.

+--cert-file=[PATH]+

Sets [PATH] as the certificate for validating the engine. The default is **/etc/pki/ovirt-engine/ca.pem**.

+--insecure+

Specifies that no attempt will be made to verify the engine.

+--quiet+

Sets quiet mode, reducing console output to a minimum.

+-v, --verbose+

Sets verbose mode, providing more console output.

+-f, --force+

Force mode is necessary when the source file being uploaded has the same file name as an existing file in the destination export domain. This option forces the existing file to be overwritten.

*Red Hat Enterprise Virtualization Manager Options*

+-u [USER], --user=[USER]+

Specifies the user whose credentials will be used to execute the command. The +[USER]+ is specified in the format **[username]@[domain]**. The user must exist in the specified domain and be known to the Red Hat Enterprise Virtualization Manager.

+-r [FQDN], --engine=[FQDN]+

Specifies the IP address or fully qualified domain name of the Red Hat Enterprise Virtualization Manager from which the images will be uploaded. It is assumed that the image uploader is being run from the same machine on which the Red Hat Enterprise Virtualization Manager is installed. The default value is **localhost:443**.

*Export Storage Domain Options*

The following options specify the export domain to which the images will be uploaded. These options cannot be used together; you must used either the **-e** option or the **-n** option.

+-e [EXPORT_DOMAIN], --export-domain=[EXPORT_DOMAIN]+

Sets the storage domain +EXPORT_DOMAIN+ as the destination for uploads.

+-n [NFSSERVER], --nfs-server=[NFSSERVER]+

Sets the NFS path +[NFSSERVER]+ as the destination for uploads.

*Import Options*

The following options allow you to customize which attributes of the images being uploaded are included when the image is uploaded to the export domain.

+-i, --ovf-id+

Specifies that the UUID of the image will not be updated. By default, the command generates a new UUID for images that are uploaded. This ensures there is no conflict between the id of the image being uploaded and the images already in the environment.

+-d, --disk-instance-id+

Specifies that the instance ID for each disk in the image will not be renamed. By default, the command generates new UUIDs for disks in images that are uploaded. This ensures there are no conflicts between the disks on the image being uploaded and the disks already in the environment.

+-m, --mac-address+

Specifies that network components in the image will not be removed from the image. By default, the command removes network interface cards from image being uploaded to prevent conflicts with network cards on other virtual machines already in the environment. If you do not use this option, you can use the Administration Portal to add network interface cards to newly imported images and the Manager will ensure there are no MAC address conflicts.

+-N [NEW_IMAGE_NAME], --name=[NEW_IMAGE_NAME]+

Specifies a new name for the image being uploaded.

==== Uploading the Appliance with the Image Uploader

The following procedure uploads the CloudForms Management Engine Appliance using the Image Uploader tool.

. Change to the directory containing the CloudForms Management Engine Appliance.
. Run the following command:
+
----
# engine-image-uploader -N     newimagename     -e     myexportdomain     -v -m upload cfme-rhevm-5.3-15.x86_64.rhevm.ova
----
+
Substitute +newimagename+ with your chosen name for the image, and substitute +myexportdomain+ with your chosen Export storage domain.
. Enter the password of the default administrative user for your Red Hat Enterprise Virtualization Manager when prompted.
+
----
Please provide the REST API password for the admin@internal oVirt Engine user (CTRL+D to abort): **********
----
+

[IMPORTANT]
======
Ensure your Red Hat Enterprise Virtualization Manager has administrator access to the chosen Export storage domain.
======

It takes approximately 90 minutes to upload the CloudForms Management Engine Appliance file to the Red Hat Enterprise Virtualization Manager.


=== Uploading the Appliance Manually

The following procedure provides manual upload instructions if the Image
Uploader tool is not available or fails to upload.

Procedure 2. To Manually Upload the CloudForms Management Engine
Appliance

. Log into a host in your Red Hat Enterprise Virtualization with a mount to the Export storage domain.
. Change to the Export storage domain's directory.
. Copy the CloudForms Management Engine Appliance OVF archive to this directory.
. Extract the OVF file using the tar command:
+
----
$ tar xvf cfme-rhevm-5.3-15.x86_64.rhevm.ova  
----
+
. Set the following permissions:
+
----
chown -R 36:36 images/
chown -R 36:36 master/  
----
+


=== Running CloudForms Management Engine

After uploading the appliance to the export storage domain, import it as
a template and create a virtual machine. Use the following procedure as a
guide.


. Import the appliance image from the export storage domain as a template in a Red Hat Enterprise Virtualization data storage domain. Use the +newimagename+ you specified when you uploaded the image to find the image to import as a template. Once the import is complete, check the template for a network interface (NIC). If the template does not include one, create a NIC for it.
. Create a new virtual machine using the CloudForms Management Engine Appliance template as a basis. See the Red Hat Enterprise Virtualization Administrator Guide for instructions.
. Add a database disk if you are hosting the database on the same machine as the appliance.
. Start the newly created CloudForms Management Engine Appliance virtual machine.

Your Red Hat Enterprise Virtualization environment now contains a running CloudForms Management Engine Appliance.
