// Module included in the following assemblies:
// assembly_Migrating_the_infrastructure.adoc
[id="Creating_and_running_a_migration_plan"]
= Creating and running a migration plan

.Prerequisites

Certain prerequisites may apply.

Check your migration for the following conditions:

* *You are migrating previously migrated virtual machines*
+
You can previously migrated machines to the migration plan with a CSV file. This is also recommended for large migrations. See xref:Creating_a_csv_file_to_add_virtual_machines_to_the_migration_plan[].

* *You are migrating virtual machines running RHEL or other Linux operating system*
+
RHEL/Linux virtual machines require additional configuration to preserve their IP addresses after migration. See xref:Creating_a_rhel_premigration_playbook[].

* *You are using Ansible playbooks for premigration/postmigration tasks*
+
You can add an Ansible repository, credentials, and playbooks to CloudForms. See xref:Adding_ansible_playbooks_to_cloudforms[].

If these conditions do not apply, you are ready to create a migration plan.

.Creating and running a migration plan

Creating and running a migration plan involves the following key steps:

. Creating a migration plan with the *Create Migration Plan* wizard in CloudForms (see xref:Creating_a_migration_plan[])

. Running the migration plan (the last step of the *Create Migration Plan* wizard) with one of the following options:

* Saving the migration plan and scheduling it to run in the future (see xref:Scheduling_a_saved_migration_plan[])
* Running the migration plan immediately

Optionally, you can do the following:

* xref:Viewing_migration_plan_progress[View a migration plan's progress]
* xref:Canceling_a_migration_plan[Cancel a migration plan in progress]
* xref:Retrying_a_failed_migration_plan[Retry a migration plan] if external factors, such as network disruptions, cause a migration failure

include::con_Migration_plan_options.adoc[leveloffset=+1]
include::proc_Creating_a_migration_plan.adoc[leveloffset=+1]
