// Module included in the following assemblies:
// assembly_Migrating_the_infrastructure.adoc
[id="Creating_and_running_a_migration_plan"]
= Creating and running a migration plan

[NOTE]
====
Performing test migrations with different maximum numbers of concurrent migrations is highly recommended, to assess the capabilities of your environment's infrastructure. See xref:Changing_the_maximum_number_of_concurrent_migrations[].
====

Creating and running a migration plan involves the following key steps:

. Checking whether the following xref:Migration_plan_prerequisites_and_options[migration plan options and prerequisites] apply:

* You are migrating previously migrated virtual machines
* You are migrating virtual machines running RHEL or other Linux operating system
* You are using Ansible playbooks for premigration/postmigration tasks

. xref:Creating_a_migration_plan[Creating a migration plan] with the *Create Migration Plan* wizard in CloudForms

. Running the migration plan, the last step of the *Create Migration Plan* wizard, with one of the following options:

* Saving the migration plan and xref:Scheduling_a_saved_migration_plan[scheduling it] to run in the future

* Running the migration plan immediately
+
Optionally, you can xref:Viewing_migration_plan_progress[view a migration plan's progress] and xref:Canceling_a_migration_plan[cancel a migration plan].
+
If external factors (for example, network disruption) cause migration errors, you can xref:Retrying_a_migration_plan[retry the migration plan]. For other migration errors, see xref:Troubleshooting[].

include::con_Migration_plan_options.adoc[leveloffset=+1]
include::proc_Creating_a_migration_plan.adoc[leveloffset=+1]
