// Module included in the following assemblies:
// assembly_Migrating_the_infrastructure.adoc
[id="Migration_plan_prerequisites"]
= Migration plan prerequisites that may apply

Check the following prerequisites to see whether they apply to your migration:

* Creating a CSV file (xref:Creating_a_csv_file_to_add_virtual_machines_to_the_migration_plan[])
** Mandatory, if you are migrating source virtual machines that have been migrated in the past
** Optional, but recommended, for large migrations

* Creating a `RHEL premigration` Ansible playbook (xref:Creating_a_rhel_premigration_playbook[])
** Mandatory, if you are migrating source virtual machines running RHEL or other Linux-based operating system

* Adding Ansible playbooks to CloudForms (xref:Adding_ansible_playbooks_to_cloudforms[])
** Mandatory, if you are using Ansible playbooks, including the `RHEL premigration` playbook, for premigration and postmigration tasks in the migration plan

If these prerequisites do not apply, you can create a migration plan (xref:Creating_and_running_a_migration_plan[]).

include::proc_Creating_a_csv_file_to_add_virtual_machines_to_the_migration_plan.adoc[leveloffset=+1]
include::proc_Creating_a_rhel_premigration_playbook.adoc[leveloffset=+1]
include::proc_Adding_ansible_playbooks_to_cloudforms.adoc[leveloffset=+1]
