// Module included in the following assemblies:
// assembly_Creating_and_configuring_the_conversion_hosts.adoc
[id="Conversion_host_prerequisites"]
= Conversion host prerequisites

The following prerequisites apply to both Red Hat Virtualization and OpenStack Platform conversion hosts:

* xref:Deciding_how_many_conversion_hosts_to_create[Deciding how many conversion hosts to create]
+
Optionally, you can xref:Changing_the_maximum_number_of_concurrent_migrations[change the number of maximum number of concurrent migrations] for the conversion hosts or the provider.

* xref:Choosing_vddk_or_ssh_transformation[Choosing VDDK or SSH transformation for the migration]

[id="Deciding_how_many_conversion_hosts_to_create"]
== Deciding how many conversion hosts to create

All the virtual machines in the migration plan are migrated at the same time. Therefore, the number of conversion hosts you create depends on the size of your migration. Multiple conversion hosts are recommended for load-balancing purposes, even for smaller migrations.

The number of virtual machines that you can migrate simultaneously depends on your infrastructure capabilities. Each migration requires a certain amount of network bandwidth, I/O throughput, and processing power for the conversion process. You should thoroughly test your environment before the migration to determine how many migrations it can support without negative effects.

Each conversion host is limited to `10` concurrent migrations, unless you xref:Changing_the_maximum_number_of_concurrent_migrations[change the maximum number of concurrent migrations].

include::proc_Changing_the_maximum_number_of_concurrent_migrations.adoc[leveloffset=+1]

[id="Choosing_vddk_or_ssh_transformation"]
== Choosing VDDK or SSH transformation

Choose the transformation option, VDDK or SSH, that is appropriate for your environment, taking into account the following considerations.

*VDDK*

* Pros:
** Recommended because it is approximately twice as fast as SSH
** Compiled with `nbdkit` to provide direct connectivity to the virtual machine disks
* Cons:
** Requires VDDK package download
** Requires a VDDK library location for configuring conversion hosts

*SSH*

* Pros:
** Better suited for large-scale migrations than VDDK
** Does not require additional downloads, packages, tools, or compilation
* Cons:
** Slower than VDDK
** SSH access must be enabled on the VMware hypervisors
** VMware and target environments must share SSH keys

After you have decided how many conversion hosts to create and whether to use VDDK or SSH, you can proceed to the next step.

.Red Hat Virtualization

. Select one or more existing hosts (on physical machines, not virtual machines) to use as conversion hosts.
. Configure the conversion hosts for xref:Configuring_conversion_hosts_for_transformation[SSH or VDDK transformation].

.OpenStack Platform

xref:Creating_OSP_conversion_hosts[Create the OpenStack Platform conversion hosts].
