[id="Conversion_host_considerations"]
= Conversion host considerations

Before creating the conversion hosts, you must consider the following questions, taking into account your environment and the size of the migration:

* How many conversion hosts do I need? (see xref:Number_of_conversion_hosts[])
* Should I use VDDK or SSH transformation? (see xref:datapath_transformation_options_vddk_ssh[])

[[Number_of_conversion_hosts]]
== Number of conversion hosts

Because all the virtual machines in a migration plan are migrated at the same time, the number of conversion hosts you require depends on the number of virtual machines you are migrating. Multiple conversion hosts are recommended for load-balancing purposes, even for smaller migrations.

The number of virtual machines that you can migrate simultaneously depends on your infrastructure capabilities. Each migration requires a certain amount of network bandwidth, I/O throughput, and processing power for the conversion process. You should thoroughly test your environment before the migration to determine how many migrations it can support without negative effects.

Each conversion host is limited to `10` concurrent migrations, unless you  xref:Configuring_the_maximum_number_of_concurrent_migrations[change the default value].

[IMPORTANT]
====
The maximum number of concurrent virtual machine migrations per conversion host is `20` for both VDDK and SSH transformation. The SSH limitation, however, applies only to RHV 4.2.5, not to later versions of RHV.
====

[[datapath_transformation_options_vddk_ssh]]
== Transformation options: VDDK or SSH

You must select the transformation option, VDDK or SSH, that is appropriate for your migration size and environment:

* *VDDK*

** Recommended because it is approximately twice as fast as SSH
** Compiled with `nbdkit` to provide direct connectivity to the virtual machine disks
** Requires VDDK package download
** Requires the location of the VDDK library for conversion host configuration

* *SSH*

** Slower than VDDK
** Better suited for large-scale migrations than VDDK
** Does not require additional downloads, packages, tools, or compilation
** SSH access must be enabled on the source hypervisors
** Source and target environments must share SSH keys