// Module included in the following assemblies:
// assembly_Creating_and_running_a_migration_plan.adoc
[id="Migration_plan_prerequisites_and_options"]
= Migration plan options and prerequisites

Check whether the following options and prerequisites apply to your migration:

You are migrating previously migrated virtual machines::
See xref:Creating_a_csv_file_to_add_virtual_machines_to_the_migration_plan[]
+
[NOTE]
====
For large migrations, a CSV file is optional, but recommended.
====

You are migrating virtual machines running RHEL or other Linux operating system::
See xref:Creating_a_rhel_premigration_playbook[]

You are using Ansible playbooks for premigration/postmigration tasks::
See xref:Adding_ansible_playbooks_to_cloudforms[]

If these prerequisites and options do not apply, you can xref:Creating_a_migration_plan[create a migration plan].

include::proc_Creating_a_csv_file_to_add_virtual_machines_to_the_migration_plan.adoc[leveloffset=+1]
include::proc_Creating_a_rhel_premigration_playbook.adoc[leveloffset=+1]
include::proc_Adding_ansible_playbooks_to_cloudforms.adoc[leveloffset=+1]
