[[Automating_pre_and_post_migration_tasks_with_ansible]]
= Automating pre- and post-migration tasks with Ansible

You can perform automated tasks before and after a virtual machine is migrated, such as removing web servers from a load-balancing pool before migration and adding them back to the pool after migration. Each task is an Ansible service catalog item, which you xref:Advanced_options_screen[select] when you create the migration plan.

The Ansible service catalog item must exist before you create the migration plan. The CloudForms inventory must contain at least one repository, one playbook, and one credential.

To set up the Ansible environment and create a service catalog item:

[[Creating_an_Ansible_service_catalog_item]]
. Configure an link:https://access.redhat.com/documentation/en-us/red_hat_cloudforms/4.6/html/managing_providers/automation_management_providers#ansible-inside[Ansible repository and credentials].

. Create a link:https://access.redhat.com/documentation/en-us/red_hat_cloudforms/4.6/html-single/provisioning_virtual_machines_and_hosts/#creating-a-catalog-bundle[catalog bundle].

. Create an link:https://access.redhat.com/documentation/en-us/red_hat_cloudforms/4.6/html-single/provisioning_virtual_machines_and_hosts/#create-playbook-service-catalog-item[Ansible service catalog item].
