// Module included in the following assemblies:
// assembly_Preparing_the_environment_for_migration.adoc
[id="Configuring_the_conversion_hosts"]
= Configuring the conversion hosts

You can select, authenticate, and configure your conversion hosts in CloudForms.

[IMPORTANT]
====
If you upgrade the target environment, you should xref:Upgrading_the_conversion_hosts[update the conversion hosts] to ensure that you have the latest software and patches.
====

.Prerequisites

* (VDDK only) download the VMware Virtual Disk Development Kit:
+
. Navigate to link:https://www.vmware.com/support/pubs/[].
. Click *VMware SDK & API Product Documentation* to expand.
. Click *VMware Virtual Disk Development Kit (VDDK)*.
. Click *Latest Releases* and select the latest VDDK release.
. Download and save the VDDK package (+VMware-vix-disklib-_version_.x86_64.tar.gz+).

* (VDDK and SSH) Generate an SSH key pair to connect to the VMware hypervisors.

.Procedure

THIS PROCEDURE IS FROM MOCKUPS, NOT REAL UI

. In CloudForms, click menu:Compute[Migration > Migration Settings].
. In the *Conversion Hosts* tab, click *Configure Conversion Host*.
. Perform the following procedures in the *Configure Conversion Host* wizard:

PLACEHOLDER: CONVERSION HOST UI SCREENSHOT

[cols="1,3", options="header"]
|===
|Screen |Procedure
|*Location*
.<a|. Select a *Provider Type*.
. Select a *Provider*.

. Select a Red Hat Virtualization *Cluster* / OpenStack Platform *Project*.

. Click *Next*.
|*Hosts*
.<a|. Select one or more hosts from the dropdown list.
. Click *Next*.
|*Authentication*
.<a|. Click *Browse* to browse to the SSH key or paste it in the *Conversion host SSH key* field.

* Red Hat Virtualization Manager deploys a private SSH key on the conversion hosts in order to send commands and run playbooks. The default key file is `/etc/pki/ovirt-engine/keys/engine_id_rsa` on the Manager machine.
* OpenStack Platform user uses a private SSH key to connect to the conversion hosts.

. Select *SSH* or *VDDK* as a *Transformation method*.

. If you selected SSH, lick *Browse* to browse to the SSH key or paste it in the *VMware hypervisors SSH key* field.
+
If you selected VDDK, enter the path of the VDDK package in the *VDDK library path* field and click *Validate*. Wait for validation to complete.

. Click *Configure*.
|*Results*
.<a|. Wait for the conversion host configuration to finish.
. Click *Close*.
|===

The configured conversion hosts and status information, including error messages, appear in the *Configured Conversion Hosts* list.

[IMPORTANT]
====
If you are using SSH transformation, there is an additional step. See xref:Ssh_only_copying_the_vmware_hypervisor_keys_to_the_conversion_hosts[].
====

Optionally, you can click *Remove* to unconfigure a conversion host or *Retry* to retry a conversion host configuration.

[id="Ssh_only_copying_the_vmware_hypervisor_keys_to_the_conversion_hosts"]
== Copying the VMware keys to the conversion hosts for SSH transformation

To prevent man-in-the-middle attacks, the conversion hosts do not accept the VMware SSH public keys by default for SSH transformation. Instead, the `known_hosts` file of each conversion host must be populated with the public keys of the VMware hypervisors.

Depending on the security processes of your VMware environment, you can either obtain a list of public keys from the VMware system administrators if they collected the keys when they xref:Configuring_the_vmware_hypervisors_for_ssh_transformation[enabled SSH access on the hypervisors] or you can use `ssh-keyscan`.

[WARNING]
====
You must run `ssh-keyscan` multiple times, once for each VMware hypervisor, repeating the procedure on each conversion host. Otherwise your conversion hosts will not have all the VMware keys and the migration will fail.
====

.Gathering VMware keys with `ssh-keyscan`

. On a conversion host, run `ssh-keyscan`, as in the following examples:
+
.Red Hat Virtualization
[options="nowrap" subs="+quotes,verbatim"]
----
# ssh-keyscan _esx1.example.com_ > /var/lib/vdsm/.ssh/known_hosts
# ssh-keyscan _esx2.example.com_ > /var/lib/vdsm/.ssh/known_hosts
# ssh-keyscan _esx3.example.com_ > /var/lib/vdsm/.ssh/known_hosts
----
+
Change the ownership of the `known_hosts` file to user `vdsm` and group `kvm`:
+
----
# chown 36:36 /var/lib/vdsm/.ssh/known_hosts
----
+
.OpenStack Platform
[options="nowrap" subs="+quotes,verbatim"]
----
# ssh-keyscan _esx1.example.com_ > /root/.ssh/known_hosts
# ssh-keyscan _esx2.example.com_ > /root/.ssh/known_hosts
# ssh-keyscan _esx3.example.com_ > /root/.ssh/known_hosts
----

. Repeat for each conversion host, to ensure that all your conversion hosts have all the VMware keys.

[id="Upgrading_the_conversion_hosts"]
== Upgrading the conversion hosts

If you upgrade your target environment, you should update the conversion hosts to ensure that you have the latest software and critical updates:

* Red Hat Virtualization: Run `yum update` on the conversion hosts.
* OpenStack Platform: Download the latest conversion host appliance and re-deploy the conversion hosts (see xref:Deploying_osp_conversion_hosts[]).
