[id="proc_Creating_rhv_conversion_hosts"]
= Creating RHV Conversion Hosts

All the virtual machines that are specified in a migration plan are migrated at the same time. Therefore, the number of RHV conversion hosts that you create depends on the number of virtual machines you intend to migrate. Red Hat recommends configuring the RHV conversion hosts on physical machines, not nested virtual machines.

Each conversion host supports up to 10 concurrent virtual machine migrations, unless you change the default value (see xref:Configuring_the_maximum_number_of_concurrent_migrations[] below). Increasing the number of concurrent migrations is only possible for SSH transformation.

VDDK transformation is limited to 10 concurrent migrations because the vSphere transfer buffer for all NFC connections to an ESXi host cannot exceed 32 MB. See link:https://pubs.vmware.com/vsphere-6-5/index.jsp?topic=%2Fcom.vmware.vddk.pg.doc%2FvddkDataStruct.5.5.html&resultof=%22%4e%46%43%22%20%22%6e%66%63%22%20%22%53%65%73%73%69%6f%6e%22%20%22%73%65%73%73%69%6f%6e%22%20%22%4c%69%6d%69%74%73%22%20%22%6c%69%6d%69%74%22%20[vSphere 6.5 Virtual Disk Transport Methods] for details.

Multiple conversion hosts are recommended, even for small migrations, for load-balancing purposes.

[NOTE]
====
The number of virtual machines that you can migrate at the same time depends on your infrastructure capabilities. Each migration requires a certain amount of network bandwidth, I/O throughput, and processing power for the conversion process. You should test your environment to understand how many migrations can occur simultaneously without negative effects.
====

[[datapath_transformation_options_vddk_ssh]]
[discrete]
== Datapath Transformation Options: VDDK or SSH

You must select the best datapath transformation option for your environment, either VDDK or SSH:

VDDK::
* Best performance and, therefore, recommended
* Compiled with `nbdkit` to provide direct connectivity to the virtual machine disks
* Requires downloading the VDDK package
* Requires a location for the conversion host configuration

SSH::
* Does not require additional downloads, packages, tools, or compilation
* Requires the RHV and VMware environments to share SSH keys
* Requires enabling SSH access on ESX hosts
* Slower than VDDK

[discrete]
== Procedure

Create one or more RHV conversion hosts:

. Log in to the link:https://www.vmware.com/support/developer/vddk/[VMware VDDK Documentation] site and download the latest VDDK package (for example, `VMware-vix-disklib-6.5.3-8315684.x86_64.tar.gz`) to your local machine. The VDDK package is required for creating the conversion host, regardless of the transformation method.

. Using SCP, copy the VDDK package to `/var/www/html` on the Manager machine.

. Go to the conversion hosts directory on the Manager machine:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# cd /usr/share/ovirt-ansible-v2v-conversion-host-_version_/playbooks/
----

. Create a `conversion_hosts_inventory.yml` inventory file with the following variables:
+
[options="nowrap" subs="+quotes,verbatim"]
----
all:
  hosts:
    _host1.example.com_:
    _host2.example.com_:
  vars:
    ansible_ssh_private_key_file: /etc/pki/ovirt-engine/keys/engine_id_rsa
    v2v_vddk_package_name: VMware-vix-disklib-_version_.x86_64.tar.gz
    v2v_vddk_package_url: http://_Manager_FQDN_/VMware-vix-disklib-_version_.x86_64.tar.gz
----

. Enable the conversion hosts:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# ansible-playbook -i conversion_hosts_inventory.yml conversion_host_enable.yml
----
+
[NOTE]
====
The Ansible role checks for the presence of the RHV guest tools ISO image in the ISO storage domain. This image is used to migrate Windows virtual machines.
====

. Verify that the conversion hosts are enabled:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# ansible-playbook -i conversion_hosts_inventory.yml conversion_host_check.yml
----

After creating the RHV conversion hosts, you must configure them in CloudForms.

[NOTE]
====
If you upgrade your RHV environment, you must run the `conversion_host_enable` playbook again, with the option `-e v2v_vddk_override=true`, to update the IMS packages.
====

[discrete]
== Additional resources

* For more information, see link:https://github.com/oVirt/ovirt-ansible-v2v-conversion-host[V2V - Conversion Host - Ansible].
