[id="Configuring_the_maximum_number_of_concurrent_migrations"]
= Changing the maximum number of concurrent migrations

The default maximum number of concurrent migrations is `10` for conversion hosts and `10` for a provider. You can change these limits to control the impact of the migration process on your infrastructure.

The provider's limit has priority over the conversion hosts' limits. For example, if a provider's limit is set to `20` and 5 conversion hosts' limits are set to `3`, the maximum number of concurrent migrations is `20`, not `15`.

.Changing the maximum number of concurrent migrations for conversion hosts

The maximum supported number of concurrent migrations for conversion hosts is `20` for VDDK and `20` for SSH transformation (RHV migrations only: this limitation only applies to RHV 4.2.5 and earlier).

An increased limit takes effect immediately. Virtual machines that are queued to migrate will migrate in greater numbers.

A decreased limit affects future migration plans. Migration plans that are in progress use the limit that was set when the plan was created.

You can change the limits of some or all conversion hosts:

* To change the limits of all conversion hosts, click menu:Compute[Migration > Migration Settings] and select the new maximum number of concurrent migrations.

* To change the limit of a specific conversion host to `20`, enter the following command on the CloudForms machine:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# vmdb
# rails console
irb(main):001:0> $evm = MiqAeMethodService::MiqAeService.new(MiqAeEngine::MiqAeWorkspaceRuntime.new)
irb(main):002:0> $evm.vmdb(:host).find_by(:name => "_host1.example.com_").custom_set("Max Transformation Runners", _20_)
----

.Changing the maximum number of concurrent migrations for a provider

To set a provider's limit to `30`, enter the following command on the CloudForms machine:
[options="nowrap" subs="+quotes,verbatim"]
----
# vmdb
# rails console
irb(main):001:0> $evm = MiqAeMethodService::MiqAeService.new(MiqAeEngine::MiqAeWorkspaceRuntime.new)
irb(main):002:0> $evm.vmdb(:ext_management_system).find_by(:name => "_provider_").custom_set("Max Transformation Runners", _30_)
----

To get a provider's limit, enter the following command on the CloudForms machine:
[options="nowrap" subs="+quotes,verbatim"]
----
# vmdb
# rails console
irb(main):001:0> $evm = MiqAeMethodService::MiqAeService.new(MiqAeEngine::MiqAeWorkspaceRuntime.new)
irb(main):002:0> $evm.vmdb(:ext_management_system).find_by(:name => "_provider_").custom_get("Max Transformation Runners")
----
