[id="Configuring_the_maximum_number_of_concurrent_migrations"]
= Changing the maximum number of concurrent migrations

The default limit for concurrent migrations is `10` for conversion hosts and `10` for a provider. You can change these defaults in order to control the impact of the migration process on your infrastructure.

The provider's limit has priority over the conversion hosts' limit. For example, if you set the provider's limit to `20` and the conversion hosts' limit to `3`, the maximum number of concurrent migrations allowed will be `20`.

.Changing the conversion hosts' limits

[IMPORTANT]
====
The maximum number of concurrent virtual machine migrations per conversion host is `20` for both VDDK and SSH transformation. The SSH limitation, however, applies only to RHV 4.2.5, not to later versions of RHV.
====

To change the default limit for the conversion hosts, click menu:Compute[Migration > Migration Settings] and select the new limit for concurrent migrations.

If the maximum number of concurrent migrations is increased, the virtual machines that are queued to migrate will migrate in greater numbers.

If the maximum number is decreased, migration plans in progress will complete at the current rate and future migration plans will reflect the lower number of concurrent migrations.

.Changing the provider's limit

You can set and get `Max Transformation Runners` using the Rails console on the command line of the CloudForms machine:

* To set `Max Transformation Runners` for the provider to `30`:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# vmdb
# rails console
irb(main):001:0> $evm = MiqAeMethodService::MiqAeService.new(MiqAeEngine::MiqAeWorkspaceRuntime.new)
irb(main):002:0> $evm.vmdb(:ext_management_system).find_by(:name => "_provider_").custom_set("Max Transformation Runners", _30_)
----

* To get the configuration of `Max Transformation Runners` for the provider:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# vmdb
# rails console
irb(main):001:0> $evm = MiqAeMethodService::MiqAeService.new(MiqAeEngine::MiqAeWorkspaceRuntime.new)
irb(main):002:0> $evm.vmdb(:ext_management_system).find_by(:name => "_provider_").custom_get("Max Transformation Runners")
----
