// Module included in the following assemblies:
// assembly_Preparing_the_environment_for_migration.adoc
[id="Configuring_the_conversion_hosts"]
= Configuring the conversion hosts

You can select, authenticate, and configure your conversion hosts in CloudForms.

[IMPORTANT]
====
If you upgrade the target environment, you should xref:Upgrading_the_conversion_hosts[update the conversion hosts] to ensure that you have the latest software and patches.
====

.Prerequisites

* (VDDK only) download the VMware Virtual Disk Development Kit:
+
. Navigate to link:https://www.vmware.com/support/pubs/[].
. Click *VMware SDK & API Product Documentation* to expand.
. Click *VMware Virtual Disk Development Kit (VDDK)*.
. Click *Latest Releases* and select the latest VDDK release.
. Download and save the VDDK package (+VMware-vix-disklib-_version_.x86_64.tar.gz+).

* (VDDK and SSH) Generate an SSH key pair to connect to the VMware hypervisors.

.Procedure

THIS PROCEDURE IS FROM MOCKUPS, NOT REAL UI

. In CloudForms, click menu:Compute[Migration > Migration Settings].
. In the *Conversion Hosts* tab, click *Configure Conversion Host*.
. Perform the following procedures in the *Configure Conversion Host* wizard:

PLACEHOLDER: CONVERSION HOST UI SCREENSHOT

[cols="1,3", options="header"]
|===
|Screen |Procedure
|*Location*
.<a|. Select a *Provider Type*.
. Select a *Provider*.

. Select a Red Hat Virtualization *Cluster* / OpenStack Platform *Project*.

. Click *Next*.
|*Hosts*
.<a|. Select one or more hosts from the dropdown list.
. Click *Next*.
|*Authentication*
.<a|. Click *Browse* to browse to the SSH key or paste it in the *Conversion host SSH key* field.

* Red Hat Virtualization Manager deploys a private SSH key on the conversion hosts in order to send commands and run playbooks. The default key file is `/etc/pki/ovirt-engine/keys/engine_id_rsa` on the Manager machine.
* OpenStack Platform user uses a private SSH key to connect to the conversion hosts.

. Select *SSH* or *VDDK* as a *Transformation method*.

. If you selected SSH, lick *Browse* to browse to the SSH key or paste it in the *VMware hypervisors SSH key* field.
+
If you selected VDDK, enter the path of the VDDK package in the *VDDK library path* field and click *Validate*. Wait for validation to complete.

. Click *Configure*.
|*Results*
.<a|. Wait for the conversion host configuration to finish.
. Click *Close*.
|===

The configured conversion hosts and status information, including error messages, appear in the *Configured Conversion Hosts* list.

You are ready to xref:Configuring_the_ssh_connection_to_the_vmware_hypervisors[configure the SSH connection to the VMware hypervisors].

Optionally, you can click *Remove* to unconfigure a conversion host or *Retry* to retry a conversion host configuration.

[id="Configuring_the_ssh_connection_to_the_vmware_hypervisors"]
== Configuring the SSH connection to the VMware hypervisors

.Red Hat Virtualization

. Log in to each Red Hat Virtualization conversion host.

. Copy the public SSH key to each VMware hypervisor:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# ssh root@_esx1.example.com_ sh -c \
    "cat >> /etc/ssh/keys-root/authorized_keys" < /var/lib/vdsm/.ssh/id_rsa.pub
----

. Connect to each VMware hypervisor as `root` using SSH.

.OpenStack Platform

. Log in to each OpenStack Platform conversion host.

. Copy the public SSH key to each VMware hypervisor:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# ssh root@_esx1.example.com_ sh -c \
    "cat >> /etc/ssh/keys-root/authorized_keys" < /root/.ssh/id_rsa.pub
----

. Connect to each VMware hypervisor as `cloud-user` using SSH.

[id="Upgrading_the_conversion_hosts"]
== Upgrading the conversion hosts

If you upgrade your target environment, you should update the conversion hosts to ensure that you have the latest software and critical updates:

* Red Hat Virtualization:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# yum update
# cp /usr/share/ansible/roles/oVirt.ovirt-ansible-v2v-conversion-host/files/virt-v2v-wrapper.py /usr/bin/
----

* OpenStack Platform: Download the latest conversion host appliance and xref:Deploying_osp_conversion_hosts[re-deploy the conversion hosts]
