[id="Configuring_conversion_hosts_for_transformation"]
= Configuring conversion hosts for transformation

You can configure your conversion hosts for VDDK or SSH transformation. Configuring the conversion hosts for transformation involves the following key steps:

. VDDK only: xref:VDDK_only_Downloading_and_copying_VDDK[Downloading and copying the VDDK package]
. VDDK and SSH: xref:VDDK_and_SSH_Configuring_the_conversion_hosts[Configuring the conversion hosts]
. VDDK and SSH: xref:VDDK_and_SSH_Validating_the_transformation_configuration[Validating the configuration]
. SSH only: xref:SSH_only_Configuring_and_validating_the_SSH_connection[Configuring and validating the SSH connection]

[id='VDDK_only_Downloading_and_copying_VDDK']
== VDDK only: Downloading and copying VDDK

. Go to link:https://www.vmware.com/support/pubs/[VMware Documentation], click `VMware SDK & API Product Documentation` to expand, and click `VMware Virtual Disk Development Kit (VDDK)`.

. Click `Latest Releases` and select the latest VDDK release.

. Download the VDDK package (for example, `VMware-vix-disklib-_version_.x86_64.tar.gz`).

. Copy the VDDK package to a location that is accessible over `HTTP`, for example, `/var/www/html` on the Red Hat Virtualization Manager machine.

You are ready to configure the conversion hosts.

[id='VDDK_and_SSH_Configuring_the_conversion_hosts']
== VDDK and SSH: Configuring the conversion hosts

. Go to +/usr/share/ovirt-ansible-v2v-conversion-host-_version_/playbooks+ on the Manager machine (for Red Hat Virtualization) or on each conversion host (for OpenStack Platform).

. Create `extra_vars.yml` according to the following examples:

* Red Hat Virtualization conversion host using VDDK:
+
[options="nowrap" subs="+quotes,verbatim"]
----
---
v2v_host_type: rhv
# Transport methods to configure on the conversion host. Valid values: 'vddk', 'ssh' (on separate lines)
v2v_transport_methods:
  - vddk
# Maximum number of concurrent conversions per host. Default is '10'.
v2v_max_concurrent_conversions: _10_
# File name of ``.tar.gz package with VDDK library, located in /tmp.
v2v_vddk_package_name: "VMware-vix-disklib-_version_.x86_64.tar.gz"
v2v_vddk_package_url: "http://_path/to/downloaded_vddk_package_/{{ v2v_vddk_package_name }}"
manageiq_provider_name: RHV
manageiq_url: "https://_CloudForms_FQDN_"
manageiq_validate_certs: false
manageiq_zone_id: "42000000000001"
manageiq_providers:
  - name: "_RHV_"
    connection_configurations:
      - endpoint:
          role: "default"
          verify_ssl: true
          certificate_authority: |
            -----BEGIN CERTIFICATE-----
            MIIDoDCCAoigAwIBAgIBATANBgkqhkiG9w0BAQsFADA9MRswGQYDVQ....
            -----END CERTIFICATE-----
----
+
[NOTE]
====
The RHV certificate (`certificate_authority`) is `/etc/pki/ovirt-engine/apache-ca.pem` on the Manager machine.
====

* OpenStack Platform conversion host using SSH:
+
[options="nowrap" subs="+quotes,verbatim"]
----
---
v2v_host_type: openstack
v2v_transport_methods:
  - ssh
v2v_max_concurrent_conversions: _10_
manageiq_provider_name: OpenStack
manageiq_url: "https://_CloudForms_FQDN_"
manageiq_validate_certs: false
manageiq_zone_id: "42000000000001"
manageiq_providers:
  - name: "_OpenStack_"
    connection_configurations:
      - endpoint:
          role: "default"
          security_protocol: "ssl"
          certificate_authority: |
            -----BEGIN TRUSTED CERTIFICATE-----
            MIIDNzCCAh8CAQEwDQYJKoZIhvcNAQELBQAwYjELMAkGA1UEBhMCVV....
            -----END TRUSTED CERTIFICATE-----
            -----BEGIN TRUSTED CERTIFICATE-----
            MIIDlzCCAn+gAwIBAgIJAOP7AaT7dsLYMA0GCSqGSIb3DQEBCwUAMG....
            -----END TRUSTED CERTIFICATE-----
----
+
[NOTE]
====
The OpenStack Platform certificate chain (`certificate_authority`) concatenates two CA files:

* `/etc/pki/ca-trust/source/anchors/undercloud-cacert.pem` on the undercloud server
* `/etc/pki/ca-trust/anchors/overcloud-cacert.pem` on one of the overcloud controllers

If you deploy your own link:https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/13/html-single/director_installation_and_usage/#appe-SSLTLS_Certificate_Configuration[certificate authority], use the chain that signs the OpenStack Platform API certificates.
====

. Create an encrypted `secure_vars.yml` file for your passwords and keys:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# ansible-vault create secure_vars.yml
----

. Add the following lines to `secure_vars.yml`:
+
[options="nowrap" subs="+quotes,verbatim"]
----
---
# Use this file for sensitive information
# CloudForms `admin` user, for connecting to CloudForms
manageiq_username: "_username_"

# CloudForms `admin` password:
manageiq_password: "_password_"

# SSH private key
v2v_ssh_private_key: |
  -----BEGIN RSA PRIVATE KEY-----
  b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAlwAAAAdzc2gtcn....
  -----END RSA PRIVATE KEY-----
----

. Run the `conversion_host_enable` playbook to configure the conversion hosts for transformation:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# ansible-playbook -i `hostname`, -c local -b \
    -e @extra_vars.yml -e @secure_vars.yml --ask-vault-pass \
    /usr/share/ovirt-ansible-v2v-conversion-host/playbooks/conversion_host_enable.yml
----

[id="VDDK_and_SSH_Validating_the_transformation_configuration"]
== VDDK and SSH: Validating the configuration

. Run the `conversion_host_check` playbook to verify that the conversion hosts are configured correctly:

[options="nowrap" subs="+quotes,verbatim"]
----
# ansible-playbook --ask-vault-pass -i conversion_hosts_inventory.yml conversion_host_check.yml
----

If you are configuring the conversion hosts for VDDK transformation, you are ready to xref:Enabling_conversion_hosts_in_cloudforms[enable them] in CloudForms.

If you are configuring the conversion hosts for SSH transformation, you must configure the SSH connection.

[id="SSH_only_Configuring_and_validating_the_SSH_connection"]
== SSH only: Configuring and validating the SSH connection

. Enable SSH on the VMware hypervisors. (For details, see link:https://docs.vmware.com/en/VMware-vSphere/index.html[VMware vSphere Documentation]. In the left pane, click menu:vSphere _version_[ESXi and vCenter Server > VMware ESXi Installation and Setup > Installing and Setting Up ESXi > Setting Up ESXi > Enable ESXi Shell and SSH Access with the Direct Console User Interface].)

. Copy the SSH keys to all VMware hypervisors to ensure that each conversion host has the SSH key of the ESXi host in its `known_hosts` file:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# ssh root@_esx1.example.com_ sh -c \
    'cat >> /etc/ssh/keys-root/authorized_keys' < /var/lib/vdsm/.ssh/id_rsa.pub
----

. Connect to the VMware hypervisor using `ssh-agent`, the program that `virt-v2v` uses to connect to the hypervisor, to validate the SSH connection:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# sudo -u vdsm ssh-agent
SSH_AUTH_SOCK=/tmp/ssh-_Gi2oSn44DHNL_/agent.65904; export SSH_AUTH_SOCK;
SSH_AGENT_PID=65905; export SSH_AGENT_PID;
echo Agent pid 65905;

# sudo -u vdsm SSH_AUTH_SOCK=/tmp/ssh-_Gi2oSn44DHNL_/agent.65904 ssh-add
# sudo -u vdsm \
    SSH_AUTH_SOCK=/tmp/ssh-_Gi2oSn44DHNL_/agent.65904 ssh root@_esx1.example.com_
----
+
If the connection is successful, the conversion host is correctly configured for SSH transformation.

[NOTE]
====
Red Hat Virtualization only: If you are using SSSD with single sign-on, you must reinstall `ipa-client` without configuring the OpenSSH client. See xref:SSH_transformation_fails[SSH transformation failure] for details.
====

You are ready to xref:Enabling_conversion_hosts_in_cloudforms[enable the conversion hosts] in CloudForms.
