// Module included in the following assemblies:
// assembly_Configuring_conversion_hosts_for_transformation.adoc
[id="Configuring_the_{context}_conversion_hosts"]

.Prerequisites

* (VDDK only) Download the VMware Virtual Disk Development Kit:
+
. Navigate to link:https://www.vmware.com/support/pubs/[].
. Click *VMware SDK & API Product Documentation* to expand.
. Click *VMware Virtual Disk Development Kit (VDDK)*.
. Click *Latest Releases* and select the latest VDDK release.
. Download and save the VDDK package (+VMware-vix-disklib-_version_.x86_64.tar.gz+), recording its URL.

* (VDDK and SSH) Generate an SSH key pair to connect to the VMware hypervisors.

.Procedure

ifdef::rhv[]
. Connect to the Manager machine using SSH.
. Go to `/usr/share/ovirt-ansible-v2v-conversion-host/playbooks`.
endif::rhv[]
ifdef::osp[]
. Connect to a conversion host using SSH.
. Go to `/usr/share/ovirt-ansible-v2v-conversion-host/playbooks`.
endif::osp[]

. Create an `extra_vars.yml` file in this directory and update its parameters:
ifdef::rhv[]
+
[options="nowrap" subs="+quotes,verbatim"]
----
---
# Valid values: `rhevm`, `openstack`
v2v_host_type: rhevm

# Transport methods to configure on the conversion host. Valid values: `vddk`, `ssh`
v2v_transport_methods:
  - _vddk_

# Maximum number of concurrent conversions per host. Default is `10`.
v2v_max_concurrent_conversions: _10_

# File name of VDDK package
v2v_vddk_package_name: "VMware-vix-disklib-_version_.x86_64.tar.gz"

# URL of VDDK package
v2v_vddk_package_url: "http://_path_to_vddk_package_/{{ v2v_vddk_package_name }}"

manageiq_provider_name: 'RHV'

# Base URL of CloudForms machine
manageiq_url: "https://_CloudForms_FQDN_"

# Whether to validate certificate of CloudForms server. Default is `true`.
manageiq_validate_certs: _false_
manageiq_zone_id: "42000000000001"

# List of infrastructure providers
# Each provider is a dictionary with 3 attributes: `name`, `hostname`, and `connection_configurations`
manageiq_providers:
  - name: "_RHV_"
    hostname: _Manager_FQDN_or_IP_address_
    connection_configurations: <1>
      - endpoint:
          role: "default"
          verify_ssl: true <2>
          certificate_authority: | <3>
            -----BEGIN CERTIFICATE-----
            _MIIDoDCCAoigAwIBAgIBATANBgkqhkiG9w0BAQsFADA9MRswGQYDVQ...._
            -----END CERTIFICATE-----
----
<1> `connection_configurations` has a single endpoint, whose role is `default`.
<2> If you choose to verify the SSL certificate (`verify_ssl: true`), add the `certificate_authority`.
<3> The default `certificate_authority` is `/etc/pki/ovirt-engine/apache-ca.pem` on the Manager machine.
endif::rhv[]
ifdef::osp[]
+
[options="nowrap" subs="+quotes,verbatim"]
----
---
# Valid values: `rhevm`, `openstack`
v2v_host_type: openstack

# Transport methods to configure on the conversion host. Valid values: `vddk`, `ssh`
v2v_transport_methods:
  - _vddk_

# Maximum number of concurrent conversions per host. Default is `10`.
v2v_max_concurrent_conversions: _10_

# File name of VDDK package
v2v_vddk_package_name: "VMware-vix-disklib-_version_.x86_64.tar.gz"

# URL of VDDK package
v2v_vddk_package_url: "http://_path/to/downloaded_vddk_package_/{{ v2v_vddk_package_name }}"

manageiq_provider_name: OpenStack

# Base URL of CloudForms machine
manageiq_url: "https://_CloudForms_FQDN_"

# Whether to validate certificate of CloudForms server. Default is `true`.
manageiq_validate_certs: _false_
manageiq_zone_id: "42000000000001"

# List of cloud providers
# Each provider is a dictionary with 3 attributes: `name`, `hostname`, and `connection_configurations`
manageiq_providers:
  - name: "_OpenStack_"
    hostname: _controller_node_FQDN_or_IP_address_
    connection_configurations: <1>
      - endpoint:
          role: "default"
          security_protocol: "ssl" <2>
          certificate_authority: | <3>
            -----BEGIN TRUSTED CERTIFICATE-----
            _MIIDNzCCAh8CAQEwDQYJKoZIhvcNAQELBQAwYjELMAkGA1UEBhMCVV...._
            -----END TRUSTED CERTIFICATE-----
            -----BEGIN TRUSTED CERTIFICATE-----
            _MIIDlzCCAn+gAwIBAgIJAOP7AaT7dsLYMA0GCSqGSIb3DQEBCwUAMG...._
            -----END TRUSTED CERTIFICATE-----
----
<1> `connection_configurations` has a single endpoint, whose role is `default`.
<2> You can specify the connection security: `non-ssl`, `ssl-without-validation`, or `ssl`. If you choose `ssl`, add the CA chain (`certificate_authority`)
<3> The CA chain (`certificate_authority`) is a concatenation of two CA files:
+
* `/etc/pki/ca-trust/source/anchors/undercloud-cacert.pem` on the undercloud server
* `/etc/pki/ca-trust/anchors/overcloud-cacert.pem` on one of the overcloud controllers
+
If you deploy your own CA chain, use the chain that signs the OpenStack Platform API certificates (see link:https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/14/html-single/director_installation_and_usage/index#appe-SSLTLS_Certificate_Configuration[SSL/TLS Certificate Configuration] in _Red Hat OpenStack Platform Director Installation and Usage_).
endif::osp[]

. Create an encrypted `secure_vars.yml` file in the current directory:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# ansible-vault create secure_vars.yml
----

. Add the following variables to `secure_vars.yml` and save the file:
+
[options="nowrap" subs="+quotes,verbatim"]
----
---
# CloudForms `admin` user, for connecting to CloudForms
manageiq_username: "_username_"

# CloudForms `admin` password:
manageiq_password: "_password_"

# SSH private key to connect to VMware hypervisors. Required for both VDDK and SSH.
v2v_ssh_private_key: |
  -----BEGIN RSA PRIVATE KEY-----
  _b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAlwAAAAdzc2gtcn...._
  -----END RSA PRIVATE KEY-----
----

. Run the `conversion_host_enable` playbook:
+
ifdef::rhv[]
[options="nowrap" subs="+quotes,verbatim"]
----
# ansible-playbook -i _Manager_FQDN_or_IP_, -c local -b \
    -e @extra_vars.yml -e @secure_vars.yml --ask-vault-pass \
    /usr/share/ovirt-ansible-v2v-conversion-host/playbooks/conversion_host_enable.yml
----
endif::rhv[]
ifdef::osp[]
[options="nowrap" subs="+quotes,verbatim"]
----
# ansible-playbook -i _controller_node_FQDN_or_IP_, -c local -b \
    -e @extra_vars.yml -e @secure_vars.yml --ask-vault-pass \
    /usr/share/ovirt-ansible-v2v-conversion-host/playbooks/conversion_host_enable.yml
----
endif::osp[]
+
[WARNING]
====
Running the `conversion_host_enable` playbook more than once on the same host creates multiple entries in the CloudForms database for that host.

If you need to run the `conversion_host_enable` playbook again, you should remove the existing database entry by running the `conversion_host_disable` playbook on the host:

[options="nowrap" subs="+quotes,verbatim"]
----
# ansible-playbook /usr/share/ovirt-ansible-v2v-conversion-host/playbooks/conversion_host_disable.yml
----
====

. Run the `conversion_host_check` playbook to verify the conversion host configuration:
ifdef::rhv[]
+
[options="nowrap" subs="+quotes,verbatim"]
----
# ansible-playbook --ask-vault-pass -i _Manager_FQDN_or_IP_, conversion_host_check.yml
----
endif::rhv[]
ifdef::osp[]
+
[options="nowrap" subs="+quotes,verbatim"]
----
# ansible-playbook --ask-vault-pass -i _controller_node_FQDN_or_IP_, conversion_host_check.yml
----
+
* If you are configuring your OpenStack Platform conversion host for VDDK, you can xref:Migrating_the_infrastructure[migrate the infrastructure].
* If you are configuring your OpenStack Platform conversion host for SSH, you can xref:Configuring_ssh_connection_for_osp[configure the SSH connection to the VMware hypervisors].

:context: osp
:osp:
include::proc_Configuring_the_ssh_connection_to_vmware_hypervisors.adoc[]
:osp!:

.Updating OpenStack Platform conversion hosts[[Updating_osp_conversion_hosts]]

To ensure that you have the latest software and critical updates, download the latest conversion host appliance and redeploy the conversion hosts (see xref:Deploying_osp_conversion_hosts[Deploying the OpenStack Platform conversion hosts]).
endif::osp[]
ifdef::rhv[]
+
* If you are configuring your RHV conversion host for VDDK, you can xref:Enabling_conversion_hosts_in_cloudforms[authenticate the conversion hosts in CloudForms].

* If you are configuring your RHV conversion host for SSH, you can xref:Configuring_ssh_connection_for_rhv[configure the SSH connection to the VMware hypervisors].

:context: rhv
:rhv:
include::proc_Configuring_the_ssh_connection_to_vmware_hypervisors.adoc[]
:rhv!:

.Authenticating the RHV conversion host in CloudForms[[Enabling_conversion_hosts_in_cloudforms]]

. Click menu:Compute[Infrastructure > Hosts] and select a Red Hat Virtualization conversion host.
. Click the *Configuration* drop-down button, and select *Edit Selected items*.
. In the *Default* tab of the Endpoints section, enter the *Username* (root)  and the *Password*.
. Click *Validate* and wait for validation to complete.
. Click *Save*.
+
You can xref:Migrating_the_infrastructure[migrate the infrastructure].

.Updating the conversion hosts[[Updating_rhv_conversion_hosts]]

To ensure that you have the latest software and critical updates:

. Log in to the Manager machine using SSH.
. Update the packages and re-deploy `virt-v2v-wrapper`:

[options="nowrap" subs="+quotes,verbatim"]
----
# yum update
# cp /usr/share/ansible/roles/oVirt.ovirt-ansible-v2v-conversion-host/files/virt-v2v-wrapper.py /usr/bin/
----
endif::rhv[]
