[[Setting_up_an_ansible_environment]]
= Setting up an Ansible environment

You can perform automated tasks before and after a virtual machine is migrated, such as removing web servers from a load-balancing pool before migration and adding them back to the pool after migration.

Each task is an Ansible service catalog item, which you select in *Advanced Options* when you create the migration plan. You must create the Ansible service catalog item before creating the migration plan. The CloudForms inventory requires a minimum of one repository, one playbook, and one set of credentials.

To set up an Ansible environment and create a service catalog item:

[[Creating_an_Ansible_service_catalog_item]]
. Configure an link:https://access.redhat.com/documentation/en-us/red_hat_cloudforms/4.7/html/managing_providers/automation_management_providers#ansible-inside[Ansible repository] that is accessible to CloudForms.

. Create link:https://access.redhat.com/documentation/en-us/red_hat_cloudforms/4.7/html/managing_providers/automation_management_providers#ansible-credentials[Ansible credentials] for the virtual machines.

. Create an link:https://access.redhat.com/documentation/en-us/red_hat_cloudforms/4.7/html-single/provisioning_virtual_machines_and_hosts/#create-playbook-service-catalog-item[Ansible service catalog item].
