[id="Creating_conversion_hosts"]
= Creating the conversion hosts

The prerequisites apply to both Red Hat Virtualization and OpenStack Platform. See xref:Conversion_host_prerequisites[Conversion host prerequisites].

For Red Hat Virtualization, select the conversion hosts in your environment. See xref:Creating_RHV_conversion_hosts[Creating Red Hat Virtualization conversion hosts].

For OpenStack Platform, download the conversion appliance and create the conversion hosts. See xref:Creating_OSP_conversion_hosts[Creating OpenStack Platform conversion hosts].

[[Conversion_host_prerequisites]]
== Conversion host prerequisites

Before you create the conversion hosts, ensure that the following prerequisites are met:

* Decide how many conversion hosts to create. See xref:Number_of_conversion_hosts[How many conversion hosts to create]
* Choose VDDK or SSH transformation for the migration. See xref:datapath_transformation_options_vddk_ssh[Transformation options: VDDK or SSH]

[[Number_of_conversion_hosts]]
How many conversion hosts to create::
All the virtual machines in the migration plan are migrated at the same time. Therefore, the number of conversion hosts you create depends on the size of your migration. Multiple conversion hosts are recommended for load-balancing purposes, even for smaller migrations.
+
The number of virtual machines that you can migrate simultaneously depends on your infrastructure capabilities. Each migration requires a certain amount of network bandwidth, I/O throughput, and processing power for the conversion process. You should thoroughly test your environment before the migration to determine how many migrations it can support without negative effects.
+
Each conversion host is limited to `10` concurrent migrations, unless you  xref:Configuring_the_maximum_number_of_concurrent_migrations[change the default value].
+
[IMPORTANT]
====
The maximum number of concurrent virtual machine migrations per conversion host is `20` for both VDDK and SSH transformation. The SSH limitation, however, applies only to RHV 4.2.5, not to later versions of RHV.
====

[[datapath_transformation_options_vddk_ssh]]
Transformation options: VDDK or SSH::
Choose the transformation option, VDDK or SSH, that is appropriate for your environment:
+
* *VDDK*

** Recommended because it is approximately twice as fast as SSH
** Compiled with `nbdkit` to provide direct connectivity to the virtual machine disks
** Requires VDDK package download
** Requires the location of the VDDK library for conversion host configuration

* *SSH*

** Slower than VDDK
** Better suited for large-scale migrations than VDDK
** Does not require additional downloads, packages, tools, or compilation
** SSH access must be enabled on the source hypervisors
** Source and target environments must share SSH keys

[[Creating_RHV_conversion_hosts]]
== Creating Red Hat Virtualization conversion hosts

If you are migrating to Red Hat Virtualization, select one or more existing hosts (on physical machines, not virtual machines) to use as conversion hosts.

You can configure the conversion hosts for SSH or VDDK transformation. See xref:Configuring_conversion_hosts_for_transformation[].

[[Creating_OSP_conversion_hosts]]
== Creating OpenStack Platform conversion hosts

. Download the OpenStack Platform conversion appliance:

.. Go to the link:https://access.redhat.com/downloads/[Red Hat Customer Portal Product Downloads] site.
.. In the *A-Z* tab, click *Red Hat OpenStack Platform*.
.. Click the green *Download Latest* button to go to the OpenStack Platform download page.
.. Click the *Product Software* tab and download the `RHOSP V2V Image for Red Hat OpenStack Director (x86_64)`.
+
[NOTE]
====
Always download the latest version of the OpenStack Platform conversion appliance because it contains patches and fixes.

The conversion appliance for OpenStack Platform 14 may be used with OpenStack Platform 13.
====

. Upload the appliance to Glance storage.
. Deploy the appliance as a conversion host instance, with the following resources:

* 4 vCPUs
* 8 GB RAM
* `/tmp` (1 GB for each conversion)
* `/var/tmp` (1 GB for each conversion)
* `/var/logs` (5 GB)

. Add the SSH key for `cloud-user` in CloudForms:

.. Click menu:Compute[Clouds > Providers] and select the OpenStack Platform provider.
.. From the *Configuration* dropdown menu, select *Edit Selected Cloud Provider*.
.. Click the *RSA key pair* tab in the *Endpoints* section.
.. Enter the *Username*, `cloud-user`.
.. Click *Choose File*, browse to the SSH key file that you use to create OpenStack Platform instances, and click *Save*.

You are ready to configure the conversion hosts for SSH or VDDK transformation. See xref:Configuring_conversion_hosts_for_transformation[].
