[id="Creating_and_configuring_rhv_conversion_hosts_for_ssh_transformation"]
= Creating and Configuring RHV Conversion Hosts for SSH Transformation

Create and configure RHV conversion hosts for SSH transformation:

. Go to the Ansible conversion hosts playbooks directory on the Manager machine:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# cd /usr/share/ovirt-ansible-v2v-conversion-host/playbooks/
----

. Create a `conversion_hosts_inventory.yml` inventory file with the following variables:
+
[options="nowrap" subs="+quotes,verbatim"]
----
all:
  hosts:
    _host1.example.com_:
    _host2.example.com_:
  vars:
    ansible_ssh_private_key_file: /etc/pki/ovirt-engine/keys/engine_id_rsa
----

. Enable the conversion hosts:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# ansible-playbook -i conversion_hosts_inventory.yml conversion_host_enable.yml
----
+
[NOTE]
====
The Ansible role checks for the presence of the RHV guest tools ISO image in the ISO storage domain. This image is used to migrate Windows virtual machines.
====

. Verify that the conversion hosts are enabled:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# ansible-playbook -i conversion_hosts_inventory.yml conversion_host_check.yml
----

. Enable SSH on all the VMware hypervisors. See link:https://pubs.vmware.com/vsphere-6-5/index.jsp?topic=%2Fcom.vmware.vcli.getstart.doc%2FGUID-C3A44A30-EEA5-4359-A248-D13927A94CCE.html[Enable SSH from the vSphere Web Client] for details.
+
[NOTE]
====
If you created the RHV conversion hosts manually, without using the `ovirt-ansible-v2v-conversion-host` role, you must create the key pairs on each conversion host for the `vdsm` user:

[options="nowrap" subs="+quotes,verbatim"]
----
# install -o vdsm -g kvm -m 0700 -d /var/lib/vdsm/.ssh
# ssh-keygen -t rsa -N '' -C "vdsm@_hostname_" -f /var/lib/vdsm/.ssh/id_rsa
# chown vdsm:kvm /var/lib/vdsm/.ssh/id_rsa
----
====

. Copy the SSH keys to the VMware hypervisors:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# ssh root@_esx1.example.com_ sh -c \'cat >> /etc/ssh/keys-root/authorized_keys' < /var/lib/vdsm/.ssh/id_rsa.pub
----
+
[NOTE]
====
This step ensures that each conversion host has the SSH key of the ESXi host in its *known_hosts* file.
====

. Validate the configuration by connecting to the VMware hypervisor using `ssh-agent`, the program that `virt-v2v` uses to connect to the hypervisor:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# sudo -u vdsm ssh-agent
SSH_AUTH_SOCK=/tmp/ssh-_Gi2oSn44DHNL_/agent.65904; export SSH_AUTH_SOCK;
SSH_AGENT_PID=65905; export SSH_AGENT_PID;
echo Agent pid 65905;

# sudo -u vdsm SSH_AUTH_SOCK=/tmp/ssh-_Gi2oSn44DHNL_/agent.65904 ssh-add
# sudo -u vdsm \
    SSH_AUTH_SOCK=/tmp/ssh-_Gi2oSn44DHNL_/agent.65904 ssh root@_esx1.example.com_
----
+
If the connection is successful, the RHV conversion host is correctly configured for SSH transformation.

[NOTE]
====
If you are using SSSD with single sign-on, see xref:SSH_transformation_fails[Troubleshooting] for additional information.
====

After creating the RHV conversion hosts, you must configure them in CloudForms. See xref:Configuring_rhv_conversion_hosts_in_cloudforms[].

[discrete]
== Additional resources

* For more information, see link:https://github.com/oVirt/ovirt-ansible-v2v-conversion-host[V2V - Conversion Host - Ansible].
