// Module included in the following assemblies:
// con_Migration_plan_prerequisites.adoc
[id="Creating_a_csv_file_to_add_virtual_machines_to_the_migration_plan"]
= Creating a CSV file to add virtual machines to the migration plan

A CSV file is required if you are migrating virtual machines that were migrated in the past.

If you are migrating a large number of virtual machines, you have the option of creating a CSV file to add the source virtual machines to the migration plan.

The virtual machine `Name` is mandatory. `Provider`, `Host`, and `Cluster` are optional, to differentiate identical virtual machine names in different environments.

.Sample CSV file with `Name` (mandatory) and `Provider` (optional)

[options="nowrap" subs="+quotes,verbatim"]
----
Name,Provider
vm01,vSphere3
vm02,vSphere3
vm03,vSphere3
...
----

Duplicate virtual machines with no optional fields to differentiate them, or with duplicate optional fields, are marked with a red `x` and cannot be added to the migration plan.
