// Module included in the following assemblies:
// con_Migration_plan_options.adoc
[id="Creating_a_csv_file_to_add_virtual_machines_to_the_migration_plan"]
= Creating a CSV file to add virtual machines to the migration plan

If you are migrating virtual machines that were migrated in the past, you should create a CSV file to add the virtual machines to the migration plan because the migration plan cannot discover them automatically.

.Using a CSV file for large migrations (recommended)
[NOTE]
====
If you are migrating a large number of virtual machines, using a CSV file to add the virtual machines is faster than selecting them individually from a list of discovered virtual machines.
====

The CSV file format supports the following fields:

.CSV file fields
[cols="1,3", options="header"]
|===
|Field |Comments
|`Name` |Virtual machine name. Required
|`Host` |Optional. Only required if virtual machines have identical `Name` fields.
|`Provider` |Optional. Only required if virtual machines have identical `Name` and `Host` fields.
|===

Create a CSV file according to the following example:

.CSV file example
[options="nowrap" subs="+quotes,verbatim"]
----
Name,Host,Provider
vm01,host1,vSphere3
vm02,host1,vSphere3
vm03,host1,vSphere3
----
