// Module included in the following assemblies:
// assembly_Configuring_conversion_hosts_for_transformation.adoc
[id="Configuring_the_{context}_conversion_hosts"]

ifdef::rhv[]
Configuring the Red Hat Virtualization conversion hosts for VDDK or SSH transformation involves the following steps:

. Fulfilling the prerequisites
. Creating the `extra_vars.yml` and `secure_vars.yml` files
. Configuring the conversion host with the `conversion_host_enable` playbook
. Verifying the configuration with the `conversion_host_check` playbook
. SSH only: xref:Configuring_ssh_connection_for_rhv[Configuring the SSH connection to the VMware hypervisors]
. xref:Enabling_conversion_hosts_in_cloudforms[Authenticating the conversion hosts in CloudForms]
. (Optional) xref:Verifying_conversion_hosts[Verifying the name and number of conversion hosts in a browser]
endif::rhv[]
ifdef::osp[]
Configuring the OpenStack Platform conversion hosts for VDDK or SSH transformation involves the following steps:

. Fulfilling the prerequisites
. Creating the `extra_vars.yml` and `secure_vars.yml` files
. Configuring the conversion host with the `conversion_host_enable` playbook
. Verifying the configuration with the `conversion_host_check` playbook
. (SSH only) xref:Configuring_ssh_connection_for_osp[Configuring the SSH connection to the VMware hypervisors]
. (Optional) xref:Verifying_conversion_hosts[Verifying the name and number of conversion hosts in a browser]
endif::osp[]

.Prerequisites

VDDK only::
Download the VMware Virtual Disk Development Kit:
+
. Navigate to link:https://www.vmware.com/support/pubs/[].
. Click *VMware SDK & API Product Documentation* to expand.
. Click *VMware Virtual Disk Development Kit (VDDK)*.
. Click *Latest Releases* and select the latest VDDK release.
. Download and save the VDDK package (+VMware-vix-disklib-_version_.x86_64.tar.gz+), recording its URL.

VDDK and SSH::
Generate an SSH key pair to connect to the VMware hypervisors.

.Procedure

Perform the following procedure on each conversion host:

. Log in to a conversion host.
ifdef::rhv[]
. Install the `ovirt-ansible-v2v-conversion-host` package:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# yum install ovirt-ansible-v2v-conversion-host
----
+
[WARNING]
====
This command only works with RHEL hosts because the `ovirt-ansible-v2v-conversion-host` package is part of the `rhel-7-server-rpms` repository.

For RHVH hosts, you should copy the Manager's SSH key to each conversion host and run this procedure from the Manager machine.
====

. Go to `/usr/share/ovirt-ansible-v2v-conversion-host/playbooks`.

. Create an `extra_vars.yml` file in this directory and update its parameters:
+
[options="nowrap" subs="+quotes,verbatim"]
----
---
# Valid values: `rhevm`, `openstack`
v2v_host_type: rhevm

# Transport methods to configure on the conversion host. Valid values: `vddk`, `ssh`
v2v_transport_methods:
  - _vddk_

# Maximum number of concurrent conversions per host. Default is `10`.
v2v_max_concurrent_conversions: _10_

# File name of VDDK package
v2v_vddk_package_name: "VMware-vix-disklib-_version_.x86_64.tar.gz"

# URL of VDDK package
v2v_vddk_package_url: "http://_path_to_vddk_package_/{{ v2v_vddk_package_name }}"

manageiq_provider_name: 'RHV'

# Base URL of CloudForms machine
manageiq_url: "https://_CloudForms_FQDN_"

# Whether to validate certificate of CloudForms server. Default is `true`.
manageiq_validate_certs: _false_
manageiq_zone_id: "42000000000001"

# List of infrastructure providers
# Each provider is a dictionary with 3 attributes: `name`, `hostname`, and `connection_configurations`
manageiq_providers:
  - name: "_RHV_"
    hostname: _Manager_FQDN_or_IP_address_
    connection_configurations: <1>
      - endpoint:
          role: "default"
          verify_ssl: true <2>
          certificate_authority: | <3>
            -----BEGIN CERTIFICATE-----
            _MIIDoDCCAoigAwIBAgIBATANBgkqhkiG9w0BAQsFADA9MRswGQYDVQ...._
            -----END CERTIFICATE-----
----
<1> `connection_configurations` has a single endpoint, whose role is `default`.
<2> If you choose to verify the SSL certificate (`verify_ssl: true`), add the `certificate_authority`.
<3> The default `certificate_authority` is `/etc/pki/ovirt-engine/apache-ca.pem` on the Manager machine.
endif::rhv[]
ifdef::osp[]
. Go to `/usr/share/ovirt-ansible-v2v-conversion-host/playbooks`.

. Create an `extra_vars.yml` file in this directory and update its parameters:
+
[options="nowrap" subs="+quotes,verbatim"]
----
---
# Valid values: `rhevm`, `openstack`
v2v_host_type: openstack

# Transport methods to configure on the conversion host. Valid values: `vddk`, `ssh`
v2v_transport_methods:
  - _vddk_

# Maximum number of concurrent conversions per host. Default is `10`.
v2v_max_concurrent_conversions: _10_

# File name of VDDK package
v2v_vddk_package_name: "VMware-vix-disklib-_version_.x86_64.tar.gz"

# URL of VDDK package
v2v_vddk_package_url: "http://_path/to/downloaded_vddk_package_/{{ v2v_vddk_package_name }}"

manageiq_provider_name: OpenStack

# Base URL of CloudForms machine
manageiq_url: "https://_CloudForms_FQDN_"

# Whether to validate certificate of CloudForms server. Default is `true`.
manageiq_validate_certs: _false_
manageiq_zone_id: "42000000000001"

# List of cloud providers
# Each provider is a dictionary with 3 attributes: `name`, `hostname`, and `connection_configurations`
manageiq_providers:
  - name: "_OpenStack_"
    hostname: _controller_node_FQDN_or_IP_address_
    connection_configurations: <1>
      - endpoint:
          role: "default"
          security_protocol: "ssl" <2>
          certificate_authority: | <3>
            -----BEGIN TRUSTED CERTIFICATE-----
            _MIIDNzCCAh8CAQEwDQYJKoZIhvcNAQELBQAwYjELMAkGA1UEBhMCVV...._
            -----END TRUSTED CERTIFICATE-----
            -----BEGIN TRUSTED CERTIFICATE-----
            _MIIDlzCCAn+gAwIBAgIJAOP7AaT7dsLYMA0GCSqGSIb3DQEBCwUAMG...._
            -----END TRUSTED CERTIFICATE-----
----
<1> `connection_configurations` has a single endpoint, whose role is `default`.
<2> You can specify the connection security: `non-ssl`, `ssl-without-validation`, or `ssl`. If you choose `ssl`, add the CA chain (`certificate_authority`)
<3> The CA chain (`certificate_authority`) is a concatenation of two CA files:
+
* `/etc/pki/ca-trust/source/anchors/undercloud-cacert.pem` on the undercloud server
* `/etc/pki/ca-trust/anchors/overcloud-cacert.pem` on one of the overcloud controllers
+
If you deploy your own CA chain, use the chain that signs the OpenStack Platform API certificates (see link:https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/14/html-single/director_installation_and_usage/index#appe-SSLTLS_Certificate_Configuration[SSL/TLS Certificate Configuration] in _Red Hat OpenStack Platform Director Installation and Usage_).
endif::osp[]

. Create an encrypted `secure_vars.yml` file in the current directory:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# ansible-vault create secure_vars.yml
----

. Add the following variables to `secure_vars.yml` and save the file:
+
[options="nowrap" subs="+quotes,verbatim"]
----
---
# CloudForms `admin` user, for connecting to CloudForms
manageiq_username: "_username_"

# CloudForms `admin` password:
manageiq_password: "_password_"

# SSH private key to connect to VMware hypervisors. Required for both VDDK and SSH.
v2v_ssh_private_key: |
  -----BEGIN RSA PRIVATE KEY-----
  _b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAlwAAAAdzc2gtcn...._
  -----END RSA PRIVATE KEY-----
----

. Run the `conversion_host_enable` playbook:
+
ifdef::rhv[]
[options="nowrap" subs="+quotes,verbatim"]
----
# ansible-playbook -i _conversion_host_FQDN_or_IP_, -c local -b \
    -e @extra_vars.yml -e @secure_vars.yml --ask-vault-pass \
    /usr/share/ovirt-ansible-v2v-conversion-host/playbooks/conversion_host_enable.yml
----
+
If you are running the playbook from the Manager to configure a RHVH host:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# ansible-playbook -i _Manager_FQDN_or_IP_ -b \
    -e @extra_vars.yml -e @secure_vars.yml --ask-vault-pass \
    /usr/share/ovirt-ansible-v2v-conversion-host/playbooks/conversion_host_enable.yml
----
endif::rhv[]
ifdef::osp[]
[options="nowrap" subs="+quotes,verbatim"]
----
# ansible-playbook -i _conversion_host_FQDN_or_IP_, -c local -b \
    -e @extra_vars.yml -e @secure_vars.yml --ask-vault-pass \
    /usr/share/ovirt-ansible-v2v-conversion-host/playbooks/conversion_host_enable.yml
----
endif::osp[]
+
[WARNING]
====
Running the `conversion_host_enable` playbook more than once on the same host creates multiple entries in the CloudForms database for that host.

If you need to run the `conversion_host_enable` playbook again, you should remove the existing database entry by running the `conversion_host_disable` playbook on the host:

[options="nowrap" subs="+quotes,verbatim"]
----
# ansible-playbook /usr/share/ovirt-ansible-v2v-conversion-host/playbooks/conversion_host_disable.yml
----
====

. Run the `conversion_host_check` playbook to verify the conversion host configuration:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# ansible-playbook --ask-vault-pass -i _conversion_host_FQDN_or_IP_, conversion_host_check.yml
----
ifdef::osp[]
+
* If you are configuring your OpenStack Platform conversion host for VDDK, you can xref:Creating_an_infrastructure_mapping[create an infrastructure mapping]. Optionally, you can xref:Verifying_conversion_hosts[verify the conversion hosts] in a browser.
* If you are configuring your OpenStack Platform conversion host for SSH, you can xref:Configuring_ssh_connection_for_osp[configure the SSH connection to the VMware hypervisors].

:context: osp
:osp:
include::proc_Configuring_the_ssh_connection_to_vmware_hypervisors.adoc[leveloffset=+1]
:osp!:

endif::osp[]
ifdef::rhv[]
+
* If you are configuring your RHV conversion host for VDDK, you can xref:Enabling_conversion_hosts_in_cloudforms[authenticate the conversion hosts] in CloudForms.

* If you are configuring your RHV conversion host for SSH, you can xref:Configuring_ssh_connection_for_rhv[configure the SSH connection to the VMware hypervisors].

:context: rhv
:rhv:
include::proc_Configuring_the_ssh_connection_to_vmware_hypervisors.adoc[leveloffset=+1]
:rhv!:

== Authenticating the Red Hat Virtualization conversion hosts[[Enabling_conversion_hosts_in_cloudforms]]

In CloudForms, perform the following procedure for each Red Hat Virtualization conversion host:

. Click menu:Compute[Infrastructure > Hosts] and select a Red Hat Virtualization conversion host.
. Click the *Configuration* drop-down button and select *Edit Selected items*.
. In the *Default* tab of the Endpoints section, enter the *Username* and the *Password* for `root`.
. Click *Validate* and wait for validation to complete.
. Click *Save*.
+
You are ready to xref:Creating_an_infrastructure_mapping[create an infrastructure mapping]. Optionally, you can xref:Verifying_conversion_hosts[verify the conversion hosts] in a browser.
endif::rhv[]
