// Module included in the following assemblies:
// assembly_Creating_and_configuring_the_conversion_hosts.adoc
[id="Changing_the_maximum_number_of_concurrent_migrations"]
= (Optional) Changing the maximum number of concurrent migrations

You can change the maximum number of concurrent migrations for conversion hosts or providers to control the impact of the migration process on your infrastructure. The default is `10` for both a conversion host and a provider.

The provider's limit has priority over the conversion hosts' limits. For example, if a provider's limit is set to `20` and five conversion hosts' limits are set to `3`, the maximum number of concurrent migrations is `20`, not `15`.

.Changing the limit for conversion hosts

An increase affects all migration plans immediately. Virtual machines that are queued to migrate will migrate in greater numbers.

A decrease affects future migration plans. Migration plans that are in progress will continue to use the limit that was set when the plan was created.

[IMPORTANT]
====
The maximum number of concurrent migrations for a conversion host is `20`, for VDDK, and `40`, for SSH.
====

* To change the limit for all conversion hosts, click menu:Compute[Migration > Migration Settings] in CloudForms and select the new limit.

* To change the limit for a specific conversion host:

. Log in to the CloudForms machine using SSH.

. Change the limit of `host ?` to `?`:
+
[options="nowrap" subs="+quotes,verbatim"]
----
API PLACEHOLDER
----

.Changing the limit for a provider

. Log in to the CloudForms machine using SSH.

. Change the limit to `30`:
+
[options="nowrap" subs="+quotes,verbatim"]
----
API PLACEHOLDER
----
+
To get a provider's limit:
+
[options="nowrap" subs="+quotes,verbatim"]
----
API PLACEHOLDER
----
