// Module included in the following assemblies:
// assembly_Configuring_conversion_hosts_for_transformation.adoc
[id="Configuring_the_{context}_conversion_hosts"]

ifdef::rhv[]
Configuring the Red Hat Virtualization conversion hosts for VDDK or SSH transformation involves the following steps:

. VDDK only: xref:rhv_vddk_download[Downloading the VMware Virtual Disk Development kit]
. xref:Configuring_conversion_host_procedure_rhv[Configuring the conversion hosts]:
.. Installing the `ovirt-ansible-v2v-conversion-host` package
.. Creating the `extra_vars.yml` and `secure_vars.yml` files
.. Configuring the conversion host with the `conversion_host_enable` playbook
.. Verifying the configuration with the `conversion_host_check` playbook
.. SSH only: xref:Copying_VMware_keys_to_conversion_hosts_rhv[Copying the VMware keys to the conversion hosts]
.. SSH only: xref:Configuring_secure_remote_login_to_the_vmware_hypervisors_for_ssh_transformation[Configuring secure remote login to the VMware hypervisors]
. xref:Authenticating_the_red_hat_virtualization_conversion_hosts[Authenticating the conversion hosts in CloudForms]
. (Optional) xref:Verifying_conversion_hosts[Verifying the name and number of conversion hosts] in a browser
endif::rhv[]
ifdef::osp[]
Configuring the OpenStack Platform conversion hosts for VDDK or SSH transformation involves the following steps:

. VDDK only: xref:osp_vddk_download[Downloading the VMware Virtual Disk Development kit]
. xref:Configuring_conversion_host_procedure_osp[Configuring the conversion hosts]:
.. Creating the `extra_vars.yml` and `secure_vars.yml` files
.. Configuring the conversion host with the `conversion_host_enable` playbook
.. Verifying the configuration with the `conversion_host_check` playbook
.. SSH only: xref:Copying_VMware_keys_to_conversion_hosts_osp[Copying the VMware keys to the conversion hosts]
. (Optional) xref:Verifying_conversion_hosts[Verifying the name and number of conversion hosts] in a browser
endif::osp[]

.Prerequisite
ifdef::rhv[]
[id="rhv_vddk_download"]
endif::rhv[]
ifdef::osp[]
[id="osp_vddk_download"]
endif::osp[]
* VDDK only: Download the VMware Virtual Disk Development kit:
+
. Navigate to link:https://www.vmware.com/support/pubs/[].
. Click *VMware SDK & API Product Documentation* to expand.
. Click *VMware Virtual Disk Development Kit (VDDK)*.
. Click *Latest Releases* and select the latest VDDK release.
. Download and save the VDDK package (+VMware-vix-disklib-_version_.x86_64.tar.gz+), recording its URL.

.Procedure

ifdef::rhv[]
[[Configuring_conversion_host_procedure_rhv]]
Perform the following procedure on the Manager machine:

. Install the `ovirt-ansible-v2v-conversion-host` package:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# yum install ovirt-ansible-v2v-conversion-host
----

. Create an `extra_vars.yml` file and update its parameters:
+
[options="nowrap" subs="+quotes,verbatim"]
----
---
v2v_host_type: rhevm

# Transport methods to configure on the conversion host. Valid values: `vddk`, `ssh`
v2v_transport_methods:
  - _vddk_

# Maximum number of concurrent conversions per host. Default is `10`.
v2v_max_concurrent_conversions: _10_

# File name of VDDK package
v2v_vddk_package_name: "VMware-vix-disklib-_version_.x86_64.tar.gz"

# URL of VDDK package
v2v_vddk_package_url: "http://_path_to_vddk_package_/{{ v2v_vddk_package_name }}"

# Name of the CloudForms provider to which the conversion host belongs
manageiq_provider_name: RHV

# Base URL of CloudForms machine
manageiq_url: "https://_CloudForms_FQDN_"

# Whether to validate certificate of CloudForms server. Default is `true`.
manageiq_validate_certs: _false_

# To obtain the CloudForms zone ID, run this API call on the CloudForms machine:
# curl -sk -u admin http://_CloudForms_FQDN_/api/zones/?filter\[\]=name=RHV&expand=resources&attributes=zone
manageiq_zone_id: "42000000000001"

# List of infrastructure providers
# Each provider is a dictionary with 3 attributes: `name`, `hostname`, and `connection_configurations`
manageiq_providers:
  - name: "_RHV_"
    hostname: _Manager_FQDN_or_IP_address_
    connection_configurations: <1>
      - endpoint:
          role: "default"
          certificate_authority: | <2>
            -----BEGIN CERTIFICATE-----
            _MIIDoDCCAoigAwIBAgIBATANBgkqhkiG9w0BAQsFADA9MRswGQYDVQ...._
            -----END CERTIFICATE-----
----
<1> `connection_configurations` has a single endpoint, whose role is `default`.
<2> The CA certificate is stored as `/etc/pki/ovirt-engine/apache-ca.pem` on the Manager machine.
endif::rhv[]
ifdef::osp[]
[[Configuring_conversion_host_procedure_osp]]
Perform the following procedure on each conversion host:

. Go to `/usr/share/ovirt-ansible-v2v-conversion-host/playbooks`.
. Create an `extra_vars.yml` file and update its parameters:
+
[options="nowrap" subs="+quotes,verbatim"]
----
---
v2v_host_type: openstack

# Transport methods to configure on the conversion host. Valid values: `vddk`, `ssh`
v2v_transport_methods:
  - _vddk_

# Maximum number of concurrent conversions per host. Default is `10`.
v2v_max_concurrent_conversions: _10_

# File name of VDDK package
v2v_vddk_package_name: "VMware-vix-disklib-_version_.x86_64.tar.gz"

# URL of VDDK package
v2v_vddk_package_url: "http://_path/to/downloaded_vddk_package_/{{ v2v_vddk_package_name }}"

manageiq_provider_name: OpenStack

# Base URL of CloudForms machine
manageiq_url: "https://_CloudForms_FQDN_"

# Whether to validate certificate of CloudForms server. Default is `true`.
manageiq_validate_certs: _false_
manageiq_zone_id: "42000000000001"

# List of cloud providers
# Each provider is a dictionary with 3 attributes: `name`, `hostname`, and `connection_configurations`
manageiq_providers:
  - name: "_OpenStack_"
    hostname: _controller_node_FQDN_or_IP_address_
    connection_configurations: <1>
      - endpoint:
          role: "default"
          security_protocol: "ssl" <2>
          certificate_authority: | <3>
            -----BEGIN TRUSTED CERTIFICATE-----
            _MIIDNzCCAh8CAQEwDQYJKoZIhvcNAQELBQAwYjELMAkGA1UEBhMCVV...._
            -----END TRUSTED CERTIFICATE-----
            -----BEGIN TRUSTED CERTIFICATE-----
            _MIIDlzCCAn+gAwIBAgIJAOP7AaT7dsLYMA0GCSqGSIb3DQEBCwUAMG...._
            -----END TRUSTED CERTIFICATE-----
----
<1> `connection_configurations` has a single endpoint, whose role is `default`.
<2> You can specify the connection security: `non-ssl`, `ssl-without-validation`, or `ssl`. If you choose `ssl`, add the CA chain (`certificate_authority`)
<3> The CA chain (`certificate_authority`) is a concatenation of two CA files:
+
* `/etc/pki/ca-trust/source/anchors/undercloud-cacert.pem` on the undercloud server
* `/etc/pki/ca-trust/anchors/overcloud-cacert.pem` on one of the overcloud controllers
+
If you deploy your own CA chain, use the chain that signs the OpenStack Platform API certificates (see link:https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/14/html-single/director_installation_and_usage/index#appe-SSLTLS_Certificate_Configuration[SSL/TLS Certificate Configuration] in _Red Hat OpenStack Platform Director Installation and Usage_).
endif::osp[]

. Create an encrypted `secure_vars.yml` file:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# ansible-vault create secure_vars.yml
----

. Add the following variables to `secure_vars.yml` and save the file:
+
[options="nowrap" subs="+quotes,verbatim"]
----
---
# CloudForms `admin` user, for connecting to CloudForms
manageiq_username: "_username_"

# CloudForms `admin` password:
manageiq_password: "_password_"

# SSH private key to connect to VMware hypervisors. Required for both VDDK and SSH. <1>
v2v_ssh_private_key: |
  -----BEGIN RSA PRIVATE KEY-----
  _b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAlwAAAAdzc2gtcn...._
  -----END RSA PRIVATE KEY-----
----
<1> This is the private key of the SSH key pair that you created in xref:Configuring_the_vmware_hypervisors_for_ssh_transformation[].

. Run the `conversion_host_enable` playbook:
+
ifdef::rhv[]
[options="nowrap" subs="+quotes,verbatim"]
----
# ansible-playbook -i _conversion_host_FQDN_or_IP_, -b \
    -e "ansible_ssh_private_key_file=/etc/pki/ovirt-engine/keys/engine_id_rsa" \
    -e @extra_vars.yml -e @secure_vars.yml --ask-vault-pass \
    /usr/share/ovirt-ansible-v2v-conversion-host/playbooks/conversion_host_enable.yml
----
endif::rhv[]
ifdef::osp[]
[options="nowrap" subs="+quotes,verbatim"]
----
# ansible-playbook -i _conversion_host_FQDN_or_IP_, -c local -b \
    -e @extra_vars.yml -e @secure_vars.yml --ask-vault-pass \
    /usr/share/ovirt-ansible-v2v-conversion-host/playbooks/conversion_host_enable.yml
----
endif::osp[]
+
[WARNING]
====
Running the `conversion_host_enable` playbook more than once on the same host creates multiple entries in the CloudForms database for that host.

If you need to run the `conversion_host_enable` playbook again, you should remove the existing database entry by running the `conversion_host_disable` playbook on the host:

[options="nowrap" subs="+quotes,verbatim"]
----
# ansible-playbook /usr/share/ovirt-ansible-v2v-conversion-host/playbooks/conversion_host_disable.yml
----
====

. Run the `conversion_host_check` playbook to verify the conversion host configuration:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# ansible-playbook --ask-vault-pass -i _conversion_host_FQDN_or_IP_, conversion_host_check.yml
----
ifdef::rhv[]
+
* If you are using VDDK, you can authenticate the conversion hosts in CloudForms. See xref:Authenticating_the_red_hat_virtualization_conversion_hosts[].
* If you are using SSH, you are ready to copy the VMware keys to the conversion hosts. See xref:Copying_VMware_keys_to_conversion_hosts_rhv[].
endif::rhv[]
ifdef::osp[]
+
* If you are using VDDK, you can create an infrastructure mapping. See xref:Creating_an_infrastructure_mapping[].
* If you are using SSH, you are ready to copy the VMware keys to the conversion hosts. See xref:Copying_VMware_keys_to_conversion_hosts_osp[].
endif::osp[]

== Copying the VMware keys to the conversion hosts for SSH transformation
ifdef::rhv[]
[[Copying_VMware_keys_to_conversion_hosts_rhv]]
endif::rhv[]
ifdef::osp[]
[[Copying_VMware_keys_to_conversion_hosts_osp]]
endif::osp[]

To prevent man-in-the-middle attacks, the conversion hosts do not accept the VMware keys by default for SSH transformation. Instead, the `known_hosts` file of each conversion host must be populated with the public keys of the VMware hypervisors.

Depending on the security processes of your VMware environment, you can either obtain a list of public keys from the VMware system administrators, if they collected the keys when they xref:Configuring_the_vmware_hypervisors_for_ssh_transformation[enabled SSH access on the hypervisors], or you can use `ssh-keyscan`.

[WARNING]
====
You must run `ssh-keyscan` multiple times, once for each VMware hypervisor, and repeat the procedure on each conversion host. Otherwise your conversion hosts will not have all the VMware keys and the migration will fail.
====

.Gathering VMware keys with `ssh-keyscan` and copying them to conversion hosts

ifdef::rhv[]
Perform the following procedure on a conversion host:

. Run `ssh-keyscan` for each VMware hypervisor and output the public key to `known_hosts`, as in the following example:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# ssh-keyscan _esx1.example.com_ > /var/lib/vdsm/.ssh/known_hosts
# ssh-keyscan _esx2.example.com_ >> /var/lib/vdsm/.ssh/known_hosts
# ssh-keyscan _esx3.example.com_ >> /var/lib/vdsm/.ssh/known_hosts
----

. Change the ownership of the `known_hosts` file to user `vdsm` and group `kvm`:
+
----
# chown 36:36 /var/lib/vdsm/.ssh/known_hosts
----

. Repeat the procedure on each conversion host, to ensure that all the conversion hosts have all the VMware keys.
endif::rhv[]
ifdef::osp[]
Perform the following procedure on a conversion host:

. Run `ssh-keyscan` for each VMware hypervisor and output the public key to `known_hosts`, as in the following example:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# ssh-keyscan _esx1.example.com_ > /root/.ssh/known_hosts
# ssh-keyscan _esx2.example.com_ >> /root/.ssh/known_hosts
# ssh-keyscan _esx3.example.com_ >> /root/.ssh/known_hosts
----

. Repeat the procedure on each conversion host, to ensure that all the conversion hosts have all the VMware keys.
. Connect to each VMware hypervisor from each conversion host as `cloud-user` to verify the SSH connection.
+
[IMPORTANT]
====
If the SSH connection to a VMware hypervisor fails, check the following procedures:

* xref:Configuring_the_vmware_hypervisors_for_ssh_transformation[]
* xref:Copying_VMware_keys_to_conversion_hosts_osp[]
====
+
If the connection is successful, you can create an infrastructure mapping. See xref:Creating_an_infrastructure_mapping[].
+
Optionally, you can verify the conversion hosts in a browser. See xref:Verifying_conversion_hosts[].
endif::osp[]
ifdef::rhv[]
You are ready to configure secure remote login to the VMware hypervisors. See xref:Configuring_secure_remote_login_to_the_vmware_hypervisors_for_ssh_transformation[].

[id="Configuring_secure_remote_login_to_the_vmware_hypervisors_for_ssh_transformation"]
== Configuring secure remote login to the VMware hypervisors for SSH transformation

Perform the following procedure on the Manager machine:

. Enter the following command:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# sudo -u vdsm ssh-agent
----
+
The command returns this output:
+
[options="nowrap" subs="+quotes,verbatim"]
----
SSH_AUTH_SOCK=_socket_domain_; export SSH_AUTH_SOCK; <1>
SSH_AGENT_PID=139150; export SSH_AGENT_PID;
echo Agent pid 139150;
----
<1> The `socket_domain` format is +/tmp/ssh-_socket_number_/agent._pid_+.

. Enter the following commands, copying the _socket_domain_ from the output, to validate the SSH configuration for each VMware hypervisor:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# sudo -u vdsm SSH_AUTH_SOCK=_socket_domain_ ssh-add
# sudo -u vdsm \
    SSH_AUTH_SOCK=_socket_domain_ ssh root@_esx1.example.com_
----
+
[IMPORTANT]
====
These commands must be run for each VMware hypervisor.

If the last command fails, all migrations from this VMware hypervisor using SSH transformation will fail. Check the following procedures:

* xref:Configuring_the_vmware_hypervisors_for_ssh_transformation[]
* xref:Copying_VMware_keys_to_conversion_hosts_rhv[]
* xref:Configuring_secure_remote_login_to_the_vmware_hypervisors_for_ssh_transformation[].
====
+
If the SSH connection is successful, you can authenticate the conversion hosts in CloudForms. See xref:Authenticating_the_red_hat_virtualization_conversion_hosts[].

[id="Authenticating_the_red_hat_virtualization_conversion_hosts"]
== Authenticating the Red Hat Virtualization conversion hosts in CloudForms

Perform the following procedure for each Red Hat Virtualization conversion host:

. Click menu:Compute[Infrastructure > Hosts] and select a Red Hat Virtualization conversion host.
. Click the *Configuration* drop-down button and select *Edit Selected items*.
. In the *Default* tab of the Endpoints section, enter the *Username* and the *Password* for `root`.
. Click *Validate* and wait for validation to complete.
. Click *Save*.

You can create an infrastructure mapping. See xref:Creating_an_infrastructure_mapping[].

Optionally, you can verify the conversion hosts in a browser. See xref:Verifying_conversion_hosts[].
endif::rhv[]
