[id="Creating_conversion_hosts"]
= Creating conversion hosts

If you are migrating to Red Hat Virtualization, select one or more existing hosts (on physical machines, not virtual machines) to use as conversion hosts.

If you are migrating to OpenStack Platform:

. Download the OpenStack Platform conversion appliance from _TBD_.
. Upload the appliance to Glance storage.
. Deploy the appliance as a conversion host instance, with the following resources:

* 4 vCPUs
* 8 GB RAM
* `/tmp` (1 GB for each conversion)
* `/var/tmp` (1 GB for each conversion)
* `/var/logs` (5 GB)

. Add the SSH key for `cloud-user` in CloudForms:

.. Click menu:Compute[Clouds > Providers] and select the OpenStack Platform provider.
.. From the *Configuration* dropdown menu, select *Edit Selected Cloud Provider*.
.. Click the *RSA key pair* tab in the *Endpoints* section.
.. Enter the *Username*, `cloud-user`.
.. Click *Choose File*, browse to the SSH key file that you use to create OpenStack Platform instances, and click *Save*.

You are ready to configure the conversion hosts for xref:Configuring_conversion_hosts_for_transformation[transformation].
