// Module included in the following assemblies:
// proc_Configuring_conversion_hosts_for_transformation.adoc
[id="Configuring_ssh_connection_for_{context}"]
.Configuring the SSH connection to the VMware hypervisors

. Enable SSH access on all VMware hypervisors. For instructions, navigate to link:https://docs.vmware.com/en/VMware-vSphere/index.html[]. In the navigation pane, click menu:vSphere _version_[ESXi and vCenter Server > VMware ESXi Installation and Setup > Installing and Setting Up ESXi > Setting Up ESXi > Enable ESXi Shell and SSH Access with the Direct Console User Interface].

. Copy the public SSH key corresponding to the private SSH key in the `secure_vars.yml` file to each VMware hypervisor:
ifdef::rhv[]
+
[options="nowrap" subs="+quotes,verbatim"]
----
# ssh root@_esx1.example.com_ sh -c \
    'cat >> /etc/ssh/keys-root/authorized_keys' < /var/lib/vdsm/.ssh/id_rsa.pub
----

. Connect to each VMware hypervisor using `ssh-agent` to validate the SSH connection:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# sudo -u vdsm ssh-agent
SSH_AUTH_SOCK=/tmp/ssh-11111AAAAA/agent.12345; export SSH_AUTH_SOCK;
SSH_AGENT_PID=12345; export SSH_AGENT_PID;
echo Agent pid 12345;

# sudo -u vdsm SSH_AUTH_SOCK=/tmp/ssh-11111AAAAA/agent.12345 ssh-add
# sudo -u vdsm \
    SSH_AUTH_SOCK=/tmp/ssh-123456ABCDE/agent.12345 ssh root@_esx1.example.com_
----
+
If the connection is successful, the RHV conversion host is correctly configured for SSH transformation.
+
You can authenticate the RHV conversion host in CloudForms.

endif::rhv[]
ifdef::osp[]
+
[options="nowrap" subs="+quotes,verbatim"]
----
# ssh root@_esx1.example.com_ sh -c \
    'cat >> /etc/ssh/keys-root/authorized_keys' < /OpenStack_Platform/conversion_host_key/id_rsa.pub
----

. Connect to the VMware hypervisor as `cloud-user` to validate the SSH connection.
+
If the connection is successful, the OpenStack Platform conversion host is correctly configured for SSH transformation.
+
You can migrate the infrastructure.

endif::osp[]
