// Used in module: assembly_Conversion_hosts.adoc
[id="Configuring_the_maximum_number_of_concurrent_migrations"]
= Changing the maximum number of concurrent migrations

The default maximum number of concurrent migrations is `10` for conversion hosts and `10` for a provider. You can change these limits to control the impact of the migration process on your infrastructure.

The provider's limit has priority over the conversion hosts' limits. For example, if a provider's limit is set to `20` and 5 conversion hosts' limits are set to `3`, the maximum number of concurrent migrations is `20`, not `15`.

.Changing the maximum number of concurrent migrations for conversion hosts

An increase affects all migration plans immediately. Virtual machines that are queued to migrate will migrate in greater numbers.

A decrease affects future migration plans. Migration plans that are in progress will continue to use the limit that was set when the plan was created.

To change the maximum number of concurrent migrations of all conversion hosts:

* While configuring xref:VDDK_and_SSH_Configuring_the_conversion_hosts[conversion hosts for transformation], you can set the `v2v_max_concurrent_conversions` variable in `extra_vars.yml` to the new limit.

* After creating the conversion hosts, you can click menu:Compute[Migration > Migration Settings] in CloudForms and select the new limit.

To change the maximum number of concurrent migrations of a specific conversion host, enter the following command on the CloudForms machine:

[options="nowrap" subs="+quotes,verbatim"]
----
# vmdb
# rails console
irb(main):001:0> $evm = MiqAeMethodService::MiqAeService.new(MiqAeEngine::MiqAeWorkspaceRuntime.new)
irb(main):002:0> $evm.vmdb(:host).find_by(:name => "_host1.example.com_").custom_set("Max Transformation Runners", _20_)
----

.Changing the maximum number of concurrent migrations for a provider

To set a provider's limit to `30`, enter this command on the CloudForms machine:
[options="nowrap" subs="+quotes,verbatim"]
----
# vmdb
# rails console
irb(main):001:0> $evm = MiqAeMethodService::MiqAeService.new(MiqAeEngine::MiqAeWorkspaceRuntime.new)
irb(main):002:0> $evm.vmdb(:ext_management_system).find_by(:name => "_provider_").custom_set("Max Transformation Runners", _30_)
----

To get a provider's limit, enter this command on the CloudForms machine:
[options="nowrap" subs="+quotes,verbatim"]
----
# vmdb
# rails console
irb(main):001:0> $evm = MiqAeMethodService::MiqAeService.new(MiqAeEngine::MiqAeWorkspaceRuntime.new)
irb(main):002:0> $evm.vmdb(:ext_management_system).find_by(:name => "_provider_").custom_get("Max Transformation Runners")
----
