[id="Configuring_the_maximum_number_of_concurrent_migrations"]
= Changing the maximum number of concurrent migrations

The default limit for concurrent migrations is `10` for a conversion host and `10` for a provider.

.Changing the conversion host limit

To change the default limit for the conversion host, click menu:Compute[Migration > Migration Settings] and select the new limit for concurrent migrations.

This setting can be adjusted to throttle the migration process. If the maximum number of concurrent migrations is increased, the virtual machines that are queued to migrate will migrate in greater numbers. If the number is reduced, migration plans in progress will complete and future migration plans will reflect the lower number of concurrent migrations.

[IMPORTANT]
====
The maximum number of concurrent virtual machine migrations per conversion host is `20` for both VDDK and SSH. The SSH limitation applies only to RHV 4.2.5, not to later versions of RHV.
====

.Changing the provider limit

The limit that is set for the provider has priority over the limit set for the conversion host. For example, if you set the number of concurrent migrations to `20` at the provider level, while having `3` conversion hosts, the number of concurrent migrations is limited to `20` because the provider's setting overrides the conversion hosts' setting.

You can set and get `Max Transformation Runners` using the Rails console on the command line of the CloudForms machine:

* To set `Max Transformation Runners` for the provider to `30`:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# vmdb
# rails console
irb(main):001:0> $evm = MiqAeMethodService::MiqAeService.new(MiqAeEngine::MiqAeWorkspaceRuntime.new)
irb(main):002:0> $evm.vmdb(:ext_management_system).find_by(:name => "_provider_").custom_set("Max Transformation Runners", _30_)
----

* To get the configuration of `Max Transformation Runners` for the provider:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# vmdb
# rails console
irb(main):001:0> $evm = MiqAeMethodService::MiqAeService.new(MiqAeEngine::MiqAeWorkspaceRuntime.new)
irb(main):002:0> $evm.vmdb(:ext_management_system).find_by(:name => "_provider_").custom_get("Max Transformation Runners")
----
