// Module included in the following assemblies:
// con_Migration_plan_prerequisites.adoc
[id="Adding_ansible_playbooks_to_cloudforms"]
= Adding Ansible playbooks to CloudForms

You can add Ansible playbooks to CloudForms to perform automated tasks, for example, removing web servers from a load-balancing pool before migration and adding them back to the pool after migration.

[IMPORTANT]
====
If you are migrating virtual machines running RHEL or other Linux-based operating system, create a `RHEL premigration` playbook, to ensure that the IP addresses of these virtual machines are accessible after migration.
====

CloudForms requires a minimum of one Ansible playbook repository, one playbook, and one set of credentials.

.Procedure

. Enable the link:https://access.redhat.com/documentation/en-us/red_hat_cloudforms/4.6/html/managing_providers/automation_management_providers#enabling-embedded-ansible-server-role[`Embedded Ansible` role].

[id="Creating_an_Ansible_service_catalog_item"]
. Create an link:https://access.redhat.com/documentation/en-us/red_hat_cloudforms/4.7/html/managing_providers/automation_management_providers#ansible-inside[Ansible playbook repository].

. Add the link:https://access.redhat.com/documentation/en-us/red_hat_cloudforms/4.7/html/managing_providers/automation_management_providers#ansible-credentials[Ansible credentials] for your virtual machines.

. Add a playbook as an link:https://access.redhat.com/documentation/en-us/red_hat_cloudforms/4.7/html-single/provisioning_virtual_machines_and_instances/#create-playbook-service-catalog-item[Ansible service catalog item].

[id="Rhel_premigration_playbook"]
.`RHEL premigration` playbook

If you are migrating virtual machines running RHEL or other Linux-based operating system, create a `RHEL premigration` playbook that calls the Ansible link:https://galaxy.ansible.com/fdupont_redhat/ims_rhel_pre_migration[`ims.rhel_premigration` role].

[IMPORTANT]
====
This role is required for both Red Hat Virtualization and OpenStack Platform. Otherwise, you will not be able to access the IP addresses of the migrated virtual machines.
====

The `ims.rhel_premigration` role performs the following tasks on the source virtual machine:

* Preserves the static IP address configuration by creating udev rules to associate the VMware virtual machine's MAC address with its existing interface name (Red Hat Virtualization and OpenStack Platform)

* Installs the Red Hat Virtualization guest agent, which enables Red Hat Virtualization to report the IP address of the new virtual machine and to integrate it into the new environment (Red Hat Virtualization only)

[NOTE]
====
The `ims.rhel_premigration` role assumes that either the `rhel-6-server-rpms` or `rhel-7-server-rpms` repository is enabled in the VMware virtual machine when it installs `qemu-guest-agent`. If you have disabled the repository, re-enable it in the RHEL premigration playbook.
====

The following is an example of a `RHEL premigration` playbook that calls the `ims.rhel_pre_migration` role:

[source,yml]
----
---
- hosts: all
  roles:
    - role: ims.rhel_pre_migration
----

You will select this playbook as a xref:Advanced_options_screen[premigration playbook service] when you create the migration plan.
