// Used in module: assembly_Conversion_hosts.adoc
[id="Creating_conversion_hosts"]
= Creating the OpenStack Platform conversion hosts
[id="Creating_OSP_conversion_hosts"]
Create the OpenStack Platform conversion hosts.

.Procedure

. Download the OpenStack Platform conversion appliance:

.. Go to the link:https://access.redhat.com/downloads/[Red Hat Customer Portal Product Downloads] site.
.. In the *A-Z* tab, click *Red Hat OpenStack Platform*.
.. Click the green *Download Latest* button to go to the OpenStack Platform download page.
.. Click the *Product Software* tab and download the `RHOSP V2V Image for Red Hat OpenStack Director (x86_64)`.
+
[NOTE]
====
Always download the latest version of the OpenStack Platform conversion appliance because it contains patches and fixes.

The conversion appliance for OpenStack Platform 14 may be used with OpenStack Platform 13.
====

. Upload the appliance to Glance storage.
. Deploy the appliance as a conversion host instance, with the following resources:

* 4 vCPUs
* 8 GB RAM
* `/tmp` (1 GB for each conversion)
* `/var/tmp` (1 GB for each conversion)
* `/var/logs` (5 GB)

. Add the SSH key for `cloud-user` in CloudForms:

.. Click menu:Compute[Clouds > Providers] and select the OpenStack Platform provider.
.. From the *Configuration* dropdown menu, select *Edit Selected Cloud Provider*.
.. Click the *RSA key pair* tab in the *Endpoints* section.
.. Enter the *Username*, `cloud-user`.
.. Click *Choose File*, browse to the SSH key file that you use to create OpenStack Platform instances, and click *Save*.

You are ready to configure the conversion hosts for SSH or VDDK transformation. See xref:Configuring_conversion_hosts_for_transformation[].
