// Module included in the following assemblies:
// assembly_Creating_and_running_a_migration_plan.adoc
[id="Performing_premigration_tasks"]
= Performing premigration tasks

Perform the following premigration tasks if they are relevant to your migration:

* xref:Creating_a_csv_file_to_add_virtual_machines_to_the_migration_plan[Creating a CSV file to add virtual machines to the migration plan]
+
If you are migrating a large number of virtual machines, you can create a CSV file to add the virtual machines to the migration plan.
+
If you are migrating virtual machines that have been migrated in the past, use a CSV file to add the virtual machines to the migration plan. The migration plan cannot re-discover previously migrated virtual machines.

* xref:Setting_up_an_ansible_environment[Setting up an Ansible environment]
+
If you are using Ansible to automate pre- and post-migration tasks, set up an Ansible environment.

* xref:Configuring_the_rhel_premigration_playbook[Creating a RHEL premigration playbook for migrating RHEL virtual machines]
+
If you are migrating RHEL or other Linux virtual machines, set up an xref:Setting_up_an_ansible_environment[Ansible environment], and create a RHEL premigration playbook. You will add the RHEL premigration playbook to the migration plan.

include::proc_Creating_a_csv_file_to_add_virtual_machines_to_the_migration_plan.adoc[leveloffset=+1]
include::proc_Setting_up_an_ansible_environment.adoc[leveloffset=+1]
include::proc_Configuring_the_rhel_premigration_playbook.adoc[leveloffset=+1]
