[id="Preparing_the_osp_target_environment"]
= Preparing the Red Hat OpenStack Platform environment

To prepare the Red Hat OpenStack Platform environment for migration:

. Ensure that the storage backends have sufficient space for the virtual machines you are migrating.

. Set the BIOS settings of the physical hosts for optimal performance (rather than power-saving), according to the vendor's recommendations, and disable the C1E halt state, if applicable.

. Install link:https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/13/html-single/director_installation_and_usage/[Red Hat OpenStack Platform] 10 or later.

. Create link:https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/13/html-single/networking_guide/#create_a_network[provider networks] for the target instances to ensure that the IP addresses of the source virtual machines are preserved.

. Create a project for the conversion hosts and whatever projects you require for the target instances.

.   link:https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/13/html-single/storage_guide/#section-volumes-advanced-vol-type[Set at least one `volume type`] for the target block storage. Otherwise, CloudForms will not detect the storage during infrastructure mapping.

. Ensure that the user configured in CloudForms for the OpenStack Platform provider has `admin` privileges on the target projects.

. Configure security groups:
* A security group for the conversion hosts and CloudForms must have port 22 (SSH) enabled.
* A security group for CloudForms must have port 443 (HTTPS) enabled.
+
[NOTE]
====
Outbound traffic is enabled by default. If you have changed this setting, enable ports 902 (CloudForms to VMware) and 5480 (`virt-v2v` to vCenter).
====

. Create flavors suitable for the virtual machines that you are migrating. If you do not create custom flavors, CloudForms will try to map the source virtual machine to an existing flavor.

. Install link:https://access.redhat.com/documentation/en-us/red_hat_cloudforms/46/html-single/installing_red_hat_cloudforms_on_red_hat_openstack_platform/[Red Hat CloudForms] 4.6 or later.

. Add the link:https://access.redhat.com/documentation/en-us/red_hat_cloudforms/4.6/html-single/managing_providers/#vmware_vcenter_providers[VMware] and  link:https://access.redhat.com/documentation/en-us/red_hat_cloudforms/4.6/html-single/managing_providers/#adding_an_openstack_infrastructure_provider[OpenStack Platform] environments to CloudForms.
+
While you are adding OpenStack Platform to CloudForms (menu:Compute[Clouds > Providers > Add New Cloud Provider]), you must add the SSH key for `cloud-user`:

.. Click the *RSA key pair* tab in the *Endpoints* section.
.. Enter the *Username*, `cloud-user`.
.. Click *Choose File*, browse to the SSH key file for OpenStack Platform, and click *Add*.

. Create and configure the xref:Conversion_hosts[conversion hosts].
+
[NOTE]
====
For best performance, deploy the conversion hosts on a compute node with nested virtualization enabled.
====
