// Used in module: assembly_Preparation.adoc
[id="Preparing_the_vmware_source_environment"]
= Preparing the VMware environment

Prepare the VMware environment for migration:

. Extend the VMware network to the target environment.
+
[IMPORTANT]
====
The network configuration must not be changed in any way during the migration. IP addresses, VLANs, and other network configurations must be the same, before and after migration, because the conversion process preserves the source virtual machine MAC addresses.
====

. Unmount ISO/CDROM disks from the source virtual machines.

. Check that the source virtual machines do not have encrypted disks.

. Check that each NIC on each virtual machine has no more than 1 IPv4 and/or 1 IPv6 address.

. Install link:https://www.vmware.com/support/ws5/doc/new_guest_tools_ws.html[VMware Tools] on all source virtual machines to capture the IP addresses.

. Check that source virtual machine names contain only upper- or lower-case letters, numbers, underscores (`_`), hyphens (`-`), or periods (`.`). Special characters and spaces are not permitted.

. Red Hat Virtualization only: Check that the names of VMware virtual machines do not duplicate the names of existing RHV virtual machines.

You are ready to xref:Preparing_the_target_environment[prepare the target environment].
