[[Running_a_migration_plan]]
= Running a migration plan

You can run the migration plan immediately or in the future, depending on the schedule option that you selected.

== Running a migration plan immediately

The migration plan may take some time to complete. Progress bars indicate the amount of transferred data, the number of migrated virtual machines, and the elapsed time.

To view the migration progress of individual virtual machines:

. Click *Migration Plans in Progress*.
. Click the migration plan name to display the migration plan details.

[NOTE]
====
The counter that shows the migration plan progress in menu:Compute[Migration > Migration Plans] may be a few seconds ahead of the counter that appears in the migration plan details. This is because the migration plans counter displays the total time for running a migration plan, while the migration plan details counter displays the time for migrating the virtual machines.
====

== Running a migration plan in the future

The migration plan is saved in *Migration Plans Not Started* and will not run until you schedule or run it.

* To schedule a migration plan:

. Click the *Schedule* button.
. In the *Schedule Migration Plan* window, select a date and time and click *Schedule*. The plan's status is *Migration Scheduled* with the date and time.

* To run a scheduled plan immediately, click *Migrate*.

* To edit or delete a migration plan, click the *More Actions* icon.