[id="Configuring_the_rhel_premigration_playbook"]
= Creating a `RHEL pre-migration` playbook for migrating RHEL virtual machines

If you are migrating virtual machines with RHEL or other Linux operating systems, you must create a `RHEL pre-migration` playbook that calls the Ansible link:https://galaxy.ansible.com/fdupont_redhat/ims_rhel_pre_migration[`ims.rhel_pre_migration` role]. You will select this playbook to run as a xref:Advanced_options_screen[pre-migration task] when you create the migration plan.

[IMPORTANT]
====
This role is required for both Red Hat Virtualization and OpenStack Platform migrations. Otherwise, the migration will appear to be successful but you will not be able to access the IP addresses of the target virtual machines.
====

The `RHEL pre-migration` role performs the following tasks on a source virtual machine:

* Preserves the static IP address configuration by creating udev rules to associate the source virtual machine's MAC address with its existing interface name (Red Hat Virtualization and OpenStack Platform)
* Installs the Red Hat Virtualization guest agent, which enables Red Hat Virtualization to report the IP address of the new virtual machine and to integrate it into the new environment (Red Hat Virtualization only)

To create a `RHEL pre-migration` playbook:

. Set up an xref:Setting_up_an_ansible_environment[Ansible environment].

. Create a `RHEL pre-migration` playbook that calls the `ims.rhel_pre_migration` role:
+
[options="nowrap" subs="+quotes,verbatim"]
----
---
- hosts: all
  roles:
     - role: ims.rhel_pre_migration
----
+
[NOTE]
====
The `RHEL pre-migration` role assumes that the `rhel-6-server-rpms` or `rhel-7-server-rpms` repository is enabled in the source virtual machine when it installs `qemu-guest-agent`. If you have disabled the repository, you must enable it in the playbook.
====
