// Module included in the following assemblies:
// assembly_Migrating_the_infrastructure.adoc
[id="Running_a_migration_plan"]
= Running a migration plan

You can run a migration plan xref:Running_migration_plan_immediately[immediately] or in the xref:Running_migration_plan_future[future]. Optionally, you can xref:Canceling_a_migration_plan[cancel a migration plan in progress].

[NOTE]
====
For OpenStack Platform, source virtual machines must be powered on at the time of migration.
====

[id="Running_migration_plan_immediately"]
.Running a migration plan immediately

The migration plan may take some time to complete. Progress bars indicate the amount of transferred data, the number of migrated virtual machines, and the elapsed time.

To view the migration progress of individual virtual machines:

. Click *Migration Plans in Progress*.
. Click the migration plan name to display the migration plan details.
+
[NOTE]
====
The counter that shows the migration plan progress in menu:Compute[Migration > Migration Plans] may be a few seconds ahead of the counter that appears in the migration plan details. This is because the migration plans counter displays the total time for running a migration plan, while the migration plan details counter displays the time for migrating the virtual machines.
====

:context: immediately
include::proc_Validating_a_migration_plan.adoc[]

[id="Running_migration_plan_future"]
.Running a migration plan in the future

The migration plan is saved in *Migration Plans Not Started* and will not run until you schedule or run it.

To schedule a migration plan:

. Click the *Schedule* button.
. In the *Schedule Migration Plan* window, select a date and time and click *Schedule*. The plan's status is *Migration Scheduled* with the date and time.
+
You can click *Migrate* to run a scheduled migration plan immediately.

To edit or delete a migration plan, click the *More Actions* icon.

:context: in_the_future
include::proc_Validating_a_migration_plan.adoc[]

[id="Canceling_a_migration_plan"]
.(Optional) Canceling a migration plan in progress

To cancel a migration plan that has started:

. In menu:Compute[Migration > Migration Plans], click *Migration Plans in Progress*.
. Select a migration plan and click *Cancel Migration*.
. Click *Cancel Migrations* to confirm the cancellation. The canceled migration appears in *Migration Plans Complete* with a red `x` indicating that the plan did not complete successfully.

You can click *Retry* to run the migration plan immediately or *Schedule* to run the migration plan in the future.

Click the *More Actions* button to archive, edit, or delete the migration plan.
