// Module included in the following assemblies:
// proc_Configuring_conversion_hosts_for_transformation.adoc
[id="Configuring_ssh_connection_for_{context}"]

ifdef::rhv[]
= Configuring the SSH connection to the VMware hypervisors for Red Hat Virtualization
endif::rhv[]
ifdef::osp[]
= Configuring the SSH connection to the VMware hypervisors for OpenStack Platform
endif::osp[]

. Enable SSH access on all VMware hypervisors.
+
For instructions, navigate to link:https://docs.vmware.com/en/VMware-vSphere/index.html[]. In the navigation pane, click menu:vSphere _version_[ESXi and vCenter Server > VMware ESXi Installation and Setup > Installing and Setting Up ESXi > Setting Up ESXi > Enable ESXi Shell and SSH Access with the Direct Console User Interface].

ifdef::rhv[]
. On the Manager machine, copy the public SSH key corresponding to the private SSH key in the `secure_vars.yml` file to each VMware hypervisor:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# ssh root@_esx1.example.com_ sh -c \
    "cat >> /etc/ssh/keys-root/authorized_keys" < /var/lib/vdsm/.ssh/id_rsa.pub
----

. On the Manager machine, enter this command:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# sudo -u vdsm ssh-agent
----
+
The command returns output:
+
[options="nowrap" subs="+quotes,verbatim"]
----
SSH_AUTH_SOCK=_socket_domain_; export SSH_AUTH_SOCK; <1>
SSH_AGENT_PID=139150; export SSH_AGENT_PID;
echo Agent pid 139150;
----
<1> The `socket_domain` has the following format: +/tmp/ssh-_socket_number_/agent._pid_+.

. Enter the following commands with the correct parameters:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# sudo -u vdsm SSH_AUTH_SOCK=_socket_domain_ ssh-add
# sudo -u vdsm \
    SSH_AUTH_SOCK=_socket_domain_ ssh root@_esx1.example.com_
----
+
You are ready to authenticate the conversion hosts in CloudForms.

endif::rhv[]
ifdef::osp[]
. On each OpenStack Platform conversion host, copy the public SSH key corresponding to the private SSH key in the `secure_vars.yml` file to each VMware hypervisor:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# ssh root@_esx1.example.com_ sh -c \
    "cat >> /etc/ssh/keys-root/authorized_keys" < /root/.ssh/id_rsa.pub
----

. On each OpenStack Platform conversion host, connect to each VMware hypervisor as `cloud-user` to validate the SSH connection.
+
You are ready to xref:Creating_an_infrastructure_mapping[create an infrastructure mapping]. Optionally, you can xref:Verifying_conversion_hosts[verify the conversion hosts] in a browser.
endif::osp[]
