[id="Configuring_conversion_hosts_for_vddk_transformation"]
= Configuring conversion hosts for VDDK transformation

You can configure the conversion hosts for VDDK transformation by downloading the VDDK package and running a playbook to configure the conversion hosts.

To download the VDDK package:

. Go to link:https://www.vmware.com/support/pubs/[VMware Documentation], click `VMware SDK & API Product Documentation` to expand, and click `VMware Virtual Disk Development Kit (VDDK)`.

. Click `Latest Releases` and select the latest VDDK release.

. Download the SDK package (for example, `VMware-vix-disklib-6.5.3-8315684.x86_64.tar.gz`) to your local machine.

To configure the conversion hosts, perform the following steps on the Manager machine, for Red Hat Virtualization, or on each conversion host, for OpenStack Platform:

. Using SCP, copy the VDDK package to `/var/www/html`.

. Create +/usr/share/ovirt-ansible-v2v-conversion-host-_version_/playbooks/conversion_hosts_inventory.yml+ according to the following example (for more options, see xref:Ansible_conversion_hosts_inventory_file_example[]):
+
[options="nowrap" subs="+quotes,verbatim"]
----
all:
  hosts:
    host1.example.com:
      manageiq_provider_name: "RHV"
#     manageiq_provider_name: "OpenStack"
      v2v_host_type: rhv
#     v2v_host_type: openstack
      v2v_transport_methods:
        - vddk
    host2.example.com:
  vars:
      ansible_ssh_private_key_file: /etc/pki/ovirt-engine/keys/engine_id_rsa
      v2v_vddk_package_name: VMware-vix-disklib-version.x86_64.tar.gz
      v2v_vddk_package_url: http://FQDN/VMware-vix-disklib-version.x86_64.tar.gz
      manageiq_url: "https://CloudForms_FQDN"
      manageiq_username: admin
      manageiq_password: password
      manageiq_zone_id: 4200000001
      manageiq_providers:
        - name: "provider"
        connection_configuration:
          - endpoint:
              role: default
              verify_ssl: false
----

. Enable the conversion hosts:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# ansible-playbook -i conversion_hosts_inventory.yml conversion_host_enable.yml
----

. Verify that the conversion hosts are enabled:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# ansible-playbook -i conversion_hosts_inventory.yml conversion_host_check.yml
----

After configuring the conversion hosts, you can xref:Enabling_conversion_hosts_in_cloudforms[enable them] in CloudForms.
