// Module included in the following assemblies:
// assembly_Creating_and_configuring_the_conversion_hosts.adoc
[id="Configuring_conversion_hosts_for_transformation"]
= Configuring the conversion hosts for VDDK or SSH transformation

Configuring the conversion hosts for VDDK or SSH transformation involves the following key steps:

. VDDK only: xref:VDDK_only_Downloading_and_copying_VDDK[Downloading and copying the VDDK package]
. VDDK and SSH: xref:VDDK_and_SSH_Configuring_the_conversion_hosts[Configuring the conversion hosts]
. VDDK and SSH: xref:VDDK_and_SSH_Validating_the_transformation_configuration[Validating the VDDK or SSH transformation configuration]
. SSH only: xref:SSH_only_Configuring_and_validating_the_SSH_connection[Configuring and validating the SSH connection]

[id='VDDK_only_Downloading_and_copying_VDDK']
== VDDK only: Downloading and copying the VDDK package

. Go to the link:https://www.vmware.com/support/pubs/[VMware Documentation site], click `VMware SDK & API Product Documentation` to expand, and click `VMware Virtual Disk Development Kit (VDDK)`.

. Click `Latest Releases` and select the latest VDDK release.

. Download the VDDK package, +VMware-vix-disklib-_version_.x86_64.tar.gz+.

. Copy the VDDK package to a location that is accessible over `HTTP`, for example, `/var/www/html` on the Red Hat Virtualization Manager machine.

You are ready to configure the conversion hosts.

[id='VDDK_and_SSH_Configuring_the_conversion_hosts']
== VDDK and SSH: Configuring the conversion hosts

. Go to `/usr/share/ovirt-ansible-v2v-conversion-host/playbooks` on the Manager machine (for Red Hat Virtualization) or on each conversion host (for OpenStack Platform).

. Generate an SSH key pair to connect to the VMware hypervisors over SSH.
+
[NOTE]
====
You must create the SSH key pair, regardless of the chosen transformation method.
====

. Create `extra_vars.yml` according to the following examples:

* Red Hat Virtualization conversion host using VDDK:
+
[options="nowrap" subs="+quotes,verbatim"]
----
---
v2v_host_type: rhv

# Transport methods to configure on the conversion host. Valid values: 'vddk', 'ssh' (on separate lines)
v2v_transport_methods:
  - vddk

# Maximum number of concurrent conversions per host. Default is '10'.
v2v_max_concurrent_conversions: _10_ <1>

# File name of VDDK package
v2v_vddk_package_name: "VMware-vix-disklib-_version_.x86_64.tar.gz"

# URL of VDDK package
v2v_vddk_package_url: "http://_path/to/downloaded_vddk_package_/{{ v2v_vddk_package_name }}"

manageiq_provider_name: RHV

# Base URL of CloudForms machine
manageiq_url: "https://_CloudForms_FQDN_"

# Whether to validate certificate of CloudForms server. Default is 'true'
manageiq_validate_certs: _false_
manageiq_zone_id: "42000000000001"

# List of cloud or infrastructure providers
# Each provider is a dictionary with 3 attributes: `name`, `hostname`, and `connection_configurations`
manageiq_providers:
  - name: "_RHV_"
    hostname: _FQDN_or_IP_
    connection_configurations:
      - endpoint:
          role: "default"
          verify_ssl: true <2>
          certificate_authority: |
            -----BEGIN CERTIFICATE-----
            MIIDoDCCAoigAwIBAgIBATANBgkqhkiG9w0BAQsFADA9MRswGQYDVQ....
            -----END CERTIFICATE-----
----
+
<1> `v2v_max_concurrent_conversions` sets the xref:Changing_the_maximum_number_of_concurrent_migrations[maximum number of concurrent migrations] for all conversion hosts. The default is `10`.
<2> RHV `connection_configurations` has a single endpoint, whose role is `default`. If you choose to verify the SSL certificate (`verify_ssl: true`), you must provide the CA chain (`certificate_authority`), found in `/etc/pki/ovirt-engine/apache-ca.pem` on the Manager machine.

* OpenStack Platform conversion host using SSH:
+
[options="nowrap" subs="+quotes,verbatim"]
----
---
v2v_host_type: openstack
v2v_transport_methods:
  - ssh
v2v_max_concurrent_conversions: _10_
manageiq_provider_name: OpenStack
manageiq_url: "https://_CloudForms_FQDN_"
manageiq_validate_certs: false
manageiq_zone_id: "42000000000001"
manageiq_providers:
  - name: "_OpenStack_"
    hostname: _FQDN_or_IP_
    connection_configurations:
      - endpoint:
          role: "default"
          # Valid values: `non-ssl`, `ssl-without-validation`, `ssl`. `ssl` requires `certificate_authority`.<1>
          security_protocol: "ssl"
          certificate_authority: |
            -----BEGIN TRUSTED CERTIFICATE-----
            MIIDNzCCAh8CAQEwDQYJKoZIhvcNAQELBQAwYjELMAkGA1UEBhMCVV....
            -----END TRUSTED CERTIFICATE-----
            -----BEGIN TRUSTED CERTIFICATE-----
            MIIDlzCCAn+gAwIBAgIJAOP7AaT7dsLYMA0GCSqGSIb3DQEBCwUAMG....
            -----END TRUSTED CERTIFICATE-----
----
+
<1> If you select `ssl` as the security protocol, you must provide a CA chain (`certificate_authority`), which is a concatenation of the following CA files:
+
* `/etc/pki/ca-trust/source/anchors/undercloud-cacert.pem` on the undercloud server
* `/etc/pki/ca-trust/anchors/overcloud-cacert.pem` on one of the overcloud controllers
+
If you deploy your own link:https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/13/html-single/director_installation_and_usage/#appe-SSLTLS_Certificate_Configuration[certificate authority], use the chain that signs the OpenStack Platform API certificates.

. Create an encrypted `secure_vars.yml` file for your passwords and keys:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# ansible-vault create secure_vars.yml
----

. Add the following lines to `secure_vars.yml`:
+
[options="nowrap" subs="+quotes,verbatim"]
----
---
# Use this file for sensitive information
# CloudForms `admin` user, for connecting to CloudForms
manageiq_username: "_username_"

# CloudForms `admin` password:
manageiq_password: "_password_"

# SSH private key to connect to VMware hypervisors.
# You will later copy this key to the VMware hypervisors if you use SSH transformation.
v2v_ssh_private_key: |
  -----BEGIN RSA PRIVATE KEY-----
  b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAlwAAAAdzc2gtcn....
  -----END RSA PRIVATE KEY-----
----

. Run the `conversion_host_enable` playbook to configure the conversion hosts for transformation:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# ansible-playbook -i `hostname`, -c local -b \
    -e @extra_vars.yml -e @secure_vars.yml --ask-vault-pass \
    /usr/share/ovirt-ansible-v2v-conversion-host/playbooks/conversion_host_enable.yml
----
+
[IMPORTANT]
====
Running the `conversion_host_enable` playbook more than once on the same host creates multiple entries in the CloudForms database for the same host. If you need to run the `conversion_host_enable` playbook again, first remove the existing database entry by running the `conversion_host_disable` playbook on the same host:

[options="nowrap" subs="+quotes,verbatim"]
----
# ansible-playbook /usr/share/ovirt-ansible-v2v-conversion-host/playbooks/conversion_host_disable.yml
----
====

[id="VDDK_and_SSH_Validating_the_transformation_configuration"]
== VDDK and SSH: Validating the transformation configuration

Run the `conversion_host_check` playbook to verify that the conversion hosts are configured correctly for VDDK or SSH transformation:

[options="nowrap" subs="+quotes,verbatim"]
----
# ansible-playbook --ask-vault-pass -i conversion_hosts_inventory.yml conversion_host_check.yml
----

If the conversion hosts are configured correctly, proceed to the next step:

* VDDK:
** Red Hat Virtualization: xref:Authenticating_rhv_conversion_hosts_in_cloudforms[Authenticate the conversion hosts] in CloudForms.
** OpenStack Platform: Create an xref:Creating_an_Infrastructure_Mapping[infrastructure mapping].

* SSH
** All environments: xref:SSH_only_Configuring_and_validating_the_SSH_connection[Configure and validate the SSH connection].

[id="SSH_only_Configuring_and_validating_the_SSH_connection"]
== SSH only: Configuring and validating the SSH connection

. Enable SSH on all VMware hypervisors.
+
For instructions, go to the link:https://docs.vmware.com/en/VMware-vSphere/index.html[VMware vSphere Documentation site]. In the navigation pane, click menu:vSphere _version_[ESXi and vCenter Server > VMware ESXi Installation and Setup > Installing and Setting Up ESXi > Setting Up ESXi > Enable ESXi Shell and SSH Access with the Direct Console User Interface].

. Copy the public key you created in xref:VDDK_and_SSH_Configuring_the_conversion_hosts[] to each VMware hypervisor to ensure that the Manager or the OpenStack Platform conversion host has the SSH key of the VMware hypervisor in its `known_hosts` file:
+
[options="nowrap" subs="verbatim"]
----
# ssh root@_esx1.example.com_ sh -c \
    'cat >> /etc/ssh/keys-root/authorized_keys' < /var/lib/vdsm/.ssh/id_rsa.pub
#   'cat >> /etc/ssh/keys-root/authorized_keys' < /OpenStack_Platform/conversion_host_key/id_rsa.pub
----

.Red Hat Virtualization

Connect to the VMware hypervisor using `ssh-agent` to validate the SSH connection:

[options="nowrap" subs="+quotes,verbatim"]
----
# sudo -u vdsm ssh-agent
SSH_AUTH_SOCK=/tmp/ssh-11111AAAAA/agent.12345; export SSH_AUTH_SOCK;
SSH_AGENT_PID=12345; export SSH_AGENT_PID;
echo Agent pid 12345;

# sudo -u vdsm SSH_AUTH_SOCK=/tmp/ssh-11111AAAAA/agent.12345 ssh-add
# sudo -u vdsm \
    SSH_AUTH_SOCK=/tmp/ssh-123456ABCDE/agent.12345 ssh root@_esx1.example.com_
----

[IMPORTANT]
====
If you are using SSSD with single sign-on, reinstall `ipa-client` without configuring the OpenSSH client. See xref:SSH_transformation_fails[SSH transformation failure] for details.
====

You are ready to xref:Authenticating_rhv_conversion_hosts_in_cloudforms[authenticate the Red Hat Virtualization conversion hosts] in CloudForms.

.OpenStack Platform

Connect to the VM hypervisor as `cloud-user` to validate the SSH connection.

If the connection is successful, the conversion host is correctly configured for SSH transformation.

You are ready to xref:Verifying_conversion_hosts[verify the conversion hosts].
