[id="Known_issues"]
= Known Issues

Migration cancellation is not working as intended with the initial IMS 1.1 release. A hotfix can be requested to resolve this problem by contacting xref:[Red Hat Support]. This issue will be resolved in a future release.

Migrate user interface may display an error if conversion hosts are improperly configured. This will be addressed in an upcoming release.

The conversion host enable playbook contains an issue with virt-v2v-wrapper that causes VM migration to Red Hat OpenStack to fail. After deploying the IMS solution, please download the latest version of the conversion host appliance for Red Hat OpenStack 14. If deploying RHV 4.2.8, please run yum update to capture the latest packages post deployment.

Running the conversion host enable playbook more than one time will create multiple entries in the CloudForms database for the same host.  If there is a need to run the enable playbook more than one time on the same host, run the disable playbook first prior to running enable.  This issue will be resolved in a future release.
