// Module included in the following assemblies:
// assembly_Troubleshooting.adoc
[id="Migration_logs"]
= Migration logs

You can check the conversion host logs and the CloudForms migration log for errors.

.Conversion host logs

When disk migration starts, two logs are created in the conversion host:

* `virt-v2v`: Debug output from `virt-v2v` itself. This log tracks the core of the virtual machine process, including `libguestfs` traces and disk migration details.
* `virt-v2v-wrapper`: Log of the daemonizing wrapper for `virt-v2v`. This log traces the orchestration of the virtual machine conversion on the conversion host, including disk migration percentages and `virt-v2v` error reporting.

[IMPORTANT]
====
 If you need to open a link:https://access.redhat.com/support/cases/#/case/new[Red Hat Support call], you will be required to submit both the migration (`virt-v2v`) log and `virt-v2v-wrapper` log for analysis.
====

Accessing the `virt-v2v` and `virt-v2v-wrapper` logs on the conversion host::

. Log in to the conversion host using SSH.
+
If you have multiple conversion hosts, you can see the name of the conversion host in the tooltip of the migrated virtual machine in the migration plans details view.
. Go to `/var/log/vdsm/import/` to access the logs for each migration:
+
* `virt-v2v` log: +v2v-import-_date_-_log_number_.log+
* `virt-v2v-wrapper` log: +v2v-import-_date_-_log_number_-wrapper.log+

Downloading the migration (`virt-v2v`) log in CloudForms::

. Click menu:Compute[*Migration* > Migration Plans].
. Click a completed migration plan to view its details.
. Click menu:Download Log[Migration Log].

[id="CloudForms_log"]
.CloudForms migration log

This log traces the orchestration of the virtual machine migration in CloudForms.

Accessing the CloudForms migration log::

. Log in to the CloudForms machine using SSH.
. The migration log is `/var/www/miq/vmdb/log/automation.log`.
