// Module included in the following assemblies:
// assembly_Common_issues_and_mistakes.adoc
[id="Migration_plan_errors"]
= Migration plan errors

[id="Virtual_machines_cannot_be_discovered"]
* If the virtual machines are being migrated for the first time and are not discovered by the migration plan, check the source datastores and networks in the infrastructure mapping.

* If the virtual machines have been migrated in the past, they cannot be discovered by the migration plan. Use a xref:Creating_a_csv_file_to_add_virtual_machines_to_the_migration_plan[CSV file] to add the virtual machines to the migration plan.

[id="Virtual_machines_cannot_be_added_with_CSV_file"]
* If the virtual machines cannot be added to the migration plan with a CSV file, check the   xref:Creating_a_csv_file_to_add_virtual_machines_to_the_migration_plan[CSV file format and fields]. Create a new migration plan with the updated CSV file.

* If you have not configured conversion hosts, the following error appears after running the migration plan: `Unable to migrate VMs because no conversion host was configured at the time of the attempted migration. See the product documentation for information on configuring conversion hosts.` You can create and save a migration plan whose infrastructure mapping does not contain conversion hosts, but you cannot run the migration plan without conversion hosts.
