// Module included in the following assemblies:
// assembly_Troubleshooting.adoc
[id="Migration_logs"]
= Migration logs

You can check the conversion host migration logs, playbook logs (if relevant), and the CloudForms log for errors.

[IMPORTANT]
====
If you open a link:https://access.redhat.com/support/cases/#/case/new[Red Hat Support call], you will need to provide the *Migration log* (`virt-v2v`) and the `virt-v2v-wrapper` log for analysis.
====

Downloading logs in CloudForms::

. Click menu:Compute[Migration > Migration Plans].
. Click *Migration Plans Complete* and click a migration plan name to view its details.
. Click *Download Log* of a virtual machine and select a log from the dropdown list:

* *Premigration log:* This option only appears if a premigration playbook is used.
* *Migration log:* This is the `virt-v2v` log. This log tracks the core of the virtual machine process, including `libguestfs` traces and disk migration details.
* *Virt-v2v-wrapper log:* `virt-v2v-wrapper` is the daemonizing wrapper for `virt-v2v`. This log traces the orchestration of the virtual machine conversion on the conversion host, including disk migration percentages and `virt-v2v` error reporting.
* *Postmigration log:* This option only appears if a postmigration playbook is used.

[id="CloudForms_log"]
Accessing the CloudForms migration log::

. Log into the CloudForms machine using SSH.
. The migration log is `/var/www/miq/vmdb/log/automation.log`.
