// Used in module: assembly_Troubleshooting.adoc
[id="Migration_logs"]
= Migration logs

Check the following logs to troubleshoot a failed migration.

[id="CloudForms_log"]
.CloudForms log

This log traces the orchestration of the virtual machine migration in CloudForms.

Location: `/var/www/miq/vmdb/log/automation.log`

[id="Conversion_host_logs"]
.Conversion host logs

When disk migration starts, two logs are created in the conversion host:

* `virt-v2v-wrapper`: Log of the daemonizing wrapper for `virt-v2v`. This log traces the orchestration of the virtual machine conversion on the conversion host, including disk migration percentages and `virt-v2v` error reporting.
* `virt-v2v`: Debug output from `virt-v2v` itself. This log tracks the core of the virtual machine process, including `libguestfs` traces and disk migration details.
+
[IMPORTANT]
====
Both logs are required for bug analysis. If you open a link:https://access.redhat.com/support/cases/#/case/new[Red Hat Support call], you should provide both logs.
====

Location:

* Red Hat Virtualization: `/var/log/vdsm/import/v2v-import-_timestamp_-_log_number_.log` and `v2v-import-_timestamp_-_log_number_-wrapper.log`
* OpenStack Platform: `/var/log/virt-v2v/v2v-import-_timestamp_-_log_number_.log` and `v2v-import-_timestamp_-_log_number_-wrapper.log`

[id="VM_migration_log"]
.Virtual machine migration log

Location:

. In menu:Compute[Migration Plans > Migration Plans Complete], click a migration plan name to go to the details view.
. Click menu:Download Log[Migration log] of a virtual machine.
