[[Common_issues_and_mistakes]]
= Common issues and mistakes

== Infrastructure mapping errors[[Infrastructure_mapping_errors]]

[[Infrastructure_mapping_missing_resources]]
* Missing datastores or clusters. If the infrastructure mapping displays a *Datastores missing* or *Clusters missing* error message, delete the mapping and create a new one. This error is caused by creating a mapping and subsequently adding or removing providers or provider objects, which changes their object IDs.

.Red Hat Virtualization only

* Missing networks. [[Infrastructure_mapping_missing_networks]]If the infrastructure mapping displays a *Networks missing* error message, delete the mapping, xref:Enabling_rhv_conversion_hosts_in_cloudforms[authenticate the RHV conversion hosts], and create a new mapping.

* Missing networks and datastore. Refreshing the hosts can cause *Networks missing* or *Datastore missing* error messages. Delete the mapping and create a new one.

.OpenStack Platform only

* Storage not detected. [[OpenStack_storage_not_detected]]If the target block storage does not appear while you are creating an infrastructure mapping, check that you have   link:https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/13/html-single/storage_guide/#section-volumes-advanced-vol-type[set at least one `volume type`] for the storage.

== Migration plan errors[[Migration_plan_errors]]

* Virtual machines are not discovered. If a migration plan does not discover the source virtual machines and if the virtual machines have never been migrated in the past, check that the datastores and networks of the source virtual machines have been added to the Infrastructure Mapping.
+
If a migration plan does not discover source virtual machines that have been migrated in the past, xref:Remigrating_virtual_machines[re-migrate] the virtual machines. Previously migrated virtual machines cannot be discovered because they are marked as `migrated` in the CloudForms VMDB.

* Virtual machines cannot be imported. If you cannot import the source virtual machines with a CSV file while creating a migration plan, check the xref:Creating_a_csv_file_to_import_virtual_machines[CSV file's format and fields]. Create a new migration plan using the updated CSV file.

* `Denied State`. [[Denied_state_error]]If a migration plan fails immediately and the migration plan displays a *Denied State* error message in *Migration Plans Complete*, check that you have xref:Creating_conversion_hosts[created the conversion hosts]. (Red Hat Virtualization only: ensure that you have xref:Enabling_rhv_conversion_hosts_in_cloudforms[authenticated the conversion hosts]). Cancel the migration plan and xref:Retrying_a_failed_migration_plan[retry it].

* IP address of RHEL or other Linux virtual machine not accessible after migration. If the IP address of a RHEL or other Linux virtual machine is not accessible after an apparently successful migration, xref:Remigrating_virtual_machines[re-migrate] the virtual machine with the xref:Configuring_the_rhel_premigration_playbook[`RHEL pre-migration` playbook].

== Virtual machine migration failure[[Virtual_machine_migration_failure]]

If a virtual machine fails to migrate, check its xref:Logs[conversion log] and review the possible causes below.

The following scenarios can cause a failed migration:

* Mounted ISO/CDROM disk(s)

* Encrypted disk(s)

* Invalid name. The source virtual machine name must not contain spaces or special characters.

.Red Hat Virtualization only

* Virtual machine name duplicates an existing target virtual machine name.

* SSH transformation failure. [[SSH_transformation_fails]]If you are using SSSD with single sign-on, SSH fails for the `vdsm` account. Reinstall `ipa-client` without configuring the OpenSSH client:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# ipa-client-install --uninstall
# ipa-client-install --no-ssh
----

[NOTE]
====
You cannot resolve this issue by changing the configuration file because the file is restored during upgrades.
====

.OpenStack Platform only

* Virtual machine powered off. The virtual machine must be powered on at the time of migration.

* No IP address:

** VMware Tools not installed on source virtual machine. VMware Tools preserves the IP address for migration.

** Source virtual machine has an interface configuration file that is mapped to a non-existent interface (for example, `/etc/sysconfig/network-scripts/ifcfg-eth1` exists, but `eth1` interface does not).
+
[options="" subs="+quotes,verbatim"]
----
CalledProcessError: Command \'['openstack', u'--os-username=admin', u'--os-identity-api-version=3', u'--os-user-domain-name=default', u'--os-auth-url=http://_osp.example.com_:5000/v3', u'--os-project-name=admin', u'--os-password=\*\*******', u'--os-project-id=0123456789abcdef0123456789abcdef', \'port', \'create', \'--format', \'json', \'--network', u'01234567-89ab-cdef-0123-456789abcdef', \'--mac-address', u'00:50:56:01:23:45', \'--enable', u'port_0', \'--fixed-ip', \'*ip-address=None*']' returned non-zero exit status 1
_date_ _time_:ERROR: Command output:
BadRequestException: Unknown error
----

* Not Authorized. The OpenStack Platform provider user, `admin`, configured in CloudForms does not have `admin` role privileges within the target project.  link:https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/13/html-single/users_and_identity_management_guide/#edit_a_project[Add the `admin` user] as `member` and `admin` to your target project.
+
[options="" subs="verbatim"]
----
ERROR: Command exited with non-zero return code 1, output: HttpException: 403: Client Error for url: https://123.123.123.123:13696/v2.0/ports, {"NeutronError": {"message": "((rule:create_port and rule:create_port:mac_address) and rule:create_port:fixed_ips) is disallowed by policy", "type": "PolicyNotAuthorized", "detail": ""}}
----
