[id="Planning_questions"]
= Planning questions

Plan sufficient resources for your migration based on your responses to the following questions:

What am I migrating?::
Identify the hosts and virtual machines to be migrated. If your deployment is large and complex, you may want to divide your resources into migration groups.

What is the maximum number of disks, virtual machines, or NICs that I can migrate?::
There is no maximum number of disks or virtual machines that you can migrate. However, you may not want to migrate all your virtual machines at the same time, in order to minimize the impact on your users. The maximum number of NICs per virtual machine that you can migrate is 4.
+
If you exceed the capabilities of the environment, the migrations will fail and may negatively affect existing applications running on virtual machines attached to the network and storage. Plan carefully and perform test migrations to determine the capabilities of your environment.

What operating systems can I migrate?::
For a list of supported guest operating systems, see link:https://access.redhat.com/articles/1351473[Converting Virtual Machines from Other Hypervisors to KVM with virt-v2v in RHEL 7]. For a list of certified guest operating systems, see link:https://access.redhat.com/articles/973163[Certified Guest Operating Systems in Red Hat OpenStack Platform and Red Hat Enterprise Virtualization].
+
[NOTE]
====
Although it is possible to migrate guest operating systems that are not certified for Red Hat Virtualization or OpenStack Platform, running these guests is not officially supported.
====

What resources will my target environment require?::
Your target environment must be large enough to run the migrated virtual machines in addition to the original VMware virtual machines. The VMware virtual machines are not affected by the migration process.

What am I missing?::
Identify resource gaps, such as bandwidth, storage, licenses, or a suitable maintenance window.

How long will the migration take?::
There are no specific rules to determine how long the actual migration will take. This is determined on a case-by-case basis. A xref:Migration_example[migration example] is provided as a guide. It may be possible to migrate your applications in phases, without downtime at the application layer, if the applications are distributed in a high-availability architecture.

What impact will the migration have on my users?::
Assess the effect the migration may have on a production environment. Check whether users will lose access to critical applications.
