// Module included in the following assemblies:
// assembly_Planning_the_migration.adoc
[id="Questions_to_ask_before_migration"]
= Questions to ask before migration

Plan sufficient resources for your migration based on your responses to the following questions:

What am I migrating?::
* Identify the hosts and virtual machines to be migrated.

What is the maximum number of disks, virtual machines, or NICs that I can migrate?::
* There is no maximum number of disks or virtual machines that you can migrate. However, you may not want to migrate all your virtual machines at the same time, in order to minimize the impact on your users.
* You can migrate a maximum of four NICs with each virtual machine.
+
[IMPORTANT]
====
If you exceed the capabilities of your environment, the migrations will fail. This situation could affect existing applications running on virtual machines attached to the network and storage.
====

What operating systems can I migrate?::
* For a list of supported guest operating systems, see link:https://access.redhat.com/articles/1351473[].
* For a list of certified guest operating systems, see link:https://access.redhat.com/articles/973163[].
+
Although it is possible to migrate guest operating systems that are not certified for Red Hat Virtualization or OpenStack Platform, these guests are not officially supported.

What resources does my target environment require?::
* Your target environment must be large enough to run the migrated virtual machines in addition to the source virtual machines. The source virtual machines are not affected by the migration process.

What am I missing?::
* Identify resource gaps, such as bandwidth, storage, licenses, or a suitable maintenance window.

What impact will the migration have on my users?::
* Assess the effect the migration may have on a production environment.
+
It may be possible to migrate your applications in phases, without downtime at the application layer, if the applications are distributed in a high-availability architecture.

* Check whether users will lose access to critical applications.

How long will the migration take?::
* There are no specific rules to determine how long the actual migration will take. This is determined on a case-by-case basis.
+
The following example is provided as a guide:
+
.Red Hat Virtualization migration
====
* Duration of migration: 1:15:53 (_hh:mm:ss_)
* 10 virtual machines (100 GB RAM, 1000 GB storage)
* Total data migrated, using VDDK: 1000 GB
* Hardware:
** Strong host (40 cores, 500 GB RAM)
** Fast SSD XtremIO storage
** Fibre Channel 8 interface for host-to-storage connection
** 10 GbE network interface cards for all other connections
====
