[[Storage]]
= Adding Storage

You must attach at least one storage domain to each data center. Setting up storage is a prerequisite for a new data center because a data center cannot be initialized unless storage domains are attached and activated. A storage domain can be made of either block devices (iSCSI or Fibre Channel) or a file system. At this point, you are adding your existing storage to Red Hat Virtualization.

[IMPORTANT]
====
Red Hat Virtualization currently does not support storage with a block size of 4K. You must configure block storage in legacy (512b block) mode.
====

This guide describes how to add xref:Adding_NFS_Storage[NFS storage].

For other storage types, click the link for documentation:

* xref:Adding_NFS_Storage[NFS]
* xref:iSCSI[iSCSI]
* xref:fc[Fibre Channel]
* xref:FCoE[Fibre Channel over Ethernet]
* xref:Gluster[Red Hat Gluster Storage]
* xref:Ceph[Red Hat Ceph File System]
* xref:POSIX[POSIX-Compliant FS]
* xref:local[Local Storage]

For more information about storage, see:

* link:https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.2/html/administration_guide/chap-storage[Storage] in the Red Hat Virtualization _Administration Guide_.

* Red Hat Enterprise Linux  link:https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Storage_Administration_Guide/index.html[_Storage Administration Guide_].

include::proc_Adding_NFS_Storage.adoc[leveloffset=+1]
include::proc_Adding_other_storage.adoc[leveloffset=+1]
