[id="rhv_conversion_hosts"]
= RHV Conversion Hosts

All the virtual machines that are specified in a migration plan are migrated at the same time. Therefore, the number of RHV conversion hosts that you create depends on the number of virtual machines you intend to migrate. Red Hat recommends configuring the RHV conversion hosts on physical machines, not nested virtual machines.

Each conversion host is limited to `10` concurrent migrations, unless you change the default value (see xref:Configuring_the_maximum_number_of_concurrent_migrations[] below).

[IMPORTANT]
====
The maximum number of concurrent virtual machine migrations per conversion host is `10`, for VDDK transformation, and `20`, for SSH transformation. The SSH transformation limitation applies only to Red Hat Virtualization 4.2.5, not to later versions.
====

Multiple conversion hosts are recommended, even for smaller migrations, for load-balancing purposes. The number of virtual machines that you can migrate at the same time depends on your infrastructure capabilities. Each migration requires a certain amount of network bandwidth, I/O throughput, and processing power for the conversion process. You should test your environment to understand how many migrations can occur simultaneously without negative effects.

[[datapath_transformation_options_vddk_ssh]]
*Datapath Transformation Options: VDDK or SSH*

Select the best datapath transformation option for your environment, either VDDK or SSH:

VDDK::
* Recommended because it is approximately twice as fast as SSH
* Compiled with `nbdkit` to provide direct connectivity to the virtual machine disks
* VDDK package must be downloaded
* Conversion host configuration requires a location
* Each conversion host supports only 10 concurrent migrations

SSH::
* Does not require additional downloads, packages, tools, or compilation
* RHV and VMware environments must share SSH keys
* SSH access must be enabled on ESXi hosts
* Slower than VDDK
* Suitable for larger scale migrations than VDDK
