[id="Creating_and_configuring_rhv_conversion_hosts_for_vddk_transformation"]
= Creating and Configuring RHV Conversion Hosts for VDDK Transformation

Create and configure RHV conversion hosts for VDDK transformation:

. Log in to the link:https://www.vmware.com/support/developer/vddk/[VMware VDDK Documentation] site and download the latest VDDK package (for example, `VMware-vix-disklib-6.5.3-8315684.x86_64.tar.gz`) to your local machine.

. Using SCP, copy the VDDK package to `/var/www/html` on the Manager machine.

. Go to the Ansible conversion hosts playbooks directory on the Manager machine:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# cd /usr/share/ovirt-ansible-v2v-conversion-host/playbooks/
----

. Create a `conversion_hosts_inventory.yml` inventory file with the following variables:
+
[options="nowrap" subs="+quotes,verbatim"]
----
all:
  hosts:
    _host1.example.com_:
    _host2.example.com_:
  vars:
    ansible_ssh_private_key_file: /etc/pki/ovirt-engine/keys/engine_id_rsa
    v2v_vddk_package_name: VMware-vix-disklib-_version_.x86_64.tar.gz
    v2v_vddk_package_url: http://_Manager_FQDN_/VMware-vix-disklib-_version_.x86_64.tar.gz
----

. Enable the conversion hosts:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# ansible-playbook -i conversion_hosts_inventory.yml conversion_host_enable.yml
----
+
[NOTE]
====
The Ansible role checks for the presence of the RHV guest tools ISO image in the ISO storage domain. This image is used to migrate Windows virtual machines.
====

. Verify that the conversion hosts are enabled:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# ansible-playbook -i conversion_hosts_inventory.yml conversion_host_check.yml
----

[NOTE]
====
If you upgrade your RHV environment, you must run the `conversion_host_enable` playbook again, with the option `-e v2v_vddk_override=true`, to update the IMS packages.
====

After creating the RHV conversion hosts, you must configure them in CloudForms. See xref:Configuring_rhv_conversion_hosts_in_cloudforms[].
