[[ha_roles]]
== Scaling a Highly Available {product-title_short} Environment

After creating high availability for the database tier and the user interface tier, the rest of the infrastructure should be sized as appropriate for the roles and the environments that they manage. These roles and tiers use built-in high availability mechanisms like primary, secondary, and tertiary failover or use round robin or most available schemes built into {product-title_short}.

You can configure additional worker appliances as needed using the steps in xref:installation_appliances_addl[] and assign server roles. The {product-title_short} appliances and roles can be configured in any order.

.Considerations

* User interface (UI) zone
* Management zone (for providers)
* Database Operations zone

See https://access.redhat.com/documentation/en-us/red_hat_cloudforms/4.5/html-single/general_configuration/#regions[Regions] and  https://access.redhat.com/documentation/en-us/red_hat_cloudforms/4.5/html-single/general_configuration/#servers[Servers] in  _General Configuration_ for more information on configuring servers and roles.


The following diagram shows an example of a highly available database configuration with worker appliances configured:

*[INSERT DIAGRAM]*

////

https://bugzilla.redhat.com/show_bug.cgi?id=1414214


Insert diagram with worker appliances
////

