[[Overview]]
== Environment Overview

This guide describes how to configure and manage database high availability in a {product-title} environment. This configuration allows for disaster mitigation: a failure in the primary database does not result in downtime, as the standby database takes over the failed database’s processes. This is made possible by database replication between two or more database servers. In {product-title_short}, these servers are _database-only {product-title_short} appliances_ which do not have `evmserverd` processes enabled. 

In this configuration, only one database is writable at any given time. This procedure also does not provide scalability or a multi-master database setup. While a {product-title} environment is comprised of an engine tier and a database tier, this configuration affects only the database tier and does not provide load balancing for the appliances.

This guide describes two types of appliances used in high availability: 

* _Database-only {product-title_short} appliances_, which do not have `evmserverd` processes enabled or a user interface.
* _{product-title_short} appliances_, which are standard appliances containing a user interface and which have `evmserverd` processes enabled.


[NOTE]
====
Manual steps are required to reintroduce the failed database node back as the standby server. See xref:reintroducing_the_failed_node[].
====

[[requirements]]
=== Requirements

For a high availability {product-title} environment, you need a virtualization host containing at minimum four virtual machines with {product-title_short} installed, consisting of:

- One virtual machine for the primary external database containing a minimum of 4GB dedicated disk space
- One virtual machine for the standby external database containing a minimum of 4GB dedicated disk space
- Two virtual machines for the {product-title_short} appliances

ifdef::cfme[]
See https://access.redhat.com/documentation/en/red-hat-cloudforms/4.2/paged/deployment-planning-guide/chapter-2-planning[Planning] in the _Deployment Planning Guide_ for information on setting up the correct disk space for the database-only appliances.
endif::cfme[]

The database-only appliances should reside on a highly reliable local network in the same location.

[IMPORTANT]
====
It is essential to use the same {product-title} appliance template version to install each virtual machine in this environment. 

ifdef::cfme[]
See the https://access.redhat.com/products/red-hat-cloudforms[Red Hat Customer Portal] to obtain the appliance download for the platform you are running {product-title_short} on.
endif::cfme[]
====

Correct time synchronization is required before installing the cluster. After installing the appliances, configure time synchronization on all appliances using `chronyd`.

ifdef::cfme[]
[NOTE]
====
Red Hat recommends using a DNS server for a high availability configuration, as DNS names can be updated more quickly than IP addresses when restoring an operation in a different location, network, or datacenter.
====
endif::cfme[]
