[[renaming-ha]]
== Updating Hostnames on Database-Only Appliances

When updating the hostnames of database-only appliances in a cluster, you must also re-configure high availability on the primary and standby database-only appliances.

=== Preparing to Update Appliance Hostnames

Before updating the hostnames of your appliances, complete the following:

. Note the hostnames of the active database (primary) appliance and the standby database appliances in the appliance console.
+
You can verify this from the appliance summary screen of a database-only appliance, where the status for *Local Database Server* shows _primary_ or _standby_, for example:
+
----
...
Local Database Server:   running (primary)
...
----
+
. On the non-database {product-title_short} appliances, stop the failover monitor:
.. In the appliance console menu, select *Configure Application Database Failover Monitor*.
.. Select *Stop Database Failover Monitor*.
. On the _standby_ database-only appliances, stop the `postgresql` database service:
+
----
# systemctl stop postgresql.service
----
+
. Stop `evmserverd` on each non-database {product-title_short} appliance:
+
----
# systemctl stop evmserverd
----


=== Updating the Primary Database-Only Appliance Hostname

Run the following steps on your primary database-only appliance:

. In the appliance console menu, configure the new hostname or IP address from the *Configure Network* option.
. Restart the appliance.
. Update the `host` key to the primary database appliance's new hostname in `/var/www/miq/vmdb/config/database.yml`.


=== Updating the Standby Database-Only Appliance Hostname

Run the following steps on your standby database-only appliances:

. In the appliance console menu, configure the new hostname or IP address from the *Configure Network* option.
. Restart the appliance.
. Update the `host` key to the standby database appliance's new hostname in `/var/www/miq/vmdb/config/database.yml`.

Repeat these steps on any additional standby database-only appliances.

[IMPORTANT]
====
Your primary and standby appliances must be reachable to each other by their hostnames. If all appliances are on the same network and are resolvable, no additional updates are needed. If your appliances exist on different networks, edit the `/etc/hosts` file on each database appliance to include entries for the IP address and hostname of each other database appliance in the cluster.
====

Proceed to re-configure high availability on the primary and standby database-only appliances.

=== Re-configuring High Availability on Database-Only Appliances

Re-configure replication on the database-only appliances, and restart services on your cluster.

==== Configuring the Primary Database-Only Appliance

On the primary database-only appliance, initialize the nodes in the database cluster to re-configure the database replication:

. In the appliance console menu, select *Configure Database Replication*.
. Select *Configure Server as Primary*.
. Set a unique identifier number for the server and enter the database name and credentials:
.. Select a number to uniquely identify the node in the replication cluster.
.. Enter the cluster database name.
.. Enter the cluster database username.
.. Enter the cluster database password and confirm the password.
.. Enter the new primary database-only appliance hostname or IP address.
+
[NOTE]
====
The hostname or IP address must be visible to all appliances that communicate with this database, including the non-database {product-title_short} appliances and any global region databases.
====
+
.. Confirm that the replication server configuration details are correct, and select `y` to apply the configuration.



==== Configuring the Standby Database-Only Appliance

The steps to re-configure the standby database-only appliances are similar to that of the primary database-only appliance, in that they prepare the appliance to be database-only, but as the standby.

On the standby database-only appliances, configure the following:

. In the appliance console menu, select *Configure Database Replication*.
. Select *Configure Server as Standby*.
. Select the database disk. {product-title_short} then activates the configuration.
. Set a unique identifier number for the standby server and enter the database name and credentials:
.. Select a number to uniquely identify the node in the replication cluster.
.. Enter the cluster database name.
.. Enter the cluster database username.
.. Enter the cluster database password.
.. Enter the new primary database-only appliance hostname or IP address.
.. Enter the new standby database-only appliance hostname or IP address.
+
[NOTE]
====
The hostname or IP address must be visible to all appliances that communicate with this database, including the engine appliances and any global region databases.
====
+
.. Select `y` to configure the replication manager for automatic failover.
.. Confirm that the replication standby server configuration details are correct, and select `y` to apply the configuration. The standby server will then run an initial synchronization with the primary database, and start locally in standby mode.
. Verify the configuration on the appliance console details screen for the standby server. When configured successfully, *Local Database Server* shows as `running (standby)`.

Repeat these steps on any additional standby database-only appliances.

[IMPORTANT]
====
If you are using non-dedicated database appliances, also stop `evmserverd` on those appliances before changing their hostnames, and reconfigure `database.yml` before restarting.
====


==== Restarting Services

. Start `evmserverd` on each non-database {product-title_short} appliance:
+
----
# systemctl start evmserverd
----
+
After `evmserverd` has started successfully, all appliances will be able connect to the database.
+
. Restart the failover monitor on the non-database {product-title_short} appliances:
.. In the appliance console menu, select *Configure Application Database Failover Monitor*.
.. Select *Start Database Failover Monitor*.


[NOTE]
====
You can view a summary of the updated appliances by running `repmgr cluster show` on one of the database appliances.
====

Your {product-title_short} environment is now re-configured for high availability.
