[[_chap_red_hat_cloudforms_security_guide_setting_ssl_for_the_database_appliance]]
=== Configuring the Database to use SSL

{product-title} initially connects to the database through an unencrypted communication.
If using multiple appliances connecting to a single database appliance, you can set up the database connection to use SSL.
An SSL connection encrypts the communication between the {product-title} and the database.

The procedures in this section use the SSL certificate and key files listed below.
These files can be found on your main {product-title} database appliance.

[NOTE]
====
The appliance image ships with a default SSL certificate and it is recommended to change this certificate.
You can use a certificate signed by a trusted CA or, alternatively, generate a self-signed certificate.

See <<_chap_red_hat_cloudforms_security_guide_ssl_certs>> for more information on generating an SSL certificate.
====

* `/var/www/miq/vmdb/certs/server.cer` - Signed or self-signed certificate for the database appliance.
* `/var/www/miq/vmdb/certs/server.cer.key` - Private key for server certificate.
* `/var/www/miq/vmdb/certs/root.crt` - The root certificate for {product-title} database server appliance.
  You can either use a self-signed certificate or a certificate signed by a trusted CA to generate your root certificate.

It is also recommended to stop all {product-title} services before configuring the database to use SSL.

To configure SSL on the database appliance:

. Log in as `root` to the appliance where the database resides.
. Stop the `evmserverd` and `rh-postgresql94-postgresql` services:
+
[subs="verbatim,attributes"]
----
[root@{productname_short_l}2 ~]# systemctl stop evmserverd
[root@{productname_short_l}2 ~]# systemctl stop rh-postgresql94-postgresql
----

. Install the server key file in the correct location and set the ownership and permissions for it:
+
[subs="verbatim,attributes"]
----
[root@{productname_short_l}2 ~]# install -m 600 -o postgres -g postgres \
/var/www/miq/vmdb/certs/server.cer.key /var/www/miq/vmdb/certs/postgres.key
----

. Install the server certificate file in the correct location and set the ownership and permissions for it:
+
[subs="verbatim,attributes"]
----
[root@{productname_short_l}2 ~]# install -m 644 -o postgres -g postgres \
/var/www/miq/vmdb/certs/server.cer /var/www/miq/vmdb/certs/postgres.crt
----

. Install the database appliance certificate file as the root certificate in the correct location and set the ownership and permissions for it:
+
[subs="verbatim,attributes"]
----
[root@{productname_short_l}2 ~]# install -m 644 -o postgres -g postgres /var/www/miq/vmdb/certs/server.cer /var/www/miq/vmdb/certs/root.crt
----

. Make sure that the security context is set correctly for the files in `/var/www/miq/certs`:
+
[subs="verbatim,attributes"]
----
[root@{productname_short_l}2 ~]# restorecon -R -v /var/www/miq/vmdb/certs
----
. Open the `/var/opt/rh/rh-postgresql94/lib/pgsql/data/postgresql.conf` file and uncomment and edit the `ssl` option:
+
----

ssl=on
----
+
In the same file, locate the options `ssl_cert_file`, `ssl_key_file`, and `ssl_ca_file` that specify the location of SSL certificates and edit them so that they are uncommented and point to the correct certificate files:
+
[source]
----

ssl_cert_file = '/var/www/miq/vmdb/certs/postgres.crt'  # (change requires restart)
ssl_key_file  = '/var/www/miq/vmdb/certs/postgres.key'  # (change requires restart)
ssl_ca_file   = '/var/www/miq/vmdb/certs/root.crt'      # (change requires restart)
----

. Open the `/var/opt/rh/rh-postgresql94/lib/pgsql/data/pg_hba.conf` file and locate the two lines that contain the following:
+
[source]
----

host      all      all   all           md5
#hostssl  all      all   all           md5
----
+
Modify the two lines to comment the `host` entry and uncomment the `hostssl` entry:
+
[source]
----

#host     all      all   all           md5
hostssl   all      all   all           md5
----
+
This changes the incoming communication protocol to use SSL and refuse any unencrypted PostgreSQL connections.

. Start the `rh-postgresql94-postgresql` and `evmserverd` services so that the changes take effect:
+
[subs="verbatim,attributes"]
----
[root@{productname_short_l}1 ~]# systemctl start rh-postgresql94-postgresql
[root@{productname_short_l}1 ~]# systemctl start evmserverd
----

The database appliance now only accepts connections from connecting appliances using SSL.
The following procedure sets up connecting appliances to communicate to the database using SSL. Use this procedure for each connecting appliance:

. Log in as `root` to the connecting appliance.
. Create the `.postgresql` directory in your `root` user home directory.
+
[subs="verbatim,attributes"]
----
[root@{productname_short_l}2 ~]# mkdir /root/.postgresql
----
+
The PostgreSQL client library, which {product-title} also uses, looks to this directory for custom configuration files.

. Copy the root certificate file from the database appliance to the `/root/.postgresql` directory on the connecting appliance:
+
[subs="verbatim,attributes"]
----
[root@{productname_short_l}2 ~]# scp root@[database_appliance_fqdn]:/var/www/miq/vmdb/certs/root.crt /root/.postgresql/root.crt
----
+
Where `[database_appliance_fqdn]` is the fully qualified domain name of the database appliance.

. Test the connection between the connecting appliance and the database appliance using the `psql`:
+
----

[root@localhost ~]# psql -h [database_appliance_fqdn] -d vmdb_production
Password: ********
psql (9.2.8)
SSL connection (cipher: DHE-RSA-AES256-SHA, bits: 256)
Type "help" for help.

vmdb_production=#
----
+
The `psql` displays information about the SSL connection, which indicates that the configuration succeeded.
Enter `\q` to leave `psql`.


Complete this procedure for each external appliance.
This enhances the security of all database transactions in your {product-title} infrastructure.


==== Hardening TLS Protocol Version
 
After configuring the database to use SSL, protocol TLS version 1.2 is used as default. The older versions of this protocol (TLS 1.0 and 1.1) are still available for clients to choose. You can disable older versions by inserting the following lines into `/var/opt/rh/rh-postgresql94/lib/pgsql/data/postgresql.conf`:
 
----
ssl_ciphers = 'TLSv1.2:!aNULL'
ssl_prefer_server_ciphers=true
----
 



