[[_chap_red_hat_cloudforms_security_guide_firewall]]
=== Configuring Firewall Ports

A new appliance starts with a few standard ports open:

* 22 for SSH communication
* 80 for HTTP access to the appliance
* 443 for HTTPS access to the appliance
* 5432 for the appliance database

You might need to restrict or open access to certain services on your appliance in the future.
In such situations, use the following method:

* Use `firewalld` to enable a service or port, specifying the zone in use.
  For example, to open the LDAP port:
+
------
[root@ ~]# firewall-cmd --zone=manageiq --permanent --add-port=389/tcp
------

The following table lists the appliance's main services and their respective ports. 

.Ports Used by {product-title}
[cols="1,1,1,1,1,1", frame="all", options="header"]
|===
|

                            Initiator (CFME Role if applicable)


|

                            Receiver (CFME Role if applicable)


|

                            Application


|

                            TCP Port


|

                            UDP Port


|

                            Purpose


|

                            Administrator (Internet Browser)


|

                            CFME appliance (User Interface)


|

                            HTTPS


|

                            443


|
|

                            Access to CFME appliance User Interface



|

                            Administrator (Internet Browser)


|

                            CFME appliance (User Interface)


|

                            HTTP


|

                            80


|
|

                            Redirect Web Browser to HTTPS service (443)



|

                            Service Catalog or other integration through Web Service


|

                            CFME appliance (Web Service)


|

                            HTTPS


|

                            443


|
|

                            Access to CFME appliance Web Service



|

                            CFME appliance


|

                            NFS Server


|

                            NFS


|

                            2049


|

                            2049


|

                            Embedded NFS VM scanning



|

                            CFME appliance (User Interface)


|

                            Any Virtual Machine


|

                            TCP


|

                            903


|
|

                            VM Remote Console (if using MKS plug-in)



|

                            CFME appliance (User Interface)


|

                            Any Virtual Machine


|

                            TCP


|

                            5900-5999


|
|

                            VM Remote Console (if using VNC)



|

                            CFME appliance (any role)


|

                            CFME appliance running the VMDB


|

                            PostgreSQL Named Pipes


|

                            5432


|
|

                            CFME appliance connectivity to the CFME Database (PostgreSQL)



|

                            CFME Subordinate Region VMDB appliance(Database Synchronization)


|

                            CFME Master Region VMDB appliance


|

                            PostgreSQL Named Pipes


|

                            5432


|
|

                            Regional VMDB node replication up to Master VMDB node (PostgreSQL only)



|

                            CFME appliance(Authentication through LDAP)


|

                            LDAP Server (AD or other)


|

                            LDAP


|

                            389


|
|

                            LDAP integration



|

                            CFME appliance (Authentication through LDAPs)


|

                            LDAP Server (AD or other)


|

                            LDAPs


|

                            636


|
|

                            LDAPS integration



|

                            SNMP Agent


|

                            CFME appliance (Notifier)


|

                            SNMP (UDP)


|
|

                            161


|

                            SNMP Polling



|

                            CFME appliance (Notifier)


|

                            SNMP Server


|

                            SNMP (TCP)


|

                            162


|
|

                            SNMP Trap Send



|

                            CFME appliance (Notifier)


|

                            Mail server


|

                            SMTP


|

                            25


|
|

                            SNMP Trap Send



|

                            CFME appliance (any role)


|

                            NTP Server


|

                            NTP


|
|

                            123


|

                            Time Source



|

                            CFME appliance


|

                            CFME SmartProxy installed on VMware ESX Server


|

                            HTTPS


|

                            1139


|
|

                            Communication with SmartProxy



|

                            CFME appliance


|

                            DNS Server


|

                            UDP


|
|

                            53


|

                            DNS Lookups


|===


The following tables detail the ports used by {product-title} to communicate with providers.

.Red Hat Enterprise Virtualization Ports Used by {product-title}
[cols="1,1,1,1,1,1", frame="all", options="header"]
|===
|

                            Initiator (CFME Role if applicable)


|

                            Receiver (CFME Role if applicable)


|

                            Application


|

                            TCP Port


|

                            UDP Port


|

                            Purpose


|

                            CFME appliance (SmartProxy)


|

                            RHEV-M Server


|

                            HTTPS


|

                            8443


|
|

                            API communications to RHEV-M environment (Inventory, Operations, SmartProxy)



|

                            CFME appliance (C&U)


|

                            RHEV-M Server


|

                            PostgreSQL


|

                            5432


|
|

                            RHEV-M History Database (Database connectivity not enabled by default). See https://access.redhat.com/site/solutions/63277[How to access the RHEV-M Postgres DB from a remote machine].



|

                            CFME appliance


|

                            RHEV-H Hosts or RHEL Hypervisors


|

                            SSH


|

                            22


|
|

                            SSH connections.



|

                            CFME appliance


|

                            RHEV-H Hosts or RHEL Hypervisors


|

                            DirectLUN


|
|
|

                            Direct LUN hook must be installed and enabled for embedded VM scanning on FC or iSCSI storage devices. Not a tcp/udp connection.


|===

.Red Hat OpenStack Platform Ports Used by {product-title}
[cols="1,1,1,1,1,1", frame="all", options="header"]
|===
|

                            Initiator (CFME Role if applicable)


|

                            Receiver (CFME Role if applicable)


|

                            Application


|

                            TCP Port


|

                            UDP Port


|

                            Purpose


|

                            CFME appliance


|

                            RHOS (Keystone)


|

                            HTTP REST API


|

                            5000


|
|

                            Authentication and Service Entry Point



|

                            CFME appliance


|

                            RHOS (Nova)


|

                            HTTP REST API


|

                            8774


|
|

                            Compute Resources



|

                            CFME appliance (C&U)


|

                            RHOS (Ceilometer)


|

                            HTTP REST API


|

                            8777


|
|

                            Metrics for Capacity and Utilization



|

                            CFME appliance


|

                            RHOS (Glance)


|

                            HTTP REST API


|

                            9292


|
|

                            Authentication and Service Entry Point



|

                            CFME appliance


|

                            RHOS (AMQP)


|

                            AMQP


|

                            5672


|
|

                            Events Integration



|

                            CFME appliance


|

                            RHOS (Neutron)


|

                            HTTP REST API


|

                            9696


|
|

                            Networking



|

                            CFME appliance


|

                            RHOS (Cinder)


|

                            HTTP REST API


|

                            8776


|
|

                            Block Storage


|===


.OpenShift Container Platform Ports Used by CloudForms Management Engine
[cols="1,1,1,1,1,1", frame="all", options="header"]
|===
|

                            Initiator (CFME Role if applicable)


|

                            Receiver (CFME Role if applicable)


|

                            Application


|

                            TCP Port


|

                            UDP Port


|

                            Purpose


|

                            CFME Appliance


|

                            OpenShift Master Node(s) (or Load Balancer)


|

                            HTTPS


|

                            8443 or 443


|



|

                        Required for communication to the OpenShift API. Dependent on OpenShift configuration.


|

                         CFME Appliance


|

                         OpenShift Infrastructure Node(s) (or Load Balancer)


|

                         HTTPS


|

                         443


|



|

                        Metrics and logging

|


|===


.VMware vSphere Ports Used by {product-title}
[cols="1,1,1,1,1,1", frame="all", options="header"]
|===
|

                            Initiator (CFME Role if applicable)


|

                            Receiver (CFME Role if applicable)


|

                            Application


|

                            TCP Port


|

                            UDP Port


|

                            Purpose


|

                            CFME appliance(Management System Inventory, Management System Operations, C & U Data Collection, SmartProxy)


|

                            vCenter


|

                            HTTPS


|

                            443


|
|

                            CFME appliance running any of these roles will initiate communication with vCenter on this port



|

                            CFME appliance (SmartProxy)


|

                            ESX, ESXi Host


|

                            HTTPS


|

                            443


|
|

                            CFME appliance



|

                            CFME appliance (SmartProxy)


|

                            ESX Hosts (if analyzing VMs through host)


|

                            SOAP over HTTPS


|

                            902


|
|

                            Communication from CFME appliance to hosts


|

                            CFME appliance (SmartProxy)


|

                            vCenter (if analyzing VMs through VC)


|

                            SOAP over HTTPS


|

                            902


|
|

                            Communication from CFME appliance to vCenters



|

                            CFME appliance(SmartProxy)


|

                            ESX Hosts (not needed for ESXi)


|

                            SSH


|

                            22


|
|

                            CFME appliance console access (ssh) to ESX hosts


|===

.SCVMM Ports Used by {product-title}
[cols="1,1,1,1,1,1", frame="all", options="header"]
|===
|

                            Initiator (CFME Role if applicable)


|

                            Receiver (CFME Role if applicable)


|

                            Application


|

                            TCP Port


|

                            UDP Port


|

                            Purpose


|

                            CFME appliance


|

                            Hyper-V Host (VMM agent)


|

                            WinRM/RPC/NetBIOS/SMB (over TCP)


|

                            80/135/139/445


|




|


			    Communication from CFME appliance to Host



|

                            CFME appliance


|

                            Hyper-V Host (file transfer)


|

                            HTTPS (using BITS)


|

                            443


|




|

			    Communication from CFME appliance to Host




|

                            CFME appliance


|

                            VM Guest Agent (file transfer)


|

                            HTTPS (using BITS)


|

                            443


|




|


			    Communication from CFME appliance to VM Guest Agent




|

                            CFME appliance


|

                            VMware ESX 3.0/3.5 Host (file transfer)


|

                            SFTP


|

                            22


|




|


			    Communication from CFME appliance to ESX Host




|

                            CFME appliance


|

                            VMware ESXi Host (file transfer)


|

                            SSH/HTTPS (using BITS)


|

                            443


|




|


			    Communication from CFME appliance to ESX Host




|

                            CFME appliance


|

                            WSUS Server (data channel)


|

                            HTTP


|

                            80/443


|




|

			    Communication from CFME appliance to Server




|

                            CFME appliance


|

                            SQL Server database (remote)


|

                            TDS


|

                            1433


|




|


			    CFME appliance connectivity to the Database 




|

                            CFME appliance


|

                            Load Balancer


|

                            Load balancer config provider


|

                            80/443


|
|





|

                            CFME appliance


|

                            Hyper-V host in untrusted domain or perimeter network (File Transfer)


|

                            TCP


|

                            443


|




|


			    CFME appliance connectivity to the host




|

                            CFME appliance


|

                            Hyper-V Host (file transfer)


|

                            BITS


|

                            443


|




|


			    Communication from CFME appliance to Host




|

                            CFME appliance


|

                            VMware Web Services


|

                            WCF


|

                            443


|
|


|===

.Azure Ports Used by {product-title}
[cols="1,1,1,1,1,1", frame="all", options="header"]
|===
|

                            Initiator (CFME Role if applicable)


|

                            Receiver (CFME Role if applicable)


|

                            Application


|

                            TCP Port


|

                            UDP Port


|

                            Purpose


|

                            CFME appliance


|

                            SQL Management (*.database.windows.net)


|

                            TDS


|

                            1433


|




|

			    CFME appliance connectivity to the Database




|

                            CFME appliance


|

                            Upload into Storage (*.blob.core.windows.net)


|

                            HTTP/HTTPS


|

                            80/443


|
|





|

                            CFME appliance


|

                            Service Bus Relay HTTP Mode (*.servicebus.windows.net)


|

                            SB over HTTP


|

                            80


|
|




|

                            CFME appliance


|

                            Service Bus Pubsub over REST (*.servicebus.windows.net)


|

                            HTTPS


|

                            443


|
|





|

                            CFME appliance


|

                            Access Control (*.accesscontrol.windows.net)


|

                            HTTPS


|

                            443


|
|



|===





IMPORTANT: To provide your {product-title} infrastructure with an extra layer of security, use a network layer firewall to restrict port access.


