[[_chap_red_hat_cloudforms_security_guide_hbac]]
=== Configuring Host-Based Access Control Rules on your IPA Server

{product-title} provides support for external authentication using an IPA server.
However, there are certain recommendations to enhance security to your appliance, such as creating a specific user group and host group that can access the appliance authentication service.

Run the following steps on your IPA server:

. Create a user group and restrict access to only the {product-title} users:
+
[subs="verbatim,attributes"]
------
[root@ipa ~]# ipa group-add {productname_short_l}_users --desc="{productname_short_l} Users"
[root@ipa ~]# ipa group-add-member {productname_short_l}_users --users=testuser1,testuser2
------

. Create a host group and restrict access to your appliance hosts:
+
[subs="verbatim,attributes"]
------
[root@ipa ~]# ipa hostgroup-add {productname_short_l}_hosts --desc "{product-title} hosts"
[root@ipa ~]# ipa hostgroup-add-member {productname_short_l}_hosts --hosts=appliance1.example.com,appliance2.example.com
------

. Add rules to allow the host group and user group access to the {product-title} HTTP service:
+
[subs="verbatim,attributes"]
------
[root@ipa ~]# ipa hbacrule-add {productname_short_l}_access --srchostcat=all
[root@ipa ~]# ipa hbacrule-add-service {productname_short_l}_access --hbacsvcs httpd-auth
[root@ipa ~]# ipa hbacrule-add-user {productname_short_l}_access --groups {productname_short_l}_users
[root@ipa ~]# ipa hbacrule-add-host {productname_short_l}_access --hostgroups {productname_short_l}_hosts
------

. Remove the default rule on your IPA server to allow access to all:
+
------
[root@ipa ~]# ipa hbacrule-disable allow_all
------


This ensures only users in the `{productname_short_l}_users` group can access the authentication service (`http-auth`) on the appliances in the `{productname_short_l}_hosts` host group.




