[[_chap_red_hat_cloudforms_security_guide_updates]]

= Registering and Updating {product-title} 

An important part of securing {product-title}  is to ensure your appliances use the latest packages.
Package updates to the appliance contain patches for any software bugs, including possible security bugs.

The *Red Hat Updates* page enables you to edit register and update appliances.
This includes either registering the appliance to Red Hat Content Delivery Network (CDN) or to a Red Hat Satellite server.

The following tools are used during the update process:

* `Yum` provides package installation, updates, and dependency checking.
* `Red Hat Subscription Manager` manages subscriptions and entitlements.
* `Red Hat Satellite Server` runs at customer locations providing local system registration and updates from inside the customer's firewall.

[IMPORTANT]
====
The update worker synchronizes the VMDB with the status of available CloudForms content every 12 hours.
====

[NOTE]
====
Servers with the `RHN Mirror` role also act as a repository for other appliances to pull CloudForms package updates.
====

== Registering Appliances 

The *Red Hat Updates* page enables you to register and update appliances.
This includes either registering the appliance to Red Hat Content Delivery Network (CDN) or to a Red Hat Satellite server. The subscription management service you register with will provide your systems with updates and allow additional management.

You need the following to register your appliance:

* Your Red Hat account login or Red Hat Network Satellite login
* A Red Hat subscription that covers your product
* (Optional) Your HTTP proxy information
* (Optional) The address of an alternate service

To register your appliance with Red Hat Subscription Management or Red Hat Satellite 6:

. Log in to the appliance as the `admin` user.
. Navigate to menu:Settings[Configuration].
. Select *Region* in the accordion menu and click the *Red Hat Updates* tab.
. Click *Edit Registration*.
. You can register the CloudForms Management Engine appliance using one of two available options:
.. To register with Red Hat Subscription Management:
... In *Register to*, select *Red Hat Subscription Management*.
... Enter the *Red Hat Subscription Management Address*. The default is `subscription.rhn.redhat.com`.
... Enter the *Repository Name(s)*. The default is `cf-me-5.5-for-rhel-7-rpms rhel-server-rhscl-7-rpms`, which are the Red Hat CloudForms repository and the Red Hat Software Collections repository.
... To use a HTTP proxy, select *Use HTTP Proxy* and enter your proxy details.
... Enter your Red Hat account information and click *Validate*.
... Click *Save*.
.. To register with Red Hat Satellite 6:
... In *Register to*, select *Red Hat Satellite 6*.
... Enter the *Red Hat Satellite 6 Address*. The default is `subscription.rhn.redhat.com`.
... Enter the *Repository Name(s)*. The default is `cf-me-5.5-for-rhel-7-rpms rhel-server-rhscl-7-rpms`, which are the Red Hat CloudForms repository and the Red Hat Software Collections repository.
... To use a HTTP proxy, select *Use HTTP Proxy* and enter your proxy details.
... Enter your Red Hat Satellite account information; click *Validate*.
... After your credentials are validated, click *Save*.

== Updating Appliances

The *Red Hat Updates* page enables you to check for updates and update registered appliances.

. Navigate to menu:Settings[Configuration].
. Select *Region* in the accordion menu and click the *Red Hat Updates* tab.
. After registering, the following options are available in the *Appliance Updates* section of the *Red Hat Updates* tab:

.Options Available in the Appliance Updates section of the Red Hat Updates tab

[cols="1,1", frame="all", options="header"]
|====
|

              Option


|

              Use

|
             Refresh List


|
            Refreshes list of appliances.


|
             Check for Updates


|
            Checks for all available updates using `yum`.

|
              Register


|
            Attempts to register the appliance if it is not already registered. CloudForms Management Engine subscribes to the `rhel-x86_64-server-6-cf-me-3` RHN channel for RHN-registered appliances, and to the products designated by Red Hat product certification for subscription-manager registered appliances. The Red Hat Enterprise Linux channels are enabled by default on registration. In addition, CloudForms Management Engine checks for updates after registering.
|
               Apply CFME Update


|
            Applies updates to CloudForms Management Engine packages only. Specifically, this option runs the `yum -y update cfme-appliance` command. This command installs every package listed in the dependency tree if it is not already installed. If a specific version of a package is required, that version of the package is installed or upgraded. No other packages, such as PostgreSQL or Red Hat Enterprise Linux, are updated.

|====


[NOTE]
====
If the appliance is registered to Red Hat Satellite, you can use content views to manage updates for Red Hat CloudForms. For more information, see https://access.redhat.com/documentation/en/red-hat-satellite/6.2/single/content-management-guide#Creating_Content_Views[Creating Content Views] in the _Red Hat Satellite 6 Content Management Guide_.
====


=== Non-CFME Package Updates

Non-CFME package updates can be applied in the CloudForms web user interface using the *Red Hat Updates* page, or manually using the `yum update` command to the appliance.

Red Hat recommends applying all updates using the *Red Hat Updates* page, which automatically handles any necessary restarts to the appliance and/or services. Performing updates from the command line may require manually restarting CloudForms services or rebooting the appliance.

[IMPORTANT]
====
When applying non-CFME package updates, such as PostgreSQL and Red Hat Enterprise Linux updates, ensure you schedule downtime for your system. This is by design for the following reasons:

* Some of these updates may interrupt CloudForms operations.
* Updates for PostgreSQL (the server hosting the VMDB) must be done in a maintenance window as it will take down CloudForms operations.
* System updates may require a reboot of the appliance.
====

