[[_chap_red_hat_cloudforms_security_guide_updates]]
= Registering and Updating {product-title} 

An important part of securing {product-title}  is to ensure your appliances use the latest packages.
Package updates to the appliance contain patches for any software bugs, including possible security bugs.

The *Red Hat Updates* page enables you to edit register and update appliances.
This includes either registering the appliance to Red Hat's Content Delivery Network (CDN) or to a Red Hat Satellite server.

The following tools are used during the update process:

* `Yum` provides package installation, updates, and dependency checking.
* `Red Hat Subscription Manager` manages subscriptions and entitlements.
* `Red Hat Satellite Server` runs at customer locations providing local system registration and updates from inside the customer's firewall.

IMPORTANT: The update worker synchronizes the VMDB with the status of available {product-title} content every 12 hours.

NOTE: Servers with the `RHN Mirror` role also act as a repository for other appliances to pull {product-title} packages updates.

The *Red Hat Updates* page enables you to register appliances.
You need the following to register:

* Your Red Hat Account login or Red Hat Network Satellite login
* A Red Hat subscription that covers your product

. Log in to the appliance as the `root` user.
. Navigate to menu:Settings[Configuration]. Select *Region* in the accordion menu and click the *Red Hat Updates* tab.
. In *Red Hat Software Updates*, click *Edit Registration*.
. You can register the {product-title} appliance using one of two available options:
+
* Red Hat Subscription Management
* Red Hat Satellite 6
+
The Subscription Management Service you register with will provide your systems with updates and allow additional management.

.To register with Red Hat Subscription Management:
.. In *Register to*, select *Red Hat Subscription Management*.
.. Enter *Red Hat Subscription Management Address*. The default is `subscription.rhn.redhat.com`.
.. Enter *Repository Name*. The default is `cf-me-5.4-for-rhel-6-rpms rhel-server-rhscl-6-rpms`, which are the {product-title} repository and the Red Hat Software Collections repository.
.. To use a HTTP proxy, select *Use HTTP Proxy* and enter your proxy details.
.. Enter your Red Hat account information; click *Validate*.
.. Click *Save*.

.To register with Red Hat Satellite 6:
.. In *Register to*, select *Red Hat Satellite 6*.
.. Enter *Red Hat Satellite 6 Address*. The default is `subscription.rhn.redhat.com`.
.. Enter *Repository Name*. The default is `cf-me-5.4-for-rhel-6-rpms rhel-server-rhscl-6-rpms`, which are the {product-title} repository and the Red Hat Software Collections repository.
.. To use a HTTP proxy, select *Use HTTP Proxy* and enter your proxy details.
.. Enter your Red Hat Satellite account information; click *Validate*.
.. Click *Save*.

After registering, the following options are available in the *appliance Updates* section of the *Red Hat Updates* tab:

.Options Available in the appliance Updates Section of the Red Hat Updates Tab
[cols="1,1", frame="all", options="header"]
|===
|

              Option


|

              Use


|
             Check for Updates


|
            Checks for available updates using yum.

|
              Register


|
            Attempts to register the appliance if it is not already registered. {product-title} subscribes to the `rhel-x86_64-server-6-cf-me-3` RHN channel for RHN-registered appliances, and to the products designated by Red Hat product certification for subscription-manager registered appliances. The Red Hat Enterprise Linux channels are enabled by default on registration. In addition, {product-title} checks for updates after registering.
|
               Apply CFME Update


|
            Applies updates to {product-title} packages only. Specifically, this option runs the `yum -y update cfme-appliance` command. This command installs every package listed in the dependency tree if it is not already installed. If a specific version of a package is required, that version of the package is installed or upgraded. No other packages, such as PostgreSQL or Red Hat Enterprise Linux, are updated.

|===







