[[database_replication]]
== Configuring Database Replication

This chapter describes the steps needed to set up database replication.

[[replication-configuring-primary]]
=== Configuring the Primary Database Server

On the primary database server, initialize the nodes in the database cluster to configure the database replication:

. In the appliance console menu, select *Configure Database Replication*. 
. Select *Configure Server as Primary*.
. Set an unique identifier number for the server and enter the database name and credentials:
.. Select a number to uniquely identify the node in the replication cluster.
.. Enter the cluster database name.
.. Enter the cluster database username.
.. Enter the cluster database password and confirm the password.
.. Enter the primary database server hostname or IP address.
+
[NOTE]
====
The hostname must be visible to all appliances that communicate with this database, including the engine appliances and any global region databases.
====
+
.. Confirm that the replication server configuration details are correct, and select `y` to apply the configuration.

[[replication-configuring-standby]]
=== Configuring the Standby Database Server

On the standby database server, configure the following:

. In the appliance console menu, select *Configure Database Replication*. 
. Select *Configure Server as Standby*.
. Set an unique identifier number for the standby server and enter the database name and credentials:
.. Select a number to uniquely identify the node in the replication cluster.
.. Enter the cluster database name.
.. Enter the cluster database username.
.. Enter the cluster database password.
.. Enter the primary database server hostname or IP address.
.. Enter the standby database server hostname or IP address.
+
[NOTE]
====
The hostname must be visible to all appliances that communicate with this database, including the engine appliances and any global region databases.
====
+
.. Select `y` to configure Replication Manager for automatic failover.
.. Confirm that the replication standby server configuration details are correct, and select `y` to apply the configuration.

The standby server will then run an initial synchronization with the primary database, and start locally in standby mode.

Verify the configuration on the appliance console details screen for the standby server. When configured successfully, *Local Database Server* shows as `running (standby)`. 


