[[_chap_red_hat_cloudforms_security_guide_setting_ssh_keys]]
= Setting SSH Keys on the Appliance

Another recommended practice is to use SSH keys to access the appliance from a single machine.
An SSH key provides access from one machine to another through the SSH protocol.
The following procedure shows how to create an SSH key on your local machine and add it to the appliance. 

.Procedure: Setting SSH Keys on the Appliance
. Check the [path]_.ssh/_ directory in your home directory for any existing key pairs: 
+
----

[user@localhost ~]$ ls ~/.ssh/
----
+
A key pair usually consists of two files.
One file is the private key, which stays on your local machine, and the other is the public key, which you copy to another machine.
But files are named the same except the public key ends with a [path]_.pub_ extension. 
+
If a key pair already exists, you can use this key pair.
Otherwise, use the next few steps to create your own. 

. On your local machine, start the key pair generation process using the +ssh-keygen+ command: 
+
----

[user@localhost ~]$ ssh-keygen -t rsa
----

. A prompt asks for the file and location to store these keys. 
+
----

Enter file in which to save the key (/home/user/.ssh/id_rsa):
----
+
Accept the default path if you do not have a [path]_id_rsa_ key pair. 

. Another prompt asks for a passphrase: 
+
----

Enter passphrase (empty for no passphrase):
----
+
This encrypts the key pair with a password.
This protects the key pair if it ever falls into the wrong hands.
Alternatively, you can leave the passphrase empty, which provides an automatic login between your local machine and the remote machine. 

. The +ssh-keygen+ command generates two files: 
+
* The private key - the default is [path]_/home/user/.ssh/id_rsa_          
* The public key - the default is [path]_/home/user/.ssh/id_rsa.pub_          
+
Copy the public key to the appliance using the +ssh-copy-id+ command: 
+
----

[user@localhost ~]$ ssh-copy-id ~/.ssh/id_rsa.pub root@10.1.1.205
----
+
The command copies the public key to the appliance.
You might receive a prompt for the password of the root user on the appliance. 

. Test the SSH key authentication: 
+
----

[user@localhost ~]$ ssh root@10.1.1.205
----
+
This authenticates using the SSH key pair.
If you entered a passphrase for the key, the command prompts you for the passphrase. 

. As an additional security measure, edit the [path]_/etc/ssh/sshd_config_ on the appliance and modify the following parameter: 
+
----

PermitRootLogin without-password
----
+
This forces the [literal]+root+ user account to use certificates instead of passwords for SSH logins.
This means only your local system can access the appliance. 


The appliance now restricts access to only a single machine using the SSH key. 