pressgang_website_callback([
	{"topicId":14720,"target":"Architecture2","title":"Architecture","newSince":""},
	{"topicId":14721,"target":"Requirements1","title":"Requirements","newSince":""},
	{"topicId":42049,"target":"Regions","title":"Regions","newSince":""},
	{"topicId":14722,"target":"Terminology2","title":"Terminology","newSince":""},
	{"topicId":42050,"target":"appe-Revision_History","title":"Revision History","newSince":""},
	{"topicId":42051,"target":"Abstract","title":"Abstract","newSince":""},
	{"topicId":26757,"target":"Example_PostgreSQL_Configuration_File","title":"Example PostgreSQL Configuration File","newSince":""},
	{"topicId":32939,"target":"sect-Security","title":"Red Hat CloudForms Main Ports Reference","newSince":""},
	{"topicId":32941,"target":"sect-Security","title":"Additional Red Hat CloudForms Ports Reference for Red Hat Enterprise Virtualization","newSince":""},
	{"topicId":36209,"target":"Database_Sizing_Assistant","title":"Database Sizing Assistant","newSince":""},
	{"topicId":44369,"target":"sect-Planning","title":"Planning","newSince":""},
	{"topicId":41106,"target":"sect-Introduction_to_Red_Hat_CloudForms","title":"Introduction to Red Hat CloudForms","newSince":""},
	{"topicId":41460,"target":"Getting_Help_and_Giving_Feedback","title":"Getting Help and Giving Feedback","newSince":""},
	{"topicId":25716,"target":"Author_Group","title":"Author Group","newSince":""},
	{"topicId":26422,"target":"CPU_Sizing_Assistant","title":"CPU Sizing Assistant for a Dedicated VMDB Host","newSince":""}], 22969, "Red Hat CloudForms", "Deployment Planning Guide", "3.2");