// https://access.redhat.com/documentation/en/openshift-enterprise/version-3.2/installation-and-configuration/#install-config-cluster-metrics

In order for {product-title_short} to collect OpenShift Enterprise node, pod, and container, you must first enable _cluster metrics_ for your OpenShift cluster. This involves running the OpenShift Metrics services inside your cluster. If cluster metrics are already enabled on OpenShift, skip this section and proceed to xref:Obtaining_OpenShift_Enterprise_Management_Token[].

[NOTE]
===================
This section is an abridged version of a more detailed chapter, namely https://access.redhat.com/documentation/en/openshift-enterprise/version-3.2/installation-and-configuration/#install-config-cluster-metrics[Enabling Cluster Metrics] from the https://access.redhat.com/documentation/en/openshift-enterprise/version-3.2/installation-and-configuration/[OpenShift Enterprise Installation and Configuration documentation]. Refer to that chapter for more information.
===================

[[ose-metrics-prep]]
== Configuring the Required Service Accounts

Cluster metrics requires the following service accounts:

* *metrics-deployer*
* *heapster*

[IMPORTANT]
===============
If you deployed OpenShift using `openshift-ansible-3.0.20`, then the service account and roles required for enabling metrics will already be installed. You can skip this section and go to xref:ose-metrics-storage[].
===============

To create these accounts:

. Log in as an administrator to any node within the OpenShift Enterprise cluster.
. Open a terminal.
. Switch to the *openshift-infra* project:
+
[literal,subs="+quotes"]
--------------------------
$ oc project openshift-infra
--------------------------
. Create a service account for the Metrics Deployer named *metrics-deployer*:
+
[literal,subs="+quotes"]
--------------------------
$ oc create -f - <<API
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: metrics-deployer
  secrets:
  - name: metrics-deployer
  API
--------------------------
. As described in xref:ose-metrics-storage[], the Metrics Deployer uses the *metrics-deployer* service account. Configure the *metrics-deployer* account to have *edit* permissions in the *openshift-infra* project:
+
[literal,subs="+quotes"]
--------------------------
$ oadm policy add-role-to-user \
    edit system:serviceaccount:openshift-infra:metrics-deployer
--------------------------
. The *heapster* account will be automatically created in xref:ose-metrics-deploy[]. However, pre-emptively grant it *cluster-reader* permission to the *openshift-infra* project:
+
[literal,subs="+quotes"]
--------------------------
$ oadm policy add-cluster-role-to-user \
    cluster-reader system:serviceaccount:openshift-infra:heapster
--------------------------

[[ose-metrics-storage]]
== Configuring Metrics Components

The Metrics Deployer installs and configures the components required for OpenShift Enterprise metrics. By default, the Metrics Deployer uses _self-signed certificates_ to secure communication between components. This document assumes that you will use this default. For information on alternative secure communication configurations, see https://access.redhat.com/documentation/en/openshift-enterprise/version-3.2/installation-and-configuration/#metrics-deployer-using-secrets[Using Secrets] in the OpenShift Enterprise _Installation and Configuration_ documentation.

[NOTE]
===================
This section is an abridged version of a more detailed chapter, namely https://access.redhat.com/documentation/en/openshift-enterprise/version-3.2/installation-and-configuration/#metrics-data-storage[Metrics Data Storage] in the OpenShift Enterprise _Installation and Configuration_ documentation. Refer to that chapter for more information on how to deploy the metrics plug-in using persistent and non-persistent storage.
===================

[[ose-metrics-deploy]]
=== Deploying the Metrics Components

OpenShift Enterprise uses _Hawkular Metrics_ as its metrics engine. The Metrics Deployer will install the Hawkular Metrics service; however, you need to provide the external hostname so that {product-title_short} can reach the Hawkular Metrics service. The base configuration of the Metrics Deployer is defined in the `/usr/share/openshift/examples/infrastructure-templates/enterprise/metrics-deployer.yaml` file.

Before deploying OpenShift metrics, choose a storage option, then log in as an administrator to any node within the OpenShift Enterprise cluster. From there, open a terminal and run the corresponding command:

Deploying with persistent storage::

With _persistent storage_, OpenShift metrics will be stored on a persistent volume. This offers metrics data protection by allowing it to survive a pod recreation or restart. OpenShift metrics requires a specifically configured persistent volume; see https://access.redhat.com/documentation/en/openshift-enterprise/version-3.2/architecture/#architecture-additional-concepts-storage[Persistent Volumes] in the OpenShift Enterprise _Architecture_ documentation. 
+
//When preparing the persistent volume, note its _size_, as this will be used later in xref:ose-metrics-deploy[].
+
[literal,subs="+quotes"]
--------------------------
$ oc new-app \
    -f /usr/share/openshift/examples/infrastructure-templates/enterprise/metrics-deployer.yaml \
    -p HAWKULAR_METRICS_HOSTNAME=_HAWKULARHOST_
--------------------------

Deploying with non-persistent storage::

With _non-persistent storage_, any stored metrics will be deleted when the pod is deleted. While it is much easier to run cluster metrics with non-persistent data, it does come with the risk of permanent data loss. So, while you no longer need to provision and configure a volume to store metric data, this does not offer the same protection as persistent storage.
+
[literal,subs="+quotes"]
--------------------------
$ oc new-app \
    -f /usr/share/openshift/examples/infrastructure-templates/enterprise/metrics-deployer.yaml \
    -p HAWKULAR_METRICS_HOSTNAME=_HAWKULARHOST_ \
    -p USE_PERSISTENT_STORAGE=false
--------------------------

///////
--> Deploying template metrics-deployer-template for "/usr/share/openshift/examples/infrastructure-templates/enterprise/metrics-deployer.yaml"
     With parameters:
      IMAGE_PREFIX=registry.access.redhat.com/openshift3/
      IMAGE_VERSION=3.1.1
      MASTER_URL=https://kubernetes.default.svc:443
      HAWKULAR_METRICS_HOSTNAME=hawkular.example.com
      REDEPLOY=false
      USE_PERSISTENT_STORAGE=true
      CASSANDRA_NODES=1
      CASSANDRA_PV_SIZE=1Gi
      METRIC_DURATION=7
--> Creating resources ...
    Pod "metrics-deployer-7da46" created
--> Success
    Run 'oc status' to view your app.
///////


For either command, replace _HAWKULARHOST_ with the external hostname that {product-title_short} will use to reach the Hawkular Metrics service. _HAWKULARHOST_ must be a fully-qualified domain name.

Either storage method deploys the required metrics components and creates the necessary service accounts. In particular, the metrics components will be configured to also use the specified _HAWKULARHOST_ as its public endpoint.

[[ose-metrics-finish]]
=== Applying the Hawkular Metrics Settings to OpenShift Enterprise 

After deploying the metrics components, configure OpenShift Enterprise to use them:

. Open the OpenShift Master Configuration file at `/etc/origin/master/master-config.yaml`. Add the *metricsPublicURL* parameter to the *assetConfig* section, specifying the _HAWKULARHOST_ you specified in xref:ose-metrics-deploy[]:
+
[literal,subs="+quotes"]
--------------------------
assetConfig:
    ...
    metricsPublicURL: "https://_HAWKULARHOST_/hawkular/metrics"
--------------------------
. Restart your OpenShift Enterprise master host:
+
[literal,subs="+quotes"]
--------------------------
$ sudo systemctl restart atomic-openshift-master
--------------------------
