pressgang_website_callback([
	{"topicId":41984,"target":"Firewall_Rules_firewall_rule","title":"Firewall Rules (firewall_rule)","newSince":""},
	{"topicId":41985,"target":"Flavors_flavor","title":"Flavors (flavor)","newSince":""},
	{"topicId":41986,"target":"Floating_IPs_floating_ip","title":"Floating IPs (floating_ip)","newSince":""},
	{"topicId":41987,"target":"Proxies_miq_proxy","title":"Proxies (miq_proxy)","newSince":""},
	{"topicId":41988,"target":"VM_Provisioning_for_Clouds_Task_miq_provision_cloud","title":"VM Provisioning for Clouds Task (miq_provision_cloud)","newSince":""},
	{"topicId":41989,"target":"Service_Reconfiguration_Task_service_reconfigure_task","title":"Service Reconfiguration Task (service_reconfigure_task)","newSince":""},
	{"topicId":41990,"target":"Security_Groups_security_group","title":"Security Groups (security_group)","newSince":""},
	{"topicId":41991,"target":"sect-VMs_vm","title":"VMs (vm)","newSince":""},
	{"topicId":41992,"target":"VMs_for_Clouds_vm_cloud","title":"VMs for Clouds (vm_cloud)","newSince":""},
	{"topicId":41993,"target":"sect-VMs_vm","title":"Virtual Machine Metrics","newSince":""},
	{"topicId":30217,"target":"Abstract","title":"Abstract","newSince":""},
	{"topicId":42007,"target":"Cloud_Providers_ems_cloud","title":"Cloud Providers (ems_cloud)","newSince":""},
	{"topicId":25885,"target":"Service_Resource_service_resource","title":"Service Resource (service_resource)","newSince":""},
	{"topicId":43178,"target":"Booting_OpenStack_Instances_from_Volume","title":"Booting OpenStack Instances from Volume","newSince":""},
	{"topicId":43185,"target":"Adding_Disks_to_OpenStack_Instance_Provisioning","title":"Adding Disks to OpenStack Instance Provisioning","newSince":""},
	{"topicId":15670,"target":"chap-Methods_Available_for_Use_with_CloudForms_Management_Engine","title":"Methods Available for Use with CloudForms Management Engine","newSince":""},
	{"topicId":15671,"target":"About_evm.root","title":"$evm.root","newSince":""},
	{"topicId":15672,"target":"Method_Hierarchy","title":"Method Hierarchy","newSince":""},
	{"topicId":15673,"target":"Base_Methods","title":"Base Methods","newSince":""},
	{"topicId":15674,"target":"sect-Virtual_Machines_and_Templates_vm_or_template","title":"Virtual Machines and Templates (vm_or_template)","newSince":""},
	{"topicId":42938,"target":"Author_Group","title":"Author Group","newSince":""},
	{"topicId":15675,"target":"sect-Virtual_Machines_and_Templates_vm_or_template","title":"Excerpt from Sample/InspectMe","newSince":""},
	{"topicId":15676,"target":"sect-Virtual_Machines_and_Templates_vm_or_template","title":"Snapshot Example","newSince":""},
	{"topicId":15677,"target":"sect-Hosts_host","title":"Hosts (host)","newSince":""},
	{"topicId":15678,"target":"sect-Hosts_host","title":"Excerpt from Sample/InspectMe","newSince":""},
	{"topicId":15679,"target":"Hosts_Vmware_ESX_host_vmware_esx","title":"Hosts: Vmware ESX (host_vmware_esx)","newSince":""},
	{"topicId":15680,"target":"sect-Clusters_ems_cluster","title":"Clusters (ems_cluster)","newSince":""},
	{"topicId":15681,"target":"sect-Clusters_ems_cluster","title":"Excerpt from Sample/InspectMe","newSince":""},
	{"topicId":15682,"target":"sect-Datastores_storage","title":"Datastores (storage)","newSince":""},
	{"topicId":42946,"target":"appe-Revision_History","title":"Revision History","newSince":""},
	{"topicId":15683,"target":"sect-Datastores_storage","title":"Excerpt from Sample/InspectMe","newSince":""},
	{"topicId":15685,"target":"sect-Providers_ext_management_system","title":"Providers (ext_management_system)","newSince":""},
	{"topicId":15686,"target":"sect-Providers_ext_management_system","title":"Excerpt from Sample/InspectMe","newSince":""},
	{"topicId":15687,"target":"Management_System_Events_ems_event","title":"Management System Events (ems_event)","newSince":""},
	{"topicId":15688,"target":"Management_System_Folders_ems_folder","title":"Management System Folders (ems_folder)","newSince":""},
	{"topicId":23112,"target":"sect-Hosts_host","title":"Host Metrics","newSince":""},
	{"topicId":15689,"target":"Guest_Applications_guest_application","title":"Guest Applications (guest_application)","newSince":""},
	{"topicId":15690,"target":"Guest_Device_guest_device","title":"Guest Device (guest_device)","newSince":""},
	{"topicId":15691,"target":"Hardware_hardware","title":"Hardware (hardware)","newSince":""},
	{"topicId":15692,"target":"LAN_lan","title":"LAN (lan)","newSince":""},
	{"topicId":15693,"target":"sect-Groups_miq_group","title":"Groups (miq_group)","newSince":""},
	{"topicId":15694,"target":"sect-Groups_miq_group","title":"Excerpt from Sample/InspectMe","newSince":""},
	{"topicId":15695,"target":"sect-Servers_miq_server","title":"Servers (miq_server)","newSince":""},
	{"topicId":15696,"target":"sect-Servers_miq_server","title":"Excerpt from Sample/InspectMe","newSince":""},
	{"topicId":15697,"target":"Network_network","title":"Network (network)","newSince":""},
	{"topicId":15698,"target":"Snapshot_snapshot","title":"Snapshot (snapshot)","newSince":""},
	{"topicId":15699,"target":"Switch_switch","title":"Switch (switch)","newSince":""},
	{"topicId":15700,"target":"sect-User_user","title":"User (user)","newSince":""},
	{"topicId":15701,"target":"sect-User_user","title":"Excerpt from Sample/InspectMe","newSince":""},
	{"topicId":15703,"target":"Customization_template","title":"Customization Template (customization_template)","newSince":""},
	{"topicId":15704,"target":"sect-Request_miq_request","title":"Request (miq_request)","newSince":""},
	{"topicId":15705,"target":"Automation_request","title":"Automation Request (automation_request)","newSince":""},
	{"topicId":15706,"target":"Miq_host_provision_request","title":"Host Provision Request (miq_host_provision_request)","newSince":""},
	{"topicId":15707,"target":"Miq_provision_request","title":"VM Provision Request (miq_provision_request)","newSince":""},
	{"topicId":15708,"target":"sect-Request_Task_miq_request_task","title":"Request Task (miq_request_task)","newSince":""},
	{"topicId":15709,"target":"Automation_task","title":"Automation Task (automation_task)","newSince":""},
	{"topicId":15710,"target":"Miq_host_provision","title":"Host Provision Task (miq_host_provision)","newSince":""},
	{"topicId":15711,"target":"sect-VM_Provision_Task_miq_provision","title":"VM Provision Task (miq_provision)","newSince":""},
	{"topicId":15712,"target":"sect-VM_Provision_Task_miq_provision","title":"Example using miq_provision object","newSince":""},
	{"topicId":15713,"target":"Service_template_provision_task","title":"Service Template Provision Task (service_template_provision_task)","newSince":""},
	{"topicId":15714,"target":"Vm_migrate_task","title":"VM Migrate Task (vm_migrate_task)","newSince":""},
	{"topicId":15715,"target":"Pxe_image","title":"PXE Image (pxe_image)","newSince":""},
	{"topicId":15716,"target":"Pxe_server","title":"PXE Server (pxe_server)","newSince":""},
	{"topicId":15717,"target":"Service2","title":"Service (service)","newSince":""},
	{"topicId":15718,"target":"Service_Template","title":"Service Template (service_template)","newSince":""},
	{"topicId":15719,"target":"sect-Creating_Categories_and_Tags","title":"Creating Categories and Tags","newSince":""},
	{"topicId":15720,"target":"Category_and_Tags_Methods_Example1","title":"Category and Tags Methods Example","newSince":""},
	{"topicId":15721,"target":"Quota2","title":"Quota","newSince":""},
	{"topicId":15722,"target":"Windows_image","title":"Windows Image (windows_image)","newSince":""},
	{"topicId":41977,"target":"Availability_Zones_availability_zone","title":"Availability Zones (availability_zone)","newSince":""},
	{"topicId":41978,"target":"Classifications_classification","title":"Classifications (classification)","newSince":""},
	{"topicId":41979,"target":"Cloud_Networks_cloud_network","title":"Cloud Networks (cloud_network)","newSince":""},
	{"topicId":41980,"target":"Cloud_Resource_Quotas_cloud_resource_quota","title":"Cloud Resource Quotas (cloud_resource_quota)","newSince":""},
	{"topicId":41981,"target":"Cloud_Subnets_cloud_subnet","title":"Cloud Subnets (cloud_subnet)","newSince":""},
	{"topicId":41982,"target":"Cloud_Tenants_cloud_tenant","title":"Cloud Tenants (cloud_tenant)","newSince":""}], 23042, "Red Hat CloudForms", "Methods Available for Automation", "3.2");