[[Configuring-cloudforms]]
== Configuring {product-title}

After installing {product-title_short} and running it for the first time, you must perform some basic configuration. To configure {product-title_short}, you must at a minimum:

. Add a disk to the infrastructure hosting your appliance.
. Configure the database.

Configure the {product-title_short} appliance using the internal appliance console.

[[accessing-appliance-console]]
=== Accessing the Appliance Console

. Start the appliance and open a terminal console.
ifdef::login[]
. After starting the appliance, log in with a user name of `root` and the default password of `smartvm`. This displays the Bash prompt for the `root` user.
endif::login[]
ifdef::ssh[]
. Log in to the appliance using the SSH key.
endif::ssh[]
. Enter the `appliance_console` command. The {product-title} appliance summary screen displays.
. Press `Enter` to manually configure settings.
. Press the number for the item you want to change, and press `Enter`. The options for your selection are displayed.
. Follow the prompts to make the changes.
. Press `Enter` to accept a setting where applicable.

[NOTE]
====
The {product-title_short} appliance console automatically logs out after five minutes of inactivity.
====


[[configuring_a_database]]
=== Configuring a Database

{product-title_short} uses a database to store information about the environment. Before using {product-title_short}, configure the database options for it; {product-title_short} provides the following two options for database configuration:

* Install an internal PostgreSQL database to the appliance
* Configure the appliance to use an external PostgreSQL database

[[configuring-an-internal-database]]
==== Configuring an Internal Database

include::configuration-db.adoc[]

[[configuring-an-external-database]]
==== Configuring an External Database

Based on your setup, you will choose to configure the appliance to use an external PostgreSQL database. For example, we can only have one database in a single region. However, a region can be segmented into multiple zones, such as database zone, user interface zone, and reporting zone, where each zone provides a specific function. The appliances in these zones must be configured to use an external database.

The `postgresql.conf` file used with {product-title} databases requires specific settings for correct operation. For example, it must correctly reclaim table space, control session timeouts, and format the PostgreSQL server log for improved system support. Due to these requirements, Red Hat recommends that external {product-title} databases use a `postgresql.conf` file based on the standard file used by the {product-title} appliance.

Ensure you configure the settings in the `postgresql.conf` to suit your system. For example, customize the `shared_buffers` setting according to the amount of real storage available in the external system hosting the PostgreSQL instance. In addition, depending on the aggregate number of appliances expected to connect to the PostgreSQL instance, it may be
necessary to alter the `max_connections` setting.

[NOTE]
====
* {product-title} requires PostgreSQL version 9.5.
* Because the `postgresql.conf` file controls the operation of all databases managed by a single instance of PostgreSQL, do not mix {product-title} databases with other types of databases in a single PostgreSQL instance.
====

. Start the appliance and open a terminal console.
ifdef::login[]
. After starting the appliance, log in with a user name of `root` and the default password of `smartvm`. This displays the Bash prompt for the `root` user.
endif::login[]
ifdef::ssh[]
. Log in to the appliance using the SSH key.
endif::ssh[]
. Enter the `appliance_console` command. The {product-title} appliance summary screen displays.
. Press *Enter* to manually configure settings.
. Select *Configure Database* from the menu.
. You are prompted to create or fetch a security key.
* If this is the first {product-title} appliance, choose *Create key*.
* If this is not the first {product-title} appliance, choose *Fetch key from remote machine* to fetch the key from the first appliance.
+
[NOTE]
====
All {product-title_short} appliances in a multi-region deployment must use the same key.
====
+
. Choose *Create Region in External Database* for the database location.
. Enter the database hostname or IP address when prompted.
. Enter the database name or leave blank for the default (`vmdb_production`).
. Enter the database username or leave blank for the default (`root`).
. Enter the chosen database user's password.
. Confirm the configuration if prompted.

{product-title} will then configure the external database.

[[configuring-a-worker-appliance]]
=== Configuring a Worker Appliance

You can use multiple appliances to facilitate horizontal scaling, as well as for dividing up work by roles. Accordingly, configure an appliance to handle work for one or many roles, with workers within the appliance carrying out the duties for which they are configured. You can configure a worker appliance through the terminal. The following steps demonstrate how to join a worker appliance to an appliance that already has a region configured with a database.

. Start the appliance and open a terminal console.
ifdef::login[]
. After starting the appliance, log in with a user name of `root` and the default password of `smartvm`. This displays the Bash prompt for the `root` user.
endif::login[]
ifdef::ssh[]
. Log in to the appliance using the SSH key.
endif::ssh[]
. Enter the `appliance_console` command. The {product-title} appliance summary screen displays.
. Press *Enter* to manually configure settings.
. Select *Configure Database* from the menu.
. You are prompted to create or fetch a security key. Since this is not the first {product-title} appliance, choose *2) Fetch key from remote machine*. For worker and multi-region setups, use this option to copy the security key from another appliance.
+
[NOTE]
====
All {product-title_short} appliances in a multi-region deployment must use the same key.
====
+
. Choose *Join Region in External Database* for the database location.
. Enter the database hostname or IP address when prompted.
. Enter the port number or leave blank for the default (`5432`).
. Enter the database name or leave blank for the default (`vmdb_production`).
. Enter the database username or leave blank for the default (`root`).
. Enter the chosen database user's password.
. Confirm the configuration if prompted.
