
Creating a database dump from the appliance console can be used to provide additional information when raising a support case. Options exist to generate a database dump excluding specified tables and to split the database dump into multiple parts.  

Database dumps require name or location information based on the `Dump Output File Name` selection:

[width="75%"]
|==============
| Local File | Location
| Network File System (NFS)| Location 
| Samba (SMB)|Location
| Amazon S3| Name
| File Transfer Protocol (FTP)|Location
| ftp to dropbox.redhat.com|Name
|==============


To create a database dump:

. SSH into the appliance console as `root`.
. Press any key to continue.
. Type `appliance_console` and press `Enter`.
. From the Advanced Settings, select option 5, `Create a Database Dump`.
. Select a `Dump Output File Name` from the list. 
. Enter the location or name to save the dump file to.
+
ifdef::cfme[]
[IMPORTANT]
====
For {product-title} support select `dropbox.redhat.com`. Use the following convention for the dump output file name: case number dash (-) filename, ex: `12345-db.backup`. 
====
endif::cfme[]
+
. (Optional) Select tables to exclude from the dump:
.. Enter `Y` to exclude tables. Select `N` to skip the operation. 
.. Enter the table names in a space-separated list:
+
-----
metrics_* vim_performance_states event_streams
----- 
+
. (Optional) Split the database dump output into multiple parts:
.. Enter `Y` to split the database dump output. Select `N` to skip the operation. 
.. Enter the size to split by, ex `250M` or `1G`. 

The database dump is created and sent to the specified location.

