[[data-optimization]]
= Data Optimization

{product-title} optimization functions allow you to view
utilization trends in your
environment. In addition, you can predict where you have capacity for
additional virtual machines, see link:https://access.redhat.com/documentation/en-us/red_hat_cloudforms/4.7/html-single/deployment_planning_guide/#planning-where-to-put-a-new-virtual-machine[Planning Where to Put a New Virtual Machine] in the _Deployment Planning Guide_.

[NOTE]
====
* To access the utilization report features, you will first need to enable data collection in {product-title}; see the following sections in the _Deployment Planning Guide_:
** link:https://access.redhat.com/documentation/en-us/red_hat_cloudforms/4.7/html/deployment_planning_guide/Capacity_Planning#assigning_the_capacity_and_utilization_server_roles[Assigning the Capacity and Utilization Server Roles]
** link:https://access.redhat.com/documentation/en-us/red_hat_cloudforms/4.7/html/deployment_planning_guide/capacity_planning#data_collected[Capacity and Utilization Data Collected]
====

[[utilization-trends]]
== Utilization Trends

{product-title} allows you to view the resource utilization of your clusters, providers, and datastores. You can choose from summary,
details, or report view.

[[viewing-utilization-trend-summary]]
=== Viewing a Utilization Trend Summary

This procedure shows you how to view a utilization trend summary.

. Navigate to menu:Overview[Utilization].
. Click *Summary* if it is not already selected.
. Expand the tree on the left side, until you can see the desired
  providers, clusters, or datastores.
. Click on the item.
. Use the *Options* section in the *Summary* tab to change the
  characteristics of the data.
+
* Use *Trends* to select how far back you want to calculate
  the trend.
* Use *Selected Day* for the date you want to see percent utilization
  for in the chart on the *Summary* tab.
* Use *Classification* to only see trends for a specific applied tag.
* Use *Time Profile* to select an existing time profile. If the
  logged on user does not have any time profiles available, this
  option will not show.
* Select a *Time Zone*.

[[viewing-detail-lines-of-a-utilization-trend]]
=== Viewing Detail Lines of a Utilization Trend

This procedure shows you how to view detail lines of a utilization trend.

. Navigate to menu:Overview[Utilization].
. Expand the tree on the left side, until you can see the desired
  providers, clusters, or datastores.
. Click on the item.
. Click *Details* if it is not already selected.
. From the *Options* area, select how far back you want to view the
  trends for and any classifications you want to use.

[[viewing-a-report-of-a-utilization-trend]]
=== Viewing a Report of a Utilization Trend

To find out more about resource utilization, view utilization trend
reports.

. Navigate to menu:Overview[Utilization].
. Expand the tree on the left side, until you can see the desired
  providers, clusters, or datastores.
. Click on the item.
. Click *Report* if it is not already selected.
. From the *Options* area, select how far back you want to view the
  trends for and any classifications you want to use.
