= Enabling AWS Config Notifications

Amazon's AWS Config notifies subscribers of changes in a region through its Simple Notification Service (SNS). Red Hat CloudForms subscribes to the SNS service for AWS Config deltas and converts the deltas into Red Hat CloudForms events. 


. Enable the AWS Config service in the AWS Management Console.
  See the http://aws.amazon.com/documentation/config/[AWS Config Developer Guide] for more information. 
. Create a new Amazon SNS topic named [literal]+AWSConfig_topic+.
  CloudForms automatically connects to this topic. 
. (Optional) Configure the frequency of delta creation in the AWS Management Console. 

You can assign Red Hat CloudForms policies to the AWS events listed below.
The appliance performs a provider refresh on all these events except for [code]+AWS_EC2_Instance_UPDATE+.
See the https://access.redhat.com/documentation/en-US/Red_Hat_CloudForms/[Control Guide] for more information on working with CloudForms policies. 

[cols="1,1,1", options="header"]
|===
| 
						Event
| 
						Policies
| 
						Refresh
|
						AWS_EC2_Instance_CREATE
| 
							src_vm

							vm_create
| 
						ems
| 
						AWS_EC2_Instance_UPDATE
| 
						N/A
| 
						ems
| 
						AWS_EC2_Instance_running
| 
							src_vm

							vm_start
| 
						ems
| 
						AWS_EC2_Instance_stopped
| 
							src_vm

							vm_power_off
| 
						ems
| 
						AWS_EC2_Instance_shutting-down
| 
							src_vm

							vm_power_off
| 
						ems
|===

