[[Reconfiguring_VMs]]
= Reconfiguring Virtual Machines

Memory, processors, and disks can be reconfigured on existing VMware and Red Hat Virtualization virtual machines using the *Reconfigure this VM* button.

You can reconfigure multiple components on a virtual machine using one request before confirming the changes with the *Submit* button, or make each reconfiguration separately.

[IMPORTANT]
====
The following restrictions apply to adding and removing Red Hat Virtualization virtual machine disks:

* Supported by Red Hat Virtualization 4.0 and above.
* Only a single bootable disk is supported.
* The virtual machine requires at least one existing disk to allow adding additional disks. This is because the destination storage cannot be specified from the {product-title} dialog, so the storage associated with the existing disk is reused.
====

:leveloffset: 3
include::Adding_a_VM_disk.adoc[]

:leveloffset: 3
include::Removing_a_VM_disk.adoc[]

:leveloffset: 3
include::Reconfiguring_a_VM_Disk.adoc[]

:leveloffset: 3
include::Reconfiguring_VM_Memory.adoc[]

:leveloffset: 3
include::Reconfiguring_VM_Processors.adoc[]

:leveloffset: 3
include::Reconfiguring_VM_Network_Adapters.adoc[]


