[[cloud-tenants]]
= Cloud Tenants

A tenant is an OpenStack term for an organizational unit or project.
{product-title_short} creates cloud tenants to match existing OpenStack tenants for managing resources and controlling visibility of objects.

[NOTE]
====
OpenStack tenant mapping must be enabled for cloud tenants to be created. See xref:tenant-mapping[] for details.
====

OpenStack uses tenants for the following reasons:

* Assigning users to a project
* Defining quotas for a project
* Applying access and security rules for a project
* Managing resources and instances for a project

This helps administrators and users organize their OpenStack environment and define limits for different groups of people.
For example, one project might require higher quotas and another project might require restricted access to certain ports.
OpenStack allows you to define these limits and apply them to a project.

{product-title} can abstract information from tenants including quotas and relationships to other OpenStack objects.

To see multiple tenants in {product-title}, the user authenticating to your OpenStack environment from {product-title} must be configured to have visibility into these tenants.


[NOTE]
====
This section describes OpenStack cloud tenant usage. For information about tenants created in {product-title_short} for access and resource control, see https://access.redhat.com/documentation/en-us/red_hat_cloudforms/4.7/html-single/general_configuration/#access-control[Access Control] in _General Configuration_.
====

[[tenant-mapping]]
== Tenant Mapping

include::common/openstack/tenant-mapping.adoc[]

:leveloffset: 2
include::Viewing_a_Tenant.adoc[]

