pressgang_website_callback([
	{"topicId":14849,"target":"To_assign_an_Alert_Profile","title":"Assigning an Alert Profile","newSince":""},
	{"topicId":30209,"target":"Abstract","title":"Abstract","newSince":""},
	{"topicId":14852,"target":"sect-Accessing_Virtual_Machines_and_Hosts","title":"Accessing Virtual Machines and Hosts","newSince":""},
	{"topicId":14854,"target":"sect-Controlling_Virtual_Machines","title":"Controlling Virtual Machines","newSince":""},
	{"topicId":14856,"target":"To_control_the_power_state_of_one_Virtual_Machine","title":"Controlling the Power State of Virtual Machines","newSince":""},
	{"topicId":14860,"target":"sect-Retiring_Virtual_Machines","title":"Retiring Virtual Machines","newSince":""},
	{"topicId":18189,"target":"chap-Policies","title":"Policies","newSince":""},
	{"topicId":14861,"target":"To_set_a_retirement_date_for_a_Virtual_Machine1","title":"Setting a Retirement Date for a Virtual Machine","newSince":""},
	{"topicId":14862,"target":"To_remove_a_retirement_date_for_a_Virtual_Machine1","title":"Removing a Retirement Date for a Virtual Machine","newSince":""},
	{"topicId":14863,"target":"To_immediately_retire_a_Virtual_Machine1","title":"Immediately Retiring a Virtual Machine","newSince":""},
	{"topicId":14864,"target":"sect-Creating_and_Deleting_Snapshots","title":"Creating and Deleting Snapshots","newSince":""},
	{"topicId":14865,"target":"To_create_a_snapshot","title":"Creating a Snapshot","newSince":""},
	{"topicId":14866,"target":"To_delete_one_snapshot","title":"Deleting a Snapshot","newSince":""},
	{"topicId":14867,"target":"To_delete_all_snapshots","title":"Deleting All Snapshots","newSince":""},
	{"topicId":14868,"target":"To_revert_to_a_previous_snapshot","title":"Reverting to a Previous Snapshot","newSince":""},
	{"topicId":14870,"target":"appe-Regular_Expressions","title":"Regular Expressions","newSince":""},
	{"topicId":14871,"target":"To_export_a_Policy_Policy_Profile_or_an_Alert","title":"Exporting a Policy, Policy Profile, or an Alert","newSince":""},
	{"topicId":14728,"target":"sect-Control_Policies","title":"Control Policies","newSince":""},
	{"topicId":14730,"target":"To_create_a_Control_Policy","title":"Creating Control Policies","newSince":""},
	{"topicId":14731,"target":"Editing_Basic_Info_Scope_and_Notes_for_a_Policy","title":"Editing Basic Information, Scope, and Notes for a Policy","newSince":""},
	{"topicId":14732,"target":"Copying_a_Policy","title":"Copying a Policy","newSince":""},
	{"topicId":14734,"target":"Deleting_a_Policy","title":"Deleting a Policy","newSince":""},
	{"topicId":14735,"target":"Creating_a_new_Policy_Condition","title":"Creating a New Policy Condition","newSince":""},
	{"topicId":14736,"target":"Editing_Policy_Condition_Assignments","title":"Editing Policy Condition Assignments","newSince":""},
	{"topicId":14738,"target":"Editing_Policy_Event_Assignments","title":"Editing Policy Event Assignments","newSince":""},
	{"topicId":14739,"target":"To_assign_an_Action_to_an_Event","title":"Assigning an Action to an Event","newSince":""},
	{"topicId":14741,"target":"chap-Events","title":"Events","newSince":""},
	{"topicId":14742,"target":"chap-Conditions","title":"Conditions","newSince":""},
	{"topicId":14743,"target":"Creating_a_Condition","title":"Creating a Condition","newSince":""},
	{"topicId":14744,"target":"Copying_a_Condition","title":"Copying a Condition","newSince":""},
	{"topicId":14745,"target":"Deleting_a_Condition","title":"Deleting a Condition","newSince":""},
	{"topicId":14746,"target":"chap-Actions","title":"Actions","newSince":""},
	{"topicId":14747,"target":"sect-Custom_Actions","title":"Custom Actions","newSince":""},
	{"topicId":14748,"target":"Editing_a_Condition","title":"Editing a Condition","newSince":""},
	{"topicId":14749,"target":"To_create_an_Assign_Profile_to_Analysis_Task_action","title":"Creating an Assign Profile to Analysis Task Action","newSince":""},
	{"topicId":14750,"target":"To_create_a_snapshot_Action","title":"Creating a Snapshot Action","newSince":""},
	{"topicId":14752,"target":"To_delete_snapshots_by_age","title":"Deleting Snapshots by Age","newSince":""},
	{"topicId":14753,"target":"To_evaluate_an_Alert","title":"Evaluating an Alert","newSince":""},
	{"topicId":14754,"target":"To_create_an_Inherit_Tag_Action","title":"Creating an Inherit Tag Action","newSince":""},
	{"topicId":14755,"target":"To_create_a_CPU_reconfigure_Action","title":"Creating a CPU Reconfigure Action","newSince":""},
	{"topicId":14756,"target":"To_create_a_memory_reconfigure_Action","title":"Creating a Memory Reconfigure Action","newSince":""},
	{"topicId":14757,"target":"To_create_an_Remove_Tag_Action","title":"Creating a Remove Tag Action","newSince":""},
	{"topicId":14758,"target":"To_create_an_e-mail_Action","title":"Creating an E-mail Action","newSince":""},
	{"topicId":14759,"target":"To_create_an_SNMP_Action","title":"Creating an SNMP Action","newSince":""},
	{"topicId":14760,"target":"To_create_a_set_custom_attribute_Action","title":"Creating a Set Custom Attribute Action","newSince":""},
	{"topicId":14761,"target":"To_create_a_tag_Action","title":"Creating a Tag Action","newSince":""},
	{"topicId":14762,"target":"Editing_an_Action","title":"Editing an Action","newSince":""},
	{"topicId":14763,"target":"Deleting_an_Action","title":"Deleting an Action","newSince":""},
	{"topicId":14764,"target":"Importing_and_Exporting_Policies_Policy_Profiles_and_Alerts","title":"Importing and Exporting Policies, Policy Profiles, and Alerts","newSince":""},
	{"topicId":14765,"target":"Creating_Policy_Profiles","title":"Creating Policy Profiles","newSince":""},
	{"topicId":14767,"target":"Deleting_a_Policy_Profile","title":"Deleting a Policy Profile","newSince":""},
	{"topicId":14770,"target":"sect-Compliance_Policies","title":"Compliance Policies","newSince":""},
	{"topicId":14772,"target":"To_create_a_compliance_Policy","title":"Creating a Compliance Policy","newSince":""},
	{"topicId":14774,"target":"To_create_a_Condition_to_check_file_contents_of_a_host","title":"Creating a Compliance Condition to Check Host File Contents","newSince":""},
	{"topicId":14775,"target":"sect-Checking_for_Compliance","title":"Checking for Compliance","newSince":""},
	{"topicId":14776,"target":"To_schedule_a_Compliance_check","title":"Scheduling a Compliance Check","newSince":""},
	{"topicId":14777,"target":"To_check_a_Virtual_Machine_for_Compliance_from_the_Summary_Screen","title":"Checking a Virtual Machine for Compliance from the Summary Screen","newSince":""},
	{"topicId":14778,"target":"To_check_a_Host_for_Compliance_from_the_Summary_Screen","title":"Checking a Host for Compliance from the Summary Screen","newSince":""},
	{"topicId":42938,"target":"Author_Group","title":"Author Group","newSince":""},
	{"topicId":42942,"target":"appe-Revision_History","title":"Revision History","newSince":""},
	{"topicId":14786,"target":"sect-Simulating_Policy","title":"Simulating Policy","newSince":""},
	{"topicId":14787,"target":"To_simulate_Policy_Profiles_on_Virtual_Machines","title":"Simulating Policy Profiles on Virtual Machines","newSince":""},
	{"topicId":14788,"target":"sect-Assigning_Policy_Profiles","title":"Assigning Policy Profiles","newSince":""},
	{"topicId":14789,"target":"To_assign_Policy_Profiles_to_a_Virtual_Machine","title":"Assigning Policy Profiles to a Virtual Machine","newSince":""},
	{"topicId":14790,"target":"To_remove_Policy_Profiles_from_a_Virtual_Machine","title":"Removing Policy Profiles from a Virtual Machine","newSince":""},
	{"topicId":14791,"target":"To_assign_policies_to_a_Management_System","title":"Assigning Policy Profiles to a Provider","newSince":""},
	{"topicId":14792,"target":"To_remove_Policy_Profiles_from_a_Management_System","title":"Removing Policy Profiles from a Provider","newSince":""},
	{"topicId":14793,"target":"To_assign_Policy_Profiles_to_a_Cluster","title":"Assigning Policy Profiles to a Cluster","newSince":""},
	{"topicId":14794,"target":"To_remove_Policy_Profiles_from_a_Cluster","title":"Removing Policy Profiles from a Cluster","newSince":""},
	{"topicId":14795,"target":"To_assign_Policy_Profiles_to_a_Host","title":"Assigning Policy Profiles to a Host","newSince":""},
	{"topicId":14796,"target":"To_remove_Policy_Profiles_from_a_Host","title":"Removing Policy Profiles from a Host","newSince":""},
	{"topicId":14797,"target":"To_assign_Policy_Profiles_to_a_Resource_Pool","title":"Assigning Policy Profiles to a Resource Pool","newSince":""},
	{"topicId":14798,"target":"To_remove_Policy_Profiles_from_a_Resource_Pool","title":"Removing Policy Profiles from a Resource Pool","newSince":""},
	{"topicId":22222,"target":"Assigning_Policy_Profiles_to_a_Cloud_Provider","title":"Assigning Policy Profiles to a Cloud Provider","newSince":""},
	{"topicId":14799,"target":"To_assign_policies_to_a_Repository","title":"Assigning Policies to a Repository","newSince":""},
	{"topicId":22223,"target":"Removing_Policy_Profiles_from_a_Cloud_Provider","title":"Removing Policy Profiles from a Cloud Provider","newSince":""},
	{"topicId":14800,"target":"To_remove_Policy_Profiles_from_a_Repository","title":"Removing Policy Profiles from a Repository","newSince":""},
	{"topicId":22224,"target":"Assigning_Policy_Profiles_to_an_Instance","title":"Assigning Policy Profiles to an Instance","newSince":""},
	{"topicId":22225,"target":"Removing_Policy_Profiles_from_an_Instance","title":"Removing Policy Profiles from an Instance","newSince":""},
	{"topicId":14802,"target":"To_disable_a_Policy","title":"Disabling a Policy in a Policy Profile","newSince":""},
	{"topicId":22226,"target":"sect-Accessing_Cloud_Instances","title":"Accessing Cloud Instances","newSince":""},
	{"topicId":22227,"target":"sect-Controlling_Instances","title":"Controlling Instances","newSince":""},
	{"topicId":14804,"target":"To_view_Policy_Simulation_RSOP","title":"Viewing Policy Simulation - Resultant Set of Policy (RSOP)","newSince":""},
	{"topicId":22229,"target":"Controlling_the_Power_State_of_an_Instance1","title":"Terminating the Power State of Instances","newSince":""},
	{"topicId":22230,"target":"sect-Retiring_Instances","title":"Retiring Instances","newSince":""},
	{"topicId":14807,"target":"chap-Alerts","title":"Alerts","newSince":""},
	{"topicId":22231,"target":"Setting_a_Retirement_Date_for_an_Instance","title":"Setting a Retirement Date for an Instance","newSince":""},
	{"topicId":14808,"target":"sect-Notifier_Server_Role","title":"Notifier Server Role","newSince":""},
	{"topicId":22232,"target":"Removing_a_Retirement_Date_for_an_Instance","title":"Removing a Retirement Date for an Instance","newSince":""},
	{"topicId":14809,"target":"To_assign_the_Notifier_Role","title":"Assigning the Notifier Role","newSince":""},
	{"topicId":22233,"target":"Immediately_Retiring_an_Instance","title":"Immediately Retiring an Instance","newSince":""},
	{"topicId":14811,"target":"To_create_an_Alert","title":"Creating an Alert","newSince":""},
	{"topicId":14812,"target":"sect-Virtual_Machine_and_Instance_Alerts","title":"Virtual Machine and Instance Alerts","newSince":""},
	{"topicId":14814,"target":"To_create_an_Event_Log_Threshold_Alert","title":"Creating an Event Log Threshold Alert","newSince":""},
	{"topicId":14816,"target":"To_create_an_Event_Threshold_Alert","title":"Creating an Event Threshold Alert","newSince":""},
	{"topicId":14818,"target":"To_create_a_Hardware_Reconfigure_Alert","title":"Creating a Hardware Reconfigured Alert","newSince":""},
	{"topicId":14820,"target":"To_create_a_Normal_Operating_Range_Alert","title":"Creating a Normal Operating Range Alert","newSince":""},
	{"topicId":14822,"target":"To_create_a_Real_Time_Performance_Alert","title":"Creating a Real Time Performance Alert","newSince":""},
	{"topicId":14824,"target":"To_create_an_Hourly_Performance_Alert","title":"Creating an Hourly Performance Alert","newSince":""},
	{"topicId":14826,"target":"To_create_a_Hostd_Log_Threshold_Alert","title":"Creating a hostd Log Threshold Alert","newSince":""},
	{"topicId":14828,"target":"To_create_a_VMware_Alarm_Alert","title":"Creating a VMware Alarm Alert","newSince":""},
	{"topicId":14830,"target":"Expression_Alerts","title":"Creating an Expression Alert","newSince":""},
	{"topicId":14831,"target":"sect-CloudForms_Management_Engine_Operational_Alerts","title":"CloudForms Management Engine Operational Alerts","newSince":""},
	{"topicId":14832,"target":"To_create_an_Operational_Alert","title":"Create an Operational Alert","newSince":""},
	{"topicId":14833,"target":"Operational_Alerts","title":"Operational Alert Types","newSince":""},
	{"topicId":14835,"target":"To_edit_an_Alert","title":"Editing an Alert","newSince":""},
	{"topicId":14837,"target":"To_copy_an_Alert","title":"Copying an Alert","newSince":""},
	{"topicId":14839,"target":"To_delete_an_Alert","title":"Deleting an Alert","newSince":""},
	{"topicId":14841,"target":"To_evaluate_an_Alert1","title":"Evaluating an Alert","newSince":""},
	{"topicId":14843,"target":"To_create_an_Alert_Profile","title":"Creating Alert Profiles","newSince":""},
	{"topicId":14845,"target":"To_edit_an_Alert_Profile","title":"Editing an Alert Profile","newSince":""},
	{"topicId":14847,"target":"To_delete_an_Alert_Profile","title":"Deleting an Alert Profile","newSince":""}], 23038, "Red Hat CloudForms", "Control Guide", "3.2");