[id="Checking_for_migration_prerequisites_{context}"]
= Checking for migration prerequisites

Check your migration for the following conditions, which have prerequisites:

* *You are migrating previously migrated virtual machines*
+
Previously migrated machines are added to the migration plan with a CSV file. This is also recommended for large migrations

* *You are using Ansible playbooks for premigration/postmigration tasks*
+
Create an Ansible repository and add the credentials and playbooks to CloudForms.

* *You are migrating virtual machines running RHEL or other Linux operating system*
+
RHEL/Linux virtual machines require additional configuration to preserve their IP addresses after migration

If these conditions do not apply, you can create a migration plan.

include::proc_Creating_a_csv_file_to_add_virtual_machines_to_the_migration_plan.adoc[leveloffset=+1]

You can create a migration plan.

include::proc_Adding_ansible_playbooks_to_cloudforms.adoc[leveloffset=+1]

You can create a migration plan.

If you are migrating virtual machines running RHEL or other Linux operating system, you must create a RHEL premigration playbook.

include::proc_Creating_a_rhel_premigration_playbook.adoc[leveloffset=+1]

You will select this playbook when you create the migration plan.
