[id="Checking_for_migration_prerequisites_{context}"]
= Checking for migration prerequisites

Check your migration for the following conditions, which have prerequisites:

You are migrating previously migrated virtual machines::
Add previously migrated machines to the migration plan with a CSV file. A CSV file is also recommended for large migrations.
+
See xref:Creating_a_csv_file_to_add_virtual_machines_to_the_migration_plan_{context}[].

You are using Ansible playbooks for premigration/postmigration tasks::
Create an Ansible repository and add credentials and playbooks to CloudForms.
+
See xref:Adding_ansible_playbooks_to_cloudforms_{context}[].

You are migrating virtual machines running RHEL or other Linux operating system::
Create a RHEL premigration playbook to preserve IP addresses and select this playbook when you create a migration plan.
+
See xref:Adding_ansible_playbooks_to_cloudforms_{context}[] and xref:Creating_a_rhel_premigration_playbook_{context}[].

include::proc_Creating_a_csv_file_to_add_virtual_machines_to_the_migration_plan.adoc[leveloffset=+1]
include::proc_Adding_ansible_playbooks_to_cloudforms.adoc[leveloffset=+1]
include::proc_Creating_a_rhel_premigration_playbook.adoc[leveloffset=+1]
