[id="Migrating_the_virtual_machines_{context}"]
= Migrating the virtual machines

ifdef::rhv[]
Migrating the virtual machines involves the following key tasks:

. Mapping the resources of your VMware and Red Hat Virtualization environments. See xref:Creating_an_infrastructure_mapping_for_{context}[].
endif::rhv[]
ifdef::osp[]
Migrating the virtual machines involves the following key tasks:

. Mapping the resources of your VMware and Red Hat OpenStack Platform environments. See xref:Creating_an_infrastructure_mapping_for_{context}[].
endif::osp[]
. Checking for migration conditions with prerequisites. See xref:Checking_for_migration_prerequisites_{context}[].
. Creating and running a migration plan. See xref:Creating_a_migration_plan_in_cloudforms_{context}[].
+
(Optional) You can change the maximum number of concurrent migrations for conversion hosts or providers to control the migration process. See xref:Changing_the_maximum_number_of_concurrent_migrations_{context}[].

include::proc_Creating_an_infrastructure_mapping.adoc[leveloffset=+1]

After you have created an infrastructure mapping, you can check for migration prerequisites. If these conditions do not apply, you can create a migration plan. See xref:Creating_a_migration_plan_in_cloudforms_{context}[].

include::assembly_Checking_for_migration_prerequisites.adoc[leveloffset=+1]

You can create a migration plan. See xref:Creating_a_migration_plan_in_cloudforms_{context}[].

include::proc_Creating_a_migration_plan_in_cloudforms.adoc[leveloffset=+1]

include::../modules/proc_Changing_the_maximum_number_of_concurrent_migrations.adoc[leveloffset=+2]
