// Module included in the following assemblies:
// assembly_Migrating_the_infrastructure.adoc
[id="Migration_plan_prerequisites"]
= Migration plan prerequisites

Check your migration for the following conditions, which have prerequisites:

* *You are migrating previously migrated virtual machines*
+
Previously migrated machines are added to the migration plan with a CSV file. This is also recommended for large migrations. See xref:Creating_a_csv_file_to_add_virtual_machines_to_the_migration_plan[].

* *You are migrating virtual machines running RHEL or other Linux operating system*
+
RHEL/Linux virtual machines require additional configuration to preserve their IP addresses after migration. See xref:Creating_a_rhel_premigration_playbook[].

* *You are using Ansible playbooks for premigration/postmigration tasks*
+
Create an Ansible repository and add the credentials and playbooks to CloudForms. See xref:Adding_ansible_playbooks_to_cloudforms[].

If these conditions do not apply, you can create a migration plan. See xref:Creating_a_migration_plan_in_cloudforms[].

include::proc_Creating_a_csv_file_to_add_virtual_machines_to_the_migration_plan.adoc[leveloffset=+1]
include::proc_Creating_a_rhel_premigration_playbook.adoc[leveloffset=+1]
include::proc_Adding_ansible_playbooks_to_cloudforms.adoc[leveloffset=+1]
