// Module included in the following assemblies:
//
// assembly_Configuring_the_1_1_conversion_hosts.adoc
// assembly_Configuring_the_1_2_conversion_hosts.adoc
[id="Copying_vmware_keys_to_{context}_conversion_hosts"]
= Copying the VMware SSH keys to the conversion hosts

If you collected the VMware SSH public keys when you enabled SSH access in the VMware hypervisors, perform the following procedure to copy the keys to your conversion hosts:

ifdef::rhv[]
. Copy the VMware keys to `/var/lib/vdsm/.ssh/known_hosts` on each conversion host.
include::../ims_common/proc_Verifying_the_ssh_connection_for_conversion_hosts.adoc[]
endif::rhv[]
ifdef::osp[]
. Copy the VMware keys to `/root/.ssh/known_hosts` on each conversion host.
include::../ims_common/proc_Verifying_the_ssh_connection_for_conversion_hosts.adoc[]
endif::osp[]

If you did not collect the VMware keys when you configured the VMware hypervisors, perform the following procedure to collect the keys with `ssh-keyscan` and copy them to your conversion hosts:

[CAUTION]
====
You must run `ssh-keyscan` for each VMware hypervisor. Otherwise your conversion hosts will not have all the VMware hypervisor keys and the migration will fail.
====

. Run `ssh-keyscan` for each VMware hypervisor IP address and copy its public key to `known_hosts`, as in the following example:
ifdef::rhv[]
+
[options="nowrap" subs="+quotes,verbatim"]
----
# ssh-keyscan _esx1_IP_ > /var/lib/vdsm/.ssh/known_hosts
# ssh-keyscan _esx2_IP_ >> /var/lib/vdsm/.ssh/known_hosts
# ssh-keyscan _esx3_IP_ >> /var/lib/vdsm/.ssh/known_hosts
----

. Change the ownership of the `known_hosts` file to `vdsm` user and `kvm` group:
+
----
# chown 36:36 /var/lib/vdsm/.ssh/known_hosts
----
include::../ims_common/proc_Verifying_the_ssh_connection_for_conversion_hosts.adoc[]
endif::rhv[]
ifdef::osp[]
+
[options="nowrap" subs="+quotes,verbatim"]
----
# ssh-keyscan _esx1_IP_ > /root/.ssh/known_hosts
# ssh-keyscan _esx2_IP_ >> /root/.ssh/known_hosts
# ssh-keyscan _esx3_IP_ >> /root/.ssh/known_hosts
----
include::../ims_common/proc_Verifying_the_ssh_connection_for_conversion_hosts.adoc[]
endif::osp[]
