// Module included in the following assemblies:
// proc_Configuring_the_conversion_hosts_for_transformation.adoc
[id="Copying_the_vmware_keys_to_the_conversion_hosts"]
= Copying the VMware keys to the conversion hosts for SSH transformation

To prevent man-in-the-middle attacks, the conversion hosts do not accept the VMware keys by default for SSH transformation. Instead, the `known_hosts` file of each conversion host must be populated with the public keys of the VMware hypervisors.

Depending on the security processes of your VMware environment, you can either obtain a list of public keys from the VMware system administrators, if they collected the keys when they xref:Configuring_the_vmware_hypervisors_for_ssh_transformation[enabled SSH access on the hypervisors], or you can use `ssh-keyscan`.

[WARNING]
====
You must run `ssh-keyscan` multiple times, once for each VMware hypervisor, repeating the procedure on each conversion host. Otherwise your conversion hosts will not have all the VMware keys and the migration will fail.
====

.Gathering VMware keys with `ssh-keyscan`

. On a conversion host, run `ssh-keyscan`, as in the following examples:
+
.Red Hat Virtualization
[options="nowrap" subs="+quotes,verbatim"]
----
# ssh-keyscan _esx1.example.com_ > /var/lib/vdsm/.ssh/known_hosts
# ssh-keyscan _esx2.example.com_ > /var/lib/vdsm/.ssh/known_hosts
# ssh-keyscan _esx3.example.com_ > /var/lib/vdsm/.ssh/known_hosts
----
+
Change the ownership of the `known_hosts` file to user `vdsm` and group `kvm`:
+
----
# chown 36:36 /var/lib/vdsm/.ssh/known_hosts
----
+
.OpenStack Platform
[options="nowrap" subs="+quotes,verbatim"]
----
# ssh-keyscan _esx1.example.com_ > /root/.ssh/known_hosts
# ssh-keyscan _esx2.example.com_ > /root/.ssh/known_hosts
# ssh-keyscan _esx3.example.com_ > /root/.ssh/known_hosts
----

. Repeat for each conversion host, to ensure that all your conversion hosts have all the VMware keys.
