// Module included in the following assemblies:
// proc_Configuring_the_conversion_hosts_for_transformation.adoc
[id="Copying_the_vmware_keys_for_SSH_for_{context}"]
ifdef::rhv[]
= Copying the VMware keys for Red Hat Virtualization
endif::rhv[]
ifdef::osp[]
= Copying the VMware keys for OpenStack Platform
endif::osp[]

To prevent man-in-the-middle attacks, the conversion hosts do not accept the VMware keys by default for SSH transformation. Instead, the `known_hosts` file of each conversion host must be populated with the public keys of the VMware hypervisors.

Depending on the security processes of your VMware environment, you can either obtain a list of public keys from the VMware system administrators, if they collected the keys when they xref:Configuring_the_vmware_hypervisors_for_ssh_transformation[enabled SSH access on the hypervisors], or you can use `ssh-keyscan`.

[WARNING]
====
You must run `ssh-keyscan` multiple times, once for each VMware hypervisor.

Otherwise your conversion hosts will not have all the VMware keys and the migration will fail.
====

ifdef::rhv[]
Perform the following procedure on the Manager machine:

. Run `ssh-keyscan` for each VMware hypervisor, using its IP address, and output the public key to `known_hosts`, as in the following example:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# ssh-keyscan _10.19.2.12_ > /var/lib/vdsm/.ssh/known_hosts
# ssh-keyscan _10.19.2.13_ >> /var/lib/vdsm/.ssh/known_hosts
# ssh-keyscan _10.19.2.14_ >> /var/lib/vdsm/.ssh/known_hosts
----

. Change the ownership of the `known_hosts` file to user `vdsm` and group `kvm`:
+
----
# chown 36:36 /var/lib/vdsm/.ssh/known_hosts
----
endif::rhv[]
ifdef::osp[]
Perform the following procedure on a conversion host:

. Run `ssh-keyscan` for each VMware hypervisor, using its IP address, and output the public key to `known_hosts`, as in the following example:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# ssh-keyscan _10.19.2.12_ > /root/.ssh/known_hosts
# ssh-keyscan _10.19.2.13_ >> /root/.ssh/known_hosts
# ssh-keyscan _10.19.2.14_ >> /root/.ssh/known_hosts
----

. Repeat the procedure on each conversion host, to ensure that all the conversion hosts have all the VMware keys.
. Connect to each VMware hypervisor from each conversion host as `cloud-user` to verify the SSH connection.
+
[IMPORTANT]
====
If the SSH connection to a VMware hypervisor fails, check xref:Configuring_the_vmware_hypervisors_for_ssh_transformation[].
====
+
If the connection is successful, you can create an infrastructure mapping. See xref:Creating_an_infrastructure_mapping[].
endif::osp[]
