// Module included in the following assemblies:
// con_Migration_plan_options.adoc
[id="Creating_a_rhel_premigration_playbook_{context}"]
= Creating a `RHEL premigration` playbook for RHEL/Linux source virtual machines

If you are migrating virtual machines running RHEL or other Linux operating system, a `RHEL premigration` playbook ensures that their IP addresses are accessible after migration. The `RHEL premigration` playbook calls the Ansible `ims.rhel_premigration` role.

You can install the role with Ansible Galaxy. See link:https://galaxy.ansible.com/fdupont_redhat/ims_rhel_pre_migration[ims_rhel_pre_migration]. The role is not included in the IMS installation.

The `ims.rhel_premigration` role performs the following tasks on the VMware virtual machines:

* Preserves the static IP address configuration by creating udev rules to associate the virtual machine's MAC address with its interface name
* (Red Hat Virtualization only) Installs the Red Hat Virtualization guest agent, which enables Red Hat Virtualization to report the IP address of the new virtual machine and to integrate it into the new environment

[NOTE]
====
The `ims.rhel_premigration` role assumes that either the `rhel-6-server-rpms` or the `rhel-7-server-rpms` repository is enabled in the source virtual machine when it installs `qemu-guest-agent`. If you have disabled the repository, re-enable it in the RHEL premigration playbook.
====

.`RHEL premigration` playbook example
[source,yml]
----
---
- hosts: all
  roles:
    - role: ims.rhel_pre_migration
----
