// Module included in the following assemblies:
// proc_Configuring_the_conversion_hosts_for_transformation.adoc
[id="Copying_the_vmware_keys_to_the_conversion_hosts"]
= Copying the VMware keys for SSH transformation

To prevent man-in-the-middle attacks, the conversion hosts do not accept the VMware keys by default for SSH transformation. Instead, the `known_hosts` file of each conversion host must be populated with the public keys of the VMware hypervisors.

Depending on the security processes of your VMware environment, you can either obtain a list of public keys from the VMware system administrators, if they collected the keys when they xref:Configuring_the_vmware_hypervisors_for_ssh_transformation[enabled SSH access on the hypervisors], or you can use `ssh-keyscan`.

[WARNING]
====
You must run `ssh-keyscan` multiple times, once for each VMware hypervisor. Otherwise your conversion hosts will not have all the VMware keys and the migration will fail.
====

[id="Copying_vmware_keys_for_rhv"]
== Copying VMware keys for Red Hat Virtualization

. On the Manager machine, run `ssh-keyscan` for each VMware hypervisor, as in the following examples:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# ssh-keyscan _esx1.example.com_ > /var/lib/vdsm/.ssh/known_hosts
# ssh-keyscan _esx2.example.com_ >> /var/lib/vdsm/.ssh/known_hosts
# ssh-keyscan _esx3.example.com_ >> /var/lib/vdsm/.ssh/known_hosts
----

. Change the ownership of the `known_hosts` file to user `vdsm` and group `kvm`:
+
----
# chown 36:36 /var/lib/vdsm/.ssh/known_hosts
----

[id="Copying_vmware_keys_for_osp"]
== Copying VMware keys for OpenStack Platform

. On each conversion host, run `ssh-keyscan`for each VMware hypervisor, as in the following examples:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# ssh-keyscan _esx1.example.com_ > /root/.ssh/known_hosts
# ssh-keyscan _esx2.example.com_ >> /root/.ssh/known_hosts
# ssh-keyscan _esx3.example.com_ >> /root/.ssh/known_hosts
----

. Repeat for each conversion host, to ensure that all your conversion hosts have all the VMware keys.
