// Module included in the following assemblies:
// assembly_Preparing_the_environment_for_migration.adoc
[id="Preparing_the_vmware_source_environment"]
= Preparing the VMware source environment

Preparing the VMware source environment involves the following tasks:

. Preparing the VMware network. See xref:Preparing_the_vmware_network[].
. Preparing the VMware virtual machines. See xref:Preparing_the_source_virtual_machines[].
. (SSH only) Configuring the VMware hypervisors. See xref:Configuring_the_vmware_hypervisors_for_ssh_transformation[].

(VDDK only, optional) If you intend to run more than 10 concurrent migrations per conversion host using VDDK transformation, you can increase each VMware hypervisor's memory. See xref:Increasing_esxi_memory_for_vddk_transformation[].

[id="Preparing_the_vmware_network"]
== Preparing the VMware network

Extend the VMware network to the target environment.

[IMPORTANT]
====
* The network configuration must not be changed in any way during the migration.
* IP addresses, VLANs, and other network configurations should not be changed before or after migration because the conversion process preserves the source virtual machine MAC addresses.
====

[id="Preparing_the_source_virtual_machines"]
== Preparing the VMware virtual machines

Perform the following steps on each VMware virtual machine that you are migrating:

. Install VMware Tools to capture IP addresses.
+
For download and installation instructions, navigate to link:https://www.vmware.com/support/ws5/doc/new_guest_tools_ws.html[
VMware Workstation 5.0 Installing VMware Tools].
. Unmount mounted ISO/CDROM disks.
. Ensure that attached disks are not encrypted.
. Ensure that each NIC has no more than one IPv4 and/or one IPv6 address.
. Ensure that the virtual machine names contain only upper- or lower-case letters, numbers, underscores (`_`), hyphens (`-`), or periods (`.`).
+
[NOTE]
====
International characters and spaces are not permitted.
====

. Ensure that source virtual machine names do not duplicate target machine names for the appropriate scope:

* Red Hat Virtualization: Within the entire environment
* Red Hat OpenStack Platform: Within a single tenant

If you are using VDDK transformation, you are ready to prepare the target environment.

If you are using SSH transformation, you must configure the VMware hypervisors.

[id="Configuring_the_vmware_hypervisors_for_ssh_transformation"]
== (SSH only) Configuring the VMware hypervisors for SSH transformation

SSH transformation requires the VMware hypervisors to be configured for passwordless access by the conversion hosts:

. Enable SSH access on each VMware hypervisor:
+
For instructions, navigate to link:https://docs.vmware.com/en/VMware-vSphere/index.html[VMware vSphere Documentation]. In the navigation pane, click menu:vSphere _version_[ESXi and vCenter Server > VMware ESXi Installation and Setup > Installing and Setting Up ESXi > Setting Up ESXi > Enable ESXi Shell and SSH Access with the Direct Console User Interface].
+
[NOTE]
====
If your security policies allow you to collect the SSH public keys of the VMware hypervisors at this stage, save them for copying to the conversion hosts.
====

. Generate an SSH key pair without a passphrase:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# ssh-keygen -N ''
----

. Copy the public SSH key to `/etc/ssh/keys-root/authorized_keys` on *each* VMware hypervisor.

[IMPORTANT]
====
A single SSH key pair for all conversion hosts is recommended because the key pair is used only for virtual machine conversion and it simplifies conversion host management.

If you wish to use a dedicated SSH key pair for each conversion host, you can create multiple key pairs. You must copy all the public keys to each VMware hypervisor.
====

[id="Increasing_esxi_memory_for_vddk_transformation"]
== (VDDK only, optional) Increasing the memory of VMware hypervisors for VDDK transformation

If you are using VDDK transformation and you plan to run more than 10 concurrent migrations per conversion host, you must increase the VMware hypervisor's memory. Otherwise the migration will fail, due to an ESXi service memory limitation. (See link:http://libguestfs.org/virt-v2v.1.html#vddk:-esxi-nfc-service-memory-limits[VDDK: ESXi NFC SERVICE MEMORY LIMITS] in link:http://libguestfs.org/virt-v2v.1.html[virt-v2v - Convert a guest to use KVM] for details.)

.Procedure

. Log in to a VMware hypervisor.
. Change the value of `maxMemory` to `1000000000` in `/etc/vmware/hostd/config.xml`:
+
[options="nowrap" subs="+quotes,verbatim"]
----
      <nfcsvc>
         <path>libnfcsvc.so</path>
         <enabled>true</enabled>
         <maxMemory>1000000000</maxMemory>
         <maxStreamMemory>10485760</maxStreamMemory>
      </nfcsvc>
----

. Restart `hostd`:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# /etc/init.d/hostd restart
----
+
You do not need to reboot the VMware hypervisor.
