// Module included in the following assemblies:
// IMS_1.2/modules/proc_Configuring_the_conversion_hosts_for_transformation.adoc
[id="Copying_the_vmware_keys_for_SSH_for_{context}"]

ifdef::rhv[]
= Copying VMware keys to Red Hat Virtualization conversion hosts
endif::rhv[]
ifdef::osp[]
= Copying VMware keys to Red Hat OpenStack Platform conversion hosts
endif::osp[]

.Copying collected VMware keys

If you collected the SSH public keys in when you enabled SSH access in the VMware hypervisors, perform the following procedure:

ifdef::rhv[]
. Copy the VMware keys to `/var/lib/vdsm/.ssh/known_hosts` on each conversion host.
include::../ims_common/proc_Verifying_the_ssh_connection_for_conversion_hosts.adoc[]
endif::rhv[]
ifdef::osp[]
. Copy the VMware keys to `/root/.ssh/known_hosts` on each conversion host.
include::../ims_common/proc_Verifying_the_ssh_connection_for_conversion_hosts.adoc[]
endif::osp[]

.Collecting VMware keys with `ssh-keyscan`

If you are collecting the SSH public keys with `keyscan`, perform the following procedure:

[CAUTION]
====
You must run `ssh-keyscan` for each VMware hypervisor. Otherwise your conversion hosts will not have all the VMware hypervisor keys and the migration will fail.
====

Perform the following procedure on each conversion host:

. Run `ssh-keyscan` for each VMware hypervisor IP address and copy its public key to `known_hosts`, as in the following example:
ifdef::rhv[]
+
[options="nowrap" subs="+quotes,verbatim"]
----
# ssh-keyscan _esx1_IP_ > /var/lib/vdsm/.ssh/known_hosts
# ssh-keyscan _esx2_IP_ >> /var/lib/vdsm/.ssh/known_hosts
# ssh-keyscan _esx3_IP_ >> /var/lib/vdsm/.ssh/known_hosts
----

. Change the ownership of the `known_hosts` file to `vdsm` user and `kvm` group:
+
----
# chown 36:36 /var/lib/vdsm/.ssh/known_hosts
----
include::../ims_common/proc_Verifying_the_ssh_connection_for_conversion_hosts.adoc[]
endif::rhv[]
ifdef::osp[]
+
[options="nowrap" subs="+quotes,verbatim"]
----
# ssh-keyscan _esx1_IP_ > /root/.ssh/known_hosts
# ssh-keyscan _esx2_IP_ >> /root/.ssh/known_hosts
# ssh-keyscan _esx3_IP_ >> /root/.ssh/known_hosts
----
include::../ims_common/proc_Verifying_the_ssh_connection_for_conversion_hosts.adoc[]
endif::osp[]

If the connection is successful, you can create an infrastructure mapping. See xref:Creating_an_infrastructure_mapping[].
