// Module included in the following assemblies:
// assembly_Preparing_the_environment_for_migration.adoc
[id="Preparing_the_vmware_source_environment"]
= Preparing the VMware source environment

Prepare the VMware source environment for migration:

. Extend the VMware network to the target environment.
+
[IMPORTANT]
====
* The network configuration must not be changed in any way during the migration.
* IP addresses, VLANs, and other network configurations should not be changed before or after migration because the conversion process preserves the source virtual machine MAC addresses.
====

. Prepare the VMware virtual machines. See xref:Preparing_the_source_virtual_machines[].
. Configure the VMware hypervisors for SSH transformation, if necessary. See xref:Configuring_the_vmware_hypervisors_for_ssh_transformation[].

[id="Preparing_the_source_virtual_machines"]
== Preparing the VMware virtual machines

Perform the following steps on each VMware virtual machine that you are migrating:

. Install VMware Tools to capture IP addresses. For download and installation instructions, navigate to link:https://www.vmware.com/support/ws5/doc/new_guest_tools_ws.html[].
. Unmount mounted ISO/CDROM disks.
. Ensure that attached disks are not encrypted.
. Ensure that each NIC has no more than one IPv4 and/or one IPv6 address.
. Ensure that the virtual machine names contain only upper- or lower-case letters, numbers, underscores (`_`), hyphens (`-`), or periods (`.`).
+
[NOTE]
====
International characters and spaces are not permitted.
====

. Ensure that source virtual machine names do not duplicate target machine names for the appropriate scope:

* Red Hat Virtualization: Within the entire environment
* Red Hat OpenStack Platform: Within a single tenant

If you are using VDDK transformation, you are ready to prepare the target environment. See xref:Preparing_the_target_environment[].

If you are using SSH transformation, you should prepare the VMware hypervisors. See  xref:Configuring_the_vmware_hypervisors_for_ssh_transformation[].

[id="Configuring_the_vmware_hypervisors_for_ssh_transformation"]
== Preparing the VMware hypervisors for SSH transformation

SSH transformation requires the VMware hypervisors to be configured for passwordless access by the conversion hosts:

. Enable SSH access on each VMware hypervisor:
+
For instructions, navigate to link:https://docs.vmware.com/en/VMware-vSphere/index.html[]. In the navigation pane, click menu:vSphere _version_[ESXi and vCenter Server > VMware ESXi Installation and Setup > Installing and Setting Up ESXi > Setting Up ESXi > Enable ESXi Shell and SSH Access with the Direct Console User Interface].
+
[NOTE]
====
If your security processes allow you to collect the VMware hypervisors' public keys, save them for xref:Configuring_the_conversion_hosts[].
====

. Generate an SSH key pair without a passphrase:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# ssh-keygen -N ''
----

. Copy the public SSH key to `/etc/ssh/keys-root/authorized_keys` on *each* VMware hypervisor. (The private key is used in xref:Configuring_the_conversion_hosts[].)

[IMPORTANT]
====
A single SSH key pair for all conversion hosts is recommended because the key pair is used only for virtual machine conversion and it simplifies conversion host management.

If you wish to use a dedicated SSH key pair for each conversion host, you can create multiple key pairs. You must copy all the public keys to each VMware hypervisor.
====

You are ready to prepare your xref:Preparing_the_target_environment[target environment].
