// Module included in the following assemblies:
// assembly_Preparing_the_environment_for_migration.adoc
[id="Preparing_the_vmware_source_environment"]
= Preparing the VMware source environment

Preparing the VMware source environment involves the following tasks:

. Preparing the VMware network. See xref:Preparing_the_vmware_network[].
. Preparing the VMware virtual machines. See xref:Preparing_the_source_virtual_machines[].
. (SSH only) Configuring all VMware hypervisors for passwordless access. See xref:Configuring_the_vmware_hypervisors_for_ssh_transformation[].
+
(VDDK only) Configuring a VMware hypervisor if it must support more than ten concurrent migrations. See xref:Increasing_esxi_memory_for_vddk_transformation[].

[id="Preparing_the_vmware_network"]
== Preparing the VMware network

Extend the VMware network to the target environment.

[IMPORTANT]
====
* The network configuration must not be changed in any way during the migration.
* IP addresses, VLANs, and other network configuration must not be changed before or after migration because the conversion process preserves the source virtual machine MAC addresses.
====

[id="Preparing_the_source_virtual_machines"]
== Preparing the VMware virtual machines

Perform the following steps on each VMware virtual machine that you are migrating:

. Install VMware Tools to capture IP addresses.
+
To download and install VMware Tools, see link:https://www.vmware.com/support/ws5/doc/new_guest_tools_ws.html[VMware Workstation 5.0: Installing VMware Tools].

. Unmount mounted ISO/CDROM disks.
. Ensure that attached disks are not encrypted.
. Ensure that each NIC has no more than one IPv4 and/or one IPv6 address.
. Ensure that the virtual machine names contain only upper- or lower-case letters, numbers, underscores (`_`), hyphens (`-`), or periods (`.`).
+
[NOTE]
====
International characters and spaces are not permitted.
====

. Ensure that source virtual machine names do not duplicate target machine names for the appropriate scope:

* Red Hat Virtualization: Within the entire environment
* Red Hat OpenStack Platform: Within a single tenant

If you are performing more than ten concurrent migrations from a VMware hypervisor, you must increase the its NFC service memory. See xref:Increasing_esxi_memory_for_vddk_transformation[].

If you are using SSH transformation, you must configure the VMware hypervisors for passwordless access. See xref:Configuring_the_vmware_hypervisors_for_ssh_transformation[].

[id="Configuring_the_vmware_hypervisors_for_ssh_transformation"]
== (SSH only) Configuring the VMware hypervisors for passwordless access

SSH transformation requires the VMware hypervisors to be configured for passwordless access by the conversion hosts:

. Enable SSH access on each VMware hypervisor:
+
For instructions, navigate to link:https://docs.vmware.com/en/VMware-vSphere/index.html[VMware vSphere Documentation]. In the navigation pane, click menu:vSphere _version_[ESXi and vCenter Server > VMware ESXi Installation and Setup > Installing and Setting Up ESXi > Setting Up ESXi > Enable ESXi Shell and SSH Access with the Direct Console User Interface].
+
[NOTE]
====
If your security policies allow you to collect the SSH public keys of the VMware hypervisors at this stage, save them for copying to the conversion hosts.
====

. Generate an SSH key pair without a passphrase:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# ssh-keygen -N ''
----

. Copy the public SSH key to `/etc/ssh/keys-root/authorized_keys` on *each* VMware hypervisor.

[IMPORTANT]
====
A single SSH key pair for all conversion hosts is recommended because the key pair is used only for virtual machine conversion and it simplifies conversion host management.

If you wish to use a dedicated SSH key pair for each conversion host, you can create multiple key pairs. You must copy all the public keys to each VMware hypervisor.
====

[id="Increasing_esxi_memory_for_vddk_transformation"]
== (VDDK only) Configuring a VMware hypervisor for more than ten concurrent migrations

If you are performing more than ten concurrent migrations from a VMware hypervisor using VDDK transformation, the migration will fail because the hypervisor cannot handle more than ten parallel connections. See link:https://pubs.vmware.com/vsphere-6-5/topic/com.vmware.vddk.pg.doc/vddkDataStruct.5.5.html#1025227[VMware vSphere 6.5 NFC session connection limits] and link:http://libguestfs.org/virt-v2v.1.html#vddk:-esxi-nfc-service-memory-limits[Virt-v2v. VDDK: ESXi NFC service memory limits] for details.

You must increase the hypervisor's maximum NFC service memory to enable additional connections for migrations.

.Procedure

. Log in to a VMware hypervisor.
. Change the value of `maxMemory` to `1000000000` in `/etc/vmware/hostd/config.xml`:
+
[options="nowrap" subs="+quotes,verbatim"]
----
      <nfcsvc>
         <path>libnfcsvc.so</path>
         <enabled>true</enabled>
         <maxMemory>1000000000</maxMemory>
         <maxStreamMemory>10485760</maxStreamMemory>
      </nfcsvc>
----

. Restart `hostd`:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# /etc/init.d/hostd restart
----
+
You do not need to reboot the VMware hypervisor.
