// Module included in the following assemblies:
// assembly_Planning_the_migration.adoc
[id="Recommendations_for_migration_{context}"]
= Recommendations and best practices

The following recommendations will help to minimize the impact of the migration on your environment.

.Scheduling the migration

* Schedule your migration carefully, to minimize the impact on your users.
* Prepare your users for downtime.
+
[IMPORTANT]
====
Currently, IMS supports only cold migration. Virtual machines are powered off gracefully as part of the migration process.
====

* Stagger the migration schedules.
* Move critical applications during maintenance windows.

.Distributing the migration workload

* Create migration groups, so that you are not migrating all of your virtual machines at the same time, keeping in mind the following considerations:

** How are the virtual machines grouped now?
** Which virtual machines should be migrated together?
** Which workloads or linked applications should be migrated together?
** What applications must remain available?

* Consider which parts of the workload to migrate first:

** Databases
** Applications
** Web servers
** Load balancers

.Deploying the conversion hosts

* Create enough conversion hosts for your migration, with sufficient resources.
* Create multiple conversion hosts for load-balancing. The virtual machines in a migration plan are automatically distributed among the conversion hosts. This decreases the load on the conversion hosts and allows you to increase the concurrent migrations beyond the limits of a single conversion host.

.Controlling the migration process

* Create multiple migration plans for finer control.
* Perform test migrations with different maximum numbers of concurrent migrations to assess the capabilities of your environment's infrastructure.
