// Module included in the following assemblies:
// assembly_Common_issues_and_mistakes.adoc
[id="Virtual_machine_migration_errors"]
= Virtual machine migration errors

[id="IP_address_errors"]
== Postmigration virtual machine IP address errors

[id="Migrated_RHEL_IP_address_not_accessible"]
* If the IP address of a migrated RHEL (or other Linux-based operating system) virtual machine is not accessible, create a xref:Creating_a_rhel_premigration_playbook[`RHEL premigration` playbook] and add it to the xref:Advanced_options_screen[migration plan].

[id="Migrated_VM_missing_IP"]
* If a migrated virtual machine does not have an IP address:

** Check that VMware Tools is installed on the source virtual machine.
[id="OSP_missing_IP"]
** OpenStack Platform: Check the source virtual machine for an interface configuration file mapped to a non-existent interface (for example, `/etc/sysconfig/network-scripts/ifcfg-eth1` exists, but `eth1` interface does not). Log example:
+
[options="" subs="+quotes,verbatim"]
----
CalledProcessError: Command \'['openstack', u'--os-username=admin', u'--os-identity-api-version=3', u'--os-user-domain-name=default', u'--os-auth-url=http://_osp.example.com_:5000/v3', u'--os-project-name=admin', u'--os-password=\*\*******', u'--os-project-id=0123456789abcdef0123456789abcdef', \'port', \'create', \'--format', \'json', \'--network', u'01234567-89ab-cdef-0123-456789abcdef', \'--mac-address', u'00:50:56:01:23:45', \'--enable', u'port_0', \'--fixed-ip', \'*ip-address=None*'"]' returned non-zero exit status 1
_date_ _time_:ERROR: Command output:
BadRequestException: Unknown error
----

[id="VMware_environment_errors"]
== VMware environment errors

A source virtual machine cannot migrate if it has any of the following conditions:

* Mounted ISO/CDROM disk
* Encrypted disk
* Invalid name (containing spaces or special characters)

If you are using SSH transformation, see xref:Configuring_the_vmware_hypervisors_for_ssh_transformation[].

[id="Target_environment_errors"]
== Target environment errors

[id="RHV_VM_migration_failure"]
*Red Hat Virtualization*
[id="RHV_name_conflict"]
* Name conflict: VMware virtual machine has the same name as a RHV virtual machine.
* MAC address conflict: VMware virtual machine has the same MAC address as a RHV virtual machine in a MAC address pool.

* SSH transformation failure:

** If you are using SSSD with single sign-on, xref:Reinstalling_ipa_client[reinstall `ipa-client`] without the OpenSSH client on the Manager machine.
** Check that SSH transformation was correctly configured. See xref:Configuring_the_vmware_hypervisors_for_ssh_transformation[] and xref:Configuring_the_conversion_hosts[].
** Check that the conversion host does not have an existing private SSH key in `/var/lib/vdsm/.ssh/id_rsa`. Conversion host configuration does not overwrite SSH keys. They must be deleted manually.

[id="OSP_VM_migration_failure"]
*OpenStack Platform*
[id="OSP_VM_powered_off"]
* Virtual machine powered off: The virtual machine must be powered on at the time of migration.

* SSH transformation failure: Check that SSH transformation was correctly configured. See xref:Configuring_the_vmware_hypervisors_for_ssh_transformation[] and xref:Configuring_the_conversion_hosts[].

[id="OSP_not_authorized"]
* `disallowed by policy` error: The OpenStack Platform `admin` user in CloudForms does not have `admin` role privileges within the target project. Add the `admin` user as `member` and `admin` to your target project (see link:https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/14/html-single/users_and_identity_management_guide/#edit_a_project[Edit a Project] in the _Red Hat OpenStack Platform Users and Identity Management Guide_). Log example:
+
[options="" subs="+quotes,verbatim"]
----
ERROR: Command exited with non-zero return code 1, output: HttpException: 403: Client Error for url: https://_FQDN_:13696/v2.0/ports, {"NeutronError": {"message": "((rule:create_port and rule:create_port:mac_address) and rule:create_port:fixed_ips) is disallowed by policy", "type": "PolicyNotAuthorized", "detail": ""}}
----
