// Module included in the following assemblies:
// assembly_Planning_the_migration.adoc
[id="Questions_to_ask_before_migration_{context}"]
= Questions to ask before migration

The following questions can help you to estimate the resources and time required for migration.

What am I migrating?::
* Identify the VMware virtual machines that you will be migrating.

What is the maximum number of disks or virtual machines that I can migrate?::
* There is no maximum number of disks or virtual machines that you can migrate. However, you may not want to migrate all your virtual machines at the same time, in order to minimize the impact on your users.
+
[IMPORTANT]
====
If you exceed the capabilities of your environment, the migrations will fail. This situation could affect existing applications running on virtual machines attached to the network and storage.
====

What operating systems can I migrate?::
* You can migrate any guest operating system that is certified and supported for use with the Red Hat Virtualization Hypervisor. See link:https://access.redhat.com/articles/973163[Certified Guest Operating Systems in Red Hat OpenStack Platform and Red Hat Virtualization].

What am I missing?::
* Identify resource gaps, such as bandwidth, storage, licenses, or a suitable maintenance window, before you begin the migration.

What impact will the migration have on my users?::
* Assess the effects the migration may have on a production environment.
+
It may be possible to migrate your applications in phases, without downtime at the application layer, if the applications are distributed in a high-availability architecture.

* Check whether users will lose access to critical applications.

How long will the migration take?::
There is no formula to estimate how long the actual migration will take. This is determined on a case-by-case basis.
+
The following example is provided as a guide:
+
ifdef::rhv[]
.Red Hat Virtualization migration
+
====
* Duration of migration: 1:15:53 (hh:mm:ss)
* 10 virtual machines
* Total data migrated: 1000 GB
* Hardware:
** Strong host (40 cores, 500 GB RAM)
** Fast SSD XtremIO storage
** Fibre Channel 8 interface for host-to-storage connection
** 10 GbE network interface cards for all other connections
====
endif::rhv[]
ifdef::osp[]
.Red Hat OpenStack Platform migration
+
====
* Duration of migration: 2:13:00 (hh:mm:ss)
* 20 virtual machines
* 2 conversion hosts, maximum of 10 concurrent conversions
* Total data migrated: 1000 GB
* Hardware:
** Strong host (40 cores, 500 GB RAM)
** Fast SSD XtremIO storage
** Fibre Channel 8 interface for host-to-storage connection
** 10 GbE network interface cards for all other connections
====
endif::osp[]

How many conversion hosts do I need?::
The number of conversion hosts you create depends on the size of your migration. All the virtual machines in a migration plan are migrated at the same time, in parallel. The number of virtual machines that you can migrate simultaneously depends on your infrastructure capabilities. Each migration requires a certain amount of network bandwidth, I/O throughput, and processing power for the conversion process.
+
Multiple conversion hosts provide load-balancing and better performance, even for small migrations.
+
Conversion hosts are limited to a maximum of ten concurrent migrations, unless you change the default values.
+
You should test your environment thoroughly before the migration to determine how many migrations it can support without negative effects, for example, five conversion hosts, each running ten concurrent migrations.

// Should I migrate my virtual machines with VDDK or SSH?::
// You can configure your conversion hosts to migrate the virtual machines by using either the VMware Virtual Disk Development Kit (VDDK) or SSH. The choice is determined by the number of virtual machines you are migrating and the capabilities of your infrastructure.
// +
// The following table compares the options.
// +
// [cols="1,2,2", options="header"]
// .VDDK and SSH comparison
// |===
// | ^|Pros ^|Cons
// |*VDDK* .<a|* Recommended because it is approximately twice as fast as SSH
// * Compiled with `nbdkit`, which provides direct connectivity to the virtual machine disks
// .<a|* Requires VDDK package download
// * Requires VDDK package location for conversion host configuration
// * Limited to 20 concurrent migrations per conversion host
// * Limited to 10 concurrent migrations per VMware hypervisor unless you increase the hypervisor's NFC service memory
//
// |*SSH* .<a|* Better suited for large-scale migrations than VDDK (not affected by hypervisor's NFC service memory limitation)
// * Does not require additional downloads, packages, tools, or compilation
// .<a|* Slower than VDDK
// * Requires VMware hypervisors to have SSH access enabled
// * Requires VMware hypervisors and conversion hosts to have shared SSH keys
// |===
