// Module included in the following assemblies:
// assembly_Common_issues_and_mistakes.adoc
[id="Virtual_machine_migration_errors"]
= Environment configuration errors

[id="VMware_environment_errors"]
== VMware

A source virtual machine cannot migrate if it has any of the following conditions:

* Mounted ISO/CDROM disk
* Encrypted disk
* Invalid name (containing spaces or special characters)

If you are using SSH transformation, check the configuration of the VMware hypervisors. See xref:Configuring_the_vmware_hypervisors_for_ssh_transformation[].

[id="Target_environment_errors"]
[id="RHV_VM_migration_failure"]
== Red Hat Virtualization
[id="RHV_name_conflict"]

The following conditions can cause a migration error for Red Hat Virtualization:

* Name conflict: VMware virtual machine has the same name as a Red Hat Virtualization virtual machine.
* MAC address conflict: VMware virtual machine has the same MAC address as a Red Hat Virtualization virtual machine in a MAC address pool.

* SSH transformation only:

** If you are using SSSD with single sign-on, xref:Reinstalling_ipa_client[reinstall `ipa-client`] without OpenSSH.
** Check that SSH transformation was correctly configured. See xref:Configuring_the_vmware_hypervisors_for_ssh_transformation[] and xref:Configuring_the_conversion_hosts[].
** Check that the conversion host does not have an existing private SSH key in `/var/lib/vdsm/.ssh/id_rsa`. Conversion host configuration does not overwrite old SSH keys. They must be deleted manually.

[id="OSP_VM_migration_failure"]
== Red Hat OpenStack Platform

The following conditions can cause a migration error for Red Hat OpenStack Platform:

[id="OSP_VM_powered_off"]
* VMware virtual machine powered off: The virtual machine must be powered on at the time of migration.

* SSH transformation only: Check that SSH transformation was correctly configured. See xref:Configuring_the_vmware_hypervisors_for_ssh_transformation[] and xref:Configuring_the_conversion_hosts[].

[id="OSP_not_authorized"]
* `disallowed by policy` error: The Red Hat OpenStack Platform `admin` user in CloudForms does not have `admin` role privileges within the target project. Add the `admin` user as `member` and `admin` to your target project. See link:https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/14/html-single/users_and_identity_management_guide/#edit_a_project[Edit a Project] in the _Red Hat OpenStack Platform Users and Identity Management Guide_.
+
[options="" subs="+quotes,verbatim"]
----
ERROR: Command exited with non-zero return code 1, output: HttpException: 403: Client Error for url: https://_FQDN_:13696/v2.0/ports, {"NeutronError": {"message": "((rule:create_port and rule:create_port:mac_address) and rule:create_port:fixed_ips) is disallowed by policy", "type": "PolicyNotAuthorized", "detail": ""}}
----
