= Managing Providers
:imagesdir: images
:vernum: 4.5
:doctype: book
:toc: left
:toclevels: 3
:numbered!:
:experimental:

// Custom attributes
include::common/attributes/cfme.adoc[]

:cfme:

:numbered:

// Read slides, research and edit this description.

{product-title} can manage a variety of external environments, known as providers and managers. A provider or manager is any system that {product-title_short} integrates with for the purpose of collecting data and performing operations.

// A provider is a server with software to manage multiple virtual machines that reside on multiple hosts.
// from http://manageiq.org/docs/get-started/concepts - revise

In {product-title_short}, a _provider_ is an external virtualization, cloud, and containers environment that manages multiple virtual machines or instances residing on multiple hosts. One example is Red Hat Virtualization, a platform that manages multiple hosts and virtual machines.

In {product-title_short}, a _manager_ is an external management system that manages more than one type of main resource. One example of a manager is OpenStack, which manages infrastucture, cloud, network, and storage resources.

This guide covers working with providers, as well as with managers in {product-title_short}.

{product-title_short} supports several types of providers and managers, which include:

* Infrastructure providers
* Configuration management providers
* Automation management providers
* Cloud providers
* Networking management providers
* Middleware management providers
* Container providers
* Storage managers

For information on managing the resources contained by a provider or manager, see link:https://access.redhat.com/documentation/en-us/red_hat_cloudforms/4.2/html-single/managing_infrastructure_and_inventory/[Managing Infrastructure and Inventory].


:leveloffset: 1
include::topics/Infrastructure_Providers.adoc[]

:leveloffset: 1
include::topics/Configuration_Management_Providers.adoc[]

:leveloffset: 1
include::topics/Automation_Management_Providers.adoc[]

:leveloffset: 1
include::topics/Cloud_Providers.adoc[]

:leveloffset: 1
include::topics/Networking_Providers.adoc[]

:leveloffset: 1
include::topics/Middleware_Providers.adoc[]

:leveloffset: 1
include::topics/Containers_Providers.adoc[]

:leveloffset: 1
include::topics/Storage_Managers.adoc[]






