= Managing Providers
:imagesdir: images
:vernum: 4.6
:doctype: book
:toc: left
:toclevels: 3
:numbered!:
:experimental:

// Custom attributes
include::common/attributes/cfme.adoc[]

:cfme:

:numbered:


{product-title} can manage a variety of external environments, known as providers and managers. A provider or manager is any system that {product-title_short} integrates with for the purpose of collecting data and performing operations.

In {product-title_short}, a _provider_ is an external virtualization, cloud, or containers environment that manages multiple virtual machines or instances residing on multiple hosts. One example is Red Hat Virtualization, a platform that manages multiple hosts and virtual machines.

In {product-title_short}, a _manager_ is an external management environment that manages more than one type of resource. One example of a manager is OpenStack, which manages infrastucture, cloud, network, and storage resources.

This guide covers working with providers and managers in {product-title_short}, which include:

* Infrastructure providers
* Configuration management providers
* Automation management providers
* Cloud providers
* Networking management providers
* Middleware management providers
* Container providers
* Storage managers

For information on working with the resources contained by a provider or manager, see link:https://access.redhat.com/documentation/en-us/red_hat_cloudforms/4.6/html-single/managing_infrastructure_and_inventory/[Managing Infrastructure and Inventory].

[[cross-providers-insight]]
== Cross-Providers Insight

Cross-providers insight is a feature that connects all layers of infrastructure, cloud, and containers known to {product-title} and collects data for analysis.

It supports cross-linking all of the layers available in the following environments:

* OpenStack
* Red Hat Virtualization
* VMware vCenter
* Amazon EC2
* Google Cloud Engine

The collected information includes all the data available in other (infrastructure or cloud) providers.

[NOTE]
====
For Amazon EC2 (AWS) and Google Cloud Engine (GCE) support, OpenShift must be installed using the relevant cloud provider. For more information, see the https://access.redhat.com/documentation/en/openshift-container-platform/[OpenShift Container Platform Installation and Configuration Guide], ensuring you use the desired version of OpenShift.
====



:leveloffset: 1
include::topics/Infrastructure_Providers.adoc[]

:leveloffset: 1
include::topics/Configuration_Management_Providers.adoc[]

:leveloffset: 1
include::topics/Automation_Management_Providers.adoc[]

:leveloffset: 1
include::topics/Cloud_Providers.adoc[]

:leveloffset: 1
include::topics/Networking_Providers.adoc[]

:leveloffset: 1
include::topics/Containers_Providers.adoc[]

:leveloffset: 1
include::topics/Storage_Managers.adoc[]

[appendix]
[[appendix]]
:leveloffset: 1
= Appendix

include::common/app-self_signed_CA.adoc[]



