[[enhancements]]
== Enhancements

The following enhancements are available with Red Hat CloudForms 4.0
(CFME 5.5).

Entitlements::

Red Hat CloudForms now provides the capability of enabling
providers based on subscription/certificates, which allows its
shipping as a bundled product with other SKU’s such as OpenStack
with CloudForms and OpenShift with CloudForms. Having other streams
available for the delivery of Red Hat CloudForms increases adoption
and provides advanced management capabilities to the users.
+
Entitlements provides the following enhancements to Red Hat:
+
* Ability to enable or disable providers based upon a certificate.
* Active subscription with Red Hat Cloud Data Network for delivery to Red Hat CloudForms.
* Ability to remain in its own CloudForms channels.
* Ability to add providers even if no certificate is found.
* In the presence of a certificate, providers are limited as per SKU, the certificate is supporting.
* Ability to support the provider to SKU mapping.
* Providers remain fully functional even after adding or removing SKU associated with certificates.

Event Switchboard::

Red Hat CloudForms now has better visibility and normalization of
the event handling capabilities through the introduction of a new
feature, Event Switchboard. Event switchboard automates the
provider events and miq policy events by handling them via
automate. A new class EventStream is added to be the parent class
of all event classes. Whenever an event comes in, an EventStream
object is sent to automate that kicks off the event handling
process. An EmsEvent instance contains all information about its
VM, host and provider related to the event.
+
The Event Switchboard delivers the following capabilities:
+
* Move the current event definitions into the database.
* Map the events through to automation.

Multi Tenancy::

Multi tenancy in Red Hat CloudForms offers several enhancements, with an ability to:
+
* Support more than one organization with separate authentication and resource distribution. This includes the ability to have multi-level (nested) tenants.
* Set quotas in the new tenant.
* Support Role-based Access Control (RBAC), tagging, and approval system for tenants.

Red Hat Access Insights Plug-In::

With this release, users can now access Red Hat Access Insights
directly from the Red Hat CloudForms appliance web user interface.
Red Hat Access Insights is an automated service that provides
information that helps users to rapidly identify key issues in
their Red Hat CloudForms deployment.

Microsoft Azure Providers::

Red Hat CloudForms now provides a new provider to enable deep Microsoft Azure Integration, providing capabilities such as inventory and provisioning.
+
The Microsoft Azure Integration will deliver the following capabilities to Red Hat CloudForms:
+
* Inventory
* Component Inventory
* Capacity
* Relationships
* Utilization

Red Hat OpenShift v3 Providers::

The integration of Red Hat OpenShift v3 providers in Red Hat
CloudForms provides support in the following areas, with an ability to:
+
* View the topology of the OpenShift infrastructure.
* Link any OpenShift inventory object to its hosting infrastructure. Red Hat CloudForms can cross-link the OpenShift components to either their virtual or physical counterparts.
* Generate a graphical topology map launched from the relationship area of the user interface.
* See the capacity that the RHEL Atomic Platform nodes have to offer.
* See how OpenShift Enterprise components (CPU, Memory, Storage and Networking) are utilized.
* Deliver fleecing images.
* Have a dashboard showing details of your OpenShift Enterprise infrastructure.
* Receive events from OpenShift.

Pluggable Providers::

Red Hat CloudForms now provides the ability to vendors to write
their own providers for Red Hat CloudForms using community
available practices and documentation. Previously, Red Hat Insight
was used to identify key issues in the Red Hat CloudForms deployment by
supplying detailed information about security vulnerabilities as
well as tuning recommendations. In Red Hat CloudForms 4.0, there is
no sharing of data between Red Hat CloudForms and the Red Hat
Insights plugin. Red Hat Insights is used as a pluggable user interface module
to the Red Hat CloudForms user interface.
+
The Pluggable providers provide the following enhancement to Red
Hat CloudForms:
+
* Allows community to create providers for the product
* Simplifies the previous architecture that supported providers by namespacing of the provider code giving clear separation between providers.
* Enable the pluggability aspects of the framework project by separating the existing vendor providers into individual folders/namespaces.

Self Service Portal::

Users can better manage services and resources, using a user interface with
widgets, dashboard controls and feedback. This enhancement supports:
+
* Graphic images and HTML text description on the services.
* Presentation of dialogs when a service is ordered.
* Management of deployed services (My Services).
* Catalog categories, branding, and authentication.
+

Simplified Chinese language support::

Red Hat CloudForms now includes Simplified Chinese as one of the supported languages for the CFME appliance.

Red Hat Enterprise Linux 7.1 support::

Red Hat CloudForms is fully supported on Red Hat Enterprise Linux 7.1.
+
Red Hat recommends delaying upgrades of Red Hat CloudForms 4.0 appliances to
Red Hat Enterprise Linux 7.2 until the first Red Hat CloudForms 4.0 advisory
 is released noting Red Hat Enterprise Linux 7.2 support.


