[[introduction]]
== Introduction

Red Hat CloudForms Management Engine (CFME) delivers the insight,
control, and automation enterprises need to address the challenges of
managing virtual environments, which are far more complex than physical
ones. This technology enables enterprises with existing virtual
infrastructures to improve visibility and control, and those just
starting virtualization deployments to build and operate a well-managed
virtual infrastructure.

Red Hat CloudForms 4.0 is comprised of a single component, the CloudForms
Management Engine. It has the following feature sets:

* Insight: Discovery, Monitoring, Utilization, Performance, Reporting, Analytics, Chargeback, and Trending.
* Control: Security, Compliance, Alerting, Policy-Based Resource and Configuration Management.
* Automate: IT Process, Task and Event, Provisioning, Workload Management and Orchestration.
* Integrate: Systems Management, Tools and Processes, Event Consoles, CMDB, RBA, and Web Services.

If you experience difficulty with a procedure described in this
documentation, visit the Red Hat Customer Portal at
http://access.redhat.com. Through the customer portal, you can:

* Search or browse through a knowledgebase of technical support articles about Red Hat products
* Submit a support case to Red Hat Global Support Services (GSS)
* Access other product documentation

Red Hat also hosts a large number of electronic mailing lists for
discussion of Red Hat software and technology. You can find a list of
publicly available mailing lists at
https://www.redhat.com/mailman/listinfo. Click on the name of any mailing
list to subscribe to that list or to access the list archives.

+Documentation Feedback+
If you find a typographical error in this manual,
or if you have thought of a way to make this manual better, please submit
a report to GSS through the customer portal.

When submitting a report, be sure to mention the manual's identifier:
Release Notes

If you have a suggestion for improving the documentation, try to be as
specific as possible when describing it. If you have found an error,
please include the section number and some of the surrounding text so we
can find it easily.

