[id="Configuring_the_1_2_{context}_conversion_hosts"]
= Configuring the conversion hosts for VDDK or SSH transformation

Perform the following steps to configure your conversion hosts for VDDK or SSH transformation:

[cols="1,1", options="header"]
|===
^|VDDK ^|SSH
a|. Download the VDDK package. See xref:Downloading_vddk_for_{context}[].
. Configure the conversion hosts. See xref:Configuring_the_1_2_{context}_conversion_hosts_with_cloudforms[]

a|. Configure the conversion hosts. See xref:Configuring_the_1_2_{context}_conversion_hosts_with_cloudforms[]
. Copy the VMware SSH keys to the conversion hosts. See xref:Copying_vmware_keys_to_{context}_conversion_hosts[].
|===

include::ims_common/proc_Downloading_vddk.adoc[leveloffset=+1]

You can configure the conversion hosts with CloudForms.

include::modules/proc_Configuring_the_1_2_conversion_hosts_with_cloudforms.adoc[leveloffset=+1]

If you are using VDDK, you can migrate your virtual machines. (Optionally) You can verify the conversion hosts in a browser. See xref:Verifying_{context}_conversion_hosts_in_browser[].

If you are using SSH, copy the VMware keys to the conversion hosts. See xref:Copying_vmware_keys_to_{context}_conversion_hosts[].

include::ims_common/proc_Copying_the_vmware_keys_to_the_conversion_hosts.adoc[leveloffset=+1]

You are ready to migrate your virtual machines. (Optionally) You can verify the conversion hosts in a browser. See xref:Verifying_rhv_conversion_hosts_in_browser[].

include::ims_common/proc_Verifying_conversion_hosts_in_browser.adoc[leveloffset=+1]
