// For 1.2
[id='Infrastructure_migration_solution_overview']
= Infrastructure Migration Solution overview

Red Hat Infrastructure Migration Solution (IMS) 1.2 enables you to migrate virtual machines from VMware{nbsp}5.5 (and later) to the following target environments:

Red Hat Virtualization 4.3::
Red Hat Virtualization is a virtualization platform built on Red Hat Enterprise Linux. You can manage your virtual infrastructure, including hosts, virtual machines, networks, storage, and users, from a centralized graphical user interface or with a REST API. For more information, see the link:https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.3/[Red Hat Virtualization documentation].

Red Hat OpenStack Platform 13 and 14::
Red Hat OpenStack Platform enables you to create a scaleable, fault-tolerant, private or public cloud based on Red Hat Enterprise Linux. For more information, see the link:https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/14[Red Hat OpenStack Platform documentation].

Red Hat CloudForms 4.7.4::
The environment in which the migration is performed is Red Hat CloudForms, a user interface for managing the infrastructure. For more information, see the link:https://access.redhat.com/documentation/en-us/red_hat_cloudforms/4.7/[Red Hat CloudForms documentation].

[NOTE]
====
You can migrate a single virtual machine to Red Hat Container-native Virtualization (technical preview). See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.1/html/container-native_virtualization_users_guide/index#cnv-importing-vm-wizard-web[Importing a virtual machine] in the _Red Hat Container-native Virtualization User's Guide_.
====

The migration process has the following key steps:

. Planning the migration:
+
* Questions to ask before migration to estimate time and resource requirements, including the following:

** "How long will the migration take?"
** "How many conversion hosts do I need?"
** "Which datapath transformation option should I use, VDDK or SSH?"

* Recommendations to minimize the impact on your users

. Preparing the environment for migration:
+
* Preparing the VMware environment
* Preparing the Red Hat Virtualization or Red Hat OpenStack Platform environment
* Configuring the conversion hosts.  Conversion hosts are Red Hat Virtualization hosts or Red Hat OpenStack Platform instances running `virt-v2v` and `virt-v2v-wrapper`, which perform the migration.

. Migrating the virtual machines:
+
* Mapping the source and target environments
* Creating and running a migration plan
+
For a detailed description of the migration process, see the migration workflows:

** xref:Vmware_to_rhv_migration_workflow[]
** xref:Vmware_to_osp_migration_workflow[]

:context: rhv
:rhv:
include::ims_common/con_Migration_workflow.adoc[leveloffset=+1]
:rhv!:

:context: osp
:osp:
include::ims_common/con_Migration_workflow.adoc[leveloffset=+1]
:osp!:
