[id='Infrastructure_migration_solution_overview']
= Infrastructure Migration Solution overview

The Red Hat Infrastructure Migration Solution (IMS) enables you to migrate virtual machines from VMware{nbsp}5.5 (and later) to the following target environments:

* Red Hat Virtualization 4.3.4
+
Red Hat Virtualization is a virtualization platform built on Red Hat Enterprise Linux. You can manage your virtual infrastructure, including hosts, virtual machines, networks, storage, and users, from a centralized graphical user interface or with a REST API. For more information, see the link:https://access.redhat.com/documentation/en-us/red_hat_virtualization[Red Hat Virtualization documentation].

* Red Hat OpenStack Platform 13 and 14
+
Red Hat OpenStack Platform enables you to create a scaleable, fault-tolerant, private or public cloud based on Red Hat Enterprise Linux. For more information, see the link:https://access.redhat.com/documentation/en-us/red_hat_openstack_platform[Red Hat OpenStack Platform documentation].
+
[NOTE]
====
You can migrate a single virtual machine to Red Hat Container-native Virtualization (technical preview). See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.1/html/container-native_virtualization_users_guide/index#cnv-importing-vm-wizard-web[Importing a virtual machine] in the _Red Hat Container-native Virtualization User's Guide_.
====

The migration process is performed with CloudForms, a user interface for managing the infrastructure. For more information, see the link:https://access.redhat.com/documentation/en-us/red-hat-cloudforms[Red Hat CloudForms documentation].

The migration involves the following key steps:

. xref:Planning_the_migration[Planning the migration]
+
* xref:Questions_to_ask_before_migration[Questions to ask before migration]:
** xref:How_long_will_the_migration_take["How long will the migration take?"]
** xref:Deciding_how_many_conversion_hosts_to_create["How many conversion hosts do I need?"]
** xref:Choosing_vddk_or_ssh_transformation["Which datapath transformation option should I use, VDDK or SSH?"]

* xref:Recommendations_for_migration[Recommendations to minimize the impact on your users]

. xref:Preparing_the_environment_for_migration[Preparing for migration]:
+
* xref:Preparing_the_vmware_source_environment[Preparing the VMware virtual machines for migration]
* xref:Preparing_the_target_environment[Preparing the Red Hat Virtualization or Red Hat OpenStack Platform environment]

* xref:Configuring_the_conversion_hosts[Configuring the conversion hosts in CloudForms]. Conversion hosts are Red Hat Virtualization hosts or Red Hat OpenStack Platform instances running `virt-v2v` and `virt-v2v-wrapper`, which perform the migration.

. xref:Migrating_the_infrastructure[Migrating the virtual machines]
+
* xref:Creating_an_infrastructure_mapping[Mapping the source and target environments]
* xref:Creating_and_running_a_migration_plan[Creating and running a migration plan]. Optionally, you can automate tasks before and after migration with Ansible. See xref:Adding_ansible_playbooks_to_cloudforms[].
+
For a detailed description of the migration process, see the migration workflows:

** xref:Vmware_to_rhv_migration_workflow[]
** xref:Vmware_to_osp_migration_workflow[]

:context: rhv
:rhv:
include::ims_common/con_Migration_workflow.adoc[leveloffset=+1]
:rhv!:

:context: osp
:osp:
include::ims_common/con_Migration_workflow.adoc[leveloffset=+1]
:osp!:
