[[Introduction]]
== Introduction

=== Technology Preview

Technology preview features provide early access to upcoming product innovations, enabling you to test functionality and provide feedback during the development process. However, these features are not fully supported under Subscription Level Agreements, may not be functionally complete, and are not intended for production use. As it is considered making future iterations of technology preview features generally available, we will attempt to resolve any issues that customers experience when using these features.

During the development of a technology preview feature, additional components may become available to the public for testing. Because technology preview features are still under development, the stability of such features cannot be guaranteed. As a result, if you are using technology preview features, you may not be able to seamlessly upgrade to subsequent releases of that feature. While it is intended to fully support technology preview features in future releases, we may discover that a feature does not meet the standards for enterprise viability. If this happens, we cannot guarantee that technology preview features will be released in a supported manner.

Some technology preview features may only be available for specific hardware architectures.

=== Terminology

The following terms are used throughout this document.

*Filer*

A `filer` is a set of hardware, software, and disks specifically designed to provide fast and reliable storage. The *Filer* page shows all of the systems detected by the connected storage managers. Click on a *Filer* from the list to see a summary view of its properties, relationships, and tags.

*LUN*

A storage volume is a set of disks connected to a storage system. The *LUNs* page shows all of the storage volumes detected by the connected SMI-S agents. Click on a storage volume in the list view to see a summary view of its properties, relationships, and tags.

*File Share*

A file share is an accessible directory location on a disk. The *File Share* page shows all of the volumes detected by the connected SMI-S agents. Click on a *File Share* in the list view to see a summary view of its properties, relationships, and tags.

*Volume*

A volume is an area of usable storage capacity on one or more physical disks. The *Volumes* page shows all of the volumes detected by the connected `Storage Manager`. Click on a *Volume* in the list view to see a summary view of its properties, relationships, and tags.

Click on the above items in the list view to see a summary view of the properties, relationships and tags.

* *Properties* includes the vendor details, operational status, and health status as reported by the agent. Possible operational statuses are *Starting*, *Stopping*, *Stopped*, *In Service*, *No Contact*, and *OK*. *Health status* describes the health of the storage system itself, but not necessarily that of the components of the system.
* *Relationships* shows the *Filers*, *LUNs*, *File Shares*, *Local File Systems*, and *Volumes* associated with the storage system. You can click on the items to directly view each of these relationships.
* *Infrastructure Relationships* contains clickable links to the parts of your virtual infrastructure associated with the storage system.
* *Smart Management* shows the tags that have been assigned using the {product-title} Server.


=== Requirements

To connect a {product-title} server to the inventory storage manager, you need to:

* Install the NetApp SDK
* Enable Storage features and the Storage Inventory Server Role
* Connect the server to the Storage Manager

To connect the server to the Storage Manager, you need the host name, IP address, port, and credentials for the agent. You must have an account role with the proper access to modify server roles. In addition, since this is a technology preview feature it is not automatically viewable in the {product-title} Console. To see it, edit the main configuration file.
