[[_chap_specification]]
== Specification

[[_sect_http_basics]]
=== HTTP Basics

include::REST_API_Entry_Point.adoc[]

include::Supported_Content_Types.adoc[]

include::URL_Paths.adoc[]

include::Methods_and_related_URLs.adoc[]

include::Updating_Resources.adoc[]

include::Modifying_Resource_Attributes.adoc[]

include::Return_Codes.adoc[]

include::CRUD_Examples.adoc[]

[[_sect_authentication]]
=== Authentication

There are two methods of authentication for the {product-title} REST API: 

* *Basic Authentication*: The user and password credentials are passed in with each HTTP request. 
* *Token based Authentication*: The client requests a token for the username/password credentials specified.
  Then the token is used in lieu of the username/password for each subsequent API call. 

include::Using_Basic_Authentication.adoc[]

include::Using_Authentication_Tokens.adoc[]

[[_sect_json_specification]]
=== JSON Specification

The API uses JSON throughout; the Content-Type for all requests and responses is `application/json`. 

As is general practice with REST, clients should not make assumptions about the server's URL space.
Clients are expected to discover all URL's by navigating the API.
To keep this document readable, we still mention specific URL's, generally in the form of an absolute path.
Clients should not use these, or assume that the actual URL structure follows these examples, and instead use discovered URL's.
Any client should start its discovery with the API entry point, here denoted with `/api`. 

include::Basic_types.adoc[]

include::Common_Attributes_and_Actions.adoc[]

include::Collections4.adoc[]

include::Actions4.adoc[]

include::Forms1.adoc[]

[[_sect_query_specification]]
=== Query Specification

This specification identifies the controls available when querying collections. 

include::Control_Attributes.adoc[]

include::Filtering.adoc[]

include::Expanding_Collections1.adoc[]


