[[enhancements]]
== Enhancements

The following enhancements are available with {product-title}
({product-title} 5.6).

Ansible Tower Providers::

Draft text.

Google Compute Engine Providers::

Draft text.

Software-Defined Networking Providers::

{product-title} has introduced a new provider type called *Networking*. This new provider type will expose software-defined networking (SDN) providers starting with OpenStack Neutron. The plan is to conform to the template of what makes a provider as follows:

* Inventory
* Events
* Metrics
* Operations
* Provisioning
* SmartState Analysis

This release focuses on defining a model that can be consumed by other SDN providers due in future releases, as well as a level of inventory with cross linking.

Azure Provider Enhancements::

With this release, {product-title} enhances the capabilities for the Microsoft Azure Cloud. This release will deliver the following capabilities to complete the Azure provider feature set.

* Provision from Private Image 
* Provision from SnapShot Image
* Retirement (depends on API)
* SmartState Analysis
* Events
 
Self Service Enhancements::

Draft text.

VMware Provider Enhancements::

Draft text.


