[[external_auth]]
= Configuring Federated Identity Management (External Authentication) with {product-title_short}

//Overview of federated auth in CloudForms here - benefits

You can configure {product-title_short} to use federation authentication with system authentication methods such as Red Hat Identity Management (IdM), Red Hat Single Sign-On (SSO), or Active Directory (AD). 

[[external_ipa_auth]]
== Configuring Federated Authentication with IdM 

You can configure {product-title_short} to use Red Hat Identity Management (IdM) for federated authentication using the *External Authentication (httpd)* option in {product-title_short}.

When external authentication is enabled, users can log in to the {product-title_short} appliance using their IdM server credentials. The appliance creates user accounts automatically and imports relevant information from the IdM server.

The appliance contains IdM client software for connecting to IdM servers, but it is not configured by default. External authentication is enabled by first configuring it in the web interface, then in the console.
Disabling external authentication and returning to internal database authentication also requires steps in both the web interface and the console.

=== External Authentication Requirements

* For an appliance to leverage an IdM server on the network, both the appliance and the IdM server must have their clocks synchronized or Kerberos and LDAP authentication fail.
* The IdM server must be known by DNS and accessible by name. If DNS is not configured accordingly, the hosts files need to be updated to reflect both IdM server and the appliance on both virtual machines.
* For users to log in to the appliance using IdM server credentials, they must be members of at least one group on the IdM server which is also defined in the appliance. Navigate to the settings menu, then menu:Configuration[Access Control > Groups] to administer groups.

=== Configuring the Appliance for External Authentication

To configure the appliance for external authentication, first set up authentication using the web interface, then using the appliance console.

Using the web interface:

. Log in to the web interface as an administrative user.
. Navigate to the settings menu, then menu:Configuration[Settings > Zone > Server > NTP Servers] or use the hosting provider of the virtual machine to synchronize the appliance's time with an NTP server.
. From the settings menu, select *Configuration*. 
. Select your server in the *Settings* accordion.
. Select the *Authentication* tab.
. Select a *Session Timeout* if required.
. Select *External (httpd)* in the *Mode list*.
. Select *Enable Single Sign-On* to allow single sign-on using Kerberos tickets from client machines that authenticate to the same IdM server as the appliance.
. In the *Role Settings* area, select *Get User Groups* from *External Authentication (https)*.
. Click *Save*.

Using the console:

. Log in to the appliance console using the user name `admin`.
. The summary screen displays:
+
------
External Auth:  not configured
------
+
. Press Enter.
. Select *Configure External Authentication (httpd)*.
. Enter the fully qualified hostname of the IdM server, for example _idmserver.test.company.com_.
. Enter the IdM server domain, for example _test.company.com_.
. Enter the IdM server realm, for example _TEST.COMPANY.COM_.
. Enter the IdM server principal, for example _admin_.
. Enter the password of the IdM server principal.
. Enter `y` to proceed.

[NOTE]
====
If any of the following conditions are true, configuration fails:

* The IdM server is not reachable by its FQDN
* The IdM server cannot reach the appliance by its FQDN
* The time is not synchronized between the appliance and the IdM server
* The IdM server admin password is entered incorrectly
====

.Configuring External Authentication
====
----
$ ssh root@appliance.test.company.com
[appliance]# /bin/appliance_console_cli --host appliance.test.company.com \
                                      --ipaserver idmserver.test.company.com \
                                      --iparealm TEST.COMPANY.COM \
                                      --ipaprincipal admin \
                                      --ipapassword smartvm1
----
====


=== Reverting to Internal Database Authentication

To revert to internal database authentication, first configure authentication using the web interface, then using the console.

Using the web interface:

. From the settings menu, select *Configuration*. 
. Select your server in the *Settings* accordion.
. Select the *Authentication* tab.
. Select *Database* in the *Mode* list.
. Click *Save*.

Using the console:

. Log in to the appliance console using the user name `admin`.
. The summary screen displays:
+
----
External Auth:  Id.server.FQDN
----
+
. Press `Enter`.
. Select *Configure External Authentication (httpd)*. The currently configured IdM server hostname and domain are displayed.
. Enter `y` to remove configuration details for the IdM client.


.Reverting to Internal Database Authentication
====
----
$ ssh root@appliance.test.company.com
[appliance]# /bin/appliance_console_cli --uninstall-ipa
----
====

=== Optional Configuration Using the Appliance Console CLI

In addition to using the appliance console, external authentication can optionally be configured and reverted using the appliance console command line interface.

Appliance console CLI command and relevant options include:

----
/bin/appliance_console_cli --host <appliance_fqdn>
                           --ipaserver <idm_server_fqdn>
                           --iparealm <realm_of_idm_server>
                           --ipaprincipal <idm_server_principal>
                           --ipapassword <idm_server_password>
                           --uninstall-ipa
----


--host::
Updates the hostname of the appliance. If you performed this step using the console and made the necessary updates made to `/etc/hosts` if DNS is not properly configured, you can omit the `--host` option.

--iparealm::
If omitted, the `iparealm` is based on the domain name of the `ipaserver`.

--ipaprincipal::
If omitted, defaults to admin.









