pressgang_website_callback([
	{"topicId":15110,"target":"Virtual_Machines1","title":"Virtual Machines","newSince":""},
	{"topicId":14854,"target":"sect-Controlling_Virtual_Machines","title":"Controlling Virtual Machines","newSince":""},
	{"topicId":15367,"target":"Viewing_Capacity_and_Utilization_Charts_for_a_Datastore","title":"Viewing Capacity and Utilization Charts for a Datastore","newSince":""},
	{"topicId":14856,"target":"To_control_the_power_state_of_one_Virtual_Machine","title":"Controlling the Power State of Virtual Machines","newSince":""},
	{"topicId":15499,"target":"chap-Virtual_Machines","title":"Provisioning","newSince":""},
	{"topicId":15250,"target":"Clusters2","title":"Clusters","newSince":""},
	{"topicId":15783,"target":"To_modify_a_report_schedule","title":"Modifying a Report Schedule","newSince":""},
	{"topicId":15271,"target":"Viewing_Capacity_and_Utilization_Charts_for_a_Cluster","title":"Viewing Capacity and Utilization Charts for a Cluster","newSince":""},
	{"topicId":15528,"target":"To_provision_from_a_template_using_the_provided_dialogs1","title":"Provisioning a Virtual Machine from a Template","newSince":""},
	{"topicId":43177,"target":"Opening_a_Console_for_a_Virtual_Machine","title":"Opening a Console for a Virtual Machine","newSince":""},
	{"topicId":15402,"target":"chap-Capacity_and_Utilization_Charts","title":"Data Collected","newSince":""},
	{"topicId":15403,"target":"Capacity_and_Utilization_Charts_for_Host_Clusters_and_Virtual_Machines","title":"Capacity and Utilization Charts for Host, Clusters, and Virtual Machines","newSince":""},
	{"topicId":15404,"target":"Capacity_and_Utilization_Charts_for_Datastores","title":"Capacity and Utilization Charts for Datastores","newSince":""},
	{"topicId":43182,"target":"Configuring_the_Browser_Plug-in_for_a_Virtual_Machine_Console","title":"Configuring the Browser Plug-in for a Virtual Machine Console","newSince":""},
	{"topicId":43183,"target":"Configuring_the_Certificate_for_a_Virtual_Machine_Console","title":"Configuring the Certificate for a Virtual Machine Console","newSince":""},
	{"topicId":15536,"target":"Customizing_Provisioning_Dialogs1","title":"Customizing Provisioning Dialogs","newSince":""},
	{"topicId":43184,"target":"sect-Accessing_the_Console_for_a_Virtual_Machine","title":"Overview of Virtual Machine Consoles","newSince":""},
	{"topicId":44336,"target":"Enabling_Capacity_and_Utilization_Data_Collection_for_a_Cluster","title":"Enabling Capacity and Utilization Data Collection for a Cluster","newSince":""},
	{"topicId":44337,"target":"Enabling_Capacity_and_Utilization_Data_Collection_for_a_Datastore","title":"Enabling Capacity and Utilization Data Collection for a Datastore","newSince":""},
	{"topicId":15538,"target":"To_add_a_provision_dialog_file_for_all_users1","title":"Adding a Provision Dialog for All Users","newSince":""},
	{"topicId":44338,"target":"Enabling_Capacity_and_Utilization_Data_Collection_for_a_Host","title":"Enabling Capacity and Utilization Data Collection for a Host","newSince":""},
	{"topicId":15283,"target":"Hosts1","title":"Hosts","newSince":""},
	{"topicId":44339,"target":"Enabling_Capacity_and_Utilization_Data_Collection_for_a_Virtual_Machine","title":"Enabling Capacity and Utilization Data Collection for a Virtual Machine","newSince":""},
	{"topicId":15412,"target":"sect-Chart_Features","title":"Chart Features","newSince":""},
	{"topicId":15413,"target":"To_zoom_into_a_chart","title":"Zooming into a Chart","newSince":""},
	{"topicId":15414,"target":"To_drill_into_chart_data","title":"Drilling into Chart Data","newSince":""},
	{"topicId":42938,"target":"Author_Group","title":"Author Group","newSince":""},
	{"topicId":15168,"target":"To_view_capacity_and_utilization_charts_for_a_Virtual_Machine","title":"Viewing Capacity and Utilization Charts for a Virtual Machine","newSince":""},
	{"topicId":42948,"target":"appe-Revision_History","title":"Revision History","newSince":""},
	{"topicId":20178,"target":"Navigating_the_Console","title":"Navigating the Console","newSince":""},
	{"topicId":15444,"target":"chap-Reports","title":"Reports","newSince":""},
	{"topicId":15445,"target":"sect-Running_Reports","title":"Running Reports","newSince":""},
	{"topicId":15446,"target":"To_generate_a_single_report","title":"Generating a Single Report","newSince":""},
	{"topicId":15447,"target":"To_schedule_a_Report","title":"Scheduling a Report","newSince":""},
	{"topicId":15449,"target":"To_run_a_scheduled_report_immediately","title":"Running a Scheduled Report Immediately","newSince":""},
	{"topicId":15450,"target":"sect-Viewing_Reports","title":"Viewing Reports","newSince":""},
	{"topicId":15323,"target":"Viewing_Capacity_and_Utilization_Charts_for_a_Host","title":"Viewing Capacity and Utilization Charts for a Host","newSince":""},
	{"topicId":15453,"target":"Changing_Report_Views","title":"Changing Report Views","newSince":""},
	{"topicId":15455,"target":"Report_Download_Buttons","title":"Report Download Buttons","newSince":""},
	{"topicId":15456,"target":"Downloading_a_Report","title":"Downloading a Report","newSince":""},
	{"topicId":15458,"target":"Showing_a_Report_in_Full_Screen","title":"Showing a Report in Full Screen","newSince":""},
	{"topicId":21613,"target":"Instances","title":"Instances","newSince":""},
	{"topicId":15215,"target":"Management_Systems1","title":"Providers","newSince":""},
	{"topicId":44402,"target":"sect-Configuring_VMware_ESXi_Hosts_to_Enable_Console_Access","title":"Configuring VMware ESXi Hosts to Enable Console Access","newSince":""},
	{"topicId":30322,"target":"Abstract","title":"Abstract","newSince":""},
	{"topicId":44403,"target":"Using_SSH_to_Configure_VMware_ESXi_Hosts_to_Enable_Console_Access","title":"Using SSH to Configure VMware ESXi Hosts to Enable Console Access","newSince":""},
	{"topicId":44404,"target":"Using_the_VMware_vCenter_Web_Interface_to_Configure_ESXi_Hosts_to_Enable_Console_Access","title":"Using the VMware vCenter Web Interface to Configure ESXi Hosts to Enable Console Access","newSince":""},
	{"topicId":15349,"target":"Datastores1","title":"Datastores","newSince":""},
	{"topicId":15478,"target":"sect-Chargeback","title":"Chargeback","newSince":""},
	{"topicId":15479,"target":"Chargeback_Rates","title":"Chargeback Rates","newSince":""},
	{"topicId":15480,"target":"To_create_chargeback_rates","title":"Creating Chargeback Rates","newSince":""},
	{"topicId":15481,"target":"To_assign_chargeback_rates","title":"Assigning Chargeback Rates","newSince":""},
	{"topicId":15482,"target":"To_create_a_chargeback_report","title":"Creating a Chargeback Report","newSince":""},
	{"topicId":15099,"target":"chap-Navigating_the_CloudForms_Management_Engine_Console","title":"Navigating the CloudForms Management Engine Console","newSince":""},
	{"topicId":15100,"target":"To_access_the_Console1","title":"Accessing the Console","newSince":""},
	{"topicId":15484,"target":"To_access_and_use_a_Timeline","title":"Accessing and Using a Timeline","newSince":""},
	{"topicId":15485,"target":"To_download_a_Timelines_data","title":"Downloading a Timeline's Data","newSince":""}], 23044, "Red Hat CloudForms", "User Guide", "3.2");