pressgang_website_callback([
	{"topicId":15616,"target":"To_simulate_an_Automate_Model1","title":"Simulating an Automate Model","newSince":""},
	{"topicId":15617,"target":"Importing_Exporting_and_Resetting_the_Datastore1","title":"Importing, Exporting, and Resetting the Datastore","newSince":""},
	{"topicId":15618,"target":"To_export_all_Classes_classes1","title":"Exporting All Datastore Classes","newSince":""},
	{"topicId":15619,"target":"To_import_Datastore_classes1","title":"Importing Datastore Classes","newSince":""},
	{"topicId":15620,"target":"To_reset_the_Datastore_to_the_default1","title":"Resetting Datastore to Default","newSince":""},
	{"topicId":30213,"target":"Abstract","title":"Abstract","newSince":""},
	{"topicId":15622,"target":"Automate_Examples1","title":"Automate Examples","newSince":""},
	{"topicId":15623,"target":"Invoking_Automate_using_a_Custom_Button1","title":"Invoking Automate using a Custom Button","newSince":""},
	{"topicId":15624,"target":"To_create_a_custom_button_group1","title":"Creating a Custom Button Group","newSince":""},
	{"topicId":15625,"target":"To_create_a_custom_button1","title":"Creating a Custom Button","newSince":""},
	{"topicId":41994,"target":"Creating_a_Domain","title":"Creating a Domain","newSince":""},
	{"topicId":15626,"target":"To_edit_a_custom_button1","title":"Editing a Custom Button","newSince":""},
	{"topicId":41995,"target":"Creating_a_Namespace","title":"Creating a Namespace","newSince":""},
	{"topicId":15627,"target":"To_delete_a_custom_button1","title":"Deleting a Custom Button","newSince":""},
	{"topicId":15628,"target":"To_use_a_custom_button1","title":"Using a Custom Button","newSince":""},
	{"topicId":15629,"target":"Initiating_Automate_from_an_Event1","title":"Initiating Automate from an Event","newSince":""},
	{"topicId":15630,"target":"To_create_a_Policy_for_Automate1","title":"Creating a Policy for Automate","newSince":""},
	{"topicId":15631,"target":"To_create_a_custom_Automate_Action1","title":"Creating a Custom Automate Action","newSince":""},
	{"topicId":42001,"target":"Copying_a_Class_or_Instance","title":"Copying a Class or Instance","newSince":""},
	{"topicId":15633,"target":"Virtual_Machine_Properties1","title":"Virtual Machine Properties","newSince":""},
	{"topicId":15634,"target":"CloudForms_Management_Engine_Methods_for_use_in_Ruby_Scripts1","title":"CloudForms Management Engine Methods for use in Ruby Scripts","newSince":""},
	{"topicId":15636,"target":"Host_Properties2","title":"Host Properties","newSince":""},
	{"topicId":15637,"target":"Management_System_Properties1","title":"Provider Properties","newSince":""},
	{"topicId":15638,"target":"Storage_Properties1","title":"Storage Properties","newSince":""},
	{"topicId":15645,"target":"Phase_1_Create_Provision_Request1","title":"Phase 1: Create Provision Request","newSince":""},
	{"topicId":15646,"target":"Phase_2_Request_Approval","title":"Phase 2: Request Approval","newSince":""},
	{"topicId":15647,"target":"Phase_3_Quota_Validation2","title":"Phase 3: Quota Validation","newSince":""},
	{"topicId":15648,"target":"Phase_4_Provisioning1","title":"Phase 4: Provisioning","newSince":""},
	{"topicId":15649,"target":"Phase_5_Retirement1","title":"Phase 5: Retirement","newSince":""},
	{"topicId":15660,"target":"Ruby_method","title":"Ruby method","newSince":""},
	{"topicId":41556,"target":"Creating_a_Dynamic_Content_Dialog","title":"Creating a Dynamic Content Dialog","newSince":""},
	{"topicId":15498,"target":"chap-CloudForms_Management_Engine_Lifecycle","title":"CloudForms Management Engine Lifecycle","newSince":""},
	{"topicId":15499,"target":"About_Provisioning1","title":"Provisioning","newSince":""},
	{"topicId":22667,"target":"Setting_Provisioning_Notification_Email_Addresses","title":"Setting Provisioning Notification Email Addresses","newSince":""},
	{"topicId":15500,"target":"About_Automation1","title":"Automation","newSince":""},
	{"topicId":15504,"target":"chap-Provisioning_Requests","title":"Provisioning Requests","newSince":""},
	{"topicId":15505,"target":"Requirements_for_Provisioning_Virtual_Machines_from_VMware_Management_Systems1","title":"Requirements for Provisioning Virtual Machines from VMware Providers","newSince":""},
	{"topicId":15506,"target":"Requirements_for_Provisioning_Virtual_Machines_from_Red_Hat_Enterprise_Virtualization_Managers1","title":"Requirements for Provisioning Virtual Machines from Red Hat Enterprise Virtualization Manager","newSince":""},
	{"topicId":15507,"target":"sect-PXE_Provisioning","title":"PXE Provisioning","newSince":""},
	{"topicId":15508,"target":"Connect_to_the_PXE_Server1","title":"Connecting to a PXE Server","newSince":""},
	{"topicId":15509,"target":"To_create_System_Image_Types2","title":"Creating System Image Types for PXE","newSince":""},
	{"topicId":15510,"target":"To_set_the_PXE_Image_Type_for_a_PXE_Image1","title":"Setting the PXE Image Type for a PXE Image","newSince":""},
	{"topicId":15511,"target":"About_ISO_Provisioning1","title":"ISO Provisioning","newSince":""},
	{"topicId":15512,"target":"To_add_the_ISO_Datastore1","title":"Adding an ISO Datastore","newSince":""},
	{"topicId":15513,"target":"To_refresh_the_ISO_Datastore1","title":"Refreshing an ISO Datastore","newSince":""},
	{"topicId":15514,"target":"To_create_System_Image_Types3","title":"Creating System Image Types for ISO","newSince":""},
	{"topicId":15515,"target":"To_set_the_Image_Type_for_an_ISO_Image1","title":"Setting the Image Type for an ISO Image","newSince":""},
	{"topicId":15516,"target":"sect-Customization_Templates_for_Virtual_Machine_and_Instance_Provisioning","title":"Customization Templates for Virtual Machine and Instance Provisioning","newSince":""},
	{"topicId":15517,"target":"Customization_Script_Additions_for_Virtual_Machine_Provisioning1","title":"Customization Script Additions for Virtual Machine and Instance Provisioning","newSince":""},
	{"topicId":15518,"target":"To_add_a_Customization_Template3","title":"Adding a Customization Template","newSince":""},
	{"topicId":15519,"target":"sect-Requirements_for_Provisioning_a_Host","title":"Requirements for Provisioning a Host","newSince":""},
	{"topicId":15520,"target":"Connect_to_the_IPMI_Host1","title":"IPMI Hosts","newSince":""},
	{"topicId":15521,"target":"Discover_the_Management_Interface_for_the_IPMI_Host","title":"Discovering the Management Interface for an IPMI Host","newSince":""},
	{"topicId":15522,"target":"To_add_IPMI_credentials1","title":"Adding IPMI Credentials to a Discovered Host","newSince":""},
	{"topicId":15523,"target":"Add_the_Management_Interface_for_the_IPMI_Host1","title":"Adding the Management Interface for an IPMI Host","newSince":""},
	{"topicId":15524,"target":"sect-Customization_Templates_for_Host_Provisioning","title":"Customization Templates for Host Provisioning","newSince":""},
	{"topicId":15525,"target":"Customization_Script_Additions1","title":"Customization Script Additions","newSince":""},
	{"topicId":15526,"target":"To_add_a_Customization_Template2","title":"Adding a Customization Template","newSince":""},
	{"topicId":15527,"target":"sect-Provisioning_Virtual_Machines","title":"Provisioning Virtual Machines","newSince":""},
	{"topicId":15528,"target":"To_provision_from_a_template_using_the_provided_dialogs1","title":"Provisioning a Virtual Machine from a Template","newSince":""},
	{"topicId":15532,"target":"To_clone_a_Virtual_Machine_VMware_Virtual_Machines_only1","title":"Cloning a Virtual Machine (VMware Virtual Machines Only)","newSince":""},
	{"topicId":15533,"target":"To_publish_a_Virtual_Machine_to_a_template_VMware_Virtual_Machines_only1","title":"Publishing a Virtual Machine to a Template (VMware Virtual Machines Only)","newSince":""},
	{"topicId":15534,"target":"Provisioning_a_Host1","title":"Provisioning a Host","newSince":""},
	{"topicId":15536,"target":"sect-Customizing_Provisioning_Dialogs","title":"Customizing Provisioning Dialogs","newSince":""},
	{"topicId":15538,"target":"To_add_a_provision_dialog_file_for_all_users1","title":"Adding a Provision Dialog for All Users","newSince":""},
	{"topicId":15539,"target":"To_create_a_custom_miq_provision_dialogs.rb_file1","title":"Creating a Custom Provision Dialog","newSince":""},
	{"topicId":15540,"target":"sect-Provisioning_Profiles","title":"Provisioning Profiles","newSince":""},
	{"topicId":15541,"target":"To_create_a_provisioning_profile_instance1","title":"Creating a Provisioning Profile Instance","newSince":""},
	{"topicId":15544,"target":"Provisioning_Request_Approval_Methods1","title":"Provisioning Request Approval Methods","newSince":""},
	{"topicId":15545,"target":"Working_with_Provisioning_Requests1","title":"Working with Provisioning Requests","newSince":""},
	{"topicId":15546,"target":"To_reload_the_status_of_provisioning_requests1","title":"Reloading the Status of Provisioning Requests","newSince":""},
	{"topicId":42938,"target":"Author_Group","title":"Author Group","newSince":""},
	{"topicId":15547,"target":"To_approve_a_provisioning_request1","title":"Approving a Provisioning Request","newSince":""},
	{"topicId":15548,"target":"To_deny_a_provisioning_request1","title":"Denying a Provisioning Request","newSince":""},
	{"topicId":15549,"target":"To_copy_a_provisioning_request1","title":"Copying a Provisioning Request","newSince":""},
	{"topicId":15550,"target":"To_edit_a_provisioning_request1","title":"Editing a Provisioning Request","newSince":""},
	{"topicId":15551,"target":"To_delete_a_provisioning_request1","title":"Deleting a Provisioning Request","newSince":""},
	{"topicId":15552,"target":"Automatically_Approving_Requests1","title":"Automatically Approving Requests","newSince":""},
	{"topicId":42945,"target":"appe-Revision_History","title":"Revision History","newSince":""},
	{"topicId":15554,"target":"To_enable_global_defaults_for_Automatic_Approval1","title":"Enabling Global Defaults for Automatic Approval","newSince":""},
	{"topicId":15555,"target":"Template_Specific_Approval_Defaults1","title":"Template Specific Approval Defaults","newSince":""},
	{"topicId":15556,"target":"To_assign_tags_to_a_template_for_auto_approval1","title":"Assigning Tags to a Template for Auto Approval","newSince":""},
	{"topicId":15558,"target":"Fulfilling_a_Request1","title":"Fulfilling a Request","newSince":""},
	{"topicId":15559,"target":"Default_Execution_Steps_in_States_Instance1","title":"Default Execution Steps in States Instance","newSince":""},
	{"topicId":21703,"target":"Editing_Schema_Sequence","title":"Editing Schema Sequence","newSince":""},
	{"topicId":15560,"target":"Quotas2","title":"Quotas","newSince":""},
	{"topicId":15561,"target":"To_edit_the_default_quota1","title":"Editing the Default Quota","newSince":""},
	{"topicId":15562,"target":"Using_Tags_for_Owner_and_Group_Quotas1","title":"Using Tags for Owner and Group Quotas","newSince":""},
	{"topicId":15563,"target":"To_apply_a_tag_to_a_User_or_User_Group1","title":"Applying a Tag to a User or User Group","newSince":""},
	{"topicId":15564,"target":"State_Machines1","title":"State Machines","newSince":""},
	{"topicId":15565,"target":"Customizing_Provisioning_States1","title":"Customizing Provisioning States","newSince":""},
	{"topicId":15566,"target":"To_edit_the_Default_States_Instance","title":"Editing the Default State Instance","newSince":""},
	{"topicId":15567,"target":"Viewing_the_Status_of_a_Provisioning_Request1","title":"Viewing the Status of a Provisioning Request","newSince":""},
	{"topicId":15569,"target":"Viewing_a_Provisioned_Virtual_Machine1","title":"Viewing a Provisioned Virtual Machine or Instance","newSince":""},
	{"topicId":15570,"target":"To_view_the_Virtual_Machine_Summary1","title":"Viewing a Virtual Machine or Instance Summary","newSince":""},
	{"topicId":15572,"target":"About_Catalogs_and_Services1","title":"About Catalogs and Services","newSince":""},
	{"topicId":41941,"target":"Setting_Provisioning_Scope_Tags","title":"Setting Provisioning Scope Tags","newSince":""},
	{"topicId":15573,"target":"Terminology5","title":"Terminology","newSince":""},
	{"topicId":15574,"target":"Catalogs1","title":"Catalogs","newSince":""},
	{"topicId":15575,"target":"To_create_a_catalog_item1","title":"Creating a Catalog Item","newSince":""},
	{"topicId":15576,"target":"Service_Dialogs1","title":"Service Dialogs","newSince":""},
	{"topicId":15577,"target":"To_add_a_Service_Dialog1","title":"Adding a Service Dialog","newSince":""},
	{"topicId":41947,"target":"Importing_Service_Dialogs","title":"Importing Service Dialogs","newSince":""},
	{"topicId":41948,"target":"Exporting_Service_Dialogs","title":"Exporting Service Dialogs","newSince":""},
	{"topicId":15585,"target":"Creating_a_Method_to_Associate_with_the_Dialog1","title":"Creating a Method to Associate with the Dialog","newSince":""},
	{"topicId":15586,"target":"To_create_a_method_in_the_FactoryService_Class2","title":"Creating a Method in the Service Class","newSince":""},
	{"topicId":15587,"target":"To_create_a_method_in_the_FactoryService_Class3","title":"Creating an Instance in the Service Class","newSince":""},
	{"topicId":15588,"target":"To_Associate_the_Method_with_an_Automate_Instance1","title":"Associating a Method with an Automate Instance","newSince":""},
	{"topicId":15589,"target":"To_create_a_catalog_bundle1","title":"Creating a Catalog Bundle","newSince":""},
	{"topicId":15590,"target":"To_provision_a_Service1","title":"Provisioning a Service","newSince":""},
	{"topicId":15592,"target":"Retiring_Virtual_Machines1","title":"Retiring Virtual Machines and Instances","newSince":""},
	{"topicId":15593,"target":"Using_the_CloudForms_Management_Engine_Console_to_Retire1","title":"Using the CloudForms Management Engine Console to Retire","newSince":""},
	{"topicId":41962,"target":"Provisioning_an_OpenStack_Instance_from_an_Image","title":"Provisioning an OpenStack Instance from an Image","newSince":""},
	{"topicId":15594,"target":"To_immediately_retire_a_Virtual_Machine2","title":"Retiring a Virtual Machine Immediately","newSince":""},
	{"topicId":15595,"target":"To_set_a_retirement_date_for_a_Virtual_Machine2","title":"Setting a Retirement Date for a Virtual Machine or Instance","newSince":""},
	{"topicId":15596,"target":"To_remove_a_retirement_date_for_a_Virtual_Machine2","title":"Removing a Retirement Date for a Virtual Machine or Instance","newSince":""},
	{"topicId":15597,"target":"Setting_Retirement_in_a_Provision_Request1","title":"Setting Retirement in a Provision Request","newSince":""},
	{"topicId":15598,"target":"To_schedule_retirement_in_a_provision_request1","title":"Scheduling Retirement in a Provision Request","newSince":""},
	{"topicId":15599,"target":"sect-Extending_Retirement_Dates","title":"Extending Retirement Dates","newSince":""},
	{"topicId":15600,"target":"To_create_a_custom_button_to_extend_VM_Retirement1","title":"Creating a Custom Button to Extend Retirement","newSince":""},
	{"topicId":15601,"target":"To_change_the_number_of_days_to_extend_retirement1","title":"Changing the Number of Days to Extend Retirement","newSince":""},
	{"topicId":15603,"target":"chap-Automate_Model","title":"About Automate","newSince":""},
	{"topicId":15604,"target":"Automate_Model2","title":"Automate Model","newSince":""},
	{"topicId":15606,"target":"To_create_a_class1","title":"Creating a Class","newSince":""},
	{"topicId":15607,"target":"To_create_a_schema_for_a_class1","title":"Creating a Schema for a Class","newSince":""},
	{"topicId":15608,"target":"To_edit_a_field_in_a_schema1","title":"Editing a Field in a Schema","newSince":""},
	{"topicId":15609,"target":"To_add_an_instance_to_a_class1","title":"Adding an Instance to a Class","newSince":""},
	{"topicId":15610,"target":"sect-Relationships","title":"Relationship Syntax","newSince":""},
	{"topicId":21755,"target":"sect-Provisioning_Instances","title":"Provisioning Instances","newSince":""},
	{"topicId":15611,"target":"sect-Relationships","title":"Table: Relationship Examples","newSince":""},
	{"topicId":21756,"target":"Provisioning_an_Instance_from_an_Image","title":"Provisioning an EC2 Instance from an Image","newSince":""},
	{"topicId":44540,"target":"Editing_a_Domain","title":"Editing a Domain","newSince":""},
	{"topicId":15612,"target":"sect-Methods1","title":"Methods","newSince":""},
	{"topicId":44541,"target":"Deleting_a_Domain","title":"Deleting a Domain","newSince":""},
	{"topicId":44542,"target":"Changing_Priority_Order_of_Domains","title":"Changing Priority Order of Domains","newSince":""},
	{"topicId":15614,"target":"To_create_a_method1","title":"Creating a Method","newSince":""},
	{"topicId":15615,"target":"Simulation1","title":"Simulation","newSince":""}], 23041, "Red Hat CloudForms", "Lifecycle and Automation Guide", "3.2");