By default, the Telemetry service does not store events emitted by other services in a Red Hat OpenStack Platform environment. The following procedure outlines how to enable the Telemetry service on your OpenStack cloud provider to store such events. This ensures that events are exposed to {product-title} when a Red Hat OpenStack Platform environment is added as a cloud provider.

// . On the director node, edit _undercloud.conf_, and set _store_events_ to _true_.
. Log in to the undercloud host.
. Create an environment file called _ceilometer.yaml_, and add the following contents:
+
------
parameter_defaults:
  CeilometerStoreEvents: true
------
+
. Add the environment file to the _overcloud deploy_ command:
+
------
# openstack overcloud deploy --templates -e ~/ceilometer.yaml
------

If your OpenStack cloud provider was not deployed through the undercloud, you can also set this manually. To do so:

. Log in to your Controller node.
. Edit _/etc/ceilometer/ceilometer.conf_, and specify the following option:
+
------
store_events = True
------
+
. Edit _/etc/heat/heat.conf_, and specify the following options:
+
------
notification_driver=glance.openstack.common.notifier.rpc_notifier
notification_topics=notifications
------
+
. Edit _/etc/nova/nova.conf_, and specify the following options:
+
------
notification_driver=messaging
notification_topics=notifications
------
+
. Restart the Compute service and Orchestration services:
+
------
# systemctl restart openstack-heat-api.service \
  openstack-heat-api-cfn.service \
  openstack-heat-engine.service \
  openstack-heat-api-cloudwatch.service
# systemctl restart openstack-nova-compute.service
------
