
[[arbitration-rules]]
== Arbitration Rule

Management of Arbitration Rules is provided via the following collection:

[source,data]
----
/api/arbitration_rules
----

Full CRUD actions on arbitration_rules is available:

* link:#querying-arbitration-rules[Querying Arbitration Rules]
* link:#creating-arbitration-rules[Creating Arbitration Rules]
* link:#editing-arbitration-rules[Editing Arbitration Rules]
* link:#deleting-arbitration-rules[Deleting Arbitration Rules]

[[querying-arbitration-rules]]
=== Querying Arbitration Rules

Querying all arbitration rules in the system is simply:

----
GET /api/arbitration_rules
----

Getting details on a specific arbitration rule:

----
GET /api/arbitration_rules/:id
----

[[creating-arbitration-rules]]
=== Creating Arbitration Rules

Arbitration Rules can be created via a POST to the arbitration_rules collection or via the *create* action
signature which also allows creation of multiple arbitration_rules in a single request.

----
POST /api/arbitration_rules
----

[source,json]
----
{
  "description" : "admin rule",
  "operation" : "inject",
  "arbitration_profile_id" : "5",
  "expression" : {
    "EQUAL" : {
      "field" : "User-userid",
      "value" : "admin"
    }
  "
}
----

or creating multiple arbitration rules:

[source,json]
----
{
  "action" : "create",
  "resources" : [
    { "description" : "admin rule", "operation" : "inject", ... },
    { "description" : "user rule",  "operation" : "inject", ... },
    ...
  ]
}
----

[NOTE]
====
Please refer to the link:../appendices/resource_attributes.html#arbitration_rules[Resource Attributes]
page for a list of available attributes when creating Arbitration Rules.
====

[[editing-arbitration-rules]]
=== Editing Arbitration Rules

----
POST /api/arbitration_rules/:id
----

[source,json]
----
{
  "action" : "edit",
  "resource" : {
    "description" : "new admin rule"
  }
}
----

or editing multiple arbitration_rules:

----
POST /api/arbitration_rules
----

[source,json]
----
{
  "action" : "edit",
  "resources" : [
    {
      "href" : "http://localhost:3000/api/arbitration_rules/101",
      "priority" : 5
    },
    {
      "href" : "http://localhost:3000/api/arbitration_rules/102",
      "priority" : 5
    },
    ...
  ]
}
----


[[deleting-arbitration-rules]]
=== Deleting Arbitration Rules

Arbitration Rules can be deleted via either the *delete* POST action or via the DELETE HTTP method.

----
POST /api/arbitration_rules/101
----

[source,json]
----
{
  "action" : "delete"
}
----

or simply:

----
DELETE /api/arbitration_rules/101
----

Deleting multiple Arbitration Rules can be done as follows:

----
POST /api/arbitration_rules
----

[source,json]
----
{
  "action" : "delete",
  "resources" : [
    { "href" : "http://localhost:3000/api/arbitration_rules/101" },
    { "href" : "http://localhost:3000/api/arbitration_rules/102" },
    ...
  ]
}
----

