
[[arbitration-profiles]]
== Arbitration Profiles

Management of Arbitration Profiles is provided via the following collection:

[source,data]
----
/api/arbitration_profiles
----

Full CRUD actions on arbitration_profiles is available:

* link:#querying-arbitration-profiles[Querying Arbitration Profiles]
* link:#creating-arbitration-profiles[Creating Arbitration Profiles]
* link:#editing-arbitration-profiles[Editing Arbitration Profiles]
* link:#deleting-arbitration-profiles[Deleting Arbitration Profiles]

[[querying-arbitration-profiles]]
=== Querying Arbitration Profiles

Querying all arbitration profiles in the system is simply:

----
GET /api/arbitration_profiles
----

Getting details on a specific arbitration profile:

----
GET /api/arbitration_profiles/:id
----

[[creating-arbitration-profiles]]
=== Creating Arbitration Profiles

Arbitration Profiles can be created via a POST to the arbitration_profiles collection or via the *create* action
signature which also allows creation of multiple arbitration_profiles in a single request.

----
POST /api/arbitration_profiles
----

[source,json]
----
{
  "name" : "aws arbitration default",
  "provider" : {
    "href" : "http://localhost:3000/api/providers/5"
  }
}
----

or creating multiple arbitration profiles:

[source,json]
----
{
  "action" : "create",
  "resources" : [
    { "name" : "aws arbitration default",           "provider" : { "id" : 5 } },
    { "name" : "aws test environment arbitration",  "provider" : { "id" : 5 } },
    ...
  ]
}
----

[NOTE]
====
Please refer to the link:../appendices/resource_attributes.html#arbitration_profiles[Resource Attributes]
page for a list of available attributes when creating Arbitration Profiles.
====

[[editing-arbitration-profiles]]
=== Editing Arbitration Profiles

----
POST /api/arbitration_profiles/:id
----

[source,json]
----
{
  "action" : "edit",
  "resource" : {
    "name" : "aws development environment arbitration"
  }
}
----

or editing multiple arbitration_profiles:

----
POST /api/arbitration_profiles
----

[source,json]
----
{
  "action" : "edit",
  "resources" : [
    {
      "href" : "http://localhost:3000/api/arbitration_profiles/11",
      "description" : "First Test Profile"
    },
    {
      "href" : "http://localhost:3000/api/arbitration_profiles/12",
      "description" : "Second Test Profile"
    },
    ...
  ]
}
----


[[deleting-arbitration-profiles]]
=== Deleting Arbitration Profiles

Arbitration Profiles can be deleted via either the *delete* POST action or via the DELETE HTTP method.

----
POST /api/arbitration_profiles/101
----

[source,json]
----
{
  "action" : "delete"
}
----

or simply:

----
DELETE /api/arbitration_profiles/11
----

Deleting multiple Arbitration Profiles can be done as follows:

----
POST /api/arbitration_profiles
----

[source,json]
----
{
  "action" : "delete",
  "resources" : [
    { "href" : "http://localhost:3000/api/arbitration_profiles/11" },
    { "href" : "http://localhost:3000/api/arbitration_profiles/12" },
    ...
  ]
}
----

