
[[automate-domains]]
== Automate Domains

Querying the Automate Domains and triggering actions on domains is provided
via the following entrypoint:

[source,data]
----
/api/automate_domains
----

* link:#query-domains[Querying Domains]
* link:#accessing-domains[Accessing Domains]
* link:#refresh-from-source[Refresh From Source]

[[query-domains]]
=== Querying Domains

Querying the Automate Domains can be done via GET on the /api/automate_domains
entrypoint and can be queried like any other collection:

[source,data]
----
GET /api/automate_domains
----

[source,json]
----
{
  "name": "automate_domains",
  "count": 9,
  "subcount": 9,
  "resources": [
    {
      "href": "http://localhost:3000/api/automate_domains/2352"
    },
    {
      "href": "http://localhost:3000/api/automate_domains/2347"
    },
    ...
  ],
  "actions": [
    {
      "name": "query",
      "method": "post",
      "href": "http://localhost:3000/api/automate_domains"
    },
    {
      "name": "refresh_from_source",
      "method": "post",
      "href": "http://localhost:3000/api/automate_domains"
    }
  ]
}
----

[[accessing-domains]]
=== Accessing Domains

Accessing individual domains can be done via their numeric id or their name (_case sensitive_) as follows:

[source,data]
----
GET /api/automate_domains/2352
----

[source,data]
----
GET /api/automate_domains/ManageIQ
----

[[refresh-from-source]]
=== Refresh From Source

When Automate domains are imported from external sources, i.e. Git, the
_refresh_from_source_ will re-fetch the Automate domain from external source
and refresh the automate domain. This will refetch the Domain from the same
reference, i.e. branch or tag and name.

[source,data]
----
POST /api/automate_domains/SampleDomain
----

[source,json]
----
{
  "action": "refresh_from_source"
}
----

All refresh_from_source actions are done asynchronously and the related Task id and href are returned
as follows:

[source,json]
----
{
  "success": true,
  "message": "Refreshing Automate Domain id:2347 name:'SampleDomain' from git repository",
  "task_id": "61",
  "task_href": "http://localhost:3000/api/tasks/61",
  "href": "http://localhost:3000/api/automate_domains/SampleDomain"
}
----

If the Domain needs to be refreshed from a different branch or tag and name, the following can
be passed in with the _refresh_from_source_ action:

[source,json]
----
{
  "action": "refresh_from_source",
  "resource" : {
    "ref_type" : "branch" | "tag",
    "ref" : "other_branch_or_tag_name"
  }
}
----


