
[[automate-workspaces]]
== Automate Workspaces

Management of Automate Workspaces is provided with the following collection:

[source,data]
----
/api/automate_workspaces
----

- link:#querying-automate-workspaces[Querying Automate Workspaces]
- link:#editing-automate-workspaces[Editing Automate Workspaces]
- link:#encrypting-automate-workspace-passwords[Encrypting Automate Workspace Passwords]
- link:#decypting-automate-workspace-passwords[Decrypting Automate Workspace Passwords]

[[querying-automate-workspaces]]
==== Querying Automate Workspaces

It is not allowed to query the automate workspace collection, only individual
automate workspaces can be fetched by guid.

----
GET /api/automate_workspaces/:guid
----

Example GET Request and Response:

===== Request:

----
GET /api/automate_workspaces/430a66a0-b564-4341-b9b2-85d6f467f26f
----

===== Response:

[source,json]
----
{
  "href": "http://localhost:3000/api/automate_workspaces/430a66a0-b564-4341-b9b2-85d6f467f26f",
  "id": "2",
  "guid": "430a66a0-b564-4341-b9b2-85d6f467f26f",
  "user_id": "1",
  "tenant_id": "1",
  "input": {
    "objects": {
      "root": {
        "var1": "a",
        "var2": "b"
      }
    },
    "method_parameters": {
      "arg1": "first_argument"
    }
  },
  "actions": [
    {
      "name": "edit",
      "method": "post",
      "href": "http://localhost:3000/api/automate_workspaces/430a66a0-b564-4341-b9b2-85d6f467f26f"
    },
    {
      "name": "encrypt",
      "method": "post",
      "href": "http://localhost:3000/api/automate_workspaces/430a66a0-b564-4341-b9b2-85d6f467f26f"
    },
    {
      "name": "decrypt",
      "method": "post",
      "href": "http://localhost:3000/api/automate_workspaces/430a66a0-b564-4341-b9b2-85d6f467f26f"
    }
  ]
}
----

[[editing-automate-workspaces]]
==== Editing Automate Workspaces

Updating Automate Workspaces can be done via the _edit_ action as follows:

[source,data]
----
POST /api/automate_workspaces/:guid
----

[source,json]
----
{
  "action" : "edit",
  "resource" : {
    "objects" : {
      "root" : {
        "var3" : "c"
      }
    }
  }
}
----


[[encrypting-automate-workspace-passwords]]
==== Encrypting Automate Workspace Passwords

Encrypting passwords in the automate workspace can be done as follows:

===== Request:

[source,data]
----
POST /api/automate_workspaces/:guid
----

[source,json]
----
{
  "action" : "encrypt",
  "resource" : {
    "object" : "method_parameters",
    "attribute" : "arg2",
    "value" : "unencrypted_password"
  }
}
----

===== Response:

[source,json]
----
{
  "href": "http://localhost:3000/api/automate_workspaces/430a66a0-b564-4341-b9b2-85d6f467f26f",
  "id": "2",
  "guid": "430a66a0-b564-4341-b9b2-85d6f467f26f",
  "user_id": "1",
  "tenant_id": "1",
  "input": {
    "objects": {
      "root": {
        "var1": "a",
        "var2": "b"
      }
    },
    "method_parameters": {
      "arg1": "first_argument",
      "arg2": "password::********"
    }
  }
}
----

[[decypting-automate-workspace-passwords]]
==== Decrypting Automate Workspace Passwords

Encrypted passwords in the automate workspace can be decrypted individually as follows:

===== Request:

[source,data]
----
POST /api/automate_workspaces/:guid
----

[source,json]
----
{
  "action" : "decrypt",
  "resource" : {
    "object" : "method_parameters",
    "attribute" : "arg2"
  }
}
----

===== Response:

[source,json]
----
{
  "object" : "method_parameters",
  "attribtue" : "arg2",
  "value" : "unencrypted_password"
}
----

