
[[conditions]]
== Conditions

Management of Conditions is provided via the following collection:

[source,data]
----
/api/conditions
----

Full CRUD actions on conditions is available:

* link:#querying-conditions[Querying Conditions]
* link:#creating-conditions[Creating Conditions]
* link:#editing-conditions[Editing Conditions]
* link:#deleting-conditions[Deleting Conditions]

[[querying-conditions]]
=== Querying Conditions

Querying all conditions in the system is simply:

----
GET /api/conditions
----

Getting details on a specific Condition:

----
GET /api/conditions/:id
----

[[creating-conditions]]
=== Creating Conditions

Conditions can be created via a POST to the conditions collection or via the *create* action
signature which also allows creation of multiple conditions in a single request.

----
POST /api/conditions
----

[source,json]
----
{
  "name" : "sample_condition",
  "description" : "Sample Condition",
  "expression" : { "=" : { "field" : "ContainerImage-architecture", "value" : "dsa" } },
  "towhat" : "ExtManagementSystem",
  "modifier" : "allow"
}
----

or creating multiple conditions:

[source,json]
----
{
  "action" : "create",
  "resources" : [
    { "name" : "condition_1", "description" : "Condition 1", ... },
    { "name" : "condition_2", "description" : "Condition 2", ... },
    ...
  ]
}
----

[NOTE]
====
Please refer to the link:../appendices/resource_attributes.html#conditions[Resource Attributes]
page for a list of available attributes when creating Conditions.
====

[[editing-conditions]]
=== Editing Conditions

----
POST /api/conditions/:id
----

[source,json]
----
{
  "action" : "edit",
  "resource" : {
    "description" : "Updated Condition Description"
  }
}
----

or editing multiple conditions:

----
POST /api/conditions
----

[source,json]
----
{
  "action" : "edit",
  "resources" : [
    {
      "href" : "http://localhost:3000/api/conditions/101",
      "description" : "Updated Condition Description 1"
    },
    {
      "href" : "http://localhost:3000/api/conditions/102",
      "description" : "Updated Condition Description 2"
    },
    ...
  ]
}
----


[[deleting-conditions]]
=== Deleting Conditions

Conditions can be deleted via either the *delete* POST action or via the DELETE HTTP method.

----
POST /api/conditions/101
----

[source,json]
----
{
  "action" : "delete"
}
----

or simply:

----
DELETE /api/conditions/101
----

Deleting multiple Conditions can be done as follows:

----
POST /api/conditions
----

[source,json]
----
{
  "action" : "delete",
  "resources" : [
    { "href" : "http://localhost:3000/api/conditions/101" },
    { "href" : "http://localhost:3000/api/conditions/102" },
    ...
  ]
}
----

