[[conversion-hosts]]
== Conversion Hosts

Management of conversion hosts is provided via the following collection:

[source,data]
----
/api/conversion_hosts
----

The following actions are available for conversion hosts:

* link:#querying-conversion-hosts[Querying Conversion Hosts]
* link:#creating-conversion-hosts[Creating Conversion Hosts]
* link:#deleting-conversion-hosts[Deleting Conversion Hosts]

[[querying-conversion-hosts]]
=== Querying Conversion Hosts

To query all conversion hosts:

----
GET /api/conversion_hosts
----

To query a specific conversion host's details:

----
GET /api/conversion_hosts/:id
----

[[creating-conversion-hosts]]
=== Creation Conversion Hosts

Conversion hosts can be created via the _create_ POST action by posting the
request directly to */api/conversion_hosts*.

[source,json]
----
{
  "resource_type": "ManageIQ::Providers::Redhat::InfraManager::Host",
  "resource_id": 00000000000004,
  "auth_user": "root",
  "conversion_host_ssh_private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQI[...]gaS2cBrzxn3IQKTabc=\n-----END PRIVATE KEY-----\n",
  "vmware_vddk_package_url": "http://file.example.com/vddk/VMware-vix-disklib-stable.tar.gz"
}
----

==== Conversion Host Attributes

[cols="1<,1<,3<",options="header",]
|=====================
| Attribute Group                 | Type    | Description
| resource_type                   | string a| Type of resource that is acting as a conversion host:

* oVirt / RHV Host: `ManageIQ::Providers::Redhat::InfraManager::Host`
* oVirt / RHV VM: `ManageIQ::Providers::Redhat::InfraManager::Vm`
* OpenStack VM: `ManageIQ::Providers::Openstack::CloudManager::Vm`

| resource_id                     | integer | ID of the resource acting as a conversion host
| auth_user                       | string  | User name for the SSH connection to a conversion host
| conversion_host_ssh_private_key | string  | SSH private key for SSH connection to a conversion host. Line breaks must be replaced with `\n`.

| vmware_vddk_package_url         | string  | *_Only for VDDK transport_*. URL of downloaded VMware VDDK `tar.gz` archive file. The VDDK must be saved in an HTML-accessible location.

| vmware_ssh_private_key          | string  | *_Only for SSH transport_*. SSH private key for SSH connection to the VMware ESXi hosts. Line breaks must be replaced with `\n`.

| tls_ca_certs          | string  | CA certificate chain for validating the provider API endpoint certificate.
|=====================

==== Response

Creating a conversion host can take a few minutes because the resource is configured by an Ansible playbook. For this reason, the conversion host creation process is asynchronous.

The response provides the ID and the URL of the configuration task.

[source,json]
----
{
  "results": [
    {
      "success": true,
      "message": "Enabling resource id:00000000000004 type:ManageIQ::Providers::Redhat::InfraManager::Host",
      "task_id": "00000000000005",
      "task_href": "http://localhost:3000/api/tasks/00000000000005",
      "href": "https://localhost:3000/api/conversion_hosts/"
    }
  ]
}
----

==== Monitoring Configuration Tasks

To monitor the conversion host configuration tasks:

----
GET /api/tasks/:id
----

[source,json]
----
{
  "href": "http://localhost:3000/api/tasks/00000000000005",
  "id": "00000000000005",
  "name": "Configuring a conversion_host: operation=enable resource=(name: rhvh01.example.com type: ManageIQ::Providers::Redhat::InfraManager::Host id: 00000000000004)",
  "state": "Active",
  "status": "Ok",
  "message": "Task starting",
  "userid": "root",
  "created_on": "2019-09-10T07:21:36Z",
  "updated_on": "2019-09-10T07:21:37Z",
  "pct_complete": null,
  "context_data": {
    "request_params": {
      "resource_type": "Host",
      "resource_id": "00000000000004",
      "vmware_vddk_package_url": "http://file.example.com/vddk/VMware-vix-disklib-stable.tar.gz",
      "auth_user": "root"
    }
  },
  "results": null,
  "miq_server_id": "00000000000001",
  "identifier": null,
  "started_on": "2019-09-10T07:21:37Z",
  "zone": null,
  "actions": [
    {
      "name": "delete",
      "method": "post",
      "href": "http://localhost:3000/api/tasks/00000000000005"
    },
    {
      "name": "delete",
      "method": "delete",
      "href": "http://localhost:3000/api/tasks/00000000000005"
    }
  ]
}
----

[[deleting-conversion-hosts]]
=== Deleting Conversion Hosts

Conversion hosts can be deleted with either the *delete* `POST` action or the `DELETE` HTTP action.

To delete a single conversion host:

----
POST /api/conversion_hosts/101
----

[source,json]
----
{
  "action" : "delete"
}
----

or:

----
DELETE /api/conversion_hosts/101
----

To delete multiple conversion hosts:

----
POST /api/conversion_hosts
----

[source,json]
----
{
  "action" : "delete",
  "resources" : [
    { "href" : "http://localhost:3000/api/conversion_hosts/101" },
    { "href" : "http://localhost:3000/api/conversion_hosts/102" },
    ...
  ]
}
----
