
[[conversion-hosts]]
== Conversion Hosts

Management of Conversion Hosts is provided via the following collection:

[source,data]
----
/api/conversion_hosts
----

The following actions are available on conversion_hosts:

* link:#querying-conversion-hosts[Querying Conversion Hosts]
* link:#creating-conversion-hosts[Creating Conversion Hosts]
* link:#deleting-conversion-hosts[Deleting Conversion Hosts]

[[querying-conversion-hosts]]
=== Querying Conversion Hosts

Querying all conversion hosts in the system is simply:

----
GET /api/conversion_hosts
----

And getting details of a specific Conversion Host is as follows:

----
GET /api/conversion_hosts/:id
----

[[creating-conversion-hosts]]
=== Creation Conversion Hosts

Conversion Hosts can be created via the _create_ POST action by posting the
request directly to */api/conversion_hosts*

[source,json]
----
{
  "resource_type": "ManageIQ::Providers::Redhat::InfraManager::Host",
  "resource_id": 00000000000004,
  "auth_user": "root",
  "conversion_host_ssh_private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQI[...]gaS2cBrzxn3IQKTabc=\n-----END PRIVATE KEY-----\n",
  "vmware_vddk_package_url": "http://file.example.com/vddk/VMware-vix-disklib-stable.tar.gz"
}
----

==== Conversion Host attributes

[cols="1<,1<,3<",options="header",]
|=====================
| Attribute Group                 | Type    | Description
| resource_type                   | string a| Type of the resource acting as conversion host:

                                              * oVirt / RHV Host: `ManageIQ::Providers::Redhat::InfraManager::Host`
                                              * oVirt / RHV VM: `ManageIQ::Providers::Redhat::InfraManager::Vm`
                                              * OpenStack VM: `ManageIQ::Providers::Openstack::CloudManager::Vm`
| resource_id                     | integer | Id of the resource acting as conversion host
| auth_user                       | string  | Username for SSH connection to conversion host
| conversion_host_ssh_private_key | string  | SSH private key for SSH connection to conversion host. It's a single string so we have to replace new lines with `\n`.
| vmware_vddk_package_url         | string  | *_Only for VDDK transport_*. URL where to download VMware VDDK as a tar.gz archive.
| vmware_ssh_private_key          | string  | *_Only for SSH transport_*. SSH private key for SSH connection to the VMware ESXi hosts.
| openstack_tls_ca_certs          | string  | *_Only for OpenStack conversion host_*. The CA certification chain to validate OpenStack API endpoint certificate.
|=====================

==== Response

The creation of a conversion host is long, because it calls an Ansible playbook
that configures the resource. So it's done asynchronously and the response
provides the id and href of the configuration task.

[source,json]
----
{
  "results": [
    {
      "success": true,
      "message": "Enabling resource id:00000000000004 type:ManageIQ::Providers::Redhat::InfraManager::Host",
      "task_id": "00000000000005",
      "task_href": "http://localhost:3000/api/tasks/00000000000005",
      "href": "https://localhost:3000/api/conversion_hosts/"
    }
  ]
}
----

==== Monitoring configuration task

----
GET /api/tasks/:id
----

[source,json]
----
{
  "href": "http://localhost:3000/api/tasks/00000000000005",
  "id": "00000000000005",
  "name": "Configuring a conversion_host: operation=enable resource=(name: rhvh01.example.com type: ManageIQ::Providers::Redhat::InfraManager::Host id: 00000000000004)",
  "state": "Active",
  "status": "Ok",
  "message": "Task starting",
  "userid": "root",
  "created_on": "2019-09-10T07:21:36Z",
  "updated_on": "2019-09-10T07:21:37Z",
  "pct_complete": null,
  "context_data": {
    "request_params": {
      "resource_type": "Host",
      "resource_id": "00000000000004",
      "vmware_vddk_package_url": "http://file.example.com/vddk/VMware-vix-disklib-stable.tar.gz",
      "auth_user": "root"
    }
  },
  "results": null,
  "miq_server_id": "00000000000001",
  "identifier": null,
  "started_on": "2019-09-10T07:21:37Z",
  "zone": null,
  "actions": [
    {
      "name": "delete",
      "method": "post",
      "href": "http://localhost:3000/api/tasks/00000000000005"
    },
    {
      "name": "delete",
      "method": "delete",
      "href": "http://localhost:3000/api/tasks/00000000000005"
    }
  ]
}
----

[[deleting-conversion-hosts]]
=== Deleting Conversion Hosts

Conversion Hosts can be deleted via either the *delete* POST action or via the DELETE HTTP method.

----
POST /api/conversion_hosts/101
----

[source,json]
----
{
  "action" : "delete"
}
----

or simply:

----
DELETE /api/conversion_hosts/101
----

Deleting multiple Conversion Hosts can be done as follows:

----
POST /api/conversion_hosts
----

[source,json]
----
{
  "action" : "delete",
  "resources" : [
    { "href" : "http://localhost:3000/api/conversion_hosts/101" },
    { "href" : "http://localhost:3000/api/conversion_hosts/102" },
    ...
  ]
}
----

