
[[custom-button-management]]
== Custom Button Management

Management of Custom Buttons is provided with the following collections:

[source,data]
----
/api/custom_button_sets
/api/custom_buttons
----

* link:#custom-button-sets[Managing Custom Button Sets]
  - link:#querying-custom-button-sets[Querying Custom Button Sets]
  - link:#creating-custom-button-sets[Creating Custom Button Sets]
  - link:#editing-custom-button-sets[Editing Custom Button Sets]
  - link:#deleting-custom-button-sets[Deleting Custom Button Sets]
* link:#custom-buttons[Managing Custom Buttons]
  - link:#querying-custom-buttons[Querying Custom Buttons]
  - link:#creating-custom-buttons[Creating Custom Buttons]
  - link:#editing-custom-buttons[Editing Custom Buttons]
  - link:#deleting-custom-buttons[Deleting Custom Buttons]

[[custom-button-sets]]
=== Managing Custom Button Sets

[[querying-custom-button-sets]]
==== Querying Custom Button Sets

Querying all available Custom Button Sets:

----
GET /api/custom_button_sets
----

Getting details on a specific Custom Button Set:

----
GET /api/custom_button_sets/:id
----

[[creating-custom-button-sets]]
==== Creating Custom Button Sets

Custom Button Sets can be created as follows:

[source,data]
----
POST /api/custom_button_sets
----

[source,json]
----
{
  "name"        : "Generic Object Custom Button Group",
  "description" : "Generic Object Custom Button Group Description",
  "set_data"    : {
    "button_icon"      : "ff ff-view-expanded",
    "button_color"     : "#4727ff",
    "display"          : true,
    "applies_to_class" : "GenericObjectDefinition",
    "applies_to_id"    : "50"
  }
}
----

[[editing-custom-button-sets]]
==== Editing Custom Button Sets

Updating Custom Button Sets can be done via the _edit_ action as follows:

[source,data]
----
POST /api/custom_button_sets/:id
----

[source,json]
----
{
  "action" : "edit",
  "resource" : {
    "name" : "Updated Custom Button Group",
    "description" : "Updated Custom Button Group Description",
    "set_data" : {
      "button_icon" : "ff ff-closed"
    }
  }
}
----

Custom Button Sets can also be updated in bulk:

[source,data]
----
POST /api/custom_button_sets
----

[source,json]
----
{
  "action" : "edit",
  "resources" : [
    { "id" : "11", "set_data" : { "button_icon" : "ff ff-closed" } },
    { "id" : "12", "set_data" : { "button_icon" : "ff ff-closed" } },
    { "id" : "13", "set_data" : { "button_icon" : "ff ff-closed" } }
  ]
}
----

Custom button sets can also be updated with the PUT method as follows:

[source,data]
----
PUT /api/custom_button_sets/:id
----

[source,json]
----
{
  "name" : "Updated Custom Button Group",
  "description" : "Updated Custom Button Group Description",
  "set_data" : {
    "button_icon" : "ff ff-closed"
  }
}
----

[[deleting-custom-button-sets]]
==== Deleting Custom Button Sets

Custom Button Sets can be deleted via the _delete_ action as follows:

[source,data]
----
POST /api/custom_button_sets/:id
----

[source,json]
----
{
  "action" : "delete"
}
----

and in bulk as follows:

[source,data]
----
POST /api/custom_button_sets
----

[source,json]
----
{
  "action" : "delete",
  "resources" : [
    { "href" : "http://localhost:3000/api/custom_button_sets/21" },
    { "href" : "http://localhost:3000/api/custom_button_sets/22" },
    { "id" : "23" }
  ]
}
----

A single Custom Button Set can also be deleted with the DELETE method as follows:

[source,data]
----
DELETE /api/custom_button_sets/:id
----

[[custom-buttons]]
=== Managing Custom Buttons

[[querying-custom-buttons]]
==== Querying Custom Buttons

Querying all available Custom Buttons:

----
GET /api/custom_buttons
----

Getting details on a specific Custom Button:

----
GET /api/custom_buttons/:id
----

[[creating-custom-buttons]]
==== Creating Custom Buttons

Custom Buttons can be created as follows:

[source,data]
----
POST /api/custom_buttons
----

[source,json]
----
{
  "name"             : "Generic Object Custom Button",
  "description"      : "Generic Object Custom Button Description",
  "applies_to_class" : "GenericObjectDefinition",
  "options"          : {
    "button_icon"    : "ff ff-view-expanded",
    "button_color"   : "#4727ff",
    "display"        : true
  },
  "resource_action"  : {
    "ae_namespace"   : "SYSTEM",
    "ae_class"       : "PROCESS",
    "dialog_id"      : "1"
  },
  "visibility"       : {
    "roles"          : ["_ALL_"]
  }
}
----

[[editing-custom-buttons]]
==== Editing Custom Buttons

Updating Custom Buttons can be done via the _edit_ action as follows:

[source,data]
----
POST /api/custom_buttons/:id
----

[source,json]
----
{
  "action" : "edit",
  "resource" : {
    "name" : "Updated Custom Button",
    "description" : "Updated Custom Button Description",
    "resource_action" : {
      "ae_namespace"  : "SYSTEM2"
    }
  }
}
----

Custom Buttons can also be updated in Bulk as follows:

[source,data]
----
POST /api/custom_buttons
----

[source,json]
----
{
  "action" : "edit",
  "resources" : [
    {
      "href" : "http://localhost:3000/api/custom_buttons/31",
      "options" :  { "display" : false }
    },
    {
      "href" : "http://localhost:3000/api/custom_buttons/32",
      "options" :  { "display" : false }
    },
    {
      "id"   : "33",
      "options" :  { "display" : false }
    }
  ]
}
----

[[deleting-custom-buttons]]
==== Deleting Custom Buttons

Custom Buttons can be deleted via the _delete_ action as follows:

[source,data]
----
POST /api/custom_buttons/:id
----

[source,json]
----
{
  "action" : "delete"
}
----

Multiple Custom Buttons can also be deleted in a single request as follows:

[source,data]
----
POST /api/custom_buttons
----

[source,json]
----
{
  "action" : "delete",
  "resources" : [
    { "href" : "http://localhost:3000/api/custom_buttons/21" },
    { "id" : "22" },
    { "id" : "23" }
  ]
}
----

Single Custom Buttons can also be deleted with the DELETE method as follows:

[source,data]
----
DELETE /api/custom_buttons/:id
----

