
[[flavor-management]]
== Flavor Management

Management of Flavors is available via the following endpoint:

[source,data]
----
/api/flavors
----

[[querying-flavors]]
=== Querying Flavors

Querying all available Flavors:

----
GET /api/flavors
----

Getting details on a specific Flavor:

----
GET /api/flavors/:id
----

Querying the Flavors for a specific Provider:

----
GET /api/providers/:id/flavors
----

Getting details on a specific Flavor of a Provider:

----
GET /api/providers/:id/flavors/:flavor_id
----

[[managing-flavors]]
=== Managing Flavors

The following actions are available on Flavors of Providers:

[cols="1,3",options="header",width="60%"]
|=====================
| Action | Description
| link:#create-flavors[create] | Create Flavors
| link:#delete-flavors[delete] | Delete Flavors
|=====================

[[create-flavors]]
=== Create Flavors

Flavors can be created directly for a Provider as follows:

[source,data]
----
POST /api/providers/:id/flavors
----

[source,json]
----
{
  "name" : "base-system",
  "cpu_cores" : 2,
  "memory" :  4096000000,
  "root_disk_size" : 16384000000
}
----

[[delete-flavors]]
=== Delete Flavors

Flavors of a Provider can be deleted via the _delete_ action:

[source,data]
----
POST /api/providers/:id/flavors/:flavor_id
----

[source,json]
----
{
  "action" : "delete"
}
----

Multiple Flavors can also be deleted in a single request as follows:

[source,data]
----
POST /api/providers/:id/flavors
----

[source,json]
----
{
  "action" : "delete",
  "resources" : [
    { "href" : "http://localhost:3000/api/flavors/6" },
    { "id" : "7" }
  ]
}
----

Single Flavors can also be deleted with the DELETE HTTP method as follows:

[source,data]
----
DELETE /api/providers/:id/flavors/:flavor_id
----

