
[[group-management]]
== Group Management

Management of User Groups is provided via the following collection:

[source,data]
----
/api/groups
----

Full CRUD actions on groups is available:


* link:#querying-groups[Querying Groups]
* link:#creating-groups[Creating Groups]
* link:#editing-groups[Editing Groups]
* link:#deleting-groups[Deleting Groups]

[[querying-groups]]
=== Querying Groups

Querying all groups in the system:

----
GET /api/groups
----

Getting details on a specific group:

----
GET /api/groups/:id
----

[[creating-groups]]
=== Creating Groups

Groups can be created via a POST to the groups collection or via the *create* action signature which also
allows creation of multiple groups in a single request.

----
POST /api/groups
----

[source,json]
----
{
  "description" : "sample_group",
  "role" : { "id" : "2" },
  "tenant" : { "href" : "http://localhost:3000/api/tenants/1" },
  "filters" : {
    "belongsto" : [ "/belongsto/ExtManagementSystem|provider1" ],
    "managed" : [[ "/managed/infra/1" ]]
  }
}
----

[NOTE]
=====
role can be specified via *name*, *href*, or *id*

tenant can be specified via *href* or *id*
=====

or creating multiple groups:

[source,json]
----
{
  "action" : "create",
  "resources" : [
    { "description" : "sample_group1", ... },
    { "description" : "sample_group2", ... },
    ...
  ]
}
----

[NOTE]
====
Please refer to the link:../appendices/resource_attributes.html#groups[Resource Attributes]
page for a list of available attributes when creating Groups.
====

[[editing-groups]]
=== Editing Groups

----
POST /api/groups/:id
----

[source,json]
----
{
  "action" : "edit",
  "resource" : {
    "description" : "updated_sample_group",
    "filters" : {
      "belongsto" : [ "/belongsto/ExtManagementSystem|provider1", "/belongsto/ExtManagementSystem|provider2" ],
      "managed" : [[ "/managed/infra/1", "/managed/infra/2" ]]
    }
  }
}
----

or editing multiple groups:

----
POST /api/groups
----

[source,json]
----
{
  "action" : "edit",
  "resources" : [
    {
      "href" : "http://localhost:3000/api/groups/101",
      "description" : "updated_sample_group1"
    },
    {
      "href" : "http://localhost:3000/api/groups/102",
      "description" : "updated_sample_group2"
    },
    ...
  ]
}
----


[[deleting-groups]]
=== Deleting Groups

groups can be deleted via either the *delete* POST action or via the DELETE HTTP method.

----
POST /api/groups/101
----

[source,json]
----
{
  "action" : "delete"
}
----

or simply:

----
DELETE /api/groups/101
----

Deleting multiple groups can be done as follows:

----
POST /api/groups
----

[source,json]
----
{
  "action" : "delete",
  "resources" : [
    { "href" : "http://localhost:3000/api/groups/101" },
    { "href" : "http://localhost:3000/api/groups/102" },
    ...
  ]
}
----

