
[[orchestration-support]]
== Orchestration Support

Support for orchestration is provided by the following:

* link:#orchestration-templates[Orchestration Templates]

[[orchestration-templates]]
=== Orchestration Templates ===

Management of orchestration templates is provided with the following collection:

[source,data]
----
/api/orchestration_templates
----

Full CRUD actions on orchestration templates is available:


* link:#querying-orchestration-templates[Querying Orchestration Templates]
* link:#creating-orchestration-templates[Creating Orchestration Templates]
* link:#editing-orchestration-templates[Editing Orchestration Templates]
* link:#copying-orchestration-templates[Copying Orchestration Templates]
* link:#deleting-orchestration-templates[Deleting Orchestration Templates]

[[querying-orchestration-templates]]
=== Querying Orchestration Templates

Querying all orchestration templates in the system:

----
GET /api/orchestration_templates
----

Getting details on a specific orchestration template:

----
GET /api/orchestration_templates/:id
----

[[creating-orchestration-templates]]
=== Creating Orchestration Templates

Orchestration templates can be created via a POST to the orchestration templates collection or via the *create* action signature which also
allows creation of multiple orchestration templates in a single request.

----
POST /api/orchestration_templates
----

[source,json]
----
{
  "name" : "azure-single-vm-from-user-image",
  "type" : "OrchestrationTemplateAzure",
  "description" : "Create a single VM from a user image",
  "content" : " ... ",
  "orderable" : true,
  ...
}
----

or creating multiple orchestration templates:

[source,json]
----
{
  "action" : "create",
  "resources" : [
    { "description" : "sample_orchestration_template1", ... },
    { "description" : "sample_orchestration_template2", ... },
    ...
  ]
}
----

[NOTE]
====
Please refer to the link:../appendices/resource_attributes.html#orchestration_templates[Resource Attributes]
page for a list of available attributes when creating orchestration templates.
====

[[editing-orchestration-templates]]
=== Editing Orchestration Templates

----
POST /api/orchestration_templates/:id
----

[source,json]
----
{
  "action" : "edit",
  "resource" : {
    "description" : "updated_sample_orchestration_template",
  }
}
----

or editing multiple orchestration templates:

----
POST /api/orchestration_templates
----

[source,json]
----
{
  "action" : "edit",
  "resources" : [
    {
      "href" : "http://localhost:3000/api/orchestration_templates/101",
      "description" : "updated_sample_orchestration_template1"
    },
    {
      "href" : "http://localhost:3000/api/orchestration_templates/102",
      "description" : "updated_sample_orchestration_template2"
    },
    ...
  ]
}
----

[[copying-orchestration-templates]]
=== Copying Orchestration Templates

This capability allows orchestration templates to be copied onto new orchestration templates with updated content
via the _copy_ action as follows:

----
POST /api/orchestration_templates/:id
----

[source,json]
----
{
  "action" : "copy",
  "resource" : {
    "content" : "{ 'Description' : 'Copied Test Content' }"
  }
}
----

or copying multiple orchestration templates:

----
POST /api/orchestration_templates
----

[source,json]
----
{
  "action" : "copy",
  "resources" : [
    {
      "href" : "http://localhost:3000/api/orchestration_templates/101",
      "content" : "{ 'Description' : 'Copied Test Content 1' }"
    },
    {
      "href" : "http://localhost:3000/api/orchestration_templates/102",
      "content" : "{ 'Description' : 'Copied Test Content 2' }"
    },
    ...
  ]
}
----

[[deleting-orchestration-templates]]
=== Deleting Orchestration Templates

Orchestration templates can be deleted via either the *delete* POST action or via the DELETE HTTP method.

----
POST /api/orchestration_templates/101
----

[source,json]
----
{
  "action" : "delete"
}
----

or simply:

----
DELETE /api/orchestration_templates/101
----

Deleting multiple orchestration templates can be done as follows:

----
POST /api/orchestration_templates
----

[source,json]
----
{
  "action" : "delete",
  "resources" : [
    { "href" : "http://localhost:3000/api/orchestration_templates/101" },
    { "href" : "http://localhost:3000/api/orchestration_templates/102" },
    ...
  ]
}
----

