
[[picture-management]]
== Picture Management

Management of Pictures adds support of the following actions:

* link:#creating-picture[Creating a Picture]
* link:#querying-pictures[Querying Pictures]

[[creating-picture]]
=== Creating a Picture

[source,data]
----
POST /api/pictures
----

[source,json]
----
{
  "extension": "<extension of image>",
  "content": "<base 64 encoded image here>"
}
----

Supported extensions include:

[cols="1",options="header",width="30%"]
|=====
| Extension
| jpg
| png
| svg
|=====

[[querying-pictures]]
=== Querying Pictures

Querying pictures like any other collection:

[source,data]
----
GET /api/pictures?expand=resources
----

[source,json]
----
{
  "name": "pictures",
  "count": 5,
  "subcount": 5,
  "resources": [
    {
      "href": "http://localhost:3000/api/pictures/1",
      "id": "1"
    },
    ...
    {
      "href": "http://localhost:3000/api/pictures/4",
      "id": "4",
      "resource_id": "1",
      "resource_type": "ServiceTemplate"
    },
    {
      "href": "http://localhost:3000/api/pictures/5",
      "id": "5"
    }
  ],
  "actions": [
    {
      "name": "create",
      "method": "post",
      "href": "http://localhost:3000/api/pictures"
    }
  ]
}
----

This query does not return the pictures themselves, but primary resources for them.

Additional information can be obtained regarding the image binary via the _binary_blob_ attribute:

[source,data]
----
GET /api/pictures/4?attributes=binary_blob
----

[source,json]
----
{
  "href": "http://localhost:3000/api/pictures/4",
  "id": "4",
  "resource_id": "1",
  "resource_type": "ServiceTemplate",
  "binary_blob": {
    "id": "4",
    "resource_type": "Picture",
    "resource_id": "4",
    "md5": "0a38d1998325099141d4c68552440b1d",
    "size": 68314,
    "part_size": 1048576,
    "data_type": "jpg"
  }
}
----

Actually fetching the particular picture is by getting the image by its href.

The image_href of a picture can be queried as follows:

[source,data]
----
GET /api/pictures/4?attributes=binary_blob,image_href
----

[source,json]
----
{
  "href": "http://localhost:3000/api/pictures/4",
  "id": "4",
  "resource_id": "1",
  "resource_type": "ServiceTemplate",
  "binary_blob": {
    "id": "4",
    "resource_type": "Picture",
    "resource_id": "4",
    "md5": "0a38d1998325099141d4c68552440b1d",
    "size": 68314,
    "part_size": 1048576,
    "data_type": "jpg"
  },
  "image_href": "http://localhost:3000/pictures/4.jpg"
}
----

In which case the image can simply be downloaded with a GET:

[source,data]
----
GET http://localhost:3000/pictures/4.jpg
----

For fetching information about pictures pertaining to services, see the section
link:../reference/service_queries.html#querying-pictures[Querying Pictures] for details.

