
[[requests]]
== Request Support

Support for Requests in the API is provided and implemented by specific request types 
as listed here:

[cols="1<,1<,3<",options="header",width="60%"]
|=====================
| API Collection | Request Type
| /api/automation_requests | link:automation_requests.html[Automation Requests]
| /api/provision_requests  | link:provision_requests.html[Provision Requests]
| /api/service_requests    | link:services.html#service-requests[Service Requests]
|=====================

A lower level support for creating and updating requests is also provided
by the following:

[source,data]
----
/api/requests
----

* link:#creating-requests[Creating Requests]
* link:#querying-requests[Querying Requests]
* link:#editing-requests[Editing Requests]
* link:#approving-denying-requests[Approving or Denying Requests]
* link:#request-types[Request Types]

[[creating-requests]]
=== Creating Requests

Either by specifying a _create_ action or by posting the request directly
to */api/requests*.

As an example:

[source,data]
----
POST /api/requests
----

[source,json]
----
{
  "options" : {
    "request_type" : "service_reconfigure",
    "src_id" : 4,
    "service_param1" : "updated_value1",
    "service_param2" : "updated_value2"
  },
  "requester" : {
    "user_name" : "admin"
  },
  "auto_approve" : true | false
}
----

Response:

[source,json]
----
{
  "results": [
    {
      "id": 97,
      "description": "Service Reconfigure for: svc4",
      "approval_state": "pending_approval",
      "type": "ServiceReconfigureRequest",
      "created_on": "2016-11-10T21:39:08Z",
      "updated_on": "2016-11-10T21:39:08Z",
      "requester_id": 1,
      "requester_name": "Administrator",
      "request_type": "service_reconfigure",
      "request_state": "pending",
      "message": "Service Reconfigure - Request Created",
      "status": "Ok",
      "options": {
        "request_type": "service_reconfigure",
        "src_id": 4,
        "service_param1": "updated_value1",
        "service_param2": "updated_value2"
      },
      "userid": "admin",
      "source_id": 4,
      "source_type": "Service",
      "tenant_id": 1,
      "process": true
    }
  ]
}
----

[[querying-requests]]
=== Querying Requests

Once a request is created, the response result as shown above will include the id of request itself.

In the above example, the request could be queried periodically until the *request_state* reaches the *finished* state.

----
GET /api/requests/97
----

*NOTE*: The requests tasks of a request can also be queried by expanding the request_tasks subcollection:

----
GET /api/requests/:id?expand=request_tasks
----

An alias *tasks* is also defined and can be queried as such:

----
GET /api/requests/:id?expand=tasks
----

[[editing-requests]]
=== Editing Requests

Updating requests is provided by specifying an _edit_ action as follows:

[source,data]
----
POST /api/requests/97
----

[source,json]
----
{
  "action" : "edit",
  "resource" : {
    "options" : {
      "service_param1" : "new_updated_value1",
      "service_param2" : "new_updated_value2"
    },
    "requester" : {
      "user_name" : "admin"
    }
  }
}
----

Response:

[source,json]
----
{
  "href": "http://localhost:3000/api/requests/97",
  "id": 97,
  "options": {
    "request_type": "service_reconfigure",
    "src_id": 4,
    "service_param1": "new_updated_value1",
    "service_param2": "new_updated_value2"
  },
  "description": "Service Reconfigure for: svc3",
  "approval_state": "pending_approval",
  "type": "ServiceReconfigureRequest",
  "created_on": "2016-11-10T21:39:08Z",
  "updated_on": "2016-11-10T22:11:03Z",
  "requester_id": 1,
  "requester_name": "Administrator",
  "request_type": "service_reconfigure",
  "request_state": "pending",
  "message": "Service Reconfigure - Request Created",
  "status": "Ok",
  "userid": "admin",
  "source_id": 4,
  "source_type": "Service",
  "tenant_id": 1,
  "process": true
}
----

[[approving-denying-requests]]
=== Approving or Denying Requests

If a request is not auto approved, it can be approved or denied via the actions _approve_ and _deny_ on the 
request resource.

[[approving-request]]
==== Approving a Request

[source,data]
----
POST /api/requests/:id
----

[source,json]
----
{
  "action" : "approve",
  "reason" : "reason for approval"
}
----

[[denying-request]]
==== Denying a Request

[source,data]
----
POST /api/requests/:id
----

[source,json]
----
{
  "action" : "deny",
  "reason" : "reason for denial"
}
----

[[request-types]]
=== Request Types

The details for creating each type of request using the lower level
API, including validation of _request_type_ and necessary options is
driven by the model.

The basic structure for creating the request is as follows:

[source,json]
----
{
  "options" : {
    "request_type" : "...",
    ...
  },
  "requester" : {
    "user_name" : "..."
  },
  "auto_approve" : true | false
}
----

The list of supported _request_type_ values as of this writing is shown here below:

[cols="2<,2<",options="header",width="60%"]
|=====================
| request_type          | Description
| automation            | Automation
| clone_to_service      | Service Provision
| clone_to_template     | VM Publish
| clone_to_vm           | VM Clone
| host_pxe_install      | Host Provision
| provision_via_foreman | Foreman Provision
| service_reconfigure   | Service Reconfigure
| template              | VM Provision
| vm_migrate            | VM Migrate
| vm_reconfigure        | VM Reconfigure
|=====================


