
[[service-orders]]
== Service Orders

The Service Orders collection and actions are provided for managing Shopping Carts and their related
service requests.

[source,data]
----
/api/service_orders
----

Available actions on service_orders instances include:

[cols="1,3",options="header"]
|=====================
| Action | Description
| create | Creating the Shopping Cart
| clear | Clearing the Shopping Cart
| order | Ordering all service requests in the Shopping Cart
| copy | Copying the Shopping Cart
| delete | Deleting the Shopping Cart
|=====================

Some important points on Shopping Carts:

* There is one and only one shopping cart for the authenticated user
* A shopping cart is an /api/service_orders resource with a state of *cart*
* Shopping carts can be referenced by their resource id or preferably via the alphanumeric **cart** identifier.
* resource id's need to be used for accessing non-cart service_orders states of *wish* list and *ordered*

Items to add to a shopping cart are _service_requests_ that are specified similarly to when
services are ordered from a service template.

* link:#querying-service-orders[Querying Service Orders]
* link:#creating-service-orders[Creating Service Orders]
* link:#adding-service-requests[Adding Service Requests]
* link:#removing-service-requests[Removing Service Requests]
* link:#clearing-service-orders[Clearing Service Orders]
* link:#copying-service-orders[Copying Service Orders]
* link:#deleting-service-orders[Deleting Service Orders]
* link:#ordering-service-orders[Ordering Service Orders]

[[querying-service-orders]]
=== Querying Service Orders

All the queries listed here below return the service orders for
the authenticated user.

Getting all service_orders:

[source,data]
----
GET /api/service_orders
----

Getting the shopping cart:

[source,data]
----
GET /api/service_orders/cart
----

Getting the shopping cart with expanded service_requests:

[source,data]
----
GET /api/service_orders/cart?expand=service_requests,resources
----

Getting the service requests of the shopping cart:

[source,data]
----
GET /api/service_orders/cart/service_requests
----

[[creating-service-orders]]
=== Creating Service Orders with multiple service requests

[source,data]
----
POST /api/service_orders
----

[source,json]
----
{
  "service_requests" : [
    {
      "service_template_href" : "http://localhost:3000/api/service_templates/3",
      "Basic_Host_Name" : "super_vm_a",
      "Basic_Host_Ip" : "192.168.120.101"
    },
    {
      "service_template_href" : "http://localhost:3000/api/service_templates/3",
      "Basic_Host_Name" : "super_vm_b",
      "Basic_Host_Ip" : "192.168.120.102"
    },
    ...
  ]
}
----


Creating a wish list service_order:

[source,data]
----
POST /api/service_orders
----

[source,json]
----
{
  "state" : "wish",
  "service_requests" : [
    {
      "service_template_href" : "http://localhost:3000/api/service_templates/2",
      "host_name" : "sample_service_order_host_name",
      "host_ip" : "192.168.120.101"
    }
  ]
}
----

[[adding-service-requests]]
=== Adding Service Requests

Adding service requests to a shopping cart can be done by either of the create methods
shown above which will all add the service requests to the existing shopping cart:

[source,data]
----
POST /api/service_orders
----

or specifically to the shopping cart or any wish list service_orders via its _id_
instead of **cart** as follows:

[source,data]
----
POST /api/service_orders/cart/service_requests
----

[source,data]
----
POST /api/service_orders/:id/service_requests
----

[source,json]
----
{
  "action" : "add",
  "resources" : [
    {
      "service_template_href" : "http://localhost:3000/api/service_templates/3",
      "Basic_Host_Name" : "sample_service_order_host_name_2",
      "Basic_Host_Ip" : "192.168.120.102"
    },
    {
      "service_template_href" : "http://localhost:3000/api/service_templates/3",
      "Basic_Host_Name" : "sample_service_order_host_name_3",
      "Basic_Host_Bad_Ip" : "192.168.120.103"
    },
    ...
  ]
}
----

**Note**:
* POST /api/service_orders is atomic, requests are validated for all requests before adding them.
* POST /api/service_orders/cart/service_requests will add the requests one by one,
the action responses have the *success* field for each requests reflecting the success 
or failure of each request.

[[removing-service-requests]]
=== Removing Service Requests

Removing requests from the shopping cart is available via the _remove_ action:

[source,data]
----
POST /api/service_orders/cart/service_requests
----

[source,json]
----
{
  "action" : "remove",
  "resources" : [
    { "href" : "http://localhost:3000/api/service_orders/6/service_requests/56" },
    { "href" : "http://localhost:3000/api/service_orders/6/service_requests/57" }
  ]
}
----

[[clearing-service-orders]]
=== Clearing Service Orders

Clearing the shopping cart can be done via the _clear_ action:

[source,data]
----
POST /api/service_orders/cart
----

[source,json]
----
{
  "action" : "clear"
}
----

[[copying-service-orders]]
=== Copying Service Orders

A Service Order can be copied into a new Service Order via the _copy_ action:

[source,data]
----
POST /api/service_orders/:id
----

[source,json]
----
{
   "action" : "copy",
   "resource" : {
      "name" : "new_service_order_name"
   }
}
----

Service Ordered can also be copied in bulk as follows:

[source,data]
----
POST /api/service_orders/:id
----

[source,json]
----
{
   "action" : "copy",
   "resources" : [
      {
        "href" : "http://localhost:3000/api/service_orders/1",
        "name" : "new_service_order_name_1"
      },
      {
        "href" : "http://localhost:3000/api/service_orders/2",
        "name" : "new_service_order_name_2"
      },
      ...
   ]
}
----

[[deleting-service-orders]]
=== Deleting Service Orders

Deleting the shopping cart can be done via the _delete_ action:

[source,data]
----
POST /api/service_orders/cart
----

[source,json]
----
{
   "action" : "delete"
}
----

or simply via the DELETE method:

[source,data]
----
DELETE /api/service_orders/cart
----

[[ordering-service-orders]]
=== Ordering Service Orders

Ordering the shopping cart is done via the _order_ action as follows:

[source,data]
----
POST /api/service_orders/cart
----

[source,json]
----
{
   "action" : "order"
}
----

