
[[settings-management]]
== Settings Management

Management of advanced settings is available on servers, zones and regions. They
are provided with the following collection:

[source,data]
----
/api/settings
----

for the server processing the API, or specifically for a particular server, zone or region as follows:

[source,data]
----
/api/servers/:id/settings
----

[source,data]
----
/api/zones/:id/settings
----

[source,data]
----
/api/regions/:id/settings
----

The following actions are available with advanced settings:

* link:#querying-settings[Querying Settings]
* link:#updating-settings[Updating Settings]
* link:#deleting-settings[Deleting Settings]

[[querying-settings]]
=== Querying Settings

Settings can be queried as follows:

[source,data]
----
GET /api/servers
----

[source,data]
----
GET /api/servers/:id/settings
----

[source,data]
----
GET /api/zones/:id/settings
----

[source,data]
----
GET /api/regions/:id/settings
----

.Authorization
[NOTE]
================
- For users with an _EvmGroup-super_administrator_ role, the complete advanced settings are returned.

- For users with roles that include the _Configuration Settings_ feature, only a whitelisted set of settings are returned.

- Requests from all other users will be rejected with a Forbidden error.
================


[[updating-settings]]
=== Updating Settings

Updating settings can only be performed by users with an _EvmGroup-super_administrator_ role.

Updates to settings is available with the HTTP PATCH method as follows:

[source,data]
----
PATCH /api/servers/:id/settings
----

[source,data]
----
PATCH /api/zones/:id/settings
----

[source,data]
----
PATCH /api/regions/:id/settings
----

The following is an example updating the policy_events's purge_window_size:

==== Request:

[source,data]
----
PATCH /api/servers/1/settings
----

[source,data]
----
{
  “policy_events” : {
    “purge_window_size” : 500
  }
}
----

==== Response:

The complete updated settings is returned:

[source,data]
----
{
  "ems": {
    "ems_ansible_tower": {
      "blacklisted_event_names": [

      ],
  ...
  “policy_events” : {
    "history": {
      "keep_policy_events": "6.months",
      "purge_window_size": 1000
    },
    “purge_window_size” : 500
  },
  ...
  "hawkular_tenant_labels": {
    "_hawkular_admin": "Hawkular Admin"
  }
}
----

[[deleting-settings]]
=== Deleting Settings

Deleting settings can only be performed by users with an _EvmGroup-super_administrator_ role.

Deleting settings is available with the HTTP DELETE method as follows:

[source,data]
----
DELETE /api/servers/:id/settings
----

[source,data]
----
DELETE /api/zones/:id/settings
----

[source,data]
----
DELETE /api/regions/:id/settings
----

Requests must include an array representing the path of the setting to delete.

==== Example:

[source,data]
----
DELETE /api/servers/1/settings
----

[source,data]
----
[ "policy_events", "purge_window_size" ]
----

This request deletes the policy_event's purge_window_size setting for /api/servers/1 and its value would revert to its default.

