
[[snapshot-management]]
== Snapshot Management

Management of snapshots is provided for virtual machines and instances via the snapshots subcollection:

[source,data]
----
/api/vms/:id/snapshots
----

[source,data]
----
/api/instances/:id/snapshots
----

[[snapshot-actions]]
=== Snapshot Actions

The following snapshot actions are availables for the supported resources:

[cols="2,1,1",options="header",width=50%]
|=====================
| Snapshot Action | Vms | Instances
| read | X | X
| create | X | X
| revert | X |
| delete | X | X
|=====================

* link:#query-snapshots[Querying Snapshots]
* link:#create-snapshots[Creating Snapshots]
* link:#revert-snapshots[Reverting Snapshots]
* link:#delete-snapshots[Deleting Snapshots]

[[query-snapshots]]
=== Querying Snapshots

Snapshots of machines are queried via the subcollection of vms and instances as follows:

Querying all snapshots of a VM:

[source,data]
----
GET /api/vms/:id/snapshots
----

Querying all snapshots of an Instance:

[source,data]
----
GET /api/instances/:id/snapshots
----

Filtering, sorting and paging on the subcollection as mentioned on the
link:../overview/query.html[Querying] page.

For example:

[source,data]
----
GET /api/vms/11/snapshots?expand=resources&filter[]=name=test*
----

One can also fetch a single snapshot by id:

[source,data]
----
GET /api/vms/:id/snapshots/:snapshot_id
----

[source,data]
----
GET /api/instances/:id/snapshots/:snapshot_id
----

[[create-snapshots]]
=== Creating Snapshots

Creating snapshots on Vms and Instances is done by posting the request to the snapshots subcollection.

[source,data]
----
POST /api/vms/:id/snapshots
----

[source,data]
----
POST /api/instances/:id/snapshots
----

[source,json]
----
{
  "name" : "name_of_new_snapshot",
  "desciption" : "Description of new Snapshot",
  "memory" : false
}
----

In the above example, only _name_ is required. _memory_ can be set to true to have the snapshot include physical memory.

[[revert-snapshots]]
=== Reverting Snapshots

Reverting snapshots is only available for Vms.

[source,data]
----
POST /api/vms/:id/snapshots/:snapshot_id
----

[source,json]
----
{
  "action" : "revert"
}
----

[[delete-snapshots]]
=== Deleting Snapshots

Individual snapshots of Vms and Instances can be deleted via the DELETE method as follows:

[source,data]
----
DELETE /api/vms/:id/snapshots/:snapshot_id
----

[source,data]
----
DELETE /api/instances/:id/snapshots/:snapshot_id
----

As well as the _delete_ POST action as follows for VMs:

[source,data]
----
POST /api/vms/:id/snapshots/:snapshot_id
----

or instances:

[source,data]
----
POST /api/instances/:id/snapshots/:snapshot_id
----

[source,json]
----
{
  "action" : "delete"
}
----

Snapshots can also be deleted in bulk via the _delete_ action on the snapshots subcollection as follows:

[source,data]
----
POST /api/vms/11/snapshots
----

[source,json]
----
{
  "action" : "delete",
  "resources" : [
    { "href" : "http://localhost:3000/api/vms/11/snapshots/3" },
    { "href" : "http://localhost:3000/api/vms/11/snapshots/4" },
    { "href" : "http://localhost:3000/api/vms/11/snapshots/5" }
  ]
}
----

As well as for instances:

[source,data]
----
POST /api/instances/201/snapshots
----

[source,json]
----
{
  "action" : "delete",
  "resources" : [
    { "href" : "http://localhost:3000/api/instances/201/snapshots/7" },
    { "href" : "http://localhost:3000/api/instances/201/snapshots/8" }
  ]
}
----
