

[[tenant-management]]
== Tenant Management

Tenant management including CRUD operations is available via the REST API.
Management of tenants is through:

[source,data]
----
/api/tenants
----

* link:#creating-tenants[Creating Tenants]
* link:#editing-tenants[Editing Tenants]
* link:#deleting-tenants[Deleting Tenants]

[[tenant-quota-management]]
== Tenant Quota Management

Tenant Quota management is made available via the _quotas_ subcollection of tenant resources
as follows:

[source,data]
----
/api/tenants/:id/quotas
----

* link:#creating-tenant-quotas[Creating Tenant Quotas]
* link:#editing-tenant-quotas[Editing Tenant Quotas]
* link:#deleting-tenant-quotas[Deleting Tenant Quotas]

[[creating-tenants]]
=== Creating Tenants

Creating a Tenant is done via the *create* action as follows:

----
POST /api/tenants
----

[source,data]
----
{
  "action" : "create",
  "resource" : {
    # New Tenant JSON
  }
}
----

And like other *create* actions, the new tenant data can simply be posted to
the /api/tenants URL.

----
POST /api/tenants
----

[source,data]
----
{
  # New Tenant JSON
}
----

For example, creating a new tenant:

----
POST /api/tenants
----

[source,json]
----
{
  "name" : "Test Tenant",
  "description" : "Test Tenant Description",
  "parent" : { "href" : "http://localhost:3000/api/tenants/1" }
}
----

Parent can be specify by _id_ or _href_

[NOTE]
====
Please refer to the link:../appendices/resource_attributes.html#tenants[Resource Attributes]
page for a list of available attributes when creating Tenants.
====

[[editing-tenants]]
=== Editing Tenants

Editing a Tenant is available via the *edit* action with the *resource* specifying the
attributes to update for that tenant.

----
POST /api/tenants/:id
----

[source,json]
----
{
  "action" : "edit" ,
  "resource" : {
    "description" : "Updated Description for Tenant"
  }
}
----

NOTE: type is a restricted attribute and cannot be edited.

[[deleting-tenants]]
=== Deleting Tenants

Deleting a Tenant is done via the delete method:

----
DELETE /api/tenants/:id
----

or via the *delete* action as follows:

----
POST /api/tenants/:id
----

[source,json]
----
{
  "action" : "delete"
}
----

or by href:

----
POST /api/tenants
----

[source,json]
----
{
  "action" : "delete",
  "resources" : [
    { "href" : "http://localhost:3000/api/tenants/:id" }
  ]
}
----

[[creating-tenant-quotas]]
=== Creating Tenant Quotas

Creating a quota for a specific tenant is done as follows:

----
POST /api/tenants/:id/quotas
----

[source,json]
----
{
  "name" : "cpu_allocated",
  "value" : 1
}
----

[[editing-tenant-quotas]]
=== Editing Tenant Quotas

----
POST /api/tenants/:id/quotas/:quota_id
----

[source,json]
----
{
  "action" : "edit",
  "resource" : {
    "value" : 5
  }
}
----

Multiple quotas for a tenant can also be edited in a single request as follows:

----
POST /api/tenants/1/quotas
----

[source,json]
----
{
  "action" : "edit",
  "resources" : [
    {
      "href" : "http://localhost:3000/api/tenants/1/quotas/5",
      "value" : 11
    },
    { "href" : "http://localhost:3000/api/tenants/1/quotas/6",
      "value" : 12
    },
    ...
  ]
}
----


[[deleting-tenant-quotas]]
=== Deleting Tenant Quotas

Quotas of a tenant can be deleted via the _delete_ action as follows:

----
POST /api/tenants/:id/quotas/:quota_id
----

[source,json]
----
{
  "action" : "delete"
}
----


or via the DELETE HTTP method

----
DELETE /api/tenants/:id/quotas/:quota_id
----

Multiple quotas of a tenant can be deleted in a single request
as shown in the following example:

----
POST /api/tenants/1/quotas
----

[source,json]
----
{
  "action" : "delete",
  "resources" : [
    { "href" : "http://localhost:3000/api/tenants/1/quotas/7" },
    { "href" : "http://localhost:3000/api/tenants/1/quotas/8" },
    ...
  ]
}
----

