
[[vm-management]]
== Virtual Machine Management

Management of virtual machines adds support of the following actions:

[cols="1,3",options="header"]
|=====================
| Action | Description
| start | Starts a virtual machine
| stop | Stops a virtual machine
| suspend | Suspends a virtual machine
| refresh | Refreshes a virtual machine
| retire  | Retires a virtual machine
| reset | Resets a virtual machine
| reboot_guest | Reboots guest in virtual machine
| shutdown_guest | Shuts down guest in virtual machine
| scan | Scans a virtual machine (Perform SmartState Analysis)
| set_miq_server | Sets the server of a virtual machine
| set_owner | Sets the owner of a virtual machine
| add_event | Adding an event to a virtual machine
| add_lifecycle_event | Add a life cycle event to a virtual machine
| edit | Edits a virtual machine
| delete | Deletes a virtual machine in the appliance
|=====================

* link:#targeting-vms[Targeting VMs]
* link:#querying-vms[Querying VMs]
* link:#start-vm[Starting a VM]
* link:#stop-vm[Stopping a VM]
* link:#suspend-vm[Suspending a VM]
* link:#refresh-vm[Refreshing a VM]
* link:#retire-vm[Retiring a VM]
* link:#reset-vm[Resets a VM]
* link:#reboot-guest-vm[Reboots guest in VM]
* link:#shutdown-guest-vm[Shuts down guest in VM]
* link:#scan-vm[Scanning a VM]
* link:#set-miq-server-vm[Setting Server of a VM]
* link:#set-owner-vm[Setting Owner of a VM]
* link:#add-event-vm[Adding an Event to a VM]
* link:#add-lifecycle-event-vm[Adding a Lifecycle Event to a VM]
* link:#edit-vm[Editing a VM]
* link:#delete-vm[Deleting a VM]

[[targeting-vms]]
=== Targeting Virtual Machines

These actions can be triggered on individual virtual machine resources:

[source,data]
----
/api/vms/:id
----

As simply as POSTing the following action to a virtual machine.

[source,json]
----
{
  "action" : "start"
}
----


Requests can also be made on multiple vms by targetting the primary collection:

[source,data]
----
/api/vms
----

[source,json]
----
{
  "action" : "start",
  "resources" : [
    { "href" : "http://localhost:3000/api/vms/11" },
    { "href" : "http://localhost:3000/api/vms/12" },
    ...
  ]
}
----

[[querying-vms]]
=== Querying Virtual Machines

Virtual machines are queried via the primary collection URL:

[source,data]
----
/api/vms
----

Filtering, sorting and paging as mentioned on the
link:../overview/query.html[Querying] page.

When querying vms, expanding the resources themselves
as well as the following subcollections:

|======================
| accounts
| software
|======================

For example:

----
GET /api/vms?expand=resources,accounts,software
----

Or querying an individual virtual machine

----
GET /api/vms/:id?expand=accounts,software
----

[[start-vm]]
=== Starting a Virtual Machine

[source,json]
----
{
  "action" : "start"
}
----

[[stop-vm]]
=== Stopping a Virtual Machine

[source,json]
----
{
  "action" : "stop"
}
----

[[suspend-vm]]
=== Suspending a Virtual Machine

[source,json]
----
{
  "action" : "suspend"
}
----

[[refresh-vm]]
=== Refreshing a Virtual Machine

[source,json]
----
{
  "action" : "refresh"
}
----

[[retire-vm]]
=== Retiring a Virtual Machine

[source,json]
----
{
  "action" : "request_retire"
}
----

[[reset-vm]]
=== Resetting a Virtual Machine

[source,json]
----
{
  "action" : "reset"
}
----

[[reboot-guest-vm]]
=== Rebooting guest in Virtual Machine

[source,json]
----
{
  "action" : "reboot_guest"
}
----

[[shutdown-guest-vm]]
=== Shutting Down Guest in a Virtual Machine

[source,json]
----
{
  "action" : "shutdown_guest"
}
----

[[scan-vm]]
=== Scanning a Virtual Machine

[source,json]
----
{
  "action" : "scan"
}
----

[[set-miq-server-vm]]
=== Setting Server of a Virtual Machine

[source,json]
----
{
  "action" : "set_miq_server",
  "resource" : {
    "miq_server" : { "href" : "http://localhost:3000/api/servers/5" }
  }
}
----

[source,json]
----
{
  "action" : "set_miq_server",
  "resource" : {
    "miq_server" : { "id" : "6" }
  }
}
----

To remove the server from the virtual machine, pass in an empty reference as follows:

[source,json]
----
{
  "action" : "set_miq_server",
  "resource" : {
    "miq_server" : {}
  }
}
----


[[set-owner-vm]]
=== Setting Owner of a Virtual Machine

[source,json]
----
{
  "action" : "set_owner",
  "resource" : {
    "owner" : "admin"
  }
}
----

[[add-event-vm]]
=== Adding an Event to a Virtual Machine

[source,json]
----
{
  "action" : "add_event",
  "resource" : {
    "event_type" : "...",
    "event_message" : "...",
    "event_time" : "UTC Time"
  }
}
----

NOTE: event_time above is optional. If skipped, current time will be used.

[[add-lifecycle-event-vm]]
=== Adding a Lifecycle Event to a Virtual Machine

[source,json]
----
{
  "action" : "add_lifecycle_event",
  "resource" : {
    "event" : "...",
    "status" : "...",
    "message" : "...",
    "created_by" : "..."
  }
}
----

[[edit-vm]]
=== Editing a Virtual Machine

Basic information of virtual machines can be edited. This includes the following:

[options=header,cols="2,4",width=80%]
|======================
| VM Info | Attribute
| description | description
| custom attributes | custom_1 ... custom_9
| parent resource | parent_resource - resource href reference
| child resources | child_resources - array of resource href references
|======================

Virtual machine resources can be edited as follows:

[source,data]
----
POST /api/vms/:id
----

[source,json]
----
{
  "action" : "edit",
  "resource" : {
    "description" : "Updated VM Description",
    "custom_1" : "custom_attribute_1",
    "parent_resource" : { "href" : "http://localhost:3000/api/vms/11" },
    "child_resources" : [
      { "href" : "http://localhost:3000/api/vms/101" },
      { "href" : "http://localhost:3000/api/vms/102" },
      { "href" : "http://localhost:3000/api/vms/103" },
      { "href" : "http://localhost:3000/api/vms/104" }
    ]
  }
}
----

Virtual machines can also be edited in bulk as follows:

[source,data]
----
POST /api/vms
----

[source,json]
----
{
  "action" : "edit",
  "resources" : [
    {
      "href" : "http://localhost:3000/api/vms/11",
      "custom_9" : "vm_class_a"
    },
    {
      "href" : "http://localhost:3000/api/vms/12",
      "custom_9" : "vm_class_a"
    },
    {
      "href" : "http://localhost:3000/api/vms/13",
      "custom_9" : "vm_class_a"
    }
  ]
}
----


[[delete-vm]]
=== Deleting a Virtual Machine

[source,json]
----
{
  "action" : "delete"
}
----

Or simply doing the following:

----
DELETE /api/vms/:id
----

See the main REST API examples section for additional virtual machine management examples.

