[[settings-overview]]
== Settings Overview

The settings menu is located at the top right of the {product-title} user interface.

To view or modify global settings for your appliance, click your username to open the settings dropdown menu, and click *My Settings* to modify.
The availability of each menu item depends on the role assigned to your user account. For more information on roles, see xref:roles[].

The following is a list of the menu items available from the settings menu:

* *My Settings* 
+
This menu is available to all {product-title} users. The settings in this menu control how elements in the user interface are displayed, time profiles, and tags for the currently logged-in individual user.
+
* *Tasks*
+
This menu allows you to view virtual machine SmartState Analysis tasks that can be tracked through the console. The status of each task is displayed, including time started, time ended, what part of the task is currently running, and any errors encountered. 
+
* *Configuration*
+
This menu allows you to specify enterprise, region, zone, and server settings for your {product-title} infrastructure. Diagnostics such as logs and the status of processes are also shown here. The *Configuration* menu is available only to super administrators and administrators.


