[[settings-overview]]
== Settings Overview

To view or modify global settings for your appliance, hover over the *Settings* menu and click the sub-tab *My Settings* to modify.
The availability of each sub-tab depends on the role assigned to your user account. For more information on roles, see xref:roles[].

The following is a list of the sub-tabs available from the *Settings* menu:

* *My Settings* 
+
This menu is available to all {product-title} users. The settings in this menu control how elements in the user interface are displayed, time profiles, and tags for the currently logged-in individual user.
+
* *Tasks*
+
This menu allows you to view virtual machine SmartState Analysis tasks that can be tracked through the console. The status of each task is displayed, including time started, time ended, what part of the task is currently running, and any errors encountered. 
+
* *Configuration*
+
This menu allows you to specify enterprise, region, zone, and server settings for your {product-title} infrastructure. Diagnostics such as logs and the status of processes are also shown here.
+
* *About* 
+
This menu provides information about the session of the logged-in user, and links to product documentation and the Red Hat Customer Portal.
+



