[[tasks]]
== Tasks

The options under the *Tasks* menu allow you to view and control currently running tasks in {product-title}. The status of each task is displayed, including time started, time ended, what part of the task is currently running, and any errors encountered. 

[[my-vm-and-container-analysis-tasks]]
=== My VM and Container Analysis Tasks

The *My VM and Container Analysis Tasks* menu allows you to view all tasks running on virtual machines and containers for the currently logged-in user.

From the *My VM and Container Analysis Tasks* menu, you can:

* See jobs that the logged on user created for the SmartProxy either through a schedule or by manually initiating a SmartState Analysis of a virtual machine or container.
* See if a job completed successfully, resulted in an error, or is running.
* See the reason for an error.
* Filter the tasks by status and state.
* View the owner or host of the virtual machine or container referenced.
* Delete a task either explicitly or older than another task. 

[[filtering-the-vm-and-container-analysis-task-list]]
==== Filtering the VM and Container Analysis Task List

This procedure describes how to filter the virtual machine and container analysis task list. You can filter the task list by zone, time period, task status, and task state.

To filter the virtual machine and container analysis task list:

. From the settings menu, select *Tasks*.
. Click *My VM and Container Analysis Tasks*.
. From the *Zone* list, select a specific zone, or select *<All Zones>*.
. From the *24 Hour Time Period* list, select the period of time to view the tasks.
. For *Task Status*, select the check boxes next to the status to view.
. From the *Tasks State* list, select the state to view.
. Click *Apply*. 

[[deleting-a-task-from-the-vm-and-container-analysis-task-list]]
==== Deleting a Task from the VM and Container Analysis Task List

To delete a task from the list of virtual machine and container analysis tasks:

. From the settings menu, select *Tasks*.
. Click *My VM and Container Analysis Tasks*.
. Select the tasks to delete. From the *Delete* menu:
.. Click *Delete* to delete the selected tasks.
.. Click *Delete Older* to delete the tasks older than the selected tasks.
.. Click *Delete All* to delete all tasks. 
. Click *OK*. 

[[my-other-ui-tasks]]
=== My Other UI Tasks

The *My Other UI Tasks* menu allows you to view all tasks running in the user interface for the currently logged-in user.

[[filtering-the-my-other-ui-tasks-list]]
==== Filtering the My Other UI Tasks List

This procedure describes how to filter the user interface analysis task list. You can filter the task list by time period, task status, and task state.

To filter the other user interface task list:

. From the settings menu, select *Tasks*.
. Click *My Other UI Tasks*.
. From the *24 Hour Time Period* list, select the period of time to view the tasks.
. For *Task Status*, select the check boxes next to the status to view.
. From the *Tasks State* list, select the state to view.
. Click *Apply*.

[[deleting-a-my-other-ui-task]]
==== Deleting a My Other UI Task

To delete a task from the list of other user interface tasks:

. From the settings menu, select *Tasks*.
. Click *My Other UI Tasks*.
. Select the tasks to delete. From the *Delete* menu:
.. Click *Delete* to delete the selected tasks.
.. Click *Delete Older* to delete the tasks older than the selected tasks.
.. Click *Delete All* to delete all tasks.
. Click *OK*.

[[all-vm-and-container-analysis-tasks]]
=== All VM and Container Analysis Tasks

The *All VM and Container Analysis Tasks* menu allows you to view all tasks running on virtual machines and containers for all users.

From the *All VM and Container Analysis Tasks* menu, you can:

* See jobs that all users have created for the SmartProxy either through a schedule or by manually initiating a SmartState Analysis of a virtual machine or container.
* See if a job completed successfully, resulted in an error, or is running.
* See the reason for an error.
* Filter the tasks by status and state.
* View the owner or host of the virtual machine or container referenced.
* Delete a task either explicitly or older than another task.

[[filtering-the-vm-and-container-analysis-task-list-1]]
==== Filtering the VM and Container Analysis Task List

This procedure describes how to filter virtual machine analysis task lists. You can filter the task list by zone, time period, task status, and task state.

To filter the virtual machine and container analysis task list:

. From the settings menu, select *Tasks*.
. Click *All VM and Container Analysis Tasks*.
. From the *Zone* list, select a specific zone, or select *<All Zones>*.
. From the *24 Hour Time Period* list, select the period of time to view the tasks.
. For *Task Status*, select the check boxes next to the status to view.
. From the *Tasks State* list, select the state to view.
. Click *Apply*.

[[deleting-a-vm-and-container-analysis-task]]
==== Deleting a VM and Container Analysis Task

To delete a task from the list of all virtual machine and container analysis tasks:

. From the settings menu, select *Tasks*.
. Click *All VM and Container Analysis Tasks*.
. Select the tasks to delete. From the *Delete* menu:
.. Click *Delete* to delete the selected tasks.
.. Click *Delete Older* to delete the tasks older than the selected tasks.
.. Click *Delete All* to delete all tasks.
. Click *OK*.

[[all-other-tasks]]
=== All Other Tasks

The *All Other Tasks* menu allows you to view all tasks for all users. This menu is only accessible when you are logged in as the *admin* user.

[[filtering-the-all-other-tasks-list]]
==== Filtering the All Other Tasks List

This procedure describes how to filter the list of all other tasks. You can filter the task list by time period, task status, and task state.

To filter the all other tasks list:

. From the settings menu, select *Tasks*.
. Click *All Other Tasks*.
. From the *24 Hour Time Period* list, select the period of time to view the tasks.
. For *Task Status*, select the check boxes next to the status to view.
. From the *Tasks State* list, select the state to view.
. Click *Apply*.

[[deleting-a-task-from-the-all-other-tasks-list]]
==== Deleting a Task from the All Other Tasks List

To delete a task from the list of all other tasks:

. From the settings menu, select *Tasks*.
. Click *All Other Tasks*.
. Select the tasks to delete. From the *Delete* menu:
.. Click *Delete* to delete the selected tasks.
.. Click *Delete Older* to delete the tasks older than the selected tasks.
.. Click *Delete All* to delete all tasks.
. Click *OK*.



