Policies
--------

Policies are used to manage your virtual environment. There are two
types of policies available: compliance and control. Compliance policies
are used to harden your virtual infrastructure, making sure that your
security requirements are adhered to. Control policies are used to check
for a specific condition and perform an action based on the outcome. For
example:

* Prevent virtual machines from running without an administrator
account.
* Prevent virtual machines from starting if certain patches are not
applied.
* Configure the behavior of a production virtual machine to only start
if it is running on a production host.
* Force a SmartState Analysis when a host is added or removed from a
cluster.

=== Control Policies

A control policy is a combination of an event, a condition, and an
action. This combination provides management capabilities in your
virtual environment.

* An event is a trigger to check a condition.
* A condition is a test triggered by an event.
* An action is an execution that occurs if a condition is met.

include::topics/To_create_a_Control_Policy.adoc[]

include::topics/Editing_Basic_Info_Scope_and_Notes_for_a_Policy.adoc[]

include::topics/Copying_a_Policy.adoc[]

include::topics/Deleting_a_Policy.adoc[]

include::topics/Creating_a_new_Policy_Condition.adoc[]

include::topics/Editing_Policy_Condition_Assignments.adoc[]

include::topics/Editing_Policy_Event_Assignments.adoc[]

include::topics/To_assign_an_Action_to_an_Event.adoc[]

=== Compliance Policies

Compliance policies are specifically designed to secure your environment
by checking conditions that you create. These conditions can include the
same conditions that you would use in a control policy, and most of the
procedures are the same. However, a compliance policy automatically
assigns the mark as a compliant action when the virtual machine or host
passes all of the conditions. If any of the conditions are not met, then
the virtual machine or host is marked as non-compliant. The compliance
status is shown in the summary screen for the virtual machine or host
and on the compare and drift screens.

include::topics/To_create_a_compliance_Policy.adoc[]

include::topics/To_create_a_Condition_to_check_file_contents_of_a_host.adoc[]

==== Checking for Compliance

After you have created your compliance policies and assigned them to a
policy profile, you can check compliance in two ways. You can either
schedule the compliance check or perform the check directly from the
summary screen.

The compliance check runs all compliance policies that are assigned to
the host or virtual machine. If the item fails any of the checks, it is
marked as non-compliant in the item's summary screen.

[NOTE]
======
To schedule, you must have `EvmRole-administrator` access to the
{product-title} server.
======

include::topics/To_schedule_a_Compliance_check.adoc[]

include::topics/To_check_a_Virtual_Machine_for_Compliance_from_the_Summary_Screen.adoc[]

include::topics/To_check_a_Host_for_Compliance_from_the_Summary_Screen.adoc[]
