[[database_failover]]
== Configuring Database Failover

The failover monitor daemon must run on all of the non-database {product-title_short} appliances to check for failures. In case of a database failure, it modifies the database configuration accordingly.

[IMPORTANT]
====
This configuration is crucial for high availability to work in your environment. If the database failover monitor is not configured, the standby database-only appliance will not react and take over operations in case of a primary database failure. 
====

[[failover_monitor]]
=== Configuring the Failover Monitor

Configure the failover monitor only on the non-database {product-title_short} appliances  with the following steps:

. In the appliance console menu, select *Configure Application Database Failover Monitor*. 
. Select *Start Database Failover Monitor*.



[[failover_testing]]
=== Testing Database Failover

Test that failover is working correctly between your databases with the following steps:

. Simulate a failure by stopping the database on the primary server:
+
----
# systemctl stop rh-postgresql95-postgresql
----
+ 
. To check the status of the database, run:
+
----
# systemctl status rh-postgresql95-postgresql
----
+
[NOTE]
====
You can check the status of the simulated failure by viewing the most recent `ha_admin.log` log on the engine appliances: 
----
# tail -f /var/www/miq/vmdb/log/ha_admin.log
----
====
+
. Check the appliance console summary screen for the primary database. If configured correctly, the *{product-title_abbr_uc} Database* value in the appliance console summary should have switched from the hostname of the old primary database to the hostname of the new primary on all {product-title_short} appliances.


[IMPORTANT]
====
Upon database server failover, the standby server becomes the primary. However, the failed node cannot switch to standby automatically and must be manually configured. Data replication from the new primary to the failed and recovered node does not happen by default, so the failed node must be reintroduced into the configuration.
====


[[reintroducing_the_failed_node]]
=== Reintroducing the Failed Node

Manual steps are required to reintroduce the failed primary database node back into the cluster as a standby. This allows for greater control over the configuration, and to diagnose the failure.

To reintroduce the failed node reinitialize the standby database as described in xref:configuring_standby_db[].

Your {product-title_short} environment is now re-configured for high availability.
