[[installation]]
== Installing the Appliances

This chapter outlines the steps for installing and configuring the {product-title} components needed for high availability: a database cluster comprised of primary and standby database-only appliances, and two standard appliances.

[[installation_primary_db]]
=== Installing the Primary Database Appliance

The primary database appliance functions as an external database to the standard {product-title_short} appliances.

. Deploy a {product-title_short} appliance with an extra partition for the database at a size appropriate for your deployment. For recommendations on disk space, see https://access.redhat.com/documentation/en/red-hat-cloudforms/4.2/paged/deployment-planning-guide/chapter-2-planning[Planning] in the _Deployment Planning Guide_.
. Configure time synchronization on the appliance:
.. Edit `/etc/chronyd.conf` with valid NTP server information.
.. Re-synchronize time information across the appliances:
+
------
# systemctl enable chronyd.service
# systemctl start chronyd.service
------
+
. SSH into the {product-title_short} appliance to enter the appliance console.
. Configure the hostname by selecting *Set Hostname*.
. Configure networking as desired by selecting the *Set DHCP Network Configuration* or *Set Static Network Configuration* option.
. Select *Configure Database*.
. Select *Create key* to create the encryption key. You can create a new key, or use an existing key on your system by selecting *Fetch key from remote machine* and following the prompts.
. Select *Create Internal Database*.
. Select the database disk. {product-title_short} then activates the configuration.
. For *Should this appliance run as a standalone database server?*, select `Y`. Selecting this option configures this appliance as a database appliance only, and therefore `evmserverd` processes will not run. 
+
[WARNING]
====
This configuration is not reversible.
====
+
. Create the database password.

[NOTE]
====
Do not create a region at this stage in the procedure.
====

You can check the configuration on the appliance console details screen. If configured successfully, *Local Database Server* shows as `running (primary)`.


[[configuring_primary_db]]
=== Configuring the Primary Database Appliance

On the primary database appliance, initialize the nodes in the database cluster to configure the database replication:

. In the appliance console menu, select *Configure Database Replication*. 
. Select *Configure Server as Primary*.
. Set an unique identifier number for the server and enter the database name and credentials:
.. Select a number to uniquely identify the node in the replication cluster.
.. Enter the cluster database name.
.. Enter the cluster database username.
.. Enter the cluster database password and confirm the password.
.. Enter the primary database appliance hostname or IP address.
+
[NOTE]
====
The hostname must be visible to all appliances that communicate with this database, including the standard appliances and any global region databases.
====
+
.. Confirm that the replication server configuration details are correct, and select `y` to apply the configuration.


[[installation_standard_appliance]]
=== Installing a Standard {product-title} Appliance

Configure a standard {product-title_short} appliance to point to the primary database server. This appliance does not serve as a database server. From the standard appliance, you can then configure the database itself.

. Deploy a {product-title_short} appliance with an extra partition for the database at a size appropriate for your deployment. For recommendations on disk space, see https://access.redhat.com/documentation/en/red-hat-cloudforms/4.2/paged/deployment-planning-guide/chapter-2-planning[Planning] in the _Deployment Planning Guide_.
. Configure time synchronization on the appliance:
.. Edit `/etc/chronyd.conf` with valid NTP server information.
.. Re-synchronize time information across the appliances:
+
------
# systemctl enable chronyd.service
# systemctl start chronyd.service
------
+
. SSH into the {product-title_short} appliance to enter the appliance console.
. Configure the hostname by selecting *Set Hostname*.
. Configure networking as desired by selecting the *Set DHCP Network Configuration* or *Set Static Network Configuration* option.
. Select *Configure Database*.
. Configure this appliance to use the encryption key from the primary database appliance:
.. For *Encryption Key*, select *Fetch key from remote machine*.
.. Enter the hostname for the primary database appliance you previously configured containing the encryption key.
.. Enter the primary database appliance's username.
.. Enter the primary database appliance's password.
.. Enter the path of the remote encryption key. (For example, `/var/www/miq/vmdb/certs/v2_key`.)
. Configure the database:
.. Select *Create Region in External Database*, since the database is external to the appliances.
+
[IMPORTANT]
====
Creating a database region will destroy any existing data and cannot be undone.
====
+
.. Provide the primary database appliance as the remote key location and its credentials.
.. Assign a unique database region number. Note that creating a database region will destroy any existing data and cannot be undone.
.. For *Are you sure you want to continue?* Select `y`.
. Enter the primary database appliance's name and access details:
.. Enter the hostname for the primary database appliance.
.. Enter a name to identify the database.
.. Enter the primary database appliance's username.
.. Enter a password for the database and confirm the password.

You can check the configuration on the appliance console details screen. When configured successfully, *{product-title_abbr_uc} Server* will show as `running`, and *{product-title_abbr_uc} Database* will show the name of the primary database appliance.


[[installation_standby_db]]
=== Installing the Standby Database Appliance

The standby database appliance is a copy of the primary database appliance and takes over the role of primary database in case of failure.

. Deploy a {product-title_short} appliance with an extra partition for the database at a size appropriate for your deployment. For recommendations on disk space, see https://access.redhat.com/documentation/en/red-hat-cloudforms/4.2/paged/deployment-planning-guide/chapter-2-planning[Planning] in the _Deployment Planning Guide_.
. Configure time synchronization on the appliance:
.. Edit `/etc/chronyd.conf` with valid NTP server information.
.. Re-synchronize time information across the appliances:
+
------
# systemctl enable chronyd.service
# systemctl start chronyd.service
------
+
. SSH into the {product-title_short} appliance to enter the appliance console.
. Configure the hostname by selecting *Set Hostname*.
. Configure networking as desired by selecting the *Set DHCP Network Configuration* or *Set Static Network Configuration* option.


[[configuring_standby_db]]
=== Configuring the Standby Database Appliance

The steps to configure the standby database appliance are similar to that of the primary database appliance, in that they prepare the appliance to be database-only, but as the standby.

[NOTE]
====
The current {product-title_short} version contains a known limitation when configuring a dedicated database disk from the appliance console menu.

To work around this, create and mount the dedicated database partition manually with the same information from the primary database, before configuring the standby database appliance as below.
See https://bugzilla.redhat.com/show_bug.cgi?id=1412940 for more information.
====

On the standby database appliance, configure the following:

. In the appliance console menu, select *Configure Database Replication*. 
. Select *Configure Server as Standby*.
. Set an unique identifier number for the standby server and enter the database name and credentials:
.. Select a number to uniquely identify the node in the replication cluster.
.. Enter the cluster database name.
.. Enter the cluster database username.
.. Enter the cluster database password.
.. Enter the primary database appliance hostname or IP address.
.. Enter the standby database appliance hostname or IP address.
+
[NOTE]
====
The hostname must be visible to all appliances that communicate with this database, including the engine appliances and any global region databases.
====
+
.. Select `y` to configure the replication manager for automatic failover.
.. Confirm that the replication standby server configuration details are correct, and select `y` to apply the configuration.

The standby server will then run an initial synchronization with the primary database, and start locally in standby mode.

Verify the configuration on the appliance console details screen for the standby server. When configured successfully, *Local Database Server* shows as `running (standby)`. 


[[installation_standard_appliances_addl]]
=== Installing Additional {product-title} Appliances

Install a second virtual machine with a standard {product-title_short} appliance and any additional appliances in the region using the following steps:


. Deploy a {product-title_short} appliance with an extra partition for the database at a size appropriate for your deployment. For recommendations on disk space, see https://access.redhat.com/documentation/en/red-hat-cloudforms/4.2/paged/deployment-planning-guide/chapter-2-planning[Planning] in the _Deployment Planning Guide_.
. Configure time synchronization on the appliance:
.. Edit `/etc/chronyd.conf` with valid NTP server information.
.. Re-synchronize time information across the appliances:
+
------
# systemctl enable chronyd.service
# systemctl start chronyd.service
------
+
. SSH into the {product-title_short} appliance to enter the appliance console.
. Configure the hostname by selecting *Set Hostname*.
. Configure networking as desired by selecting the *Set DHCP Network Configuration* or *Set Static Network Configuration* option.
. Select *Configure Database*.
. Configure this appliance to use the encryption key from the primary database appliance:
.. For *Encryption Key*, select *Fetch key from remote machine*.
.. Enter the hostname for the primary database appliance you previously configured containing the encryption key.
.. Enter the primary database appliance's username.
.. Enter the primary database appliance's password.
.. Enter the path of the remote encryption key. (For example, `/var/www/miq/vmdb/certs/v2_key`.)
.. Select *Join Region in External Database* from the appliance console menu.
. Enter the primary database appliance's name and access details:
.. Enter the hostname for the primary database appliance.
.. Enter a name to identify the database.
.. Enter the primary database appliance's username.
.. Enter a password for the database and confirm the password.


