[[installation]]
== Installing the Appliances

This chapter outlines the steps for installing and configuring the {product-title} components needed for high availability: a database cluster comprised of primary and standby database-only appliances, and two {product-title_short} appliances.

[[installation_primary_db]]
=== Installing the Primary Database-Only Appliance

The primary database-only appliance functions as an external database to the {product-title_short} appliances.

. Deploy a {product-title_short} appliance with an extra partition for the database at a size appropriate for your deployment. For recommendations on disk space, see https://access.redhat.com/documentation/en/red-hat-cloudforms/4.2/paged/deployment-planning-guide/chapter-2-planning[Planning] in the _Deployment Planning Guide_.
. Configure time synchronization on the appliance:
.. Edit `/etc/chronyd.conf` with valid NTP server information.
.. Re-synchronize time information across the appliances:
+
------
# systemctl enable chronyd.service
# systemctl start chronyd.service
------
+
. SSH into the {product-title_short} appliance to enter the appliance console.
. Configure the hostname by selecting *Set Hostname*.
. Configure networking as desired by selecting the *Set DHCP Network Configuration* or *Set Static Network Configuration* option.
. Select *Configure Database*.
. Select *Create key* to create the encryption key. You can create a new key, or use an existing key on your system by selecting *Fetch key from remote machine* and following the prompts.
. Select *Create Internal Database*.
. Select the database disk. {product-title_short} then activates the configuration.
. For *Should this appliance run as a standalone database server?*, select `Y`. Selecting this option configures this appliance as a database-only appliance, and therefore the {product-title_abbr_uc} application and `evmserverd` processes will not run. This is required in highly available database deployments.
+
[WARNING]
====
This configuration is not reversible.
====
+
. Create the database password.

[NOTE]
====
Do not create a region at this stage in the procedure.
====

You can check the configuration on the appliance console details screen. If configured successfully, *Local Database Server* shows as `running (primary)`.


[[configuring_primary_db]]
=== Configuring the Primary Database-Only Appliance

On the primary database-only appliance, initialize the nodes in the database cluster to configure the database replication:

. In the appliance console menu, select *Configure Database Replication*. 
. Select *Configure Server as Primary*.
. Set an unique identifier number for the server and enter the database name and credentials:
.. Select a number to uniquely identify the node in the replication cluster.
.. Enter the cluster database name.
.. Enter the cluster database username.
.. Enter the cluster database password and confirm the password.
.. Enter the primary database-only appliance hostname or IP address.
+
[NOTE]
====
The hostname must be visible to all appliances that communicate with this database, including the {product-title_short} appliances and any global region databases.
====
+
.. Confirm that the replication server configuration details are correct, and select `y` to apply the configuration.


[[installation_appliance]]
=== Installing a {product-title_short} Appliance

Configure a {product-title_short} appliance to point to the primary database server. This appliance does not serve as a database server. From this appliance, you can then configure the database itself.

[NOTE]
====
After installing and configuring an empty database appliance in xref:installation_primary_db[] and xref:configuring_primary_db[], the steps in this section create the database schema used by {product-title_short} on the primary database appliance, and prepare the initial data. This must be completed before the secondary database server can be configured in xref:installation_standby_db[].
====

. Deploy a {product-title_short} appliance with an extra partition for the database at a size appropriate for your deployment. For recommendations on disk space, see https://access.redhat.com/documentation/en/red-hat-cloudforms/4.2/paged/deployment-planning-guide/chapter-2-planning[Planning] in the _Deployment Planning Guide_.
. Configure time synchronization on the appliance:
.. Edit `/etc/chronyd.conf` with valid NTP server information.
.. Re-synchronize time information across the appliances:
+
------
# systemctl enable chronyd.service
# systemctl start chronyd.service
------
+
. SSH into the {product-title_short} appliance to enter the appliance console.
. Configure the hostname by selecting *Set Hostname*.
. Configure networking as desired by selecting the *Set DHCP Network Configuration* or *Set Static Network Configuration* option.
. Select *Configure Database*.
. Configure this appliance to use the encryption key from the primary database-only appliance:
.. For *Encryption Key*, select *Fetch key from remote machine*.
.. Enter the hostname for the primary database-only appliance you previously configured containing the encryption key.
.. Enter the primary database-only appliance's username.
.. Enter the primary database-only appliance's password.
.. Enter the path of the remote encryption key. (For example, `/var/www/miq/vmdb/certs/v2_key`.)
. Configure the database:
.. Select *Create Region in External Database*, since the database is external to the appliances.
+
[IMPORTANT]
====
Creating a database region will destroy any existing data and cannot be undone.
====
+
.. Provide the primary database-only appliance as the remote key location and its credentials.
.. Assign a unique database region number. Note that creating a database region will destroy any existing data and cannot be undone.
.. For *Are you sure you want to continue?* Select `y`.
. Enter the primary database-only appliance's name and access details:
.. Enter the hostname for the primary database-only appliance.
.. Enter a name to identify the database.
.. Enter the primary database-only appliance's username.
.. Enter a password for the database and confirm the password.

You can check the configuration on the appliance console details screen. When configured successfully, *{product-title_abbr_uc} Server* will show as `running`, and *{product-title_abbr_uc} Database* will show the name of the primary database-only appliance.


[[installation_standby_db]]
=== Installing the Standby Database-Only Appliance

The standby database-only appliance is a copy of the primary database-only appliance and takes over the role of primary database in case of failure.

. Deploy a {product-title_short} appliance with an extra partition for the database that is the same size as the primary database-only appliance, as it will contain the same data. For recommendations on disk space, see https://access.redhat.com/documentation/en/red-hat-cloudforms/4.2/paged/deployment-planning-guide/chapter-2-planning[Planning] in the _Deployment Planning Guide_.
. Configure time synchronization on the appliance:
.. Edit `/etc/chronyd.conf` with valid NTP server information.
.. Re-synchronize time information across the appliances:
+
------
# systemctl enable chronyd.service
# systemctl start chronyd.service
------
+
. SSH into the {product-title_short} appliance to enter the appliance console.
. Configure the hostname by selecting *Set Hostname*.
. Configure networking as desired by selecting the *Set DHCP Network Configuration* or *Set Static Network Configuration* option.


[[configuring_standby_db]]
=== Configuring the Standby Database-Only Appliance

The steps to configure the standby database-only appliance are similar to that of the primary database-only appliance, in that they prepare the appliance to be database-only, but as the standby.

[NOTE]
====
The current {product-title_short} version contains a known limitation when configuring a dedicated database disk from the appliance console menu.

To work around this, create and mount the dedicated database partition manually with the same information from the primary database, before configuring the standby database-only appliance as below.
See https://bugzilla.redhat.com/show_bug.cgi?id=1412940 for more information.
====

On the standby database-only appliance, configure the following:

. In the appliance console menu, select *Configure Database Replication*. 
. Select *Configure Server as Standby*.
. Set an unique identifier number for the standby server and enter the database name and credentials:
.. Select a number to uniquely identify the node in the replication cluster.
.. Enter the cluster database name.
.. Enter the cluster database username.
.. Enter the cluster database password.
.. Enter the primary database-only appliance hostname or IP address.
.. Enter the standby database-only appliance hostname or IP address.
+
[NOTE]
====
The hostname must be visible to all appliances that communicate with this database, including the engine appliances and any global region databases.
====
+
.. Select `y` to configure the replication manager for automatic failover.
.. Confirm that the replication standby server configuration details are correct, and select `y` to apply the configuration.

The standby server will then run an initial synchronization with the primary database, and start locally in standby mode.

Verify the configuration on the appliance console details screen for the standby server. When configured successfully, *Local Database Server* shows as `running (standby)`. 


[[installation_appliances_addl]]
=== Installing Additional {product-title_short} Appliances

Install a second virtual machine with a {product-title_short} appliance and any additional appliances in the region using the following steps:


. Deploy a {product-title_short} appliance with an extra partition for the database at a size appropriate for your deployment. For recommendations on disk space, see https://access.redhat.com/documentation/en/red-hat-cloudforms/4.2/paged/deployment-planning-guide/chapter-2-planning[Planning] in the _Deployment Planning Guide_.
. Configure time synchronization on the appliance:
.. Edit `/etc/chronyd.conf` with valid NTP server information.
.. Re-synchronize time information across the appliances:
+
------
# systemctl enable chronyd.service
# systemctl start chronyd.service
------
+
. SSH into the {product-title_short} appliance to enter the appliance console.
. Configure the hostname by selecting *Set Hostname*.
. Configure networking as desired by selecting the *Set DHCP Network Configuration* or *Set Static Network Configuration* option.
. Select *Configure Database*.
. Configure this appliance to use the encryption key from the primary database-only appliance:
.. For *Encryption Key*, select *Fetch key from remote machine*.
.. Enter the hostname for the primary database-only appliance you previously configured containing the encryption key.
.. Enter the primary database-only appliance's username.
.. Enter the primary database-only appliance's password.
.. Enter the path of the remote encryption key. (For example, `/var/www/miq/vmdb/certs/v2_key`.)
.. Select *Join Region in External Database* from the appliance console menu.
. Enter the primary database-only appliance's name and access details:
.. Enter the hostname for the primary database-only appliance.
.. Enter a name to identify the database.
.. Enter the primary database-only appliance's username.
.. Enter a password for the database and confirm the password.



