[[updating-ha]]
== Applying Updates in a High Availability Environment

Applying minor updates and errata to appliances in a high availability environment must be performed in a specific order to avoid a database migration (to the next major version?).

//////
Later, link to migrating a HA environment in the migration guide.
//////

.Prerequisites

Ensure each appliance is registered to Red Hat Subscription Manager in order to access updates.

To verify if your appliance is registered and subscribed to the correct update channels, run:
//Test on an appliance to see what the output looks like.
----
# yum repolist
----

Appliances must be subscribed to the following channels:

* `cf-me-5.7-for-rhel-7-rpms`
* `rhel-7-server-rpms`
* `rhel-server-rhscl-7-rpms`

If any appliance shows it is not registered or is missing a subscription to any of these channels, see _Registering and Updating {product-title}_ in https://access.redhat.com/documentation/en-us/red_hat_cloudforms/4.2/html-single/general_configuration/[General Configuration] to register the appliance.

.Updating the Appliances

Follow this procedure to update the environment with platform updates, but without performing a database migration:

. Power off the {product-title_short} appliances.
. Power off the database-only (VMDB) appliances.
. Back up each appliance:
// Q: Same as in 1.2 Back Up Current Appliances, steps 1-3?
// https://access.redhat.com/documentation/en-us/red_hat_cloudforms/4.2/html/migrating_to_red_hat_cloudforms_4.2/index#back_up_current_appliances Same method for non-DB and database-only appliances? 
.. Back up the database of your appliance. Take a snapshot if possible.
.. Back up the following files for disaster recovery, noting which appliance each comes from:
  * `/var/www/miq/vmdb/GUID`
  * `/var/www/miq/vmdb/REGION`
.. Note the hostnames and IP addresses of each appliance. This information is available on the summary screen of the appliance console.
. Start each database-only (VMDB) appliance.
. Start each {product-title_short} appliance again, and stop `evmserverd` on each just after boot:
+
------
# systemctl stop evmserverd
------
+
[NOTE]
====
This step is not required on the database-only appliances, as `evmserverd` does not run on them.
====
+
. Apply updates to each appliance by running: 
//(Q: Is there an order to which appliances you update first?) On each appliance, run:
+
------
# yum update
------
+
//Q: Where does the below step go?
. On one of the {product-title_short} (non-database) appliances, apply any database migration updates and reset the Red Hat and ManageIQ automation domains:
+
------
# vmdb
# rake db:migrate
# rake evm:automate:reset
------
+
. Power off the {product-title_short} appliances. 
. Reboot the databases (database appliances?).
. Wait five minutes, then start the {product-title_short} appliances again.

The appliances in your high availability environment are now up to date.

